### ISSUE TITLE
(Special) characters in macro textarea

### ISSUE THREAD

**Issue by PvanGeffen** [umbraco/Umbraco-CMS#7416] opened 2020-01-06 09:57 UTC
If i put some basic (special) characters like a single quote ('), double qoute (") or an ampersand (&) it doesn't get rendered correct on the front end.

## Umbraco version

I am seeing this issue on Umbraco version: 8.3.0

Reproduction
------------

**Comment by kjac** [comment] 2020-01-07 06:40
Hi @PvanGeffen - looks like you accidentally created two issues here. I'm closing this as a duplicate of #7417

**Closed by kjac** 2020-01-07 06:40 UTC
