### ISSUE TITLE
V8.7RC Block List config, settings model not visible

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8759] opened 2020-08-29 13:24 UTC
When adding a settings document type, the type is not visible in the config screen. The same bug was encountered in umbraCoffee, but apparently isn't fixed yet.

![image](https://user-images.githubusercontent.com/3726467/91637835-8ed3b380-ea0b-11ea-9e88-65a133e813cf.png)

This one is from b2b9acf540c9a8d69b9bddf0542f57a6aad6d8c1

If you close the config dialog and open it again, the settings model is visible. So apparently only invisible when you have just added it.

**Comment by nul800sebastiaan** [comment] 2020-09-01 14:49
Thanks @skttl! This seems to have been fixed in the mean time, I've tried every possible combination of creating a new one that I could think of and can't reproduce any more.

If you think it's still a problem in the latest (https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=46887&view=artifacts&type=publishedArtifacts) then let us know, maybe I missed a test.

**Closed by nul800sebastiaan** 2020-09-01 14:49 UTC
