### ISSUE TITLE
Date Picker not showing the stored date value in the calendar

### ISSUE THREAD

**Issue by richard-arkom** [umbraco/Umbraco-CMS#14707] opened 2023-08-22 10:28 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

Date Picker window does not go to the correct date when you go to the content page.

![image](https://github.com/umbraco/Umbraco-CMS/assets/94534018/e11f38f2-036a-4d6f-9cf3-75f7b7aa1290)

### Specifics

Our language is set to English (United States) en-US

I have tried with the language set to English (United Kingdom), but the results are the same

### Steps to reproduce

1.	In settings, change Date Picker data type from ‘YYYY-DD-MM to ‘DD-MM-YYYY’
2.	Go to a content page which uses the Date Picker 
3.	The date box shows the correct date.  26-10-2021
4.	But if you click on the picker to select a new date, it jumps to January 1st of that year 
5.	If you re-select the correct date, and then re-click the date picker it shows the correct date in the picker. 
6.	Save and Publish
7.	Go to another page.
8.	Go back to the original article
9.	Again shows the correct date in the date box
10.	But if you click on the picker to select a new date, it jumps to January 1st of that year again. 

### Expected result / actual result

Expected result: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/94534018/d5658ca9-4692-4edb-9ab6-b7ea771fee99)

Actual result: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/94534018/3d5d57d1-2c8f-4626-b5b1-513602466508)

**Comment by Zeegaan** [comment] 2023-08-22 11:14
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/13403, thanks for reporting this, always great with extra information!

**Closed by Zeegaan** 2023-08-22 11:14 UTC
Labels: type/bug

**Comment by richard-arkom** [comment] 2023-08-22 11:51
Hi,

The original issue #13403<https://github.com/umbraco/Umbraco-CMS/issues/13403> was reported nearly a year ago.

A basic date picker not working correctly for MM-DD-YYYY is quite fundamental from a UX point of view.

Any chance of this being fixed sometime soon, do we know if it is still an issue in Umbraco 11 or 12 ?

Thanks
Rich

**Comment by Zeegaan** [comment] 2023-08-28 07:18
@richard-arkom Just as an update, the issue has been marked as up for grabs for now, as we'd love some help with this 🙌
