### ISSUE TITLE
v8 Rich text editor source code viewer too small, button in a weird place on toolbar

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4451] opened 2019-02-06 15:20 UTC
See screenshot below, I will be doing a LOT of horizontal scrolling to edit the source :)

Also the "view source" button is in the middle of the toolbar (see red arrow) but I'd expect it to be the first one, that's what it looks like when I configure the toolbar at least.

![image](https://user-images.githubusercontent.com/304656/52351309-cb574d00-2a2a-11e9-9170-e2111055bf94.png)

Toolbar settings where the code editor is the first one: 

![image](https://user-images.githubusercontent.com/304656/52351473-212bf500-2a2b-11e9-80cc-bb5284cc8268.png)

**Comment by kjac** [comment] 2019-02-06 21:14
PR in #4459 for the code editor size.

I can't reproduce the button placement; looks like this for me on the latest source:

![image](https://user-images.githubusercontent.com/7405322/52373972-5e5cab00-2a5c-11e9-96b8-552498ea78cd.png)

I haven't been digging too much into the code to see how your weird button placement could occur... if yours is still placed like that I guess we'll have to dig deeper.

**Comment by bergmania** [comment] 2019-02-13 07:15
Thanks for PR, @kjac .

I have merged the fix for the editor size. 
I also experience that the toolbar order we send to tinymce is not respected.

**Comment by bergmania** [comment] 2019-02-13 14:35
Ordering PR: https://github.com/umbraco/Umbraco-CMS/pull/4561

**Comment by Shazwazza** [comment] 2019-02-13 23:09
works!

**Closed by Shazwazza** 2019-02-13 23:09 UTC
Labels: community/pr, release/8.0.0, state/review, type/bug
