### ISSUE TITLE
Unable to translate elements in block list

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/Umbraco-CMS#12433] opened 2022-05-19 10:27 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

I've setup a document type "Page" as the root node and on it a property with an block list.
The page has "Allow vary by culture" checked, and all elements on the block list also has this enabled.

This show the content is the split view, but I cannot edit it - the cursor shows the content is disabled.
If I change the property with the block list to also "Allow vary by culture" then the content disappears, but will allow me to setup whole new content on the block list.

### Specifics

When the block list property does not allow vary by culture:
![image](https://user-images.githubusercontent.com/3674690/169273117-ae49a40f-0ff5-499f-a780-45dabc7566f9.png)

When the block list property does allow vary by culture:
![image](https://user-images.githubusercontent.com/3674690/169273449-c628543d-ad41-4138-9f6b-baf16829470f.png)

### Steps to reproduce

Follow the summary above.

### Expected result / actual result

I had expected to be able to translate the elements of the block list, instead of having to setup all the blocks again.

**Comment by Nikkelmann** [comment] 2022-05-19 10:32
I can see this is something that has transfered over from v8: #9232

**Comment by nul800sebastiaan** [comment] 2022-05-26 09:12
@Nikkelmann Thanks, this is expected behavior, at this point you can only setup a new block list and not culture-edit parts of a block. You should have a handy copy button there so you can copy the whole block to the new language. I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9232. 

![image](https://user-images.githubusercontent.com/304656/170457414-6670da9e-4a89-4a2e-bb87-66af351a2aab.png)

**Closed by nul800sebastiaan** 2022-05-26 09:12 UTC
Labels: type/bug
