### ISSUE TITLE
Unable to use Block List in packages

### ISSUE THREAD

**Issue by limpa123** [umbraco/Umbraco-CMS#8918] opened 2020-09-16 09:44 UTC
- Create a block list
- Create and add content & settings model
- Create a package containing Data type & Doc types
- Install package

Result:
![image](https://user-images.githubusercontent.com/2033070/93320606-8fdd5100-f811-11ea-8cb0-e2eb3a89c1c7.png)

Unable to edit or remove Blocks from Datatype

---
_This item has been added to our backlog [AB#8740](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8740)_

**Comment by nul800sebastiaan** [comment] 2020-09-16 14:47
Thanks! I can reproduce.

![image](https://user-images.githubusercontent.com/304656/93353117-d778d280-f83b-11ea-8c5b-aafe4c11644b.png)

I think it's because the related element type gets a new GUID when it's imported, so I did export the related doctype (element type) but it can't find it now.

And the export (packager) is generating them by integer id: 

```xml
    <readme><![CDATA[testing block packaging]]></readme>
    <actions></actions>
    <datatypes>1145</datatypes>
    <content nodeId="" loadChildNodes="false" />
    <templates>1146</templates>
    <stylesheets></stylesheets>
    <documentTypes>1147,1099</documentTypes>
    <macros></macros>
    <files />
    <languages></languages>
    <dictionaryitems></dictionaryitems>
```

So I guess we need some special code for block editors to be able to reconnect them with their related element type(s).

**Comment by nul800sebastiaan** [comment] 2020-10-21 19:05
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9219 - cherry picked for 8.8 in f1724a68b2147859addb5dd905d641d59dff950a

**Closed by nul800sebastiaan** 2020-10-21 19:05 UTC
Labels: project/block-editor, release/8.8.1, release/8.9.1, state/in-sprint, type/bug
