### ISSUE TITLE
Drag in an image into the rich text area - save the page - drag in same image again errors

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6523] opened 2019-10-01 17:19 UTC
using Umbraco 8.2.RC

This seems really niche, but has happened a few times during testing... this seems to be the way to definately recreate it, but it also happens sporadically too, it might be related to the 'saving' notification bar being on the screen anyway...

Drag a new image into the rich text area, and press save and publish... image is created in media section as expected...

![image](https://user-images.githubusercontent.com/260802/65984250-41576b00-e477-11e9-95ac-23d0af000afa.png)

Now without leaving the page... drag the same image in again... woh, it doesn't resize

![image](https://user-images.githubusercontent.com/260802/65984379-8ed3d800-e477-11e9-94a8-fd425bef3856.png)

there is a console error

![image](https://user-images.githubusercontent.com/260802/65984408-a4490200-e477-11e9-901f-16d7a79ffb0f.png)

saving the page with the super big unresized image in the rich text area, yields no error messages to the editor, it just doesn't save the second image...

If you drag the same image into the rich text editor without saving inbetween the two images are both saved and displayed side by side...

it's consistent with the same image, but have had it with different images, makes me think it's all in the timing... but it happens for me everytime that I drag, Save, and drag the same image again...

... nobody will do this I know, but it might be a clue as to why it also 'sometimes' happens when dragging images in.

**Comment by nul800sebastiaan** [comment] 2019-10-02 22:41
Weird, and indeed a bit niche! I would think it's because we're not properly selecting by each unique image, not sure what is going on here. We'll investigate!

**Comment by nielslyngsoe** [comment] 2019-10-03 08:42
Actually it makes sense that it happens, it the same reason as to why I would like us to change this: https://github.com/umbraco/Umbraco-CMS/issues/6475

**Comment by warrenbuckley** [comment] 2019-10-04 09:57
@nul800sebastiaan & @nielslyngsoe this should have been fixed by this PR
https://github.com/umbraco/Umbraco-CMS/pull/6396

Bjarke did mention in that he had issues with the sizing, but he was unable to reliably reproduce it and I couldn't repro it at all, but I think with Marc's testing notes and #6475 you mention Niels would be the cause.

I will do a PR for this issue shortly and for the time being Niels I will remove the cleanup of localstorage keys on the save/publish of the content node until we figure out a better solution to this.

**Comment by bergmania** [comment] 2019-10-07 14:11
I have tested in the latest rc-branch. I can't reproduce the issue, so it seems to be fixed as @warrenbuckley mentioned.

**Closed by bergmania** 2019-10-07 14:11 UTC
Labels: state/hq-reply
