### ISSUE TITLE
UserGroup Child-nodes does not inherited Granular permissions 

### ISSUE THREAD

**Issue by KasperBHansenAtPentia** [umbraco/Umbraco-CMS#7210] opened 2019-11-22 11:39 UTC
Known afftected versions: **U8.2.2**, **U8.3.0**

**Expected behavior**:
Applying Granular permissions in a UserGroup to a node in the Content-tree, should affect it's child-nodes with the same permissions and rules.

**Actual behavior**:
Only the selected node in a UserGroup is affected with the permissions and rules - not the child-nodes.

**Re-produce issue**:

_Prerequisite_:
Content-tree should have a node with children, that can be selected for Granular permission. Further more, there should be nodes at the same level as the node selected with Granular permission for testing, that permissions and rules are not applied to them.

Umbraco User should have permissions to access the User Section of the backoffice.

Steps to re-produce:

1. Create or edit an UserGroup
2. Select at least **Content** when choosing **Sections**
3. Set the **Content start node** to a node, that is higher or at same level as the node that will have the Granular permission
4. In the **Default permissions** settings, set only Browse Node under Content
5. Set the Granular permissions for at least one node, that fits the requirements for the prerequisite.
5.1 Set the permissions for the selected node, so that either Create, Update, Publish or Delete is selected, and set Browse Node to selected.
5.2 Submit granular permissions
6. Save User Group

7. Assign a user to the newly created group.
8. Log in with user assigned to the newly created group.
9. Navigate to selected node with Granular permissions.
10. Confirm that Granular permissions are set for top-level allowed node
11. Test that same permissions are set for child-nodes (this is part that should not work as expected)

---
_This item has been added to our backlog [AB#3975](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3975)_

**Comment by Shazwazza** [comment] 2019-12-23 05:32
I cannot replicate this issue with the latest codebase in 8.4, i'll test with the latest 8.3.x download zip.

**Comment by Shazwazza** [comment] 2019-12-23 06:02
I can confirm the issue exists in 8.3 and 8.4 releases.

Looks like this is all related to https://github.com/umbraco/Umbraco-CMS/pull/6798 + https://github.com/umbraco/Umbraco-CMS/issues/6788 + https://github.com/umbraco/Umbraco-CMS/issues/6647 + https://github.com/umbraco/Umbraco-CMS/pull/6672 + https://github.com/umbraco/Umbraco-CMS/commit/f6e7740c931ca8d20c287f32871486926ca5f53b

So it turns out that permissions are actually inherited, it's just that the context menu doesn't reflect this permission inheritance. For example, if you click on a child node under a node you've assigned update/publish to, you will be able to update/publish that node. Of course this is still annoying since the Delete action won't be shown if you've enabled Delete since the context menu isn't inheriting those permissions.

Whether this is a regression or not i'm unsure because there's several commits of changes to this file from 8.1 to latest, some of the changes are just reverts and IIRC this had all worked correctly in v7 so it's seems odd. 

I'm hoping that @kjac knows what's actually with the history of the changes for these permission calculations and if we introduced a regression and if we need to patch old releases?

**Comment by kjac** [comment] 2019-12-23 06:16
@Shazwazza  I have no reason to believe that this is anything else than a display issue. For some reason one method of retrieving node permissions is used when editing content, and another when displaying the context menu. The latter is very node centric and doesn't take into account any permissions explicitly set on the levels above.

#6672 should fix it.

**Comment by Shazwazza** [comment] 2019-12-23 06:41
@kjac yep cool, i just wasn't sure if it was a bug we introduced somewhere in 8.x or if it existed before that, there was just a few changes to this file over the past couple months. I haven't checked in 7.15.x but any chance you remember if the issue exists there too? We just need to figure out if we need to put this into patch releases for fixing a regression or if we just keep the fix in the next minor.

**Comment by kjac** [comment] 2019-12-23 06:53
@Shazwazza I honestly can't remember for 7.15, but I'm guessing this has been in V8 since day one. The PR is over two months old and it solves an issue reported on 8.1.4, so it's not a regression, at least not since 8.1.

Personally I'd let it be and wait for the 8.6 release instead of issuing a patch just for this. Again there is no immediate danger on this one, as the server side validation kicks in and saves the day.

**Comment by Shazwazza** [comment] 2019-12-23 07:16
Agreed, i'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/6647

**Closed** 2019-12-23 07:17 UTC

**Comment by Ron-Brouwer** [comment] 2020-02-06 11:13
> Agreed, i'll close this as a duplicate of #6647

Hi @Shazwazza and @kjac,

The serverside validation is only a tempo solution when you see TOO MANY actions. In our case the client CANNOT SEE the actions that they are allowed to use. This is definitely a blocking bug for us.. As there is no release date set for 8.6. We can't go live with a recently migrated Umbraco project until at least the following pull requests are released:

https://github.com/umbraco/Umbraco-CMS/pull/6798
https://github.com/umbraco/Umbraco-CMS/pull/6672

Also as a side note, its not possible to restrict all actions for a specific node. Granular permissions are not saved when there are no actions allowed for that specific part of the tree. We can work around the issue by only allowing the sort action (that will hide the node).

**Comment by KasperBHansenAtPentia** [comment] 2020-03-12 12:12
Tested in U8.6.0RC - Seems to work now
