### ISSUE TITLE
Schedule publishing is giving error when it has thrown an error at first place.

### ISSUE THREAD

**Issue by QaisarIshaq** [umbraco/Umbraco-CMS#13613] opened 2022-12-20 09:56 UTC
### Issue description

The Umbraco schedule publishing is displaying errors when it has displayed an error for the first time. I have created a small video to elaborate the issue please watch the attached video.

Umbraco version: 10.3.2

Reproduction Steps:

Select a node under content and try to schedule the publishing. If the selected time has elapsed the error is displayed. Now change the publish date to future but it still shows the same error.

Best regards,
Qaisar Ishaq
[Untitled_ Dec 19,2022 3_37 PM.webm](https://user-images.githubusercontent.com/58301779/208638218-85f9e453-bbb4-4a50-89bd-9fcd309b4fdc.webm)

**Comment by Zeegaan** [comment] 2022-12-27 08:12
Hey @QaisarIshaq thanks for reporting! I can indeed reproduce this, thanks for the video, it helped a lot!
Seems like the value isn't updated properly after the error 🤔
I am marking this up for grabs, so leaving the steps I did to reproduce this:

- Add a second language
- Create a document type with allow as root & allow vary by culture
- Create some content with both cultures
- Click schedule and click the current date (this will give you the current time)
- Wait for your clock to go past the time you have selected
- Try and schedule
- Get error
- Increase the time so its no longer in the past
- Try and schedule

**Comment by Zeegaan** [comment] 2022-12-28 11:29
I am closing this issue, as its a dupe of: https://github.com/umbraco/Umbraco-CMS/issues/12565 👍

**Closed by Zeegaan** 2022-12-28 11:29 UTC
Labels: community/up-for-grabs, state/reproduced, area/frontend, affected/v10, affected/v11, affected/v12
