### ISSUE TITLE
data-element when creating a new member are wrong and is the same on all properties

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#13619] opened 2022-12-24 11:49 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

The `data-element` attributes of each property on the editing window when creating a new member are wrong and are the same on all properties.

![image](https://user-images.githubusercontent.com/1685262/209434376-4da8f401-cf62-4232-9633-16432f9d8aed.png)

It seems that it doesn't impact editing the members, but someone came across this bug when using the Conditional Displayers package. The package uses this attribute to hide/show each property so it's not working on members. I think the Umbraco tours also target this `data-element` property, so they probably are failing too, but I haven't checked.

### Steps to reproduce

Create a new member and open the Developer tools. Check the HTML generated and you can see that all the `umb-property` elements share the same `data-element` value.

### Expected result / actual result

The value of each `data-element` should be `property-{propertyAlias}`

**Comment by Zeegaan** [comment] 2022-12-27 12:31
Hey @skartknet I cannot reproduce this, this is me on a fresh 10.3.2 install from a template: 
![image](https://user-images.githubusercontent.com/70372949/209667028-f5737af0-7463-4aa8-af2a-b93dc5cdbbce.png)
I'll close this for now, but if you find more information about how to reproduce this, please do not hesitate to re-open!

**Comment by skartknet** [comment] 2022-12-27 19:15
Hi @Zeegaan , the issue is on the `umb-property` element.

**Comment by Zeegaan** [comment] 2022-12-28 07:09
@skartknet Ah I see now, sorry about that 😅

**Comment by Zeegaan** [comment] 2022-12-28 07:51
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13621

**Closed** 2022-12-28 07:50 UTC
Labels: type/bug
