### ISSUE TITLE
NetCore: Creates Doubled Content Node

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#10573] opened 2021-07-01 13:13 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-beta004

### Bug summary

On first run: New content node get created on Save & publish twice.

### Steps to reproduce

1. Fresh install according to: https://our.umbraco.com/Documentation/Fundamentals/Setup/Install/visual-studio 
2. Ctrl + F5
3. During install create SQL-Server 2017 database and enter details into install step, login: dirk.seefeld@idseefeld.de pwd: Test!23456
4. Create media folder & upload one JPG
5. Create document type with template and properties: mainGrid [grid], pageTitle [textbox, limit 50, mandatory], umbracoNaviHide [toggle], allow at root, children of same type
6. Create master template and change generated doc type template to use master.
7. Create one node "Home", fill in content, Save & Publish
8. Two Nodes are created: "Home" & "Home(1)"
9. Emtpy node form is shown
10. Select one created node leads to redirecting. This happens only in the first runing session. After closing Visual Studio, reopen and runing solution it works.
	Project created with SqlCE has slightly different behaviour: Select one created node leads to endless redirecting.

**Comment by nul800sebastiaan** [comment] 2021-07-01 13:27
Hi @idseefeld! While I fully believe you're having problems, I will have to ask you to do some debugging on your end to figure out what the problem is. We have automated integration tests  creating nodes like this over and over again and have never seen this issue, neither on CE nor on full SQL server. Just in case we missed something in beta4, this is my experience on SQL CE:


https://user-images.githubusercontent.com/304656/124131890-895a5600-da80-11eb-946e-280a5ece55aa.mp4

Everything works perfectly. I am going to close this issue as I have to assume that something in your specific environment is not quite right.

**Closed by nul800sebastiaan** 2021-07-01 13:27 UTC
Labels: project/v9, type/bug

**Comment by idseefeld** [comment] 2021-07-02 08:53
Well, I could reproduce this issue on a fresh English _Windows 10 Pro VM_ with a fresh _Visual Studio 2019 Community_ installation using SqlCE. Besides IIS and German Windows language pack nothing else is installed. 
I think the important details to reproduce the issue are: 
1. After creating and building the Umbraco solution start IIS Express profile without debugging.
2. Within this session create a document type with template and add a content node. Saving is just fine, but Save & Publish leads to issue.

Creating a Media item does matter.
After closing and reopening Visual Studio all works fine.
Also starting with Debugging works without fine!

Maybe this is indeed such an edge case that it could be ignored. As a long year Umbraco enthusiast I would not worry at all, but:
Regarding the first impression - at least the setup documentation should be updated. I have just proposed this change for the relate doc page.

Please excuse if I am annoying with this pedantry. 😜
