### ISSUE TITLE
V8: True/False property value always seems to be false

### ISSUE THREAD

**Issue by sulmbrant** [umbraco/Umbraco-CMS#6252] opened 2019-08-31 09:17 UTC
When using the True/False property in Umbraco 8.1.3 the value seems to always be false no matter if you set it to true.

**Comment by kjac** [comment] 2019-08-31 17:10
Sounds strange! @sulmbrant could you please add some steps to reproduce this?

**Comment by sulmbrant** [comment] 2019-08-31 17:20
Nothing strange made.

1) Added true/false property to composition, set it default to true.
2) Added composition to doctype
3) Get the value in view, value is false even if default set to true.
4) Tried to rebuild models in models builder.
5) Value still false.
6) Tried to republish every page.
7) Value still false.
8) Set default value to false, tried false (of course)
9) Change property to true on page, save and publish.
10) Value still false

**Comment by kjac** [comment] 2019-08-31 19:12
Sounds an awful lot like #5224 which was closed due to lack of reproduction ... can you try the solution in #5224 and report back here?

**Comment by stevemegson** [comment] 2019-09-01 08:40
I was able to reproduce this, but when I started to investigate the problem went away. I had no composition, just a true/false property directly on the document type. It wasn't saving a false value, it was creating no row at all in `umbracoPropertyData` for that property, and the missing value was then being converted to false.

I'll see if I can work out how to consistently reproduce it.

**Comment by stevemegson** [comment] 2019-09-01 13:05
I don't think this is specific to Checkbox properties.

- Open a document, and open its document type from the Info tab.
- Add a property, creating a new data type. (I don't think it happens if you reuse a data type)
- Enter a value for the new property and save the document.
- In the request to `Content/PostSave`, the new property has `"value": ""`, ignoring the value you set.

The Checkbox type does have the added problem that the default value doesn't apply to existing documents until the document is saved. Since there's no row in `umbracoPropertyData` yet, the value defaults to null and the PropertyValueConverter converts this to false. It would be easy to convert null values to the default value instead, though this could give unexpected behaviour if the default value is later changed. There would be no way for an editor to tell whether a document has a null value which will change to the new default, or has a saved value which matches the default.

**Comment by nul800sebastiaan** [comment] 2019-09-03 14:03
So, if I understand this correctly, this is the case when you edit your doctype and publish document with the newly added property on it?

**Comment by nul800sebastiaan** [comment] 2019-09-03 14:04
Or is this ONLY the case when you add a new property and do not republish the pages which contain the new property?

**Comment by stevemegson** [comment] 2019-09-03 14:39
There are two separate issues, I think.

When you add a Checkbox property, existing pages will ignore the default value. They'll default to false until you save them, when the editor will respect the default value. This is fairly easy to change, though it has some side effects if the default value is ever changed.

The second issue happens when you add any new property by opening the document type from a document (or maybe only when you also create a new data type for the new property). The new property won't be saved on the document that you already had open. The new property appears, but saving the page will send a blank value for the property. It looks like the model on the new property editor doesn't get properly wired up to the existing model for the rest of the form, but I'll admit it doesn't take much for me to get way out of my depth with angular. Reloading the page is enough to get things behaving again.

**Comment by DanielOor365** [comment] 2019-12-07 06:05
I can confirm the second scenario:
I created a partial - a document type without a template, called "Robots info".
I added 2 NEW properties: "Checkbox - Default TRUE", and made them mandatory.
I then added the properties to EVERY document that has a template.
Result:
The values were only TRUE on those pages that I explicitly PUBLISHED again.
Before publishing: values returned FALSE. After publishing: values returned their correct value.
**Conclusion:**
_Workaround_ is to publish every single page in Content.
_Correct solution_ would be to make sure de default values of new editors are published, just as they are for reused editors.

**Comment by nul800sebastiaan** [comment] 2020-07-13 15:39
Looks like the described behavior in the initial issue can't be reproduced. The reproduction of the other issues is something that we are aware of and currently don't plan to work on. We are hoping to have a new system in place at some point were default values can be set on all datatypes where it makes sense.

So for the reasons stated in the comments on related issue https://github.com/umbraco/Umbraco-CMS/issues/8418#issuecomment-657632901 I will close this for now.

**Closed by nul800sebastiaan** 2020-07-13 15:39 UTC
Labels: state/needs-more-info
