### ISSUE TITLE
Invalid date returned from `contentResource.getById`

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13477] opened 2022-11-25 09:20 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

When I use `contentResource.getById()` I get document incl. tabs and properties.
However for some

![image](https://user-images.githubusercontent.com/2919859/203942440-4bceb98b-dac2-4e64-ae77-782d1d538543.png)

but the endpoint `GetById` does return a valid date.
![image](https://user-images.githubusercontent.com/2919859/203944758-6cad2ca9-bc33-4c5f-98c0-cff45bae62b7.png)

### Steps to reproduce

Request different documents usings `contentResource.getById`. Depending on the date, some of these are returned as invalid date from angular resource.

In this case date is `11/20/2022 12:00:00 AM` which was picked from a date picker and property editor afterwards changed to label, which is shown on the content node. I should also be mentioned that I afterwards changed datatype of the property from date picker to label (datetime), so the nodes which has been saved afterwards may store the value in a different format.

![image](https://user-images.githubusercontent.com/2919859/203946395-410a30d7-37c7-4ce7-afb9-0397fc20e4dd.png)

**Comment by bjarnef** [comment] 2022-11-25 09:42
@nul800sebastiaan @Zeegaan any idea why the date if different than the one returned from the endpoint?

**Comment by bjarnef** [comment] 2022-11-25 10:27
For other node I get a totally different year than expected 😅

![image](https://user-images.githubusercontent.com/2919859/203962805-4846966c-6fe4-4607-96a7-e5f33bc0c5c9.png)

![image](https://user-images.githubusercontent.com/2919859/203963089-47e0b243-d7e7-47f4-b30f-7727db9d409e.png)

**Comment by bjarnef** [comment] 2022-11-25 10:33
I think the issue may be inside `umbDataFormatter.formatContentGetData()` https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js#L400

which is called here:
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js#L458

**Comment by elit0451** [comment] 2022-11-25 10:37
Hi @bjarnef 👋 
Before asking you for more detailed "Steps to reproduce", so I can replicate quicker the issue you are seeing, could you tell me what is the DateTime format you are using? As in [his comment ](https://github.com/umbraco/Umbraco-CMS/issues/13403#issuecomment-1322013984) on another issue, Nikolaj explained that moving away from the default configuration `YYYY-MM-DD` causes some problems 🤔 Perhaps it is something related

**Comment by bjarnef** [comment] 2022-11-25 10:42
Hi @elit0451

It just used the standard datatype instance "Date Picker".

![image](https://user-images.githubusercontent.com/2919859/203965379-5855e701-a6c0-44c2-bf94-fb4621b56050.png)

Afterwards I changed the property editor to "Label (datetime)" as these data will be imported via a Hangfire job, so using the date picker was mainly to set a data and get a value in the property, but I think it shouldn't matter as the value returned from the endpoint looks correct.

**Comment by bjarnef** [comment] 2022-11-25 10:48
I tried changing the property editor back to Date Picker.

![image](https://user-images.githubusercontent.com/2919859/203966714-b2612e6a-f056-478f-a7af-6246ffec5e61.png)

but it doesn't seem to make a difference. Still seeing the incorrect date or invalid date when fetched from `contentResource.getById`:

![image](https://user-images.githubusercontent.com/2919859/203966863-5a6675d9-1234-43a6-82d0-8c982e3fbb4c.png)

**Comment by bjarnef** [comment] 2022-11-25 11:02
For another node I needed to save the node again after change datatype from label (datetime) >date picker as I got "Invalid date". Afterward the date looks correct.

I suspect the issue happens when changing datatype from date picker > label (datetime) and save the node again. I guess it may be storing the date in a different format.

**Comment by elit0451** [comment] 2022-11-25 11:38
Thanks for investigating! 🙌 Can I get you to update the issue description with those last relevant details and perhaps come up with a simple test scenario that we can work with when reproducing/trying to fix the issue? 🙂

**Comment by bjarnef** [comment] 2022-11-25 12:09
I tried this as a test.

```
@inject Umbraco.Cms.Core.Services.IContentService contentService;
@{
    var node = contentService.GetById(1215);

    <pre>@(node?.GetValue("expirationDate"))</pre>
}                                      
```

First using date picker (default configuration and saving node) which return this:

```
<pre>01.12.2022 00.00.00</pre>
```

![image](https://user-images.githubusercontent.com/2919859/203982418-e61a7f65-6e50-4af5-9d1d-748ca1fff54b.png)

Next a changed property editor to label (datetime) and saved node once again.
Still returning this

```
<pre>01.12.2022 00.00.00</pre>
```

and it also seems correct in the property in backoffice.

![image](https://user-images.githubusercontent.com/2919859/203981823-785c4a2d-05c9-4370-9d52-5ab48787ed50.png)

![image](https://user-images.githubusercontent.com/2919859/203982016-9be9af3d-da9c-43b9-9596-16c54cd6f60a.png)


In the table the property is formatted directly.

```
Utilities.forEach(vm.results.items, item => {
    item.editPath = `/content/content/edit/${item.id}`;

    formatDatesToLocal(item, 'L');
});

function formatDatesToLocal(item, format) {

    format = format || "LLL";

    // get current backoffice user and format dates
    userService.getCurrentUser().then(currentUser => {
        item.expirationDate = dateHelper.getLocalDate(item.expirationDate, currentUser.locale, format);
    });
}
```

in overlay same approach it use, but it fetch document from id and its properties.

```
contentResource.getById($scope.model.item.id).then(node => {
    console.log("node", node);
    const properties = getContentProperties(node.variants[0].tabs);

    $timeout(() => {
        vm.properties = properties;
        vm.loading = false;
    }, 250);
});


function getContentProperties(tabs) {

    let properties = [];

    Utilities.forEach(tabs, tab => {

        Utilities.forEach(tab.properties, prop => {

            if (!prop.alias.startsWith("_umb_")) {

                let allowed = [
                    "categories",
                    "expirationDate",
                    "duration",
                    "price"
                ];

                if (allowed.includes(prop.alias))
                {
                    if (prop.alias === "categories" && prop.value) {

                        const udis = prop.value ? prop.value.split(',') : [];

                        getCategories(udis).then(data => {

                            let categories = [];

                            Utilities.forEach(data, item => {

                                categories.push({
                                    name: item.name,
                                    id: item.id,
                                    icon: item.icon,
                                    udi: item.udi
                                });

                                prop.value = categories.map(x => x.name).join("<br>");

                            });
                        });
                    }
                    
                    if (prop.alias === "expirationDate") {
                        formatDatesToLocal(prop, 'L');
                    }

                    prop.editor = "Umbraco.Label";
                    prop.view = "readonlyvalue";

                    properties.push(prop);
                }
            }
        });
    });

    return properties;
}
```

**Comment by elit0451** [comment] 2022-11-25 12:22
Just what I was after 🤩 Thanks a lot Bjarne 🙌 , I will have a look and get back to you

**Comment by bjarnef** [comment] 2022-11-25 12:24
I reproduce this is could be a simple dashbord with a controller and fetch any node:

```
const nodeId = 1234;
contentResource.getById(nodeId)
    .then(node => {
                console.log("node", node);
            });
```

Then first start with the a property using Date Time (default configuration) and set a date, e.g. December 1st 2022 and check console from code before and compare property data from `GetById` and console log.

Next change property editor from Date Time to Label (datetime) and re-save the node.

Go back an inspect the property data from `GetById` and console log. I suspect the values would be different this time.

**Comment by elit0451** [comment] 2022-11-28 14:19
Hi again @bjarnef 
I've tried setting up a test with a dashboard, changed my backoffice language to Danish, add a Danish culture as well but unfortunately, I couldn't replicate the "Invalid date" response from `contentResource.getById` that you are getting.. 🤷 I always get the same response from both the GetById action and the console.log of calling `contentResource.getById`.

As a last resort, could you try the simplified scenario with the dashboard that you described in the above comment (_https://github.com/umbraco/Umbraco-CMS/issues/13477#issuecomment-1327410531_) and let me know if you get an "Invalid date", as I suspect it could be happening because of what you are doing with the custom `formatDatesToLocal()` function that you are calling 🤔

**Comment by bjarnef** [comment] 2022-11-28 14:34
Hi @elit0451 

Regarding my backoffice user it is isn't default "English (United States) - en-US" language.

I tried to comment the `formatDatesToLocal()` function, but it didn't seem to be the issue as I also got the error here:

```
const nodeId = 1234;
contentResource.getById(nodeId)
    .then(node => {
         console.log("node", node);
    });
```

With the `GetById` API returned the expected data, but the Angular resource returned "Invalid date" or an incorrect date, see screenshots here: https://github.com/umbraco/Umbraco-CMS/issues/13477#issuecomment-1327298518

also when I tested this I got the correct date. So I guess server side everything is as exspected.

```
@inject Umbraco.Cms.Core.Services.IContentService contentService;
@{
    var node = contentService.GetById(1234);

    <pre>@(node?.GetValue("expirationDate"))</pre>
}
```

But I think Anguar something modify the data returned from `GetById` until returned in the angular resource.

**Comment by bjarnef** [comment] 2022-11-28 22:52
Hi @elit0451 

I have made a nice dashboard for you using default starter kit 😁 

On Home Page node I have added this properties using Date Picker with default configuration.
![image](https://user-images.githubusercontent.com/2919859/204395703-5c2d22c2-9901-4752-bcdf-46662c004f2d.png)

![image](https://user-images.githubusercontent.com/2919859/204395830-f5b0c8f1-f3cb-4c25-bdd0-6bd464914ff5.png)

Next on Home Page node set December 1st 2022 as start date (v11 release date! 🎉🥳)

![image](https://user-images.githubusercontent.com/2919859/204395931-d5908a6a-8c98-4158-ac4a-ae0527b27b55.png)

In dashboard it  should show this clicking the "Show details" button.

https://user-images.githubusercontent.com/2919859/204396292-cce5a41f-ecb6-4307-bf26-8b0c80e899e9.mp4

Start Date and End Date properties are included, but only End Date is formatted.

If I then change End Date property to using "Label (datetime)" instead.

![image](https://user-images.githubusercontent.com/2919859/204396547-90631004-7d0c-4f97-8b5a-0a1126a2fde5.png)

then I get this - notice start and end dates hasn't changed, but end date is formatted as `01/20/2012`

https://user-images.githubusercontent.com/2919859/204397096-17ef0f80-92a1-4c6e-a054-b7b3a860ee62.mp4

The locale is `en-US` but even before formatting date it log the content node, which property value is `01/20/2012`:

![image](https://user-images.githubusercontent.com/2919859/204397272-66321e8a-f292-4fde-8856-d9c7ae3eaf7d.png)

even though the date stored in database and returned from `GetById` API method is `12/1/2022 12:00:00 AM`:
![image](https://user-images.githubusercontent.com/2919859/204397607-3cd6e1e5-7a18-481d-a3fd-69db8bf57299.png)

**Comment by bjarnef** [comment] 2022-11-28 23:07
Actually I think you are right that `formatDatesToLocal()` seems to affect the response I am seeing the the developer console, because when I comment that I get this instead.

![image](https://user-images.githubusercontent.com/2919859/204398390-749f4d2b-5719-40f6-99bb-94165d417af2.png)

If I modify this in the details controller then end date property in `node` has the correct date `12/1/2022`, but for `vm.node` the property value is modified as shows `01/20/2012`.

```
function onInit() {
  vm.loading = true;

  contentResource.getById($scope.model.id)
    .then(node => {

    console.log("node", node);
    vm.node = Utilities.copy(node);
    console.log("vm.node", vm.node);

    const properties = getContentProperties(vm.node.variants[0].tabs);

    $timeout(() => {
      vm.properties = properties;
      vm.loading = false;
    }, 250);
  });
}
```

**Comment by bjarnef** [comment] 2022-11-28 23:30
I tried with formatting of date directly using momentjs https://momentjs.com/guides/#/parsing/known-formats/

```
function formatDatesToLocal(prop, format) {

  format = format || "LLL";

  // get current backoffice user and format dates
  userService.getCurrentUser().then(currentUser => {
    console.log("locale", currentUser.locale);

    prop.value = moment(prop.value, 'YYYY-MM-DD HH:mm:ss').locale(currentUser.locale).format(format);
    //prop.value = dateHelper.getLocalDate(prop.value, currentUser.locale, format);
  });
}
```

where `YYYY-MM-DD HH:mm:ss` is same date format it use in `dateHelper.getLocalDate()`, but it could also use `moment.ISO_8601` if the date was in the standard format.

https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/common/services/util.service.js#L113

**Comment by bjarnef** [comment] 2022-11-28 23:43
Maybe "Label (datetime)" should have a format property as well?

![image](https://user-images.githubusercontent.com/2919859/204403889-28691dd9-80e6-43c5-b38e-3c842d470873.png)

**Comment by elit0451** [comment] 2022-11-29 14:27
Nice investigation work Bjarne and super awesome set-up test 🤩 (https://github.com/umbraco/Umbraco-CMS/issues/13477#issuecomment-1329857756). It was a great idea to send the zip file over!

I didn't have time to go through all the details of it today but I can see that you worked/are working on some PRs related to dates? Shall I let you to it and once we have the PRs merged we can close this issue? 😍

**Comment by bjarnef** [comment] 2022-11-29 15:04
When backoffice has language "English (United States)" the value of label (datetime) is formatted like this:

`1/14/2017 12:00:00 AM`

if I change backoffice user language to "Danish (Denmark)" I get this formatted value instead.

`14.01.2017 00.00.00`

So I would probably need to parse this different based on backoffice user language.
Not sure where this value is formatted in the "label (datetime)" property editor.

**Comment by elit0451** [comment] 2022-11-30 06:59
Thanks for your efforts Bjarne. 💪 I hope this helps to clarify how much easier it is to locate a bug if there is any when we have a simple clean scenario as opposed to custom functions or third parties. I think we can agree that there isn’t any issue in converting from date picker to label(datetime), nor does the angular resource return something wrong. The label changes based on culture (_da-culture will cause the dates to behave as Danish_), but that is just how it is. The conclusion that you came to in https://github.com/umbraco/Umbraco-CMS/issues/13477#issuecomment-1329891204 is better suited for a discussion about a feature request (being able to set a date time format on the label), so I will go ahead and close this issue so we don’t mix the concepts (_bug/feature_). 🙂

**Closed by elit0451** 2022-11-30 06:59 UTC
Labels: type/bug, area/frontend

**Comment by bjarnef** [comment] 2022-11-30 08:20
@elit0451 actually I think it is possible to format the datetime here using the `config > filter`, it is just not something added the the label property editor configuration:
https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/readonlyvalue/readonlyvalue.controller.js#L17-L25

However I am not sure how the default value is formatted based on culture. Often it would just be the raw value, but I think in the case there may be something formatting dates based on culture.
https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/readonlyvalue/readonlyvalue.controller.js#L24
