### ISSUE TITLE
Link Picker

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco-CMS#13483] opened 2022-11-26 10:41 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

The link picker defaults to a content picker when you want to add links in:
![image](https://user-images.githubusercontent.com/10153922/204084472-7ecff36d-8483-4473-b6c6-699dc913192c.png)

### Steps to reproduce

Highlight the "add link" option in tiny mce to open the link picker

### Expected result / actual result

It would be good if you could configure the default behaviour of the link picker, sometimes as a content editor you may want to pick an existing page, other times you may want to enter a link. If we can't do this setting focus on the link box would be the expected result.

Also there are times (as in this example) where internal links can not be used at all so would be good to be able to configure the link picker to not have them

**Comment by elit0451** [comment] 2022-11-28 10:11
Hi @RachBreeze 👋 

From my understanding, you are talking about the link picker (_Multi Url Picker_) that appears when clicking the _"Insert/edit link"_ on the toolbar of your Rich Text Editor.

The Multi Url Picker in Umbraco allows for different links to be picked- check this ["_Content Example_" in our docs](https://our.umbraco.com/Documentation/Fundamentals/Backoffice/property-editors/built-in-property-editors/Multi-Url-Picker/#content-example). Based on your needs, you can either insert a URL, Link to page, or Link to media 🙂 

Perhaps this clarifies that this isn't actually a bug - the Multi Url Picker gives you all the 3 options and does not default to a content picker; please let me know if I misinterpreted your scenario!

**Comment by soreng** [comment] 2022-12-01 10:13
@RachBreeze we have run into this a few times. We would like to be able to limit the behaviour, like disabling media, focus an a content link or external link etc.

@elit0451 I think the issue / idea here is to have some kind of configuration the the Multi Url Picker, other than just the min/max number of links

**Comment by RachBreeze** [comment] 2022-12-20 11:08
@soreng  this is exactly what I was thinking.

@elit0451 in addition when editing a link which has already been created as an external link the focus goes to the content items rather than the external link picker
![200c0f9a6ec680b26834796194e0eb08](https://user-images.githubusercontent.com/10153922/208652903-be58757e-d393-4c08-b7b3-774dced79edd.gif)

**Comment by elit0451** [comment] 2022-12-20 11:41
Thanks for clarifying @soreng 🙌 
The request for having an additional kind of configuration for the Multi Url Picker sounds to me like a feature request so I would encourage you to create a Discussion for it!

@RachBreeze I think this is the wrong video highlighting the numerous grid items and the save and close problem from the other issue 😁

**Comment by RachBreeze** [comment] 2022-12-20 11:48
@elit0451  erm you're right I've updated my comment, so sorry

**Comment by elit0451** [comment] 2022-12-20 12:27
I've tried to reproduce the second issue you mention, Rachel - the one with editing a link. For me, the focus goes to the external link picker as you can see on the video 🤷 I haven't done any special configurations to the RTE or the Multi Url Picker..

https://user-images.githubusercontent.com/21998037/208667090-66b80bee-ee70-4a21-8035-ebf4860ba3e3.mp4

**Comment by kjac** [comment] 2023-01-10 05:57
Hi everyone,

I'm going to close this as it seems to be a non-issue. I too will encourage to open a GitHub Discussion if there still is a feature request hidden here 😄 

I believe you are also able to create custom toolbar extensions for TinyMCE, which might be an acceptable approach to swapping out the link picker. Perhaps that would even be a great subject for a Skrift article 👍

**Closed by kjac** 2023-01-10 05:57 UTC
Labels: state/needs-more-info, type/bug
