### ISSUE TITLE
Save and Preview - just an Alert?

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#16325] opened 2024-05-19 10:23 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC3

### Bug summary

@nul800sebastiaan @filipbech 
Starting to doubt my sanity so going to stop testing, as I think I must be using the wrong version of the release candidate!
Apologies for all the spam!

This one is when I click 'Save and Preview' instead of seeing a preview of my page I see an alert popup that says 'Save and Preview'

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/ae405af2-665e-419d-bdae-9924a4d9e1bb)

it does say, I'm using V14 release candidate 3... but 

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/86541775-a6fa-4c55-8775-39fb7be2f718)

Let me know if I'm completely gone off piste!, and how I can get hold of the actual release candidate, I just installed it from Paul's Package Script Writer, but I must be seeing something old.

### Steps to reproduce

Press Save and Preview

### Expected result / actual result

See Preview of page

**Comment by JoJk0** [comment] 2024-05-20 08:45
> ### Which Umbraco version are you using? (Please write the _exact_ version, example: 10.1.0)
> V14 RC3
> 
> ### Bug summary
> @nul800sebastiaan @filipbech Starting to doubt my sanity so going to stop testing, as I think I must be using the wrong version of the release candidate! Apologies for all the spam!
> 
> This one is when I click 'Save and Preview' instead of seeing a preview of my page I see an alert popup that says 'Save and Preview'
> 
> ![image](https://private-user-images.githubusercontent.com/260802/331863776-ae405af2-665e-419d-bdae-9924a4d9e1bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQ3MDgsIm5iZiI6MTcxNjE5NDQwOCwicGF0aCI6Ii8yNjA4MDIvMzMxODYzNzc2LWFlNDA1YWYyLTY2NWUtNDE5ZC1iZGFlLTk5MjRhNGQ5ZTFiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwODQwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDgwMTVmYzYwOWI3MGExMTU1Nzg3OGRjYmE2Y2M2OTcyYmFkYWY4NGVkMDRmNDZkOWEyNzhlM2MyZTFmOWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.htBBQ8VU7xT3917mkdNX-xChS1tOhxgtpZHrQqPzGy4)
> 
> it does say, I'm using V14 release candidate 3... but
> 
> ![image](https://private-user-images.githubusercontent.com/260802/331863799-86541775-a6fa-4c55-8775-39fb7be2f718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQ3MDgsIm5iZiI6MTcxNjE5NDQwOCwicGF0aCI6Ii8yNjA4MDIvMzMxODYzNzk5LTg2NTQxNzc1LWE2ZmEtNGM1NS04Nzc1LTM5ZmI3YmUyZjcxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwODQwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODhhNDI1ZmZkNmU4ZTJlYzU2ZDc0NzEwNjVlMGRlMjBjMTdlZTMxZDk3YjZlMmU1MjE0NjY0ZGMyZjE3YzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cZiSTki8wsV92yUYjXS2RrE3bAZN1uOkJosfw75Uyys)
> 
> Let me know if I'm completely gone off piste!, and how I can get hold of the actual release candidate, I just installed it from Paul's Package Script Writer, but I must be seeing something old.
> 
> ### Specifics
> _No response_
> 
> ### Steps to reproduce
> Press Save and Preview
> 
> ### Expected result / actual result
> See Preview of page

I can reproduce it on mine as well and also have rc3 version, it looks like they can't move the deadline of 30th May for the official release and the backoffice is clearly not ready for production yet with whole features not implemented. I appreciate the hard work they're doing right now to make it up though.

**Comment by marcemarc** [comment] 2024-05-20 09:48
@JoJk0 Thanks for at least confirming I'm testing the right thing! 

I think with the fixed release cadence V14 is just then the latest V13 branch... but as you say looks like that maybe the new backoffice will be released as v14, but lots of it is really rather lovely and the implementation thought through... how have you found using the vue.js components alongside Umbraco's Web Components? - as that is the good news story here, if it opens up that freedom.

**Comment by JoJk0** [comment] 2024-05-20 10:15
> @JoJk0 Thanks for at least confirming I'm testing the right thing!
> 
> I think with the fixed release cadence V14 is just then the latest V13 branch... but as you say looks like that maybe the new backoffice will be released as v14, but lots of it is really rather lovely and the implementation thought through... how have you found using the vue.js components alongside Umbraco's Web Components? - as that is the good news story here, if it opens up that freedom.

Vue components can be built via `@vitejs/plugin-vue` Vite plugin as web components so it enables the integration with Umbraco stuff, however it still needs a wrapper web component to pass whatever is needed from Umbraco context API to Vue component. Ideally, we would need a plugin that takes already built Vue web component and extends it with Umbraco's `UmbElementMixin` to get direct access to context API, or some composable that could follow context API's structure, e.g. `useCurrentUser()` composable for Current User context etc.

**Comment by markadrake** [comment] 2024-05-20 18:27
I constantly have to communicate to stakeholders that Umbraco 14 is not working software, that we are not upgrading, and that it bears no significance to their project or the project's future.

- **Developers familiar with .NET and Umbraco CMS** `don't understand` this release cadence.
- **Senior-level marketing directors and managers** `need help understanding` this release cadence.
- **Editors using Umbraco CMS** `don't even _care`—_but_ let's hope their first experience with the CMS isn't version 14 because we'll never see them again.

Why are we steadfast on delivery dates for future versions of software? How do we know there are breaking changes in the pipeline for future versions of our software that aren't even in development yet? Why don't we take a more cautious approach to software development that introduces experimental features into the software that live side-by-side and don't result in breaking changes immediately? Lastly... why is HQ not listening?

**Comment by iOvergaard** [comment] 2024-05-21 08:53
Hello @marcemarc and thanks for testing RC3. You are right, it is unfortunate that an alert like this made it into a release candidate. We initially revealed in [the RC blog post](https://umbraco.com/blog/umbraco-14-release-candidate/) that "preview mode" wasn't going to make the cut for 14.0, however, that was announced out of an abundance of caution. I am pleased to announce that Preview Mode will be included in 14.0 and you should be able to test it out in the upcoming RC4.

This bug report could be linked to many pull requests, but I think this is the most appropriate one to track which has been merged: #16279

**Closed by iOvergaard** 2024-05-21 08:53 UTC
Labels: type/bug

**Comment by marcemarc** [comment] 2024-05-21 09:23
Thanks @iOvergaard it is all rather lovely by the way!!

Great that you've squeezed it in!

My thinking if it was descoped for V14, would have been not to have the 'Save and Preview' button there at all. I think its presence would have led editors to click it and think something was broken. 

But can see now, you was edging your bets, and would have removed it last minute if preview wasn't going to make it!

So I should wait to rc4 before doing any further testing?

**Comment by iOvergaard** [comment] 2024-05-21 09:31
@marcemarc To be fair, I would rather have had it the other way around, but then we'd seen bug reports with "Preview is missing". Yes, it's probably best to wait until RC4. I really hope we can get it out tomorrow.

**Comment by iOvergaard** [comment] 2024-05-21 09:38
@marcemarc no worries, I appreciate the input!
