### ISSUE TITLE
RTE mandatory issue

### ISSUE THREAD

**Issue by MatValling** [umbraco/Umbraco-CMS#10327] opened 2021-05-25 14:53 UTC
### Which Umbraco version are you using?

8.13

### Bug summary

When having an RTE which is mandatory, and you forget to fill in the RTE, you then get a validate error, as you sould how ever if you add any text and there for fulfill the requiment, you still can't click on the save/pushlish button before a page reload of the page 

### Steps to reproduce

Add a RTE filed to any docType, manke it mandatory, then creat a page based on the docType, and leave the mandatory RTE empty after you get the validations error, insert any text into it and you will not be able to klick save/publich

### Expected result / actual result

Expected result:
Wanna be able to save my content after i insert the text in the RTE.

Actual result: 
Can't even click on the publish button

**Comment by nul800sebastiaan** [comment] 2021-05-26 09:06
Thanks I can reproduce this indeed, this is ALSO an issue when you put the RTE in Nested Content, a bug we're working on soon, I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/10246 since we should fix both scenarios. Make sure to follow that issue for updates. 

A workaround exists as of the upcoming version 8.14 we WILL save the node, but you're still stuck publishing it until you do a refresh, fill in the last missing mandatory field and then continue.

**Closed by nul800sebastiaan** 2021-05-26 09:06 UTC
Labels: type/bug

**Comment by MatValling** [comment] 2021-06-08 07:33
We are still able to trigger this bug after we upgreated to 8.14, by doing following steps.
1 Create new docType With a mandatory RTE, plus a few others mandatory (date picker and a media picker) 
2 Insert data in all but the RTE
3 Try and save and publish
4 Get the value cannot be empty
5 Insert text in the RTE
6 not able to click the save and publish butten until after a page reload (aka losing what i just wrote)
