### ISSUE TITLE
v8.9: MemberService.Save() fails with SqlDateTime overflow error

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#9390] opened 2020-11-12 22:28 UTC
A change in 8.9: It seems that a value is required for "umbracoMemberLastPasswordChangeDate" because if you try to Save a newly created member, you can get an exception of "SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM."

Example:
```
                     m = memberService.CreateMemberWithIdentity(username, email, name, memberType);
                    memberService.SavePassword(m, password);

                    memberService.Save(m); <--- ERROR THROWN HERE
```

This can be fixed like this:

                     m = memberService.CreateMemberWithIdentity(username, email, name, memberType);
                    memberService.SavePassword(m, password);
                    m.SetValue("umbracoMemberLastPasswordChangeDate", DateTime.Now); //Required by v 8.9 <--- ADD
                    memberService.Save(m);

But it seems to me that this should be automatically handled via the MemberService internals.

I'm not sure exactly where the best place for this to get set internally... on Member .Create()? Or in .Save() or in  .SavePassword()?

CreateMemberWithIdentity() : https://github.com/umbraco/Umbraco-CMS/blob/f29c5f0e3b0dc79456e2726f3aeace04e51a28b0/src/Umbraco.Core/Services/Implement/MemberService.cs#L296

SavePassword() : https://github.com/umbraco/Umbraco-CMS/blob/f29c5f0e3b0dc79456e2726f3aeace04e51a28b0/src/Umbraco.Core/Services/Implement/MemberService.cs#L1166

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1 (Umbraco Cloud)

A more detailed explanation here: https://our.umbraco.com/forum/using-umbraco-and-getting-started//104154-umbraco-891-memberservicesave-fails-with-sqldatetime-overflow-error

---
_This item has been added to our backlog [AB#9483](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9483)_

**Comment by nul800sebastiaan** [comment] 2020-11-20 08:32
Oh no, that's definitely something that wasn't intended to work like this, of course we should just default to a date. We'll get it fixed! Happy to see that you found a workaround in the mean time! 👍

**Comment by nul800sebastiaan** [comment] 2021-01-13 19:44
Hi again @hfloyd and sorry for the delay on this one. I'm trying to reproduce this problem in Umbraco 8.9.1 and have dropped the following code in `App_Code`: 

```csharp
using System;
using System.Web.Mvc;
using Umbraco.Web.WebApi;

namespace ClassLibrary1
{
    public class MemberApiController : UmbracoApiController
    {
        [HttpGet]
        public string GetCreateMember()
        {
            var memberService = Services.MemberService;

            var userName = $"test@test{DateTime.Now.ToString("yyyyMMddTHHmmss")}.com";
            var m = memberService.CreateMemberWithIdentity(userName, userName, userName, "Member");
            memberService.SavePassword(m, "test123456");
            memberService.Save(m);
            
            return "Success";
        }
    }
}
```

This results in creating members just fine: 

![image](https://user-images.githubusercontent.com/304656/104501428-fcaa0180-55df-11eb-8e2e-72df549a92f8.png)

I will close this for now but I am very curious if you can still reproduce and would love an updated code snippet to test with if you can!

**Closed by nul800sebastiaan** 2021-01-13 19:44 UTC
Labels: release/8.9.2, state/sprint-candidate, status/regression, type/bug
