### ISSUE TITLE
Media overview not showing images

### ISSUE THREAD

**Issue by Amalie-Wowern** [umbraco/Umbraco-CMS#17306] opened 2024-10-18 09:05 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

When i create a new folder and upload images, i can't see the images 

![1](https://github.com/user-attachments/assets/72866da3-4c9d-470f-96fa-bdbb98c4be9c)
![2](https://github.com/user-attachments/assets/924b31da-acb5-4ac4-81d4-5e0401ef9510)

### Steps to reproduce

Go to the media section
create a folder
Upload images to the folder
click on the folder

### Expected result / actual result

Expected to see an overview of uploaded images

**Comment by iOvergaard** [comment] 2024-10-18 09:53
Hi @Amalie-Wowern, is this a new or an upgraded solution? We have seen some reports about the data type "List View - Media" not having the right views, e.g. a default setup should look like this:

![image](https://github.com/user-attachments/assets/27f638c2-f9ec-460b-9c8d-119dc3d3a0f0)

If it doesn't have a List or Grid view, or if they were not migrated properly, nothing will show for folders. It would be helpful if you could share your configuration?

**Comment by mjpraxis** [comment] 2024-10-21 12:03
@Amalie-Wowern @iOvergaard 

We had the exact same problem. We are using uSync and the exported settings from earlier versions of v14 had some diffs compared to a plain/clean v14.3 and uSync'ed settings.

In the two ListViewContent and ListViewMedia the "CollectionView" value has changed from a .html file to eg."Umb.CollectionView.Media.Grid"

![image](https://github.com/user-attachments/assets/79b0dda1-7aa7-4c08-a55a-fd25f4b2299e)

I changed the values in our "old" uSync settings files and imported them. And now everything is perfect.

**Comment by mjpraxis** [comment] 2024-10-21 12:05
Oh and BTW it fixed #17250 
So now the "Create" button works again.

**Comment by Amalie-Wowern** [comment] 2024-10-22 05:03
@iOvergaard @mjpraxis 

I have a new solution.
But i used usync files from a v14 and can confirm my issue was the same as @mjpraxis

**Comment by leekelleher** [comment] 2024-10-22 09:06
Hi @Amalie-Wowern and @mjpraxis,

To clarify my understanding of this particular issue, on a v14 instance (either new or upgraded), when uSync files (that contain data-type ListView configuration for an older Umbraco version, e.g. it has `path` and no `collectionView`), then importing those files will cause the Collection View to disappear (in this case the Media section, but would also apply to Documents).

In the case of direct upgrades, the CMS does have [a v14 database migration](https://github.com/umbraco/Umbraco-CMS/blob/release-14.0.0/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs#L313-L326) for converting the `path` value to the new `collectionView` value.

However, in the scenario where the older data-type  configuration is being (re)imported by uSync, that migration would have already ran, so the older configuration has now replaced the newer configuration in the data-type/database.

If the uSync import is a one-time situation, then the simplest workaround is to go back into the List View data-types (after the import) and re-configure the **Layout** field with the corresponding `collectionView`.

If the uSync import (of the older data) is to be a regular occurrence, then those uSync XML files would need to be manually amended ([exactly as @mjpraxis suggested above](https://github.com/umbraco/Umbraco-CMS/issues/17306#issuecomment-2426479891)), then it can be re-imported.

There are other options to explore, such as the [**uSync Migrations**](https://github.com/Jumoo/uSyncMigrations) project, which may have scope to handle these types of v14 data/schema changes. Although I must note, it's been over a year since I last looked at uSync Migrations, so I'm unsure how much it aligns with v14.

---

I'll close this issue off, as it's not a bug with the CMS itself. But do feel free to re-open if I have misunderstood and there is further information to consider.

**Closed by leekelleher** 2024-10-22 09:06 UTC
Labels: state/needs-more-info, state/needs-investigation, type/bug, affected/v15

**Comment by umbracocommunity** [comment] 2025-09-02 05:51
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/collection-bug-in-version-16/5628/8
