### ISSUE TITLE
ImageCropMode is ignored

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#10770] opened 2021-07-29 16:47 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

When a width, height and imagecropmode are set, it makes no difference to the image generated.

The urls generated are correct:

```
/media/otanyzuj/oezgbx1.png?mode=crop&width=1170&height=334

/media/otanyzuj/oezgbx1.png?mode=max&width=1170&height=334

/media/otanyzuj/oezgbx1.png?mode=min&width=1170&height=334
```

However the image is always returned as cropped.

### Steps to reproduce

Upload an image larger than 1170 x 334 (or what ever dimensions are set in the url) into the media area.

Load the image using the above parameters

The generated image will not change, and will always return the cropped image.

### Expected result / actual result

The image to change depending on the image mode selected

**Comment by AaronSadlerUK** [comment] 2021-07-29 17:16
https://github.com/umbraco/Umbraco-CMS/blob/v9/9.0-rc001/src/Umbraco.Infrastructure/Media/ImageSharpImageUrlGenerator.cs#L25-L27

I quick look in the source seems to force the url to be cropped?

Unless I've read that wrong

**Comment by bjarnef** [comment] 2021-07-29 17:48
I think this is what @Jeavon is working on in the PR: https://github.com/umbraco/Umbraco-CMS/pull/10715

From what I can tell the generated url is NOT correct. In ImageProcessor used in v8 the querystring was using `mode`, but has changed to `rmode` in ImageSharp used in v9.

**Comment by nul800sebastiaan** [comment] 2021-07-30 06:42
I'll close as duplicate of  https://github.com/umbraco/Umbraco-CMS/issues/10725 and indeed it's being worked on. :)

**Closed** 2021-07-30 08:42 UTC
Labels: type/bug
