### ISSUE TITLE
Umbraco breaks HttpAttribute

### ISSUE THREAD

**Issue by wiedikerli** [umbraco/Umbraco-CMS#16006] opened 2024-04-08 08:11 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

When I create a controller which implements `UmbracoApiController` with a http route attribute with parameter, it cannot find the route (404). But when I change to implement `ControllerBase` and route it my self it works. Is there something wrong?
In this [documentation](https://docs.umbraco.com/umbraco-cms/reference/routing/umbraco-api-controllers) i says it should work.

### Steps to reproduce

This does not work (404):
```
public class DictionaryController() : UmbracoApiController
{
	[Route("all/{area?}")]
	public IActionResult All(string? area)
	{
		...
	}
}
```
This works:
```
[Route("umbraco/api/[controller]")]
public class DictionaryController() : ControllerBase
{
	[Route("all/{area?}")]
	public IActionResult All(string? area)
	{
		...
	}
}
```

### Expected result / actual result

I expect that i behaves the same.

**Comment by NguyenThuyLan** [comment] 2024-07-10 04:34
Thanks, @wiedikerli for reporting this issue. Unfortunately, I couldn't replicate the 404 error as you described. In the image below, I used UmbracoApiController similar to yours, and it worked fine. Perhaps you might consider adding the [HttpGet] attribute? I'll close this issue as I couldn't reproduce it.
<img width="458" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/edaf93ee-990d-424c-94e7-425bafb380c6">
<img width="280" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/5f697a51-9ab7-4c24-8cb0-a3866b994dcf">

**Closed by NguyenThuyLan** 2024-07-10 04:34 UTC
Labels: type/bug
