### ISSUE TITLE
Surface controller methods containing "Async" are not registered in the route table

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#12191] opened 2022-03-29 13:10 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Any surface controller methods containing the word "Async" are not registered in the route table, resulting in an error:
`InvalidOperationException: Could not find a Surface controller route in the RouteTable for controller name x`

### Specifics

Post backs of ViewComponent forms to a surface controller method containing the suffix "Async" result in the following. 

```
InvalidOperationException: Could not find a Surface controller route in the RouteTable for controller name ChangePasswordSurface
Umbraco.Cms.Web.Website.Routing.UmbracoRouteValueTransformer.HandlePostedValues(PostedDataProxyInfo postedInfo, HttpContext httpContext)
Umbraco.Cms.Web.Website.Routing.UmbracoRouteValueTransformer.TransformAsync(HttpContext httpContext, RouteValueDictionary values)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Routing.DynamicControllerEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

1) Create a view component into an umbraco template that contains a form. Here is my example - note it's called the action "ChangePasswordAfterResetAsync"

```
    using (Html.BeginUmbracoForm<ChangePasswordSurfaceController>(nameof(ChangePasswordSurfaceController.ChangePasswordAfterResetAsync), FormMethod.Post, new { style = "width:22rem;" }))
    {
        @Html.HiddenFor(m => m.Token)
        @Html.HiddenFor(m => m.Email)
        <section class="container">
            <div class="row">
                <div class="col">
                    @Html.ValidationSummary(false, "", new { @class = "alert alert-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        @Html.LabelFor(m => m.Password, new { @class = "form-label" })
                        @Html.PasswordFor(m => m.Password, new { placeholder = "Password", @class = "form-control", aria_describedby = "passwordHelp" })
                        <div id="passwordHelp" class="form-text">New Password</div>
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "form-label" })
                        @Html.PasswordFor(m => m.ConfirmPassword, new { placeholder = "Password", @class = "form-control", aria_describedby = "passwordHelp" })
                        <div id="passwordHelp" class="form-text">Confirm your new password</div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Change Password</button>
        </section>
    }
```
The Surface Controller:

```
using Microsoft.AspNetCore.Mvc;
using Ninepoint.Core.ViewModels.ViewComponents;
using System.Threading.Tasks;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Security;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;

namespace Protean.Core.Controllers.Surfaces
{
    public class ChangePasswordSurfaceController : SurfaceController
    {
        private readonly IMemberManager _memberManager;

        public ChangePasswordSurfaceController(
            IUmbracoContextAccessor umbracoContextAccessor,
            IUmbracoDatabaseFactory databaseFactory,
            ServiceContext services,
            AppCaches appCaches,
            IProfilingLogger profilingLogger,
            IPublishedUrlProvider publishedUrlProvider,
            IMemberManager memberManager)
            : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
{
            _memberManager = memberManager;
        }


        //Method names for surface controllers can't contain Async
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePasswordAfterResetAsync(ChangePasswordViewModel model)
        {
             return CurrentUmbracoPage();
        }
    }
}
```
After posting back the form the resulting error is shown:

![image](https://user-images.githubusercontent.com/6452616/160617952-f441523a-08b2-43f1-8413-5f41bc6bfe14.png)

Next remove the suffix in the form action and the method name in the controller. The form will post back as expected.

### Expected result / actual result

Based on best practices of naming async methods as awaitable with the suffix "Async", I would expect that method names in surface controllers would function regardless of the text content of the name.

**Comment by jattwood** [comment] 2022-04-10 17:36
After researching this further, it looks like this was a breaking change introducted in .net core 3: 

https://github.com/aspnet/Announcements/issues/351 

I have concluded that this is an issue that will occur only if you are resolving the surface action with the nameof() expression. It would appear that nameof will strip off the "Async" from the end of the action name and therefore provide an inaccurate route upon form submission. For example if you have a surface controller action called "ChangePasswordAfterResetAsync", and you are using the nameof expression to resolve this in your BeginUmbracoForm method as "nameof(ChangePasswordSurfaceController.ChangePasswordAfterResetAsync)" the returned action name will be "ChangePasswordAfterReset" and not "ChangePasswordAfterResetAsync" as I would expect:

![image](https://user-images.githubusercontent.com/6452616/162631769-a3053154-e148-40b1-86f3-71d183d133df.png)

I am going to leave this open as I feel that perhaps an addition to the umbraco default configuration can be made to prevent this behaviour. According to the notice, "This behavior can be disabled by setting MvcOptions.SuppressAsyncSuffixInActionNames to false as part of the application startup"

```
services.AddMvc(options =>
{
   options.SuppressAsyncSuffixInActionNames = false; 
});
```

**Comment by kjac** [comment] 2023-01-09 07:45
@jattwood thank you for reporting and for digging into the root cause. Great job!

We try to align Umbraco as best possible to how ASP.NET Core MVC works without adding too much magic or overriding the default inner workings. Annoying as this is, we don't really want to change the defaults explicitly. Here's hoping it will be fixed in the next LTS version.

For the time being this becomes a documentation issue. I have created a PR for it here: https://github.com/umbraco/UmbracoDocs/pull/4812

**Comment by kjac** [comment] 2023-01-09 12:14
Fixed (documented) in https://github.com/umbraco/UmbracoDocs/pull/4812

**Closed by kjac** 2023-01-09 12:14 UTC
Labels: status/needs-docs, state/in-sprint, state/reproduced
