### ISSUE TITLE
Media items have no link to media in v8

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#4099] opened 2019-01-16 09:47 UTC
When testing out the v8 nightly builds, there is no link to media on the info tab.
It always says "This media item has no link".

![No link to media](https://i.imgur.com/P1QvHSt.jpg "No link to media")

**Comment by bjarnef** [comment] 2019-01-16 12:04
@prjseal it seems to be a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/4072

**Comment by kjac** [comment] 2019-01-16 21:33
PR in #4105

**Comment by nul800sebastiaan** [comment] 2019-01-17 14:32
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4105

**Closed by nul800sebastiaan** 2019-01-17 14:32 UTC
