### ISSUE TITLE
Requst handler in config ignored

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#14534] opened 2023-07-10 09:21 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.1

### Bug summary

The appsetting request handler replacement are ignored.

### Specifics

I have added a char replacement in the appsettings, under Umbrac -> CMS:

That looks like this:

```
 "RequestHandler": {
        "AddTrailingSlash": false,
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": " ",
            "Replacement": ""
          }
       ]
}
```

It should replace spaces with no spaces, instead of - 
But it's ignored.

I have tried jsut for testing.
```
 "RequestHandler": {
        "AddTrailingSlash": false,
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": " ",
            "Replacement": "--"
          }
       ]
}
```

Also with UserDefinedCharCollection instead of CharCollection

### Steps to reproduce

Add a char replacement to appsettings.

Etc:
```
 "Umbraco": {
    "CMS":  {
        "CharCollection": [
               {
                "Char": " ",
                "Replacement": ""
                }
           ]
     }
}
```
Republish a node with a space in the name and check the url a generated the no space instead of - 

### Expected result / actual result

The url of a node to be with out -

**Comment by andr317c** [comment] 2023-07-10 11:14
Hey!

Thanks for reporting the issue, I was not able to reproduce your issue. For me, it worked fine on v11.4.1. 

What I tried:

Added this to my app settings:
``` 
"Umbraco": {
    "CMS": {
      "RequestHandler": {
        "AddTrailingSlash": false,
        "ConvertUrlsToAscii": "try",
        "UserDefinedCharCollection": [
          {
            "Char": " ",
            "Replacement": ""
          }
        ]
      }
``` 
Then I created a content node with a name that had spaces. the URL ended up looking like this:
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/e2bf9a5a-b396-441a-8a9b-6f05316d8e31)

CharCollection has been removed from v11 and up, that's why it's not working anymore. But the UserDefinedCharCollection works as intended.
I see that the documentation is outdated, so I will go ahead and create an issue for it. 😄 

Since I was not able to reproduce your issue I will go ahead and close it. If I am missing anything please let me know and reopen the issue!

**Closed by andr317c** 2023-07-10 11:14 UTC
Labels: type/bug

**Comment by thomashdk** [comment] 2023-07-10 15:29
Strange, tried with UserDefinedCharCollection before. 

But works now :) thanks
