### ISSUE TITLE
Member Last Login Date not updated

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco-CMS#11955] opened 2022-02-08 13:35 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

Property "Last Login Date" on Members isn't updated when a member logs in

### Specifics

This happens when logging in via the MembershipHelper, which calls GetUser with a hardcoded value of False for paramater: userIsOnline: https://github.com/umbraco/Umbraco-CMS/blob/02004342275767b032f71890a5db4f337a8242d0/src/Umbraco.Web/Security/MembershipHelper.cs#L314

GetUser only updates Last login when userIsOnline == True: https://github.com/umbraco/Umbraco-CMS/blob/02004342275767b032f71890a5db4f337a8242d0/src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs#L347-L357

### Steps to reproduce

Login with a member using the MembershipHelper.Login method, check the last login date on the member

### Expected result / actual result

Expected: Current DateTime to be set to property "Last Login Date" on login. 
Actual result: No Change is made to "Last Login date"

**Comment by bergmania** [comment] 2023-01-04 09:13
Duplicate of #11931, fixed in 8.18.4

**Closed by bergmania** 2023-01-04 09:13 UTC
Labels: type/bug
