### ISSUE TITLE
Embed function in RTE removes previous content from RTE

### ISSUE THREAD

**Issue by TimOldenkamp** [umbraco/Umbraco-CMS#7147] opened 2019-11-13 08:50 UTC
The old content in the RTE is deleted after use of the embed function.

## Umbraco version

I am seeing this issue on Umbraco version: 8.2.2

Reproduction
------------

### Bug summary

The embed function removes the content already inserted in the RTE.

### Steps to reproduce

1.  Add text to the RTE (and save the page)
2.  Go to the same RTE and use the Embed function. For example add a Youtube-video.

![Vimeo-movie](https://user-images.githubusercontent.com/960810/68747348-a1a30600-05fa-11ea-8ad7-2cf4eaa2d267.gif)

### Expected result

The old content (for example text) is still in the RTE and the embedded item is added.

### Actual result

Only the new embedded item is in the RTE. The old content (for example text) is deleted from the RTE.

---
_This item has been added to our backlog [AB#3794](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3794)_

**Comment by nul800sebastiaan** [comment] 2019-11-15 00:22
Unfortunately for you, I cannot reproduce the issue on a clean 8.2.2 install, maybe you've upgraded this from an older version and there's a problem with the upgrade? If you have better steps to reproduce in a clean install of 8.2. then let us know, but for now I'll have to close this one as I don't know how to make it fail. :-)

**Comment by TimOldenkamp** [comment] 2019-11-15 12:04
Steps to reproduce:
1. Do a clean install of version 8.2.x or version 8.3.0 with The Starter Kit
2. Change the _Contact - Contact Intro - Rich Text Editor_ to support the Embed
3. Go to the page _Contact_. The default text at the property _Contact Intro_ is 'Lorem ipsum dolor sit amet...' Now press the Embed and insert a YouTube video.
4. The result in the property is the YouTube video but the original 'Lorem ipsum dolor sit amet...' is gone...

Tested en reproduced with Chrome (v78.0.3904.97 64-bit) and Firefox (v70.0.1 64-bit)

**Comment by nul800sebastiaan** [comment] 2019-11-16 15:24
Right, I see what you mean now! I actually typed words in the RTE before inserting the youtube video. 

It seems to work fine if you use an embed when on a new line but indeed I can see it removes the line that you are on if it's not a new line. We'll have to have a look at this!

**Closed** 2019-11-19 09:44 UTC
Labels: category/regression, state/backlog
