### ISSUE TITLE
ModelsBuilder GetModelPropertyType fails when the "itemType" is "Element"

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#14694] opened 2023-08-17 17:16 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

I have a Composition Document type, lets call it "CompMyData". It has some properties, and is on some Document types used for nodes.

I have some code like this, to get the exact alias of a composition property:
var aliasMyProp = CompMyData.GetModelPropertyType(_publishedSnapshotAccessor, x => x.MyProperty).Alias;

but it throws an error when it runs:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'itemType')
   at Umbraco.Cms.Infrastructure.ModelsBuilder.PublishedModelUtility.GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor, PublishedItemType itemType, String alias)
   at MyNamespace.Models.CompMyData.GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor) ...
```

I am using Limbo ModelsBuilder for the model generation, and the code in question looks like this:

```
 public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<CompMyData, TValue>> selector)
     => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
```
		

### Specifics

The error occurs in `Umbraco.Cms.Infrastructure.ModelsBuilder.PublishedModelUtility.GetModelContentType()`

![image](https://github.com/umbraco/Umbraco-CMS/assets/1252593/eb77e813-09e1-46c9-95ab-72669eb13b2c)

### Steps to reproduce

Attempt to use `GetModelPropertyType()` on a Model for a Composition.

### Expected result / actual result

I just wanted to get the property alias.

### Resolution?

Should "Element" be added as an acceptable itemType?

**Comment by Zeegaan** [comment] 2023-08-21 10:21
Hmm I cannot reproduce this sadly 😕 

This is me on 10.6.1: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/1ef16cf1-49d6-4936-b6b1-26cbd66fffc1)

**Comment by hfloyd** [comment] 2023-09-05 20:58
Hi @Zeegaan , Thanks for looking into this. Do you see what the "itemType" is returning when you step into that method? When I run it, "itemType" = "Element" - which isn't included in the switch statement...

**Comment by Zeegaan** [comment] 2023-09-07 15:20
Yea apparently I just forgot to re-build my models after switching to the Limbo modelsbuilder 🙈 
We had a talk and agreed this is a bug, and have made a PR implementing your suggestion @hfloyd 🙌 
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14776

**Closed by Zeegaan** 2023-09-07 15:20 UTC
Labels: state/needs-reproduction, type/bug

**Comment by abjerner** [comment] 2023-09-07 15:25
Awesome 👍 

I hadn't even spotted this. I tried to do the same as Umbraco's models builder for my package, so not sure if something has changed in Umbraco since then, or I just ended up doing this part slightly different.
