### ISSUE TITLE
Unable to schedule publishing multilingual content

### ISSUE THREAD

**Issue by iPszota** [umbraco/Umbraco-CMS#9927] opened 2021-03-03 08:58 UTC
A brief description of the issue goes here.
Endpoint /umbraco/backoffice/UmbracoApi/Content/PostSave returns status code 404 upon clicking 'Schedule', after setting 'Publish'date for one, more or all language variants of a content item.

Response:
')]}',
{"Message":"No variants flagged for saving"}'

Umbraco version:
8.11.1

Reproduction

1. Under 'Settings' section, set permission 'Allow varying by culture' to enabled/true for a document type.
2. Under 'Content' section, create content based on document type.
3. Select 'Schedule' and set scheduled publishing for one or more language variants (reproduced when setting only Publish or Publish and Unpublish date).
4. Click 'Schedule' button.

Notification message with success message 'Content saved. [name(s)-of-language-variant(s)] saved' or similar.

Actual result:
5a) Notification message is shown with error message 'Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/Content/PostSave
5b) Browser dev tools show response message: ')]}',
{"Message":"No variants flagged for saving"}'

**Comment by nul800sebastiaan** [comment] 2021-03-03 10:14
Hi @iPszota, that is very strange! 
Unfortunately all this works for me on a clean 8.11.1 install:

https://user-images.githubusercontent.com/304656/109790225-78ecb880-7c11-11eb-827a-105aab247348.mp4

I'd encourage you to have a look at if your install might be missing something. Maybe an upgrade gone wrong? Maybe we're missing some info to reproduce the issue? I'll close this for now but if you have more info we can give it another look.

**Closed by nul800sebastiaan** 2021-03-03 10:14 UTC

**Comment by iPszota** [comment] 2021-03-12 10:34
Hi @nul800sebastiaan !

Thanks for checking it and sorry for the delayed reply!
I have installed 8.11.1 and on a fresh install, it surely works.

However, I believe I have found something interesting and I need someone to point me in the right direction on how to solve this. When I do a save and schedule on the fresh install and checking the data within the POST data, I can see that at least one item is marked for saving and the release date is set:

![image](https://user-images.githubusercontent.com/6377287/110927807-60be1d00-8326-11eb-91ce-40f48ea7e0d8.png)

However, when I do the same on the production Umbraco which is now updated to 8.11.1 the Save property is false for every variant. Only the release date is not null on the variant I have marked for scheduling.

Does this help? Could you please let me know how to get rid of this error?

Many thanks,
Istvan
