### ISSUE TITLE
Custom Media Folder Error

### ISSUE THREAD

**Issue by mov3nforward** [umbraco/Umbraco-CMS#7214] opened 2019-11-22 14:57 UTC
A brief description of the issue goes here.

## Umbraco version

I am seeing this issue on Umbraco version: V8

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I have followed the instruction and the image are being uploaded to the "images" folder, BUT the thumbnail in back office is showing the default icon instead of the image! https://our.umbraco.com/documentation/reference/config/filesystemproviders/

### Specifics

I have done some research and determined that the "umbracoMediaVersion" table is not being updated with the image file path which is causing the issue. If I remove the above class from the application the images are back to being uploaded to the "Media" folder and the icons work in the back office. It seems that only part of Umbraco now understands that there is a new "images" folder. 

### Steps to reproduce

Follow the instructions on this page to create a custom media folder. Add a media picker to a document type, create a page from the document time, pick an image from the Media section. You will see that the default image icon instead of the actual image shows. 

### Expected result

I would expect that this new way of creating custom media folders works the same way as V7, but it doesn't.

### Actual result

The default image icon shows instead of the actual image.

**Comment by kjac** [comment] 2019-11-26 07:51
@mov3nforward I can't reproduce this on the latest source. Which version do you see this on?

I dumped this in `App_Code` (from [the docs](https://our.umbraco.com/documentation/reference/config/filesystemproviders/)):

```cs
using Umbraco.Core.Composing;
using Umbraco.Core;
using Umbraco.Core.IO;

namespace Umbraco8Examples.Composition
{
    public class SetMediaFileSystemComposer : IUserComposer
    {
        public void Compose(Umbraco.Core.Composing.Composition composition)
        {
            composition.SetMediaFileSystem(() => new PhysicalFileSystem("~/custommediafolder"));
        }
    }
}
```

...and uploaded some images to the media library. The uploaded files ended up in `/custommediafolder` on the file system:

![image](https://user-images.githubusercontent.com/7405322/69609424-c4d1aa80-1029-11ea-8abe-02c9e891a4f6.png)

...and the images could render just fine in backoffice and when requested from the frontend:

![image](https://user-images.githubusercontent.com/7405322/69609460-e03cb580-1029-11ea-9155-0121bdd46840.png)

**Comment by nul800sebastiaan** [comment] 2019-11-28 08:48
@mov3nforward - I'll close this for now as it can't be reproduced. Let us know if you have new steps to reproduce!

**Closed by nul800sebastiaan** 2019-11-28 08:48 UTC
