### ISSUE TITLE
V14-RC3 - Not able to page back when having many content nodes in the content tree

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#16237] opened 2024-05-07 20:44 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When the content tree has a lot of nodes a "Load more" button becomes visible but after clicking this there is no indication of what page you are on. There is also no indication of the total items or a way to go to the previous page.

https://github.com/umbraco/Umbraco-CMS/assets/24605285/2e80790a-dc26-4214-bc33-67c6d1c31348

### Steps to reproduce

1. Create a lot of content nodes.
2. Scroll down and press the "Load more" button

Tip:
To quickly create a bunch of content nodes you can add a API endpoint in the program.cs like this:
```csharp
app.MapGet("/create-content/{number:int}", ([FromServices] IContentService contentService, int number) =>
{
    for (int i = 0; i < number; i++)
    {

        contentService.CreateAndSave($"Home-{Guid.NewGuid()}", -1, "home");
    }

    return Results.Ok("Done :)");
});
```

### Expected result / actual result

I would expect to see the total content items, load more, and be able to go back if pagination is the way we want this tree to function.

Alternatively I think it would be a better solution to use a virtual scroller here as this wouldn't require showing the total nodes and you would always be able to scroll back up to the other content nodes.

**Comment by Zeegaan** [comment] 2024-05-16 09:44
Heyo! 👋 
I think this is more of a feature request than a "bug", as i agree it's confusing, but it's by design 🤣 
I will pass this on to the frontend team to see if this can be changed 😊

**Comment by Zeegaan** [comment] 2024-05-16 10:58
I am getting word that it should be fixed in rc4, please re-open this if the issue still persists there 😁

**Closed by Zeegaan** 2024-05-16 10:58 UTC
Labels: state/needs-investigation, type/bug
