### ISSUE TITLE
Unable to sort columns in list view

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#10307] opened 2021-05-21 11:16 UTC
### Which Umbraco version are you using?

8.13.0

### Bug summary

The icon to drag and drop columns to sort them in a custom list view editor window are invisible and so you can't sort columns.

If you inspect the HTML, the svg icons are there but they have no width or height and so don't appear and can't be selected.

Giving them a width and height they appear and work as expected.

![list view sort](https://user-images.githubusercontent.com/32468062/119128952-35466580-ba2e-11eb-8ec7-5107cf465f84.JPG)

### Steps to reproduce

Edit a custom list view and try to order the columns.

---
_This item has been added to our backlog [AB#12101](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12101)_

**Comment by nul800sebastiaan** [comment] 2021-05-25 09:46
Thanks @Wiggee11, I can reproduce this and it used to work in 8.12, so I'll mark this as a regression bug we should look at. I think it must have something to do with switching to SVG icons. Strange that it does work on the Layouts list below that, they're also SVGs. 🤔

**Comment by Wiggee11** [comment] 2021-05-25 12:36
It also works fine editing a list view Data Type directly.

**Comment by nul800sebastiaan** [comment] 2021-05-25 14:21
Ah that's a good workaround, thanks for highlighting that!

**Comment by bjarnef** [comment] 2021-05-28 06:43
@nul800sebastiaan I think this has already been fixed in `v8/contrib` branch.

![image](https://user-images.githubusercontent.com/2919859/119941307-b6eb4580-bf90-11eb-809c-9b6f133f83a4.png)

**Comment by nul800sebastiaan** [comment] 2021-05-28 07:07
@bjarnef That's the workaround. The problem is when you try to do this on the document type > list view content app: 

![image](https://user-images.githubusercontent.com/304656/119944054-18f97a00-bf94-11eb-8376-5ca57a4b869e.png)

**Comment by nathanwoulfe** [comment] 2021-05-28 07:09
I'm guessing the issue with the SVG icons is they don't have dimensions defined. Not an issue for icon fonts because they'll inherit font-size, but SVG will need explicit height and width.

**Comment by bjarnef** [comment] 2021-05-28 07:13
Ahh okay, will have another look. Not sure why it need to set width to zero here.

![image](https://user-images.githubusercontent.com/2919859/119944708-e56b1f80-bf94-11eb-866c-0b7fc8bc2d99.png)

**Comment by bjarnef** [comment] 2021-05-28 08:27
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10351

**Closed** 2021-06-08 08:19 UTC
Labels: state/in-sprint, status/regression, type/bug
