### ISSUE TITLE
v12 RC1 login error on Umbraco Cloud

### ISSUE THREAD

**Issue by jbreuer** [umbraco/Umbraco-CMS#14264] opened 2023-05-17 14:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc1

### Bug summary

I cloned an Umbraco Cloud project (11.3.1) locally and upgraded it to `12.0.0-rc1` with the following command: `dotnet add package Umbraco.Cms --version 12.0.0-rc1`.

This worked locally, but when I pushed the changes with GitHub to Umbraco Cloud I got the following error:

`Method not found: 'Boolean Microsoft.IdentityModel.Tokens.TokenUtilities.IsRecoverableConfiguration(Microsoft.IdentityModel.Tokens.TokenValidationParameters, Microsoft.IdentityModel.Tokens.BaseConfiguration, Microsoft.IdentityModel.Tokens.BaseConfiguration ByRef)'.`

### Specifics

The error happens after login on this URL: https://umbraco-trial.euwest01.umbraco.io/umbraco

### Steps to reproduce

The steps are already in the summary.

![image](https://github.com/umbraco/Umbraco-CMS/assets/5444597/87a33e13-0d5d-46d5-923c-2c9784885d14)

### Expected result / actual result

After upgrading to Umbraco 12 RC locally it should also work on Umbraco Cloud.

**Comment by jbreuer** [comment] 2023-05-17 15:28
This seems to be the same error as reported here: https://github.com/umbraco/Umbraco-CMS/issues/14265. But this error happens for the backoffice.

**Comment by bergmania** [comment] 2023-05-19 07:57
Hi @jbreuer..
Thanks for reporting. I'm pretty sure the root cause is the same as in https://github.com/umbraco/Umbraco-CMS/issues/14265, so Ill close this one.

**Closed by bergmania** 2023-05-19 07:57 UTC
Labels: type/bug, affected/v12

**Comment by jbreuer** [comment] 2023-05-23 07:41
I upgraded to v12 RC2 on Umbraco Cloud and now the backoffice is working again.
