### ISSUE TITLE
Manual sorting of the images in Multiple Media Picker doesn't work in Umbraco 8

### ISSUE THREAD

**Issue by ragivi** [umbraco/Umbraco-CMS#5504] opened 2019-05-21 14:43 UTC
I want to sort the images in a Multiple Media Picker but it doesn't work.

The version of the application is Umbraco 8.0.2

**Comment by nul800sebastiaan** [comment] 2019-05-21 15:38
This seems to work on the latest code, so should work in the upcoming 8.1.0.

I also just tested it in 8.0.2 and it seems to work for me, might be something in your install. Let us know if you have detailed steps to reproduce the problem on a clean version of 8.0.2.

![image](https://user-images.githubusercontent.com/304656/58110150-46fe9380-7bef-11e9-85bc-3ce0172bcc46.png)

**Comment by ragivi** [comment] 2019-05-22 08:33
Hi @nul800sebastiaan 

I think we're not in the same view or field, I'll give you an example of what I mean.

Thanks!

![image](https://user-images.githubusercontent.com/2657922/58159558-1107f080-7c7d-11e9-995c-ddb36fab4b54.png)

**Comment by MickeyThomsen** [comment] 2019-05-28 17:36
I can confirm this is not working. I have tried in multiple V8 installations. When trying to drag around the images, the cursor changes to a "not allowed" cursor and the images are not moved. This functionallity is working in V7 installations.

**Comment by alexchrgr** [comment] 2019-05-29 21:24
Just as ragivi describes it is not working in both of my two installations since 8.00 for me. I thought upgrading to 8.01 and 8.02 would make it but it didn't.

**Comment by FransdeJong** [comment] 2019-08-08 11:24
@nul800sebastiaan  This issue is still present in V8.1.1
If you add the multiple media picker there's no way to sort the images. 
I don't know what your screenshot is about but this issue is about the screenshot of @ragivi 

Can you please reopen this issue or elaborate on how we can get sorting to work?

**Comment by dawoe** [comment] 2019-08-08 11:31
@nul800sebastiaan I can confirm this behavior. And just checked with V7. There you were able to sort them

**Comment by nul800sebastiaan** [comment] 2019-08-08 11:32
D'oh!

https://media.giphy.com/media/xT5LMzIK1AdZJ4cYW4/giphy.gif

Not sure I was thinking here 😮

**Comment by stevemegson** [comment] 2019-08-08 13:36
This turns out to be nice and easy, I've submitted a PR. The check for "disable sorting if `$scope.isMultiPicker` is false" runs before we've set up `$scope.isMultiPicker`, so sorting is always disabled.

**Comment by nul800sebastiaan** [comment] 2019-08-08 14:00
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6078

**Closed** 2019-08-08 14:00 UTC
Labels: community/pr, type/bug

**Comment by nul800sebastiaan** [comment] 2019-08-08 14:03
Cherry picked into 8.1.2 - https://github.com/umbraco/Umbraco-CMS/commit/88349c6b6613d16592d7d5f79d59f4b0dede800c

**Comment by suedeapple** [comment] 2019-08-12 08:51
Just wondered if this was disabled in order for the sort order to be retained on "multilingual sites".  Fingers crossed this will just "work" :-)

**Comment by nul800sebastiaan** [comment] 2019-08-12 09:45
@suedeapple Can you elaborate please? I would assume that if the sort changes on a property that is marked as multilingual then it shouldn't change on all of the languages, just the language that the sort has been done on. Is that what you mean?

**Comment by suedeapple** [comment] 2019-08-12 11:22
Depends if you have "vary by culture" turned on for that property.  I just can't at the moment get into my head how this is going to look/feel visually, and also from a UX standpoint.  

Just seems "Odd" how the existing sort has been mysteriously been turned off at some point.  Maybe by reason, to ensure a full postback/render occurs to reflect any new sort orders across node variants (cultures)

**Comment by stevemegson** [comment] 2019-08-12 12:04
I'm almost certain that this was an unintended side effect of another change, rather than sorting being deliberately turned off.

Sorting items within the picker is really no different to removing an item and re-adding it again at the end of the list, so it shouldn't cause any problems that you wouldn't also encounter by removing and adding items.

**Comment by nul800sebastiaan** [comment] 2019-08-12 18:21
Yeah it was a bug introduced in 8.1.0, worked fine in 8.0.x
