### ISSUE TITLE
Scheduled Publishing DateTime Picker should handle daylight saving time

### ISSUE THREAD

**Issue by wifr001** [umbraco/Umbraco-CMS#3028] opened 2018-09-24 15:17 UTC
We are currently EDT Eastern Daylight Time UTC/GMT -4 hours. Starting November 4th we will be EST Eastern Standard Time UTC/GMT -5 hours. If we set a Scheduled Publishing date on a node occurring after nov. 4th there is a 1 hour difference between picker and displayed date.

Reproduction
------------

### Specifics

Umbraco 7.12.3
Chrome 69.0.3497.100
Machine timezone EDT Eastern Daylight Time UTC/GMT -4 hours

### Steps to reproduce

1. Go to "Info" tab of a node.
2. Click on Set date
3. Choose a date after nov. 4th
4. Change time et observe a 1 hour difference

### Expected result

The picked time should be same as the displayed time.

### Actual result

There is a 1 hour difference

![heure](https://user-images.githubusercontent.com/36507676/45960836-1bd58d00-bfeb-11e8-9bb3-6937056c1fe4.png)

**Comment by nul800sebastiaan** [comment] 2018-12-18 13:06
It should.. but.. it's not easy! 

If you're feeling brave then we'd love to see an attempt!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:27
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:27 UTC
Labels: community/up-for-grabs, help wanted, type/feature

**Comment by mirkomaty** [comment] 2020-10-08 10:05
This is the situation:

1. You want to enter the client local time.
2. You want to store the according server local time.
3. You only have the current time offset between client and server time

=> You can't handle the 1 hour offset problem.

There are 2 possible solutions:

Solution 1: Store the selected time as UTC. Whatever local time you enter, convert it to UTC before you store it. Since UTC doesn't have summer / winter time, there is a chance to convert the values properly. Downside: It's a breaking change to all systems, which have previously stored publish / unpublish dates. Maybe it's possible to adjust given time values to UTC during upgrade. To illustrate this solution, please have a look at this code:


```
static void Main( string[] args )
{
	var dt = new DateTime(2020, 11, 11, 10, 0, 0);
	Console.WriteLine(dt.ToUniversalTime());
}
```
Currently my local time zone is UTC+2. In winter we have UTC+1. The output of the above code is

11.11.2020 09:00:00

That's exactly, what we want, since it resolves to 10:00 _at the given date_. The .NET Frameworks converts the time not using the time zone offset, but using the locale (aka CultureInfo). The locale knows, if a daylight saving offset has to be applied at a given date. I don't know, if such a conversion can be done properly on the JavaScript side. If this is not the case we need to determine the region info of the client and transmit it to the server together with the client local time. Then the conversion can be done on the server side using the CultureInfo class.

It may be possible to convert the UTC value to the local time of the server and store this value (=> avoids a breaking change). If this is possible, the solution would be to use the locale info for conversion instead of the time offset.

Solution 2: Roll back the whole local server time implementation. There are anyway not many sites which benefit from this feature. 

Note: This feature as described at the beginning of this post cannot be fixed in any way. So the HQ has to decide, which of the two solutions it will go for. Any community effort only makes sense after this decision.

I hope my post is helpful so that someone can make that decision.

**Comment by nul800sebastiaan** [comment] 2020-10-08 10:19
> Solution 1: Store the selected time as UTC.  

This would probably be the best, but it will break all existing stored date/times. Ideally, everything would be stored as UTC, which we really want, but again.. HUGE amount of work. 

> Solution 2: Roll back the whole local server time implementation.

Maaaaaany people benefit from it! And yes, 2 days a year there may be some DST issues. 😬

**Comment by mirkomaty** [comment] 2020-10-08 11:02
> And yes, 2 days a year there may be some DST issues.

2 days a year? My customers are complaining since two weeks... ;-)

Well, I think we can manage the situation somehow. If you try the following in Javascript:

```
var d = new Date(2020,11,11,10,0,0);
var u = d.toUTCString();
```
u contains the correct time (9:00 at my time zone). Transmit this UTC value to the Server. So we don't have to bother about the current time offsets on the client side. Just leave the time as the user enters it and transfer the according UTC to the server. In the API controller parse the value as UTC and convert it to local time. I don't know why this solution shouldn't work. But maybe I oversee something here.

**Comment by nul800sebastiaan** [comment] 2020-10-08 11:18
> 2 days a year? My customers are complaining since two weeks... ;-)

Argh, you're right it will be a month or sometimes 2 weeks or.. well whatever cross-timezones. Sorry :)

Sure, gives me `Fri, 11 Dec 2020 09:00:00 GMT` - which is fine, but we can't know what the intended timezone before upgrading was. I actually think we already store this as UTC, but then offset it with your local time in javascript so you don't have to enter a UTC time. 

So I think the problem is that we don't offset it against the future time but against the current time. So, once your DST starts/ends it might actually be displayed correctly again? Not sure 🤯

**Comment by mirkomaty** [comment] 2020-10-08 11:36
It took me a while to determine, where the publishing date is stored in v8. But I can confirm the following:

Whatever value I enter, in both systems (7.6 and 8.7) I'll see the new Value (which is 1 hour later) after a page refresh. And in both versions this new value is stored the database. It can't be UTC in the database, because UTC would be 1 hour earlier than the entered value. So, in my opinion you store local time values. That leaves us with the shown solution:

User enters 11 Dec 2020 10:00 MEZ
toUTCString() converts to 11 Dec 2020 09:00 GMT
API controller parses UTC 11 Dec 2020 09:00 GMT
converting back to server locale will result in 11 Dec 2020 10:00 MEZ (if it is in the same time zone a the client)

The last value will be stored. This will give you backwards compatibility, because it's the server locale.
