### ISSUE TITLE
NotificationsService places notification under the infiniteEditor?

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#10210] opened 2021-04-30 22:37 UTC
![image](https://user-images.githubusercontent.com/12418214/116760253-6540b100-aa0c-11eb-9002-4435f177b4e5.png)

Hopefully, the picture says it all... (Umbraco 8.13.0, UForms 8.7.1) (maybe infinitemode overlay has a different notification?)
In this instance it's when `umbRequestHelper.resourcePromise` returns a 500 error

(Which also was a little undocumented that 500 errors get a umbYSOD if debug=true, also no way to remove the core notification if we wanted to handle it ourselves?)
```
myResource.getLists()
            .then(
                function (response) {
                    $scope.lists = response;
                    if ($scope.listId) {
                        $scope.changeList();
                    }
                },
                function (err) { notificationsService.error(err.errorMsg); }
            )
            .catch(function (err) { notificationsService.error(err.errorMsg); });
```

**Comment by nul800sebastiaan** [comment] 2021-05-03 20:07
Thanks, yeah, it is a UX problem that we would love some help with, it happens in more places. I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9614

**Closed by nul800sebastiaan** 2021-05-03 20:07 UTC
