### ISSUE TITLE
Document Type description is not shown in "content node create dialog" in V8

### ISSUE THREAD

**Issue by SoerenDeger** [umbraco/Umbraco-CMS#4692] opened 2019-02-21 11:48 UTC
If I set a description text in a document type, this description is not shown if I will create a new content node in content section.

The issue is in this nightly build of V8: 
8.0.0-alpha.58.2430

Reproduction:
1. Go to Settings Section
2. Add a description to an existing Document Type directly below the field of document type name
3. Save the document type
4. Go to Content Section
5. Right click context menu > Create....
6. In the dialog for choosing an existing document type for the new content node, there is NO description shown.

**Comment by kjac** [comment] 2019-02-25 08:28
I'm not seeing this on the latest build:

![image](https://user-images.githubusercontent.com/7405322/53323871-a2b2cc80-38df-11e9-8753-c850741c07fc.png)

**Comment by nul800sebastiaan** [comment] 2019-03-07 10:53
I also can't reproduce, must have been fixed in the mean time.

**Closed by nul800sebastiaan** 2019-03-07 10:53 UTC
