### ISSUE TITLE
RichText Required Field Visual Indication Issue

### ISSUE THREAD

**Issue by wadrschall** [umbraco/Umbraco-CMS#12187] opened 2022-03-28 21:22 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

If you mark a rich text property as "Required" and then leave it blank, it doesn't highlight red and show an error like other text fields. Instead, it allows the content to be "saved" but never "published". It adds a small icon to the content listing to show the content is in the saved state, but because there is no other error indication, this leaves an end user very confused why their content changes are not showing. Unless you notice the small icon difference in the tree menu OR click on the Info tab and look at the status that indicates pending changes, the end user wouldn't know there were issues. This is especially confusing because if you click "Save and Publish", it acts as if it succeeded, even though it only went into a saved state.

### Specifics

If you mark a rich text property as "Required" and then leave it blank, it doesn't highlight red and show an error like other text fields. Instead, it allows the content to be "saved" but never "published". It adds a small icon to the content listing to show the content is in the saved state, but because there is no other error indication, this leaves an end user very confused why their content changes are not showing. Unless you notice the small icon difference in the tree menu OR click on the Info tab and look at the status that indicates pending changes, the end user wouldn't know there were issues. This is especially confusing because if you click "Save and Publish", it acts as if it succeeded, even though it only went into a saved state.

### Steps to reproduce

Add a mandatory required to a rich text field in any doctype. Then edit as an end user in the backoffice. Put in text to the field, and publish (this works great). Then remove the text (clear it out) and click save/publish. It will not error, but instead you'll notice the icon in the tree menu showing its in a saved/pending state. You can continue hitting save/publish and it will not indicate an issue on the front end on why the content will not publish.

### Expected result / actual result

This field type should work the same as a text field. If left blank AND is set to required, it should highlight red with an error message and should not let you save OR save/publish until the error is resolved (just as the normal textstring prop type).

**Comment by nul800sebastiaan** [comment] 2022-03-29 07:53
Hey there @wadrschall - I am not sure how to reproduce, what am I doing differently please?

https://user-images.githubusercontent.com/304656/160561705-4e0fb0f3-5596-496b-a0c3-86c07ed72495.mp4

**Comment by wadrschall** [comment] 2022-03-30 02:04
Sebastiaan,

I've recorded a video as well to show this issue in action. Please let me know if you have any questions.

Rob

https://user-images.githubusercontent.com/50219294/160736019-6f494606-9c7c-4b5a-b956-39715ecf5ccf.mp4

**Comment by nul800sebastiaan** [comment] 2022-03-30 09:32
That's so weird! Same setup works fine for me.. 

https://user-images.githubusercontent.com/304656/160799917-2a894272-68c6-4400-9fef-9c664b75155b.mp4

But good that you found the console error, I was going to ask about that. Can you go to the network tab and look at that request when it fails, there should be something in the response that could give some pointer as to what is going on.

**Comment by wadrschall** [comment] 2022-03-30 19:01
There isn't much in the Response of the PostSave... But this is what was in there:

`Bad Request}],"notifications":[],"ModelState":{"_Properties.introCopy.invariant.null.value":["Test Validation"]},"metaData":null}`

I guess my other question is why is it even posting back at all if the required nature hasn't been satisfied yet?

Rob

**Comment by wadrschall** [comment] 2022-04-04 02:12
@nul800sebastiaan 

Just confirming if you needed anything else from me to confirm this is an issue or if there's an idea on when it might be resolved.

Thanks,
Rob

**Comment by nul800sebastiaan** [comment] 2022-04-04 08:10
Yeah I'm afraid we need a way to reproduce it @wadrschall - if you can reproduce on a clean test install of 9.4.1 then it would be good to know how. Right now I'm suspecting something in your environment being off, since we haven't had any other reports and we didn't change anything in validation for quite a few versions.

If you CAN reproduce it in a clean. new 9.4.1 install, then I can offer that you zip up that test site + database for us to have a look at.

**Comment by wadrschall** [comment] 2022-04-04 13:59
I know its not an environment issue because it happens both on my desktop, laptop and on the development server (each running a different OS, IIS, etc.

I don't know what series of items has to be in play for this to happen. I'll try it on a fresh install, but it could be a combination of packages as well (usync, etc) that are installed.

Rob

**Comment by kjac** [comment] 2023-01-09 11:33
Hi @wadrschall,

I can't reproduce this on V10 either (see screencast below), so I'm going to close this issue now.

If you have managed to reproduce it on a clean install, please feel free to share your findings 😄 

![12187](https://user-images.githubusercontent.com/7405322/211298779-6a8d340c-b3f1-4b56-9cd3-a7d3e34ba23a.gif)

**Closed by kjac** 2023-01-09 11:33 UTC
Labels: state/needs-more-info, type/bug
