### ISSUE TITLE
Timezone not set correctly

### ISSUE THREAD

**Issue by Arjanvanmaren** [umbraco/Umbraco-CMS#11948] opened 2022-02-07 19:45 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

If I select a day in umbraco date picker for instance 07-02-2021, our backend shows that it is 07-02-2021 00:00 utc if I read it from the umbraco model.

What I should expect is that the utc time is 06-02-2021 23:00 utc because that is what 07-02-2021 00:00 is in Amsterdam timezone. 

It doesn't matter if I set the following switch on or off.
![image](https://user-images.githubusercontent.com/16067826/152859662-07c18063-34e9-4c95-8e33-b4eea1906e4b.png)

### Steps to reproduce

Add a document type with a date and pick a date with the switch "Offset time" on and off. Then see what the datetime object looks like when retrieved from umbraco and see that the timezone is not applied.

### Expected result / actual result

I would expect the datetime to be local datetime displayed in umbraco with the "Offset time" switch turned on. In the backend code it should convert it to utc datetime.

**Comment by nul800sebastiaan** [comment] 2022-02-08 08:47
Hi there @Arjanvanmaren. I think you're misunderstanding what will happen. 

If you enable the offset switch, everything should look just the same in the browser, you can pick a time as it is in YOUR timezone and that time will be stored and displayed as being in your timezone to you. 

When a user from a different timezone logs in, they will see the time selected as it is in their timezone.

What we actually store in the database is the time that it is on the server, we don't store UTC (unless the server happens to be on UTC time).

So in this example, one of my date time pickers has the offsset turned off, the other one has it turned on. I selected 14:00 on both pickers and as you can see in the database, the time is either stored as selected or as the time on the server (in my case, the server is indeed set to UTC.

![image](https://user-images.githubusercontent.com/304656/152950316-7a1fc325-8160-4342-b044-b13ac5760237.png)
 
For now I'm going to close this one since as far as I can tell, this works as expected, as it has worked for years. Let me know if I'm missing anything!

**Closed by nul800sebastiaan** 2022-02-08 08:47 UTC
Labels: type/bug

**Comment by LarryBS** [comment] 2023-12-29 18:53
Still have a simliar problem in v. 10.8.3.  Is it going to be fixed?

**Comment by greystate** [comment] 2024-04-20 17:13
I'm seeing this in Umbraco `13.2.2` as well.

I kind of understand that the value stored is "just" the datetime value (does a datetime in the database have any timezone information?). But it's very confusing to get a DateTime with `.Utc` when it's not really UTC...

**Comment by abjerner** [comment] 2024-04-21 19:51
This issue has existed at least since Umbraco 7, and still exists in Umbraco 13 as mentioned by @greystate. I haven't checked with Umbraco 14. The problem is that the value is saved in the database as local time, but when later read from the database, its returned with the same date and time, but with the `Kind` property set to `Utc` instead of `Local`. This affects the date picker and date time property editors, but also the `CreateDate` and `UpdateDate` properties of `IPublishedContent` and `IContent`. 

I had a conversation about this with some HQ members a while back. I thought it was an issue on GitHub, but I can't find it now. But essentially to fix this in Umbraco, the date and time should instead be saved as UTC in the database. This might be easy if only looking forward, but handling upgrades and migrations would add another level of complexity. E.g. because there is no reliable way to determine the time zone used for the saved values, although one could assume that it's saved as local time according to the current machine.

When searching on GitHub for this, I found [this issue](https://github.com/umbraco/Umbraco-CMS/issues/14053) for Umbraco 8. Kenn tried to reproduce the issue, but since his example saves the a timestamp in UTC (which would be different from saving from the backoffice), he couldn't reproduce the issue.

For existing sites, or generally if this isn't fixed in Umbraco going forward, there are a few ways to mitigate this. E.g. is the date and time part is technically correct, but the problem is with the UTC offset, one can create a new `DateTime` value from the ticks of the returned `DateTime` instance:

```csharp
DateTime createDate = new DateTime(Model.CreateDate.Ticks, DateTimeKind.Local);
```

This however won't fix the issues if for instance two servers in different time zones, but use the same database. Or even just of sending a database copy to someone in another timezone.

For the date time picker, I've created my own property editor, which works similar to Umbraco's, but instead saves the value in UTC (see [here](https://github.com/abjerner/Limbo.Umbraco.Time/blob/v1/main/src/Limbo.Umbraco.Time/wwwroot/Scripts/Controllers/DateTime.js#L81) and [here](https://github.com/abjerner/Limbo.Umbraco.Time/blob/v1/main/src/Limbo.Umbraco.Time/wwwroot/Scripts/Controllers/DateTime.js#L97)).
