### ISSUE TITLE
V14-RC2: Document types, possible to create a property without a label

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16168] opened 2024-04-26 08:57 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When adding a property to a document type its possible to save the new property in the side modal before you have entered a label 

eg you can save this dialog while the name is empty 
![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/5596b8d7-565b-4015-955c-c90cf2d73833)

if you do this then the property is added to the document type with no name

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/f4642030-0955-477f-b79c-d998ef28e8d3)

-  A Save failed (as expected)

- if you then attempt to fix this by adding a label the alias isn't created
![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/eb6f7fa6-b485-4726-be07-1697622fb3d6)
- A Save does create an alias - but you don't know what it will be until, you save (it should happen as you type?)

### Steps to reproduce

- add a new property to a document type but don't enter a name
- you shouldn't be able to 'add' ?

---
_This item has been added to our backlog AB#42503_

**Comment by Zeegaan** [comment] 2024-04-30 10:05
I can definitely reproduce this 😁 Thanks for reporting 🐛

**Comment by Zeegaan** [comment] 2024-05-01 09:55
Found out this was a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16108
closing this one 😁

**Closed** 2024-08-19 07:58 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v14
