### ISSUE TITLE
Content rollback does not work when single language is available only

### ISSUE THREAD

**Issue by psmoq** [umbraco/Umbraco-CMS#9590] opened 2020-12-22 09:56 UTC
When we have only one single language defined in Backoffice settings, rollback process of given document will skip all its properties with **Allow vary by culture** set to _true_ - the rollback is considered as successful but it is incomplete in fact (some properties keep old values).

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.0

Reproduction
------------

### Specifics

Issue seems to not be related to any specific browser - occurs always and everywhere. After a quick look on source code, it seems that those properties are simply skipped during rollback process. 

### Steps to reproduce

1. Prepare document type with some property (e.x. Textbox) with **Allow vary by culture** enabled. 
2. Add node of newly created doctype in the content tree and fill it with some sample value e.g. _test_.
3. Update the value from _test_ to _test123_, then save and publish changes.
4. Make sure that you have only one single language configured in Backoffice settings.
5. Go back to the created document and try to rollback to the version with previous value _test_.

### Expected result

Rollback is successful and property value is set to _test_ (previously _test123_).

### Actual result

Rollback is successful (no error occurred) but property value is still set to _test123_.

**Comment by nul800sebastiaan** [comment] 2021-01-06 14:18
Thanks @psmoq! We're aware but have not found time to work on this yet I'm afraid. I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8642

**Closed by nul800sebastiaan** 2021-01-06 14:18 UTC

**Comment by psmoq** [comment] 2021-01-07 09:28
Thank you @nul800sebastiaan but linked issue is something opposite than I've described above.

In my investigation it seems that invariant properties are being rolled back successfully - the problem occurs when you want to rollback variant-supported property but there is only 1 language available. Could you revert my issue back and consider fixing it?

Thanks in advance.

**Comment by nul800sebastiaan** [comment] 2021-01-07 10:11
I've added to the other issue that we should check the other way around as well 👍
