### ISSUE TITLE
Custom Member Index not updated on member save - text fields don't update at all even after index rebuild

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#9723] opened 2021-01-26 22:47 UTC
This bug is identical to https://github.com/umbraco/Umbraco-CMS/issues/9095 which was closed back in October but continues in 8.9.1 and into 8.10.1 for _custom_ member indexes

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.1

Reproduction
------------
 
1) In Settings > Examine Management > Click on your custom member index

2) Do a search for a member and open up the blade for details - note the first name:
![image](https://user-images.githubusercontent.com/6452616/105915016-3544d480-5ffd-11eb-9d17-bf9a03d91513.png)

3) Go into the members section and update a custom field (firstName) and click save:
![image](https://user-images.githubusercontent.com/6452616/105915091-50afdf80-5ffd-11eb-99bb-a4102e579561.png)

4)  In Settings > Examine Management > Click on your custom member index and run the same search - the field will remain unchanged:
![image](https://user-images.githubusercontent.com/6452616/105915275-8228ab00-5ffd-11eb-92d8-fbef59e8f681.png)

5) Rebuild the custom index and the member values will be updated:
![image](https://user-images.githubusercontent.com/6452616/105916909-aeddc200-5fff-11eb-9ff2-e21bf36a9f5e.png)

I would expect the member index fields to update on save...

**Comment by Shazwazza** [comment] 2021-01-27 03:12
Not sure it's identical, you mention you are using a custom index. Does  it work with the default member index? If so then it'll will be some configuration of your custom index. Also why are you using a custom member index when the default one is able to be configured to suite your needs. The more indexes, the more overhead.

**Comment by jattwood** [comment] 2021-01-27 13:18
Thanks @Shazwazza, yes it is a custom index. I am mid stream in migrating a u7 to u8 instance and thought the approach would be more or less the same for u8. Not sure if you would still call this a bug, then - although technically it does occur. I do think the docs should be a little more clear about approaches to solving these common issues knowing that the approaches for 7 -> 8 could be different. Appreciate your time!

**Comment by jattwood** [comment] 2021-01-27 14:55
Thanks to @deekoulos on #9095  I have been able to inherit and extend the default members index. The docs here suggest that you can do it of course: https://our.umbraco.com/documentation/reference/searching/examine/indexing/ but its unclear (I think) that you should, as a rule, never create your own index and that in U8 you can extend the indexes with your own custom fields. The very first paragraph on this page and the sections on "Changing IValueSetValidator"  and "Overriding index creation" needs a rewrite to explain best practices and approaches the examples are muddled together. Put me in touch with the docs team and I would be happy to make some suggestions. Cheers!

**Comment by Shazwazza** [comment] 2021-01-28 00:27
@jattwood having additional indexes in v7 is also not recommended (the overhead in v7 is much worse than v8 for additional indexes). You can customize all indexes as much as you want in both v7 and v8 (so long as some important fields are not removed).

In any case though, it is absolutely possible to create custom indexes based on Umbraco data like another member index. The issue you were having was most likely an implementation issue ... which I agree is caused by lack of documentation.

The docs repo is here https://github.com/umbraco/UmbracoDocs, please feel free to update/create issues/tasks there and PRs. That would be hugely appreciated. The base Examine (not Umbraco related) docs are here https://shazwazza.github.io/Examine/ which still need to be filled out more, the repo for them are here https://github.com/Shazwazza/Examine/tree/master/docs. Any help is very much appreciated!

**Comment by Shazwazza** [comment] 2021-01-28 00:27
Can we close this issue?

**Comment by jattwood** [comment] 2021-01-28 00:58
Yep sure let’s close it. I’ll see what I can contribute for sure.
________________________________

**Closed** 2021-01-28 02:13 UTC
