### ISSUE TITLE
Tree state not kept when navigating between sections

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#17554] opened 2024-11-17 00:38 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

Not sure if this is a bug or if this is intentional but I wanted to post this since I think that it is important.

When I'm working on a node in the content-section, navigating to the media section and then want to go back the tree is collapsed and the dashboards are shown, like this:

![umb-tree-state](https://github.com/user-attachments/assets/c9466ce4-4b16-43e4-be99-3a4ca1b77862)

Not a big deal in the example but most of the real world websites that we work with will have at least 4-5 levels (sometimes more) so I would argue that this is a very nice feature for editors (and probably expected if they are used to Umbraco 13).

I can see that this is not a easy fix. If we keep the tree state when clicking on "Content" - how would someone be able to get back to the dashboards again? Maybe only load dashboards the 2nd time if clicking on the active section? Not sure.

### Steps to reproduce

I think that the way Umbraco 13 works in these scenarios is the "right way", that means remembering the last document that was edited and loading this document + the tree.

**Comment by NguyenThuyLan** [comment] 2024-11-20 07:24
I confirm that this is a bug that needs to be fixed. @enkelmedia

**Comment by PerplexDaniel** [comment] 2024-11-20 14:45
This reminds me of my [first ever PR to Umbraco v7](https://github.com/umbraco/Umbraco-CMS/pull/2287) which added this behavior 😁 Still present [in v13 today](https://github.com/umbraco/Umbraco-CMS/blob/release-13.5.2/src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbsections.directive.js#L112) it seems.

Not sure if the new backoffice has something similar to the `historyService` we had in AngularJS but that's what we used then to select the previously selected node of a section again. If not something similar may have to created in v15.

**Comment by enkelmedia** [comment] 2024-11-20 15:52
@PerplexDaniel That's quite a first PR! :) Really valuable.

I can see that it might be more complicated if tree is loaded in a paginated fashion in the future (might already be? I have not tested it) but I do think that this is a really valuable feature.

I know that there is another issue somewhere about the fact that the tree does not expand to the current node when the page is reloaded - I guess that they are kind of related.

**Comment by enkelmedia** [comment] 2024-11-20 16:34
Turns out that there was a actually another issue reported about the same problem https://github.com/umbraco/Umbraco-CMS/issues/17076 - adding here for reference.

**Comment by madsrasmussen** [comment] 2024-11-21 08:07
Hi @enkelmedia 

Thanks for the report. You are correct, this is a feature we need to bring back, and as you also mentioned it is related to being able to expand the tree and set the active tree item. With paginated trees, we first need to figure out how to solve this in the management API. How do we get a paginated result that must include a specific item? 🤔 

I will mark this issue as a duplicate and then we collect our thoughts in the same place.

Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/17076

**Closed by madsrasmussen** 2024-11-21 08:07 UTC
Labels: status/regression, type/bug, state/reproduced, area/frontend, affected/v14, affected/v15
