### ISSUE TITLE
Exception while trying to access property when it has "Vary by culture" set to true after upgrade.

### ISSUE THREAD

**Issue by bartoszc9** [umbraco/Umbraco-CMS#14689] opened 2023-08-17 07:19 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 12.1.0

### Bug summary

For some reason I have ArgumentNullException while trying to access one of properties on object generated by Umbraco. It only happens, when "Vary by culture" is set to true, when I set it to false, then exception is not occurring. Everything was working before I've updated version from 8.18.8.

Do you have any ideas what is wrong?

![image](https://github.com/umbraco/Umbraco-CMS/assets/114907545/a3269345-f610-435a-8914-7fc3e41f5ff6)
![image](https://github.com/umbraco/Umbraco-CMS/assets/114907545/d8da7267-9632-4856-9ce8-f766c429947d)

### Specifics

stack trace:
`   at Umbraco.Cms.Core.Collections.CompositeStringStringKey..ctor(String key1, String key2)
   at Umbraco.Cms.Infrastructure.PublishedCache.Property.GetSourceValue(String culture, String segment)
   at Umbraco.Cms.Infrastructure.PublishedCache.Property.HasValue(String culture, String segment)
   at Umbraco.Extensions.PublishedContentExtensions.Value[T](IPublishedContent content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Web.PublishedModels.PressReleaseCategory.get_Category() in C:\Users\cloudnine\source\repos\Permobil-Global-Backend\src\Permobil.Core\Models\Umbraco\PressReleaseCategory.generated.cs:line 58
   at Permobil.Content.PressReleases.PressReleaseCategoryIdService.GetPressReleaseCategory(PressReleaseCategory pressReleaseCategory) in C:\Users\cloudnine\source\repos\Permobil-Global-Backend\src\Permobil.Content\PressReleases\PressReleaseCategoryIdService.cs:line 27
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Permobil.Content.Components.Search.PressReleaseSearchIndexComponent.SavePressReleaseFields(Object sender, IndexingItemEventArgs e) in C:\Users\cloudnine\source\repos\Permobil-Global-Backend\src\Permobil.Content\Components\Search\PressReleaseSearchIndexComponent.cs:line 77
   at Umbraco.Cms.Infrastructure.Examine.UmbracoExamineIndex.OnTransformingIndexValues(IndexingItemEventArgs e)
   at Examine.Lucene.Providers.LuceneIndex.ProcessIndexQueueItem(IndexOperation op)
   at Examine.Lucene.Providers.LuceneIndex.ProcessQueueItem(IndexOperation item)
   at Examine.Lucene.Providers.LuceneIndex.PerformIndexItemsInternal(IEnumerable`1 valueSets, CancellationToken cancellationToken)`

### Steps to reproduce

-

**Comment by elit0451** [comment] 2023-08-17 07:39
Hi @bartoszc9 👋 

Since you have upgraded from v8 perhaps something went wrong with your custom implementation - it is a long way to v12, so perhaps you missed doing some changes. I would recommend visiting our https://our.umbraco.com/forum/ and initiating a discussion there. Perhaps someone from our friendly community has seen similar behaviour and can help you to figure out what went wrong. 

And if you figure out that there is an actual bug within the CMS, list the Steps to reproduce in a GitHub issue like this one and we will have a look 🙂

**Comment by benmurphycb** [comment] 2023-10-10 11:01
We are also getting this error - I have managed to track it back to an issue with the segment.

Even though segment is an optional parameter (`string? segment = null`) - it will throw an exception if you do not set it to `""` an empty string. 

@elit0451 please can we reopen this?

**Comment by bartoszc9** [comment] 2023-10-10 13:11
@benmurphycb In my case as a workaround for this issue I had to set Variation context with specific culture (`_variationContextAccessor.VariationContext = new(Cultures.RootCulture);`) before accessing property.

**Comment by smarshallsay** [comment] 2023-10-18 08:59
I think this may be the same issue I am getting on one of our websites that has many cultures. If I upgrade past 11.2.2 then I get null reference exceptions when I try to access certain values whether or not they have a value set. 
In my case the first erroring value is a bool (true/false) set on a page inherited from a composition

![image](https://github.com/umbraco/Umbraco-CMS/assets/5755133/3f294fff-d39d-43dd-8c32-2a306093c2e0)

![image](https://github.com/umbraco/Umbraco-CMS/assets/5755133/8707e1ac-5da4-49e7-8a85-e910d99405dc)

although the values _are_ returned in the non-public members _content

**Comment by smarshallsay** [comment] 2023-10-18 09:04
Ok, thanks. I will make a new issue

**Comment by netcamo** [comment] 2023-10-23 11:16
Hi @benmurphycb!

Thank you very much  for informative explanation on the problem!

While I see the problem that is caused I would like to reproduce it before putting appropriate labels on it. I would be very happy if you could give me steps and instructions to reproduce the error.

I am looking forward to your reply and I wish you a wonderful week ahead! 😄

**Comment by benmurphycb** [comment] 2023-10-24 08:25
Hi @netcamo 

No problem, I have added as much details as I can to [this issue](https://github.com/umbraco/Umbraco-CMS/issues/14954) 

Thank you, you too! :)

**Comment by Migaroez** [comment] 2023-11-20 14:25
Hey @bartoszc9 

After inspecting your stacktrace, I think you might be using certain parts of the framework in a way that it might not be meant for.

I can see that one of the early entrypoints is examine `Examine.UmbracoExamineIndex.OnTransformingIndexValues`, this is part of the Content authoring part of the framework which uses IContent to move data around. This type of data is not optimized for rendering, holds history data, all available cultures, and so on. It is what is used in the backoffice as that is the place where you author your content.

You seem to have hooked into examine with `PressReleaseSearchIndexComponent` which calls a custom service `PressReleaseCategoryIdService` which then returns a modelsbuilder model (I think, looking at the name and the image you provided). A modelsbuilder model is a wrapper around IPulblishedContent, which is an optimized version of content for Rendering (not authoring). To be able to construct this model from an IContent, the pipeline needs to have information about the culture to be able to know which variant to supply as an IPublishedContent. Generally we do this for you when you request content trough the UmbracoContext as part of the request pipeline, which in this case you are not doing as this is not part of a request.

So it makes sense that if you set the VariationContext, it all suddenly works again.

But it is generally a bad idea to mix IpublishedContent derived data with IContent derived data. Using the IContentService for whatever you are doing is probably the better way to go.

Since this explain the issue you were having and all other reactions to this issue have been turned into their own issues, i will be closing this one. If something doesn't sound right, feel free to reopen it with a comment.

Have a wonderful day!

**Closed by Migaroez** 2023-11-20 14:25 UTC
Labels: type/bug
