### ISSUE TITLE
V8.7RC - Updating document type from the content info menu does not save the change properly

### ISSUE THREAD

**Issue by nikolajlauridsen** [umbraco/Umbraco-CMS#8722] opened 2020-08-25 08:43 UTC
If you add a new property to a document type from the content section through the info menu, the change will not save properly, the save action succeeds, however you can not use the property in your view with strongly typed models.

![infocontext](https://user-images.githubusercontent.com/16456704/91152321-1c876a00-e6bf-11ea-9147-1bf0938104e8.jpg)

 ```Model.PropertyName``` throws and error, however ```Model.Value("propertyName")``` does not. 
![prop error](https://user-images.githubusercontent.com/16456704/91152524-5a848e00-e6bf-11ea-8f87-6c19b14543a5.jpg)

If you open the document type through the settings section you will see your change, and if you just hit save again the error no longer occurs and you can access the propertyname strongly typed.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7RC

Reproduction
------------

1. Create a document type
2. Enter the content section
3. Create a piece of content using the document type
4. Enter the info section
5. Click the "Open" button next to the template
6. Add a new property
7. Save
8. Try to render the property in the view with ```@Model.PropertyName```

---
_This item has been added to our backlog [AB#7921](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7921)_

**Comment by bergmania** [comment] 2020-08-25 08:48
Are you sure you are running ModelsBuilder in PureLive?

**Comment by nikolajlauridsen** [comment] 2020-08-25 08:54
It should be runing
![modelsBuilder](https://user-images.githubusercontent.com/16456704/91154049-4b9edb00-e6c1-11ea-8ce6-15b65ed62011.PNG)

**Comment by nul800sebastiaan** [comment] 2020-08-25 13:21
I can't reproduce this, I might have made it a little too fast but when you see the frontend for the first time you will notice that it didn't crash with the error you have. The second time it displays the property that has been populated.

![8722_2](https://user-images.githubusercontent.com/304656/91179089-57e95f00-e6e6-11ea-9e09-82e7856b5ec6.gif)

I'll close this for now but we might need to revisit later.

**Closed by nul800sebastiaan** 2020-08-25 13:21 UTC
Labels: state/sprint-candidate
