### ISSUE TITLE
List View Template issue with {{ value | ncNodeName }}

### ISSUE THREAD

**Issue by jacklawry** [umbraco/Umbraco-CMS#9437] opened 2020-11-23 13:52 UTC
A brief description of the issue goes here.

If you add a property to show a node name (in my instance for a member where I am using it to choose a company name from a list of nodes

![Screenshot 2020-11-23 at 11 55 30](https://user-images.githubusercontent.com/3786136/99969216-12463c00-2d92-11eb-8f6d-496ca9532a74.png)

Then then works but if you refresh the page then the node name shows "Loading..." if you visit another page and come back then it shows the node name again. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.7.0 but also reported the same issue in 8.9.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Please see above. 

### Specifics

/umbraco/#/member/member/list/all-members
Umbraco version 8.7.0
Browsers: Chrome, Edge, FireFox & Safari
![Screenshot 2020-11-23 at 13 49 10](https://user-images.githubusercontent.com/3786136/99969638-add7ac80-2d92-11eb-8cb9-3d6bc8afa0d0.png)

**Comment by glombek** [comment] 2020-11-23 14:09
I can replicate that issue Jack in a content list view (not just members) in Umbraco version 8.9.1.

I can also add that using the `ncNodeName` filter inside nested content in an infinite editor never loads.

**Comment by bjarnef** [comment] 2020-12-06 16:19
It seems this is a duplicate of the issue reported here: https://github.com/umbraco/Umbraco-CMS/issues/9145

**Comment by nul800sebastiaan** [comment] 2021-03-03 13:09
Closing as duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9145

**Closed by nul800sebastiaan** 2021-03-03 13:09 UTC
