### ISSUE TITLE
Mandatory fields in nested content not marked as required in 8.7.0

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#8963] opened 2020-09-25 13:32 UTC
After upgrading from 8.6.4 to 8.7.0 the red asterisk is now missing for mandatory fields in nested content.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7.0

Reproduction
------------

1. Installed a clean Umbraco 8.6.4
2. Created an element doc type with one mandatory textstring field
3. Created a nested content data type and allowed the element type I just created
4. Created a page doc type with the following fields
   1. A textstring field marked as mandatory 
   2. A field for the nested content data type created in step 3
5. Created a page and got the following (as expected)
![image](https://user-images.githubusercontent.com/2575817/94272338-37116500-ff43-11ea-8527-bc2245a320fa.png)

6. Upgrade Umbraco from 8.6.4 to 8.7.0 from NuGet
7. Now the red asterisk in on the nested content field is missing, but still there for the page field
![image](https://user-images.githubusercontent.com/2575817/94272515-72139880-ff43-11ea-8f4b-873e81248b80.png)

 

Also it doesn't tell which field in the nested element that's failing the validation
![image](https://user-images.githubusercontent.com/2575817/94428314-cd869600-0190-11eb-8c93-6f3d8501d06d.png)

---
_This item has been added to our backlog [AB#8782](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8782)_

**Comment by limpa123** [comment] 2020-09-25 14:03
Getting this one as well. Setting up new doctypes and datatype in the updated version gives the same result. 
Adding a value to the required field once the validation message has been shown does not get rid of the message. The only way to save is to remove the nested content item and then add it again filling out the value from start.

**Comment by jesperweber** [comment] 2020-09-28 11:48
@limpa123 Yes that's also what I experience.

**Comment by filefontaine** [comment] 2020-10-05 08:42
I found that in my 8.5.5 prod website, the red * is not set either so i think is a regression of 8.6. 

But the error appear correctly :
![image](https://user-images.githubusercontent.com/22192319/95058114-5a80a080-06f7-11eb-94b7-b8c6edc82ae2.png)

(**Current Navigation Title** is mandatory)

**Comment by nul800sebastiaan** [comment] 2020-10-05 15:57
First of your nested validation in 8.7+ should look a bit better, like this: 

![image](https://user-images.githubusercontent.com/304656/95102777-1790ee00-0734-11eb-9ef3-6f88e645f1b8.png)

However I am not sure what happened to the mandatory indicator, might have been a conscious choice not to have it any more or it might have accidentally been removed. 

I'll call in some feedback from @nielslyngsoe on this one!

**Comment by jesperweber** [comment] 2020-10-06 11:33
@nul800sebastiaan Strange, I also see the new validation i the clean solution now, don't why I didn't the first time? How ever if I select the interface in danish, some of the validation is in danish and some in english. This is properbly just a missing translation.
![image](https://user-images.githubusercontent.com/2575817/95196296-23ce8700-07d8-11eb-9b0a-e13f5ff758f4.png)

But yes I'm still missing the mandatory indicator and this is a problem for our editors. Hopefully this is just an error and not a conscious choice.

**Comment by filefontaine** [comment] 2020-10-06 11:45
> Strange, I also see the new validation i the clean solution now, don't why I didn't the first time? 

@jesperweber I have the same problem, you found a solution, to make them appear on an existing solution?

**Comment by jesperweber** [comment] 2020-10-06 11:50
> I have the same problem, you found a solution, to make them appear on an existing solution?

@filefontaine Nope I did nothing, I just started the solution again today and it worked. So don't know how both of us could experience the same thing and now it just works for me?

**Comment by nul800sebastiaan** [comment] 2020-10-07 13:52
Thanks for the feedback all! I've spoken to @nielslyngsoe and it's definitely a regression we will need to fix. Maybe if any of you are quick you can find the problem and send a PR? It will definitely count for Hacktoberfest! 😉

But in any case we should look at it at HQ and fix it soon.

**Comment by filefontaine** [comment] 2020-10-08 10:21
I have made some research and i found in the umbraco.directives.directive:umbProperty an not correct parameter for the * 
For now 8.8.0 (same in 8.7.0)
`
<span ng-if="vm.property.validation.mandatory"> <strong class="umb-control-required">*</strong> </span>
`
And i found in the definition of the umbProperty  a set up like 
'umb-nested-content--mandatory': property.ncMandatory
so normaly
`
<span ng-if="vm.property.ncMandatory"> <strong class="umb-control-required">*</strong> </span>
`

i dont have the time now do to the pr

But for now if you need a quick fix

**Comment by filefontaine** [comment] 2020-10-08 10:26
ok i found that the umbraco.directives.directive:umbProperty  is used for all property in the web site so i think a convertion is needed for this like 
`vm.property.validation.mandatory = vm.property.ncMandatory`

**Comment by nul800sebastiaan** [comment] 2020-10-08 10:28
There is a note in the .less file for this which might explain what is actually going on here:

```
.umb-nested-content--mandatory {
    /*
        yeah so this is a pain, but we must be super specific in targeting the mandatory property labels,
        otherwise all properties within a reqired, nested, nested content property will all appear mandatory
    */
    > ng-form > .control-group > .umb-el-wrap > .control-header label:after {
        content: '*';
        color: @red;
    }
}

```

**Comment by filefontaine** [comment] 2020-10-08 10:34
ok so if in the `UmbPropertyController`
you set something like this the message and the * work as expected (for now not the custom message if you set one)

`
if(vm.property.ncMandatory){
                    vm.property.validation.mandatory = vm.property.ncMandatory;
                }
`

**Comment by filefontaine** [comment] 2020-10-08 10:46
> 
> 
> There is a note in the .less file for this which might explain what is actually going on here:
> 
> ```
> .umb-nested-content--mandatory {
>     /*
>         yeah so this is a pain, but we must be super specific in targeting the mandatory property labels,
>         otherwise all properties within a reqired, nested, nested content property will all appear mandatory
>     */
>     > ng-form > .control-group > .umb-el-wrap > .control-header label:after {
>         content: '*';
>         color: @red;
>     }
> }
> ```
linked to this nov 2019 commit : 
https://github.com/umbraco/Umbraco-CMS/commit/880d65bb42128b7eb3ef15870cf544766f30bd09#diff-76962e8b784d85838edd5fa0affff403

i dont know if it is always relevent as the nested content have now a proper property editors view

**Comment by nul800sebastiaan** [comment] 2020-10-22 07:48
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9250

Cherry picked for 8.7.1+ in f3aad864133546793b3887eb7e917d41440e2b5e

**Closed by nul800sebastiaan** 2020-10-22 07:48 UTC
Labels: release/8.7.1, release/8.8.1, state/in-sprint, status/regression, type/bug

**Comment by DanDiplo** [comment] 2021-01-22 12:02
I'm getting the opposite problem in 8.10.1! I have a property _not_ marked as mandatory yet it _is_ showing an asterisk (*) to indicate it is mandatory when used in Nested Content:

Here is the element type. You can see the last property **Video URL** is _not_ marked as mandatory.

![image](https://user-images.githubusercontent.com/6676168/105487805-9771a280-5ca8-11eb-869c-d30db97a8033.png)

Here's the property properties:

![image](https://user-images.githubusercontent.com/6676168/105488073-04853800-5ca9-11eb-864a-283fd652eff6.png)

But when I create an instance of it in Nested Content then it gets marked with a red asterisk (*) which makes Editors think it is required (even thought it can be submitted without completion):

![image](https://user-images.githubusercontent.com/6676168/105487918-c6881400-5ca8-11eb-9674-bd1116836d6a.png)

Has anyone experienced this? I'm not sure if this is a regression due to a fix or maybe because the Video URL datatype is a custom property editor and is missing something? (Though it used to be fine in earlier versions and this issue only appears within Nested Content).

I can open this as a new issue, but just thought I'd check if anyone else has seen this?

**Comment by stewartzollinger** [comment] 2021-02-22 15:28
> 
> 
> I'm getting the opposite problem in 8.10.1! I have a property _not_ marked as mandatory yet it _is_ showing an asterisk (*) to indicate it is mandatory when used in Nested Content:
> 
> Here is the element type. You can see the last property **Video URL** is _not_ marked as mandatory.
> 
> ![image](https://user-images.githubusercontent.com/6676168/105487805-9771a280-5ca8-11eb-869c-d30db97a8033.png)
> 
> Here's the property properties:
> 
> ![image](https://user-images.githubusercontent.com/6676168/105488073-04853800-5ca9-11eb-864a-283fd652eff6.png)
> 
> But when I create an instance of it in Nested Content then it gets marked with a red asterisk (*) which makes Editors think it is required (even thought it can be submitted without completion):
> 
> ![image](https://user-images.githubusercontent.com/6676168/105487918-c6881400-5ca8-11eb-9674-bd1116836d6a.png)
> 
> Has anyone experienced this? I'm not sure if this is a regression due to a fix or maybe because the Video URL datatype is a custom property editor and is missing something? (Though it used to be fine in earlier versions and this issue only appears within Nested Content).
> 
> I can open this as a new issue, but just thought I'd check if anyone else has seen this?

This is the same issue that I'm having - all fields within a nested content item showing as mandatory, when only some actually are.

**Comment by jesperweber** [comment] 2021-05-07 07:52
@DanDiplo and @stewartzollinger do you know if there is a fix for this? If not then I will open a new issue.

**Comment by DanDiplo** [comment] 2021-05-07 07:55
@jesperweber I'm not aware of a fix, no, so please report.
