### ISSUE TITLE
v8: ContentService.GetById gets cached version when using Key (Guid)

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#4407] opened 2019-02-04 17:21 UTC
_Latest Nightly : 8.0.0-alpha.58.2084_

Calling the ContentService to get a content item by Key (Guid) returns a cached version of the item, not the latest version.

If you call the contentService.GetById with the int id you get the latest version

### Reproduction

I had the following code in an ApIController (Id / Guid is same bit of content for test)
```
var item = Services.ContentService.GetById(1061);
Logger.Info<uSyncDashboardApiController>($"By Id Content Version: {item.VersionId}");

var itemByKey = Services.ContentService.GetById(Guid.Parse("fdfa7dd1-b45d-4a14-bc66-83f441df2d69"));
Logger.Info<uSyncDashboardApiController>($"By Key Content Version: {itemByKey.VersionId}");
```

1. Before content modification log : 
```
By Id Content Version: 2
By Key Content Version: 2 
```
2 . Go to content update a field and publish the node 
3. Call after publish (new version of content)
```
By Id Content Version: 3
By Key Content Version: 2 
```
_You might not really notice this until you try and save the via the content service and you get `Cannot save a non-current version` because your version is old._

**Comment by kjac** [comment] 2019-02-04 19:14
Duplicate of #2997

**Comment by Emetico** [comment] 2019-08-05 11:07
Possible work around for v8, until it is fixed.

```
public IContent GetLatestVersion(int documentId)
{
    IContent document = contentService.GetById(documentId);
    int lastestVersionId = contentService.GetVersionIds(document.Id, 1).First();
    return lastestVersionId == document.VersionId ? document : contentService.GetVersion(lastestVersionId);
}
```

**Comment by nul800sebastiaan** [comment] 2020-07-02 14:53
I'll close this as a duplicate of #2997

**Closed by nul800sebastiaan** 2020-07-02 14:53 UTC
Labels: state/hq-discussion, type/bug
