### ISSUE TITLE
Umbraco 9 Examine Query with QueryOptions not working

### ISSUE THREAD

**Issue by DavidArmitage** [umbraco/Umbraco-CMS#10463] opened 2021-06-14 10:36 UTC
### Which Umbraco version are you using?

Umbraco version 9.0.0-beta003

### Bug summary

When searching examine using QueryOptions  there is a bug.

When you run search on page 1 it seems to work as expected.
When you run the same search on page 2 it brings back on results
When you run the same search on page 3 or above it brings back on results

### Specifics

Relating to the code I have written below.

int pageIndex = blogSearch.CurrentPage - 1;
int pageSize = blogSearch.ItemsPerPage;

QueryOptions queryOptions = new QueryOptions(pageIndex * pageSize, blogSearch.ItemsPerPage);
ISearchResults searchResult = examineQuery.Execute(queryOptions);
IEnumerable<ISearchResult> pagedResults = searchResult;

int totalResults = Convert.ToInt32(searchResult.TotalItemCount);
blogSearch.TotalItems = totalResults;
blogSearch.TotalPages = (totalResults + blogSearch.ItemsPerPage - 1) / blogSearch.ItemsPerPage;
blogSearch.BlogDetailsPages = GetBlogArticlesFromSearch(pagedResults);

As I mentioned in the summary no data is returned when searching page 2 or above.
All other data like the TotalResults and TotalPages all seems correct

### Steps to reproduce

Run any basic Examine search using QueryOptions.

Page 1 works but if you test searching page two no results will be retuned (in error)

QueryOptions queryOptions = new QueryOptions(pageIndex * pageSize, blogSearch.ItemsPerPage);
ISearchResults searchResult = examineQuery.Execute(queryOptions);

### Expected result / actual result

Results should be returned for all pages in the search,

**Comment by Shazwazza** [comment] 2021-06-14 18:36
Is this just a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/10463 ?

**Comment by nul800sebastiaan** [comment] 2021-06-14 19:44
Duplicates https://github.com/Shazwazza/Examine/issues/234

**Closed by nul800sebastiaan** 2021-06-14 19:44 UTC
Labels: type/bug
