### ISSUE TITLE
Image Media Picker 3 Is Not Working

### ISSUE THREAD

**Issue by DavidArmitage** [umbraco/Umbraco-CMS#10456] opened 2021-06-13 12:16 UTC
### Which Umbraco version are you using?

Umbraco version 9.0.0-beta003

### Bug summary

The Image Media Picker 3 simply doesn't appear to be working.

I have tested adding this datatype to the page, setting it as 0 items required and set the field as not mandatory.
It still doesn't get past validation errors.

It also will not let you choose and save an image.

I have had a play with the settings trying to make this required and need at least one item.
I still could not get this to save.

Here is a screen cast demonstration the issue.
https://www.awesomescreenshot.com/video/4110420?key=f532ef4c746779792df3f672c2d378ef

### Specifics

The Image Media Picker 3 simply doesn't appear to be working.

I have tested adding this datatype to the page, setting it as 0 items required and set the field as not mandatory.
It still doesn't get past validation errors.

It also will not let you choose and save an image.

I have had a play with the settings trying to make this required and need at least one item.
I still could not get this to save.

Here is a screen cast demonstration the issue.
https://www.awesomescreenshot.com/video/4110420?key=f532ef4c746779792df3f672c2d378ef

### Steps to reproduce

Add any Image Media Picker 3 and you will see this does not work.

### Expected result / actual result

The images should save.
Also the image picker should allow for blank selections without throwing validation errors.

**Comment by Matthew-Wise** [comment] 2021-06-15 08:37
I think this has been fixed with - https://github.com/umbraco/Umbraco-CMS/pull/10370

**Comment by bergmania** [comment] 2021-06-15 08:43
Your are right @Matthew-Wise , this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/10289

**Closed by bergmania** 2021-06-15 08:43 UTC
Labels: type/bug
