### ISSUE TITLE
When publishing content with no Name, I want to see serverside validation, not an error

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4884] opened 2019-03-06 09:59 UTC
I would like to have server-side validation feedback, if name is missing when publishing a content-node.

Similar to how server-side validation works for properties, seen in this screenshot (please investigate how the data is send, since i didn't want to paste a response in  here)

![image](https://user-images.githubusercontent.com/6791648/53872516-bad0cd00-3ffe-11e9-9fb7-fbaeff1401f3.png)

The error I get today is like this, and want fixed by having serverside validation feedback:

![image](https://user-images.githubusercontent.com/6791648/53871217-1baad600-3ffc-11e9-907a-6687f35500d3.png)

An error occured
Cannot save content with an empty name.

```
Exception Details
System.InvalidOperationException: Cannot save content with an empty name.
Stacktrace
at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.EnsureInvariantNameExists(IContent content) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 1363
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.SanitizeNames(Content content, Boolean publishing) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 1340
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistNewItem(IContent entity) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 277
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Create(TEntity entity, Action`1 persistNew) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Core\Cache\DefaultRepositoryCachePolicy.cs:line 96
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.Save(TEntity entity) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Core\Persistence\Repositories\Implement\RepositoryBaseOfTIdTEntity.cs:line 165
   at Umbraco.Core.Services.Implement.ContentService.Save(IContent content, Int32 userId, Boolean raiseEvents) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Core\Services\Implement\ContentService.cs:line 785
   at Umbraco.Web.Editors.ContentController.PublishInternal(ContentItemSave contentItem, Boolean& wasCancelled, String[]& successfulCultures) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Web\Editors\ContentController.cs:line 1226
   at Umbraco.Web.Editors.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Web\Editors\ContentController.cs:line 749
   at Umbraco.Web.Editors.ContentController.PostSave(ContentItemSave contentItem) in C:\Projects\Umbraco\Umbraco-CMS-v8\src\Umbraco.Web\Editors\ContentController.cs:line 594
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
 ```

**Comment by Shazwazza** [comment] 2019-03-12 05:15
Have started a PR to fix a few things regarding this: https://github.com/umbraco/Umbraco-CMS/pull/4955 (not done yet though)

This PR has a JS hack to allow you to select a variant for publishing without it's name filled in, this is not how it normally works though but allows testing this scenario for now.

As an example if you were to clear out the French name, go to the English variant and publish both English and French, this would be the result (this is based on server side validation)

![image](https://user-images.githubusercontent.com/1742685/54176164-d9910100-44e1-11e9-90ee-2a082b9c4508.png)

There's still a bit more to cleanup though and need to get a few more details from @nielslyngsoe

**Comment by nielslyngsoe** [comment] 2019-03-12 09:23
@Shazwazza Cool, I´m looking forward to this fix. Lets talk tomorrow.

**Comment by Shazwazza** [comment] 2019-03-14 03:22
https://github.com/umbraco/Umbraco-CMS/pull/4955 PR is ready for review, there's tons of notes in there and turns out there was quite a few issues

**Comment by RobertCopilau** [comment] 2019-03-14 14:55
Only had the chance to test for a little while but here is what I have found so far.
* Unpublish dialog has some issues with the checkboxes - https://www.useloom.com/share/aa1f7be8fd75402da0eff185b161b0c9
* The Save and  Publish dialog has the old checkboxes, regression somewhere?
* After Publishing all three languages of which two were mandatory and one had invalid name, this is how the dialog looks like -
![Annotation 2019-03-14 153714.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7850e37a25d6b479eb0037431f1d11f6140b1b56f6eb8c79f3b4687789595fbbd56e5a74c63c10a9bdd716eb57bf32975dc7e7e2de139db17770a599855d3f190f198cfa5f30a79c4ac15bf042e05f18.jpg)
* Sometimes after publishing, I can't get the unpublish button to appear in the combo, have not found a consistent way to reproduce, will update once I do.

I will do more testing tomorrow, so far no functionality issues aside from not being able to select which language I want to unpublish.

**Comment by Shazwazza** [comment] 2019-03-15 04:21
Thanks @RobertCopilau , one thing to check is that i think this error mentioned above:

> After Publishing all three languages of which two were mandatory and one had invalid name, this is how the dialog looks like -

I think is a problem even before this PR, so if you could check that would be good since if it's not caused by this PR we can treat it as a separate problem and solve it separately.

**Comment by Shazwazza** [comment] 2019-03-15 04:22
I didn't get much time on this today but will be working on more updates to it so please make sure nothing is merged yet. I need to fix up some styling that i removed and will check what happened to the checkboxes

**Comment by Shazwazza** [comment] 2019-03-15 05:05
Have added back in the umb-list-item--error and have applied it to all publish dialogs for consistency. Have also put back in the umb-checkbox in the publish dialog, there was a merge problem from the previous PR of the PR.

Here's some examples of what should happen when creating and save/publish a variant document, this is using 2 mandatory languages, a variant doc type with 2 properties: one invariant text field (required and validated by Number, one variant text field (required and validated by Number).

Of course there's a ton more combinations of just saving or send to publish or publish with descendants, etc... 

* [ ] Everything valid - will redirect and no dialog is shown, will show normal success notifications

* [ ] Everything valid on one language, nothing entered on the other, you will get this

![image](https://user-images.githubusercontent.com/1742685/54409389-a4332000-473a-11e9-8925-2717da65738c.png)

This is because the Spanish language is required, because it's required, nothing can be published, so we indicate the errors. Note that beside the English language it says 'This' language was saved but not published. In this situation, we can save the English language but cannot publish it because the Spanish language could not be published because it failed validation rules and the Spanish language cannot be created because it's missing it's Name.

* [ ] Everything valid on one language, the name entered on the other and an invalid entry entered in to the text field like 'abc' (not a number), you will get this:

![image](https://user-images.githubusercontent.com/1742685/54409498-215e9500-473b-11e9-96d5-7960220108a2.png)

Very similar to the above, however, both languages were saved this time but neither were published because the Spanish language had invalid properties.

* [ ] Names entered on both languages but invalid property data entered on both languages, you'll get this:

![image](https://user-images.githubusercontent.com/1742685/54409529-5bc83200-473b-11e9-8794-b79f99afe8f7.png)

Similar to the above again, but this time showing that there was validation problems on each corresponding language

* [ ] Names entered on both but invalid property data entered for the invariant property on the default language (the other property should be valid) and invalid property data on the invariant property on the second language

You will get exactly the same as the above because validation problems with invariant properties are related to the default language

**Comment by RobertCopilau** [comment] 2019-03-15 08:25
I am unable to test the Publish Dialog as the old validations would not allow me to have the same result as with the new validations, i.e trying to publish two valid languages and one invalid would throw validation errors for all languages.

I can, however, confirm that the unpublish dialog issue is a separate one.
https://www.useloom.com/share/aa1f7be8fd75402da0eff185b161b0c9

More testing in progress.

**Comment by Shazwazza** [comment] 2019-03-26 10:34
@RobertCopilau the scenarios you mention above is expected. We don't want to validate invariant against all languages.

In your scenarios above, you have already published both languages, so there is already a published version of the default language with the invariant property data. So now if you make that invariant property data invalid and also modify another language, then yes exactly like you say, you will get validation errors for the mandatory language but not the other language and the other language will continue to be published. That is expected because the mandatory language already has a published version. On the other hand, if you were to unpublish the default mandatory language, then all languages will be unpublished. We don't want to validate invariant properties on all languages, this was a design implementation that we worked towards during v8 development. Please let me know if you have questions about this.

As for this data loss thing, i'm investigating that now since that seems quite odd.

**Comment by Shazwazza** [comment] 2019-03-27 06:58
Known issues still:

* https://github.com/umbraco/Umbraco-CMS/issues/4988 is causing issues with variant notifications when creating content because the dialog is still referencing old stale content
* When creating new variants content, any server notifications per variant are lost during the redirect (see comment https://github.com/umbraco/Umbraco-CMS/issues/4988#issuecomment-477005074)
* Server side validation is not cleared on invariant properties on non-default languages even when the invariant property is changed on the default language which means that the user won't be able to submit the non-default language again

Much of the other issues are gone though, i'll keep working on this tomorrow.

**Comment by zpqrtbnk** [comment] 2019-04-02 16:32
Code review done, I have pushed minor renamings and stuff, and I *think* I can make sense of it now.

Now about testing...

I reproduced Robert's situation with 2 langs and it is ok with the PR - though some things are odd - when saving'n publishing the non-default lang, getting an error for the non-selected default lang is odd - I mean, I did *not* check this lang, it feels weird to get an error, considering I cannot act on that error.

And, although it's been saved, the UI still asks me whether I want to discard changes, so it looks like the UI does not get that it's been saved?

Then, as I mention somewhere else... it's not possible to edit that invariant property without re-publishing the default language (and then unpublishing it again). But that's probably outside the scope of the PR.

Other than that... works by my tests. It *feels* like there are some cases that are not under control, but ... would be happy to merge. Can you just look at that question above?

**Closed** 2019-04-04 11:15 UTC
Labels: release/8.1.0, state/review
