### ISSUE TITLE
TrueFalse data type's initial value not respected by YesNoPropertyValueConverter 

### ISSUE THREAD

**Issue by jamiepollock** [umbraco/Umbraco-CMS#14303] opened 2023-05-25 22:13 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

The built in Umbraco TrueFalse data type's initial value prevalue is not respected by the YesnoPropertyValueConverter.

### Specifics

I discovered this issue when creating a block list which had a boolean property for visibility in the settings which had an initial state of true. 

I noticed if a user did not actively view the settings for the block item that the value would be false instead of the expected true value from the data type prevalues.

### Steps to reproduce

1. Create a TrueFalse data type with initial value set to true
2. Create a content element content type with any properties
3. Create a settings element content type with the data type created in step 1
4. Create a block list data type with a configuration that uses the element content types from steps 2 & 3
5. Create a content type that uses the block list data type from step 4
6. Create content using the content type from step 5
7. Create a block in the content but do not set the settings for this block
8. Write code which access these block list property and output the value of the TrueFalse setting

### Expected

A property which has no CMS provided value should return the data type's configured initial prevalue.

### Actual

A property which has no CMS provided value returns false.

**Comment by jamiepollock** [comment] 2023-05-25 22:15
Fortunately I think the fix is fairly simple. It would be a case of updating this line:

https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Core/PropertyEditors/ValueConverters/YesNoValueConverter.cs#L55

To something like:

```
var config = propertyType.DataType.ConfigurationAs<TrueFalseConfiguration>();

return config is null ? false : config.Default;
```

**Comment by jamiepollock** [comment] 2023-05-26 01:35
I've now added a PR to fix this here: https://github.com/umbraco/Umbraco-CMS/pull/14305.

It looked like my initial code snippet didn't quite cover all the angles. Fortunately the tests project showed me the edge cases I missed.

**Comment by jamiepollock** [comment] 2023-05-26 01:36
While I initially reported this as a v10 bug it likely affects v11 and v12 too as the implementation of YesNoValueConverter has not changed.

**Comment by abjerner** [comment] 2023-05-26 07:30
I think this is similar to the issue originally reported by @sebastiandammark: https://github.com/umbraco/Umbraco-CMS/issues/10160

Back then, a problem in fixing this was that for Umbraco 8, the `TrueFalseConfiguration` is located in the `Umbraco.Web` project, while the `YesNoValueConverter` class is located in the `Umbraco.Core` project. So `YesNoValueConverter` doesn't know about `TrueFalseConfiguration`. Umbraco 9+ seems to have fixed that so they are in the same namespace, so now a fix is possible with involving lots of refactoring.

But as mentioned by @nul800sebastiaan in the original issue, a change like this is seen as a breaking change. So we should we careful about making a change like this.

Since this would be a breaking change, I created the [**Limbo Boolean**](https://github.com/limbo-works/Limbo.Umbraco.Boolean) package so we could have the expected behavior even if it wasn't addressed directly in Umbraco.

**Comment by kjac** [comment] 2023-05-26 08:20
Hi @jamiepollock,

Thank you for all your work here 👍 

As @abjerner correctly points out, this is a functionally breaking change. The fix would be nice to get in, though, so I'll see if we can include it in V12.

**Comment by nul800sebastiaan** [comment] 2023-05-26 08:50
Closing for now with an explanation added to the PR: https://github.com/umbraco/Umbraco-CMS/pull/14305#issuecomment-1564034910

**Closed by nul800sebastiaan** 2023-05-26 08:50 UTC
Labels: community/pr, state/needs-investigation, type/bug, area/backend

**Comment by jamiepollock** [comment] 2023-05-26 11:16
Hey folks. Ah that’s regrettable. I respect the reasoning. 

Fortunately the PVC system is pluggable so I’ve already replaced the behavior on my project with local code until a core feature is added later on.

Thank you for the quick turn around in feedback.

**Comment by nul800sebastiaan** [comment] 2023-05-30 09:00
@Nicholas-Westby Our [deprecation policy](https://umbraco.com/products/knowledge-center/versioning-and-release-cadence/) is to obsolete things / [announce](https://github.com/umbraco/announcements/) a breaking at least 2 major versions ahead of time v12-RC is out, which means anything we want to break now will need to wait until v14.

I didn't emphasize enough on the PR that there are quite a lot of quirks in the various PVCs right now and we'd like to see if we can come up with something coherent for all of them so that workarounds that people have been making for years are no longer necessary. And as noted, there's packages with much more consistent behavior that you can use until then.

**Comment by jamiepollock** [comment] 2023-05-30 14:53
@nul800sebastiaan thanks for this clarification. I agree the PVCs are a useful system to handle quirks and edge cases by the developer themselves or through a package.

Hopefully in the future the core PVC system will do a better job at handling these so developer intervention isn't required.

**Comment by Nicholas-Westby** [comment] 2023-05-30 15:59
@nul800sebastiaan I wouldn't say fixing this issue fits within the deprecation policy as this isn't something that is being deprecated, and the upgrade section that mentions breaking changes (if this could even be considered one) doesn't outline anything like the 2 major version announcement you mentioned (i.e., that policy is purely for deprecations). On top of that, it's a very gray area regarding whether or not a release candidate should be considered the cutoff point for a release.

In any event, it's good to hear something is being planned to revamp the core PVCs, even if it will be a several years before it will be incorporated into a LTS release (v16 around mid to late 2025, I imagine).
