### ISSUE TITLE
Using filter search when selecting child document types doesn't show filtered search.

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco-CMS#9678] opened 2021-01-18 14:29 UTC
Filtering  doesn't seem to filter/display the search you type in when selecting the type of children a document type can have:

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.1

Reproduction
------------

### Specifics
Umbraco version: 8.10.1
Chrome: 87.0.4280.141
Haven't tested in other browsers.

### Steps to reproduce

-Run the Umbraco CMS solution you have.
-Create a few document types.
-Make one of them a root and try to add children to it. When adding child document types try and search for the document type you want to add (see image below)
![image](https://user-images.githubusercontent.com/2794633/104926456-79522c80-59a0-11eb-9ec4-695269f0104b.png)

### Expected result
When using the filter search, it should display the relevant document types that are searched for

### Actual result
Nothing happens when entering filter search criteria. Tried pressing "enter" to see if that triggers it. It doesn't

**Comment by bjarnef** [comment] 2021-01-19 07:10
This issue seems to be a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9394 and fixed in https://github.com/umbraco/Umbraco-CMS/pull/9641

**Comment by nul800sebastiaan** [comment] 2021-01-19 08:21
Yep, that's a duplicate of #9394 and will is fixed for the upcoming patch releases and 8.11 next week - https://our.umbraco.com/download/releases/progress

**Closed by nul800sebastiaan** 2021-01-19 08:21 UTC
