### ISSUE TITLE
assetsService.loadCss Ignores Attributes parameter

### ISSUE THREAD

**Issue by dallascharter** [umbraco/Umbraco-CMS#3043] opened 2018-09-26 07:52 UTC
I'm modifying a custom Property Editor and I require the ability to inject a stylesheet to the page with custom attributes.

I'm using the **umbraco.services.js** module's **assetsService**.

Documentation for this service is provided here:

https://our.umbraco.com/apidocs/ui/#/api/umbraco.services.assetsService

I'm using the **loadCss** method, attempting to pass it an attribute as laid out below:

`assetsService.loadCss("style.css", $scope, { crossorigin: 'anonymous' }, 10000 )`

This attribute is not being applied to the page: 

`<link href="style.css" rel="stylesheet" class="lazyload" charset="utf-8">`

I'm checking the **umbraco.services.js** module and the **assetServices.loadCss** method appears to ignore the attributes: 
```
/**
         * @ngdoc method
         * @name umbraco.services.assetsService#loadCss
         * @methodOf umbraco.services.assetsService
         *
         * @description
         * Injects a file as a stylesheet into the document head
         * 
         * @param {String} path path to the css file to load
         * @param {Scope} scope optional scope to pass into the loader
         * @param {Object} keyvalue collection of attributes to pass to the stylesheet element  
         * @param {Number} timeout in milliseconds
         * @returns {Promise} Promise object which resolves when the file has loaded
         */
            loadCss: function (path, scope, attributes, timeout) {
                path = convertVirtualPath(path);
                var asset = this._getAssetPromise(path);
                // $q.defer();
                var t = timeout || 5000;
                var a = attributes || undefined;
                if (asset.state === 'new') {
                    asset.state = 'loading';
                    LazyLoad.css(appendRnd(path), function () {
                        if (!scope) {
                            asset.state = 'loaded';
                            asset.deferred.resolve(true);
                        } else {
                            asset.state = 'loaded';
                            angularHelper.safeApply(scope, function () {
                                asset.deferred.resolve(true);
                            });
                        }
                    });
                } else if (asset.state === 'loaded') {
                    asset.deferred.resolve(true);
                }
                return asset.deferred.promise;
            }
```

Unless _a_ or _attributes_ are being picked up by the LazyLoader somehow...

Is the _attributes_ parameter being ignored by the **loadCss** method?

**Comment by dawoe** [comment] 2018-09-26 08:15
Hi,

I think the attribute parameter is not working since a very long time.

If you take a look at this commit : https://github.com/umbraco/Umbraco-CMS/commit/90bf6003786cb6bd1c7ff94c48102fa3d1998f6a#diff-ca9e001eb1d67c6dccdfdd7aeff07f77

You will see they changed the way assets are loaded (from yepnope to LazyLoad). And since then the attributes parameter is not used anymore

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by dallascharter** [comment] 2018-09-26 08:59
It would be good to have custom attributes work again for loadCss. Is there a known suggested work around for this issue in the meantime? 

I’m thinking that for developers that wish to load a css for a property editor with custom attributes in the meantime will just have to append/insert the line via jquery.

**Comment by nul800sebastiaan** [comment] 2018-09-26 09:01
That seems like an oversight!

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by dallascharter** [comment] 2018-09-26 09:14
Thanks Sebastian, I’ve also noticed that the timeout parameter also appears to be unused.

**Comment by aslafy-z** [comment] 2018-10-09 17:09
I'd love to work on this issue. 

I just PRd a library who does that, may someone take a look ? https://github.com/LukasBombach/Lazyloader/pull/7

**Comment by skartknet** [comment] 2018-10-11 03:06
It looks like neither of both libraries support adding attributes...?

**Comment by aslafy-z** [comment] 2018-10-11 08:09
Sorry, I said I just opened a PR to the said repo to add this feature

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:28
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:28 UTC
Labels: community/up-for-grabs, help wanted, type/bug
