### ISSUE TITLE
Cannot add another color using Color Picker

### ISSUE THREAD

**Issue by suongliang** [umbraco/Umbraco-CMS#9612] opened 2021-01-04 15:47 UTC
I have a custom data type named `Test` , using Picker type `Color Picker`
This should be able to pick colors that I want as a restricted color list.
However when I add the first default color (#000), there's no color panel to select, I cannot input the HEX value for the color neither.
Please see the gif attached below

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.0
Try upgrading to 8.10 but this issue still happens

Reproduction
------------
### Bug summary
    Cannot add other colors using Color Picker for Data Type

### Specifics
    * Bug found on 8.9.0 & even on 8.10.0 after upgrading
    * Browser: Chrome, Firefox
    * 
![YyEWilOVbw](https://user-images.githubusercontent.com/26440443/103552452-82da8f80-4ede-11eb-9c98-b5d701cf5aea.gif)

### Steps to reproduce
1. Create a custom data type that will use the color pickers
2. Choose colors

### Expected result
1. Should expand the color palette for users to choose like previous versions
2. User should be able to input the HEX value in case the palette isn't provided

### Actual result
1. No color palette appears
2. User cannot input the HEX value for the color

**Comment by bjarnef** [comment] 2021-01-04 23:02
I haven't noticed that in v8.9.0 or v8.10.0 in either Chrome or Firefox.

Based on the gif where you highligt the text, it looks like you have an extension installed?

Furthermore I wonder why you have the white background color at the arrow in the color picker button. It shouldn't look like that.

Do you have any extensions installed which might inject styling or manipulate the DOM?

**Comment by nul800sebastiaan** [comment] 2021-01-05 16:22
@suongliang I also can't reproduce this problem, other than a browser extension, perhaps you have a plugin for Umbraco installed that is causing conflicts? 

I'll close this for now, if you have additional steps to reproduce this problem we can have another look.

**Closed by nul800sebastiaan** 2021-01-05 16:22 UTC

**Comment by carolina351** [comment] 2021-05-24 11:17
@suongliang I am having exactly the same problem... Were you able to fix it? If so, how did you do it?

**Comment by suongliang** [comment] 2021-05-26 07:28
@carolina351 I had a check around and it was caused by CSS override in my custom plugins
