### ISSUE TITLE
Right clicking a tree node no longer opens tree action menu

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco-CMS#17135] opened 2024-09-26 08:15 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

When right clicking a tree node (for example in the content section) the browsers right click menu oprens. In v13 and below the right click would open the tree action menu.
![image](https://github.com/user-attachments/assets/2df25bb9-d639-4a94-8c11-f18beffc6ef5)

### Steps to reproduce

1. Create an Umbraco 14.2.0 site. 
2. Create a document type.
3. Create a content node.
4. Right click the content node.

### Expected result / actual result

When right clicking a tree node I would expect the action menu to open up.

**Comment by madsrasmussen** [comment] 2024-10-02 07:22
Duplicate of #16233

**Closed by madsrasmussen** 2024-10-02 07:22 UTC
Labels: type/bug
