### ISSUE TITLE
Custom validation does not prevent a content node from publishing if it is a non varied by culture property

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#7768] opened 2020-03-06 11:24 UTC
If a page that is 'varied by culture', has a 'non-varied-by-culture' property with custom validation, the page will publish even if the validation of said property fails.
![image](https://user-images.githubusercontent.com/17008780/76080423-c7378f00-5f9e-11ea-8527-b2a9b880fe40.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.4

### Bug summary

The content node "Save and Publish" ignores property validation on properties that are **NOT** _varied by culture_. If the property **IS** set to be _varied by culture_, then "Save and Publish" behaves as expected and does not publish upon a validation fail.

### Steps to reproduce
- Install a new version of Umbraco 8.5.4
- Add an additional non-mandatory language with the fallback set to the default language.
- Create a doctype that can be varied by culture.
- Add a Textstring property to the doctype that has custom validation (e.g. validate as url) but make sure the property is NOT varied by culture.
- Create a content node in the content tree of that doctype.
- Add a value to the property that will fail the validation.
- Click "Save and Publish"
- The content node will successfully save and publish even though the property fails validation.

### Expected result
The content node should not publish if the property fails its custom validation.

### Actual result

As you can see in the GIF below, the content node is published even though the property fails its custom validation:
![validation fail](https://user-images.githubusercontent.com/17008780/76079145-f7316300-5f9b-11ea-9b5b-02b6e54038ac.gif)

In the GIF below I set the property to be "varied by culture" and then test again, this time it behaves as expected and the content node is not published:
![validation success](https://user-images.githubusercontent.com/17008780/76079156-fbf61700-5f9b-11ea-9d93-e157cf4f1860.gif)

**Comment by nul800sebastiaan** [comment] 2020-03-09 07:38
Thanks @OwainJ, I'm afraid I can't reproduce, can you spot anything I'm doing differently?

![7768](https://user-images.githubusercontent.com/304656/76192139-5e8c2480-61e1-11ea-9c6f-bc074232740c.gif)


I'll close this for now but let feel free to update if you have more info on how to reproduce!

**Closed** 2020-03-09 07:39 UTC

**Comment by OwainJ** [comment] 2020-03-09 09:02
Hi @nul800sebastiaan 

Thanks for looking into this!

Apologies, I only tested in 8.5.4 in my original report. It looks like the issue has been fixed in the latest release candidate (8.6.0-rc). Yay!

Cheers,

Owain
