### ISSUE TITLE
Netcore: When you create a doctype or datatype the focus should be in the name textbox

### ISSUE THREAD

**Issue by TwoMoreThings** [umbraco/Umbraco-CMS#10065] opened 2021-03-25 21:19 UTC
When creating a doctype or datatype, you have to click in the textbox before you can type the name, the focus should go to the textbox automatically

## Umbraco version

I am seeing this issue on Umbraco Netcore alpha4

Reproduction

Right click on the root document types or the data type folder and select Create

### Expected result

I expect to be able to start typing after I select Create from the context menu

### Actual result

I have to click on the text box first

**Comment by bergmania** [comment] 2021-03-26 07:12
Hi @TwoMoreThings, thanks for reporting.. 

I can't reproduce, what am I doing differently from you?

https://user-images.githubusercontent.com/1561480/112595642-fc618a00-8e0a-11eb-9e39-53cd85b9822a.mp4

**Comment by bergmania** [comment] 2021-06-17 12:09
I'll close this because I cannot reproduce. Feel free to reopen if it is still a problem on latest v9, and you can give reproduction steps :)

**Closed by bergmania** 2021-06-17 12:09 UTC
Labels: project/v9
