### ISSUE TITLE
[v14] Health Checks do not persist action parameters from check to action.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16477] opened 2024-05-29 14:38 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc5

### Bug summary

If you have a health check that adds a action parameter as part of an action during the check phase then when your used clicks on the action the action parameters are not passed on to the executeAction method, so you can't persist the actions between check and execute

(the `actionparameters` property is still there so presume it hasn't been deprecated). 

### Specifics

In previous versions the action parameters could be st during a GetStatus() method, and then be retrieved during Execute action.

### Steps to reproduce

HAve a health check that sets an action parameter. 

e.g this action sets a folder name in the action parameters. 

```cs
new HealthCheckAction($"removeFolders", Id)
{
    Name = $"Clean {folderName} folder",
    ActionParameters = new Dictionary<string, object>()
    {
        {  "folder", folderName }
    },
    Description = $"Remove any items in the {folderName} folder that are over {_cutOffHours} hours old"
});
```

then in an execute method, try to retrieve 

```cs
switch (action.Alias)
{
    case "removeFolders":
        if (action.ActionParameters?.ContainsKey("folder") is true)
        {
            string? folder = action.ActionParameters["folder"].ToString();
            return RemoveOldFolders(folder);
        }
        else
        {
            throw new ArgumentOutOfRangeException(nameof(action), $"No Folder for {action.Alias}");
        }
    default:
        throw new ArgumentOutOfRangeException(nameof(action));
}
```

this doesn't work becauee action.ActionParameters is empty when the executeAction method is called. 

### Expected result / actual result

ActionParameters should persist from `GetStatus` to `ExecuteAction`

**Comment by Zeegaan** [comment] 2024-06-05 08:53
I can reproduce this, thanks for reporting! 🐛 

Seems like there's some missing mapping going on backend-wise, and might need some front end work too, we will take a look 🕵️

**Comment by Zeegaan** [comment] 2024-06-05 09:25
Looks like it was purely some backend mapping that was missing, should be fixed in https://github.com/umbraco/Umbraco-CMS/pull/16557 😁

**Comment by Zeegaan** [comment] 2024-06-07 08:23
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16557

**Closed by Zeegaan** 2024-06-07 08:23 UTC
Labels: type/bug, state/reproduced, area/backend, affected/v14
