### ISSUE TITLE
U8.x: umbracoUrlAlias comma separated list is taken literally.

### ISSUE THREAD

**Issue by bmargevicius** [umbraco/Umbraco-CMS#5823] opened 2019-07-09 18:28 UTC
Not sure if this is a bug. Feels like a display bug. 
When having a property umbracoUrlAlias as a textstring. Having comma separated routes are displayed and clicked through as literal and not as individual routes. This happens in v8.02 and v8.1. 

![UmbracoUrlAlias](https://user-images.githubusercontent.com/24920023/60913263-01f0f800-a255-11e9-9b16-39de0cdc5465.gif)

I expect it not to 404 and to create two separate lines in the info tab. manually typing /gold or /golden does work. So it's not the routing that's failing. It's the display of multiple routes on the info tab that's buggy.

**Comment by nul800sebastiaan** [comment] 2019-07-11 09:53
Hey @bmargevicius - `umbracoUrlAlias` supports a single alias only, so this is expected behavior. I would look into IIS rewrite rules if you need to redirect multiple URLs to a single content item.

**Comment by bmargevicius** [comment] 2019-07-11 12:53
Not according to documentation... 
**umbracoUrlAlias**
This property when created as a text string lets you provide a comma separated list of alternate full URL paths for the node. For example, if your URL was /some-category/some-page/content-node, by adding an umbracoUrlAlias of "flowers", a user can navigate to the node by simply going to /flowers. The URL alias remains in the browser address bar as a 'mask' over the real URL. You can also specify paths like "flowers/roses/red".
ref: https://our.umbraco.com/documentation/Reference/Routing/routing-properties

**Comment by nul800sebastiaan** [comment] 2019-07-11 13:05
You'll note that this documentation requires an update for v8 though. 😅

**Comment by nul800sebastiaan** [comment] 2019-07-11 13:07
Ah, we're for some reason not showing the banner on this page that this is not up-to-date documentation. That's unfortunate.

**Comment by bmargevicius** [comment] 2019-07-11 13:12
So it's not supported anymore? This is weird. Because the comma separated routes actually work.

**Comment by ReVoid** [comment] 2019-07-11 13:39
@nul800sebastiaan Really? It was a pretty useful feature to add many aliases to one page. Is it really necessary to delete the feature. 

I hoped alias would be improved in v8, like make it repeatable textstrings to be more obvious to user. 

:(

**Comment by nul800sebastiaan** [comment] 2019-07-11 14:36
Well, I'll go be ashamed in a corner. I would've sworn this feature was removed. But nope, all good! It's just the URLs that are displayed wrong on the info tab. My bad, forget I said anything! 🙈

We'd love some help getting the URLs to display correctly if you can. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bmargevicius** [comment] 2019-07-11 14:40
Get the cone of shame.
https://media.giphy.com/media/l2JhMGnhyJGlFfSzS/giphy.gif

No worries. Now that we're open for discussion. @ReVoid asked for more of an `IEnumerable<string>` experience. I don't like parsing strings either.

**Comment by nul800sebastiaan** [comment] 2019-07-11 14:44
😂

Sounds alright, but then it suddenly needs to be a custom property editor. It was nice that it was just a text string..


Also, let me challenge you on why you would want to use this at all as I don't understand. You know that Google / search engines punish you for having duplicate content on your site. Why do you actually needto be able to do this? I'm asking out of ignorance, not because I'm trying to be a wise-ass.. I probably missed something so I'm curious to learn more.

**Comment by bmargevicius** [comment] 2019-07-11 15:15
I guess a shopping/eCommerce site could be another example of where you want the same content to lie under different urls. 
/products/super-cone = canonical, and where data entry happens in the backoffice
/medical/cone/of/shame/super-cone
/veterinary/cone/of/shame/super-cone

I guess the general case is: You want content to live in two spots, and you have a canonical url that's not desirable(?).

**Comment by ReVoid** [comment] 2019-07-11 16:24
@bmargevicius 
> I don't like parsing strings either.

As everybody does. Everybody like cakes, not a string parsing, right? 😋

@nul800sebastiaan 
>lso, let me challenge you on why you would want to use this at all as I don't understand. You know that Google / search engines punish you for having duplicate content on your site.

I am not a SEO-guy at all, but I guess, using canonnical urls solves the problem, it is like to tell Google "Hey, Goo, here is my real page here at cannonical url, it is the same as that url, do not index it again, please". [Here ](https://support.google.com/webmasters/answer/139066?hl=en)more about.

I remember a single personal case with multilingual site, I wanted page to be avaliable as two similar urls like `unicorns.com/eng` and `unicorns.com/en`

**Comment by kjac** [comment] 2019-07-12 18:20
Ain't that funky. PR in #5875 fixes the issue at hand; supporting `IEnumerable<string>` should be considered and handled in a separate issue.

**Comment by nul800sebastiaan** [comment] 2019-09-30 16:32
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5875

**Closed** 2019-09-30 16:32 UTC
Labels: community/pr, type/bug

**Comment by ReVoid** [comment] 2019-10-01 17:12
> Fixed in #5875

Good, but what about v7 branch? There is the same issue
