### ISSUE TITLE
Media Picker (Media Picker Legacy & Media Picker 3) has broken big thumbnail after updating to version 8.18.6 (Image stored in AWS S3)

### ISSUE THREAD

**Issue by by1991** [umbraco/Umbraco-CMS#14140] opened 2023-04-21 09:13 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.6

### Bug summary

![umbraco-v8-18-5](https://user-images.githubusercontent.com/91252531/233595907-13278d6f-cf5f-4a30-932a-21642caf423f.png)
Media Picker Thumbnail is fine in version 8.18.5

![umbraco-v8-18-6](https://user-images.githubusercontent.com/91252531/233596167-cfe6adb1-c576-4246-949a-a9d75657ad41.png)
Media Picker Thumbnail is broken in version 8.18.6

Error in console is:
401 (Unauthorized) for this API: /umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail

Is this a bug in version 8.18.6? 

Please help to check, thank you!

### Steps to reproduce

Update UmbracoCMS from 8.18.5 to 8.18.6

### Expected result / actual result

Media Picker Thumbnail should not be broken in version 8.18.6

**Comment by inetzo** [comment] 2023-04-21 10:51
Hi @by1991 , i guess it's the same problem as https://github.com/umbraco/Umbraco-CMS/issues/14056

**Comment by by1991** [comment] 2023-04-21 13:04
@inetzo thanks for your comment, seems the error is different, I got 401 (Unauthorized) for this API: /umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail after upgrading to version 8.18.6

**Comment by Zeegaan** [comment] 2023-04-24 11:36
Hmm I cannot reproduce this, this is me after having upgraded to 8.18 (using the media picker 3): 
![image](https://user-images.githubusercontent.com/70372949/233985000-02b28b96-68a4-4232-9a4c-4967878a584e.png)
Am i doing something wrong here? 🤔 
If not Could you try and reproduce this on a clean install ? 🙈

**Comment by by1991** [comment] 2023-04-25 02:29
@Zeegaan Thanks for your comment, I'm using the Legacy Media Picker which got the 401 error, shall I try using Media Picker 3 instead?

**Comment by Zeegaan** [comment] 2023-04-25 05:49
@by1991 Yes, that would be great 🙏

**Comment by by1991** [comment] 2023-04-25 07:57
Hi @Zeegaan I tried to change Media Picker (Legacy) to Media Picker 3, but got this error for the images, do you know how to migrate the content (media files) for Media Picker 3?

`String "[{"key":"ecc7f489-de40-4927-9197-fbfffdf77fed"" is not a valid udi.`

![image](https://user-images.githubusercontent.com/91252531/234212012-42f28477-67f6-4079-8783-213c241315f6.png)

**Comment by by1991** [comment] 2023-04-25 09:07
is it possible to fix the Media Picker (Legacy) thumbnail for version 8.18.6?

**Comment by Zeegaan** [comment] 2023-04-25 09:16
@by1991 hmmm seems some community members had success with just changing it: https://our.umbraco.com/forum/using-umbraco-and-getting-started/106798-convert-media-picker-v2-image-to-v3

And I'll take it up with the team once i can reproduce this 👍

**Comment by by1991** [comment] 2023-04-26 06:26
@Zeegaan thanks for checking, I managed to fix the errors for Media Picker 3 by deleting App_Data/TEMP folder and reload the site, but I still got the same broken thumbnail after upgrading to version 8.18.7 with Media Picker 3 from version 8.18.5

![image](https://user-images.githubusercontent.com/91252531/234487309-7d44783b-18fa-4c3b-99cc-80a1262be1c9.png)

![image](https://user-images.githubusercontent.com/91252531/234487678-bb2e8a9f-232e-4ca4-85f3-18fcbb2b77cb.png)

**Comment by Zeegaan** [comment] 2023-05-01 09:22
Images stored in AWS 3?
Are you using a package for AWS image file system provider? Or how are you achieving that 😅 
This seems like an issue with a 3rd party library 🤔

**Comment by Zeegaan** [comment] 2023-05-02 10:57
And just to confirm, you're not having any special characters in your thumbnails? 
This might be the same issue as https://github.com/umbraco/Umbraco-CMS/issues/14056

**Comment by by1991** [comment] 2023-05-02 11:13
@Zeegaan no special characters, I tested the same source:

`/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=https%3A%2F%2Faximedia.s3.amazonaws.com%2Frebrand-prod%2Fhcwon1q5%2Fj2484-axi-deposit-bonus-mancity-lp-2560x930-v1-blank.jpg&rnd=0.2430989714898768`

thumbnail is working in version 8.18.5, but broken in version 8.18.6 and 8.18.7, so maybe not an issue with 3rd party library

**Comment by Zeegaan** [comment] 2023-05-02 11:39
yes but how are you storing those AWS images in umbraco 🤔

**Comment by by1991** [comment] 2023-05-03 01:14
@Zeegaan 
![image](https://user-images.githubusercontent.com/91252531/235816258-4fe56a5a-24e4-4b55-9469-61de32f9e0d1.png)

I'm using AWS S3 SDK, implementing IFileSystem interface, and store the image as UmbracoFile

`public void AddFile(string path, Stream stream)
        {
            using (var memoryStream = new MemoryStream())
            {
                stream.CopyTo(memoryStream);
               
                var request = new PutObjectRequest
                {
                    BucketName = _bucketName,
                    Key = ResolveBucketPath(path),
                    CannedACL = S3CannedACL.PublicRead,
                    ContentType = System.Web.MimeMapping.GetMimeMapping(path),
                    InputStream = memoryStream,
                    ServerSideEncryptionMethod = ServerSideEncryptionMethod.None
                };
                if (!string.IsNullOrEmpty(_awsCacheControl))
                    request.Headers.CacheControl = _awsCacheControl;
                var response = Execute(client => client.PutObject(request));
            }
        }`

**Comment by by1991** [comment] 2023-07-03 08:28
@Zeegaan Hi, we still have this problem after updating to version 8.18.8, Thumbnail is working under Media page:

![image](https://github.com/umbraco/Umbraco-CMS/assets/91252531/1a4e5d7e-ba2b-45a4-8223-f9839d0d65b7)

But not working in Media Picker:
![image](https://github.com/umbraco/Umbraco-CMS/assets/91252531/75e9ad13-55e4-4736-a8a6-0fc9401d7a3f)

Here are the values in src:
/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=https%3A%2F%2Faximedia.s3.amazonaws.com%2Frebrand-dev%2Fv30haw1g%2Fen-desktop-new.png&rnd=0.28184666788546275

/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=https%3A%2F%2Faximedia.s3.amazonaws.com%2Frebrand-dev%2Fkfjnrlxj%2Fen-mobile.jpg&rnd=0.3306409860201023

is % in image URL supported for originalImagePath?

**Comment by andr317c** [comment] 2023-07-06 11:44
Hey!

I just took a look at your issue. I tried reproducing your error. I was using Azure Blob Storage instead of AWS for my files. I was not able to get the same 401 error you got with the Legacy Media Picker or MediaPicker3. Even when I included `%` in the orginalImagePath.  

A thing I stumbled upon was when I upgraded and I accidentally allowed the file Media/Web.config to be overwritten, when the file was overwritten, it removed this line: 
![MissingLine](https://github.com/umbraco/Umbraco-CMS/assets/73799582/ac661c3a-d655-45e6-b043-18404ecd4886)

`<add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler"/>`
I would recommend you check if the same thing has happened to your file. 

I will go ahead and close this issue since I was not able to reproduce it. Please reopen the issue if this does not fix your issue 😄

**Closed by andr317c** 2023-07-06 11:44 UTC
Labels: state/needs-investigation, type/bug

**Comment by by1991** [comment] 2023-08-04 09:19
@andr317c thank you, I tried to add <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler"/> to Media/Web.config, but thumbnail is still broken in version 8.18.6 or later.

The weired thing is thumbnail is working fine in version 8.18.5 and broken in version 8.18.6 with same settings / configs.

**Comment by umbracocommunity** [comment] 2025-10-24 08:12
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/media-picker-update/6376/2
