### ISSUE TITLE
Media cache seems to be broken after updating from 12.2.0 to 12.3.0

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#15146] opened 2023-11-06 18:25 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.0

### Bug summary

After updating from 12.2.0 to 12.3.0 noticed all methods getting media values return empty.
As it seemed a cache issue, tried rebuilding the cache database but it didnt correct the issue.
Only updating back to 12.2.0 and rebuilding the cache solved the problem.
It may be related to this issue:
https://github.com/umbraco/Umbraco-CMS/issues/13525

### Specifics

where this line
`var medias = Model.Value<IEnumerable<MediaWithCrops>>("medias");`
returned the medias after updating was returning empty.

### Steps to reproduce

Update a website v 12.2.0 to 12.3.0

**Comment by teeto** [comment] 2023-11-06 18:27
It may be related to this issue too:
https://github.com/umbraco/Umbraco-CMS/issues/15117

**Comment by bergmania** [comment] 2023-11-07 08:14
Hi @teeto.

Thanks for reporting.. I test if I can reproduce after the fix for  https://github.com/umbraco/Umbraco-CMS/issues/15117, before we do a patch

**Comment by bergmania** [comment] 2023-11-07 09:13
I can confirm this is duplicate of #15117

**Closed by bergmania** 2023-11-07 09:13 UTC
Labels: type/bug
