### ISSUE TITLE
Custom index and link to node

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13674] opened 2023-01-15 20:29 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When building a custom Examine index and populating the node name field this act as a link using the id field, but in a custom index it may not be an Umbraco node, so the content opening in infinite editor throws an error.

But without settting `nodeName` field this column is just blank, where a `name` field could be useful instead.

Maybe it should be possible to configure whether the Node Name field should open the content editor (and act as link/button) ... or configure a default "name" field, e.g. `name` instead of `nodeName`, where name field doesn't link to content node?

But the index could theoretically both contain some Umbraco nodes / content and custom data, so maybe it should be configurable per `ValueSet`?

However it may be difficult to show both `name` and `nodeName` columns.

### Steps to reproduce

Build a custom Examine index with a custom id or guid as id.
Furthermore add a value in Node Name field.

After indexing find a result and notice clicking node name field throws an error because the Umbraco content doesn't exist.

**Comment by elit0451** [comment] 2023-01-16 12:15
Hey @bjarnef 👋 

Could you possibly supply some code samples to help with a quicker reproduction of the issue? 🙂 Regarding your ideas, everything after:
> "Maybe it should be possible to ..."

sounds to me like a feature request, so perhaps you should consider converting it to a discussion!

**Comment by bjarnef** [comment] 2023-01-17 07:35
Hi @elit0451 

Yeah, it may be a feature request - or bug that it isn't handled, where custom index typical doesn't include Umbraco related content (although it could - or a combination of both).

A simple example to reproduce this take the great demo site from @Adolfi and in `ValueSet` set `nodeName` field as well and as `id` use a random int id or `Guid` e.g. by using `Guid.NewGuid()`:
https://github.com/Adolfi/UmbracoNineDemoSite/blob/master/UmbracoNineDemoSite.Core/Features/Search/Examine/Index/ContentValueSetBuilder/ProductValueSetBuilder.cs#L43

**Comment by elit0451** [comment] 2023-01-17 10:07
So, I've followed our docs about creating a custom index - https://docs.umbraco.com/v/10.x-lts/umbraco-cms/reference/searching/examine/indexing#creating-your-own-index

And I tried changing the id (ex: in ProductIndexValueSetBuilder):
```c#
public class ProductIndexValueSetBuilder : IValueSetBuilder<IContent>
{
    public IEnumerable<ValueSet> GetValueSets(params IContent[] contents)
    {
        foreach (var content in contents)
        {
            var indexValues = new Dictionary<string, object>
            {
                ["name"] = "Test name", // changed it from content.Name
                ["id"] = Guid.NewGuid(), // changed it from content.Id
            };

            yield return new ValueSet(Guid.NewGuid().ToString(), "content", indexValues); // changed the id value from content.Id.ToString()
        }
    }
}
```

And I couldn't reproduce the error you've got:

https://user-images.githubusercontent.com/21998037/212869777-33122114-10ad-4357-aa8a-947c6c330d15.mp4



Let me know if I missed any specifics 🙂

**Comment by bjarnef** [comment] 2023-01-17 10:15
Hi @elit0451 

Yes, then set this as well 😉

```
["nodeName"] = "Test name",
```

It will set a value in the empty "Name" column and act as link.. this use the `id` to open content editor, but it will fail since there is no content node with the id / guid (unless you are very lucky the generated guid actually match a key of an Umbraco node).

**Comment by elit0451** [comment] 2023-01-17 10:41
Well, I do see the error now, but it is to be expected that the custom/random id that you set for that item is not found, as you said. The "link" you mention is just doing a request to `/umbraco/backoffice/umbracoapi/content/GetById?id=` and if the content node does not exist in Umbraco it won't be found..

But if you don't want the link to be there I can offer an up-for-grabs task for making the dashboard view check for a custom boolean index field value and when set to true (_it will be the case in your scenario since you added custom ids_) then it won't be possible to open a content editor for that item.

We'd also need to update our docs so that people are aware of this option  🙂

**Comment by bjarnef** [comment] 2023-01-17 13:52
Yes, then it would be great with some feedback from HQ how this should be configurable?
Per index or per `ValueSet` (theoretically the index could contain both Umbraco node data and custom data).

Another option could be to handle a generic `name` property to which would show up instead without link and maybe a config option to specify default field used as name property?

**Comment by bjarnef** [comment] 2023-01-19 07:45
Another thing is that when an error occur, it is not possible to close the dialog again. One has to refresh page to continue navigating backoffice.

**Comment by elit0451** [comment] 2023-01-19 07:48
I will talk to the team and get back when I have an answer 🙂 (_warning: might take some time though_)

**Comment by kjac** [comment] 2023-01-30 10:45
Hi @bjarnef,

The link is only appended if the `ValueSet` is created explicitly as containing content, media or members. If you replace `IndexTypes.Content` with something else in the `ValueSet` creation, the link is not created - whatever is in the `nodeName` field will simply be rendered as text.

You can verify this by replacing `IndexTypes.Content` with `"SomethingSomething"` in [the core content `ValueSet` creation](https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs#L146). Since the core applies a `ValueSetValidator` to its content indexes, you also need to whitelist `"SomethingSomething"` as a valid category in [this line](https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs#L16). With these changes applied, go ahead and rebuild the external index, and you'll see page names in the "Name" column without links:

[13674-3.webm](https://user-images.githubusercontent.com/7405322/215455264-f9be013e-a75a-4f2f-b361-5040c04caf03.webm)

I hope this helps 😄 I'll go ahead and close this issue now; feel free to reopen if the steps above do not work.

**Closed by kjac** 2023-01-30 10:45 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11

**Comment by bjarnef** [comment] 2023-01-30 11:40
@kjac it makes sense, but isn't it valid to use `content` as Index Type in a custom value set? 😉
The benefits from this is that it would simplify the Lucene query used to query a multi-searcher combining to or more indexes.

Furthermore we have a base query builder (wrapping the querying base content e.g. by index type, nodetype alias etc.) and some other query builders inheriting this to query e.g. specific properties on a `Course` document, while a `CourseInstance` exists in a custom index.

Furthermore the dashboard requires a `nodeName` property, but there is nothing wrong naming it `title`, `heading` or something else, but one has to set `nodeName` property anyway to see this in the dashboard results.
