### ISSUE TITLE
Exception thrown while deserializing the token upon loggining in to back office

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#16533] opened 2024-05-31 12:30 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.3, 13.2.1

### Bug summary

We are receiving exceptions of token deserialisation when logging in to the back office.

### Specifics

Error details:

> 31 May 2024 13:20:11 	Error 	WK-DS-0191 	An exception was thrown while deserializing the token.
> 
> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
> 
>  ---> System.Security.Cryptography.CryptographicException: The key {7ddd3c3f-3d15-47c8-9a1c-1cd6d03fabe2} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
> 
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
> 
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
> 
>    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
> 
>    --- End of inner exception stack trace ---
> 
>    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
> 
>    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
> 
> Timestamp 	2024-05-31T12:20:11.5594154+00:00
> @MessageTemplate 	An exception was thrown while deserializing the token.
> EventId 	
> 
> {
>   "TypeTag": null,
>   "Properties": [
>     {
>       "Name": "Id",
>       "Value": {
>         "Value": 7
>       }
>     },
>     {
>       "Name": "Name",
>       "Value": {
>         "Value": "TokenDeserializeException"
>       }
>     }
>   ]
> }
> 
> SourceContext 	
> ActionId 	cf395ddc-4203-4a14-9962-12e7a5e35810
> ActionName 	Umbraco.Cms.Web.BackOffice.Controllers.AuthenticationController.PostLogin (Umbraco.Web.BackOffice)
> RequestId 	40001151-0003-dd00-b63f-84710c7967bb
> RequestPath 	/umbraco/backoffice/umbracoapi/authentication/postlogin
> ProcessId 	15120
> ProcessName 	w3wp
> ThreadId 	16
> ApplicationId 	29830c6038e821cf53320d438c1c05735a7e6ae5
> MachineName 	
> Log4NetLevel 	ERROR
> HttpRequestId 	93e797d4-19b8-4a13-962f-af42e0aae793
> HttpRequestNumber 	
> HttpSessionId 	fb9e4835-ee6a-8b88-6361-5dcabe9c521c 

### Steps to reproduce

Happens on loging in to Umbraco

### Expected result / actual result

Should not throw the error and decrypt the token

**Comment by enkelmedia** [comment] 2024-05-31 15:04
I think that this is the same issue as the one i reported: https://github.com/umbraco/Umbraco-CMS/issues/16107 ?

**Comment by kjac** [comment] 2024-06-03 05:07
Hi @ewuski,

Thank you for reaching out. This does indeed look like a duplicate of #16107 - thank you @enkelmedia for pointing that out 👍 

I'll close this in favor of #16107.

**Closed by kjac** 2024-06-03 05:07 UTC
Labels: type/bug
