### ISSUE TITLE
Repeatedly cropping an image and resetting crops results in a corrupted image 

### ISSUE THREAD

**Issue by mennomout** [umbraco/Umbraco-CMS#13783] opened 2023-02-03 13:22 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0-rc.preview.121

### Bug summary

When adding a crops to the Image Cropper data type and cropping an image -> resetting crops in the media library repeatedly will corrupt the image. 

Also affects the following Umbraco versions: 
9.5.4
10.4.0
10.3.1
 8.18.3

### Specifics

This issue originates in the frontend where the coordinates for the crop are set to null/empty. Then when the backend deserializes the value it throws an exception: 
`Newtonsoft.Json.JsonSerializationException: 'Error converting value {null} to type 'System.Decimal'. Path 'crops[0].coordinates.x1', line 1, position 104.'` 
After that the error is handled like this: 
`value = new ImageCropperValue { Src = val.ToString() };` 
This results in a broken image.

### Steps to reproduce

1. Add a crop the the image cropper data type
2. Add an image to the media library
3. Apply a crop to the image and save
4. Reset the crop and save
5. Apply a new crop and save
6. Your image will break during this last steps save. 
![cropcorruptingimage](https://user-images.githubusercontent.com/77411834/216613882-1f914969-51ff-43a5-be8c-d6dd0f7ab1a9.gif)

### Expected result / actual result

Expected result:
Crop's can be applied and reset indefinitely. Or if something corrupts it the image isn't affected.

Actual result:
Applying and resetting a crop multiple times corrupts the crop and image.

**Comment by kjac** [comment] 2023-02-06 11:06
@mennomout thank you for reaching out 👏 

I can reproduce this on V10.4, this is definitively a issue. I'm marking this as up for grabs, hopefully someone will pick this up and fix it.

I suspect some state is preserved after resetting the crop; if you look closely, the image is weirdly positioned when you attempt to redo a crop after resetting it. 

If you reload the browser before redoing the crop, nothing gets corrupted - which again points at some residue state lingering in the cropper after resetting a crop.

**Comment by Emetico** [comment] 2023-02-09 13:36
I can also reproduce this on 9.5.4 and 10.4.0.

Can we do anything to give it a higher priority?

**Comment by miski** [comment] 2023-02-17 09:12
I took a look at this and the issue seems to be in `umbraco.services.cropperHelper.pixelsToCoordinates(image, width, height, offset)`. The function tries to access `image.top` and `image.left` which don't exist if there is no existing crop.

I'll make a pull request for a fix shortly.

**Comment by mennomout** [comment] 2023-02-17 15:01
Thank you for the pull request @miski! @kjac Could someone from the PR-team take a look at it?

**Comment by kjac** [comment] 2023-02-20 06:06
Hi there @mennomout (and @miski) 👋 

Awesome with a PR to fix this 🚀 I am marking this as ready for review, the PR team will take over from here 😄

**Closed** 2023-03-02 15:52 UTC
Labels: community/pr, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11, affected/v12
