### ISSUE TITLE
Members Login takes about 10+ seconds

### ISSUE THREAD

**Issue by kikodev714** [umbraco/Umbraco-CMS#15543] opened 2024-01-08 18:09 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 10.6.1 + USkinned 3.0.5

### Bug summary

Members logging in takes about 10+ seconds. 

Umbraco 10.6.1
USkinned 3.0.5

### Specifics

This is using the out of the box members area and login form of USkinned 3.0.5
This happens even when using invalid credentials.

### Steps to reproduce

**Behavior:**

![CMS_Members_Three](https://github.com/umbraco/Umbraco-CMS/assets/140512863/6ddd0d98-328d-4ff8-9745-384163adacf9)

**Replication Steps:**
1. Add members
2. Add members to a member group
3. Run the out of the box members-area page from uSkinned (https://localhost:44384/members-area/)
4. Enter credentials and login once prompted.

### Expected result / actual result

1. Login should only take a second or less to be processed.
2. We need specifics on what causes the problem and how to mitigate.

**Comment by andr317c** [comment] 2024-01-09 11:19
Hey!
Thanks for reporting this issue. I tried on versions 10.6.1 and 10.8.3, without using USkinned. I was unable to reproduce the issue. So the issue seems to be something with USkinned. I will go ahead and close this issue. 

![FastLogin](https://github.com/umbraco/Umbraco-CMS/assets/73799582/b5bb6384-2cb7-4e97-b0fa-94f2fadcf0ac)

If you can reproduce this on a clean install of Umbraco please reopen this issue.

**Closed by andr317c** 2024-01-09 11:19 UTC
Labels: type/bug
