### ISSUE TITLE
V8.3.0 - logResource.getPagedUserLog(userLogOptions) returns empty

### ISSUE THREAD

**Issue by AmarTrebinjac** [umbraco/Umbraco-CMS#7503] opened 2020-01-24 13:46 UTC
Calling the method logResource.getPagedUserLog(userLogOptions) as described in the documentation [here](https://our.umbraco.com/documentation/Tutorials/Creating-a-Custom-Dashboard/) returns zero items.

## Umbraco version

I am seeing this issue on Umbraco version: 8.3.0

Reproduction
------------

### Bug summary
I want to get the current users logs to do various things such as showing last saved, created, etc.

### Steps to reproduce

1. Create a dashboard using package.manifest. [Guide here](https://our.umbraco.com/documentation/extending/dashboards/)
2. Create the necessary view and controller for your dashboard.
3. Include logResource in your angular controller.
4. Copy paste the relevant part of the code from the documentation into your controller. Looks like this:

```
    var userLogOptions = { 
        pageSize: 10,
        pageNumber: 1,
        orderDirection: "Descending",
        sinceDate: new Date(2018, 0, 1)
    };

    logResource.getPagedUserLog(userLogOptions)
        .then(function (response) {
            console.log(response)
        });
```

### Expected result

Get an object that includes an array "items" with the log items in it.

### Actual result

Returns the expected object, but without any items.

**Comment by krugarmatt** [comment] 2020-01-28 12:42
I'm also experiencing this issue whilst following the same tutorial (https://our.umbraco.com/documentation/extending/dashboards/) using Umbraco v8.5.2. The call to **logResource.getPagedUserLog** in the Angular controller returns an object with a property called **items** which is an empty array. I'm expecting this array to be populated with events since the user I'm logged in as has edited documents.

I downloaded a copy of the Umbraco source code from this repository and ran it locally to see if I could find the issue. It seems like it might be related to the ID of the currently logged in user. Whilst following the tutorial I am logged in as the initial user that's created when the Umbraco instance is installed. Checking the database record shows the user ID of this initial user is **-1**.

So in our Angular controller, when we're calling **logResource.getPagedUserLog**, the following API controller action is hit:

https://github.com/umbraco/Umbraco-CMS/blob/f55e05da79ca827b192a03d6d1271501bced0b66/src/Umbraco.Web/Editors/LogController.cs#L43-L63

After the method on line **56** returns, **userId** is **-1**. On line **57** the following method is called:

https://github.com/umbraco/Umbraco-CMS/blob/b2d019bfe17883f7bdfca82fda027a9517edb839/src/Umbraco.Core/Services/Implement/AuditService.cs#L140-L157

As you can see on line **145**, there's a check to make sure the userId is greater than zero which in our case it isn't. This means that the method then simply returns an empty list of audit items which would explain why in the Angular controller, we're also not getting any audit items.

I can confirm that following works as expected:
1. Create a new administrative user.
2. Check that the **userId** is greater than zero.
3. Login to the backend as the new user.
4. Edit a document.
5. View the custom dashboard where the events/audit logs for the recently edited document are displayed.

So at first glance it seems that the logic isn't expecting the userId to be less than zero but during the installation of Umbraco, the initial user that's created has an id of **-1**.

**Comment by nul800sebastiaan** [comment] 2020-01-29 08:30
Aha! Thanks! This triggered something in my memory seeing it somewhere else! There's an issue with all those details and an almost finished PR: https://github.com/umbraco/Umbraco-CMS/issues/6812

Once #6812 is fixed, this will also work as expected. So I'll close this issue as a duplicat, make sure to track the progress on #6812 for updates. 👍

**Closed by nul800sebastiaan** 2020-01-29 08:30 UTC
Labels: state/needs-investigation
