### ISSUE TITLE
8.7RC Block List Editor, inline create-bar: Plus icon is not centered on Chrome

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8839] opened 2020-09-07 10:52 UTC
In Edge this works fine, but on Chrome the plus icon is not centered. its a few pixels too low.

![image](https://user-images.githubusercontent.com/6791648/92380144-ed361b80-f108-11ea-9a87-2a58a6b8c454.png)

**Comment by bjarnef** [comment] 2020-09-07 11:07
@nielslyngsoe I recently fixed this in https://github.com/umbraco/Umbraco-CMS/pull/8763 but maybe something else has changes or update in Chrome?

**Comment by nielslyngsoe** [comment] 2020-09-07 11:10
@bjarnef I think your fix corrected this for Edge, but currently, it's not right in Chrome on my machine? I tried to correct this, but gave up after a short time, too many things to juggle, so that's why I put it as an error for now. But maybe you can have a double check?  BTW. I´m on Chrome, Mac OS. Maybe that's the problem?

**Comment by bjarnef** [comment] 2020-09-07 11:35
@nielslyngsoe it was looking correct in Chrome as in the gif in the PR here https://github.com/umbraco/Umbraco-CMS/pull/8763
But I noticed that after this a new update to Chrome has been released. I haven't tested in the latest though or there might be issues in other browsers.

Maybe something like line-height in the class `.__plus` might help?

**Comment by nielslyngsoe** [comment] 2020-09-07 11:37
@bjarnef I did try that, I think it needs to be contained in a separate element, to align height calculations in all browsers, but might also just be mee who did it wrong, trying to be shift...

**Comment by bjarnef** [comment] 2020-09-07 19:12
@nielslyngsoe I have tested it on a few different browsers on Windows and I can't reproduce this issue with latest changes in `v8/8.7` branch.

**Chrome v85.0.4183.83**

![image](https://user-images.githubusercontent.com/2919859/92412957-42485080-f14e-11ea-86b6-88015d3bd794.png)

**Firefox v80.0.1**

![image](https://user-images.githubusercontent.com/2919859/92413002-715ec200-f14e-11ea-9413-38d36c6ab2d7.png)

Microsoft Edge v44.18362.449.0

![image](https://user-images.githubusercontent.com/2919859/92413103-d5818600-f14e-11ea-856e-076a62b6e342.png)

**Comment by bjarnef** [comment] 2020-09-07 19:15
@greystate maybe you can help with this? 🧐🤔

**Comment by nielslyngsoe** [comment] 2020-09-08 07:06
@bjarnef does indeed look correct. I just did some more testing to confirm that it's just off in MacOS.
It seems that Lato isn't identical for MacOS and Windows. Since its just a Plus icon. I´m going to change the font for this one, to one that is identical between OS.

**Comment by bjarnef** [comment] 2020-09-08 07:10
@nielslyngsoe ahh, yes I think this one is a "+" and not a font icon. Maybe use same icon as in grid editor add-button?

**Comment by greystate** [comment] 2020-09-08 08:17
> @greystate maybe you can help with this? 🧐🤔

Yep - had a look last night and came to the same conclusion, that it was very hard to get the alignment correct between browsers, as the font was treated differently - even between Safari & Firefox on macOS.
Was going to suggest an SVG instead...

**Comment by nielslyngsoe** [comment] 2020-09-08 08:42
I have now made this PR that uses the icon instead as @bjarnef  suggested. Great input, thanks!
https://github.com/umbraco/Umbraco-CMS/pull/8843

**Comment by warrenbuckley** [comment] 2020-10-01 11:12
Fixed in PR #8843  due for release in 8.7.1

**Closed by warrenbuckley** 2020-10-01 11:12 UTC
Labels: category/ui, community/up-for-grabs
