### ISSUE TITLE
Media Picker v3 - Amount (min and max) isn't stored and working

### ISSUE THREAD

**Issue by cheeseytoastie** [umbraco/Umbraco-CMS#10289] opened 2021-05-19 10:32 UTC
### Which Umbraco version are you using?

v9 beta002

### Bug summary

If you create a fresh site I usually create a Single Image Picker. 
Chose the v3 Media Picker. Went to set the amount from 0 - 1 - this isn't saved on save / submit. 

If you then try to use this datatype on a content node

### Steps to reproduce

Create a data type "Single Media Picker"

Select "Media Picker v3"

Set the amounts - any figures though I used 0 - 1. 
Save

Reload the datatype you'll see the amounts are not saved. 

If you add to a doctype and try to add an image you get a warning:

Minimum undefined entries, requires -1 more.  

### Expected result / actual result

Expected values to save. 

Expected ability to have 0 -1 images picked on doctype / content node.

**Comment by nul800sebastiaan** [comment] 2021-05-20 11:12
Thanks @cheeseytoastie! I can reproduce this, even in the latest nightly build. I don't know if this because the v8 branch has only been partially merged up (Media Picker v3 is brand new in the upcoming 8.14) or if there's a different problem. In v8 it works perfectly.

**Comment by nul800sebastiaan** [comment] 2021-05-21 09:48
Looks like we're definitely out of sync on the v9 branch, so that must be it, I'll like this to https://github.com/umbraco/Umbraco-CMS/issues/10295 which should have the same cause.

**Comment by nul800sebastiaan** [comment] 2021-05-27 09:26
Update: it wasn't because we were out of sync, after merging, this is still a problem.

**Comment by elit0451** [comment] 2021-06-04 10:42
Fixed in #10370

**Closed by elit0451** 2021-06-04 10:42 UTC
Labels: project/v9, release/9.0.0-beta004, type/bug
