### ISSUE TITLE
No notifications mail send for delete actions  U8.11.1

### ISSUE THREAD

**Issue by zonor** [umbraco/Umbraco-CMS#11021] opened 2021-09-02 14:48 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

 8.11.1

### Bug summary

I will not receive a notifications mail after someone else deletes some content.
All the other triggers like publish, update, restrict public assess are working perfectly and i receive a nice email.

### Steps to reproduce

Select a node and check all the checkboxes.
Let an other user delete some content under that node and wait for the mail.
 
![2021-09-02 16_44_53-Content - anet-qas](https://user-images.githubusercontent.com/5838221/131865055-4b3ca4bf-fdce-4f96-a7a7-ea10a0c4885f.png)

### Expected result / actual result

I would like to receive a notification mail after the delete trigger

**Comment by nul800sebastiaan** [comment] 2021-09-02 15:19
Thanks @zonor! I can't reproduce the problem on Umbraco 8.16.0:

![image](https://user-images.githubusercontent.com/304656/131870628-e546860c-82e1-4903-a98a-9a9058776b75.png)


So I believe it's been fixed in the mean time! I will encourage you to upgrade to the latest version and try again. 👍

**Closed by nul800sebastiaan** 2021-09-02 15:19 UTC
Labels: type/bug

**Comment by zonor** [comment] 2021-09-06 07:22
HI Sabastiaan,
Oké, thanks for your reply, i will check it in the new version.

**Comment by zonor** [comment] 2021-09-06 11:55
Hi Sabastiaan,
I see I only receive a DELETE mail when I register the notification directly under one peace of content.
We have a situation where we set the notification on a couple of levers higher in the content tree.
That works perfect for all the notifications except for the DELETE trigger.
