### ISSUE TITLE
Root media folder "Images" not visible after v8 migration

### ISSUE THREAD

**Issue by balintbako** [umbraco/Umbraco-CMS#6196] opened 2019-08-26 10:43 UTC
After migrating from v7.15.1 to v8.1.3 the root Media folder, called "Images" is not visible in the Media tree but it is visible in the Media list.
I have added a 2nd root folder called "Test" and that is visible in the tree and the list, but Images is still only visible in the list.
This is not consistent and both should be visible in the tree and the list as well.

Node Data:
id	trashed	parentID	nodeUser	level	path	sortOrder	uniqueID	text	nodeObjectType	createDate
1216	0	-1	-1	1	-1,1216	0	39AEEDDF-CC9E-401D-B5D5-45431D9217D4	Images	B796F64C-1F99-4FFB-B886-4BF4BC011A9C	2018-01-29 09:12:07.557
2526	0	-1	-1	1	-1,2526	1	3B3558D4-B1A5-4A95-88E1-8E86B965323F	Test	B796F64C-1F99-4FFB-B886-4BF4BC011A9C	2019-08-26 12:30:45.597

**Comment by stevemegson** [comment] 2019-08-26 10:54
Have a look at #6158. Media folders created before 7.8.0 didn't show up in the tree in 7.15.0. This was fixed in 7.15.1, but v8 needs a similar fix.

**Comment by balintbako** [comment] 2019-08-26 10:58
Seems to be duplicate of #6192

**Comment by nul800sebastiaan** [comment] 2019-08-27 07:18
Yep, that's the same issue. I'll close as a duplicate of #6158. 👍

**Closed by nul800sebastiaan** 2019-08-27 07:18 UTC
