### ISSUE TITLE
The overlay pop-up "Choose child node" of "Allowed child node types" does not show

### ISSUE THREAD

**Issue by johnsharp1975** [umbraco/Umbraco-CMS#9188] opened 2020-10-16 19:43 UTC
A brief description of the issue goes here.

The overlay stylesheet appears to keep a popup hidden.

## Umbraco version

I am seeing this issue on Umbraco version: 8.8.0

Reproduction
------------

I've started with 8.7.0 and upgraded to 8.8.0. When I open one of the "Document types" I can see an item under "Permissions" which has "Allowed child node types". When I press "Add child" the screen darkens but no pop-up appears.

### Specifics

Using the most recent version of Microsoft Edge.

### Steps to reproduce

1. Open Umbraco 
2. Go to Settings
3. Open the Content Page
4. Click Permissions
5. Click Add child in the Allowed child node types property

![image](https://user-images.githubusercontent.com/54888708/96301962-ddef9b00-0fef-11eb-9e2b-81d274f28822.png)

### Expected result

I expected the overlay to appear.

I've looked around for a couple of ideas why and it appears that the stylesheet for `.umb-overlay.umb-overlay-target` has `visibility: hidden`. I can't recall changing the value myself. 

### Actual result

The overlay was "displayed" however not visible due to the stylesheet marking it inivisble.

**Comment by nul800sebastiaan** [comment] 2020-10-19 12:42
Hey there @johnsharp1975 and thanks for the detailed report! I've had a look and unfortunately can't reproduce. That leads me to believe it is a problem during your upgrade. Often people forget to update the version in ClientDependency.config (just make it 1 higher or lower). If it's still not working then, maybe refer to this blog post, it's a bit old but still applies: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

I'll close this for now, but if you can still reproduce after checking all these things we might need to re-open it.

**Closed by nul800sebastiaan** 2020-10-19 12:42 UTC
