### ISSUE TITLE
Issue when searching for media with hyphens in their names

### ISSUE THREAD

**Issue by mmadukah** [umbraco/Umbraco-CMS#13890] opened 2023-02-27 10:08 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.5

### Bug summary

When searching for media with hyphens in their names, and including the hyphens in the query, via the Umbraco backoffice for example media-test-image no results are returned. This worked in Umbraco 7. 

### Steps to reproduce

When in the Umbraco back office click the main search icon.
Type the name of a media item that has hyphens in it's name eg image-with-hyphens - the query should contain the hyphens.

### Expected result / actual result

The media item should be shown in the results.

**Comment by nikolajlauridsen** [comment] 2023-02-27 12:20
Heya, I just tried this out and unfortunately I cannot reproduce, when I search in the backoffice the image shows up like expected, I tried testing with the latest 8.15

![image](https://user-images.githubusercontent.com/16456704/221557976-abc437a5-d087-4615-89bb-75be31894185.png)

**Comment by mmadukah** [comment] 2023-02-28 09:54
Your search query should contain the hypens.

**Comment by nikolajlauridsen** [comment] 2023-02-28 12:03
Ahh yes, that's my bad, it would help if I remember to actually read :P 

I took a look at it again and can indeed reproduce it now, it seems to have been broken in #7330

Normally 8.8 is outside the range of where we usually fix regressions, but since this is still an issue in v10 and the code is exactly the same I've opted to make a fix for both v10/11 and v8, might as well 😄 

This issue will be fixed by #13896 and #13897

Thanks for reporting, this seems to have been an issue for quite a while 😄

**Comment by mmadukah** [comment] 2023-03-02 10:59
Thanks very much for the fast turn around on this.

**Comment by Zeegaan** [comment] 2023-03-07 10:33
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13896
Thanks again for reporting 🐛 !

**Closed by Zeegaan** 2023-03-07 10:33 UTC
Labels: type/bug, area/backend, affected/v8, affected/v10, affected/v11
