### ISSUE TITLE
Can't add start node for MediaPicker through infinite editing

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4241] opened 2019-01-24 12:33 UTC

**Comment by RobertCopilau** [comment] 2019-01-24 12:34
Payload
![startNode.png.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46fb809b3196ada68becf153aa5ab2d86b56357c2301a03f32dfa17dbd472905585c4bf8175c5c41fcf9882aa3b36979de0a0effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98e44c3eb3e27e4898a4f3a0c48.jpg)

**Comment by kjac** [comment] 2019-01-24 19:10
Works on my machine (tm) 😆 

![media-picker-start-node](https://user-images.githubusercontent.com/7405322/51702410-082b4900-2014-11e9-8bb6-7f945b858a87.gif)

**Comment by RobertCopilau** [comment] 2019-01-28 09:10
Hey @KennethJakobsen, I just tried on the latest of temp8 and indeed it works!

However, I did found out that the start node is still empty in the configuration even if there is a start node set.

Can you confirm this?

**Comment by RobertCopilau** [comment] 2019-01-28 09:56
Sorry for the confusion @KennethJakobsen , I meant the `Editor Settings`.
Even tho there is a start node set and its working, it does not show  up in the `Editor Settings` of the `Media Picker`
![{9A1B4197-9885-4F60-9654-B5953229EC10}.png.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46f3cdbb72a0d7f8d6bef21afc05a5d97d607123645df57e24c8c17de61728535d563bdf4058125abca7de39baa47c32d5065ebe957f5566c36f44aeec851cba55ec24884a85b6bd8b49c5bd3471b18e9d532c5c5446dda0006ceacc09da52e44ae64754a1173e65e07f357547961b753e26.jpg)

**Comment by kjac** [comment] 2019-01-28 10:01
@RobertCopilau if you look at the GIF I posted earlier the editor settings do indeed show the start node.

It looks like you're doing some infinite editing there, maybe that's what's causing the issue - I haven't tested that. But... could it be that you're creating a new editor, not reusing the existing one?

**Comment by warrenbuckley** [comment] 2019-01-29 11:00
@RobertCopilau I can't reproduce this, can you just triple check please mate

**Comment by kjac** [comment] 2019-01-29 19:37
I can reproduce it... and I think I know where the bug is. I'll dig a bit.

**Comment by kjac** [comment] 2019-01-29 20:05
PR in #4315

**Comment by RobertCopilau** [comment] 2019-01-30 07:35
Awesome @KennethJakobsen, thanks a bunch :D

**Comment by nul800sebastiaan** [comment] 2019-01-30 15:47
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4315

**Closed by nul800sebastiaan** 2019-01-30 15:47 UTC
Labels: community/pr, type/bug
