### ISSUE TITLE
Save and publish button only updates on first click pr. content node.

### ISSUE THREAD

**Issue by umbracowulser** [umbraco/Umbraco-CMS#3168] opened 2018-10-05 07:32 UTC
As an editor I would like to be able to see that Umbraco is working when I click "Save and publish".

It works the first time a content node is loaded in the backoffice, but when I click the button a second time after making more changes, there is no indication of Umbraco working.

Video of the issue: https://youtu.be/KsTdrGvDOVU

Reproduction
------------

Start editing content in a content node in the Backoffice. Save and publish. Edit content in the same node afterwards, and click "Save and Publish". Now there is no indication that Umbraco is working.

### Bug summary

There is no indication of saving and publishing going on after the first "Save and publish" action is performed on a content node.

Leaving the node, and coming back to it, seems to "reset" this and then the first "Save and publish" action, acts out as expected.

### Specifics

This happens on Umbraco Cloud at least since 7.10.

Checked in Chrome Version 69.0.3497.100 (Officiel version) (64-bit)

Umbraco Cloud Umbraco 7.10.5

### Steps to reproduce

Start editing content in a content node in the Backoffice.
Save and publish.
Edit content in the same node afterwards, and click "Save and Publish".
Now there is no indication that Umbraco is working.

### Expected result

A spinner on the button as when you click "Save and Publish" the first time.

### Actual result

There is no indication of Umbraco working on saving an publishing my changes.

**Comment by abjerner** [comment] 2018-10-05 07:41
If anyone is looking into this issue, the code for the Angular controller is here:

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js#L130

I think the problem is that `$scope.page.buttonGroupState` is set to `success` in order to show the checkmark, but then the spinner isn't shown the second time, because the code expects it to be `init`.

**Comment by nul800sebastiaan** [comment] 2018-10-05 07:50
Unfortunately I can't reproduce the issue in 7.12 so this might have been fixed in a later version already. If there's any steps to reproduce in a clean version of Umbraco I'm all ears but until then I'll close this.

**Closed by nul800sebastiaan** 2018-10-05 07:50 UTC
