### ISSUE TITLE
Blocklist editor validation error

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#11190] opened 2021-09-24 13:05 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Tested on 8.12.2 & 9.0.0-rc003

### Bug summary

If you add a block editor within a block editor and set the minimum elements to 1 you get a save validation error when not filling in an element.

### Specifics

The following error is shown when saving a document with nested blocklists not meeting validation requirements:

![image](https://user-images.githubusercontent.com/24605285/134678099-80592c41-e15a-4aad-9cfb-ac062e262bb8.png)

Stacktrace: 
```
at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyEditor.MinMaxValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Cms.Core.Services.Implement.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Cms.Core.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Core.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass17_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Cms.Core.Services.Implement.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator`3.ValidatePropertyValue(TModelSave model, TModelWithProperties modelWithProperties, IDataEditor editor, ContentPropertyDto property, Object postedValue, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator`3.ValidatePropertiesData(TModelSave model, TModelWithProperties modelWithProperties, ContentPropertyCollectionDto dto, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutingAsync(ActionExecutingContext context)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

- Create a document type
- Add an element with a block list
- Set the blocklists minimum elements to 1
- Add a blocklist to the document type you created
- Set a reference to the element you just created on the blocklist on the document type
- Create the document type in the content explorer
- Add an element to the block list but do not add an element to the block list with the minimum requirement
- Save the document
- The error is now shown

### Expected result / actual result

Expected a validation error where this message is shown:

![image](https://user-images.githubusercontent.com/24605285/134678901-164d3b44-d88a-4ad8-b7c7-b8ba6256409c.png)

Actual result:
A NullRefrenceException

**Comment by lauraneto** [comment] 2021-09-26 10:11
I think this is a duplicate of #10095, which has an open PR for v9 (#11184)

**Comment by nikcio** [comment] 2021-09-27 11:26
@lauraneto Yes, it seems to be the same issue. Do you know if a fix will come to the Umbraco v8 version as well? It seems like a pretty simple fix so maybe a PR for v8 should be opened too?

**Comment by nul800sebastiaan** [comment] 2021-10-04 12:50
Yes, we should definitely backport the fix to v8 as well 👍

**Comment by nul800sebastiaan** [comment] 2021-11-17 09:49
We have merged this for both v8 and v9, unfortunately we don't have a  release date for 8.18 yet, but it will be fixed in that version.

And nice meeting you in real life last week @nikcio! 👋

**Closed by nul800sebastiaan** 2021-11-17 09:49 UTC
Labels: community/pr, type/bug
