### ISSUE TITLE
8.5.3 saves node with invalid property value

### ISSUE THREAD

**Issue by lcichanowicz** [umbraco/Umbraco-CMS#7805] opened 2020-03-13 15:28 UTC
I just created a "clean" 8.5.3 site, in VS2019 via NuGet, with the starter kit, to confirm a bug.  I added a custom validator to an existing field, for rudimentary prevention of saving HTML in a Textstring.
`^[^<>]*$`

When I test it, adding an HTML tag to the field, and click 'Save and publish', I get the client-side error: Value is invalid, it does not match the correct pattern--_however_, if I leave the node in the backoffice and return to it, the HTML tag has been saved into the field.

Umbraco saves the invalid, but does not publish it, even though when I left the node, with the "Value is invalid..." message showing, I chose to discard changes.

**Comment by nul800sebastiaan** [comment] 2020-03-16 12:05
Thanks @lcichanowicz - I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/7484

**Closed by nul800sebastiaan** 2020-03-16 12:05 UTC
