### ISSUE TITLE
[V14] UI does not remember tree position when swapping sections

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco-CMS#16513] opened 2024-05-30 13:17 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When jumping from one section to another, trees always start unfolded. Would be really nice, if it could “remember” how a section was left like in the old backoffice.

### Steps to reproduce

- Unfold a nested tree in a section
- Go to another section
- Come back

### Expected result / actual result

Tree is still unfolded after returning to a/the previous section.

**Comment by philipdanielhayton** [comment] 2024-06-20 08:38
+1

**Comment by madsrasmussen** [comment] 2024-11-21 09:26
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/17076

**Closed by madsrasmussen** 2024-11-21 09:26 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v14
