### ISSUE TITLE
XPath for 404 pages sometimes doesn't work in v13

### ISSUE THREAD

**Issue by C0derPr0** [umbraco/Umbraco-CMS#15582] opened 2024-01-13 12:04 UTC
## What type of issue is it?
Wrong documentation

## What article/section is this about?
https://github.com/umbraco/UmbracoDocs/blob/main/13/umbraco-cms/tutorials/custom-error-page.md

## Describe the issue
The documentation provided for Error404Collection no longer works. 

Bad example:

`{
    "Umbraco": {
        "CMS": {
            "Content": {
                "Error404Collection": [
                    {
                        "Culture": "default",
                        "ContentXPath": "//errorPages[@nodeName='My cool error']"
                    }
                ]
            }
        }
    }
}`

It returns the error System.InvalidOperationException: XPathValue must be an XPathNavigator or a string. As I understand it, XPath support was removed from v13.

**Comment by andr317c** [comment] 2024-01-21 21:51
Hey! 
I tried following the documentation for using Xpath to create an Error404 page and it works without any issues on version 13.0.3
 for me 🤔.

Here is a short GIF of what I have created for it to work:
![Xpath](https://github.com/umbraco/Umbraco-CMS/assets/73799582/12937b4e-81af-421a-9199-b2b3ac04c05d)

**Comment by ninjaonsafari** [comment] 2024-02-07 14:13
I have the same issue in Umbraco 13.1.0.
![image](https://github.com/umbraco/Umbraco-CMS/assets/2211563/45cae2ef-dc97-409d-b04f-3eedf37e5f5a)
![image](https://github.com/umbraco/Umbraco-CMS/assets/2211563/b8b8de06-0d6c-48e1-a871-070cf82b6729)

**Comment by james-whittington1** [comment] 2024-02-12 21:35
This is really frustrating. I have attached source link, made a custom 404 finder that mimics the built in finder, and found that it is throwing an error when the xpath navigator attempts to "look" at a rich text value. It is expecting a navigator or string, but receives an intermediate property value converter value instead. I have no idea how to work around this.

![image](https://github.com/umbraco/Umbraco-CMS/assets/37091895/ce4adc1f-bbc4-4448-9f4f-29f11a3463b6)

**Comment by james-whittington1** [comment] 2024-02-12 21:52
@andr317c what happens if you add a rich text datatype to the page in your test?

**Comment by palmem29** [comment] 2024-02-21 15:54
Following an Umbraco update from 12.3.6 to 13.0.3 I'm having the same issue. I was hopeful this was resolved in 13.1.1 but following the update I still have no luck. I did confirm that a fresh 13.1.1 install works just fine but I'm not in a position where I can start with a fresh 13.1.1 install and rebuild my project. Any traction with this issue?

**Comment by cvocvo** [comment] 2024-02-22 16:32
For us, this post here helped:
https://our.umbraco.com/forum/using-umbraco-and-getting-started/113342-xpathvalue-must-be-an-xpathnavigator-or-a-string#comment-349382
> For me it was the // in the XPATH, if I made it / path it worked

Thus this working setup for our multisite (literally changed from `//` to `/` and it fixed it. Oddly, our 404 pages were working on every site except one, but this slash change resolved the one that wasn't working and left the others functional as well.
```
        "Error404Collection": [
          {
            "Culture": "default",
            "ContentXPath": "$site/notFound[@nodeName='404']"
          }
        ]
```

**Comment by palmem29** [comment] 2024-03-27 22:55
@andr317c, if "The current implementation of XPath is suboptimal and will be removed entirely in a future version. It is currently obsolete and scheduled for removal in v14." will there be any way to target a 404 page outside of ID and GUID ID?

Currently, it's very nice to know that we put our 404 page at /Page-Not-Found. So we don't have to update it from project to project or instance to instance. I understand how to use the ID and GUID ID. Will those be our only options in Umbraco14?

**Comment by TomChancer** [comment] 2024-04-04 10:08
Wanted to add on to this issue:

Also experiencing this on a Cloud based Baseline project that was upgraded from 12.3.7 to 13.2.2.

Original string was as follows: //error404[@nodeName='Error404']

Which returns the error in logs of: 
`System.InvalidOperationException: XPathValue must be an XPathNavigator or a string.`

Attempting the change mentioned by @cvocvo 

Results in a new error due to the $site inclusion:
`System.Xml.XPath.XPathException: Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function.`

Would like to know what the status is on this, as we have around 19 cloud baseline children with now broken 404's.

**Comment by Zeegaan** [comment] 2024-04-11 13:19
Hello there 👋 
Mine seems to work just fine aswell 😕 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/7a616ca7-ec0a-42cc-b4f9-a62e89088b63)
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/33fd3d9e-ee1c-4cfb-a879-3e986d008016)

**Comment by C0derPr0** [comment] 2024-04-11 13:36
> Hello there 👋 Mine seems to work just fine aswell 😕 ![image](https://private-user-images.githubusercontent.com/70372949/321643654-7a616ca7-ec0a-42cc-b4f9-a62e89088b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDI2NTksIm5iZiI6MTcxMjg0MjM1OSwicGF0aCI6Ii83MDM3Mjk0OS8zMjE2NDM2NTQtN2E2MTZjYTctZWMwYS00MmNjLWI0ZjktYTYyZTg5MDg4YjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEzMzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMTc3OTI3MGUwMzlhY2UzZjYxNWVjZWEzZGQ1YWU0NjU3ZTU4M2UwNWRhMzQ0OTJjMTM0NDgyNTQ5NTQwZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bhVrSpjlHFSdXovmTpToa2jlpofNutc4hU5tKuuOG3Y) ![image](https://private-user-images.githubusercontent.com/70372949/321643905-33fd3d9e-ee1c-4cfb-a879-3e986d008016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDI2NTksIm5iZiI6MTcxMjg0MjM1OSwicGF0aCI6Ii83MDM3Mjk0OS8zMjE2NDM5MDUtMzNmZDNkOWUtZWUxYy00Y2ZiLWE4NzktM2U5ODZkMDA4MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEzMzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZmVjYjMyMDUxYTA4MDUyODIwZGM2YmYwMjIwMmQ3YWJkMjJlNDIxZjk0ZTdiZTc3ZDFiZDI0ZWQ5MWNiOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iGWkFIe0SQlgkVfMbdzpcJ8UxoX3mFhHvQVS0sHcfVE)

Yes, it seems like the problems only occur when people upgrade from prior versions of Umbraco, but the folks at Umbraco ignore the error because this feature is going to be dropped in future versions. I've tested this myself on several sites, and it works fine in new builds, but it explodes every time I upgrade to v13 from any other version.

**Comment by andr317c** [comment] 2024-04-17 08:31
Hey again,

Sorry for not getting back to you sooner, we've been quite busy with V14. I have tried to reproduce the issue once more. I set everything up in Version 12.1.0, and the error page worked as it should. Afterwards, I upgraded my project to Version 13.2.2. And the error page still works 😕.  I also tried using an RTE on the Error Page, but I still had no issues. 

This is what I have in my appsettings:
```
"Error404Collection": [
          {
            "Culture": "default",
            "ContentXPath": "//errorPages[@nodeName='My cool error']"
          }
        ],
``` 
 I'm not really sure how to reproduce this issue, Could you possibly provide the exact steps you followed, starting from a clean install up to encountering the problem? Any additional insights would be greatly appreciated!

**Comment by nul800sebastiaan** [comment] 2024-04-17 10:35
FYI: I tried as well with an upgrade from 12.3.6 and it's still working for me too. Could it be that your XPath expression is not right somehow? I tried the error page being on level 2 (under "Home" as well as on level 3 under "Home" > "About us") to make sure we didn't break the `//` part of the XPath selector.

Of course if we broke it, it needs to be fixed but as noted a couple times above, we need a way to reproduce the problem. I can't see anything obvious in the changes between 12 and 13 either that could've broken this, so for now there's nowhere to start without a reproduction of the problem.

**Comment by OwainJ** [comment] 2024-04-17 11:06
I ran into this on my new v13.2.2 site, where my 404 error page is located as a child of my Homepage.
`//errorPage[@nodeName='Page not found']` - doesn't work
`$site/errorPage[@nodeName='Page not found']` - does work

This is the error that shows in my logs if I use the `//`

```
Could not parse xpath expression: "//errorPage[@nodeName='Page not found']"
--
System.InvalidOperationException: XPathValue must be an XPathNavigator or a string.    
at Umbraco.Cms.Core.Xml.XPath.NavigableNavigator.MoveToFirstChildProperty()    
at Umbraco.Cms.Core.Xml.XPath.NavigableNavigator.MoveToFirstChild()    
at MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext()   
at MS.Internal.Xml.XPath.DescendantQuery.Advance()    
at MS.Internal.Xml.XPath.FilterQuery.Advance()   
at MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext()    
at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetSingleByXPath(XPathNodeIterator iterator)    
at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetSingleByXPath(Boolean preview, String xpath, XPathVariable[] vars)    
at Umbraco.Cms.Core.PublishedCache.PublishedCacheBase.GetSingleByXPath(String xpath, XPathVariable[] vars)    
at Umbraco.Cms.Infrastructure.PublishedContentQuery.ItemByXPath(String xpath, XPathVariable[] vars, IPublishedCache cache)    at Umbraco.Cms.Infrastructure.PublishedContentQuery.ContentSingleAtXPath(String xpath, XPathVariable[] vars)    
at Umbraco.Cms.Core.Routing.NotFoundHandlerHelper.GetContentIdFromErrorPageConfig(ContentErrorPage errorPage, IEntityService entityService, IPublishedContentQuery publishedContentQuery, Nullable`1 domainContentId)
```

I have 2 languages on my site, I just tried a mixed setup, where one culture was set to use `$site/` and the other was set to use `//`, the 404 with the `//` failed, and the one with `$site/` worked fine.

**Comment by nul800sebastiaan** [comment] 2024-04-17 12:01
That might be it! I'll try multilingual!

**Comment by nul800sebastiaan** [comment] 2024-04-17 12:46
Note: when running each site you might want to do a `dotnet clean` in between, modelsbuilder gets confused since it's a site on the same port but with a different version.

**Comment by nul800sebastiaan** [comment] 2024-04-17 12:50
And one more note to be extra clear, the config looks like: 

```json
        "Error404Collection": [ 
          { "Culture": "en-US", "ContentXPath": "//errorPages[@nodeName='My cool error']" },
          { "Culture": "nl-NL", "ContentXPath": "//errorPages[@nodeName='Mijn coole error']" } 
        ]
```

Where `'My cool error'` and `'Mijn coole error'` are the exact names of the pages in the CMS.

**Comment by OwainJ** [comment] 2024-04-17 14:01
@nul800sebastiaan I downloaded your .zip and ran the v13.2.2 project, and 404 worked perfectly as expected.

So I decided to create my own vanilla Umbraco project to see if I could re-create the issue I'm seeing in my client's project, these are the steps I followed:
1. Created a new project using this package script writer setup: https://psw.codeshare.co.uk/?InstallUmbracoTemplate=true&UmbracoTemplateVersion=11.4.1&Packages=uSync%7C13.2.0&UserEmail=admin%40example.com&ProjectName=404TestOjo&CreateSolutionFile=true&SolutionName=404TestOjo&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=true&StarterKitPackage=clean&OnelinerOutput=false&TemplateName=Umbraco.Templates&TemplateVersion=13.2.2&RemoveComments=false
2. I then renamed the premade error page to "Page Not Found" 
3. Added a 404 collection
```
"Error404Collection": [
     {
          "Culture": "default",
          "ContentXPath": "//error[@nodeName='Page not found']"
     }
]
```
4. Navigated to a page that doesn't exists `https://localhost:44356/sfefse`
5. And it showed me the default Umbraco 404.
6. Checked the logs, and I can see the same `Could not parse xpath expression: "//error[@nodeName='Page not found']"` error that I am seeing on my client v13 project.

GIF of my Vanilla project (only package is uSync):
![Weird 404 issue](https://github.com/umbraco/Umbraco-CMS/assets/17008780/1fa7c0f0-d31b-4f01-a0a9-e09bdc7c5f8c)

And here's .zip of that project (media files removed due to github upload limit):
[404TestOjo.zip](https://github.com/umbraco/Umbraco-CMS/files/15012038/404TestOjo.zip)

**Comment by BrionyMcKenz** [comment] 2024-04-18 10:12
I've been using `"Error404Collection": [
  {
    "Culture": "default",
    "ContentXPath": "//notFound404[@nodeName='Page not found']"
  }
]` locally and it's worked fine starting on v13, I've upgraded each minor version and it's still working fine. However, I just did a deployment to Umbraco Cloud and it's not working in the Cloud environment. Weirdly it is broken for my colleague when he runs locally so is there maybe a cache issue or something that making it look like it's working for me in my local environment? 

The documentation states to use XPath for Cloud because the node ids can change, is there an alternative?

**Comment by nul800sebastiaan** [comment] 2024-04-22 09:30
@OwainJ Yes, now we're talking! Thanks very much! With a reproduction in place it wasn't too difficult to find the code that cause the problem. I've left a more extensive description of the problem (plus a fix) in PR https://github.com/umbraco/Umbraco-CMS/pull/16121 

Thanks again, that was really helpful!

**Comment by nul800sebastiaan** [comment] 2024-04-24 08:35
@anas1987 Hmm, somehow that (`$current/ancestor-or-self::home/descendant-or-self::page404`) doesn't work for me in 12.2.0 either. 

Breaking it down:

- From the `$current` page (any page we're on in the website)
- Go up to the level where a document type alias with `home` is found - we are now at the home page
   - or take the current page if that is `home` - we are now at the home page
- When on the `home` page go down to all the descendants in the tree until you found a page with document type alias `page404`
   - or take the current page - note: this is `-or-self` unnecessary, we already know we are on `home` from the previous part)

Your query can be greatly simplified by saying: `//page404` - it does the same thing, go all the way up the tree, then find the first descendant page with document type alias `page404`. This works in a multi lingual setup as well.

If that doesn't work for you, as before, we'd need a way to reproduce.

**Comment by anas1987** [comment] 2024-04-24 09:02
> @anas1987 Hmm, somehow that (`$current/ancestor-or-self::home/descendant-or-self::page404`) doesn't work for me in 12.2.0 either.
> 
> Breaking it down:
> 
> * From the `$current` page (any page we're on in the website)
> * Go up to the level where a document type alias with `home` is found - we are now at the home page
>   
>   * or take the current page if that is `home` - we are now at the home page
> * When on the `home` page go down to all the descendants in the tree until you found a page with document type alias `page404`
>   
>   * or take the current page - note: this is `-or-self` unnecessary, we already know we are on `home` from the previous part)
> 
> Your query can be greatly simplified by saying: `//page404` - it does the same thing, go all the way up the tree, then find the first descendant page with document type alias `page404`. This works in a multi lingual setup as well.
> 
> If that doesn't work for you, as before, we'd need a way to reproduce.

Thank for answer Sebastiaan, The different between `$current/ancestor-or-self::home/descendant-or-self::page404` and `//page404` that the long one ensure to come to the error page in the same culture, while the short one navigate to the first culture has page satisfy alias page404.
Since I have different culture with different language so it is necessary to meet the right not found page with right language which is created under home page in each culture

**Comment by anas1987** [comment] 2024-04-24 09:14
The good news is: 
`"Error404Collection": [
          {
            "Culture": "default",
            "ContentXPath": "$site/page404"
          }
        ],`
        works in both 13.2.2 and 12.2.0 and it meets not found page in current culture

**Comment by nul800sebastiaan** [comment] 2024-04-24 09:16
@anas1987 That was going to be my next suggestion! 😉 Much, much easier to read as well if someone ever takes over that site! 👍

**Comment by hfloyd** [comment] 2024-05-03 15:10
For anyone who wants to be able to support multiple-site-specific 404 Content nodes (as @anas1987 describes) and can't wait for @nul800sebastiaan's fix to be merged/released, or also wants to future-proof beyond XPath... I used the documentation example provided by @alina-tincas and created a version which supports the multi-site setup. Take a look here: [Umbraco v13+ 404 Error IContentLastChanceFinder - Supporting multiple sites at root
](https://gist.github.com/hfloyd/f25cc07318003e59a6045f2d4f8febcc)

**Comment by Zeegaan** [comment] 2024-05-06 07:41
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16121 🚀

**Closed by Zeegaan** 2024-05-06 07:41 UTC
Labels: type/bug, release/13.4.0
