### ISSUE TITLE
User cannot login when assigned many groups

### ISSUE THREAD

**Issue by ondrejpialek** [umbraco/Umbraco-CMS#9347] opened 2020-11-04 18:49 UTC
The user cannot log in when they have been assigned too many user groups. The problem lies in the `UMB_UCONTEXT` cookie becoming too long. While this is supported by .NET and partially by Umbraco (the cookie gets split into chunks), there are parts of the Umbraco codebase that do not expect this.

## Umbraco version

Confirmed on `v7.15.1` and on `v7/dev`. I have not checked `v8`.

Reproduction
------------

1. Create 20 user groups with GUIDs as names (observe their alias is also more or less the same GUID)
1. Create a user and assign them to 10 groups
1. Log in as the user and observe you can log in
1. Add the remaining 10 groups to the user
1. Observe the user cannot log in

Diagnostics
----------

1. When you log in the browser makes a POST to `...../PostLogin`
1. Notice in the response headers that the `UMB_UCONTEXT` cookie has value `chunks:2` and that two new cookies were sent as well: `UMB_UCONTEXTC1` and `UMB_UCONTEXTC2`
1. A subsequent call to get server variables is made 
1. This call returns a 401

**Comment by nul800sebastiaan** [comment] 2020-11-05 09:52
Thanks @ondrejpialek - this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/7727, make sure to follow that issue for progress.

**Closed by nul800sebastiaan** 2020-11-05 09:52 UTC
