### ISSUE TITLE
Add link to create an item under Content menu to 'Settings section'

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/Umbraco-CMS#3947] opened 2019-01-03 14:47 UTC
I was wondering if it would be helpful to create a link to the settings section within the 'noDocumentTypes' text - "There are no allowed document types available. You must enable these in the _settings section_ under "document types"."

### Currently

The text shows when you haven't setup a document type - usually on a fresh install. If the settings section was a link, a user could just click on the text to be taken to the settings section, instead of having to then navigate to the settings area. 

![image](https://user-images.githubusercontent.com/9438758/50643520-4fb73b80-0f66-11e9-9fba-3e8f566a2d71.png)

The link would direct the user to "/umbraco/#/settings/"

**Comment by nul800sebastiaan** [comment] 2019-01-03 14:57
@OwainWilliams Yes, that would be cool, andddd.... the message "You must enable.. " should only been shown if you have access to the settings section. This is not actually useful to show to people who can't do anything about it! :-)

**Comment by OwainWilliams** [comment] 2019-01-03 15:19
Cool - I'll have a look in to this. I might need some help with the translation files though to know where to put the link!

**Comment by nul800sebastiaan** [comment] 2019-01-03 16:13
@OwainWilliams Have a look at this translation and note the `%0%` variable: https://github.com/umbraco/Umbraco-CMS/pull/3844/files#diff-afe2906899bcedd656e05bb0e6fb20c4R836 

And it's usage here, passing in a value into the variable: https://github.com/umbraco/Umbraco-CMS/pull/3844/files#diff-7736c43054a1c5916c86566898ba3386R24

Not sure if you'd need a variable, but maybe there's a good way to dynamically get the link to the settings section, check how it's done in the info tab for editing the current doctype:

![image](https://user-images.githubusercontent.com/304656/50647982-4f28a000-0f7a-11e9-9cb2-b45a3a611d28.png)

Also, this translation includes some HTML so it's in a CDATA block. The link should probably not be hardcoded in the translation file, but I'm not sure. Probably needs to be something like `<a href="THELINK">{translatedLinkText}</a>` and the link text coming from something like `<<key alias="settingsSection">`. Play with it! 

You can do it in v7, we merge everything up to v8.

**Comment by OwainWilliams** [comment] 2019-06-02 10:20
Just wondering if this is still helpful or has it been fixed but someone else. Happy to look at it again and get it done.

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:38
Go for it @OwainWilliams ! :-) 👍

**Comment by nul800sebastiaan** [comment] 2019-06-23 11:03
@OwainWilliams whoops, looks like there's already a PR available, I missed that one!

https://github.com/umbraco/Umbraco-CMS/pull/5562

I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/5561 (even though the other one was the dupe). 

Sorry to get you all excited 🙈

**Closed by nul800sebastiaan** 2019-06-23 11:04 UTC
Labels: community/up-for-grabs, help wanted, type/feature

**Comment by OwainWilliams** [comment] 2019-06-23 19:30
Doh! No worries - I'll just need to find a new PR to give a go 👍
