### ISSUE TITLE
MembersIndex rebuild hangs in v8.9.1

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#9409] opened 2020-11-18 05:34 UTC
When I restore the database from the client based Staging server and rebuild my local indexes, all indexes besides Members rebuild without any issue. MembersIndex just hangs and never finishes. I don't have any members defined in this project.

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1 (NuGet)

Reproduction
------------

### Steps to reproduce

1. Go to Settings
2. Go to Examine Management
3. Go to MembersIndex
4. Click Rebuild index

### Expected result

MembersIndex should be rebuilt like Internal and External.

### Actual result

The process hangs as per the attachment.

![2020-11-18_09-28-20](https://user-images.githubusercontent.com/14230396/99487826-965a8700-2980-11eb-924e-ac9785451cb7.png)

**Comment by nul800sebastiaan** [comment] 2020-11-20 08:44
Thanks @Baracuda011 - that's strange, I also don't have any members in my project and it rebuilds the index just fine,

When you open up the F12 tools in your browser you should either see an error in the console or an error comin back from the rebuild requests in the network tab. Have a look there and see if that helps you identify the issue. 

I'll close this for now as I can't reproduce this but happy to reopen if you have more info to reproduce the problem.

**Closed by nul800sebastiaan** 2020-11-20 08:44 UTC

**Comment by Baracuda011** [comment] 2020-11-25 05:50
Hi @nul800sebastiaan,

Apologies for the late reply.

This time it rebuilt, but it took quite a long time, almost 30 seconds. Here is the browser console screenshot:

![2020-11-25_09-48-00](https://user-images.githubusercontent.com/14230396/100188451-a7b50d80-2f03-11eb-9cf2-3ec73a19a611.png)
