### ISSUE TITLE
Block grid

### ISSUE THREAD

**Issue by DianaSandu05** [umbraco/Umbraco-CMS#15845] opened 2024-03-05 20:55 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

I created a element with a text area, added this in the block grid and it got stack on loading...

### Steps to reproduce

I used mostly umbraco 8 and I was trying to familiarize with block grid. I created an element type following the documentation from umbraco and I added a text area.

![image](https://github.com/umbraco/Umbraco-CMS/assets/60673601/7b371bb2-f630-43a1-ac38-978c22546b25)

I then added this below

![image](https://github.com/umbraco/Umbraco-CMS/assets/60673601/29be0e72-363d-4505-950a-299bb901f855)

Then I see the umb-loading and nothing happens. There is an error in the console.

![Screenshot 2024-03-05 204515](https://github.com/umbraco/Umbraco-CMS/assets/60673601/837b78d4-54c5-4b47-90fd-a24c4de0b8b8)

But then I tried to delete the block added and I am getting the same behaviour.

**Comment by andr317c** [comment] 2024-03-15 13:34
Hey!
Thanks for reporting this issue. I was unable to reproduce the issue, I tried on versions 13.1.1 and 13.2.0☹️. Can you reproduce this from a clean install of Umbraco? And if you can, please provide the exact reproduction steps so that I can reproduce it as well 😄

**Comment by nielslyngsoe** [comment] 2024-11-27 20:47
Hi @DianaSandu05 would you be able to let us know if you are able to reproduce this problem with latest version of v.13?

If not I will consider this as fixed, and therefor close this issue. If its turns out that you can reproduce this then we will re-open and investigate. Thanks in advance

**Closed by nielslyngsoe** 2024-11-27 20:47 UTC
Labels: state/needs-more-info, type/bug
