### ISSUE TITLE
v8: Richtext editor loading slow because of stylesheets that don't exist anymore

### ISSUE THREAD

**Issue by koenvanras** [umbraco/Umbraco-CMS#5720] opened 2019-06-25 11:26 UTC
The richtext editor property loads very slowly on nodes because it can't find a stylesheet.

Reproduction
------------

### Bug summary

When you add a stylesheet to the richtext editor data type and remove the physical file, the stylesheet will still remain in the stylesheet array in the database.

There should be some sort of null check or maybe even a way to remove the stylesheet from the database array when you save the datatype again and the physical stylesheet doesn't exist anymore.

### Steps to reproduce

- Debug should be true
- Add a stylesheet to a richtext editor data type.
- Save the data type.
- Add the richtext data type to a doctype.
- Create a node from the doctype with the richtext editor.
- Remove the physical stylesheet from your project.
- Reload the node.

### Expected result

The richtext editor should load fast.

### Actual result

The node loads very slowly, some times up to 30 seconds. This even slows loading Nested Content down aswell since its still busy with the GET request for the stylesheets.
This issue is caused because it can't find the physical stylesheet that is still in the database.

**Comment by nul800sebastiaan** [comment] 2019-06-26 10:59
Hi @koenvanras, I don't really know how to reproduce this problem. I just get an immediate 404 error within milliseconds and the RTE loads quickly. 

![image](https://user-images.githubusercontent.com/304656/60174726-f42d8280-9811-11e9-8ddc-9af09eac2ed0.png)


Maybe you're working on an older version of Umbraco? Not sure.

I'll close this for now, as I can't reproduce with the steps above, if you have more info then please add to this issue.

Sidenote: it would be a nice health check to build: for each rich text editor datatype, does the connected stylesheet file actually exist on disk. Could run that periodically (and even report on slack automatically: https://our.umbraco.com/packages/backoffice-extensions/slack-health-check-notification/).

**Closed by nul800sebastiaan** 2019-06-26 10:59 UTC
