### ISSUE TITLE
Can't save empty grid layout

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#4154] opened 2019-01-19 20:01 UTC
A brief description of the issue 
------------
V7.13.1
When saving a page with an empty grid layout, the page is saved as if a layout has been selected.

Reproduction
------------

1. Create a grid DataType with a single layout and single row configuration, both single cell, full width.
2. Add to a DocType.
3. Create a page on that DocType.

### Expected result
When the page is opened for editing, the "Add a Row" dialogue should be shown.

### Actual result
When the page is opened for editing, the "Add Content" dialogue is shown. 
Saving the page in this state means Model.HasValue("myGrid") always returns "true".
While it is possible in the interface to delete the "Add Content" dialogue in the usual way by clicking on it's "Bin" and then "Tick" icons, when the page is saved, it reverts back to the "Add Content" dialogue.

**Comment by nul800sebastiaan** [comment] 2019-01-21 07:19
I can reproduce, I can see the unused grid:

![image](https://user-images.githubusercontent.com/304656/51458230-c7ea7300-1d54-11e9-90d1-2fe20bbe2f42.png)

And what's saved is some json:

![image](https://user-images.githubusercontent.com/304656/51458246-d33d9e80-1d54-11e9-95be-f9950ef90f48.png)

Note that this has probably worked this way all along, I can also reproduce in v7.7 for example.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment] 2019-01-21 21:53
Looks very much like it's by design. The rule seems to be: *If there is no current property value and only one row layout, add a row as default value".

That being said it's not particularly smart to add that default value. I've got the problem pinpointed in the code, will submit a PR soon as I can.

**Comment by kjac** [comment] 2019-01-22 06:40
PR in #4177

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:40
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:40 UTC
Labels: community/up-for-grabs, help wanted, type/bug
