### ISSUE TITLE
SQL Timeout happens randomly when saving document type

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco-CMS#12150] opened 2022-03-18 08:15 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Sometimes, when you save a document type, the SQL will timeout.

### Specifics

This happens locally. 
This has been happening, and is happening, on all of our v9 sites. 
All the sites are using local SQL Express databases.
When it happens, you have to restart the site. After that, the doctype might save instantly, or it will timeout again.

```
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

 ---> System.ComponentModel.Win32Exception (258): Ventehandlingen blev midlertidigt afbrudt.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at System.Data.SqlClient.SqlDataReader.get_MetaData()

   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)

   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)

   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)

   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 236

   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)

   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

   at NPoco.Database.ExecuteDataReader(DbCommand cmd)

   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentVersionRepository.GetCleanupPolicies()

   at Umbraco.Cms.Infrastructure.Services.Implement.DefaultContentVersionCleanupPolicy.Apply(DateTime asAtDate, IEnumerable`1 items)+MoveNext()

   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.CleanupDocumentVersions(DateTime asAtDate)

   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.PerformContentVersionCleanup(DateTime asAtDate)

   at Umbraco.Cms.Infrastructure.HostedServices.ContentVersionCleanup.PerformExecuteAsync(Object state)

   at Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase.ExecuteAsync(Object state)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

### Steps to reproduce

Save a document type, it might happen. 

### Expected result / actual result

The document type is saved quickly with no SQL timeout.

**Comment by p-m-j** [comment] 2022-03-21 08:50
This looks like it could be fixed by https://github.com/umbraco/Umbraco-CMS/pull/12153

**Comment by Zeegaan** [comment] 2022-03-22 12:06
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12153
I can't reproduce this locally anymore with the new PR applied, so i'm closing this for now, thanks for the report! 🐛 
If you still can reproduce this, i'll hapilly reopen the issue

**Closed by Zeegaan** 2022-03-22 12:06 UTC
Labels: type/bug
