### ISSUE TITLE
Multinode picker does not respect xpath of $root.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco-CMS#14887] opened 2023-10-02 10:38 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

When you make a multinode picker with the following configuration:
![image](https://github.com/umbraco/Umbraco-CMS/assets/32164310/53f3cb78-d300-4e46-8857-37ba702025fe)

And you try to pick an item, it will still travel down the tree to the specific content node.

This is an annoyance when your content tree consists of list views.
Even with the above configuration the final results looks like this, when you want to pick a node:
![image](https://github.com/umbraco/Umbraco-CMS/assets/32164310/456f45a7-0f87-43dc-89d7-52274a0d5fce)

### Steps to reproduce

Make the following content nodes:

Home page
2nd Home page
- Sub page (Has list view)
- - Content node (with multinode picker)
- - Content node
- - Content node
- - Content node

Update the MNP to the following configuration:
![image](https://github.com/umbraco/Umbraco-CMS/assets/32164310/7baa8c6a-fa6c-4dca-9929-e4859d7d86ae)

Pick the Home Page.

### Expected result / actual result

Should just let the content editor be in the root of the content tree, instead of being funnel all the way down to the Content Node

**Comment by Migaroez** [comment] 2023-10-05 14:09
Hey @Frost

This doesn't seem to be a bug as the intended behavior of the xpath node type is to limit which nodes are pickable. Combine this with its intended behavior to focus the current node to show where you are in the context (if possible within the available node list), then you get the described result.

Feel free to open a discussion if you feel like this behavior should change/be approved upon, especially with the new Backoffice coming in v14.

With the above explanation in mind, I will be closing this issue. Have a wonderful day.

**Closed by Migaroez** 2023-10-05 14:09 UTC
Labels: type/bug

**Comment by Frost** [comment] 2023-10-05 14:10
@Migaroez I think you sent a ping to the wrong user, but I'm sure @Frost117 would like to see your comment.

**Comment by Migaroez** [comment] 2023-10-06 09:18
> @Migaroez I think you sent a ping to the wrong user, but I'm sure @Frost117 would like to see your comment.

Sorry about that, thx for letting me now #H5YR
