### ISSUE TITLE
Razor Runtime Compilation not working on Linux

### ISSUE THREAD

**Issue by louisjrdev** [umbraco/Umbraco-CMS#9789] opened 2021-02-09 18:25 UTC
When I change a Razor file for one of my templates, when I refresh the page on the website, it has not picked up the changes. I have to recompile and run again to get the changes to appear, this is a bit annoying when working on a site, so would be great to see this fixed.

I did various googling around and it seems that the responsibility for this is in `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package by calling `.AddRazorRuntimeCompilation()`. 
I can see that Umbraco does have a reference to this in `UmbracoBuilderExtensions` under the `AddMvcAndRazor` method. 
Although it is not working for me at all on Linux, but I believe it was working earlier when running off of a windows pc.

**Comment by bergmania** [comment] 2021-02-10 13:03
Hi @louisjrdev ...

Thanks for reporting..  I will need some more info to reproduce, as it works for be if I just have a simple setup on Ubuntu.

My example is just an empty document type, without any properties. But the template is still renderen, and updates when I save the template.

![Peek 2021-02-10 13-59](https://user-images.githubusercontent.com/1561480/107513483-91d0f380-6ba8-11eb-92b4-64cf40e75a2d.gif)

**Comment by louisjrdev** [comment] 2021-02-10 13:13
Thanks for the quick response, I will try again with a fresh install and can put the code in a repo, as well as giving you my linux / dotnet verions etc.. Could just be something I have somehow messed up with my installation perhaps.

**Comment by louisjrdev** [comment] 2021-02-11 19:38
Hi @bergmania, so I am not entirely sure how, but after messing with the RazorCompileOnPublish settings in the .csproj and then deleting my bin folder and rebuilding I now have this working. Bit afraid to mess with it more incase I somehow get it back to its previous state. I am thinking it is most likely something that got a bit out of place in my bin folder, I think this can probably be closed. Thanks for your help, the alpha is working great!

**Comment by CarlSargunar** [comment] 2021-02-11 21:26
Just to chip in too, I just ran this again and didn't have to do anything - worked even after changes to to the views, and after a reboot.

Ran on Alpha003, on my trusty Raspberry pi 4 running Raspberry Pi OS (debian based) - it's the only linux box I've got for now

**Comment by louisjrdev** [comment] 2021-02-11 22:45
So I have actually just setup a fresh install with no changes other than adding 1 doctype, creating a node with it and editing the template and the issue occurs again for me.
I am running:
OS: Fedora 33 Workstation
Dotnet: 5.0.32
Umbraco Alpha 3
DB: Azure SQL Database
Models Builder: PureLive (happens in LiveAppData mode too)

Happens when running with `dotnet run` or running in my IDE.

I can provide access to a git repo with a backup of the database.

**Comment by bergmania** [comment] 2021-02-12 05:55
@louisjrdev, can you provide you log file?

**Comment by louisjrdev** [comment] 2021-02-12 08:00
I have shared with you my repo everything should be in the git repo 😊

**Comment by bergmania** [comment] 2021-02-12 08:53
@louisjrdev, I still can't reproduce.. Can you try to update your `Serilog element` in `AppSettings.Development.json` to the following:

```
"Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft.AspNetCore.Mvc.Razor": "Debug"
            }
           
        },
        "WriteTo": [
            {
                "Name": "Async",
                "Args": {
                    "configure": [
                        {
                            "Name": "Console"
                        }
                    ]
                }
            }
        ]
    },
```

The interesting thing, is the override the namespace `Microsoft.AspNetCore.Mvc.Razor` to log debug.


When I do this.. I have the following in my console log:

```
[09:47:09 WRN] Register called when MainDom has not been acquired
[09:47:09 INF] Creating the content store, localContentDbExists? False
[09:47:09 INF] Creating the media store, localMediaDbExists? False
[09:47:10 INF] Acquiring.
[09:47:10 INF] Acquired.
[09:47:10 INF] Initializing Umbraco internal event handlers for cache refreshing.
[09:47:10 INF] Adding examine event handlers for 3 index providers.
[09:47:10 INF] Starting initialize async background thread.
[09:47:16 INF] Now listening on: https://localhost:5001
[09:47:16 INF] Now listening on: http://localhost:5000
[09:47:16 INF] Application started. Press Ctrl+C to shut down.
[09:47:16 INF] Hosting environment: Development
[09:47:16 INF] Content root path: D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco
[09:47:27 INF] Loading content from database [Timing a7a60b9]
[09:47:27 INF] Completed. (172ms) [Timing a7a60b9]
[09:47:27 INF] Loading media from database [Timing 7f36143]
[09:47:27 INF] Completed. (14ms) [Timing 7f36143]
[09:47:27 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:47:27 DBG] Initializing Razor view compiler with no compiled views.
[09:47:29 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' started.
[09:47:32 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' completed in 2724.0726ms.
[09:47:32 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:47:55 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:47:55 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' started.
[09:47:55 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' completed in 110.4236ms.
[09:47:55 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:48:06 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:48:06 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' started.
[09:48:06 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' completed in 55.6825ms.
[09:48:06 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:48:13 DBG] View lookup cache hit for view 'Home' in controller 'Render'.
[09:48:13 DBG] View lookup cache hit for view 'Home' in controller 'Render'.
[09:48:14 DBG] View lookup cache hit for view 'Home' in controller 'Render'.
[09:48:14 DBG] View lookup cache hit for view 'Home' in controller 'Render'.

```


Everytime I change my template file. The next request has these lines.
```
[09:48:06 DBG] View lookup cache miss for view 'Home' in controller 'Render'.
[09:48:06 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' started.
[09:48:06 DBG] Compilation of the generated code for the Razor file at 'D:\Projects\UmbracoRazorRuntimeCompilationIssue\JJWebsiteUmbraco\Views\Home.cshtml' completed in 55.6825ms.
```

If I'm not changing the template I only see this
```
[09:48:14 DBG] View lookup cache hit for view 'Home' in controller 'Render'.
```

**Comment by louisjrdev** [comment] 2021-02-12 09:33
Great thanks @bergmania ! So with those changes I see that it gives me a cache hit, even after making a change to the template:
```
//First Load of site
View lookup cache miss for view 'Home' in controller 'Render'.
Compilation of the generated code for the Razor file at '/home/louis/code/JJWebsiteUmbraco/JJWebsiteUmbraco/umbraco/UmbracoBackOffice/Default.cshtml' started.
Compilation of the generated code for the Razor file at '/home/louis/code/JJWebsiteUmbraco/JJWebsiteUmbraco/umbraco/UmbracoBackOffice/Default.cshtml' completed in 394.5898ms.

//Refresh site after first load
View lookup cache hit for view 'Home' in controller 'Render'.
View lookup cache hit for view 'Home' in controller 'Render'.

//Changed my template
Antiforgery validation failed with message 'The provided antiforgery token was meant for a different claims-based user than the current user.'.

//Refresh site - hits the cache still
View lookup cache hit for view 'Home' in controller 'Render'.
View lookup cache hit for view 'Home' in controller 'Render'.
```

**Comment by bergmania** [comment] 2021-02-12 09:57
This really seems strange.. 

I can see in your repo, that you are using Rider, so you should be able to debug into the Umbraco and Microsoft decompiled code.

If I create the following route hijacking, I can set a breakpoint in the decompiled code.
```
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.Extensions.Logging;
using Umbraco.Web;
using Umbraco.Web.Common.Controllers;

namespace JJWebsiteUmbraco
{
    public class HomeController : RenderController
    {
        public HomeController(ILogger<RenderController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor) : base(logger, compositeViewEngine, umbracoContextAccessor)
        {
        }

        public override IActionResult Index()
        {
            Debugger.Break();
            return base.Index();
        }
    }
}
```

One interesting file is RuntimeViewCompiler (Rider finds it in if you use find all). I had a breakpoint in `CompileAsync`
![image](https://user-images.githubusercontent.com/1561480/107753800-e0a19900-6d20-11eb-9a38-813e09c5eb56.png)

From the call stack, the `RazorViewEngine.LocatePageFromViewLocations` also seems interesting as it makes the cache look up in `ViewLookupCache.TryGetValue`..

**Comment by bergmania** [comment] 2021-03-25 15:29
@louisjrdev any updates? otherwise, I'll close this issue :)

**Comment by bergmania** [comment] 2021-09-10 13:04
Hey, if you have any more steps to reproduce then ping on this issue and we can have another look. Ill close for now

**Closed by bergmania** 2021-09-10 13:04 UTC
Labels: project/v9
