### ISSUE TITLE
Using Fallback to default langauge on a specific item changes the whole VariationContext

### ISSUE THREAD

**Issue by Musealali** [umbraco/Umbraco-CMS#14351] opened 2023-06-07 08:58 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

 Whenever I try to get a fallback value from a property, it will simply overwrite the variation context for the given request with whatever culture was provided.

This effectively breaks the entire multi-lingual layer, as every link and nodes fetched from here on out will use the new variation context, that is in the fallback culture, which is never the intention.

### Specifics

We believe that this bug was introduced with this PR:

https://github.com/umbraco/Umbraco-CMS/pull/13889/files

### Steps to reproduce

1. Create a simple documenttype with a couple of properties (some text strings and media picker)
2. Create a language (danish) and set is a defaultlanguage - but with no fallback.
3. Create an English language with no Fallback
4. Create some content and fill in the properties for both danish and english (but do not add an image to the English node)
5. Remember to add the domain for danish and english
6. In your template only use fallback on the image item

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/4f199632-7fd8-4d07-8c4e-288d79cf989e)

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/f028d48e-3b6c-45ca-87d2-8c0a50990075)

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
	var image = Model.Value<IPublishedContent>("niceImage", fallback: Fallback.ToDefaultLanguage);
}

@Model.Value("title")
@Model.Value("anotherString")
@Model.Value("someName")
<img src="@image.Url()">

```

### Expected result / actual result

Expected result is to only see the image item fallback to the defaultlanguage.

What is actually happening is the whole Variation context falling back to the default language.

This means that all the properties and not only the image one will fallback. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/9c94f768-9d56-4ab8-8476-c0ccd4c539d0)

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/067fedb7-5b04-4392-9636-31056cf4799b)

---
_This item has been added to our backlog [AB#30202](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30202)_

**Comment by jveer** [comment] 2023-07-14 10:25
We are having the same issue after upgrading from 10.4.2 to 10.6.1.

From doing a little bit of debugging, I think it's caused by this PR: https://github.com/umbraco/Umbraco-CMS/pull/13889

As it overrides the `VariationContext` when the culture provided and current culture are not the same. However, it never sets it back to the original value..

We don't use the fallback, but we use `.ValueFor(x => x.Property, culture)`, with a culture. A bypass for us is to use `.Value("property", culture)`..

But it's a bug that breaks the complete website, because we use it for the alternate tags.. Hopefully a fix can be implemented soon.

**Comment by sniffdk** [comment] 2023-07-31 12:31
Would also love to have an update on this soon @Musealali @andr317c , we are closing in on 2 months of waiting here 🕐

**Closed** 2023-10-17 11:24 UTC
Labels: status/regression, state/sprint-candidate, type/bug, area/backend, affected/v11, affected/v12
