### ISSUE TITLE
Choosing thumbnail in catalogue view opens root folder with random media folder names

### ISSUE THREAD

**Issue by lassespilling** [umbraco/Umbraco-CMS#11920] opened 2022-01-28 14:11 UTC
### Version

9.2.0

### Bug summary

When trying to add a thumbnail within Catalogue appearance on a element in a block list editor, the thumbnail opens a root folder view with all the random media folder names.

![catalogue-appearance](https://user-images.githubusercontent.com/1065943/151561051-e68de67f-4fd7-41cc-8d58-b1d41945f3a2.jpg)

Here you can see the view i am mentioning:
![random-folders-media](https://user-images.githubusercontent.com/1065943/151561290-553f61d5-0dc9-47f0-918c-31b4e53ea1fe.jpg)

This gets really frustrating having to open all the folders to find the image i want for thumbnail.

![image-that-i-want](https://user-images.githubusercontent.com/1065943/151561698-ef0606b5-ea52-4ed5-bd29-4b18d314b1bf.jpg)

### Steps to reproduce

Create a block list editor and an element, then click on element within blocklist and navigate to catalogue-appearance.

### Expected result / actual result

I would expect it to open the media picker with the folders that i created in media library. Similar to a media picker.

**Comment by kjac** [comment] 2023-01-09 06:13
Hi @lassespilling,

Thanks for raising this 😄 and apologies for the very belated response.

This is intended behaviour. What you're seeing is a file system picker that picks files on disk. 

The catalogue thumbnail feature is not intended to be used with media items, but rather with thumbnail images created explicitly as files on disk - either somewhere under wwwroot (they will be publicly available though) or in a sub folder to App_Plugins. 

The assumption is that you'll want these thumbnails as static resources, checked into source control and deployed as part of the site functionality. When using media items for these thumbnails, you risk editors unintentionally overwriting those thumbnails.

**Closed by kjac** 2023-01-09 06:13 UTC
Labels: type/bug
