### ISSUE TITLE
Sorting of tabs in backend isn't respected

### ISSUE THREAD

**Issue by martinbrud** [umbraco/Umbraco-CMS#14280] opened 2023-05-22 11:08 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

Suddenly tabs doesn't sort tabs the way. I have been around in all doc types and compositions to ensure the sorting numbers and tab names are the same. 

### Specifics

They are like this, https://i.imgur.com/knPMAyn.png, but I wan't "Content" to be first, "Settings" to be last.

### Steps to reproduce

Update sort numbers on doc types and compositions. Check from editor point of view if they are sorted correctly.

**Comment by kjac** [comment] 2023-05-22 18:49
Hi @martinbrud,

Thank you for reaching out 👍 

I'm afraid I can't really reproduce this on a clean 11.3.1 install 😕 

My content type _Composed_ is composed of two other content types (_Composition One_ and _Composition Two_):
<img width="1643" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/e09d1721-0a75-4d37-ba5c-4c562eb92630">

- _Composition One_ has a tab with sort order 5
- _Composed_ has a tab with sort order 10
- _Composition Two_ has a tab with sort order 20

When editing content of type _Composed_, things look as expected:
<img width="1306" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/f7cef1ab-43ee-4d82-83f5-b844b277e4db">

If I go ahead and change the sort order of the _Composed Tab_ to 0:
<img width="1517" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/e3046de0-4c8a-4222-aba9-b970356fcfa3">

...the editing experience adjusts accordingly:
<img width="1190" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/1376e0a7-3440-4f60-92e7-7a3b98621a42">

As I couldn't reproduce, I had a theory that this might be tied to the creation order of the content types (yes, I was grasping). But that is not the case; in the screenshots above, the content types are created in the order _Composition One_, _Composed_, _Composition Two_.

**Comment by martinbrud** [comment] 2023-05-22 19:58
Hi Kenn,

Thanks for your reply. I will try to update the sorting numbers again.
Maybe I have overlooked something. :)



Bedste hilsner,
Martin Bernt Rud
Freelance webudvikler og digital rådgiver
T: 4128 4388

**Comment by martinbrud** [comment] 2023-05-23 05:50
> I have investigated a bit more. Maybe it can help you reproduce:

On a page document type I have inserted a composition with a tab "Settings" (the tab is onthe composition). When I open reordering on the page the tab has a (referenced) sorting = 0 (which is wrong):

![DT-page](https://github.com/umbraco/Umbraco-CMS/assets/48518930/1c0933b8-c1a6-4b8a-85ed-0237a1eb8053)

But on the composition it is 99:
![DT-composition](https://github.com/umbraco/Umbraco-CMS/assets/48518930/e6dde0c7-29eb-48e2-aa96-b664917806ca)

**Comment by kjac** [comment] 2023-05-23 10:20
Hi @martinbrud,

Thank you for investigating further. Unfortunately I still cannot replicate 😖 

The sort order of my _Composition Two Tab_ is now 99:
<img width="1270" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/88e67085-86e3-40eb-b367-e01847ea7f8d">

The editor still plays nice:
<img width="790" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/aaf20750-9c93-45d3-a018-cf834e0d62db">

Judging from your screenshot, all your tabs are inherited from compositions, so I have also tried creating a _Fully Composed_ content type, consisting solely of other compositions (introducing _Composition Three_ containing a tab with sort order 0):
<img width="1255" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/6dfccc52-e64c-4d2f-bbef-feb4d45ba505">

...but still the editor works as expected:
<img width="1032" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/05e3542d-7656-4685-aabd-9ebd86ce59eb">

Inspecting the JSON payload for a content item also shows the tabs in the correct order:
<img width="1001" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/724b0567-4af4-4f32-9b42-ee0b41a24a73">

I'm rather running out of ideas here. Are you perhaps using some add-on or package that might interfere with tabs?

**Comment by martinbrud** [comment] 2023-05-23 11:03
Thanks for trying hard. No problem - I can live with it, and maybe some
time I find out what causes the problem. :)

About packages: Maybe NestingContently or ConditionalDisplayers could do
it. I tried to uninstall NestingContently, but no change.
ConditionalDisplayers I can't do without.

    <PackageReference Include="Dawoe.OEmbedPickerPropertyEditor" Version=
"11.0.0" />
    <PackageReference Include="Dyfort.Umbraco.AutoImageOptimize" Version=
"1.0.1" />
    <PackageReference Include="NestingContently.Umbraco" Version="11.0.1" />
    <PackageReference Include="Our.Umbraco.ConditionalDisplayers" Version=
"3.4.0" />
    <PackageReference Include="Our.Umbraco.LinkedPages" Version="10.0.1" />
    <PackageReference Include="Umbraco.Cms" Version="11.3.1" />
    <PackageReference Include="uSync" Version="11.1.0" />

[image: 2222.png]


Bedste hilsner,
Martin Bernt Rud
Freelance webudvikler og digital rådgiver
T: 4128 4388

**Comment by kjac** [comment] 2023-05-23 12:47
Thanks 😄 

It might be worth it to try setting up a clean 11.3.1 install and point it at a copy of your DB to see if things work as expected. I would certainly hope so... and then things would point at either packages or things being done in your codebase i.e. in `SendingContentNotification` handlers.

I'm going to close this for the time being. If you can reproduce on a clean 11.3.1, please reopen so we can get to the bottom of this.

**Closed by kjac** 2023-05-23 12:47 UTC
Labels: state/needs-more-info, state/needs-reproduction, type/bug
