### ISSUE TITLE
14.0.0-RC1 Throws error during upgrade

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16115] opened 2024-04-19 23:58 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-RC1

### Bug summary

I'm upgrading a SQL Server database that was created on something like Umbraco 9 and then has been upgraded up to v14.0.0-beta1. When upgrading to RC1 the bootscreen throws.

### Specifics

```
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Cms.Core.Exceptions.BootFailedException: An error occurred while running the unattended upgrade.
The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoUser' that match the referencing column list in the foreign key 'FK_umbracoUserData_umbracoUser_key'.
Could not create constraint or index. See previous errors.
Please check log file for additional information (can be found in 'LoggingSettings.Directory')

-> Umbraco.Cms.Core.Exceptions.UnattendedInstallException: An error occurred while running the unattended upgrade.
The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoUser' that match the referencing column list in the foreign key 'FK_umbracoUserData_umbracoUser_key'.
Could not create constraint or index. See previous errors.
Please check log file for additional information (can be found in 'LoggingSettings.Directory')
```

```
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details. -> Umbraco.Cms.Core.Exceptions.BootFailedException: An error occurred while running the unattended upgrade. The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoUser' that match the referencing column list in the foreign key 'FK_umbracoUserData_umbracoUser_key'. Could not create constraint or index. See previous errors. Please check log file for additional information (can be found in 'LoggingSettings.Directory') -> Umbraco.Cms.Core.Exceptions.UnattendedInstallException: An error occurred while running the unattended upgrade. The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoUser' that match the referencing column list in the foreign key 'FK_umbracoUserData_umbracoUser_key'. Could not create constraint or index. See previous errors. Please check log file for additional information (can be found in 'LoggingSettings.Directory')
Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)
Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+InterfaceMiddlewareBinder+<>c__DisplayClass2_0+<<CreateMiddleware>b__0>d.MoveNext()
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, bool retry)
Umbraco.Cms.Api.Management.Middleware.BackOfficeAuthorizationInitializationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+InterfaceMiddlewareBinder+<>c__DisplayClass2_0+<<CreateMiddleware>b__0>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Steps to reproduce

Upgrade from v9 via v10, v11,v12, v13 and then to v14 rc1

### Expected result / actual result

Upgrades should work or error should provide information about needed action.

**Comment by enkelmedia** [comment] 2024-04-20 00:08
This will solve the problem if anyone else has the same issue:

```SQL
ALTER TABLE [dbo].[umbracoUser] DROP CONSTRAINT DF_umbracoUser_key;
ALTER TABLE [dbo].[umbracoUser] ADD CONSTRAINT DF_umbracoUser_key UNIQUE ([key]);
```

**Comment by Zeegaan** [comment] 2024-04-22 08:10
Heyo! 👋 
This is a bug caused by a missing index, which has been fixed when going from v13 -> v14-rc1
Problem is if you were already on the beta001, there is not much we can do 🤔 (we cannot insert the migration earlier, as that breaks everyone already on rc1)

Atleast there is a manual workaround you have come up with for now 😁 
But we will look into if there is a possible way of resolving this, thanks for reporting 🐛

**Comment by enkelmedia** [comment] 2024-04-22 09:15
I figured that this was the problem =D I guess that is a very small issue, not many people that is upgrading from beta001 to rc1 =D

I'm okey with closing the issue, or keep it open for a while if anyone else have the same issue but might not need to be addresses in code.

Feel free to close if you want to  =D

**Closed** 2024-04-23 07:45 UTC
Labels: state/needs-investigation, type/bug, affected/v14
