### ISSUE TITLE
Content Delivery API - API non compliant to Swagger Spec

### ISSUE THREAD

**Issue by vsilvar** [umbraco/Umbraco-CMS#14299] opened 2023-05-25 08:43 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc2

### Bug summary

The OpenAPI v3 specification does not support path parameters with multiple segments (https://github.com/OAI/OpenAPI-Specification/issues/892).

This means that any OpenApi tooling won't support it either, and will simply encode the slashes when doing API requests.
This can already be seen in the swagger UI itself, which means you get a 404 when trying to, for example, retrieve the root `/`

In order for Umbraco to have a compliant spec and allow consumers to use code generation tools, I think it should support both encoded and non-encoded paths.

### Steps to reproduce

1. Install the latest Umbraco 12 RC2
2. Create some dummy content types and content
3. Use the swagger UI to retrieve content by path `/` or configure a code generation tool by following the following steps
4. Save the `/umbraco/swagger/delivery/swagger.json` file in the project as `UmbracoDeliveryApiSwagger.json`
5. Add the following to the `.csproj` file:
```
<ItemGroup>
 <PackageReference Include="NSwag.ApiDescription.Client" Version="13.19.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
 </PackageReference>
 <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
 <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="7.0.5">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
 </PackageReference>
 <OpenApiReference Include="UmbracoDeliveryApiSwagger.json" CodeGenerator="NSwagCSharp" Namespace="Umbraco.DeliveryApi" ClassName="DeliveryApiClient" />
</ItemGroup>
```
6. Add the following to the end of `WithEndpoints` in `Startup.cs`:
```
u.EndpointRouteBuilder.MapGet("/delivery-test", async (HttpContext context, IOptions<WebRoutingSettings> webRoutingSettings, IHttpClientFactory httpClientFactory) =>
{
    DeliveryApiClient client = new(context.Request.GetApplicationUri(webRoutingSettings.Value).ToString(), httpClientFactory.CreateClient(nameof(DeliveryApiClient)));

    return await client.GetContentItemByPathAsync("/");
});
```
7. When you call the `/delivery-test` endpoint you'll get an exception due to the 404

**Comment by vsilvar** [comment] 2023-05-25 08:45
#14298 is related to this issue.

Also, interestingly enough, if backslashes are used instead of forward slashes, then it works.

**Comment by vsilvar** [comment] 2023-05-25 09:13
Hi @kjac 

Indeed, the issue is the encoding, as you can see by the generated code:
![image](https://github.com/umbraco/Umbraco-CMS/assets/279175/4b01a3a7-932b-4cd1-8f05-fe617002884f)


The snippet you are mentioning, as I interpret it, only seems to apply to query parameters, and not path parameters.
I'm not totally sure my interpretation is correct, but it seems to align with the [schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml#L375):
![image](https://github.com/umbraco/Umbraco-CMS/assets/279175/c5644151-d125-482e-beb7-8cc32aeb2e62)
![image](https://github.com/umbraco/Umbraco-CMS/assets/279175/cf6a5099-8ba6-4df1-9e9b-a39ac67e4e85)

**Comment by kjac** [comment] 2023-05-25 09:55
Hi again @vsilvar,

Thanks for investigating, I really appreciate you taking the time 🥇 

I'm going to keep this issue open for now, even though technically it is a duplicate of #14298 ... we'll make sure to update both issues when we know more.

**Comment by kjac** [comment] 2023-05-26 17:42
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14311

See also https://github.com/umbraco/Umbraco-CMS/issues/14298#issuecomment-1564717690

**Comment by kjac** [comment] 2023-05-31 11:11
https://github.com/umbraco/Umbraco-CMS/pull/14311 has been merged now, so I'll go ahead and close this issue.

We are looking into a V12 RC3, which will contain this fix. It is still unknown when it will be out, we have a few more things we'd like in there.

Again, thank you so much for bringing this issue to our attention 👍

**Closed by kjac** 2023-05-31 11:11 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, area/backend, affected/v12
