### ISSUE TITLE
NuCache.Content.db locked when app starts after inactivity on Azure

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#6363] opened 2019-09-17 17:54 UTC
Sometimes when our web app in Azure turns off due to inactivity, whenever someone tries to go to the website the websites throws the following exception:
```
-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.IO.IOException: The process cannot access the file 'D:\home\site\wwwroot\App_Data\TEMP\NuCache\NuCache.Content.db' because it is being used by another process.
```
[FullException.txt](https://github.com/umbraco/Umbraco-CMS/files/3622753/FullException.txt)
[UmbracoTraceLog.RD0003FF744804.20190910.zip](https://github.com/umbraco/Umbraco-CMS/files/3622794/UmbracoTraceLog.RD0003FF744804.20190910.zip)

This seems to only happen when the site goes offline due to inactivity, and a restart causes the file to be unlocked and everything to work properly again.

We do not use deployments slots or application insights currently. And the settings as described in [Issue 5035](https://github.com/umbraco/Umbraco-CMS/issues/5035) have also been configured properly. I am currently trying out the "fix" to ignore the localDb file but obviously I hope for a more appropriate solution. If there are any more logs needed please do tell.

Reproduction
------------
- Release an Umbraco site to Azure
- Wait until it goed offline due to inactivity
- Try to go to a page

Umbraco version: 8.1.3

---
_This item has been added to our backlog [AB#3407](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3407)_

**Comment by nul800sebastiaan** [comment] 2019-09-18 11:43
Interesting, how do you "detect"/determine that a site goes offline due to inactivity?

**Comment by deMD** [comment] 2019-09-18 11:50
Mostly due to the fact this issue happens when booting, and the web app is not set to `Always On` so I know it does go offline when idle for to long as that is default Azure behaviour, and I also know this exception happens during boot, as it says in the exception message. And as we have not done any deploy or other actions on the site for a while, there is no other reason for the web app to go offline.

**Comment by John-Blair** [comment] 2019-10-15 13:50
@Shazwazza - you reference this issue from mine #6546
The location of the file in this error - shows they have not configured their app settings correctly - if they had it would refer to D:\local\temp. 

>The process cannot access the file >'D:\home\site\wwwroot\App_Data\TEMP\NuCache\NuCache.Content.db'

The location

**Comment by deMD** [comment] 2019-10-15 13:55
Not sure why the location is that, we have the appsettings correct as per the ticket I referenced: 
```
<add key="Umbraco.Core.LocalTempStorage" value="EnvironmentTemp" />
<add key="Umbraco.Examine.LuceneDirectoryFactory" value="Examine.LuceneEngine.Directories.SyncTempEnvDirectoryFactory, Examine" />
```

**Comment by John-Blair** [comment] 2019-10-15 17:05
You may want to check you do not have any applications settings configured directly in Azure as they override the web.config settings.  A minor diff in my settings is I don't have the ", Examine" assembly name in the 2nd config. But it is the first setting which dictates the  %TMP% environment variable should be used to specify the location of the temp files which is normally D:\local\temp on Azure.  My web.config contains my localhost settings so I specify the changed settings directly in Azure to override the web.config ones:  
![image](https://user-images.githubusercontent.com/28809458/66852969-23f5c700-ef76-11e9-9030-dbc40122cfc1.png)

**Comment by deMD** [comment] 2019-10-17 09:14
I did not have those settings in the application settings in Azure but defined globally in the web.config directly, so overriding shouldn't be a problem. But just to be sure I also added them to the app settings now.

**Comment by John-Blair** [comment] 2019-10-17 10:02
fyi  - you can check if you are setup correctly by going to the Kudu version  (*..scm.azurewebsites.net)  of your website and seeing if your umbraco files are in d:\local\temp

![image](https://user-images.githubusercontent.com/28809458/66999110-4e0dcd00-f0cd-11e9-8a62-53e2c710bc53.png)

You will need to set the make the following setting in Azure App Settings first to make the temp folders visible.

![image](https://user-images.githubusercontent.com/28809458/66999185-74336d00-f0cd-11e9-9999-1b94f7903edf.png)

**Comment by deMD** [comment] 2019-10-17 10:12
I can see the ExamineIndexes folder there, however there is no UmbracoData folder:
![image](https://user-images.githubusercontent.com/22070292/67000053-64b92180-f0d7-11e9-9c72-27f085097a0c.png)
![image](https://user-images.githubusercontent.com/22070292/67000073-6d115c80-f0d7-11e9-994c-d681a13dbafe.png)

**Comment by Shazwazza** [comment] 2019-11-05 00:11
Hi @deMD 

If you can report back if there's still an issue when you have all of the correct settings applied that would be great. We've discovered that an additional and very important setting needs to be configured too and I've submitted a PR for our docs regarding it, you can see here: https://github.com/umbraco/UmbracoDocs/pull/2042

The important part is this:

> You need to [disable overlapping recycling](https://github.com/projectkudu/kudu/wiki/Configurable-settings#disable-overlapped-recycling) by adding the `WEBSITE_DISABLE_OVERLAPPED_RECYCLING` setting to appSettings with a value of `1`. If you don't do this, you will most likely get some file locking issues with Umbraco caches files and Lucene files.

There is also another pending PR to update the docs for v8 here https://github.com/umbraco/UmbracoDocs/pull/1994

**Comment by deMD** [comment] 2019-11-05 15:59
Hi @Shazwazza I will add that app setting as well. So far I have not noticed any more errors since using the correct key values so  think that was the bulk of the issue.

**Comment by Shazwazza** [comment] 2019-11-12 00:25
Thanks, i will close this issue now.

**Closed by Shazwazza** 2019-11-12 00:25 UTC
Labels: state/sprint-backlog, type/bug

**Comment by deMD** [comment] 2019-12-16 16:17
@Shazwazza Sadly here to report that the issue does still occur for me in Umbraco 8.4. I have added more info in issue #5035

**Comment by claushingebjerg** [comment] 2020-04-15 05:37
experienced this in vanilla 8.6 as well

**Comment by Shazwazza** [comment] 2020-04-15 07:16
@claushingebjerg please explain what configuration you are using, have you seen/followed these config options for 8.6 (these docs have been updated post 8.6 release)? https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps

**Comment by Shazwazza** [comment] 2020-04-15 07:16
sorry just realized you said _not Azure_, then do you have steps to replicate and/or more information about hosting environment, configuration, etc... ?

**Comment by claushingebjerg** [comment] 2020-04-15 07:25
Ok, so im running sites on a managed server at a host, so i dont have access to the specifics of the IIS.
I have never experienced the mentioned error before the two latest sites i've worked on. An 8.5.5 and now 8.6. The 8.6 site was installed yesterday and i totally vanilla. installed directly on the server, no packages installed. The host rebooted the server during the night for maintenance, and when i hit the site this morning i got the error. Touching the web.config made it go away

**Comment by Shazwazza** [comment] 2020-04-15 07:31
@claushingebjerg there's a lot of moving parts with hosting setups that can affect all sorts of things. Whether it's a network shared drive that's hosting the app (like azure), etc... There's lots of info among these docs related to those types of things https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/

**Comment by claushingebjerg** [comment] 2020-04-15 07:32
Ok... i'm now pretty sure it has something to do with multiple domain names on the same site...
when i hit the site from an "extra" domain name i got the error again. Messed about. Got it up. And now the main domain went down with the error...

**Comment by claushingebjerg** [comment] 2020-04-15 07:34
Ok, but i got 50 pre 8.5 sites running on the server with no issues...

**Comment by Shazwazza** [comment] 2020-04-15 07:52
There's not a lot I can tell you unless there's steps to reproduce. I'd suggest having a look in your logs to see where there's errors occurring, maybe your site is in a restart loop or something similar.

**Comment by webtimisten** [comment] 2020-06-26 08:34
> Ok, but i got 50 pre 8.5 sites running on the server with no issues...

Did you solve the issue? I'm having the same problem now in Umbraco 8.6.3.

**Comment by vladicaivanovski** [comment] 2022-09-30 10:35
The process cannot access the file 'D:\\local\\Temp\\UmbracoData\\8c88e448981650d162c7b798b5f3e3de\\NuCache\\NuCache.Content.db' because it is being used by another process.

Happening a lot in our Umbraco Azure website v8.18.4. We have deployment slots and proper settings as suggested for Azure websites, but still we see this frustrating error very often which crashes the whole site and requires restart in order to get up and running.

Please help
