### ISSUE TITLE
Infinite Editor from member property with a media picker for folders, shows wrong listview 

### ISSUE THREAD

**Issue by Emetico** [umbraco/Umbraco-CMS#13770] opened 2023-02-01 11:41 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

Using a media picker to select a folder on a member property and trying to open the selected folder in the Infinite Editor, shows the listview for the members and not the listview for the media as expected.

### Specifics

https://user-images.githubusercontent.com/10114290/216032885-60e11a87-c268-4835-aeab-bcb021c011ee.mp4

### Steps to reproduce

1. Add a new Media Picker (Umbraco.MediaPicker3) datatype and set the accepted types to the standard folder and the minimum amout to 0 and the maximum amount to 1.

2. Add a new property on the standard member type with the new Media Picker datatype.

3. Create a new standard member and go to the new property and select a random folder.

4. Click on the foldername and choose to open it in the medialibrary in infinite editor

### Expected result / actual result

I would except the the listview to be the one for folder and not the members.

**Comment by nikolajlauridsen** [comment] 2023-02-01 15:23
Heya, just popping it to say that I've taken a look at reproducing this is both v10 and v11, and can confirm that the issue is there in both cases.

We'd love some help fixing this, so I've marked it as up for grabs :smile:

**Comment by nul800sebastiaan** [comment] 2023-03-17 11:21
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13817

**Closed** 2023-03-17 11:20 UTC
Labels: community/pr, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11
