### ISSUE TITLE
Strange behavior for validation of RTE inside a block list field

### ISSUE THREAD

**Issue by Pieter-vdh** [umbraco/Umbraco-CMS#15993] opened 2024-04-05 09:58 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2

### Bug summary

When using Block List fields that contain an Element Type including a mandatory Rich Text Editor, the validation gives a vague message when publishing.

### Specifics

This might be related to a previous bug report: #15270

An item that contains a Block List always seems to give a vague error when publishing if the element inside the list contains a Rich Text Editor.
This seems to only be the case for mandatory field validation. Not for custom validation.

Here is what I did:
My page item contains a Block List with elements of type `ValidationElement`. This element type contains 3 fields:
- Title (Textstring + Mandatory)
- MandatoryText (Rich Text Editor + Mandatory)
- CustomValidationText (Rich Text Editor + Custom validation as email)

I edit my page item and add a new ValidationElement to my list.
I don't fill in any values and try to submit. This gives me the validation error that my Title field is mandatory. No message for the other 2 fields.
![image](https://github.com/umbraco/Umbraco-CMS/assets/126693637/8a957941-82c5-4f95-91fd-8b9f1f3de72d)

I fill in the title and submit. No validation error at this point.
I save and publish. I get a **red validation error** that something inside my list is wrong.
![image](https://github.com/umbraco/Umbraco-CMS/assets/126693637/4c7687b3-4132-4586-82e0-3733cf29ab0c)

I see that the CustomValidationText is not correctly filled in. However, no message for the empty MandatoryText field.
![image](https://github.com/umbraco/Umbraco-CMS/assets/126693637/a93efc4d-93c2-4b56-b59c-5614fad677a7)

I fill in this field (in this case with an email address). I submit and get no error again at this point. Once again, I save and publish.
I now get a **yellow warning error** that 'some' validation failed. But no specific direction as to where or what.
![image](https://github.com/umbraco/Umbraco-CMS/assets/126693637/fb80b564-80e7-4025-958d-237ca6c2e0a7)

When I open my list element details, there is no validation message anywhere.
I press 'Save and publish' a second time and now I get a **red validation error**.
![image](https://github.com/umbraco/Umbraco-CMS/assets/126693637/37cfee72-1c56-49f5-b96d-0edf7ffb5856)

The field with the error is now also marked.
![image](https://github.com/umbraco/Umbraco-CMS/assets/126693637/d2e0b901-b455-4201-a959-d6bad72ad8f4)

What is causing this inconsistency?
Especially the vague yellow warning is very confusing to content creators as they won't realize that you have to click 'Save and publish' a second time to get the real error message.

Any help would be appreciated

### Steps to reproduce

Create an Element Type with 3 fields:
- Title (Textstring + Mandatory)
- MandatoryText (Rich Text Editor + Mandatory)
- CustomValidationText (Rich Text Editor + Custom validation as email)

Create a Document Type with 1 field:
- List (Block List that allows adding the created Element Type)

Follow the steps in the description above.

### Expected result / actual result

Expected result:
Validation is consistent and will show either when clicking 'Submit' or 'Save and publish' for all fields.

Actual result:
The Rich Text Fields behave differently based on their settings. Mandatory RTE fields produce a yellow warning error on 'Save and publish' that is too vague to be useful, especially when using complicated Document Types with many different Block Lists.

---
_This item has been added to our backlog AB#43158_

**Comment by NguyenThuyLan** [comment] 2024-07-25 04:03
Hi @Pieter-vdh , I agree this is a really annoying bug and needs to be fixed. I will let the team know. Thank you for reporting.
I reproduced this issue and noticed that in v14, mandatory fields don't even have ***** marked as required.
Btw, the CustomValidationText should not be warned because it is not mandatory and can be empty.
<img width="949" alt="image" src="https://github.com/user-attachments/assets/599347ee-e475-49c4-a97e-662fbe99fa61">

**Comment by Pieter-vdh** [comment] 2024-07-26 07:00
Hi @NguyenThuyLan 

Yes, you are correct. The CustomValidationText Should not report a problem when left empty. As you can see in this screenshot it _does_ do that. So this is another bug in my opinion.
![image](https://github.com/user-attachments/assets/c3e970a7-e4cf-4eae-983f-d2f8775c96de)

Thanks you for opening this up to the community.

**Closed** 2024-08-27 10:51 UTC
Labels: type/bug, release/13.5.0
