### ISSUE TITLE
ApplicationVirtualPath setting does not work well.

### ISSUE THREAD

**Issue by a-t-k** [umbraco/Umbraco-CMS#12092] opened 2022-03-03 10:37 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

This setting is not supported by the following calls

![image](https://user-images.githubusercontent.com/14151950/156545172-02491aa5-171d-48bc-a57b-951aa3f5a8f8.png)
![image](https://user-images.githubusercontent.com/14151950/156545303-f7ceffa9-155b-42e8-9489-6cb8dc180800.png)
![image](https://user-images.githubusercontent.com/14151950/156545598-3f97c576-efcf-4ab3-84a3-3d0f16f4bce6.png)

On used URL-Rewriting with IIS and aktive ApplicationVirtualPath  setting the UMB-XSRF-V does not work
![image](https://user-images.githubusercontent.com/14151950/156546171-561ea75d-2974-46c6-bbb1-7255abd1d337.png)

### Specifics

After the "ApplicationVirtualPath" setting has been set, almost all pages are mapped correctly. However, the pages visible in the pictures cannot be reached. "ApplicationVirtualPath" is probably not implemented everywhere in "Java-Script".
This means that Umbraco 9 cannot be run with the "ApplicationVirtualPath" settings.

### Steps to reproduce

Set "ApplicationVirtualPath in appsettings "/api/cms"
set same virtual path "/api/cms" in IIS
in the browser go to "localhost/api/cms/umbraco"

### Expected result / actual result

"ApplicationVirtualPath" should be interpreted correctly by all "JavaScript" pages.

**Comment by nul800sebastiaan** [comment] 2022-03-04 08:37
Thanks for the additional report @a-t-k, I'll close this as a duplicate of #11891 and we'd love some help getting this fixed!

**Closed by nul800sebastiaan** 2022-03-04 08:37 UTC
Labels: type/bug
