### ISSUE TITLE
Multiple package references to Serilog.AspNetCore in v12/dev branch

### ISSUE THREAD

**Issue by matteus-hemstrom-nltg** [umbraco/Umbraco-CMS#15280] opened 2023-11-22 08:46 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.3

### Bug summary

There are two `<PackageReference>` elements for `Serilog.AspNetCore` in the dev branch for v12. One references `7.0.0` and the other `5.0.0`. I think this is due to a mistake in a merge. See:
https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj#L15-L16

### Steps to reproduce

See https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj#L15-L16

**Comment by kjac** [comment] 2023-11-27 10:19
Hi @matteus-hemstrom-nltg,

Thank you for reaching out and for pointing this out ❤️ and not least for digging into the root cause 💪 

We're currently in the process of redoing our package references, so the package versions will be managed in one central file for all projects. We do expect this to be done soon, thus eliminating these silly errors in the future.

The initial PR is here: https://github.com/umbraco/Umbraco-CMS/pull/15293 - it targets V10, but once it's in we'll merge it to the later versions too (taking into account the newer package versions as we progress through the CMS versions).

I'm cross linking your issue to the PR. Hopefully it'll be tracked and auto-closed by GitHub once the PR is merged. 🙈

**Closed** 2023-11-27 14:18 UTC
Labels: state/in-sprint, type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12, affected/v14, affected/v13
