### ISSUE TITLE
Mandatory Properties, in nested content can not be valid

### ISSUE THREAD

**Issue by lucasmichaelsengorm** [umbraco/Umbraco-CMS#10249] opened 2021-05-07 13:13 UTC
A brief description of the issue goes here.
A have a doctype, witch contain a datatype of Nested content, some of thies element do have some mandatory fields.
If you in the section Content, ad the doctype, and add the nested content element, and try to hit Save and published, it does a it suppose, it give a validation error, "Value connet be empty", if you then fix the empty field by adding content to the field, and again hit save and publishe, the error is still continue, when i expected here the content node will be saved and published.

![chrome-capture (1)](https://user-images.githubusercontent.com/69140700/117454622-a07c3c00-af46-11eb-9176-1d04d9dc7ab6.gif)

## Umbraco version
8.13.0

**Comment by emma-hq** [comment] 2021-05-11 12:04
Hey @lucasmichaelsengorm 

Thanks for pointing that out. I'll keep both open in that case and consider them together. 

Emma

**Comment by VargyasMoniLajos** [comment] 2021-05-12 07:10
Hi! We are also seeing this issue, probably since 8.11.x The issue is that when you have a nested content editor, and you add an element that has a required field. When you save the page without adding a value for the required field, it validates, not allowing to save. When you then complete the field, the validation error does not go away, and so you have to reload the page to start again.

**Comment by nul800sebastiaan** [comment] 2021-05-12 09:27
I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8954 

We've fixed the problem for the upcoming 8.14 release (the release candidate will be out next week).

**Closed by nul800sebastiaan** 2021-05-12 09:27 UTC

**Comment by nul800sebastiaan** [comment] 2021-05-25 14:48
I can confirm that for the media picker, this seems to be fixed in 8.14-RC, however I might not have the exact same setup as you so I would love it if you can test this as well @lucasmichaelsengorm. I've set it to Mandatory and requiring at least 1 image to be picked.

**Comment by lucasmichaelsengorm** [comment] 2021-05-25 21:23
@nul800sebastiaan I have teste with the solution where I spotted this issues. It is not quite there yet.
Media Picker, both single and multi works.
Relatede Links (Multi Url picker), both single and multi works.
Dropdown, color picker, textstring, textarea, Content Tree Picker, also works now as expected.

But there is still some issues.

1 - But the rich text editor still have the same issue, where if the error is triggered, when you fix it, then you are stuck as before, the validation error would not go away
![chrome-capture](https://user-images.githubusercontent.com/69140700/119566048-f9ebc400-bdaa-11eb-9b0a-60f262d7f47f.gif)

There is a small work around. So if you trigger multiple errors, as ex here, where color picker and rich text editor has an error, you will need to fix the RTE first and then the color picker, then it wors as kind of expeteded 
![chrome-capture (2)](https://user-images.githubusercontent.com/69140700/119566616-a29a2380-bdab-11eb-9881-5fd89859099d.gif)

2 - So as ex, i have a media picker and related link picker.
Media picker is with data, related link is empty, and I try to publish.
An error will be show there on the Related links property.

If I delete the data from the media picker, so both the Media picker and related Links is empty, and try to hit Publish.
An error is still only being showed on the Related links property.

If I fix the related link property so the Media pick is still empty, and Related is with data, and hit Publish.
The error on the related links property is now gone, and an error would now be showed on the media picker property.
![chrome-capture (4)](https://user-images.githubusercontent.com/69140700/119568014-50f29880-bdad-11eb-8772-1b0e0ecf2aa0.gif)

----

![chrome-capture (6)](https://user-images.githubusercontent.com/69140700/119568182-84352780-bdad-11eb-9173-cca7c699912d.gif)
