### ISSUE TITLE
Override EmailSender class not possible

### ISSUE THREAD

**Issue by brannmark** [umbraco/Umbraco-CMS#13750] opened 2023-01-27 13:34 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.3

### Bug summary

EmailSender implements IEmailSender. Implementing a custom EmailSender is not possible because implementations creates a new EmailSender and not relaying on injection of an IEmailSender.

### Specifics

Due to many different scenarios on SMTP setups, override the EmailSender for all Umbraco internal stuff is vital. There is no way of using certificates on the SMTP with current solution in 8.18.3 for example.

### Steps to reproduce

1. Create a new custom EmailSender that implements IEmailSender
2. Register implementation in Composer
3. Try trigger a mail from Backoffice
4. Default implementation is used instead of custom email sender

**Comment by Zeegaan** [comment] 2023-01-27 13:48
This is unfortunately not really a bug, but wrong by design in v8, so it won't get fixed for v8 sadly.
This has however been addressed in v9, so if its something you need, I'd recommend upgrading to V10 👍

**Closed by Zeegaan** 2023-01-27 13:48 UTC
Labels: type/bug
