### ISSUE TITLE
V8: Contentpicker and Multinode Treepicker can't be saved or submitted.

### ISSUE THREAD

**Issue by SjorsHartwijk** [umbraco/Umbraco-CMS#6420] opened 2019-09-25 09:04 UTC
When using a Contentpicker and or Multinode picker in nested content, it can't be saved.

### Bug summary

I want to create a FAQ page with questions categorized by document type. Each question has: question, answer and category. For category i would like to use the content picker or multinode treepicker (multinode because you can limit the document types).

My questions are defined as nested content in the Document Type so i can add unlimited questions to my FAQ document type. 

### Specifics

Umbraco version: 8.1.5
IDE: Visual Studio 16.2.5
Browser: Google Chrome 77.0.3865.90
Problem occurs in other browsers as well (IE, Edge, Firefox)

### Steps to reproduce

Create nested content type without a template
create properties:
question - textstring
answer - textarea
category - multinode treepicker or content picker
in multinode treepicker: select document types to include from root
in content picker: select root

Content: Create faq page with properties:
title, content and nested content question

Content: create question on FAQ page, fill in question and answer. select category.

### Expected result

when using the multinode treepicker: select the document type and press submit
when using the content picker: select the document type and press submit

### Actual result

when using the multinode treepicker: you can't press press submit, it won't save
when using the content picker: the submit button isn't visible.
![oYuaJGWuds](https://user-images.githubusercontent.com/5611008/65586225-199e6980-df84-11e9-9b51-26e2d4f2abcf.png)

**Comment by nul800sebastiaan** [comment] 2019-09-25 11:23
Hey there @SjorsHartwijk - could it be that you just upgraded from an older version? It seems like something might have gone wrong there. Both scenarios work great for me (see gif below). I'll close this for now. :)

![6420](https://user-images.githubusercontent.com/304656/65596619-87a05c00-df97-11e9-9059-2cf6c64761d6.gif)

**Closed by nul800sebastiaan** 2019-09-25 11:23 UTC

**Comment by SjorsHartwijk** [comment] 2019-09-25 11:27
Flushed all cache, restarted the application and it worked. Thank you!

**Comment by FransdeJong** [comment] 2019-09-25 11:47
There is still something wrong.
Sjors tested this issue again by adding two new properties on a documenttype using the same datatype. That worked, problem solved it seems. But on the old property (Categorie) it still doesn't work. Console throws a string split error.
The strange thing is that when we change the name it works instantly.

So for us the problem is solved now but there is something wrong...

**Comment by nul800sebastiaan** [comment] 2019-09-25 11:48
Make sure to post the error, in case it helps someone else.

Does renaming it back cause the error again?

**Comment by FransdeJong** [comment] 2019-09-25 11:53
Didn't have the error on my pc. Made the error come back. But when we checked it just now to recreate the error it didn't come back. It seems like the property on the DocumentType was somehow cached? I had this issue before in V7 a few years back.

So for now solved I think?

**Comment by sattapaal** [comment] 2019-11-18 12:41
im got exactly this error.  my property was called "Stage Questions", i deleted this property and set it to just "Questions", it worked fine. i then deleted "questions" and called it "stage questions" again and now its working. odd though. i felt compelled to google the Angular javascript errors.
