### ISSUE TITLE
Innitial account can't add roles to own profile

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#5612] opened 2019-06-07 13:54 UTC
As the initial account you can't edit your own groups, content nodes or media nodes.

Umbraco V8.0.2

Reproduction
1. Create a new instance of Umbraco
2. Go to the user section
3. Open you profile
4. See you can't edit groups or nodes.

This is especially problematic when you need access to the Translation section, as the only option is to create a new account with those rights.

**Comment by nul800sebastiaan** [comment] 2019-06-11 05:16
Hi @deMD - there seems to be a small bug here, where the "Add" button is missing for the initial account.

![image](https://user-images.githubusercontent.com/304656/59245341-a82aed00-8c18-11e9-8cfd-03b2d204802a.png)

You can edit user groups though and from there you can add the initial user to any group you want or update the administrators group to have access to the Translation section.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-06-11 05:16
By the way, please make sure to always note the version of Umbraco you're using. This was tested on 7.14.0.

**Comment by deMD** [comment] 2019-06-11 07:21
> 
> 
> By the way, please make sure to always note the version of Umbraco you're using. This was tested on 7.14.0.

Ah sorry, I indeed forgot the Umbraco version, I will update this report and the other reports I did last week. All bugs were obeserved on Umbraco V8.0.2.

**Comment by patrickdemooij9** [comment] 2019-06-12 15:20
@nul800sebastiaan Is this really a bug though? Looking at the code there is a check to see if I am the same person as the one that I am currently editing. If so, the button won't be shown. If I create another account and log in (with administrator rights, so I can get to the users) then I am also not able to add my own groups.

Should the initial user have special permissions like being able to edit their own groups? Or should all administrators have that ability?

**Comment by nul800sebastiaan** [comment] 2019-06-13 07:18
I remember this having some kind of reason, but I can't see a good reason if you can perform the same actions through the user group editors anyway.

I can confirm this is still an issue on 8.0.2.

**Comment by patrickdemooij9** [comment] 2019-06-13 07:21
Oke, I will make a PR to fix it then.

**Comment by nul800sebastiaan** [comment] 2019-06-27 20:06
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5655

**Closed by nul800sebastiaan** 2019-06-27 20:06 UTC
Labels: community/pr, release/8.1.0, type/bug
