### ISSUE TITLE
Umbraco 14 - SSO OpenIDConnect 500 Error: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.

### ISSUE THREAD

**Issue by jovanzlatanovic** [umbraco/Umbraco-CMS#16583] opened 2024-06-10 12:22 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

After upgrading from Umbraco 13 to Umbraco 14, Umbraco can't seem to read my configuration where I've set the metadata address of the openid-configuration.

### Specifics

Metadata is added in the following manner:
```
    backOfficeAuthenticationBuilder.AddOpenIdConnect(
        schemeName, displayName,
        options =>
        {
            options.MetadataAddress = "https://custom-auth.com/openid-configuration";
            // ... other options
        });
```

After clicking the SSO button (added the necessary `ExternalLoginProviders/umbraco-package.json` as in the docs) the following error appears, at the endpoint `/umbraco/management/api/v1/security/back-office/authorize?...`:
```
{
    "type": "Error",
    "title": "Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.",
    "status": 500,
    "detail": "   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Our.Umbraco.StorageProviders.AWSS3.AWSS3FileSystemMiddleware.HandleRequestAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Api.Management.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\\projects\\dotnet\\src\\MiniProfiler.AspNetCore\\MiniProfilerMiddleware.cs:line 112\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)",
    "instance": "InvalidOperationException"
}
```

### Steps to reproduce

Setup SSO with OpenIDConnect metadata HTTPS address:
```
    public static IUmbracoBuilder AddProviderBackofficeAuthentication(this IUmbracoBuilder builder, IConfiguration config)
        builder.Services.ConfigureOptions<ProviderBackOfficeExternalLoginProviderOptions>();

        builder.AddBackOfficeExternalLogins(logins =>
        {
            logins.AddBackOfficeLogin(
                backOfficeAuthenticationBuilder =>
                {
                    backOfficeAuthenticationBuilder.AddOpenIdConnect(
                        schemeName, displayName,
                        options =>
                        {
                            options.MetadataAddress =
                                metaDataAddress;
                                ...
                        });
                });
        });
```

### Expected result / actual result

**Expected result:** Have the login pass.

**Actual result:** Previously mentioned error appears.

**Comment by kjac** [comment] 2024-06-10 12:53
Hi @jovanzlatanovic,

Thanks for reporting this 👍 I'll have a look today or tomorrow.

**Comment by kjac** [comment] 2024-06-11 10:45
So. I can reproduce it for sure. I can get a little further by specifying the known endpoints explicitly instead of relying on auto-discovery (metadata):

```csharp
backOfficeAuthenticationBuilder.AddOpenIdConnect(
  BackOfficeAuthenticationBuilder.SchemeForBackOffice("OpenIdConnect")!,
  options =>
  {
    // options.MetadataAddress = "https://some.where/.well-known/openid-configuration";
    options.Configuration = new OpenIdConnectConfiguration
    {
      Issuer = "https://some.where/",
      AuthorizationEndpoint = "https://some.where/authorize",
      TokenEndpoint = "https://some.where/token",
      UserInfoEndpoint = "some.where/userinfo",
    };
    ....
```

But at least in my current test setup, this only brings about a new world of pain 🤕 

Can you try it and see if it works for you?

**Comment by jovanzlatanovic** [comment] 2024-06-11 11:33
Hi @kjac thanks for confirming! I thought I was going mad.

Specifying the endpoints explicitly got me to the login screen of the external auth and upon logging in I've gotten a new exception:
```
An unhandled exception occurred while processing the request.
ArgumentNullException: IDX10000: The parameter 'token' cannot be a 'null' or an empty object. (Parameter 'token')
```
Here's the full error screen if you'd like the trace as well:

![image](https://github.com/umbraco/Umbraco-CMS/assets/99445204/dd0ab7e4-dcc6-454d-9266-86df39ef2073)

**Comment by kjac** [comment] 2024-06-11 12:04
Thanks for testing @jovanzlatanovic 

That looks exactly like what I ran into. It's caused by a missing ID token. Once you add that, a whole new range of errors occur.

We know for a fact that [`AspNet.Security.OAuth.GitHub`](https://www.nuget.org/packages/AspNet.Security.OAuth.GitHub) and `Microsoft.AspNetCore.Authentication.Google`(https://docs.umbraco.com/umbraco-cms/tutorials/add-google-authentication) work splendidly. We clearly need to figure out how to get a "raw" OpenId Connect configuration working.

I'll take this to the team and see if we can get someone to look at it in the coming weeks 👍

**Comment by jovanzlatanovic** [comment] 2024-06-11 12:26
Thank you very much! 👏

**Comment by kjac** [comment] 2024-06-25 05:06
Hi again @jovanzlatanovic,

First and foremost: We definitively recommend using [dedicated OAuth or OpenIdConnect implementations](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/) for handling external auth. They may be somewhat opinionated, but they also hide away a lot of the really tricky stuff. And OAuth/OpenIdConnect _is_ tricky.

Now, I've been going over this whole thing from scratch, and I do have a "raw" configuration based on `Microsoft.AspNetCore.Authentication.OpenIdConnect` working with Google Accounts.

I _think_ the first thing you should do, though, is to check if you have the same version of all `IdentityModel` NuGet packages installed throughout your solution. This is absolutely necessary and quite annoying, because NuGet can't enforce it 😢 

Try running this in your solution root:

```bash
dotnet list package --include-transitive | sls "Microsoft.IdentityModel|System.IdentityModel"
```

It will likely report different versions of packages, unless you have actively done something to align them. In my V14 test project I had to upgrade `Microsoft.IdentityModel.Protocols.OpenIdConnect` to version 7.5.1 - that aligned the versions of the entire chain of dependencies.

This fixed a lot of the wonky issues for me, but Google still does not supply the necessary token parameters for signature validation, so I had to override that.

I'm enclosing my implementation below. Perhaps it will give you some pointers.

These links might also provide additional info:

- https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events
- https://github.com/dotnet/aspnetcore/issues/52075
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2510

As this does actually work, I'm going to close this issue now.

### Sample OpenIdConnect implementation with Google Accounts

```cs
using System.Security.Claims;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.IdentityModel.Tokens;
using OpenIddict.Abstractions;
using Umbraco.Cms.Api.Management.Security;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Composing;

namespace Umbraco.Cms.Web.UI.Custom;

public class OpenIdConnectBackOfficeExternalLoginProviderOptions : IConfigureNamedOptions<BackOfficeExternalLoginProviderOptions>
{
    public const string SchemeName = "OpenIdConnect";

    public void Configure(string? name, BackOfficeExternalLoginProviderOptions options)
    {
        if (name != Constants.Security.BackOfficeExternalAuthenticationTypePrefix + SchemeName)
        {
            return;
        }

        Configure(options);
    }

    public void Configure(BackOfficeExternalLoginProviderOptions options)
    {
        options.AutoLinkOptions = new ExternalSignInAutoLinkOptions(
            // must be true for auto-linking to be enabled
            autoLinkExternalAccount: true,

            // Optionally specify default user group, else
            // assign in the OnAutoLinking callback
            // (default is editor)
            defaultUserGroups: new[] { Constants.Security.EditorGroupAlias },

            // Optionally specify the default culture to create
            // the user as. If null it will use the default
            // culture defined in the web.config, or it can
            // be dynamically assigned in the OnAutoLinking
            // callback.
            defaultCulture: null,
            // Optionally you can disable the ability to link/unlink
            // manually from within the back office. Set this to false
            // if you don't want the user to unlink from this external
            // provider.
            allowManualLinking: true
        )
        {
            // Optional callback
            OnAutoLinking = (autoLinkUser, loginInfo) =>
            {
                // You can customize the user before it's linked.
                // i.e. Modify the user's groups based on the Claims returned
                // in the externalLogin info

                // see https://github.com/umbraco/Umbraco-CMS/issues/12487
                autoLinkUser.IsApproved = true;
            },
            OnExternalLogin = (user, loginInfo) =>
            {
                // You can customize the user before it's saved whenever they have
                // logged in with the external provider.
                // That is to sync the user's name based on the Claims returned
                // in the externalLogin info

                return true; //returns a boolean indicating if sign-in should continue or not.
            },
        };
    }
}

public class OpenIdConnectBackOfficeExternalLoginComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.ConfigureOptions<OpenIdConnectBackOfficeExternalLoginProviderOptions>();

        builder.AddBackOfficeExternalLogins(logins =>
        {
            logins.AddBackOfficeLogin(
                backOfficeAuthenticationBuilder =>
                {
                    backOfficeAuthenticationBuilder.AddOpenIdConnect(
                        BackOfficeAuthenticationBuilder.SchemeForBackOffice(
                            OpenIdConnectBackOfficeExternalLoginProviderOptions.SchemeName)!,
                        options =>
                        {
                            options.Configuration = new OpenIdConnectConfiguration
                            {
                                Issuer = "https://accounts.google.com",
                                AuthorizationEndpoint = "https://accounts.google.com/o/oauth2/v2/auth",
                                TokenEndpoint = "https://oauth2.googleapis.com/token",
                                UserInfoEndpoint = "https://www.googleapis.com/oauth2/v3/userinfo"
                            };

                            options.CallbackPath = "/umbraco/signin-google"; // whatever you defined as allowed callback URL
                            options.ClientId = "[your client ID]";
                            options.ClientSecret = "[your client secret]";
                            options.Scope.Add("email");
                            options.Scope.Add("profile");
                            options.Scope.Add("openid");

                            options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                            options.ResponseMode = OpenIdConnectResponseMode.FormPost;
                            options.UsePkce = true;

                            // this seems necessary despite matching all package versions
                            options.TokenValidationParameters.SignatureValidator = (token, parameters) => new JsonWebToken(token);

                            // this ensures that the user name is in ClaimTypes.Name, as it is necessary for auto linking
                            options.Events.OnTokenValidated = async context =>
                            {
                                if (context.Principal is null || context.Principal.Identity?.Name is not null)
                                {
                                    return;
                                }

                                var name = context.Principal.GetClaims("name").FirstOrDefault();
                                if (name is null)
                                {
                                    return;
                                }

                                context.Principal.SetClaim(ClaimTypes.Name, name);
                            };
                        });
                });
        });
    }
}
```

**Closed by kjac** 2024-06-25 05:06 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, affected/v14

**Comment by jovanzlatanovic** [comment] 2024-06-27 14:09
Hi @kjac, you're a lifesaver, thank you very much for the extremely detailed response and thourough investigation. 🙏 

After explicitly setting the configuration and adding some additional lines from your example (SignatureValidator, ResponseMode...) I've managed to get to the actual authentication page after which an error appeared upon successful login for a version missmatch of the `Microsoft.IdentityModel.Protocols.OpenIdConnect` package.

Going through transient dependencies and upgrading `Microsoft.AspNetCore.Authentication.OpenIdConnect` to `8.0.6` and explicitly installing `Microsoft.IdentityModel.Protocols.OpenIdConnect 7.5.1` the login page worked like a charm!

Only issue I've encountered is that since I've prevously had SSO enabled the "Umbraco.OpenIDConnect" schema was already added and I was able to fix the issue by changing the schema name (since I didn't want to mess around modifying Umbraco tables).

**Comment by Joe-Spadea** [comment] 2024-09-24 00:59
@kjac - I owe you a beer! Simply making sure the package versions were consistent fixed all the buggy/broken behavior I was facing. Thank you!!!

**Comment by bendickman** [comment] 2024-09-24 10:51
@kjac & @jovanzlatanovic - thank you both, you've saved me a big headache trying to figure this out.

I updated from v13.3.2 to 13.5.1 and had similar issues.

**Comment by oxioquadhenke** [comment] 2024-10-24 08:41
@kjac & @jovanzlatanovic  Thank you saved me a big hedache to, this applies to security path 13.5.1 as well. Only had to align the Microsoft.IdentityModel.Protocols.OpenIdConnect versions. We are using Entra Id.

**Comment by biapar** [comment] 2024-10-24 21:30
Have you updated the Umbraco docs?
