### ISSUE TITLE
Save and Preview blank on second use

### ISSUE THREAD

**Issue by dhedgepeth** [umbraco/Umbraco-CMS#14052] opened 2023-04-03 19:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.2 (also tested on 11.2.2)

### Bug summary

If you have a project with more than 1 language available, and you open the "Save and Preview" tab twice, the second time it will be completely blank. 
![image](https://user-images.githubusercontent.com/29805065/229612019-6a356938-16fd-4122-af09-ff119f67300b.png)

### Steps to reproduce

1. Create a document type with template.
2. Add some content to template to test save and preview
3. Add a new language under "Languages" in Settings 
4. Create new content page from doc type 
5. Click "Save and preview"
6. Go back to backoffice and click "Save and preview" again **do not close first save and preview tab**

After clicking Save and preview the second time you'll be greeted by a blank white screen.

### Expected result / actual result

Expected result:
Preview of front end

Actual result:
Blank white screen

**Comment by kjac** [comment] 2023-04-11 12:09
Hi @dhedgepeth,

Thank you for reporting this 💪 I can reproduce this on V10 and V11. It looks like the `id` query string parameter disappears the second time around. Interestingly enough it re-appears (and works) if you click "Save and preview" three times (and disappears again the fourth time 😆).

The only effective workaround is to close the preview tab.

I'll mark this as up for grabs, in case you or someone else would like to have a look at fixing it.

Just to clarify, this _only_ happens for multi-lingual content items. The steps to reproduce can be boiled down as follows:

1. On a multi-lingual content item hit "save and preview" (it doesn't matter if the content item has a template or not).
2. Without closing the preview tab, go back to the back-office tab and hit "save and preview" again.
3. The preview tab reloads and is blank. Notice how the `id` parameter is gone from the querystring.

**Closed** 2023-04-21 09:27 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11, affected/v12

**Comment by nul800sebastiaan** [comment] 2023-04-21 09:29
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14094
