### ISSUE TITLE
Multi Url Picker error returns null for the URL (umbracoapi/entity/GetUrl)

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco-CMS#10844] opened 2021-08-12 15:02 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

Using Multi Url Picker and picking a node will save correctly, however on load fails to load URL with and error and shows `null` for the URL.

`https://localhost:44387/umbraco/backoffice/umbracoapi/entity/GetUrl?udi=umb%3A%2F%2Fdocument%2Feb709196aa5d4f63aaf9f3cecd7abf04&culture=`

![Screenshot 2021-08-12 180037](https://user-images.githubusercontent.com/3933562/129220055-1c646766-e306-441e-941e-5139adcb6dd2.jpg)

### Specifics

https://our.umbraco.com/forum/umbraco-9/106194-multi-url-picker-is-loosing-the-stored-reference-in-umbraco

### Steps to reproduce

1. Add Multi Url Picker as a property
2. Pick a node 
3. Save document 
4. Refresh document

### Expected result / actual result

Expected to see local link to the node and not get the error.

**Comment by cleversolutions** [comment] 2021-08-12 19:02
This looks like a duplicate of #10694 which is fixed in rc2.

**Comment by nul800sebastiaan** [comment] 2021-08-13 07:12
Thanks @cleversolutions, that's right, this is fixed, you can use a nightly build from myget now if this is a blocker @konius. I think RC2 won't take much longer though.

**Closed by nul800sebastiaan** 2021-08-13 07:12 UTC
Labels: type/bug
