### ISSUE TITLE
"You have unsaved changes" pop-up after save of build-in-field

### ISSUE THREAD

**Issue by sk-teasolutions** [umbraco/Umbraco-CMS#14103] opened 2023-04-17 07:11 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.7

### Bug summary

I have a Date Picker field at my member (in the Member section), and when I pick a date and click save I still get the "You have unsaved changes" pop-up when I try to leave the page.
If I just updates the page the new value is still displayed in the Date Picker, so the value gets saved when I click "save".
If I update other fields the problem doesn't occur - it's only the Date Picker field that's not working as expected.

I also experienced the problem at Umbraco version 8.11.1 and the update to 8.18.7 didn't fix the problem.

### Specifics

I've tested in both Chrome and Firefox and both browsers gives me the pop-up.

### Steps to reproduce

1. Add a "Date Picker" field to a member type (image below with the settings)
2. Go to a member and fill in a date
3. Save the member
4. Try go somewhere else

![image](https://user-images.githubusercontent.com/80882513/232410641-8c4a022a-8d88-4db0-ab52-020336176f73.png)

**Comment by elit0451** [comment] 2023-04-17 13:33
Hi @sk-teasolutions 👋 

Unfortunately, we don't provide fixes for bugs that aren't regression issues for Umbraco 8 (_we broke something in a recent version_) since it is in the support phase at the moment. 

As the problem dates back to 8.11.1 and I cannot replicate it in the latest Umbraco 10 (_10.5.0_) or 11 (_11.3.0_) I will go ahead and close this issue. We recommend looking into upgrading.

**Closed by elit0451** 2023-04-17 13:33 UTC
Labels: type/bug

**Comment by sk-teasolutions** [comment] 2023-04-18 05:35
Hi @elit0451 

As I understand from [https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-8-end-of-life-eol/]here, it should still be supported until next year

**Comment by elit0451** [comment] 2023-04-18 06:19
Yes, you are correct, but since the issue you are experiencing was present already in Umbraco version 8.11.1, it is not a regression issue (_it wasn't caused after v8.15_). And as I said it doesn't seem to be present in the latest Umbraco 10 (10.5.0) or 11 (11.3.0), so there is nothing we can do here unfortunately 🤷‍♀️
