### ISSUE TITLE
[v14] Infinity editing of Document Type from Content section seems broken

### ISSUE THREAD

**Issue by RBerntsen** [umbraco/Umbraco-CMS#16581] opened 2024-06-10 09:33 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When I click on the link to the document type directly from the content (so from the General under Info) nothing happens.

### Steps to reproduce

I made a clean installation of v14 running locally. Default configuration on a windows machine. Running in debug from VS 2022.

I have created a basic document type:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/90b0535f-ffd7-4875-8a90-28da23f6ea72)

Allow at root:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/3c1dd370-d8ed-4aa3-b22b-6232f668cc1a)

I have created that page in the root of the website. When I then try and navigate to edit the document type from there nothing happens:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/2b4ffff9-af73-439d-8144-f955fc79132f)

The URL in the browser changes to:
https://localhost:44319/umbraco/edit/bf045bf7-d6cb-46fb-9f7f-461b392b33de

But nothing else happens:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/0ed5f987-2b0b-4297-959d-b22e8c9acd50)

If I follow the URL myself in a new tab I get a 404:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/1731f42b-2e1e-46c8-bf48-25a021cb7ada)

When I navigate directly to the document type the URL looks different:
https://localhost:44319/umbraco/section/settings/workspace/document-type/edit/bf045bf7-d6cb-46fb-9f7f-461b392b33de/view/design/root

### Expected result / actual result

I would expect that it's possible to click on the document type from content and edit the type directly from there.

**Comment by nikolajlauridsen** [comment] 2024-06-10 11:09
Hey @RBerntsen thanks for reporting, I can reproduce this in the 14.0 template, however, it seems to be fixed in the latest dev branch, so a fix should be out in 14.1, thanks for reporting 🐛🕵️

**Closed by nikolajlauridsen** 2024-06-10 11:09 UTC
Labels: type/bug
