### ISSUE TITLE
Error adding custom property editor

### ISSUE THREAD

**Issue by szabolaszlo90** [umbraco/Umbraco-CMS#14865] opened 2023-09-26 09:42 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 12.1.2

### Bug summary

I would like to add a custom property editor to umbraco. I prepared the editor, but when I use the editor, I unfortunately get an error. The error message is as follows
Could not load content for https://localhost:44351/umbraco/lib/angular/angular.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

### Steps to reproduce

I made it based on umbraco's documentation:
https://docs.umbraco.com/umbraco-cms/extending/property-editors

**In the first step, I made the controller of the unique editor.**

(function () {
    'use strict';
    function AnchorLinkController($scope)
      {
       var vm = this;
       vm.inputValue = '';   
       vm.generatedId = ''; 

      **$scope.$watch('inputValue', function (newValue, oldValue) {
              if (newValue !== oldValue) {
                vm.generatedId = generateValidId(newValue); // Update the generated ID
          }
      }); -> Presumably, the error may stem from this.** 
 
     
      /// Here is logic
     }
    angular.module('umbraco').controller('AnchorLinkController', AnchorLinkController);
})();

**The view to it:**
<div ng-controller="AnchorLinkController as vm">
    <input type="text" id="idInput" ng-model="vm.inputValue" placeholder="Enter ID">
    <div>
        <strong>Generated Anchor Link:</strong>
        <span>{{vm.generatedId}}</span>
    </div>
</div>

**Then I'll add the _package.manifest_ file.**

{
  "propertyEditors": [
    {
      "alias": "Anchor link",
      "name": "Anchor Link",
      "icon": "icon-list",
      "group": "Common",
      "editor": {
        "view": "~/App_Plugins/AnchorLink/anchorlink.html"
      }
    }
  ],

  "javascript": [
    "~/App_Plugins/AnchorLink/anchorlink.controller.js"
  ]
}

Then I start umbraco. I add the new editor and the function does not work because it could not find angular.js.

![image](https://github.com/umbraco/Umbraco-CMS/assets/146074763/393ac933-ddb7-443c-b507-2d5ea0384823)

The error message is:
Could not load content for https://localhost:44351/umbraco/lib/angular/angular.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

### Expected result / actual result

I would like this problem to be solved and to be able to easily add individual property editors.

**Comment by bjarnef** [comment] 2023-09-27 07:28
@szabolaszlo90 could you eventually show the full code of controller and view?

```
```

**Comment by szabolaszlo90** [comment] 2023-09-27 08:13
@bjarnef of course I can show you the other code details.

The controller:
(function () {
    'use strict';

    function AnchorLinkController($scope) {
        var vm = this;
        vm.inputValue = '';      // Initialize the input value
        vm.generatedId = '';    // Initialize the generated ID

        //Watch for changes in the input value
        $scope.$watch('inputValue', function (newValue, oldValue) {
            if (newValue !== oldValue) {
                vm.generatedId = generateValidId(newValue); // Update the generated ID
            }
        });

        //Function to ensure the uniqueness of an ID
        function ensureUnique(id) {

            //Gather the values of "id" attributes on elements currently present in the page.
            const existingIds = Array.from(document.querySelectorAll('[id]')).map(element => element.id);

            //Check if the ID already exists on the page; if yes, add a unique identifier.
            if (!existingIds.includes(id)) {
                return id; // The ID is unique; return it as is
            }

            let uniqueId = id;
            let counter = 1;

            //Add a unique identifier until a unique ID is found.
            while (existingIds.includes(uniqueId)) {
                uniqueId = id + "_" + counter;
                counter++;
            }

            return uniqueId;
        }

        //Function to generate a valid ID
        function generateValidId(inputValue) {
            if (/^\d/.test(inputValue))
            {
                inputValue = "nf_" + inputValue; //Prepend "nf_" if it starts with a number
            }

            inputValue = inputValue.toLowerCase().replace(/[^a-z0-9_]/g, "_"); //Replace non-valid characters with underscores

            return ensureUnique(inputValue); //Ensure uniqueness and return the ID
        }
    }

    angular.module('umbraco').controller('AnchorLinkController', AnchorLinkController);
})();

The view:
![image](https://github.com/umbraco/Umbraco-CMS/assets/146074763/8e4859df-8d4b-4fd2-a0e4-63578beb3e3f)

**Comment by szabolaszlo90** [comment] 2023-09-27 11:52
@bjarnef 
Thank you very much for your help. The problem is solved :)

**Comment by andr317c** [comment] 2023-09-28 08:19
Hey, I am glad to see the problem is solved! Thank you Bjarne for providing help 💪 I'll go ahead and close this issue.

**Closed by andr317c** 2023-09-28 08:19 UTC
Labels: type/bug
