### ISSUE TITLE
v9-beta004: Initial Backoffice tour gets lost..

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#10570] opened 2021-07-01 11:25 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-beta004

### Bug summary

Initial tour of the backoffice got to users (no next button on the dialog)

Then resumed and got this.
![Screenshot 2021-07-01 122241](https://user-images.githubusercontent.com/12418214/124116624-12649380-da67-11eb-863d-e0e515522fed.png)

Starting the tour again from the help sidebar.. get to the user step
![image](https://user-images.githubusercontent.com/12418214/124117324-e564b080-da67-11eb-94e7-a60a1ee83c0f.png)

### Steps to reproduce

Simply followed the v9 install here https://our.umbraco.com/documentation/UmbracoNetCoreUpdates#umbraco-9-net-core-beta
and first run started to walk through the backoffice tour.

### Expected result / actual result

Completed the tour without getting "lost" ;-)

**Comment by nikolajlauridsen** [comment] 2021-07-05 11:15
Hi @mistyn8, thanks for letting us know, but I can't seem to reproduce, the tests run without issues for me. 

There is not supposed next button on the dialog, if you click your user avatar a side panel will open and you will be on to the next step. 

In regards to getting lost, it seems like the tour will get lost both in v8 and v9 if you start the tour when the dashboard doesn't show, for instance if you start the tour while creating a content node

**Comment by nikolajlauridsen** [comment] 2021-07-05 11:41
I've made a PR which should fix the tour getting lost when the dashboard isn't whown, so I'll go ahead an close this issue, please don't hesitate to comment here if you're still having issues with the introduction tour.

**Closed by nikolajlauridsen** 2021-07-05 11:41 UTC
Labels: project/v9, type/bug

**Comment by mistyn8** [comment] 2021-07-05 11:50
Added a video for clarification.
each of the steps 1-6 have a next button.. step 7 users is missing it?? So can never get to step 8??

https://user-images.githubusercontent.com/12418214/124467216-76e96080-dd8f-11eb-8dc4-a378e53a726e.mp4

**Comment by nikolajlauridsen** [comment] 2021-07-05 12:01
I don't think it should, we need the user to click the avatar to be able to go on with the tour. More generally speaking it can be said that the tour steps serve two different purposes, step 1-6 is about showing the user different options, whereas step 7 is about getting users to perform an action to see what they result in, this can be seen more clearly in the other tours, like creating document type. 

Step 7 is not the only step that does not have the next button, following steps also require users to interact with the site. 


https://user-images.githubusercontent.com/16456704/124468545-85d51080-dd99-11eb-8468-b2ce0e72267e.mp4

**Comment by mistyn8** [comment] 2021-07-05 13:49
That makes sense.. 
However, have you tried navigating with just the keyboard though?? (next buttons easy to access... the directed go click somewhere I couldn't tab too easily?)

**Comment by nikolajlauridsen** [comment] 2021-07-06 12:06
Admittedly no, that seems like something very different from this issue though, and since the front end hasn't changed for V9, that is something that should be reported for V8, and then merged up to V9.  If you think the tab order is incorrect I'd recommend creating an issue targeting V8, it might be a good case for a community PR if that is the case though.
