### ISSUE TITLE
Group picker dialog is showing beneath public access dialog

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#5725] opened 2019-06-26 11:24 UTC
I resized my window to document some other issue, and noticed that the group picker dialog opened in the public access dialog is showing beneath the public access dialog, making it harder to select the right group to protect.

![billede](https://user-images.githubusercontent.com/3726467/60176109-a9156e80-9815-11e9-9ada-6576254549bc.png)

**Comment by nul800sebastiaan** [comment] 2019-06-26 11:30
Thanks! This is a duplicate of: https://github.com/umbraco/Umbraco-CMS/issues/5603

**Closed by nul800sebastiaan** 2019-06-26 11:30 UTC
