### ISSUE TITLE
Multi URL Picker doesn't display culture variant URL in backoffice

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/Umbraco-CMS#7114] opened 2019-11-09 17:44 UTC
When picking a content URL in the Multi URL Picker in a multilinguagl website the default language URL is displayed in the backoffice instead of the culture variant URL:

![image](https://user-images.githubusercontent.com/161342/68532473-eb9b9b80-031d-11ea-93ca-be73dd7d5d21.png)

## Umbraco version: 

I am seeing this issue on Umbraco version: 8.2.2

Reproduction
------------

Add two (or more) languages to the website with one default:

![image](https://user-images.githubusercontent.com/161342/68532517-5cdb4e80-031e-11ea-8db2-2ef606c24833.png)

Add a document type with **Allow varying by culture** enabled and add a Multi URL Picker property to this document also with **Allow varying by culture** enabled:

![image](https://user-images.githubusercontent.com/161342/68532534-a0ce5380-031e-11ea-8b39-017cf5b68de1.png)

Add internal content links to the page in the non-default language:

![image](https://user-images.githubusercontent.com/161342/68532473-eb9b9b80-031d-11ea-93ca-be73dd7d5d21.png)

The property shows the URL's for the default language instead of the culture variant URL, this is very confusing for the editors. When rendering the links in a view (frontend) it does show the proper culture variant URL, so it's only an issue of the backoffice.

I've found similar issues in Github. In issue [#6145](https://github.com/umbraco/Umbraco-CMS/issues/6145) @nul800sebastiaan states this issue was fixed in Umbraco 8.1.4, but I'm still seeing it in version 8.2.2. I've also tried it on a clean install which you can download here (backoffice credentials are in the readme.txt):

https://www.dropbox.com/s/h5hhsztgxv9bvpm/umbraco-822.zip?dl=0

**Comment by kjac** [comment] 2019-11-10 06:35
Well that's weird! I did #6109 to fix this a while back. I'll investigate why this doesn't apply anymore 👍

**Comment by creativesuspects** [comment] 2019-11-11 08:26
This is the data that /umbraco/backoffice/UmbracoApi/Content/GetById?id= returns:

![image](https://user-images.githubusercontent.com/161342/68572293-5dcac800-0465-11ea-986e-3197ffbb9eba.png)

**Comment by kjac** [comment] 2019-11-11 09:21
@creativesuspects I did some research last night and I can reproduce. The issue is a bit more complex than I thought, and the original solution from #6109 is no longer applicable. It also entails redoing the way the property editor fetches existing URLs. Not undoable, it will just take a bit more time.

**Comment by nul800sebastiaan** [comment] 2019-11-11 18:37
Thanks @kjac for looking into this! If you have some thoughts on how this could be fixed feel free to post them, sounds like something we would want to look in to!

**Comment by kjac** [comment] 2019-11-11 21:12
@nul800sebastiaan I've got it fixed, will verify tomorrow and submit a PR for it 👍

**Comment by creativesuspects** [comment] 2019-11-11 21:52
@kjac Awesome! Let me know if you need me to do some testing as well. Also, do you think you could provide a hotfix that I can use until the next release comes out?

**Comment by kjac** [comment] 2019-11-12 07:10
PR in #7130. This I'm afraid isn't hotfix-able 😄

**Comment by creativesuspects** [comment] 2019-11-27 14:38
@nul800sebastiaan Did you get a chance to check the fix? And do you have any idea if and when this will be merged into a release?

**Comment by emmaburstow** [comment] 2020-01-17 12:59
Fixed in #7130 :)

**Closed** 2020-01-17 12:58 UTC
Labels: type/bug

**Comment by ronaldbarendse** [comment] 2020-01-30 21:54
Please make sure to include https://github.com/umbraco/Umbraco-CMS/pull/7543 before releasing Umbraco 8.6.0, as PR https://github.com/umbraco/Umbraco-CMS/pull/7130 contains a bug causing all Multi URL Pickers containing a single external URL to completely stop working.
