### ISSUE TITLE
Notify when (or prevent) multiple users  editing a page at the same time

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [umbraco/Umbraco-CMS#5025] opened 2019-03-19 17:06 UTC
We have 20+ editors - and run into problems where more than one editor is editing a page at the same time ( they will have a batch of pages to change between them; they are situated across different locations, and if there is a tight deadline everyone pitches in to help). They often accidentally overwrite each other's changes, and therefore work is lost (which then makes the time pressures worse). 

It would be helpful if Umbraco could either:

-  create an alert when more than one user has that page open
- or have a 'page locked for editing' function - so that:

-  editors know if someone else is editing the page.
- edits are not lost or overwritten

It would also need the ability to'unlock' the page for editing eg when someone has been called away mid-edit. 

This feature request has been talked about in the past - https://issues.umbraco.org/issue/U4-6317. Does any one know if this idea was it abandoned (too difficult / or not enough interest / or volume of people with the same issue) or is it still in-play somewhere?

Concierge or MyLocks tools were depreciated in V7.

We are using Umbraco v7.13.2 btw

**Comment by sleslie321** [comment] 2019-03-19 21:59
+1

**Comment by nul800sebastiaan** [comment] 2019-05-03 14:04
Hey there @HistoricEnglandDigitalTeam and thanks for bringing this up again. It's still functionality we'd love to have and as you can imagine this is a big feature to build. 

We've outlined how we think it should work in this comment: https://issues.umbraco.org/issue/U4-6317#comment=67-45995

At HQ we don't currently have this listed as one of our highest priorities but we will be happy to look at a new attempt for a PR for this functionality in v8. Note that we expect there will be several rounds of feedback before it can be added to the core properly. 

Alternatively, as others have done before, it is possible to build this as custom functionality as a plugin for Umbraco,

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-09-04 09:17
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-09-04 09:17 UTC
Labels: community/up-for-grabs, help wanted, type/feature

**Comment by Sven883** [comment] 2021-01-20 11:30
Hey @nul800sebastiaan, is it possible to re-open this issue? It's for sure a function that a lot of Umbraco websites with multiple content editors need. I've been looking for a solution for this but haven't found any packages for this issue.

**Comment by nul800sebastiaan** [comment] 2021-01-20 16:11
@Sven883 This is not on our roadmap to implement in the foreseeable future so we'll keep this issue closed until someone is planning to create a pull request according to the specifications as described in the related issue.

**Comment by melvinvanrookhuizen** [comment] 2021-02-09 15:52
@nul800sebastiaan @Sven883 @sleslie321 @emmaburstow   I know this is closed, but we are about to share a 'needs-a-little-love' version of a check-in/check-out package in a week or 2. We need to do some polishing before it's presentable, but it's working. We will keep on working on it, but will also be open for collaboration.

**Comment by SRandomName** [comment] 2021-03-01 12:01
@melvinvanrookhuizen - Any update on this ?

**Comment by Wolfkhan66** [comment] 2021-03-03 10:59
@melvinvanrookhuizen - Just wanted to add that we are also very interested in this.

**Comment by fbenyah** [comment] 2021-09-21 13:08
Older versions had this feature not sure why it got dropped.
Definitely will be useful to have it back because this is a one of those questions that come up 9/10 presentations we do with umbraco as a solution for enterprise content management.

It makes sense that it is not needed in most small to medium sites but in larger sites with multiple editors, multiple time zones on multiple devices this is one of the places where umbraco falls short compared to other enterprise solutions

**Comment by SupremeOverlordTheFirst** [comment] 2023-09-13 06:17
Not having this feature is definitely a big blocker for enterprise content management. 
We are trialing Umbraco, and this has been raised by the content teams as the biggest shortcoming.

**Comment by HistoricEnglandDigitalTeam** [comment] 2023-09-13 09:01
we still have the same issue! The third party tool which makes an editor check out a page before editing, and then check it back in again, is not suitable and we had to ditch it. It slowed down the editing process considerably and ended up making the content teams' life much harder, rather than better.

**Comment by russellshome** [comment] 2023-10-31 19:41
Just a thought about this since the link to "how we think it should work" is no longer available...

On edit action you could store the current property values in Session and compare on save. If different then you could allow the overwrite and notify the editor that an overwrite happened and who the editor is whose work was overwritten.

While this does not stop overwriting it does improve the situation by informing editors who might otherwise be overwriting each others work without knowing.

**Comment by tcmorris** [comment] 2023-12-12 09:53
Adding a thought here, but with the introduction of Umbraco Workflow and 'Content Lock' being a feature in the free version of that add-on, perhaps the need for this in the core is no longer needed and should remain closed. 

There are of course other features within Umbraco Workflow that for content teams with multiple editors, hopefully the needs for enhanced content flows can be achieved by simply installing that add-on.

**Comment by Shadewing666** [comment] 2024-05-22 03:16
This seems a bit dead but it is functionality that would be very useful for my team at work.
I have no idea how to go about implementing this but I would point out that Content Lock that tcmorris refers to above is described as "Prevent edit on content pending approval", which is not what is being talked about here.

An idea of what the feature could look like, from my point of view as a user, would be something like Microsoft's Sharepoint "check out" system. Where a file must be checked out to be able to edit it and while it is checked out but one user, another use can view the file but not check it out themselves. It also informs the second user of the username of the first user, and provides the option to notify the first user that the second user would like to check out the file.
