### ISSUE TITLE
V9 - Wrong document type on the "create" button when both "parent" node and "son" node are "Enable list view"

### ISSUE THREAD

**Issue by malkag** [umbraco/Umbraco-CMS#12482] opened 2022-05-25 09:50 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

When having 2 hierarchical doc-types that "Enable list view", the "create" button in the "child" node, shows the doc-type which is allowed for the "parent" (instead of showing the allowed doc-types of the "child")
[happens also on 9.4.3]

### Specifics

Lets assume this doc-type hierarchy:
-- filters - root
---- filters - category
------filters - filter

both "filters root" and "filters category" are "Enable list view".

When trying to create child node for the "filters category", the create button show "Create Filers - Catogory" instead of "Create Filters - Filter

https://user-images.githubusercontent.com/19535838/170232209-6cb45483-d8f3-4c8f-945f-acb30dd712b0.mp4

If I disable the list view option for the parent, the create button of the child will show the right doc-type

https://user-images.githubusercontent.com/19535838/170232572-b390a1f6-e274-439e-9d85-8f0aa0a97d8c.mp4

### Steps to reproduce

1. Create doc-type hierarchy as described
2. Create a "parent" node (of type "filters -root")
3. Under this parent, create a "child" node (of type "filters -category")
4. On the "Child items" tab of the child node, you will see it's "create" button with the wrong document type

### Expected result / actual result

The "create" button on the "child" node shouls show the doc-type the is allowed to it (and not to it's "parent")

**Comment by Zeegaan** [comment] 2022-12-29 11:12
Hey @malkag and sorry for the late answer here 😅!
I'm trying this out on V10 (as V9 is EOL) and cannot reproduce this.
When trying to create a grandchild node, it no longer opens the infinite editor, and thus is no longer a problem, demonstration here: 
![CanCreateDoubleListView](https://user-images.githubusercontent.com/70372949/209943206-0143b346-2193-4473-9a53-786e59d4584f.gif)

Since this is a long time ago, I will close this for now, but do not hesitate to re-open it, if you can still reproduce this or run into it again, then we'll have a look again 💪

**Closed by Zeegaan** 2022-12-29 11:12 UTC
Labels: type/bug
