### ISSUE TITLE
Umbraco.Blocklist problem when reordering items contain richtext. 

### ISSUE THREAD

**Issue by ltyczka** [umbraco/Umbraco-CMS#14091] opened 2023-04-13 11:56 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.1, 10.5.0

### Bug summary

The items used in Umbraco's BlockList contain RichText editors. When I reorder the elements of the list while they are expanded, the RichText content disappears.

### Steps to reproduce

1. Create a page with RichText.
2. Create another page with the property Umbraco.BlockList and include the previously created page in the available blocks.
3. Create a page with Umbraco.BlockList.
4. Add at least two elements to that list.
5. Expand one of the elements.
6. Reorder the elements.
7. Observe the result.

In the GIF below, you can see the last two steps demonstrated.

![problem](https://user-images.githubusercontent.com/103414371/231751043-1d199d25-badb-4cf8-b6b5-a0e342584012.gif)

### Expected result / actual result

The content of RichText should always be visible.

**Comment by kjac** [comment] 2023-04-14 09:04
Hi @ltyczka,

Thank you for reporting 👍

This is a known issue; see #12906. The only known workaround at the moment is to configure the block list editor without the "Inline" option:

![image](https://user-images.githubusercontent.com/7405322/231998279-ee9fb633-5c30-4c7b-bf2e-7a66a5ff50d4.png)

I'm closing this as a duplicate of #12906. All future communication regarding this issue will be kept at #12906.

**Closed by kjac** 2023-04-14 09:04 UTC
Labels: type/bug
