### ISSUE TITLE
Umbraco 8 very slow modifying a document type

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#7756] opened 2020-03-04 12:03 UTC
I have an Umbraco 8.5.3 with lots of content and media items.
My examine index goes like 15512 documents
Published cache status: Database cache is ok. ContentStore contains 8898 items and has 1 generation and 1 snapshot. MediaStore contains 4341 items and has 1 generation and 1 snapshot.

At first everything was ok when site was empty but since we have that many content modifying (ie adding a property) a document type goes sometimes about a minute when saving. And sometimes it gets a timeout error. 
Creating an empty document type is very slow too. Deleting it too.
I think it is every document type operation related.
The rest, creating and saving content and media goes very fast.
The site loads very well, only problem at the backoffice when saving a document type.
I have tried removing custom code but the problem keeps happening.
I have Models builder disabled. And create the document types without template.
The problem happens both on my local dev machine (windows 10, sql express) and on azure web app with sql azure.

---
_This item has been added to our backlog [AB#5773](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5773)_

**Comment by renaldas** [comment] 2020-03-09 09:12
Same issue happens for me, just I'm not importing anything, clicking refresh "Memory Cache" breaking the website.

**Comment by nul800sebastiaan** [comment] 2020-03-09 09:15
@renaldas Can you elaborate? how much content and how many media items do you have? What breaks?

**Comment by renaldas** [comment] 2020-03-09 09:21
@nul800sebastiaan around 200 pages and 500 media items and it breaks rendering of images.

System.NullReferenceException: Object reference not set to an instance of an object. - when trying to get image from nested content item.

**Comment by nul800sebastiaan** [comment] 2020-03-09 10:47
@renaldas - Thanks, that specific TreeNodeLocked issue has been fixed and will be part of the 8.6.0 release coming later this week (https://our.umbraco.com/download/releases/860) - see the related issue + PR for more info https://github.com/umbraco/Umbraco-CMS/issues/6758

**Comment by teeto** [comment] 2020-03-17 11:59
Hi @nul800sebastiaan , i need to solve this issue as soon as possible, i have tried 8.6.0 release candidate with no luck.
Will it be fixed on the final 8.6.0 release? when will it be ready to download? the release date was set for last friday but it seems delayed and now no release date is set :(

**Comment by nul800sebastiaan** [comment] 2020-03-17 15:02
@teeto I don't think I ever gave you a clear reply on this, sorry about that. We have limited time and people and that unfortunately doesn't allow us the luxury of immediately looking into an issue that has only been reported by 1 person. 

We are always interested in improving performance when we identify an issue with it but that takes a bit of time I'm afraid. First this needs to be reproduced, which can be quite hard with performance issues and then we need to figure out what we can do about it.

So for now, I am going to have to encourage you to have a look at trying to see if you can do some profiling yourself, maybe you can pinpoint the issue and we can pick it up quite quickly.

I can't give you a timeline as to when we can look into this properly, but if you have more information on where we could look then that would help getting it fixed faster.

**Comment by nul800sebastiaan** [comment] 2020-03-17 15:08
As for the 8.6.0 release, we have had to focus on a security release first (https://umbraco.com/blog/security-advisory-17th-of-march-patch-for-your-site-is-now-available/)  and of course everybody at the company is currently dealing as best we can with the changing circumstances resulting from the corona virus pandemic. Therefore we have had to delay the release of 8.6.0 final until at least next week, it's currently difficult to give an exact date.

**Comment by teeto** [comment] 2020-03-17 16:51
Thanks for your answer @nul800sebastiaan , i thought you fixed this issue and would be on 8.6.0 version as you said on your message above: https://github.com/umbraco/Umbraco-CMS/issues/7756#issuecomment-596454903
I understand that it is going to be delayed becouse of current circumstances, but is there a way i could try that fix you commented without waiting for the official release? may be downloading from some fork on github repository?

**Comment by nul800sebastiaan** [comment] 2020-03-17 17:20
@teeto Ah sorry, I thought you were hoping the original issue was fixed. The specific `TreeNodeLocked` issue is already in the RC so if that doesn't work for you then there must be something else going on. I would encourage you to double check that the RC dlls are in the bin folder of the site that you're experiencing the problem with. If that is already the case then I'm afraid there's more going on in your site that will require an investigation.

**Comment by teeto** [comment] 2020-03-17 19:05
@nul800sebastiaan RC is not solving my issue. I have downloaded the 8.6.0 source code and change connection string to my database. I can see the error is in this class:
https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.0/src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs

At line 1034 on the AddTreeNodeLocked function and the reason is parent variable is null.
I dont know why it is null. I have fixed it setting:
if (parent == null) return;

But i dont know if it can bring other issues.

**Comment by teeto** [comment] 2020-03-18 16:50
Finally i solved my issue. 
I have explained in the related issue here: https://github.com/umbraco/Umbraco-CMS/issues/7766
And now it seems modifying a document type is slow but not that much (10-15 sec) as i dont get timeout (the error really was a AddTreeNodeLocked issue).

What i dont know what the AddTreeNodeLocked has to do if in a future parent variable is null.
I dont know if the line if (parent == null) return; is fine to add to do a pull request as i dont fully understand the process.

**Comment by Shazwazza** [comment] 2020-04-01 00:01
@teeto I'm looking into all of this now but there's a lot of information here and on #7766 that I'm trying to understand. There's also a new issue logged #7868 which is the same issue as far as i know. 

Can I ask you to read my comment here? https://github.com/umbraco/Umbraco-CMS/issues/7868#issuecomment-606949239 and reply there with any answers to my questions? And hopefully you might have the info on replication steps I've mentioned. 
Thanks!

**Comment by teeto** [comment] 2020-04-01 16:11
Thanks @Shazwazza , i have just read your comment and posted a reply there.

**Comment by Shazwazza** [comment] 2020-04-15 02:44
Hi @teeto, I have tested this with your database and with the changes in this PR https://github.com/umbraco/Umbraco-CMS/pull/7907

Creating and deleting a new document type is fast along with adding/removing a property type on an existing doc type is fast. 

I then reverted the code to the changes prior to that pull request and your original DB which had database path errors and tried again. This time, adding any new property type results in a YSOD and adding any new document type results in a YSOD. It could be that you don't have debug=true turned on and that these YSODs are taking some time to produce or potentially they are hidden so the requests seem to timeout which might look like they are taking a long time. 

The underlying problem though is the corrupted data in the database. I can confirm that updating to the code in that PR and running the health checks to fix the data and then changing any document type works and is fast.

I'll close this issue but will add additional notes to the #7907 about corrupted data affecting content type saving.

**Closed by Shazwazza** 2020-04-15 02:44 UTC
Labels: state/needs-investigation, state/sprint-candidate

**Comment by Shazwazza** [comment] 2020-04-15 02:46
@teeto if you would like to fix your current database now, you can use the SQL workaround mentioned here https://github.com/umbraco/Umbraco-CMS/pull/7907#issuecomment-610732293 and then you can re-test modifying document types

**Comment by teeto** [comment] 2020-04-15 10:11
Thanks @Shazwazza i have ran the script but no errors found.
So may be the slowiness is normal for this amount of data, but i have Umbraco 7 websites with larger datasets and these operations to document types are a lot faster.
May be i have to update my Umbraco 8 to include the #7907 fix? when it will be released?
BTW, when doing these operations why i had errors, is it updating the cache? or rebuilding something?

**Comment by teeto** [comment] 2020-04-15 15:34
Now on production site i have added a text property to a document and have this error (sometimes):
`System.Data.SqlClient.SqlException (0x80131904): Lock request time out period exceeded.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)`

After several times it saved and then (i was on content, infinit editing the document type) fill the new textfield and after saving same error.

Then, after saving another 2 times i get this:
`System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' with unique index 'IX_umbracoPropertyData_VersionId'. The duplicate key value is (53268, 139, <NULL>, <NULL>).
The statement has been terminated.`

So i have waited a minute and then save again and it is saved succesfully.
Remember i set this web app on a normal azure web app, sql azure and on web.config:
`<add key="Umbraco.Core.LocalTempStorage" value="EnvironmentTemp" />
	<add key="Umbraco.Examine.LuceneDirectoryFactory" value="Examine.LuceneEngine.Directories.TempEnvDirectoryFactory, Examine" />
	<add key="Umbraco.Examine.RebuildOnAppStart" value="false" />
	<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />	`

**Comment by Shazwazza** [comment] 2020-04-16 05:52
Hi @teeto,

> So may be the slowness is normal for this amount of data, but i have Umbraco 7 websites with larger datasets and these operations to document types are a lot faster.

no it shouldn't be. I tested the DB that you provided me which i assume has the same data and there was no delay when i tested it, though i was getting YSOD errors when modifying doc types because the DB had data/path errors. (see my comments above https://github.com/umbraco/Umbraco-CMS/issues/7756#issuecomment-613783120)

I ran the SQL script on the databases that you sent me and they have errors. Are the databases you sent me different from the ones you are testing?

Regarding your Azure hosting what database tier are you using? If you are using a Tier below S2 you will most likely have issues. S2 is the minimum that we recommend, see docs https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps#recommended-configuration

**Comment by teeto** [comment] 2020-04-16 16:02
The database we are using is the first one i sent to you but we have worked more on it. 
I have ran the script with no errors (i fixed them when moving to a folder).
The Azure tier is S0 10DTUs, S2 its too expensive for this project.
That should not be a problem,  i have on that tier another Umbraco 7 projects (one with over 50.000 products) that runs fine and never have problems.
It seems an issue related with azure locks, i know you fixed them in 8.6 but may be there is something more to fix.
BTW i have restored the database on local computer and adding a property and saving is about 10s and removing it afterwards and saving is 20s. Thats not normal, i guess this actions performs operations that are database heavy on Umbraco 8 and not on Umbraco 7.
Im sending an updated data base for you to test it.

**Comment by Shazwazza** [comment] 2020-04-17 00:33
@teeto this is not a problem with v8 vs v7. v8 runs faster than v7 so if there's an issue I can replicate regarding this, than it's a v8 bug that needs to be resolved. I will retry with the latest DB you have sent me. But like I said, DB tiers less than S2 will see issues. Yesterday I also discovered a reason why sometimes SQL timeouts may occur on a cold boot when rebuilding nucache. This could be directly related to your issue too but I'm not 100% sure at this stage.

**Comment by Shazwazza** [comment] 2020-04-17 04:58
Hi @teeto I haven't had a chance to look at your new DB yet but as i mentioned above I was debugging another issue I saw and I think this is directly related to the issue you are seeing. I've created a new PR here https://github.com/umbraco/Umbraco-CMS/pull/7970

Can i assume that you are using PureLive models for Models Builder? It is not recommended to use PureLive models in production especially with large amounts of data. PureLive models directly rely on the schema of document/media types and as such the entire nucache objects rely on the runtime generated models. When a doc type or media type changes and PureLive is enabled, the entire nucache needs to be regenerated. So yes this is different from v7 because in v7 the in-memory cache is just an XML document and then each time a model needs to be resolved it has to create and map to a new IPublishedContent instance which is horribly slow and is the main cause of memory/performance issues in v7. In v8, the in-memory cache IS the models already, there is no mapping between xml and models. So in v8 with PureLive enabled, document type/media type changes will cause the whole cache to be rebuilt. 

So you are probably affected by that, especially since you are on a lower DB tier than we require and this is causing your SQL timeouts. The PR I mentioned above will prevent the SQL timeouts and it should go a little faster but it still won't be perfect if you are not running S2. You should look at using non-PureLive models and then this won't be an issue.

**Comment by teeto** [comment] 2020-04-17 10:03
Thanks @Shazwazza 
Im not using Models Builder, so i have disabled on my web.confg (i hope so):
`
<add key="Umbraco.ModelsBuilder.Enable" value="false" />
    <add key="Umbraco.ModelsBuilder.ModelsMode" value="PureLive" />
`
It sounds like that could be the problem, because i guess its rebuilding the cache each time i modify a document type. When i had corrupted media i had the same errors rebuilding the cache as changing document types. May be it is not completely disabled?
I compare v8 to v7 because it is my first v8 project and have done lots of v7. S2 is recommended for v7 too but i never had an issue with v7 regarding database usage. Most of my projects are small and therefore run basic tier but some larger projects run S0 tier. This being said i have noticed v8 is very very faster compared to v7 specially on front end queries. Only problem when editing document types and having this database locks.

**Comment by teeto** [comment] 2020-04-17 10:08
I can see a Models folder in App_Data with models.generated.cs file recently updated so i guess Models Builder is not fully disabled

**Comment by teeto** [comment] 2020-04-17 14:22
I have changed the Models mode:
`<add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" />`
And now changing a document type is not slow anymore! i guess that it was ignoring the "Umbraco.ModelsBuilder.Enable" key.
I hope lock errors are gone too...

**Comment by Shazwazza** [comment] 2020-04-20 08:51
Well i guess this is both good news and bad news. I have a task to look into and fix the Enabled flag. Thanks for all your help!
