### ISSUE TITLE
"Duplicate to..." does not work in v14 beta 2

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16013] opened 2024-04-08 13:04 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-beta002

### Bug summary

Trying to make a duplicate of a DocumentType is not possible. Nothing happens besides an error in the console window.

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/36481eb3-209c-4dec-8937-c812ac40d21f)

### Steps to reproduce

Create a DocumentType
Click on the 3 dots on the new item and choose "Duplicate to..."
Chose the folder you want the new item to be placed.

### Expected result / actual result

Excpected: a copy the DocumentType to appear in the destination folder.

Result: nothing - not even a error messsage
There is an error in the browser console window - "duplicate is not a function"

**Comment by nhudinh0309** [comment] 2024-05-03 06:51
Hi @mjpraxis 😄 
Thanks for reporting this issue! 
I was able to reproduce it. The issue is currently fixed on our dev branch, so it should be released in the next beta version!
Therefore, I will mark this as closed for now. 👍

**Closed by nhudinh0309** 2024-05-03 06:51 UTC
Labels: type/bug
