### ISSUE TITLE
Using Unattended Install with database type, without username/email/password, gives System.IO.DirectoryNotFoundException: 'wwwroot\media\''

### ISSUE THREAD

**Issue by jacksorjacksor** [umbraco/Umbraco-CMS#15119] opened 2023-11-02 15:05 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7.0

### Bug summary

Running a new project where you specify a database type (i.e. SQLite) but *don't* provide username/email/password results in the error:
`System.IO.DirectoryNotFoundException: 'wwwroot\media\''`

### Specifics

The error specifically comes from the block in `Startup.cs` starting on line 51.

### Steps to reproduce

Create project and solution with following script:

```bash
# Ensure we have the version specific Umbraco templates
dotnet new -i Umbraco.Templates::10.7.0 --force

# Create solution
dotnet new sln --name "UnattendedTestSolution"

# Create project with database type, without --friendly-name or --email or --password
dotnet new umbraco -n "UnattendedTestProject" --development-database-type SQLite

# Add project to solution
dotnet sln add "UnattendedTestProject"

# Run project
dotnet run --project "UnattendedTestProject"
#Running
```

The same came be achieved through the Visual Studio "File>New>Project" wizard with Umbraco Project (Umbraco HQ) template:

![image](https://github.com/umbraco/Umbraco-CMS/assets/5838388/28e68e94-0405-48a3-a268-3425446a904b)

![image](https://github.com/umbraco/Umbraco-CMS/assets/5838388/c72ca1da-d828-49e3-b93d-acda94ad0a12)

Running the project gets you the same error, from `Startup.cs` line 51 block:

![image](https://github.com/umbraco/Umbraco-CMS/assets/5838388/9b05d7a0-d652-49ef-b3cf-0ca14202ac3a)

### Expected result / actual result

Ideally a more appropriate error message would display - "Database type provided but username, email and password are required for Unattended Install". 

Ideally the requirement of these fields should be made more explicit in the [documentation](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/setup/install/unattended-install) - I'm happy to submit a suggestion to the docs!

**Comment by andr317c** [comment] 2023-11-03 07:54
Hey!
Thanks a lot for taking the time to post this issue. This seems like a duplicate of #14956. I will go ahead and close this issue so we can keep the discussion in one place 😄

**Closed** 2023-11-03 07:54 UTC
Labels: type/bug

**Comment by jacksorjacksor** [comment] 2023-11-03 09:11
Ah my apologies, thanks for highlighting!
