### ISSUE TITLE
Umbraco Forms - V8. Workflow - Save as Umbraco content node Content Picker, 404

### ISSUE THREAD

**Issue by RobinHoody** [umbraco/Umbraco-CMS#4952] opened 2019-03-11 21:07 UTC
If I add a create umbraco node on form submission workflow step, under - Save as Umbraco content node, where to save, if I click on choose (the content picker), I get a 404 with /views/common/overlays/treepicker/treepicker.html not found.

![image](https://user-images.githubusercontent.com/4989076/54157891-2ec90600-4441-11e9-980b-a9f49d2fb4af.png)

Reproduction
------------

### Bug summary
Looks like the path to the tree picker overlay is wrong, maybe a typo?

### Specifics

Any umbraco form for V8, I've just used the default starter kit on umbraco cloud and local, tested both and the issue is present in both.

### Steps to reproduce

On configure workflows for any form add a new step (Umbraco content node). Click add then go to the bottom of the editor window and click on choose a node, you should receive a 404 in a red error message notification.

![image](https://user-images.githubusercontent.com/4989076/54158259-ff66c900-4441-11e9-8e6f-af3f86bf14f3.png)

### Expected result

View the tree picker to pick a node to add new content items under.

### Actual result

Red error notification - 404. See screenshot: 

![image](https://user-images.githubusercontent.com/4989076/54157891-2ec90600-4441-11e9-980b-a9f49d2fb4af.png)

**Comment by RobinHoody** [comment] 2019-03-12 09:18
Looking at other working tree pickers, it looks like this url should be: /views/common/infiniteeditors/treepicker/treepicker.html

Is that correct?

**Comment by RobinHoody** [comment] 2019-03-12 09:22
@nul800sebastiaan Also, is this the right project for this bug report? I can't find forms to do a pull request (but I don't think forms is open source).

**Comment by bergmania** [comment] 2019-03-12 09:31
The right project for this bug is: https://github.com/umbraco/Umbraco.Forms.Issues 

I can confirm the bug.

**Comment by bergmania** [comment] 2019-03-12 09:52
After more investigation, this is duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/105

**Comment by RobinHoody** [comment] 2019-03-12 09:54
Ok thanks.

**Closed** 2019-03-12 09:54 UTC

**Comment by RobinHoody** [comment] 2019-03-12 09:56
If you don't mind me asking, do you know when this fix will be released?

**Comment by bergmania** [comment] 2019-03-12 10:18
Not today but probably one of the upcoming Tuesdays

**Comment by RobinHoody** [comment] 2019-03-12 10:23
Ok thanks!
