### ISSUE TITLE
v15: Models Builder no longer generates correct type for Label value types

### ISSUE THREAD

**Issue by PhyxionNL** [umbraco/Umbraco-CMS#17543] opened 2024-11-15 10:04 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0

### Bug summary

In V13, if you have a Label with value type Integer, the models builder would generate this as an int. With v15 this is generated as a string.

### Steps to reproduce

Create a label with integer (or anything other than String) and it's not working OK.

**Comment by nikolajlauridsen** [comment] 2024-11-15 13:36
Thanks for reporting, I'll go ahead and close this one as it's a duplicate of #17192 fixed in #17435 😄

**Closed by nikolajlauridsen** 2024-11-15 13:36 UTC
Labels: type/bug
