### ISSUE TITLE
When published using appsettings.json value "Debug": false the package.manifest files within App_Plugins return a 404 when hosted in IIS

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#10863] opened 2021-08-15 16:08 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0 RC1

### Bug summary

When published using appsettings.json value "Debug": false the package.manifest files within App_Plugins return a 404 when hosted in IIS.

### Specifics

Using .NET 5.09 and have tested this using the default RC1 template. Have also tested this in Windows Server 2016 as well as the latest version of Windows 10.

### Steps to reproduce

First, configure your project to also deploy your App_Plugins folder (this omission is also a bug with the Umbraco 9 templates):

```
<ItemGroup>  
    <None Update="App_Plugins\**\*">  
       <CopyToPublishDirectory>Always</CopyToPublishDirectory>  
    </None>  
</ItemGroup>
```
Then publish a project using the Release config and an appsettings "Debug" value of false.

```
"Umbraco": {  
      ...  
      "Hosting": {  
          "Debug": false  
      },...
```

When you host that published folder in IIS, the package.manifest files within the App_Plugins folder return 404s and plugins stop working. If you try to access a .manifest file from somewhere within the wwwroot folder they are returned to the browser properly.

### Expected result / actual result

The package.manifest files should be served correctly, as they are in debug mode.

**Comment by nul800sebastiaan** [comment] 2021-08-19 11:57
Hi @argentini - I would note that `package.manifest` doesn't have a handler, and it does not need to be available in the browser.

After applying your fix, the publishing including the `App_Plugins` folder seems to work fine, `debug` is set to `false` and the app plugin works as intended. Maybe you need to do a hard refresh in the browser? Not sure, this is how it looks for me:

![image](https://user-images.githubusercontent.com/304656/130064458-c6fe73e2-9d6b-4dd1-8f09-b25ca05c2cf6.png)

I've fixed the template to also copy  `App_Plugins` here: https://github.com/umbraco/Umbraco-CMS/pull/10904

**Comment by nul800sebastiaan** [comment] 2021-08-19 12:24
Oh it turns out this was already fixed in RC2! 

I had to do `dotnet new --uninstall Umbraco.Templates` and then `dotnet new -i Umbraco.Templates::9.0.0-rc002` - but that's probably because I had been playing with RC2 last week before it was updated, so the last command should be sufficient for you.

I'll close this now, I believe everything works as expected now!

**Closed by nul800sebastiaan** 2021-08-19 12:24 UTC
Labels: project/v9, type/bug, release/9.0.0-rc002

**Comment by argentini** [comment] 2021-08-19 14:31
Ah good to know. I thought that the manifest was part of the deliverable to the browser since Angular is largely a client-side stack. Either way it was not being read by Umbraco :)

Is RC2 available in Nuget yet? If not, when will it be?

**Comment by nul800sebastiaan** [comment] 2021-08-19 14:34
RC2 was released this morning, go for it! :)

**Comment by argentini** [comment] 2021-08-19 15:28
It looks like there are some breaking changes in RC2. Is there any documentation for what has changed in RC2 from RC1? For example, ContentService.SaveAndPublish() doesn't appear to have the "raiseEvents" parameter.

**Comment by nul800sebastiaan** [comment] 2021-08-20 13:42
@argentini Sure thing, we've added to the documentation: https://our.umbraco.com/documentation/UmbracoNetCoreUpdates#changes-between-rc-1-and-rc-2 and your specific issue can be found here: https://github.com/umbraco/Umbraco-CMS/pull/10655

**Comment by argentini** [comment] 2021-09-04 17:41
@nul800sebastiaan I just did a deployment in release mode and the error is still happening. On the production server when I edit the appSettings and change debug to true, the App_Plugins start working.
