### ISSUE TITLE
Cant copy and paster blocks in block list using version 13.5.0

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#17088] opened 2024-09-18 08:50 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.0

### Bug summary

After updating from 13.4.1 to 13.5.0 cant copy and paste blocks inside block list editor.
Downgrading to 13.4.1 makes it work again.

### Steps to reproduce

Copy a block
Paster a block
Select the block from the clipboard
It hangs.

**Comment by NguyenThuyLan** [comment] 2024-09-20 08:07
Hi @teeto , thanks for reporting the issue. Unfortunately, I couldn't reproduce it like the video below (V13.5.0)

https://github.com/user-attachments/assets/57e9eb9b-d66f-45f2-b03f-f631f5422010

Can you give me more details or recheck it?

**Comment by danbramall** [comment] 2024-09-22 14:15
This seems to be resolved in 13.5.1 (https://github.com/umbraco/Umbraco-CMS/pull/17070)

**Comment by teeto** [comment] 2024-09-23 08:31
thanks @danbramall i have updated and i can confirm the issue is solved.

**Closed** 2024-09-23 08:31 UTC
Labels: state/needs-more-info, type/bug
