### ISSUE TITLE
Installation doesn't work on Mac M1 getting SQLite error

### ISSUE THREAD

**Issue by osterhult** [umbraco/Umbraco-CMS#13206] opened 2022-10-13 12:51 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10

### Bug summary

I have now tried to install Umbraco 10 locally on two different Macs. One Intel based and one with a M1 processor. Followed the instructions I found here on this site.

https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-templates

But on both computers I get the same error.

"Error during installation SQLite Error 1: 'no such column: −339'."

### Specifics

It happens the installation phase.

### Steps to reproduce

Just follow the steps on this page on a Mac.
https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-templates

### Expected result / actual result

A successful installation with SQLite.

**Comment by nul800sebastiaan** [comment] 2022-10-13 13:51
Hey there @osterhult - seems strange, other people are using it just fine on M1 Macs. 

Can you try again [with these steps](https://psw.codeshare.co.uk/?InstallUmbracoTemplate=true&UmbracoTemplateVersion=&Packages=&UserEmail=test%40test.com&ProjectName=MyProject&CreateSolutionFile=false&SolutionName=MySolution&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=test123456&UserFriendlyName=Test&IncludeStarterKit=false&StarterKitPackage=clean) and see what happens? 

I'm assuming you have dotnet 6 SDK and the runtime installed? https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by nul800sebastiaan** [comment] 2022-10-13 13:59
Was there more after `...`?

**Comment by osterhult** [comment] 2022-10-13 14:06
Yes. Here is the hole dump..

....

[16:01:58 INF] Create Index:
 CREATE UNIQUE INDEX "IX_umbracoCreatedPackageSchema_Name" ON "umbracoCreatedPackageSchema" ("name")
[16:01:58 INF] Creating data in umbracoCreatedPackageSchema
[16:01:58 INF] Completed creating data in umbracoCreatedPackageSchema
[16:01:58 INF] New table umbracoCreatedPackageSchema was created
[16:01:58 INF] Create table:
 CREATE TABLE umbracoUserGroup2Language
(
 "userGroupId" INTEGER NOT NULL
, "languageId" INTEGER NOT NULL
, CONSTRAINT PK_userGroup2language PRIMARY KEY ("userGroupId", "languageId")
, CONSTRAINT FK_umbracoUserGroup2Language_umbracoUserGroup_id FOREIGN KEY ("userGroupId") REFERENCES "umbracoUserGroup" ("id")  ON DELETE CASCADE
, CONSTRAINT FK_umbracoUserGroup2Language_umbracoLanguage_id FOREIGN KEY ("languageId") REFERENCES "umbracoLanguage" ("id")  ON DELETE CASCADE
)

16:01:58 INF] Creating data in umbracoUserGroup2Language
[16:01:58 INF] Completed creating data in umbracoUserGroup2Language
[16:01:58 INF] New table umbracoUserGroup2Language was created
[16:01:58 INF] Unattended install completed.
[16:01:58 WRN] No last synced Id found, this generally means this is a new server/install. A cold boot will be triggered.
[16:01:58 WRN] Database NuCache was serialized using 0. Currently configured NuCache serializer MessagePack. Rebuilding Nucache
[16:01:58 INF] Rebuilding NuCache database with MessagePack serializer [Timing ed86490]
[16:01:58 INF] Completed. (109ms) [Timing ed86490]
[16:01:58 Unhandled exception. ERR] Unhandled exception in AppDomain (terminating).
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: −339'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock.ObtainWriteLock()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock..ctor(SqliteDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.RepositoryBase.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.KeyValueRepository.PerformGet(String id)
   at Umbraco.Cms.Core.Cache.NoCacheRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Get(TId id)
   at Umbraco.Cms.Core.Services.KeyValueService.SetValue(String key, String value)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.RebuildDatabaseCacheIfSerializerChanged()
   at Umbraco.Cms.Infrastructure.PublishedCache.NuCacheStartupHandler.Handle(UmbracoApplicationStartingNotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MyProject2.Program.Main(String[] args) in /Users/magnusosterhult/Documents/Kodning/Umbraco/MyProject2/Program.cs:line 6
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: −339'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281%

I also noted some other errors before this happened. 
<img width="906" alt="Skärmavbild 2022-10-13 kl  16 04 57" src="https://user-images.githubusercontent.com/2151403/195618964-bf5ebc24-4b6c-4fea-831a-d192064c0390.png">

**Comment by nul800sebastiaan** [comment] 2022-10-13 14:46
Yeah the errors in the screenshot are "normal" for an unattended install (which is what I directed you to do). 

I don't see an obvious cause of the error here I'm afraid, we'll need to try to reproduce and investigate. Sorry I don't have much else to offer at the moment!

**Comment by osterhult** [comment] 2022-10-13 14:54
@nul800sebastiaan Thanks anyway. The strange thing is that I get the same error on two different machines. My best guess is it has something to do with SQLite installation. But I can't figure out what it is.

**Comment by markadrake** [comment] 2022-10-13 15:44
This looks more like a permission issue, i.e., _not having access to read/write to the SQLite file_. 

I will update our Dotnet template to 10.2.1 and then ask others in the office to install Umbraco and report back.

**Comment by osterhult** [comment] 2022-10-14 05:37
@markadrake Thanks for testing. So strange that I have gotten this issue on two separate machines and no one else seems to be able to replicate it. 

More info from me. 
On this machine I use 12.6 of MacOS. Not sure which version I have one the other one at home. It might also be 12.6.

Moving stuff outside of /Users/ seems a bit dodgy since more or less everything is read-only per default. 

If you follow the instructions on the Umbraco page "dotnet run" is used inside the project folder. So that shouldn't be an issue.

**Comment by osterhult** [comment] 2022-10-14 05:45
@markadrake **update**

Tried to back NuGet package to both 10.1.0 and 10.0.0 and also changed directory to install into (still within /Users/) but I get the same error. Although maybe not on the same place. From my try with package version 10.0.0.


[07:41:21 INF] Create Index:
 CREATE UNIQUE INDEX "IX_umbracoCreatedPackageSchema_Name" ON "umbracoCreatedPackageSchema" ("name")
[07:41:21 INF] Creating data in umbracoCreatedPackageSchema
[07:41:21 INF] Completed creating data in umbracoCreatedPackageSchema
[07:41:21 INF] New table umbracoCreatedPackageSchema was created
[07:41:21 INF] Database configuration status: <p>Installation completed!</p>
[07:41:21 INF] Step completed (172ms) [Timing 2554511]
[07:41:21 INF] Executing installation step: 'User'. [Timing 49c36b0]
[07:41:21 WRN] No last synced Id found, this generally means this is a new server/install. A cold boot will be triggered.
[07:41:21 INF] Step completed (104ms) [Timing 49c36b0]
[07:41:21 INF] Executing installation step: 'UmbracoVersion'. [Timing 1c80cb8]
[07:41:37 INF] Step completed (15993ms) [Timing 1c80cb8]
[07:41:37 WRN] Database NuCache was serialized using 0. Currently configured NuCache serializer MessagePack. Rebuilding Nucache
[07:41:37 INF] Rebuilding NuCache database with MessagePack serializer [Timing 50768b0]
[07:41:37 INF] Completed. (120ms) [Timing 50768b0]
[07:41:37 ERR] An unhandled exception has occurred while executing the request.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: −339'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock.ObtainWriteLock()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock..ctor(SqliteDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.RepositoryBase.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.KeyValueRepository.PerformGet(String id)
   at Umbraco.Cms.Core.Cache.NoCacheRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Get(TId id)
   at Umbraco.Cms.Core.Services.KeyValueService.SetValue(String key, String value)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.RebuildDatabaseCacheIfSerializerChanged()
   at Umbraco.Cms.Infrastructure.PublishedCache.NuCacheStartupHandler.Handle(UmbracoApplicationStartingNotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.RestartAsync()
   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.CompleteInstall()
   at lambda_method289(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 119
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[07:42:02 ERR] Failed to update server record in database.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: −331'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock.ObtainWriteLock()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock..ctor(SqliteDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.RepositoryBase.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ServerRegistrationRepository.PerformGetAll(Int32[] ids)
   at Umbraco.Cms.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.GetMany(TId[] ids)
   at Umbraco.Cms.Core.Services.Implement.ServerRegistrationService.TouchServer(String serverAddress, TimeSpan staleTimeout)
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.TouchServerTask.PerformExecuteAsync(Object state)
[07:43:02 ERR] Failed to update server record in database.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: −331'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock.ObtainWriteLock()
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock..ctor(SqliteDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.RepositoryBase.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ServerRegistrationRepository.PerformGetAll(Int32[] ids)
   at Umbraco.Cms.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.GetMany(TId[] ids)
   at Umbraco.Cms.Core.Services.Implement.ServerRegistrationService.TouchServer(String serverAddress, TimeSpan staleTimeout)
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.TouchServerTask.PerformExecuteAsync(Object state)

**Comment by markadrake** [comment] 2022-10-21 06:05
@osterhult Have you made any progress in the past few days mate? I apologize for not getting back to you. To be quite honest, I'm stumped. 

Could you kindly share a screenshot of the output from these commands:

1. `dotnet --info`
2. `sqlite3 -version`

The information might help someone at HQ understand the scenario better.

Here is an example from my output: 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/713355/197123456-994dfadd-5deb-4c40-9dbb-9325017c808f.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/713355/197123861-2c4364fb-1fcc-4ef1-a645-31f23671167d.png">

**Comment by osterhult** [comment] 2022-10-21 06:42
@markadrake no worries. No progress from my end. Sadly! I am starting to wonder if it is the macOS 12.6 who is the villain.

Here is my screen dumps.

<img width="788" alt="Skärmavbild 2022-10-21 kl  08 39 57" src="https://user-images.githubusercontent.com/2151403/197130027-71c7a59b-433e-44e0-881f-468ab490bb60.png">

<img width="774" alt="Skärmavbild 2022-10-21 kl  08 40 19" src="https://user-images.githubusercontent.com/2151403/197130046-a58d9823-5db5-4729-9282-e7cc87352038.png">

**Comment by osterhult** [comment] 2022-10-21 12:50
@markadrake update: Just tried it with the new Template release of 10.3.1, but I get the same error.  :(

**Comment by crystalii** [comment] 2022-10-22 13:12
Hello!

I am experiencing the exact same issue I'm afraid. I am running on Macbook Air with M2 and OS version 12.5. I cannot create a new project since I get `SQLite Error 1: 'no such column: −339'.`

Here is the full logs on my end: https://pastebin.com/wL92kt6k

**Comment by crystalii** [comment] 2022-10-23 10:58
I managed to find a workaround by running an SQL server instance in a docker environment, then select SQL Server instead of SQLite in the Umbraco Setup. I don't know the reason of this bug, if it is is something limited to the Apple Silicon architecture or if it is because of something else. Either way, you should run your own DB instance and select so that Umbraco connects to it.

For Apple Silicon users, install and run Docker and then execute the following command in the Terminal:

docker run -e "ACCEPT_EULA=1" -e "MSSQL_SA_PASSWORD=Password123" -e "MSSQL_PID=Developer" -e "MSSQL_USER=sa" -p 1433:1433 -d --name=localhost mcr.microsoft.com/azure-sql-edge


Then in the Umbraco setup, enter 127.0.0.1 as server name, master as db name, Password123 as password and sa as username.

**Comment by dlidstrom** [comment] 2022-10-25 15:17
This issue is solved in #13284.

**Comment by nul800sebastiaan** [comment] 2022-10-26 07:11
Aha!! Great find @dlidstrom - yep that's the exact error that's been fixed, which will be released in 10.3.2 (commit id 272e9220205d562a964fce9de25cf4bb201ebf26) soon. I'll close this as fixed in #13284, do keep an eye out for that release, should hopefully be out by tomorrow or otherwise early next week. Thanks for the discussions everyone! 👍

**Closed by nul800sebastiaan** 2022-10-26 07:11 UTC
Labels: type/bug, release/10.3.2

**Comment by dlidstrom** [comment] 2022-10-26 07:33
Yep @nul800sebastiaan, I've already seen and fixed the same issue in the PostgreSQL persistence implementation I've been working on.
