### ISSUE TITLE
List view links do not respect the chosen culture variant

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco-CMS#6116] opened 2019-08-13 13:04 UTC
After changing the language in the top left and navigating to a node with a listview, the children are shown in the chosen language. But when clicking on a child node, the node is opened in the default language

Umbraco version 8.1.1

Reproduction
------------
### Bug summary
![ChildVariants](https://user-images.githubusercontent.com/6025797/62943858-af6aa480-bddb-11e9-87a5-5fbfa944b218.gif)

### Steps to reproduce

I will try and reproduce this on a brand new instance

### Expected result

Editor opens the child item in the correct variant culture

### Actual result

Default variant is used

**Comment by nul800sebastiaan** [comment] 2019-08-13 15:33
I noticed @kjac fixed something similar for https://github.com/umbraco/Umbraco-CMS/issues/6100 so hopefully it can be fixed in the same way here.

**Comment by kjac** [comment] 2019-08-13 19:56
@Migaroez I can't reproduce this (and the fix for #6100 is not yet merged in so that can't be it)... can you shed anymore light as to how you've managed this?

Here's how it looks when I test:
 
![list-view-child-link-language](https://user-images.githubusercontent.com/7405322/62972792-21abab00-be15-11e9-9628-d1725a58c87f.gif)

**Comment by TobiasJensen** [comment] 2019-08-14 09:45
I have reproduced similar issue.

1. Created new project and installed a clean 8.1.2 Umbraco sample site.
2. Added Language "Swedish" keeping en-us as default language.
3. Making document types "Home" and "Products" to allow varying by culture
4. Reload Content section.
5. Change language in upper left to swedish
6. Click "Home" and main content area/mid is shown in default language

When I play around with editing/creating pages in non-default language, the language in the mid part keeps changing back to default language.

We hade this working in v8.0 and discovered this in v8.1. I havent yet tried same clean procedure as above in a clean v8.0.

**Comment by TobiasJensen** [comment] 2019-08-21 08:46
#6026 fixed this imo. 👍

**Comment by nul800sebastiaan** [comment] 2019-08-21 09:00
Thanks @TobiasJensen - I'll close this as fixed in 8.1.3 for now.

**Closed by nul800sebastiaan** 2019-08-21 09:00 UTC

**Comment by Migaroez** [comment] 2019-08-21 09:38
Great, ill have a look if it is fixed on my instance once 8.1.3 is out.

Thx guys!

**Comment by nul800sebastiaan** [comment] 2019-08-21 09:47
@Migaroez - Keep up mate, it was released yesterday 😅😉

**Comment by Migaroez** [comment] 2019-08-21 10:04
I guess its upgrade time then.
