### ISSUE TITLE
SqlMainDom lock fails during install or upgrade

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco-CMS#8089] opened 2020-05-11 11:01 UTC
The `SqlMainDom` lock is required while running on Azure - this is configured via an app setting:

```
<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />
```

If this app setting is applied before Umbraco has been installed the application fails to start. This kind of makes sense as there's no database to apply the lock.

However the same issue occurs when performing an upgrade. If you upgrade Umbraco 8.5.x => 8.6.x and apply the new app setting, the application fails to start unless the upgrade has been performed first.

![image](https://user-images.githubusercontent.com/16511093/81554693-24750580-937f-11ea-9974-b6cd32c8678f.png)

It seems a little unnecessary for Umbraco to obtain a lock before / while upgrading, and the error causes a lot of confusion.

Maybe I'm missing a very good technical reason, but I feel this error could be avoided by only applying the SQL lock when Umbraco is fully initialized.

**Comment by sitereactor** [comment] 2020-05-11 11:08
We have that captured here as we ran into it ourselves 😅

https://github.com/umbraco/Umbraco-CMS/issues/7967

**Comment by callumbwhyte** [comment] 2020-05-11 11:19
Excellent!

I tried to look through the commits but couldn't directly see anything fixing this... Looking forward to v8.6.2 😎

**Comment by nul800sebastiaan** [comment] 2020-05-11 15:28
I'll close this as a duplicate of #7967

**Closed by nul800sebastiaan** 2020-05-11 15:28 UTC
