### ISSUE TITLE
Blocklist editor doesn't load on Member Edit

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#11082] opened 2021-09-12 21:22 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-RC3

### Bug summary

Add a block list editor property to a member type, and then try to edit a member you will get the following console error:

```
Could not find umbVariantContent in the $scope chain
```

The block list editor also fails to load:

![image](https://user-images.githubusercontent.com/9937803/133003275-b963ae6f-5ec8-40be-9c4c-31faa18275de.png)

### Steps to reproduce

Create a block list element
Add a block list editor property to a member type
Try to edit a member to add a block

### Expected result / actual result

The block list editor to appear and work

**Comment by bergmania** [comment] 2021-09-13 06:33
Hi @AaronSadlerUK, thanks for reporting.

I'm pretty sure this is the same behavior as in v8. Not sure the complex editors ever was intended to work on Members, but Ill investigate and return.

**Comment by patrickdemooij9** [comment] 2021-09-13 09:45
Yes, this is also the case in v8: https://github.com/umbraco/Umbraco-CMS/issues/10085

**Comment by AaronSadlerUK** [comment] 2021-09-13 09:47
@bergmania If nested get's fixed as per #11083 then blocklist isn't required for my case.

However maybe removing the ability to add blocklist to member types is the best solution here?

**Comment by nul800sebastiaan** [comment] 2021-09-13 11:20
I'll close this as a duplicate of #10085

**Closed by nul800sebastiaan** 2021-09-13 11:20 UTC
Labels: project/v9, type/bug
