### ISSUE TITLE
Media Uploads only allowed if MediaTypeAlias is Folder

### ISSUE THREAD

**Issue by uniquelau** [umbraco/Umbraco-CMS#7694] opened 2020-02-20 15:03 UTC
When using infinite editing or the media library, it is only possible to upload files if the media type of the folder is `Folder`.

This means that it is not possible to create other folder types, e.g. a folder specifically for PDF's or a folder specifically for Product Images.

## Umbraco version

8+ (including 8.5.3)

Reproduction
------------

Create a new secondary Folder media type, 
e.g. "Product Images", alias `productImageFolder`
Try to upload media via media section or infinite editing 
The upload function is disabled

Potential solution
-------------

Allow uploads when the Folder media type is used as a Composition

**Comment by nul800sebastiaan** [comment] 2020-02-20 17:06
The trick is to make a folder derived from the `Folder` type.. so nest it under the regular `Folder` and you should be good to go: 

![image](https://user-images.githubusercontent.com/304656/74959944-c255d580-540b-11ea-9238-3bc7bfa40230.png)

**Comment by nul800sebastiaan** [comment] 2020-02-20 17:07
Let me know if this works for you, or if you tried this and it didn't work.

**Comment by uniquelau** [comment] 2020-02-20 17:26
Ahha! I tried compositions, but forgot about the derived types - will give
that a go, sounds like it'll do the trick 👍

**Comment by nul800sebastiaan** [comment] 2020-02-21 10:30
👍  

I'm going to tentatively close this issue for now as being "intended behavior", it's not ideal but in the future we do want to update the whole media section experience. I'll add the `idea`  label to this so we don't forget about this one!

**Closed by nul800sebastiaan** 2020-02-21 10:30 UTC
Labels: project/media-library, status/idea

**Comment by uniquelau** [comment] 2020-02-21 11:51
@nul800sebastiaan Thanks!

For reference this only works if the derived media type items are set to use the List View.
