### ISSUE TITLE
Cannot pick form using Umbraco form picker with an emepy selection (all forms)

### ISSUE THREAD

**Issue by WeAreJigital** [umbraco/Umbraco-CMS#13523] opened 2022-12-04 22:30 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.1

### Bug summary

![e6198679630b4dc6ba29bc26ef386f56](https://user-images.githubusercontent.com/60449677/205519160-ec2838de-d8c4-4a17-af2a-a41ac4bb57a8.jpg)
![b800347200db4740919d91db493448d5](https://user-images.githubusercontent.com/60449677/205519175-5c5d376e-49f2-4813-b0c4-f00cc0ff57b4.jpg)

When i try to select a form using Umbraco forms picker I dont get the option of picking a form although the text says 'The forms available for selection. If none are selected then all forms will be allowed.'

### Specifics

Check browsers, video below and screen shots above

### Steps to reproduce

https://www.loom.com/share/8c61198af1984870823c0846acc9e59d

### Expected result / actual result

Can select all forms as per the description text.

**Comment by nikolajlauridsen** [comment] 2022-12-05 10:32
Hey @WeAreJigital, thanks for your report and video (they're always super helpful), unfortunately I'm unable to reproduce the issue, I've tried with a form picker in a blocklist and it seems to work as expected, both in 10.1.1, and the latest V10 (10.3.2). 

Are you sure your user has access to the forms? That's just a thought, but that might interfere with being able to pick a form. 

I've taken a video of it working on my side, can you see if anything's different? 

https://user-images.githubusercontent.com/16456704/205615635-da90981f-61a6-4da2-b814-e6190c7b2ef0.mp4

**Comment by WeAreJigital** [comment] 2022-12-05 12:43
Hi @nikolajlauridsen Yes i am using an administrator account

**Comment by WeAreJigital** [comment] 2022-12-05 12:44
@nikolajlauridsen i will try a few other things :)

**Comment by nikolajlauridsen** [comment] 2022-12-06 07:51
Awesome, please let me know if you find anything so we can proceed, or close this issue down. 

It's also worth mentioning that since this is a Forms issue, [the dedicated Forms.Issues repo](https://github.com/umbraco/Umbraco.Forms.Issues/issues) might be a better place to ask

**Comment by WeAreJigital** [comment] 2022-12-08 09:44
@nikolajlauridsen thanks sorry about that, i will check the link out.  Not found anything yet.  No idea what it is right now :/

**Comment by nikolajlauridsen** [comment] 2022-12-08 12:32
Awesome 👍 Glad to hear you got it resolved 🎉 I'll go ahead and close this one then 😄

**Closed by nikolajlauridsen** 2022-12-08 12:32 UTC
Labels: state/needs-more-info, type/bug
