### ISSUE TITLE
"Allowed child nodes" picker filter not working in v8.9.1

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#9394] opened 2020-11-13 14:34 UTC
When editing a Document type, the picker for the "Add Child" button on the Permissions Tab *does not filter* by the text entered in the search box

![image](https://user-images.githubusercontent.com/923289/99082778-5cb20680-25a3-11eb-8cf8-92d0b35f96d5.png)

I am seeing this issue on Umbraco version: 8.9.1

Steps to reproduce
------------
* Create an empty Umbraco v8.9.1 website and add several doc types (or use the Starter Kit)
* Go to the permissions tab, Add Child, and try to filter the displayed options by text

**Comment by nul800sebastiaan** [comment] 2020-11-16 11:19
Interesting, I can reproduce, something must not have been completely finished with this PR: https://github.com/umbraco/Umbraco-CMS/pull/9132

**Comment by DavidArmitage** [comment] 2020-11-30 02:56
Hi,

I am having the same issues. With standard doc types, nested content. Pretty much anything searching document types isn't working.

It was working fine in older versions of Umbraco 8.
I noticed this after I ungraded to Version v8.9.1

It's really annoying because some of my sites are pretty big with a lot of tested content.

Myself as the developer cant search for doc types 
and the content editor cant search for nested content sections that already exist.

Hopefully this will be fixed in the next update.

**Comment by nul800sebastiaan** [comment] 2020-12-17 15:44
While fixing this one, we should update the styling to work properly as well: https://github.com/umbraco/Umbraco-CMS/issues/9394

**Comment by Matthew-Wise** [comment] 2021-01-04 10:50
Just updated to 8.10 the search issue is still present.

**Comment by nul800sebastiaan** [comment] 2021-01-04 14:34
Yep, it is not yet fixed.

**Comment by nul800sebastiaan** [comment] 2021-01-12 12:57
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9641 and cherry picked for 8.9.2 and upwards.

**Closed by nul800sebastiaan** 2021-01-12 12:57 UTC
Labels: release/8.10.2, release/8.11.0, release/8.8.3, release/8.9.2, status/regression, type/bug

**Comment by nul800sebastiaan** [comment] 2021-01-14 07:48
**Note:** This didn't make it into the 8.11.0-RC build but will be in the final build of 8.11.0.
