### ISSUE TITLE
NetCore: Url Tracker not being disabled and button still showing 'Disable Url Tracker' after clicking it.

### ISSUE THREAD

**Issue by TwoMoreThings** [umbraco/Umbraco-CMS#9813] opened 2021-02-14 20:55 UTC
On Alpha 3, click on the Disable Url tracker button and confirm you want to disable the Url tracker, after this you will see a confirmation notification appear at the bottom to confirm the url tracker has been disabled. However, the button text remains as 'Disable Url tracker', even after a refresh. 

I tested and this is an issue with the Url tracker not being disabled, despite the confirmation message.

This was tested using the latest version of Chrome on Windows but not tested in any other browsers.

regards
t

**Comment by bergmania** [comment] 2021-02-15 06:34
Hi @TwoMoreThings. Thansk for reporting. I can confirm I can reproduce, and will look into it

**Comment by bergmania** [comment] 2021-02-15 07:14
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9814. The issue was due to caching of the value, even that the value was updated in the configuration file.

Again, thanks for reporting 💪

**Closed** 2021-02-15 07:40 UTC
Labels: project/net-core
