### ISSUE TITLE
checkbox field "Is sensitive data" not working in Umbraco 8.3.0

### ISSUE THREAD

**Issue by VelikiiAntyan** [umbraco/Umbraco-CMS#7289] opened 2019-12-06 11:48 UTC
I created new property (textstring) with checkbox field "Is sensitive data" - TRUE, for the member type. The switch works, but the changes are not saved. When I click save, and I go to the field settings - The field "Is sensitive data" remains FALSE.

I am seeing this issue on Umbraco version 8.2.0 & Umbraco version 8.3.0 

### Bug summary
I don't see any error in console or umbraco logs

### Specifics
Browsers: 
Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)
Firefox 71.0 (64-bit)
![image](https://user-images.githubusercontent.com/35688501/70320413-506ae880-182d-11ea-9e90-ae7555bbd0ed.png)

### Steps to reproduce
Click Setting => Open Folder Member Types => Click Member, scroll down and click "add property". A window "Property settings" will open. Click "add editor" and change field "Is sensitive data" to true. Save new field with field "Is sensitive data" true, and check value in this field again.

### Expected result
When changing the field "Is sensitive data" to true and save data - a new value must be applied.

### Actual result
When changing the field "Is sensitive data" to true and save data - a new value always remain false

**Comment by kjac** [comment] 2019-12-09 06:50
Hi @VelikiiAntyan, thanks for reporting! 

This is a duplicate of #7270 which should be fixed in #7273 😄

**Closed** 2019-12-09 07:25 UTC

**Comment by VelikiiAntyan** [comment] 2019-12-09 08:45
@kjac, thank's!
