### ISSUE TITLE
Eye Dropper Color Picker showing blank and no color when color is picked V12

### ISSUE THREAD

**Issue by Abdjulaziz** [umbraco/Umbraco-CMS#14645] opened 2023-08-08 08:23 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

Eye Dropper Color Picker not showing the color in the content node on V12

You can pick the color but it does not show it in the "preview" as shown in the image below.

Tested on V12 & V11 to compare 
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/7e914d97-ea4a-483a-9821-d7dcc2b97b65)

The color picked is reflecting but not in the backoffice(so it works) 

### Specifics

I tested this out on 4 browsers on V12.

Chrome - not working
Brave - not working
Firefox - working
Safari - not working

There is not trace on it. 

Chrome - console
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/3b5e7e3f-79f5-42b8-9fdc-bfcebc20befa)
Firefox - console
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/148d9e5e-5801-4b83-ad3e-25a85f313ae6)

### Steps to reproduce

1. Create doctype 
2. Add property  
3. Select editor (Eye Dropper Color Picker)
4. Save doctype (in this case allow as root)
5. Create content node 
6. Then you should see a blank dropper
7. ![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/36ecae7b-bfb9-4f58-851a-89b8183e4686) 

Looking from Firefox it looks like this as it should
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/83fbb73b-9683-4024-9070-70fac484416c)

### Expected result / actual result

The Eye Dropper Color Picker should show like this ↓
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/0ae67ff5-105a-44e1-8db2-7d2164c1ec61)

And when picking a color it should then show that color like so ↓ 
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/c4261181-be2c-48b1-abe6-26b5c23a275c)

Where in Chromium based browser and safari it shows like this ↓
![image](https://github.com/umbraco/Umbraco-CMS/assets/60339265/6049bebf-a8fe-494b-a5fa-1baad794c88b)

**Comment by bjarnef** [comment] 2023-08-08 09:33
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/14627
This has already been fixed in next release.

For now a workaround is to inject custom CSS via a package.manifest:

```
.umb-color-picker .sp-replacer .sp-preview {
    height: calc(100% - 10px);
}
```

**Closed** 2023-08-08 09:34 UTC
Labels: type/bug
