### ISSUE TITLE
DomainService.GetAll returns domains from nodes that have been deleted

### ISSUE THREAD

**Issue by joepvtl** [umbraco/Umbraco-CMS#8610] opened 2020-08-07 13:09 UTC
When using the GetAll(bool) method from the DomainService, it also returns domains from nodes that are in the recycle bin. I'm not sure if this is a bug or if this was meant to be like this, so just making this issue to be sure.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.3

Reproduction
------------

1. Install the default starterkit.
2. Create a new home node at root.
3. Add a domain to that node.
4. Delete the node.
5. Add the Umbraco.Core.Composing; namespace to your home view.
6. Add this code to the bottom of your home view:
` @foreach(var domain in Current.Services.DomainService.GetAll(false))
    {
    @Html.Raw("Domain:" + domain.DomainName + " NodeId:" +domain.RootContentId.Value);
    <br />
    }`

And you will see that it shows the domain of the deleted node

### Expected result

The domainservice to not return the domain of a deleted node.

### Actual result

It returns all domains on all nodes.

**Comment by nul800sebastiaan** [comment] 2020-08-11 12:00
Hi @joepvtl, this is very much on purpose, as long as a node is in the trash it will keep it's domain binding. This is especially important if something was trashed accidentally and gets moved back into the tree. 

Since this is expected behavior I'll close this issue.

**Closed by nul800sebastiaan** 2020-08-11 12:00 UTC

**Comment by joepvtl** [comment] 2020-08-11 12:17
Hi @nul800sebastiaan , thanks for the answer. But wouldn't it also be nice if there was a method on the DomainService to get domains that have been binded to nodes that are not in the recycle bin? So the domains you get are domains that have published content.

**Comment by nul800sebastiaan** [comment] 2020-08-11 12:20
I would need to know a bit more about the use case, what is the concrete example that you need this for please?
