### ISSUE TITLE
NuCache & Examine taking a long time to build on large websites

### ISSUE THREAD

**Issue by jt3432** [umbraco/Umbraco-CMS#13051] opened 2022-09-22 20:01 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

I have a large site that has ~200000 nodes. It taking about 30mins to start up on a local instance with a database installed locally as well. It is taking a bit over an hour with a VM and Azure SQL in the same region. This long startup time is causing issues in the Azure hosting environment. Azure App Services have a 230sec timeout that cannot be adjusted so using this method to host the site is failing epically. We are testing with hosting the site in a Linux VM (for cost reasons) but that is also proving to be a bit of a challenge. We suspect that even with a MS SQL database in the same azure region the latency is still too much during a fresh startup. Setting EnvironmentTemp help on sequential deployments. 

I did a little digging and I found this old v8 issue that was reported that is very similar to the one we are having minus the Azure stuff.

https://github.com/umbraco/Umbraco-CMS/issues/5925

What is interesting is that at the end of the thread it looks like the fix never was merged into the code. Would it be possible to find out if it ever was merged? Also, is there anyway to get Examine and NuCache to run in the back ground so that the site will return something instead of "spinning" for 30mins and cause timeouts? Thanks again.

### Steps to reproduce

Run a site with a lot of nodes. Very first load while the NuCache and Index build take a very long time.

### Expected result / actual result

Maybe build NuCache and Examine indexes in the back ground. Site should return a response to the browser indicating that cache and indexes are building instead of spinning.

**Comment by jt3432** [comment] 2022-09-23 17:21
This issue seems to be related: https://github.com/umbraco/Umbraco-CMS/issues/12159

**Comment by kjac** [comment] 2022-12-12 11:18
Hi @jt3432,

The code from https://github.com/umbraco/Umbraco-CMS/issues/5925 is indeed merged and part as V10 😄 

Just so I understand you correctly here; is the site slow on to start on _every_ boot or "only" if the Examine indexes are gone/not yet built (need rebuilding)?

**Comment by kjac** [comment] 2022-12-13 06:19
@jt3432 thank you for your quick response 👍 we're currently investigating our options for managing cache in another way. I'll make sure we bring this into that effort.

One way to verify if the culprit is indeed NuCache is to disable the Examine indexes entirely. If you're up for it I would really appreciate the insights - I'll post the code below.

Full disclaimer here: The code is a hacky, very non-supported way of short circuiting the Examine indexes. Don't use it in production 😆 

```csharp
using Examine;
using Umbraco.Cms.Core.Composing;

namespace My.Site.Examine;

public class DisableExamineComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
        => builder.Services.AddSingleton<IExamineManager, EmptyExamineManager>();
}

public class EmptyExamineManager : IExamineManager
{
    public void Dispose() {}

    public bool TryGetIndex(string indexName, out IIndex index)
    {
        index = null!;
        return false;
    }

    public bool TryGetSearcher(string searcherName, out ISearcher searcher)
    {
        searcher = null!;
        return false;
    }

    public IEnumerable<IIndex> Indexes => Array.Empty<IIndex>();

    public IEnumerable<ISearcher> RegisteredSearchers => Array.Empty<ISearcher>();
}
```

**Comment by jt3432** [comment] 2022-12-14 15:37
@dawoe Thanks for the suggestion, we have been on 10.3.2 since its release and still have the issue. Considering going to v11 to see if that has any impact. To give you an idea of the size of the sites we are working with, we have one site with ~200000 nodes and another with ~100000. 

@kjac I will not be able to get to it right away but I will try disabling the Examine index as soon as I can and see what the load time look like.

**Comment by kjac** [comment] 2023-01-10 05:48
Hi again @jt3432,

Just checking up - did you by any chance test if disabling the Examine indexes have any impact on load time?

**Comment by Zeegaan** [comment] 2023-01-27 08:50
Hey @jt3432 Since we haven't heard from you in a while, and we cannot reproduce this on our end, I am going to go ahead and close this 👍 
Feel free to re-open this if you find more information / reproduction steps 🐛

**Closed by Zeegaan** 2023-01-27 08:50 UTC
Labels: state/needs-more-info, type/bug

**Comment by jt3432** [comment] 2023-02-02 15:57
Sorry for the extreme delay for this replay, but wanted to close the loop here. I was not able to test disabling Examine for a cold start, but it has sort of become a none issue. We have been able to avoid most cold starts when deploying through a better configuration while hosting in Azure. We are seeing other performance issues, but I will create a separate issue to look into those. Good to keep this closed and just except that large sites will take longer to cold start, which sort of makes sense. Thanks.

**Comment by kjac** [comment] 2023-02-03 07:28
Thank you for getting back to us @jt3432 👏
