### ISSUE TITLE
V7 - bug create a link, for only navigate to anchor (on current page)

### ISSUE THREAD

**Issue by EmbraceSBS-Umbraco** [umbraco/Umbraco-CMS#5433] opened 2019-05-09 07:28 UTC
When a content editor create a link, for only navigate to anchor (on current page). The content editor fill an anchor and title, but this link don't appear in the source code. With Umbraco 7.7.13 was this still working, but after upgrade to newer version of Umbraco (7.14.0) the anchor does't working as expected.

Reproduction
------------

1. See video in create-link-to-anchor.zip
[create-link-to-anchor.zip](https://github.com/umbraco/Umbraco-CMS/files/3160777/create-link-to-anchor.zip)

2. See video https://we.tl/t-eROrdjidhL (comparison of Umbraco 7.7.13 and 7.14.0)

**Comment by nul800sebastiaan** [comment] 2019-05-09 07:31
Interesting, never knew this was possible! That answers https://github.com/umbraco/Umbraco-CMS/issues/5295 then.. I'll mark this as a duplicate of #5295

**Closed by nul800sebastiaan** 2019-05-09 07:31 UTC
