### ISSUE TITLE
Not show Label custom - Block list

### ISSUE THREAD

**Issue by thientu995** [umbraco/Umbraco-CMS#14176] opened 2023-04-27 13:16 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

When I input Label with code: {{$contentTypeName}} ({{$index}})
After add data for Block list this, it show title with code?

### Specifics

I have a Element Type, and add text Label field: {{$contentTypeName}} ({{$index}})
<img width="482" alt="image" src="https://user-images.githubusercontent.com/15050790/234869456-cdcd19f4-5edc-46ef-b551-e2010f52b586.png">

But, when I add new Item: title show text: {{$contentTypeName}} ({{$index}})
<img width="498" alt="image" src="https://user-images.githubusercontent.com/15050790/234869191-a6dfcb59-1269-4559-b77e-b43356c418f5.png">

After, it show correct:
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/15050790/234870121-a560b1f5-0b85-45ea-b67a-4e9362edd3d4.png">

### Steps to reproduce

https://user-images.githubusercontent.com/15050790/234873350-2a78cdbc-f4b6-4863-be93-5436b701eb42.mp4

### Expected result / actual result

title show text: {{$contentTypeName}} ({{$index}}) in correct with after save

---
_This item has been added to our backlog [AB#29190](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29190)_

**Comment by nikolajlauridsen** [comment] 2023-05-04 12:15
@thientu995 I just looked at this, and I can reproduce it. This has worked earlier, so I'll go ahead and mark this as regression, and we'll have a look at it in an upcoming sprint. 

To add a bit more information, this can be pretty easily reproduced using the block grid by using the sample blocks: 

![image](https://user-images.githubusercontent.com/16456704/236201014-0f0b55b8-4903-4f9c-9102-00f3cf539b42.png)

**Comment by iOvergaard** [comment] 2023-05-10 09:23
Testing this further, it seems to be exactly the same issue as described in #14105 which happens to have a proposed fix in #14143. I will go ahead and close this as duplicate and expect the issue to be fixed with #14143. Please re-open if you believe this information to be false ☺️

**Closed by iOvergaard** 2023-05-10 09:23 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11
