### ISSUE TITLE
Umbraco returns domain even if it doesn't exists

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11788] opened 2021-12-23 13:03 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

While investigating https://github.com/umbraco/Umbraco-CMS/issues/11787, we also found another issue on v9. We have a website with 2 languages (en-US & nl-NL). Our website is a multi language & multi country website, so we have multiple homepages on the root.

Now in v9, we are facing the following issue. Even though we only have 1 domain setup for a homepage (NL-NL):
![image](https://user-images.githubusercontent.com/11466511/147241845-006f0f01-ae32-4de2-a2ab-98d1a62b6922.png)
It will still show the url for the language that doesn't have the domain setup:
![image](https://user-images.githubusercontent.com/11466511/147244099-611d01e5-0df6-4db4-8bd5-a1159000188d.png)

And this is only with the default language for some reason. If I turn it around and make the en-US language the only domain, it will not show the nl-NL variant with an URL. 

### Steps to reproduce

- Create a new v9 installation
- Add a new language
- Add a document type with varied for culture enabled
- Create a new page with both languages
- Add the non-default language as a domain to the page
- Refresh the page
- See that the default language that does **not** have a domain still have an URL listed that actually works.

### Expected result / actual result

Page shouldn't have an URL if there is no domain connected to it.

**Comment by nul800sebastiaan** [comment] 2022-01-03 13:50
Unfortunately that's not how it works.. If you don't want a page to get a URL then don't publish it. 😅 If you publish it we try very hard to give it a URL because clearly you wanted it to be publicly available.

I believe, indeed, the fallback is always to the default language.

Really not sure what you're trying to accomplish here but for sites with language variants we would recommend configuring a route (`/nl`) or actual domain for each language. If you do not, Umbraco doesn't know how to route pages properly and is preventing you from doing so (as you've noticed). 

I would recommend you post your specific scenario on the forum to maybe get some help there, it seems like an uncommon scenario but maybe other people already found how to do what you're trying to do. 

I'll close this for now as what you're seeing is expected behavior.

**Closed by nul800sebastiaan** 2022-01-03 13:50 UTC
Labels: type/bug

**Comment by patrickdemooij9** [comment] 2022-01-03 14:08
Hmm, I guess I would expect the link only to be shown if it has a domain, but I guess I can live with it. However, I do think there is still a difference with how v8 handled this.

If I take a look at an v8 project that has the exact same situation (Node with default language is published, but domain is on another language)
![image](https://user-images.githubusercontent.com/11466511/147939918-98bd5848-a478-46fc-827f-983b4b18ce80.png)

It shows the URL (which is the desired solution), but the URL doesn't use the name of the node, but instead takes it from somewhere else:
![image](https://user-images.githubusercontent.com/11466511/147939991-ec47cc5d-4052-468e-9c54-33014417f67f.png)

I assume that it is taking it from the other domain as we don't have any UrlProviders in that project. If I would do this with the v9 installation, I would expect there to be /homepage-czech-republic.

**Comment by nul800sebastiaan** [comment] 2022-01-03 14:12
I think that something with `HideTopLevelNodeFromPath` - which has changed to be `true` by default in v9 https://our.umbraco.com/Documentation/UmbracoNetCoreUpdates#changes-between-beta-1-and-beta-2

**Comment by patrickdemooij9** [comment] 2022-01-03 14:21
Tried changing it on v8, but still showed the /nl-nl. However, it doesn't really matter here (I think). Just a bit confused with all the domain stuff. Especially with that fallback in place.

As when publishing the original v9 setup, it does show this warning about the domain not being setup:
![image](https://user-images.githubusercontent.com/11466511/147941464-c0fa56dc-1120-4b52-90e9-3269b02dadf9.png)

Even though the url just works without domain anyway.
