### ISSUE TITLE
Process hangs when updating "Allowed child node types"

### ISSUE THREAD

**Issue by bagaag** [umbraco/Umbraco-CMS#11023] opened 2021-09-03 03:16 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002

### Bug summary

The application hangs (does not crash, but spins indefinitely and becomes unresponsive) if "Allowed child node types" is updated for a Document Type that allows itself as a child node and this relationship is used by existing content in the tree.

### Steps to reproduce

1. Create a Document Type with Template and allow creation at root
2. Add itself under "Allowed child node types" and save
3. Create a second Document Type with Template
4. Create a Content item of the first type at the root, then create another content item of the same type under it as a child
5. Attempt to add the second Document type to the first type's "Allowed child node types" and save OR attempt to remove the first type from itself in "Allowed child node types"
6. Clicking save hangs the process

Only after deleting the child node and emptying the recycle bin can the recursive Document Type's "Allowed child node types" property be modified and saved.

### Expected result / actual result

I expected to either get a validation error or have the Document Type save successfully. Instead, the process hangs with the spinner replacing the Save button remaining indefinitely. The app must be restarted to recover.

**Comment by nul800sebastiaan** [comment] 2021-09-03 06:38
Hey there @bagaag, unfortunately I can't reproduce this scenario, or I'm doing it wrong (very possible! 😉). I've recorded my steps, can you spot if I'm doing anything different?

https://user-images.githubusercontent.com/304656/131961260-aea3e4f5-0e91-479f-9e9b-1217432bd695.mp4


I'll close this one for now but happy to try again if you can tell me what I'm missing! 👍

**Closed by nul800sebastiaan** 2021-09-03 06:38 UTC
Labels: type/bug

**Comment by bagaag** [comment] 2021-09-04 13:48
Thanks for taking a look, Sebastian. I'm able to reproduce this in most cases using the same steps shown in your video, but it is proving to be inconsistent and I haven't been able to determine what makes it happen sometimes and not others. 

As I've continued development, I find saving document types hangs up in other situations as well when there is no recursive allowance. So it seems likely there are multiple different things going on here. Sometimes I get a SQL timeout, which is probably the same issue reported in #10362. Here's an example of the log entry for that scenario:

`
{"@t":"2021-09-04T01:13:58.9382775Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.\r\n ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteScalar()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func'1 func)\r\n   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)\r\n   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)\r\nClientConnectionId:91a9ef42-3c36-4440-ae5c-24f9cc9e9e3c\r\nError Number:-2,State:0,Class:11","InstanceId":"4f54826c","SourceContext":"Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase","ActionId":"1ea2a5a6-ae65-4247-9f11-17e916a607f8","ActionName":"Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeController.AllowsCultureVariation (Umbraco.Web.BackOffice)","RequestId":"80000045-0002-fe00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/umbracoapi/contenttype/AllowsCultureVariation","ProcessId":18608,"ProcessName":"iisexpress","ThreadId":261,"AppDomainId":1,"AppDomainAppId":"7c5b9bae3645fe004b4e13efb0d8d8e0181edb1e","MachineName":"BODHI-WINDOWS","Log4NetLevel":"ERROR","HttpRequestId":"8895c775-da53-434a-a2be-233deb31356f","HttpRequestNumber":3,"HttpSessionId":"432d7fff-bd34-d419-0b2b-913ffc6d7ad4"}
`

And sometimes I get a routing error, which is odd because why would my front-end controller be getting invoked at all when saving a Document Type on the back end (and this controller works fine on the front end). 

`
{"@t":"2021-09-02T02:29:33.4217431Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: \r\n\r\nMemoryUmbraco9.Controllers.ContentPageController.Index (MemoryUmbraco9)\r\nMemoryUmbraco9.Controllers.ContentPageController.Index (MemoryUmbraco9)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)\r\n   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)\r\n   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)\r\n   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)\r\n   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\\projects\\dotnet\\src\\MiniProfiler.AspNetCore\\MiniProfilerMiddleware.cs:line 119\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"800000ab-0001-fd00-b63f-84710c7967bb","RequestPath":"/","ProcessId":10728,"ProcessName":"iisexpress","ThreadId":9,"AppDomainId":1,"AppDomainAppId":"d4f2f2734ea1c1fb088b9ea84437b7045f08ac11","MachineName":"BODHI-WINDOWS","Log4NetLevel":"ERROR"}
`

And in both of these cases, the user experience differs from time to time. Sometimes I get an error displayed and sometimes it just spins for a very very long time (several minutes) before finally succeeding. Sorry this is a bit all over the place. I'll continue to observe the behavior and if I can pin it down a bit more I'll update here.
