### ISSUE TITLE
Tabs disappearing act!

### ISSUE THREAD

**Issue by bourpie** [umbraco/Umbraco-CMS#6198] opened 2019-08-26 12:08 UTC
A collegue of mine sent me this screen capture. I have not been able to reproduce it. Has this happened to anyone?

![tabs-are-missing](https://user-images.githubusercontent.com/4865432/63689703-b086d300-c7d8-11e9-81cb-d8d42b42184b.gif)

**Comment by abjerner** [comment] 2019-08-26 12:15
Hi @bourpie,

What version of Umbraco 8 is this?

And do you by any chance have a screenshot of the full page (that would help with debugging)? The screenshot doesn't show the right part the the screen/monitor, which should be where the tabs are located.

**Comment by bourpie** [comment] 2019-08-26 23:10
Unfortunately that's what I got from my friend. Sorry. I asked her to come
get me next time it happens. Apparently, it happened a few times when she
came back after some time of no activity.

Le lun. 26 août 2019 8:15 a.m., Anders Bjerner <notifications@github.com> a
écrit :

**Comment by abjerner** [comment] 2019-08-27 06:41
@bourpie Ok - no worries. I'll close the issue for now as I can't reproduce it.

If your colleague comes back with more information, we can re-open the issue and have another look at it 😉

**Closed by abjerner** 2019-08-27 06:41 UTC

**Comment by bourpie** [comment] 2019-08-27 07:29
I understand. Thank you.

Pierre

Le mar. 27 août 2019 2:42 a.m., Anders Bjerner <notifications@github.com> a
écrit :
