### ISSUE TITLE
UmbracoApi's GetPagedReferencedItems() times out when querying moderate numbers of relations

### ISSUE THREAD

**Issue by digbyswift** [umbraco/Umbraco-CMS#12489] opened 2022-05-25 19:34 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2 & 9.4.3

### Bug summary

When deleting a batch of images in the backoffice, the popup that appears never shows the "Delete" button, just the loading dots.

In the browser console we can see that the POSTed request umbraco/backoffice/umbracoapi/trackedreferences/GetPagedReferencedItems?entityType=undefined&pageNumber=undefined&pageSize=undefined is being made but returning a 500 timeout error:

 > Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."

Reviewing the database, we can see that the following query is timing out:

```
SELECT COUNT(*) FROM (
	SELECT DISTINCT
		[pn].[id] as nodeId, [pn].[uniqueId] as nodeKey, [pn].[text] as nodeName, [pn].[nodeObjectType] as nodeObjectType,
		[ct].[icon] as contentTypeIcon, [ct].[alias] as contentTypeAlias,
		[ctn].[text] as contentTypeName,
		[umbracoRelationType].[alias] as relationTypeAlias, [umbracoRelationType].[name] as relationTypeName,
		[umbracoRelationType].[isDependency] as relationTypeIsDependency, [umbracoRelationType].[dual] as relationTypeIsBidirectional
	FROM [umbracoRelation] [r]
	INNER JOIN [umbracoRelationType] [umbracoRelationType] ON ([r].[relType] = [umbracoRelationType].[id])
	INNER JOIN [umbracoNode] [cn] ON (([umbracoRelationType].[dual] = 1 AND ([r].[parentId] = [cn].[id])) OR ([umbracoRelationType].[dual] = 1 AND (([r].[childId] = [cn].[id]) OR ([r].[parentId] = [cn].[id]))))
	INNER JOIN [umbracoNode] [pn] ON ((([pn].[id] = [r].[childId]) AND ([cn].[id] = [r].[parentId])) OR (([pn].[id] = [r].[parentId]) AND ([cn].[id] = [r].[childId])))
	LEFT JOIN [umbracoContent] [c] ON ([pn].[id] = [c].[nodeId])
	LEFT JOIN [cmsContentType] [ct] ON ([c].[contentTypeId] = [ct].[nodeId])
	LEFT JOIN [umbracoNode] [ctn] ON ([ct].[nodeId] = [ctn].[id])
	WHERE ([pn].[id] IN (@id)) AND ([umbracoRelationType].[isDependency] = 1)
) npoco_tbl
```

### Specifics

The database in question is an Azure SQL S3 and I can see that the compute utilization/DTUs are maxing out, corresponding with the running of the query.

If the query is run against the database directly using SSMS, the query actually runs perfectly fine.

If we pull down a copy of the database and attempt the same action in the backoffice locally, we see a slowness although no timeout. 

There are currently over 11,000 rows in the [umbracoRelation] table and approx 55,000 records in the [umbracoNode] table.

### Steps to reproduce

I don't expect this issue to be reproducible in a clean install.

**Comment by Ambertvu** [comment] 2022-05-25 19:51
Think this is related to https://github.com/umbraco/Umbraco-CMS/issues/12308 which should be fixed in 9.5.1

**Comment by digbyswift** [comment] 2022-05-26 09:02
@Ambertvu It does appear that way. Thanks for the link. We'll test again with 9.5.1 then once we're able to upgrade.

**Comment by nul800sebastiaan** [comment] 2022-05-26 09:16
Thanks! I'll close as duplicate of https://github.com/umbraco/Umbraco-CMS/issues/12308

**Closed by nul800sebastiaan** 2022-05-26 09:16 UTC
Labels: type/bug
