### ISSUE TITLE
Failed to acquire write lock for id: -333.

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#14705] opened 2023-08-21 14:00 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

We have an issue where it looks like randomaly locks our solution so we can't publish with the log error:

**Failed to acquire write lock for id: -333.**

I have tried restart the solution, clear temp etc.

I'm getting diffrent issues in the lock:

   `Microsoft.Data.SqlClient.SqlException (0x80131904): Lock request time out period exceeded.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
ClientConnectionId:01f07cad-18b0-419e-8daa-2aba187e5b93
Error Number:1222,State:51,Class:16`

And also:

  `Umbraco.Cms.Core.DistributedLocking.Exceptions.DistributedWriteLockTimeoutException: Failed to acquire write lock for id: -333.
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock..ctor(SqlServerDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentVersionRepository.DeleteVersions(IEnumerable`1 versionIds)
   at Umbraco.Cms.Core.Services.ContentVersionService.CleanupDocumentVersions(DateTime asAtDate)
   at Umbraco.Cms.Core.Services.ContentVersionService.PerformContentVersionCleanup(DateTime asAtDate)
   at Umbraco.Cms.Infrastructure.HostedServices.ContentVersionCleanup.PerformExecuteAsync(Object state)
   at Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase.ExecuteAsync(Object state)`

### Specifics

It happens after some time of generate some content on the solution.

### Steps to reproduce

We have a running solution with a lot of nodes (10.000) and around 66.000 medias

When trying to run Health check "**Data integrity**" it fails with error:

`Umbraco.Cms.Core.DistributedLocking.Exceptions.DistributedWriteLockTimeoutException: Failed to acquire write lock for id: -333.
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock..ctor(SqlServerDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.CheckDataIntegrity(ContentDataIntegrityReportOptions options)
   at Umbraco.Cms.Core.Services.ContentService.CheckDataIntegrity(ContentDataIntegrityReportOptions options)
   at Umbraco.Cms.Core.HealthChecks.Checks.Data.DatabaseIntegrityCheck.<>c__DisplayClass11_0.<CheckDocuments>b__0()
   at Umbraco.Cms.Core.HealthChecks.Checks.Data.DatabaseIntegrityCheck.CheckPaths(String actionAlias, String actionName, String entityType, Boolean detailedReport, Func`1 doCheck)
   at Umbraco.Cms.Core.HealthChecks.Checks.Data.DatabaseIntegrityCheck.CheckDocuments(Boolean fix)
   at Umbraco.Cms.Core.HealthChecks.Checks.Data.DatabaseIntegrityCheck.GetStatus()
   at Umbraco.Cms.Web.BackOffice.HealthChecks.HealthCheckController.GetStatus(Guid id)`

### Expected result / actual result

Being able to publish nodes og solution running smoothly

The site on the frontend runs fine, it's only in the backoffice..

**Comment by thomashdk** [comment] 2023-08-21 14:27
I have 11 other solution running on the same code. But the issue is only on this one solution...

**Comment by andr317c** [comment] 2023-08-22 06:19
Hey!

This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/14195 I will go ahead and close this

**Closed by andr317c** 2023-08-22 06:19 UTC
Labels: type/bug
