### ISSUE TITLE
Add image captions in RTE

### ISSUE THREAD

**Issue by lcichanowicz** [umbraco/Umbraco-CMS#2945] opened 2018-09-07 16:21 UTC
It would be great if the `umbmediapicker` supported image captions the way the native TinyMCE image plugin does.

https://www.tiny.cloud/docs/plugins/image/#image_caption

**Comment by nul800sebastiaan** [comment] 2019-03-14 20:34
It's a great suggestion, would be great to have. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nathanwoulfe** [comment] 2019-06-07 05:15
#5607 resolves this as part of allowing editing alt text/caption on grid/rte images

**Comment by nul800sebastiaan** [comment] 2019-08-29 19:27
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-08-29 19:27 UTC
Labels: community/up-for-grabs, help wanted, type/feature

**Comment by c9mbundy** [comment] 2019-12-04 20:56
Some comments on this issue.

I've been looking at this recently, as I'm getting push-back from my site's content admins about the rt-editor. WordPress always seems to be used as the benchmark for comparison (Umbraco doesn't do this but WP...) and the reality is that WP also uses tinyMCE, just configured with more custom functionality, including a heap of macros.

None of my site's content editors are comfortable with direct html editing, but that's pretty much what this content requirement involves. Many of the sites currently on V7 will not be contemplating replacement for at least a few years, so I need to find a resolution to this so we are considered favorably at that time.

A grid-only solution is not sufficient for my needs (nor I suspect most content admins) as it's an essential for many applications of RTE, including blog-posts.

WordPress handles this using a custom tinyMCE plugin that converts the image to a div with a dl/dt/dd structure - it works, but is an ugly solution.

However, TinyMCE's image plugin natively supports adding a caption to an image with the "image_caption" parameter, at which time the img element is converted to figure-img-figcap block - obviously preferable:  [www.tiny.cloud/docs/plugins/image/#image_caption](url)

I can't see how it can be done using tinyMceConfig.config, as there seems to be no support for additional tinyMceCommand attributes in the "mceImage" command.
 
I contemplated just using a backoffice extension script to add the functionality (rather than risk modifying Umbraco) but couldn't find where the image plugin is initialised/configured in Umbraco, and trying to read/understand the files /Umbraco/js/umbraco.controllers.js, umbraco.directives.js, umbraco.services.js just makes my head hurt... 

Obviously if the Umbraco insert-media dialog was enhanced to support caption, title, alignment, etc (as per wordpress) this would be great, but alternatively (perhaps additionally?) this could be done using a pop-up dialog activated by right-click on an inserted image (as per WordPress) so you can modify an existing image, and still add media using the existing Umbraco dialog.

**Comment by nathanwoulfe** [comment] 2019-12-04 21:05
Have a look at my changes in #5607 - was a while back, but from memory they resolve these issues. Might revisit it when I have time

**Comment by c9mbundy** [comment] 2019-12-15 21:44
Apologies for the tardy response - clients that expect me to actually do some work!
Anyway, #5607 looks like it addresses the same concerns, that the ability to create/update the alt and caption be via an extension of the editor rather than grid-specific - e.g. be able to use the same functionality in say a blog-post to insert an image and then decide it needs to be a figure by adding a caption and/or editing the alt/caption after the image has been inserted without resorting to html edit mode. This functionality is built into tinyMCE but it's a matter of tapping into it from Umbraco. Unfortunately I'm still building with V7 so I'm not expecting to see a solution there, but V8, the greater good and all that...
