### ISSUE TITLE
Update Umbraco 8.16.0 to Umbraco 9.1.1

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#11723] opened 2021-12-03 10:08 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 8.16.0 to Umbraco 9.1.1

### Bug summary

When upgrading Umbraco from 8.16.0 to 9.1.1 fails on installations.

### Specifics

I tried to update from 8.16.0 to 9.1.1 and on install it fails.

The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'cmsContentType' that match the referencing column list in the foreign key 'FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId'. Could not create constraint or index. See previous errors. Please check log file for additional information (can be found in '~/umbraco/Logs')

![image](https://user-images.githubusercontent.com/6445636/144585017-f769055a-06c4-4ddf-9844-665af0728bb2.png)
![image](https://user-images.githubusercontent.com/6445636/144584179-46e7dc87-ee68-469d-b5da-bc369751f10b.png)

I have tried to update step by step:

8.16.0 > 9.0.0 Worked
9.0.0 > 9.0.1 Worked:
9.01 > 9.1.0 Failed with:

`ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'cmsContentType' that match the referencing column list in the foreign key 'FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId'.`

From the log:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Umbraco.Cms.Core.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'cmsContentType' that match the referencing column list in the foreign key 'FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId'.
Could not create constraint or index. See previous errors.
 Please check log file for additional information (can be found in '~/umbraco/Logs')
   at Umbraco.Cms.Infrastructure.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.ExecuteStepAsync(InstallSetupStep step, Object instruction)
   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.PostPerformInstall(InstallInstructions installModel)`

![image](https://user-images.githubusercontent.com/6445636/144584868-c4403386-9bc3-499c-b03a-4568a45b2bda.png)

### Steps to reproduce

Update from 
8.16.0 > 9.0.0,
9.0.0 > 9.0.1,
9.01 > 9.1.0

or update from 8.16.0 to 9.1.1 directly.

### Expected result / actual result

Expected Ubmraco 9.1.1 to be installed.

**Comment by thomashdk** [comment] 2021-12-09 14:36
Same issue from 8.16 to 9.1.2

![image](https://user-images.githubusercontent.com/6445636/145416145-a4552bc9-e072-466a-a8e4-6ee941c734bc.png)

**Comment by thomashdk** [comment] 2021-12-10 08:53
When I connect my 8.16 database to my Umbraco 9.1.2 solution and getting the login screen to start the upgrade, the user password are not working, but need to reset it before it works. After that I get the error as above.

**Comment by thomashdk** [comment] 2021-12-10 08:57
Also gettings this.

**`The database schema validation produced the following summary: "The following tables were found in the database, but are not in the current schema:
 SEOChecker_Queue,SEOChecker_ScheduledValidation,SEOChecker_ValidationIssues,SkyfishLogin,UCErrorLog,UFRecordDataBit,UFRecordDataDateTime,UFRecordDataInteger,UFRecordDataLongString,UFRecordDataString,UFRecordFields,UFRecords,UFUserFormSecurity,UFUserSecurity,LdapUsers,umbracoDeployDependency,umbracoDeploySignature,CabanaRedirects,_TransactionIndex_098b082c-5e66-4ac1-8764-54e6a19e957f,PageCounter,UserDashboard,SiteImprove_settings,SiteImproveUrlMap,FeedbackComments,MessageWallLikes,MessageWallPosts,NodeMediaLog,PageEditorComments,RestrictBackofficeTable,SEOChecker_Configuration,SEOChecker_ConfigurationIssues,SEOChecker_Notifications,SEOChecker_PageNotFound,umbracoExternalLoginToken,umbracoLogViewerQuery,umbracoContentVersionCleanupPolicy
 
 The following columns were found in the database, but are not in the current schema:
 SEOChecker_Queue,DocumentID,SEOChecker_Queue,QueuedDateTime,SEOChecker_Queue,Priority,SEOChecker_ScheduledValidation,Id,SEOChecker_ScheduledValidation,TaskName,SEOChecker_ScheduledValidation,NotificationEmailAddress,SEOChecker_ScheduledValidation,ExecuteEvery,SEOChecker_ScheduledValidation,ExecuteDays,SEOChecker_ScheduledValidation,ExecuteHour,SEOChecker_ScheduledValidation,ExecuteMinute,SEOChecker_ScheduledValidation,ValidationRoot,SEOChecker_ScheduledValidation,IncludeChildren,SEOChecker_ScheduledValidation,NextRun,SEOChecker_ScheduledValidation,LastTimeExecuted,SEOChecker_ValidationIssues,IssueId,SEOChecker_ValidationIssues,DocumentID,SEOChecker_ValidationIssues,ErrorCode,SEOChecker_ValidationIssues,ValidatorAlias,SEOChecker_ValidationIssues,ErrorDescription,SEOChecker_ValidationIssues,Error,SEOChecker_ValidationIssues,Template,SEOChecker_ValidationIssues,Category,SEOChecker_ValidationIssues,ValidationType,SEOChecker_ValidationIssues,ErrorType,SEOChecker_ValidationIssues,PropertyAlias,SEOChecker_ValidationIssues,CrawlDate,SEOChecker_ValidationIssues,ResolvedDate,SEOChecker_ValidationIssues,Ignore,SkyfishLogin,Id,SkyfishLogin,Username,SkyfishLogin,Password,SkyfishLogin,Secret,SkyfishLogin,Api,SkyfishLogin,Token,SkyfishLogin,ExpireDateToken,UCErrorLog,Id,UCErrorLog,Date,UCErrorLog,Thread,UCErrorLog,Level,UCErrorLog,Logger,UCErrorLog,Message,UCErrorLog,Exception,UCErrorLog,ThreadId,UCErrorLog,SourceContext,UCErrorLog,ReadBy,UCErrorLog,Read,UFRecordDataBit,Id,UFRecordDataBit,Key,UFRecordDataBit,Value,UFRecordDataDateTime,Id,UFRecordDataDateTime,Key,UFRecordDataDateTime,Value,UFRecordDataInteger,Id,UFRecordDataInteger,Key,UFRecordDataInteger,Value,UFRecordDataLongString,Id,UFRecordDataLongString,Key,UFRecordDataLongString,Value,UFRecordDataString,Id,UFRecordDataString,Key,UFRecordDataString,Value,UFRecordFields,Key,UFRecordFields,FieldId,UFRecordFields,Record,UFRecordFields,Alias,UFRecordFields,DataType,UFRecords,Id,UFRecords,Form,UFRecords,Created,UFRecords,Updated,UFRecords,CurrentPage,UFRecords,UmbracoPageId,UFRecords,IP,UFRecords,MemberKey,UFRecords,UniqueId,UFRecords,State,UFRecords,RecordData,UFUserFormSecurity,Id,UFUserFormSecurity,User,UFUserFormSecurity,Form,UFUserFormSecurity,HasAccess,UFUserFormSecurity,AllowInEditor,UFUserFormSecurity,SecurityType,UFUserSecurity,User,UFUserSecurity,ManageDataSources,UFUserSecurity,ManagePreValueSources,UFUserSecurity,ManageWorkflows,UFUserSecurity,ManageForms,LdapUsers,UserId,LdapUsers,UserAlias,LdapUsers,FirstName,LdapUsers,LastName,LdapUsers,Email,LdapUsers,TelephoneNumber,LdapUsers,MobileNumber,LdapUsers,JobTitle,LdapUsers,Departments,LdapUsers,Interests,LdapUsers,ProfileImage,LdapUsers,PersonText,LdapUsers,PersonLink,LdapUsers,IsEditor,LdapUsers,IsAdmin,LdapUsers,LastUpdated,LdapUsers,Created,LdapUsers,MainDepartment,umbracoDeployDependency,sourceUdi,umbracoDeployDependency,targetUdi,umbracoDeployDependency,ordering,umbracoDeployDependency,mode,umbracoDeploySignature,udi,umbracoDeploySignature,nodeId,umbracoDeploySignature,checksum,CabanaRedirects,Id,CabanaRedirects,Date,CabanaRedirects,OldUrl,CabanaRedirects,NewUrl,CabanaRedirects,Accessed,CabanaRedirects,WildCard,CabanaRedirects,LastReference,CabanaRedirects,LastReferenceDate,CabanaRedirects,CreatedBy,umbracoServer,isMaster,_TransactionIndex_098b082c-5e66-4ac1-8764-54e6a19e957f,Id,PageCounter,Id,PageCounter,Date,PageCounter,PageId,PageCounter,Uniq,UserDashboard,Id,UserDashboard,UserID,UserDashboard,Links,SiteImprove_settings,id,SiteImprove_settings,Token,SiteImprove_settings,Installed,SiteImproveUrlMap,id,SiteImproveUrlMap,CurrentUrlPart,SiteImproveUrlMap,NewUrlPart,SiteImproveUrlMap,PageId,FeedbackComments,Id,FeedbackComments,Date,FeedbackComments,PageId,FeedbackComments,Name,FeedbackComments,Email,FeedbackComments,Comment,FeedbackComments,Feedback,FeedbackComments,Reference,FeedbackComments,Lang,FeedbackComments,ScreenWidth,MessageWallLikes,Id,MessageWallLikes,RelatedPostId,MessageWallLikes,UserAlias,MessageWallPosts,Id,MessageWallPosts,RelatedPostId,MessageWallPosts,IsGlobal,MessageWallPosts,InterestAreas,MessageWallPosts,Date,MessageWallPosts,ExpireDate,MessageWallPosts,UserAlias,MessageWallPosts,Message,MessageWallPosts,FileId,NodeMediaLog,id,NodeMediaLog,date,NodeMediaLog,userId,NodeMediaLog,userName,NodeMediaLog,nodeId,NodeMediaLog,nodeName,NodeMediaLog,type,NodeMediaLog,action,PageEditorComments,Id,PageEditorComments,PageId,PageEditorComments,Username,PageEditorComments,Comment,PageEditorComments,Date,RestrictBackofficeTable,Id,RestrictBackofficeTable,Date,RestrictBackofficeTable,AddedByUserId,RestrictBackofficeTable,Name,RestrictBackofficeTable,UserGroupAlias,RestrictBackofficeTable,PageAlias,RestrictBackofficeTable,Tabs,RestrictBackofficeTable,Fields,RestrictBackofficeTable,Components,SEOChecker_Configuration,ConfigId,SEOChecker_Configuration,Name,SEOChecker_Configuration,Configuration,SEOChecker_Configuration,LastSave,SEOChecker_ConfigurationIssues,IssueId,SEOChecker_ConfigurationIssues,ErrorCode,SEOChecker_ConfigurationIssues,ValidatorAlias,SEOChecker_ConfigurationIssues,ErrorDescription,SEOChecker_ConfigurationIssues,Error,SEOChecker_ConfigurationIssues,ErrorType,SEOChecker_ConfigurationIssues,Category,SEOChecker_ConfigurationIssues,CrawlDate,SEOChecker_ConfigurationIssues,ResolvedDate,SEOChecker_ConfigurationIssues,Ignore,SEOChecker_Notifications,Id,SEOChecker_Notifications,NotificationUser,SEOChecker_Notifications,ExecuteEvery,SEOChecker_Notifications,ExecuteDays,SEOChecker_Notifications,ExecuteHour,SEOChecker_Notifications,ExecuteMinute,SEOChecker_Notifications,NextRun,SEOChecker_PageNotFound,NotFoundId,SEOChecker_PageNotFound,Url,SEOChecker_PageNotFound,DocumentID,SEOChecker_PageNotFound,Ignore,SEOChecker_PageNotFound,TimesAccessed,SEOChecker_PageNotFound,LastTimeAccessed,SEOChecker_PageNotFound,RedirectUrl,SEOChecker_PageNotFound,Referer,SEOChecker_PageNotFound,ContentType,SEOChecker_PageNotFound,Domain,SEOChecker_PageNotFound,QueryString,SEOChecker_PageNotFound,WildCard,umbracoContentVersion,preventCleanup,cmsMember,passwordConfig,cmsMember,securityStampToken,cmsMember,emailConfirmedDate,umbracoServer,isSchedulingPublisher,umbracoExternalLoginToken,id,umbracoExternalLoginToken,externalLoginId,umbracoExternalLoginToken,name,umbracoExternalLoginToken,value,umbracoExternalLoginToken,createDate,umbracoLogViewerQuery,id,umbracoLogViewerQuery,name,umbracoLogViewerQuery,query,umbracoContentVersionCleanupPolicy,contentTypeId,umbracoContentVersionCleanupPolicy,preventCleanup,umbracoContentVersionCleanupPolicy,keepAllVersionsNewerThanDays,umbracoContentVersionCleanupPolicy,keepLatestVersionPerDayForDays,umbracoContentVersionCleanupPolicy,updated
 
 The following constraints (Primary Keys, Foreign Keys and Indexes) were found in the database, but are not in the current schema:
 FK_UFRecordDataBit_UFRecordFields_Key,FK_UFRecordDataDateTime_UFRecordFields_Key,FK_UFRecordDataInteger_UFRecordFields_Key,FK_UFRecordDataLongString_UFRecordFields_Key,FK_UFRecordDataString_UFRecordFields_Key,FK_UFRecordFields_UFRecords_Record,FK_umbracoExternalLoginToken_umbracoExternalLogin_id,FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId,PK___Transac__3214EC07CC590AE3,PK__LdapUser__1788CC4C42AE67EF,PK__UCErrorL__3214EC0742CAAE70,PK_CabanaRedirects,PK_deployDependency,PK_deploySignature,PK_FeedbackComments,PK_id,PK_MessageWallLikes,PK_MessageWallPosts,PK_PageCounter,PK_PageEditorComments,PK_RestrictBackofficeTable,PK_SEOChecker_Configuration,PK_SEOChecker_ConfigurationIssues,PK_SEOChecker_Notifications,PK_SEOChecker_PageNotFound,PK_SEOChecker_ScheduledValidation,PK_SEOChecker_ValidationIssues,PK_SiteImprove_settings,PK_SiteImproveUrlMap,PK_SkyfishLogin,PK_UFRecordDataBit,PK_UFRecordDataDateTime,PK_UFRecordDataInteger,PK_UFRecordDataLongString,PK_UFRecordDataString,PK_UFRecordFields,PK_UFRecords,PK_UFUserFormSecurity,PK_UserDashboard,PK_umbracoExternalLoginToken,PK_umbracoLogViewerQuery
 
 The following indexes were found in the database, but are not in the current schema:
 UmbracoCloud_DateRead,IX_UFRecordDataBit_Key,IX_UFRecordDataDateTime_Key,IX_UFRecordDataInteger_Key,IX_UFRecordDataLongString_Key,IX_datastring_recordfield,IX_record_recordfield,UK_UFUserFormSecurity_User_Form,IX_cmsLanguageText_languageId,IX_umbracoExternalLogin_userId,IX_umbracoExternalLogin_LoginProvider,IX_umbracoExternalLogin_ProviderKey,IX_umbracoExternalLoginToken_Name,IX_LogViewerQuery_name
 
 The following unknown constraints (Primary Keys, Foreign Keys and Indexes) were found in the database, but are not in the current schema:
 UK_UFUserFormSecurity_User_Form
 `**

**Comment by thomashdk** [comment] 2021-12-10 10:01
Looks like running this 

`/****** Object:  Table [dbo].[umbracoContentVersionCleanupPolicy]    Script Date: 10-12-2021 11:00:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[umbracoContentVersionCleanupPolicy](
	[contentTypeId] [int] NOT NULL,
	[preventCleanup] [bit] NOT NULL,
	[keepAllVersionsNewerThanDays] [int] NULL,
	[keepLatestVersionPerDayForDays] [int] NULL,
	[updated] [datetime] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH CHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY([contentTypeId])
REFERENCES [dbo].[cmsContentType] ([nodeId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
GO`

And then reload the installation site again works.

**Comment by p-m-j** [comment] 2021-12-13 11:02
Hey @thomashdk, I'm sorry to hear about your pain upgrading :(

I tried to reproduce by creating 8.16.0 site with starter template and then:
Updating to 9.0.0 -> 9.0.1 -> 9.1.0 -> 9.1.1 -> 9.1.2

Everything worked just fine

Additionally I tried from 8.16.0 -> 9.1.2 which was also fine.

I had no issues with database migrations or user logins.

Are you able to provide any additional details / steps to reproduce?

**Comment by thomashdk** [comment] 2021-12-15 14:23
Hmm sadly no.
I have some custom table in the db? Not sure if that could have something to do with it

**Comment by nul800sebastiaan** [comment] 2022-01-04 15:35
Hmmm, a mystery for now! I'll close this one as it looks like you're up and running now, but we might need to re-open if other people have this problem and can provide more info!

**Closed by nul800sebastiaan** 2022-01-04 15:35 UTC
Labels: type/bug

**Comment by qamarkhan84** [comment] 2022-02-14 16:02
Hi there ,
I am upgrading umbraco from version  8.17.1  to version 9.1.2. I am getting following error

**Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'umbracoContentVersionCleanupPolicy'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()**

**Comment by qamarkhan84** [comment] 2022-02-14 19:28
I found that root cause of this is that in my startup.cs  before the line  u.UseInstallerEndpoints();
I had some custom logic to register routing logic, which was blocking to migration starup.

**Comment by sumeyyeclockwork** [comment] 2022-03-07 10:03
I am upgrading umbraco 8.16 to 8.18 and getting same SQL error

**Comment by sumeyyeclockwork** [comment] 2022-03-07 10:04
> Looks like running this
> 
> ```sql
> /****** Object:  Table [dbo].[umbracoContentVersionCleanupPolicy]    Script Date: 10-12-2021 11:00:04 ******/
> SET ANSI_NULLS ON
> GO
> 
> SET QUOTED_IDENTIFIER ON
> GO
> 
> CREATE TABLE [dbo].[umbracoContentVersionCleanupPolicy](
> 	[contentTypeId] [int] NOT NULL,
> 	[preventCleanup] [bit] NOT NULL,
> 	[keepAllVersionsNewerThanDays] [int] NULL,
> 	[keepLatestVersionPerDayForDays] [int] NULL,
> 	[updated] [datetime] NOT NULL
> ) ON [PRIMARY]
> GO
> 
> ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH CHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY([contentTypeId])
> REFERENCES [dbo].[cmsContentType] ([nodeId])
> ON DELETE CASCADE
> GO
> 
> ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
> GO
> ```
> 
> And then reload the installation site again works.

I run this  command but the second part cause error because new table dese not have any key

**Comment by abaderkar** [comment] 2022-03-07 17:04
> > Looks like running this
> > ```sql
> > /****** Object:  Table [dbo].[umbracoContentVersionCleanupPolicy]    Script Date: 10-12-2021 11:00:04 ******/
> > SET ANSI_NULLS ON
> > GO
> > 
> > SET QUOTED_IDENTIFIER ON
> > GO
> > 
> > CREATE TABLE [dbo].[umbracoContentVersionCleanupPolicy](
> > 	[contentTypeId] [int] NOT NULL,
> > 	[preventCleanup] [bit] NOT NULL,
> > 	[keepAllVersionsNewerThanDays] [int] NULL,
> > 	[keepLatestVersionPerDayForDays] [int] NULL,
> > 	[updated] [datetime] NOT NULL
> > ) ON [PRIMARY]
> > GO
> > 
> > ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH CHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY([contentTypeId])
> > REFERENCES [dbo].[cmsContentType] ([nodeId])
> > ON DELETE CASCADE
> > GO
> > 
> > ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
> > GO
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then reload the installation site again works.
> 
> I run this command but the second part cause error because new table dese not have any key

Hi, 
I have the same issue. I want upgrade from 8.17.2 to 8.18.0

**Comment by p-m-j** [comment] 2022-03-07 19:27
@abaderkar just tried 8.12.2 -> 8.18, seemed to work fine, what edition of SQL Server are you using, potentially related to https://github.com/umbraco/Umbraco-CMS/issues/11964

**Comment by p-m-j** [comment] 2022-03-07 19:51
Can anyone impacted run the following query and post the result set?

```sql
select 
	T.name as table_name, 
	I.name as index_name, 
	AC.Name as column_name,
	I.is_unique,
	I.is_unique_constraint
from sys.tables as T inner join sys.indexes as I on T.[object_id] = I.[object_id]
   inner join sys.index_columns as IC on IC.[object_id] = I.[object_id] and IC.[index_id] = I.[index_id]
   inner join sys.all_columns as AC on IC.[object_id] = AC.[object_id] and IC.[column_id] = AC.[column_id]
   inner join sys.schemas as S on T.[schema_id] = S.[schema_id]
WHERE S.name = (SELECT SCHEMA_NAME()) 
and T.Name = 'cmsContentType'
```

**Comment by akiselenko** [comment] 2022-03-12 18:42
Migration 8.17.0 -> 9.3.1   The same error: 'There are no primary or candidate keys in the referenced table 'cmsContentType' that match the referencing column list in the foreign key 'FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId'. 

> Can anyone impacted run the following query and post the result set?
> 
> ```sql
> select 
> 	T.name as table_name, 
> 	I.name as index_name, 
> 	AC.Name as column_name,
> 	I.is_unique,
> 	I.is_unique_constraint
> from sys.tables as T inner join sys.indexes as I on T.[object_id] = I.[object_id]
>    inner join sys.index_columns as IC on IC.[object_id] = I.[object_id] and IC.[index_id] = I.[index_id]
>    inner join sys.all_columns as AC on IC.[object_id] = AC.[object_id] and IC.[column_id] = AC.[column_id]
>    inner join sys.schemas as S on T.[schema_id] = S.[schema_id]
> WHERE S.name = (SELECT SCHEMA_NAME()) 
> and T.Name = 'cmsContentType'
> ```

cmsContentType	IX_cmsContentType_icon	icon	0	0
cmsContentType	IX_cmsContentType	nodeId	1	0
cmsContentType	PK_cmsContentType	pk	1	0

![image](https://user-images.githubusercontent.com/261399/158030671-8d9da5ba-1762-4123-8b27-f2884e7a83b4.png)

**Comment by p-m-j** [comment] 2022-03-12 21:44
@akiselenko i'm pretty stumped, since SQL server 2005 a FK should be able to reference a column which has a unique index which cmsContentType.nodeId does in your database.

Obviously you're not alone in having this issue but I don't know how to explain it and I can't reproduce.

What do you get for the following queries

```sql
SELECT SERVERPROPERTY('ProductVersion');

SELECT name, compatibility_level 
FROM sys.databases
where name = '{{your database name}}'
```

Would you be able to script your database (schema only) and upload somewhere https://docs.microsoft.com/en-us/sql/ssms/tutorials/scripting-ssms?view=sql-server-ver15#script-a-database-by-using-the-generate-scripts-option

**Comment by brano** [comment] 2022-03-25 16:19
I have to same issue when upgrading Umbraco version 8.16 to latest version 8.18.1.

Error from App_Data/Logs:
Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table '**cmsContentType**' that match the referencing column list in the foreign key '**FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId**'.
Could not create constraint or index. See previous errors.

Initially it was v7 PROD database copy which will successfully migrated to v8.16 some time ago and all worked (after many upgrade steps and issues when going from v7 to v8).

**Comment by brano** [comment] 2022-03-25 16:30
Nothing special in our [dbo].[cmsContentType] table I guess...
![image](https://user-images.githubusercontent.com/848391/160161776-4951d8d2-9cc6-4e77-9b1e-30eef468d5b7.png)
![image](https://user-images.githubusercontent.com/848391/160161948-da888c25-c958-401d-9e5f-818158410509.png)

**Comment by brano** [comment] 2022-03-28 13:27
https://gist.github.com/brano/c9df1bea80bbe50ff61d3106e2686d0d

@p-m-j thanks for your help!

**Comment by p-m-j** [comment] 2022-03-29 10:19
On line 1133 you have
```sql
ALTER INDEX [IX_cmsContentType] ON [dbo].[cmsContentType] DISABLE
```
We need that index to create the new foreign key, if you run the following can you then migrate?

```sql
ALTER INDEX [IX_cmsContentType] ON [dbo].[cmsContentType] REBUILD
```

**Comment by brano** [comment] 2022-03-29 12:03
Great it helped! Thanks man!
Enabling index [IX_cmsContentType] ON [dbo].[cmsContentType] has fixed migration issue (from 8.16 to 8.18.1).

![image](https://user-images.githubusercontent.com/848391/160606962-34ce4b85-6ced-4df3-a5b1-e7d58886488e.png)

**Comment by chrden** [comment] 2023-04-11 01:36
For anyone who experiences this issue, this worked for me.

I tried the upgrade from Umbraco 9.0.0 > 9.0.1 and received the original error. After running this script, the installation succeeded, and further upgrades also worked 🎉 

> ```sql
> SET ANSI_NULLS ON
> GO
> 
> SET QUOTED_IDENTIFIER ON
> GO
> 
> CREATE TABLE [dbo].[umbracoContentVersionCleanupPolicy](
> 	[contentTypeId] [int] NOT NULL,
> 	[preventCleanup] [bit] NOT NULL,
> 	[keepAllVersionsNewerThanDays] [int] NULL,
> 	[keepLatestVersionPerDayForDays] [int] NULL,
> 	[updated] [datetime] NOT NULL
> ) ON [PRIMARY]
> GO
> 
> ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH CHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY([contentTypeId])
> REFERENCES [dbo].[cmsContentType] ([nodeId])
> ON DELETE CASCADE
> GO
> 
> ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
> GO
> ```

Thanks @thomashdk 👍

**Comment by mirkomaty** [comment] 2023-07-17 11:34
I had this error while updating from Umbraco 10.3.2 to 10.6.1. The problem occurs because the nodeId column of the cmsContentType table is not unique. Therefore the constraint couldn't be executed. You can come over it using these lines:
```
alter table cmsContentType add unique(nodeid)
GO
ALTER TABLE [umbracoContentVersionCleanupPolicy] ADD CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY ([contentTypeId]) REFERENCES [cmsContentType]([nodeId]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

```

**Comment by lordy1981** [comment] 2023-07-18 08:27
> I had this error while updating from Umbraco 10.3.2 to 10.6.1. The problem occurs because the nodeId column of the cmsContentType table is not unique. Therefore the constraint couldn't be executed. You can come over it using these lines:
> 
> ```
> alter table cmsContentType add unique(nodeid)
> GO
> ALTER TABLE [umbracoContentVersionCleanupPolicy] ADD CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY ([contentTypeId]) REFERENCES [cmsContentType]([nodeId]) ON DELETE NO ACTION ON UPDATE NO ACTION;
> GO
> ```

@nul800sebastiaan can you confirm this is the recommended fix, or whether you will be releasing another version to resolve this?

**Comment by ane-dwarf** [comment] 2023-12-19 12:56
I was facing this issue when upgrading from v10.0.0 to v11.3.1 (the migration from v8.18.7 => v9.3.1 => v10.0.0 ran perfectly fine) and what fixed it for me was to run the following scripts before starting migration from v8.18.7:

**Enable the disabled indexes**
```sql
DECLARE @AlterStatements TABLE (
    Statement NVARCHAR(MAX)
)

INSERT INTO @AlterStatements (Statement)
SELECT 'ALTER INDEX [' + I.name + '] ON [' + T.name + '] REBUILD'
FROM sys.indexes I
INNER JOIN sys.tables T ON I.object_id = T.object_id
WHERE I.type_desc = 'NONCLUSTERED'
AND I.name IS NOT NULL

DECLARE @Statement NVARCHAR(MAX)

DECLARE AlterCursor CURSOR FOR
SELECT Statement FROM @AlterStatements

OPEN AlterCursor
FETCH NEXT FROM AlterCursor INTO @Statement

WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC sp_executesql @Statement
    FETCH NEXT FROM AlterCursor INTO @Statement
END

CLOSE AlterCursor
DEALLOCATE AlterCursor
```

**Re-creating `umbracoContentVersionCleanupPolicy` table**
```sql
drop table [dbo].[umbracoContentVersionCleanupPolicy]

GO
--drop table umbracoContentVersionCleanupPolicy
CREATE TABLE [dbo].[umbracoContentVersionCleanupPolicy](
    [contentTypeId] [int] NOT NULL,
    [preventCleanup] [bit] NOT NULL,
    [keepAllVersionsNewerThanDays] [int] NULL,
    [keepLatestVersionPerDayForDays] [int] NULL,
    [updated] [datetime] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH NOCHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] CHECK  (([contentTypeId]<>''))
GO
ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
GO
```
