### ISSUE TITLE
SetRedirect in `RoutingRequestNotification` doesn't work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13542] opened 2022-12-08 08:45 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

I tried the example here from the docs, but it doesn't seem to redirect: 
https://docs.umbraco.com/umbraco-cms/implementation/custom-routing#routingrequestnotification
https://docs.umbraco.com/umbraco-cms/reference/routing/request-pipeline/published-content-request-preparation#redirects

The node hasn't any template and shows the default not found page, but including the code here doesn't make a difference even though it goes to `SetRedirect()` method when debugging.

```
public class PublishedRequestHandler : INotificationHandler<RoutingRequestNotification>
{
    public void Handle(RoutingRequestNotification notification)
    {
        var requestBuilder = notification.RequestBuilder;
        var content = requestBuilder.PublishedContent;

        if (content is CourseArchive)
        {
            requestBuilder.SetRedirect("/");
        }
    }
}
```

### Steps to reproduce

Implement the code above and noticed no redirect happens.

**Comment by nikolajlauridsen** [comment] 2022-12-08 10:36
Hey Bjarne, I'm unfortunately unable to reproduce, it seems to work fine for me, but I'm not 100% what you're trying to do. 

What I did was was: 

1. Create a root document type and template `Page`
2. Create a second document type and template `SubPage`
3. Create a root node with `Page`
4. Create a child node with `SubPage`
5. Added the redirect code (snippet below) 

This works just fine and redirects me to the root node, as expected.


Code snippet 

```c#
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace Umbraco.Cms.Web.UI;

public class ManualRedirectHandler : INotificationHandler<RoutingRequestNotification>
{
    public void Handle(RoutingRequestNotification notification)
    {
        var requestBuilder = notification.RequestBuilder;
        var content = requestBuilder.PublishedContent;

        if (content is SubPage)
        {
            requestBuilder.SetRedirect("/");
        }
    }
}

public class Comp : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<RoutingRequestNotification, ManualRedirectHandler>();
    }
}
```

**Comment by bjarnef** [comment] 2022-12-08 12:16
Hi @nikolajlauridsen 

Does it work when the `SubPage` hasn't a template?

In this case we have:

![image](https://user-images.githubusercontent.com/2919859/206443945-0e12cf88-4760-4151-8363-dbadc15a27cd.png)

![image](https://user-images.githubusercontent.com/2919859/206444004-8a8c3882-8efa-41db-901f-380dee29d5f3.png)

It hit the notification and goes all down to the `SetRedirect()` ... but afterwards I am still on the page `/kurser` seeing the default not found page.

**Comment by nikolajlauridsen** [comment] 2022-12-08 13:16
Ahh okay, I see.

I don't think is a bug to be honest, it's how it's intended to work, you can see that your request gets caught here: https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.Website/Routing/UmbracoRouteValuesFactory.cs#L125

Basically as long as templates are enabled, then content that does not have any template is by definition not routable, except by route hijacking, this is basically to allow the last chance content finders to handle custom 404 pages and so on. 


Now I don't know what the aim is here of course, but if you really want to go down this path, you can work around this limitation, but manually setting a dummy template when doing your redirect, the way the Umbraco routing is fooled and will happily redirect, depending on your needs, this also seems like a place where [route hijacking](https://docs.umbraco.com/umbraco-cms/reference/routing/custom-controllers) would make sense.


Regardless, here's an example of a working redirect of a content node with no template: 

```C#
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Core.Strings;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace Umbraco.Cms.Web.UI;

public class ManualRedirectHandler : INotificationHandler<RoutingRequestNotification>
{
    private readonly IShortStringHelper _shortStringHelper;

    public ManualRedirectHandler(IShortStringHelper shortStringHelper)
    {
        _shortStringHelper = shortStringHelper;
    }

    public void Handle(RoutingRequestNotification notification)
    {
        var requestBuilder = notification.RequestBuilder;

        var content = requestBuilder.PublishedContent;

        if (content is NoTemp)
        {
            // This template doesn't exist.
            requestBuilder.SetTemplate(new Template(_shortStringHelper, "dummyTemplate", "fake"));
            requestBuilder.SetRedirect("/");
        }
    }
}

public class Comp : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<RoutingRequestNotification, ManualRedirectHandler>();
    }
}

```

**Comment by bjarnef** [comment] 2022-12-08 13:42
@nikolajlauridsen okay I see.. the aim is just that the node is an archive node, so no real content on this, but I think it would be better to redirect to home page instead of seeing the not found page.

I think it makes sense to use route hijacking here (or set the `umbracoRedirect` property on the node), but great to have this example as well. Maybe it should be added to the documentation in case anyone is looking for this approach?

**Comment by nikolajlauridsen** [comment] 2022-12-08 13:56
Ahh okay I see, that makes a lot of sense, but yeah I think route hijacking could be your friend here, I haven't really tested it myself, but I think it could be a great way to do it :) 

I'm not sure we want the above example in the docs, it may be a bit too hacky for official documentation (no that there's anything really wrong with it), but I do think that the use case you're describing would be a great idea to document, both for archival nodes, settings nodes etc. 

Anyhow I'll go ahead and close this for now since it's more of a design thing :)

**Closed by nikolajlauridsen** 2022-12-08 13:56 UTC
Labels: state/needs-more-info, type/bug
