### ISSUE TITLE
Unpublished content appearing in macro results

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#6676] opened 2019-10-12 15:28 UTC
### Bug summary
This issue is about unpublished child nodes. Although **Model.Content** looks like **Umbraco.Content(Model.Content.Id)** it is not equal
At least when it comes to the Children property where unpublished children are listed in object flavor.
I came across this issue by using the code snippets.

Reproduction
------------
### Steps to reproduce
Use fresh default installation with StarterKit.
In the Settings section:

- create new partial view macro from snippet...
- List Child Pages From Current Page
- place the new macro in the people template
- unpublish one person

### Expected result

Only published persons should be listed.

### Actual result

All persons are listed

### Possible fix for the snippet
Within the line where the selection object is build, replace **Model.Content** by **Umbraco.Content(Model.Content.Id)**

### Remarks

I do not think there is a good reason why **Model.Content** and **Umbraco.Content(Model.Content.Id)** should create such subtly different results ;-)
Maybe I have overlooked something?

**Comment by idseefeld** [comment] 2019-10-12 15:56
This is true from 8.1.1 to the latest dev branch 8.3.0

**Comment by stevemegson** [comment] 2019-10-13 07:11
This is fixed in PR #6627. `Model.Content` is being set to the unpublished version of the content, as you'd see in preview. This was intended to allow macros to render inside editors when you're editing an unpublished page, but it's also affecting `Umbraco.RenderMacro` in templates.

As you've found, as a workaround you can use `Umbraco.Content(Model.Content.Id)` to get the published version that should have been assigned to `Model.Content`.

**Closed** 2019-11-26 23:47 UTC
Labels: community/pr, release/8.6.0, type/bug
