### ISSUE TITLE
Backoffice: umbraco.service iconApi uppercase bug

### ISSUE THREAD

**Issue by robgha01** [umbraco/Umbraco-CMS#12152] opened 2022-03-18 10:38 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18

### Bug summary

We upgraded umbraco from 8.1 to 8.14 and noticed a problem the icon api expects a lowercase object of "data" but the server returns it as "Data" see image this also happens in 8.14

i fixed it for now by just doing "Object.entries(response.data.Data ?? response.data.data)" until this is found and fixed.

### Specifics

![image](https://user-images.githubusercontent.com/362726/158987696-495736bb-3a6d-443e-a8a1-51dcc501cb77.png)

### Steps to reproduce

Im not sure how to reproduce this but we have a umbraco 8.1 site that we upgraded in 8.1 this worked so something changed maybe the code needs a "rewrite" for the data property so it is server as uppercase.

see line 5990 in umbraco.services.js

### Expected result / actual result

it should work :)

**Comment by nul800sebastiaan** [comment] 2022-03-18 11:44
Hi @robgha01 I don't understand what the problem is please? What is broken for you?

**Comment by immeo-rru** [comment] 2022-03-26 23:52
> Hi @robgha01 I don't understand what the problem is please? What is broken for you?

Umbraco backoffice js calls this URL:
     Umbraco.Sys.ServerVariables.umbracoUrls.iconApiBaseUrl + 'GetIcons'
-> /umbraco/backoffice/UmbracoApi/Icon/GetIcons

The result is:
   `{"contentEncoding":null,"contentType":null,"**data**":{"icon-activity`

Note that the data is lowercase, but the backoffice js that consumes the json expect "Data" - where D is a capital letter.

I am running version 8.17.2 and I am having the same error- And it is shown in the developer console.

**Comment by nul800sebastiaan** [comment] 2022-03-27 08:36
Ah I see. This is not a problem in a default install of Umbraco, but indeed as @rbottema suggests, I assume you have a global overwrite for the JSON serialization settings somewhere. The recommendation is to only use specific formatters when you do your own serialization/deserialization.

I'll close this issue as Umbraco 8 is in the support phase at the moment, meaning we will only fix regression issues from now on (we broke something in a recent version). Therefore, we recommend working around the problem as noted above. 
It doesn't look like v9 has the same problem, but if we can cause something similar there we can have a look at that specific case.

**Closed by nul800sebastiaan** 2022-03-27 08:36 UTC
Labels: type/bug

**Comment by rbottema** [comment] 2022-03-28 07:11
@nul800sebastiaan I must say I would turn the recommendation around: Umbraco should use specific formatters so developers have more freedom in setting up the rest of their code without having to worry about Umbraco breaking.

**Comment by nul800sebastiaan** [comment] 2022-03-28 08:27
I agree and that's what we should do going forward, I believe it is taken care of in v9, but maybe there's some things that have been overlooked, we can look at those if and when they come up.
