### ISSUE TITLE
Error when deleting language

### ISSUE THREAD

**Issue by etharion** [umbraco/Umbraco-CMS#6581] opened 2019-10-04 10:51 UTC
I have found a bug when deleting a language. If you have any tags created for the desired language, it throws an error about foreign keys in the database.

Reproduction
------------
Make a clean Umbraco website with MS SQL database.
Add two language (eg: da-dk and en-gb)
Create a doc type with at least one property of Umbraco.Tags
![image](https://user-images.githubusercontent.com/15627835/66201902-bd82c600-e6a4-11e9-9126-36a04dedb9b1.png)

Create a node in content and add tags to the selected language. Save and Publish.

Now try delete the language with tags. Result will be this:
![image](https://user-images.githubusercontent.com/15627835/66201912-c4a9d400-e6a4-11e9-90f9-26b00bb46948.png)

I manually tried to add Delete on cascade on the two relationships in table ‘dbo.cmsTags’ with the result of fixing the above error.

**Comment by AndyButland** [comment] 2019-10-05 17:15
Think this is a duplicate of #6269, which has now been fixed via  PR (so should be in the next release).

**Comment by nul800sebastiaan** [comment] 2019-10-06 10:26
Yep, closing as a duplicate of #6269

**Closed by nul800sebastiaan** 2019-10-06 10:26 UTC
