### ISSUE TITLE
Content 'Send to publish' notifications doesn't work for more root nodes

### ISSUE THREAD

**Issue by ricbrady** [umbraco/Umbraco-CMS#12194] opened 2022-03-29 15:05 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

I would like to set the notification for the 'send to publish' action.

In my Umbraco I have 2 Root nodes and I've configured the notifications for both.

The problem is that I receive the notifications only for the nodes that are under the first root node where I've configured the subscription. No way to receive something for the second.

### Steps to reproduce

Subscrive to receive notifications for 'SendToPublish' action for 2 root nodes contents and try to send some content to be published.
You will receive the notification only for the nodes where you subribe first

### Expected result / actual result

Receive notification for all configured nodes

---
_This item has been added to our backlog [AB#26479](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/26479)_

**Comment by nathanwoulfe** [comment] 2022-04-06 22:36
Hey @ricbrady, I've had a quick look, this issue applies to all notifications - I've subscribed to publish notifications and confirm that they only send for the first root node. Will see if I can find why, but this certainly looks like something needing attention.

**Comment by nathanwoulfe** [comment] 2022-04-06 23:05
Looks like the problem is in this block, particularly the check at L113:

https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Infrastructure/Services/Implement/NotificationService.cs#L97-L130

Because notifications are inherited, it's assumed the first notification in the set can be used to determine if the notifications apply to the current node (by checking the notification id against the current entity's path). If the notification id is in the entity path, send the email. 

The issue with sibling root nodes is because the first notification id will be the first root node id, so will never match on the sibling nodes. This also means notifications will only work for the first root node with notifications enabled (that might be the second, third node), since the notifications are treated as representing a path to a node, not siblings.

Passing the entity ids to `GetUsersNotifications` (L98) fixes the problem for the root nodes, but breaks notifications for nested nodes... Maybe needs some additional logic to check the node is at the root, if so send the ids, otherwise send the empty int enumerable. Definitely needs proper investigation, but I think this is where the problem originates.

**Comment by kjac** [comment] 2023-02-08 09:58
Hi @ricbrady,

Sorry for the belated response here.

I can reproduce this in V10+, so this definitively is an ongoing issue. 

I have created a PR that fixes it for V10+ in #13805

**Comment by nikolajlauridsen** [comment] 2023-02-10 09:49
Fixed in #13805, thanks for reporting 😄

**Closed by nikolajlauridsen** 2023-02-10 09:49 UTC
Labels: type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12, release/10.4.1, release/11.3.0
