### ISSUE TITLE
BlockList Editor loses Blocks with skin/theme package

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#9148] opened 2020-10-13 05:56 UTC
- Create a Skin/Theme as a package that includes Blocklist editors
- Import it into a new Umbraco install
- The Block Editor DataType does not contain the blocks
- You get the usual 404 error "Failed to retrieve data for empty content item id ..."

**Comment by nul800sebastiaan** [comment] 2020-10-14 13:31
Thanks! This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8918 - make sure to follow progress there! 👍

**Closed by nul800sebastiaan** 2020-10-14 13:31 UTC
