### ISSUE TITLE
Lucene Error when publishing a node: Lucene.Net.QueryParsers.Classic.ParseException: Encountered " <OR> "OR "" at line 1, column 5.

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco-CMS#16223] opened 2024-05-06 17:12 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 13.1.1

### Bug summary

When I publish a node, I've this Lucene error:

Lucene.Net.QueryParsers.Classic.ParseException: Encountered " <OR> "OR "" at line 1, column 5.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    
   at Lucene.Net.QueryParsers.Classic.QueryParser.Jj_consume_token(Int32 kind)
   at Lucene.Net.QueryParsers.Classic.QueryParser.Clause(String field)
   at Lucene.Net.QueryParsers.Classic.QueryParser.Query(String field)
   at Lucene.Net.QueryParsers.Classic.QueryParser.Clause(String field)
   at Lucene.Net.QueryParsers.Classic.QueryParser.Query(String field)
   at Lucene.Net.QueryParsers.Classic.QueryParser.TopLevelQuery(String field)
   at Lucene.Net.QueryParsers.Classic.QueryParserBase.Parse(String query)
   --- End of inner exception stack trace ---
   at Lucene.Net.QueryParsers.Classic.QueryParserBase.Parse(String query)
   at Examine.Lucene.Search.LuceneSearchQueryBase.NativeQuery(String query)
   at Umbraco.Cms.Infrastructure.Examine.DeliveryApiContentIndex.PerformDeleteFromIndex(IEnumerable`1 itemIds, Action`1 onComplete)
   at Examine.BaseIndexProvider.DeleteFromIndex(IEnumerable`1 itemIds)
   at Umbraco.Cms.Infrastructure.Examine.Deferred.DeliveryApiContentIndexDeferredBase.RemoveFromIndex(IReadOnlyCollection`1 ids, IIndex index)
   at Umbraco.Cms.Infrastructure.Examine.Deferred.DeliveryApiContentIndexDeferredBase.RemoveFromIndex(IReadOnlyCollection`1 ids, IIndex index)
   at Umbraco.Cms.Infrastructure.Examine.Deferred.DeliveryApiContentIndexDeferredBase.RemoveFromIndex(Int32 id, IIndex index)
   at Umbraco.Cms.Infrastructure.Examine.Deferred.DeliveryApiContentIndexHandleContentChanges.Reindex(IContent content, IIndex index)
   at Umbraco.Cms.Infrastructure.Examine.Deferred.DeliveryApiContentIndexHandleContentChanges.<Execute>b__7_0(CancellationToken _)
   at Umbraco.Cms.Infrastructure.HostedServices.QueuedHostedService.BackgroundProcessing(CancellationToken stoppingToken)

This error slow the publishing action, too.

### Steps to reproduce

When Save or Publish a node. I've a lots members and nodes.

**Comment by Shazwazza** [comment] 2024-08-16 15:24
This will be caused by passing in empty fields/strings or something similar to that with however Umbraco is creating its manual Lucene query with the call to "Examine.Lucene.Search.LuceneSearchQueryBase.NativeQuery". Perhaps this is already fixed in later Umbraco versions?

**Comment by Shazwazza** [comment] 2024-08-16 17:45
I believe this is fixed here https://github.com/umbraco/Umbraco-CMS/pull/15848

**Comment by biapar** [comment] 2024-08-16 19:02
I’ll check. 
I don’t understand which query cause the problem. I cannot use a query direct on the index.

**Comment by Shazwazza** [comment] 2024-08-16 19:12
Its part of Umbraco's logic that creates the native query to pass to examine. Please try the latest Umbraco 13 version, it should be resolved.

**Comment by kjac** [comment] 2024-08-19 04:36
This does indeed look like the issue fixed in #15848 

![image](https://github.com/user-attachments/assets/98023c96-e808-482c-a0ed-1d9c046e4aa6)

I'll close this as a duplicate.

@biapar please try upgrading to 13.3. If that does not resolve your problem, feel free to reopen this issue with steps to reproduce 👍

**Closed by kjac** 2024-08-19 04:36 UTC
Labels: type/bug

**Comment by biapar** [comment] 2024-08-23 17:50
Solved with the fix into latest version Umbraco 13
