### ISSUE TITLE
NestedContent: Publish blocked due to "invalid" Content Picker

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#9363] opened 2020-11-09 09:34 UTC
## Umbraco version

I am seeing this issue on Umbraco version: 8.9.0

### Bug summary

When Nested Content contains a mandatory Content Picker and you publish it will be marked as invalid, that's good.
However, when you then pick a node it remains invalid and you cannot ever publish the page. 
The error should be cleared when the property is touched but this does not seem to happen. 

See below:
![cannot-publish](https://user-images.githubusercontent.com/24297947/98523942-d29e3100-2276-11eb-9413-3bea8b856ba9.gif)

### Steps to reproduce

1. Create a NestedContent with a "Content Picker" property (`Umbraco.ContentPicker`)
2. Make this property mandatory
3. Publish your content without picking any content
4. Observe validation message (correctly).
5. Pick content
6. Try to publish again
7. Observe you cannot

### Expected result

I can publish the page again when filling the mandatory property.

### Actual result

I cannot publish the page, it is blocked due to an invalid property which is in fact not invalid.

**Comment by AndersBrohus** [comment] 2020-11-09 11:38
Thanks alot for report Daniel :)

This is a big issue for some of our clients :)

**Comment by nul800sebastiaan** [comment] 2020-11-09 15:21
Thank @PerplexDaniel - turns out this is indeed an issue still present in the upcoming releases. :-(

It's a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8954, so I'll close this one. Make sure to keep following progress on #8954 instead 👍

**Closed by nul800sebastiaan** 2020-11-09 15:21 UTC
