### ISSUE TITLE
Date Picker not saving data

### ISSUE THREAD

**Issue by lars-lindstrom** [umbraco/Umbraco-CMS#16779] opened 2024-07-14 09:13 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0

### Bug summary

I have created a document type to represent a person. The document type inherits a composition "Person composition" which includes an invariant "birthdate" property of type "Date Picker".

The document type and composition was created using version 14.0.0, but since upgrading to version 14.1.0 both new and updated values are no longer saved. Infact any value is deleted when updating any value of other properties of the document type.

### Specifics

https://nxtlevelsport.dk/athletes/andreas-bock/

Birthdate "Født" shows 01 jan. 0001 and in the backoffice "dd-mm-yyyy" is shown when refreshing data.

### Steps to reproduce

https://github.com/user-attachments/assets/356a2618-5d39-4b62-9060-1334058d7126

### Expected result / actual result

I expected the updated date to be saved.

---
_This item has been added to our backlog AB#42326_

**Comment by lars-lindstrom** [comment] 2024-07-14 09:41
After investigating the issue further, it seems the property value is not saved in the DB table "umbracoPropertyData". All other properties are updated and stored

**Comment by iOvergaard** [comment] 2024-07-15 12:17
Looking into this, I can reproduce the behavior if the format of the Date Picker does not match that which the server expects. For example, if configured as a date-only picker with `YYYY-mm-dd`, then the server cannot convert the value because the time string is missing. Conversely, if configured as a time-only picker with `HH:mm:ss`, then the server lacks the date part.

The only thing that works right now is the full string `YYYY-mm-dd HH:mm:ss`.

A fix has been started and we'll see how soon we can get it out.

**Comment by lars-lindstrom** [comment] 2024-07-15 15:24
Great work @iOvergaard !!

I have temporarily changed my site to use the Date with Time picker and it works as expected. 
A thought, I recall a similar issue occured in v13.x (I cannot recall the actual version). Maybe some legacy code was not applied to v14.

**Closed** 2024-07-15 18:32 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v14, release/14.1.1

**Comment by iOvergaard** [comment] 2024-07-16 06:53
Thanks, @lars-lindstrom!

Here is the plan: We are going to release a patch as soon as possible: **14.1.1**. It will contain this fix as well as a few others we are looking into. I suspect we can get it out this week.
