### ISSUE TITLE
Lucene ExternalIndex error , multiple domains

### ISSUE THREAD

**Issue by hsh79** [umbraco/Umbraco-CMS#8133] opened 2020-05-19 07:48 UTC
A brief description of the issue goes here.

After publishing numerous times, publising fails, and the index search engine fails. It is not possbile to navigate to search-configuration page in /umbraco.

It gives the following Exception.
System.ApplicationException: Could not create an index searcher with the supplied lucene directory ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _8: fieldsReader shows 1 but segmentInfo shows 4 at Lucene.Net.Index.SegmentReader.CoreReaders.OpenDocStores(SegmentInfo si) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\SegmentReader.cs:line 361 at Lucene.Net.Index.SegmentReader.Get(Boolean readOnly, Directory dir, SegmentInfo si, Int32 readBufferSize, Boolean doOpenStores, Int32 termInfosIndexDivisor) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\SegmentReader.cs:line 782 at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 689 at Lucene.Net.Index.IndexWriter.ReaderPool.GetReadOnlyClone(SegmentInfo info, Boolean doOpenStores, Int32 termInfosIndexDivisor) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 630 at Lucene.Net.Index.DirectoryReader..ctor(IndexWriter writer, SegmentInfos infos, Int32 termInfosIndexDivisor) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\DirectoryReader.cs:line 204 at Lucene.Net.Index.IndexWriter.GetReader(Int32 termInfosIndexDivisor) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 392 at Lucene.Net.Index.IndexWriter.GetReader() in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 353 at Examine.LuceneEngine.Providers.LuceneSearcher.ValidateSearcher() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneSearcher.cs:line 198 --- End of inner exception stack trace --- at Examine.LuceneEngine.Providers.LuceneSearcher.ValidateSearcher() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneSearcher.cs:line 209 at Examine.LuceneEngine.Providers.LuceneSearcher.GetLuceneSearcher() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneSearcher.cs:line 83 at Examine.LuceneEngine.Providers.LuceneSearcher.GetSearchContext() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneSearcher.cs:line 92 at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation, Analyzer luceneAnalyzer, LuceneSearchOptions searchOptions) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\BaseLuceneSearcher.cs:line 64 at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\BaseLuceneSearcher.cs:line 49 at ASP._Page_Views_FAQArea_cshtml.Execute() in c:\Src\CSCPublic\yyy\System\4-Implementation\yyyNet-Umb8\WebProjects\yyy.umbraco\Views\FAQArea.cshtml:line 31 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.Mvc.WebViewPage.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) at Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in D:\a\1\s\src\Umbraco.Web\Mvc\ProfilingView.cs:line 25 at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) at System.Web.Mvc.Controller.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

## Umbraco version

I am seeing this issue on Umbraco version: 
8.6.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

It is reproducable in Umbraco 8.6.1.
1. Install a base Umbraco
2. Have multiple nodes, and multiple associed dns-names configuret to point to same IIS/Umbraco
3. publish content on .dk site, and later on .se site, then Search Engine is corrupted.

Maybe related to this (although problems with version 7)
https://our.umbraco.com/forum/using-umbraco-and-getting-started/102097-whats-the-best-umbraco-websites-subdomains-and-indexes-configuration-to-avoid-lucene-errors

**Comment by nul800sebastiaan** [comment] 2020-05-19 10:48
Hi there @hsh79, thanks for reporting but we unfortunately need more information than this:

- Have you been able to reproduce this on a clean install of Umbraco 8.6.1
- What are the exact steps to reproduce? - how many times is "publishing numerous times" for example?
- What have you tried?
- When did this start happening?
- Did you change any configurations - Examine configs for example
- Is your environment load balanced or are multiple sites trying to connect to the same database

Things like that are important to know before we can say something about this issue you're experiencing. 

I just noticed you mentioned "multiple domains" so I am assuming you're on a load balanced environment. Usually errors with Examine/Lucene come from a configuration problem, make sure to read the docs about this carefully and apply to your situation, make sure to review:

- https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/
- and specifically: https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/file-system-replication#examine-directory-factory-options

I'm going to close this for now and advise you to get some feedback on your setup (after you've reviewed the above) on the forum at https://our,umbraco.com.

**Closed by nul800sebastiaan** 2020-05-19 10:48 UTC

**Comment by hsh79** [comment] 2020-05-20 08:43
Hi @nul800sebastiaan 
Thanks for the answer. 
During many years accessing the admin pages on different country sites, where possible, at least we did not get any hard errors (version 7 of Ubmraco ) accessing test.dk/admin, test.se/admin and test.no/admin. But in version 8 we experieced weird errors. 

So what we have done know, since we understand only admin pages must be visited from one url, we have added som url-blocking rules, to only access administration from on url. 

It seems to work, but if you have any other ideas what we can do, please let us know.

BR
Henrik

**Comment by Shazwazza** [comment] 2020-05-26 04:51
This sounds like the same issue listed here https://our.umbraco.com/forum/using-umbraco-and-getting-started/102097-whats-the-best-umbraco-websites-subdomains-and-indexes-configuration-to-avoid-lucene-errors where there are multiple IIS websites pointing to the same physical file system. If that is the case, please read that thread since that is not a supported hosting configuration.

**Comment by hsh79** [comment] 2020-05-27 08:07
Hi Again,

Thanks for the answer it helps us a lot.

It seems we have had this problem many years in production in version 7, where we have multiple IIS sites pointing to the same physical file system.

Now in version 8, it seems that it will give huger problems, since now it gives hard error, "file is locked" etc.

Since we cannot change this very easily, we try to do some workarounds.
1) Assume all content is added to the website, thereafter the indexfile is regenerated from scratch.
2) Now if end-user access UMBRACO and perform searches, the search indexer will only be accessed in READ operations, and therefore will not lock the file.

Do you think it will work out, or is there another work-around?

BR
Henrik

**Comment by Shazwazza** [comment] 2020-05-28 06:56
I'm unsure how this has ever worked:

> It seems we have had this problem many years in production in version 7, where we have multiple IIS sites pointing to the same physical file system.

Even in v7 this would not (should not) work. The umbraco cache file would have worked by fluke because it was not explicitly locked, but this means you would have definitely ran into consistency problems, though this might have happened silently or been raised as some other odd errors or exceptions. Lucene however has always worked this way so it seems very strange how this could have worked previously. Perhaps lucene 3.x which v8 uses auto-optimizes properly and in v2.x it didn't. I'm unsure. 

In any case, this setup has never been supported for Umbraco. Multiple IIS sites pointing to the same file location IS load balancing and this is normally done in load balanced scenarios using a SAN/NAS shared file system. You can make it work but you have to follow the load balancing docs/guidelines. Only a single process can ever write to the umbraco cache and lucene files at once. 

Also we've never supported multiple 'master' servers which this also is. It can work but again you can run into consistency issues if there's high admin traffic on all IIS instances writing to the same database.

Please see the load balancing docs to understand how to make this all work. https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/

**Comment by hsh79** [comment] 2020-05-28 08:03
Hi @Shazwazza 

I really appreciate you feedback. I will return if needed also if we find a solution, that will benefit other users/customers.

BR
Henrik

**Comment by Shazwazza** [comment] 2020-05-28 08:14
@hsh79 I would recommend not inventing new work arounds as this will most likely lead to problems. If you follow the load balancing information to understand how this can all work you can get it going. This is for v7 but this is essentially what you are doing: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/files-shared-v7

The same principles apply to v8 which the docs are here https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/, https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/file-system-replication#standalone-file-system. You just need to understand the settings for where to store things that cannot be written to by multiple processes: umbraco cache files & examine files. There's a bunch of different settings you can apply to make it work... but you should still only have a single master admin server.

**Comment by hsh79** [comment] 2020-05-28 09:16
Dear Shannon,

Thanks again.

OK, we will take it into account regarding load-balancing. The workaround could consider making Umbraco/Lucene thread-safe either inspirated from stackoverflow, or adding a queue updating the index at a certain time, when index file /Umbraco cache not locked.
https://stackoverflow.com/questions/193624/does-lucene-net-manage-multiple-threads-accessing-the-same-index-one-indexing-w

MVH
Henrik

**Comment by Shazwazza** [comment] 2020-05-28 09:40
> The workaround could consider making Umbraco/Lucene thread-safe either inspirated from stackoverflow, or adding a queue updating the index at a certain time, when index file /Umbraco cache not locked.

That is what Examine does. The problem is that you are trying to read/write from multiple processes. It is thread safe, multiple processes are different from threads.

**Comment by hsh79** [comment] 2020-05-28 10:33
Do you think it will work out, if the different IIS websites use the same app-pool ?

**Comment by Shazwazza** [comment] 2020-05-28 11:51
@hsh79 no, an application still has multiple appdomains, its basically the same as multiple processes.

**Comment by Shazwazza** [comment] 2020-05-28 11:54
There's already ways to make this work, please see the docs, there's a few different config settings to use to ensure that each instance stores its cache/lucene files in a temporary/local folder that exists outside of the main shared file system. That is how LB works in Umbraco, each instance maintains it's own caches. It's all in the docs.

**Comment by hsh79** [comment] 2020-05-28 13:38
Will it be possible to disable the indexing? (temporarly)
