### ISSUE TITLE
Rolling back multilingual content does not work on non varied fields.

### ISSUE THREAD

**Issue by crjc** [umbraco/Umbraco-CMS#14687] opened 2023-08-16 15:22 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2 (also confirmed on latest 12)

### Bug summary

Rollbacks on multilingual content do not revert fields which are configured to NOT vary by culture.

### Specifics

It looks like its these conditionals preventing the field from copied:
https://github.com/umbraco/Umbraco-CMS/blob/3a7e388547e3df29bee9bb2649c543c19a1e775a/src/Umbraco.Core/Models/ContentRepositoryExtensions.cs#L195

https://github.com/umbraco/Umbraco-CMS/blob/3a7e388547e3df29bee9bb2649c543c19a1e775a/src/Umbraco.Core/Models/ContentRepositoryExtensions.cs#L176C29-L176C29

SupportsVariation returns false from here:
https://github.com/umbraco/Umbraco-CMS/blob/3a7e388547e3df29bee9bb2649c543c19a1e775a/src/Umbraco.Core/Extensions/ContentVariationExtensions.cs#L360C23-L360C23

In my case, culture at this point was "en-us".

### Steps to reproduce

New Umbraco Installation
SQL Server or Sqlite

1. Create document type "Home"
2. Add a text field "Title".
3. Enable "Allow as root"
4. Enable "Allow vary by culture". Ensure Title is still not varied by culture.
5. Save and close
6. In settings, configure a second language. Keep the default (en-us). This step is important. If I later delete the second language, rollbacks work as expected. 
7. Create a page using the Home document type.
8. Save and publish once with the Title as "test1"
9. Save and publish again with the Title as "test2"
10. Rollback to the test1 version
--- the field will still show test2 ---

### Expected result / actual result

After the above steps, the field should be 'test1'. But the field does not roll back and stays as test2.

**Comment by elit0451** [comment] 2023-08-17 06:26
Hi @crjc 👋 

Thanks for the detailed reproduction steps and the initial investigation 💪 
I can confirm that when we have a second language, the rollback functionality is not working on invariant fields. We would like some help fixing this, so I will mark it as up for grabs.

**Comment by nagolucky18** [comment] 2023-11-04 04:35
I will look at this one.

**Comment by pmann1991** [comment] 2024-03-25 11:22
This still seems to be an issue in v13. Is there an update on this? Looks like the PR was never merged? This is a pretty major flaw IMO and you'd expect it to be fixed way before a whole new major release.

**Comment by keithlfs** [comment] 2024-03-25 12:46
Hi @elit0451 - please review the PR that was added a while back. This is a serious issue that looks to have already been fixed, barring review.

**Closed** 2024-03-25 13:27 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12
