### ISSUE TITLE
No option to Move a folder in DataTypes area

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#10545] opened 2021-06-28 14:44 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.0

### Bug summary

It is possible to right-click on a DataType in the tree and choose "Delete..." or "Move...":

![image](https://user-images.githubusercontent.com/1252593/123656106-9f0c1900-d7fd-11eb-8b30-24dfe3f630b8.png)

but there is no  "Move..." option on folders:

![image](https://user-images.githubusercontent.com/1252593/123656013-86036800-d7fd-11eb-89df-b42c9fc870e6.png)

### Steps to reproduce

Create a folder under "DataTypes" and then try to move it.

**Comment by bjarnef** [comment] 2021-06-29 09:28
It seems this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9754
I think it would be a general feature to move folders in document types, datatypes, etc.

Furthermore it probably also need to trigger an event, so packages like Umbraco Deploy and uSync can re-generate meta data as mentioned in https://github.com/umbraco/Umbraco-CMS/issues/9754

**Comment by hfloyd** [comment] 2021-06-29 13:34
Yes, I think any schema items that can be in folders should allow folders to move

**Comment by nul800sebastiaan** [comment] 2021-06-30 07:47
I'll close as a duplicate of  https://github.com/umbraco/Umbraco-CMS/issues/9754 👍

**Closed by nul800sebastiaan** 2021-06-30 07:47 UTC
Labels: type/bug
