### ISSUE TITLE
V8.1.0 database update Error from 8.0.2

### ISSUE THREAD

**Issue by filefontaine** [umbraco/Umbraco-CMS#5811] opened 2019-07-09 09:55 UTC
Problem when updating the datebase with the installer

![image](https://user-images.githubusercontent.com/22192319/60878487-1971b600-a240-11e9-8df6-121bf26a0df3.png)

Reproduction
------------

* i try to update my site in 8.0.2 to 8.1.0. 
* I have make all change needed for the project build (obviously ^^)
* click on update database

### Bug summary

full log info error :
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoContent' that match the referencing column list in the foreign key 'FK_cmsContentNu_umbracoContent_nodeId'.
Could not create constraint or index. See previous errors.
 Please check log file for additional information (can be found in '/App_Data/Logs/')
   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model) in d:\a\1\s\src\Umbraco.Web\Install\InstallSteps\DatabaseUpgradeStep.cs:line 47
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__14.MoveNext() in d:\a\1\s\src\Umbraco.Web\Install\Controllers\InstallApiController.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Umbraco.Web.Install.Controllers.InstallApiController.<PostPerformInstall>d__11.MoveNext() in d:\a\1\s\src\Umbraco.Web\Install\Controllers\InstallApiController.cs:line 104
```

**Comment by clausjensen** [comment] 2019-07-18 13:05
@filefontaine You seem to be having some issues with your database being in an incorrect state.

Since we can't really debug this and we haven't seen it happen in any of our tests doing the upgrade from 8.0.x to 8.1.0 - could you provide instructions on how to replicate this scenario from scratch?

What version(s) would we need to install and upgrade from/to in order to get the error?

**Comment by filefontaine** [comment] 2019-07-18 13:10
my colleague tried on his side and has a better expertise to side with, he posted more information on this issue here : #5811

**Comment by pralthom** [comment] 2019-07-18 14:40
Hi @clausjensen , thank you for your answer.

I think I found the solution, it's caused by some inconsistency between our dev environment and integration / production environments.

I think you can close this issue and also the #5896 

Thank you for your support,

Thomas

**Comment by clausjensen** [comment] 2019-07-18 21:12
@pralthom Great that it sounds like you found a solution 😃 
If the problem however persists, please do let us know how to replicate so we can assist with fixing it.
I'll close the issue you referenced as well as this one for now.

**Closed by clausjensen** 2019-07-18 21:12 UTC
Labels: type/bug
