### ISSUE TITLE
WebApi MapHttpAttributeRoutes causes error in IComponent

### ISSUE THREAD

**Issue by Padbury** [umbraco/Umbraco-CMS#4775] opened 2019-02-27 11:15 UTC
This is similar to issue #4464 but slightly different hence the new issue.

So, in v7 to register my own WebApi routes I'd create a class that implements IApplicationEventHandler and register my routes via the OnApplicationStarted method like this:

`GlobalConfiguration.Configuration.MapHttpAttributeRoutes();`

In v8, it's suggested to use a class that implements IUserComposer then append a component. Then it's suggested to use the Initialize() method to execute startup functions. 

However, if I put GlobalConfiguration.Configuration.MapHttpAttributeRoutes(); inside Initialize() I get the following error:

The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.

If I move the call into the constructor for the class

`  public RouteConfigComponent()
        {
            GlobalConfiguration.Configuration.MapHttpAttributeRoutes(); 
        }`

Then the error goes away and routes are registered correctly using attributes e.g.

` [Route("api/question/{id}")]
public HttpResponseMessage Get(int id)
        {
            return Request.CreateResponse(HttpStatusCode.OK);
        }`

The workaround is to have this in the constructor but I'm told this is probably not the desired behaviour and to register it here for review.

**Comment by zpqrtbnk** [comment] 2019-03-04 09:00
Notes for self: odd that it works in the constructor and not in `Initialize` as `Initialize` runs *after* the constructor. Going to look into it.

**Comment by zpqrtbnk** [comment] 2019-03-04 16:05
Reproduced. Putting `MapHttpAttributeRoutes` in the `Initialize` method does trigger the exception.

**Comment by zpqrtbnk** [comment] 2019-03-04 16:13
The problem is caused by `WebRuntimeComponent` doing:
```
// ensure WebAPI is initialized, after everything
GlobalConfiguration.Configuration.EnsureInitialized();
```

in its own `Initialize` method - and we do need to do this for everything to run.

But because your component runs after the `WebRuntimeComponent`, it invokes `MapHttpAttributeRoutes` after `EnsureInitialized` has been invoked, hence the exception.

Short term, registering your component as follows would work:
```
public class MyComposer : IComposer
{
  public void Compose(Composition composition)
  {
    composition.Components().Insert<TempComponent>();
  }
}
```

because it would insert your component in the first position, ie even before `WebRuntimeComponent` - but then, you have to be careful with what you do in the component, as strictly nothing will be initialized (no content cache, no nothing).

Longer term, it feels that `EnsureInitialized` should run after every other component has had a chance to do things - not before. Looking into it.

**Comment by zpqrtbnk** [comment] 2019-03-04 18:03
Going to fix it properly - in progress.

**Comment by zpqrtbnk** [comment] 2019-03-05 07:56
PR: https://github.com/umbraco/Umbraco-CMS/pull/4856

Test: with this in place, a user component should be able to `MapHttpAttributeRoutes` because `EnsureInitialized` will run last (after every other components).

Note: renaming some composers etc = breaking.

**Comment by Shazwazza** [comment] 2019-03-07 07:04
I can confirm this works. The breaking names are not going to affect anyone ... well except for @aaronpowell ;)

**Closed by Shazwazza** 2019-03-07 07:04 UTC
Labels: category/breaking, release/8.1.0, state/review, type/feature

**Comment by aaronpowell** [comment] 2019-03-08 00:44
Haha I think I'm good for this one 😛
