### ISSUE TITLE
Files can't be selected by clicking filename

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco-CMS#17469] opened 2024-11-08 10:12 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

When using MediaPicker, clicking on the filename part of a file shows the message 
"There are no items to show in the list."

### Steps to reproduce

In a MediaPicker when choosing an image, and clicking on the filename part of an image
![Screenshot_2](https://github.com/user-attachments/assets/3f6d34f6-a4db-4672-925c-3cfb0d00446f)

it switches to this view
![Screenshot_3](https://github.com/user-attachments/assets/ade2be4d-c32f-46fb-84eb-18e21fabd815)

Which is just empty and not helpful for the user. 

### Expected result / actual result

Files technically being able to have other files as children, does not make any sense, but I guess that's a whole other discussion. 

But I would expect that if I click anywhere on the image, thumbnail or filename, that selects it. It's confusing for the user, as they have to take care on which part they click on,. There is no indication that there is a difference in behaviour, depending on where you click.

**Comment by tbolon** [comment] 2024-11-08 10:46
Dupe of #16398 ?

**Closed as completed** 2024-11-08 11:00 UTC
Labels: type/bug
