### ISSUE TITLE
V8: syncTree causing trees to flicker

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5403] opened 2019-05-04 17:28 UTC
If you have a tree with more than 1 level in the nodes path and those nodes edit screens call `navigationService.snycTree`, switching between tree nodes causes the tree to flicker (it appears to disappear and reappear). I thought it was to do with the `forceReload` syncTree option, but even with this set to false, it still flickers.

You can replicate this by creating some content which goes 2 or 3 levels deep. Then, switch between different nodes in that tree and you'll see it flicker. This doesn't appear to be a problem for tree nodes that only have a single path level, such as the doc types tree etc

**Comment by nul800sebastiaan** [comment] 2019-05-09 06:48
I can repro, weird :-)

![5403](https://user-images.githubusercontent.com/304656/57432775-0db14580-7237-11e9-8908-14ef6b2466f8.gif)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment] 2019-05-14 07:02
Nice one! I found the issue. Good news is the fix includes saving an xhr 😊 I'll push a PR soon as I'm near some decent network connection.

**Comment by kjac** [comment] 2019-05-14 07:49
My bad. It didn't solve the problem... it was just another, less noticeable bug (see #5454). I'll see if I can track this one down later.

**Comment by electricsheep** [comment] 2019-05-14 08:34
The flicker seems to be caused by the `display:none;` that is set for `.ng-animate`. I found a fix for this by adding 
```
.umb-tree-item.ng-animate.current-add {
    display: block;
}

.umb-tree-item.ng-animate.current-remove {
    display: block;
}
```
to `animations.less`. 

However, it doesn't quite work perfectly - when you switch from a child node to a parent (e.g. Todo list -> About Us), both nodes are visibly highlighted at the same time for a brief moment. Whereas if you switch between sibling nodes, only one node is ever highlighted at a time

**Comment by kjac** [comment] 2019-05-26 11:41
I've been digging deep into the JS and fortunately there's no reloading of nodes going on. As @electricsheep points out this is purely a CSS animation issue.

The fix is fairly straight-forward, and does not introduce the double highlighting as mentioned above. I'll post it tonight if I have time, or tomorrow morning 😄

**Comment by kjac** [comment] 2019-05-27 05:28
PR in #5523

**Comment by nul800sebastiaan** [comment] 2019-05-31 14:43
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5523

**Closed** 2019-05-31 14:42 UTC
Labels: community/up-for-grabs, help wanted
