### ISSUE TITLE
Stupid CMS not build in VS 2022 I have all .Net versions installed in my PC

### ISSUE THREAD

**Issue by ednsinf** [umbraco/Umbraco-CMS#17194] opened 2024-10-05 17:17 UTC
Stupid CMS not build in VS 2022 I have all .Net versions installed in my PC

### Bug summary

Stupid CMS not build in VS 2022 I have all .Net versions installed in my PC
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NETSDK1045	The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download	Umbraco.Cms, Umbraco.Cms.Api.Common, Umbraco.Cms.Api.Delivery, Umbraco.Cms.Api.Management, Umbraco.Cms.Imaging.ImageSharp, Umbraco.Cms.Imaging.ImageSharp2, Umbraco.Cms.Persistence.EFCore, Umbraco.Cms.Persistence.EFCore.Sqlite, Umbraco.Cms.Persistence.EFCore.SqlServer, Umbraco.Cms.Persistence.Sqlite, Umbraco.Cms.Persistence.SqlServer, Umbraco.Cms.StaticAssets, Umbraco.Cms.Targets, Umbraco.Core, Umbraco.Examine.Lucene, Umbraco.Infrastructure, Umbraco.JsonSchema, Umbraco.PublishedCache.HybridCache, Umbraco.Templates, Umbraco.TestData, Umbraco.Tests.AcceptanceTest.UmbracoProject, Umbraco.Tests.Benchmarks, Umbraco.Tests.Common, Umbraco.Tests.Integration, Umbraco.Tests.UnitTests, Umbraco.Web.Common, Umbraco.Web.UI, Umbraco.Web.Website	C:\Program Files\dotnet\sdk\8.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	166		
Error (active)	NETSDK1216	Package Microsoft.Net.Sdk.Compilers.Toolset is not downloaded but it is needed because your MSBuild and SDK versions are mismatched. Ensure version 9.0.100-rc.1.24452.12 of the package is available in your NuGet source feeds and then run NuGet package restore from Visual Studio or MSBuild.	Umbraco.Cms, Umbraco.Cms.Api.Common, Umbraco.Cms.Api.Delivery, Umbraco.Cms.Api.Management, Umbraco.Cms.Imaging.ImageSharp, Umbraco.Cms.Imaging.ImageSharp2, Umbraco.Cms.Persistence.EFCore, Umbraco.Cms.Persistence.EFCore.Sqlite, Umbraco.Cms.Persistence.EFCore.SqlServer, Umbraco.Cms.Persistence.Sqlite, Umbraco.Cms.Persistence.SqlServer, Umbraco.Cms.StaticAssets, Umbraco.Cms.Targets, Umbraco.Core, Umbraco.Examine.Lucene, Umbraco.Infrastructure, Umbraco.PublishedCache.HybridCache, Umbraco.Templates, Umbraco.TestData, Umbraco.Tests.Benchmarks, Umbraco.Tests.Common, Umbraco.Tests.Integration, Umbraco.Tests.UnitTests, Umbraco.Web.Common, Umbraco.Web.UI, Umbraco.Web.Website	C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	261

**Comment by nikcio** [comment] 2024-10-06 10:32
Hi @ednsinf 

You're trying to build the source code directly which is currently in development for version 15 which is targeting the new .NET 9. As .NET 9 is in preview you will need VS 2022 Preview to install this version before its stable release: https://visualstudio.microsoft.com/vs/preview/

This is not a bug of Umbraco but a local installation problem.

If you want to create an Umbraco install you're properly not looking to use the source code directly but rather install the NuGet package with the version of the CMS you want to use. You can use the installation guide found in the documentation to get started: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install

**Comment by Zeegaan** [comment] 2024-10-07 06:31
Heyo, as @nikcio already provided an excellent explanation, I will go ahead and close this. 
Please also keep the tone friendly when posting issues. 🐛

**Closed by Zeegaan** 2024-10-07 06:31 UTC
Labels: type/bug
