### ISSUE TITLE
Can't have Login/Error pages as child nodes of protected parent in V9

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#12007] opened 2022-02-15 14:26 UTC
### Which *exact* Umbraco version are you using?

9.3.0

### Bug summary

When having a protected root node you are unable to have a Login/Error page as a child, it will throw the following error:
`InvalidOperationException: Public Access rule has a redirect node set to itself, nothing can be routed.`

This used to work in V8, so I'm not entirely sure if this falls in the '**bug**' or '**intended functionality**' section. If it's a bug, great, if it's not, extra functionality should be added so you cannot select a child of the node you are trying to protect + extra message explaining this in the backoffice.

### Specifics

Full error:
`System.InvalidOperationException: Public Access rule has a redirect node set to itself, nothing can be routed.
   at Umbraco.Cms.Web.Website.Routing.PublicAccessRequestHandler.SetPublishedContentAsOtherPageAsync(HttpContext httpContext, IPublishedRequest publishedRequest, Int32 pageId)
   at Umbraco.Cms.Web.Website.Routing.PublicAccessRequestHandler.RewriteForPublishedContentAccessAsync(HttpContext httpContext, UmbracoRouteValues routeValues)
   at Umbraco.Cms.Web.Website.Routing.UmbracoRouteValueTransformer.TransformAsync(HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Mvc.Routing.DynamicControllerEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 119
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

### Steps to reproduce

Create a new V9.3 project. 

Create a Homepage as root, with a login page and an error page as childs, each with a template assigned.
Create a member / membergroup.
Set up protection on the root/homepage node and select the created error/loginpages.

Error will show on frontend on navigating to the homepage.

### Expected result / actual result

In V8 you could have child login/errorpages on a protected parent.

---
_This item has been added to our backlog [AB#19681](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/19681)_

**Comment by nul800sebastiaan** [comment] 2022-03-02 13:04
Hi @Ambertvu - no this seems like a bug. 

So to be clear, this is my tree:

![image](https://user-images.githubusercontent.com/304656/156365964-aaf8ec5a-01c0-4bc9-aecd-0951d7fd3be0.png)

When I go to `/Intranet` I should be redirected to `/Intranet/Login` to be able to login. 

A bit of a surprising bug then as I looked at the code:

https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.Website/Routing/PublicAccessRequestHandler.cs#L129

We ONLY check `if (pageId != publishedRequest.PublishedContent.Id)` - should work, right!? 

Indeed we're seeing currentpage is Internet. 1119 and Login page is Id 1120:

![image](https://user-images.githubusercontent.com/304656/156366582-df6b7e33-52c9-4497-9109-7e0a0152f219.png)

Right, it does actually work, however then we redirect from the protected page to the login page.. and that's when we get in trouble, at that point the pageId and the published content Id is apparently the same. 

Now both the currentpage and the login page are the same. This is actually to be expected! Because.. we just redirected there.

![image](https://user-images.githubusercontent.com/304656/156366778-01aa58bd-a944-4d38-a37b-25dc86716d05.png)

The problem is now.. I don't know how to fix it, easiest would be to allow the current and login page to be the same, which is not quite right all of the time, but would that really be a problem? 🤔 

I'll give it another think!

**Comment by merly-cortez** [comment] 2022-05-18 11:33
I am having the same issue. Is there a workaround in the mean time?

**Comment by nul800sebastiaan** [comment] 2022-05-19 08:59
@merly-cortez Haven't found a way to fix it yet but in the mean time make sure your login and error pages are not under the nodes you're trying to require login for.

So not

- Home
  - 🔒Intranet
    - Login
    - Error

But 
- Home
- 🔒Intranet
- Login
- Error

We'll have a look at it in one of our upcoming sprints.

**Comment by Zeegaan** [comment] 2022-07-05 07:34
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12620

**Closed by Zeegaan** 2022-07-05 07:34 UTC
Labels: state/sprint-candidate, type/bug

**Comment by merly-cortez** [comment] 2022-08-01 23:42
> Fixed in #12620

Hi, I'm sorry am not familiar with Umbraco's release pipeline. This is marked for release 9.5.3 but I don't see any In progress version for v9. Will this be fixed in v9?

**Comment by bergmania** [comment] 2022-08-02 05:56
Hi @merly-cortez .. The plan is to release it for v9, but we do not have any target dates yet

**Comment by ajatnow** [comment] 2025-03-27 23:51
I am using v13.7.2 and seeing this exact issue occurring.

My edge case however, is that my entire site is restricted. The Home item itself is restricted with the Login page is a child item of Home. I cannot move Login.

Getting the original reported error message.
