### ISSUE TITLE
Users other than admin get kicked out the system when viewing content

### ISSUE THREAD

**Issue by sinkypars1885** [umbraco/Umbraco-CMS#7903] opened 2020-04-06 10:43 UTC
When you assign a user as an editor (or any group other than admin) they cannot browes the nodes in the back end and are redirect to the login page. A consol error is thrown:

![image](https://user-images.githubusercontent.com/62436117/78550274-b1b2c080-77fb-11ea-820d-dbab258d61b7.png)

I am seeing this issue on Umbraco version: 8.6

This occurs on Chrome and Firefox

**Comment by nul800sebastiaan** [comment] 2020-04-06 11:05
Yikes, I can reproduce this, even when setting explicit start nodes.. We'll have a look asap!

**Comment by sinkypars1885** [comment] 2020-04-09 12:28
Is there a work around to fix this whilst we wait for 8.6.1.

Should I perhaps downgrade and if so, can you let me know which version this is not an issue on?

**Comment by nul800sebastiaan** [comment] 2020-04-15 19:16
@sinkypars1885 Upon reflection, I am pretty sure it's not actually a bug. I think what I'm seeing is:

- Create new user in the users section
- Log out
- Immediately log in as the less privileged user

It will try to load the Users section but the user has no access to it - this is because Umbraco sets a cookie to remember where we were before getting logged out. As soon as I log in in a different browser everything is fine. Also if I just go to mysite.com/umbraco and refresh the page and then log in as the editor, it's also fine.

If this was a widespread issue I think we'd have way more reports about it.

**Comment by nul800sebastiaan** [comment] 2020-04-23 10:48
I'll close this for now as I haven't seen any new reports of this, seems to be localized to your site.

**Closed by nul800sebastiaan** 2020-04-23 10:48 UTC
Labels: state/needs-more-info
