### ISSUE TITLE
Media Picker DataType ability to set a limit

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8714] opened 2020-08-24 12:05 UTC
We should be able to set a range of required items of the Multi Media Picker.

The user should be able to pick freely but the property should fail validation if the requirements arent meet. We should always show a text letting the user know when they are short or has too many items selected, like we do with the limits of TextBox.

The Prevalue editor should use the Range type, looking like this:

![image](https://user-images.githubusercontent.com/6791648/91042891-d379dc00-e612-11ea-8bdc-bd05ddfbfe4a.png)

**Comment by matthewcare** [comment] 2020-08-25 07:07
Duplicate of #8471

**Comment by bjarnef** [comment] 2021-01-13 23:20
There is a few other related issues here:
https://github.com/umbraco/Umbraco-CMS/issues/8471
https://github.com/umbraco/Umbraco-CMS/issues/4922

**Comment by nul800sebastiaan** [comment] 2021-05-28 11:21
Fixed in 8.14.

**Closed by nul800sebastiaan** 2021-05-28 11:21 UTC
Labels: category/ux, community/up-for-grabs
