### ISSUE TITLE
Blocklist - Duplication issues with Content Templates

### ISSUE THREAD

**Issue by jerpenol** [umbraco/Umbraco-CMS#13901] opened 2023-03-01 15:31 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.17.0 and 11.1.0

### Bug summary

We encountered a weird issue when using Content Templates containing BlockLists, where a newly created page (created with the Content Template) did not display the content of the block within the BlockList, but displayed the content of a block of another page. The other page being the page from which the Content Template was created.

Upon further inspection we noticed that when we open the Network window and inspect the response of the GetById call, that the Udi of the block was the same as the Udi of the block on the other page. 

To further inspect the problem I tried the following:
1. Create a new node with a block in the blocklist
2. Create a copy of this node with "Relate to Original" being **false**
3. Create a copy of this node with "Relate to Original" being **true**
4. Create a new node and copy/pasted the entire blocklist from the original
5. Reuse the node created in 4 but copy/pasted the single block value to the new blocklist 
6. Create a Content Template of the original and create a new node based on it

These tests resulted in the following Udi's for the block in the blocklist:
1. Original = **96019e7d69bc4fc7972a0f57fead6124**
2. Unrelated Copy = e87f33d9bfc04d0eabba702c563f93ff
3. Related Copy = a79177ccc71d452cb1ba67c4bf8852ad
4. Copied BlockList = 98f209d954b2490a9ff08b7091a42da4
5. Copied Block = 77b0158b69884d7083877cf8b86dbe64
6. Content Template = **96019e7d69bc4fc7972a0f57fead6124**

As you can see when using the Content Template the Udi of the block remains the same as the original node the content template was based on. This causes the new node (created in step 6) to display the block values of the block in the original node.

### Specifics

This issue occurred on a website running on 11.1.0 in all browsers. I then tested this on another site using BlockLists which ran on 8.17.0. Both websites displayed the same issue.

### Steps to reproduce

1. Create a new Content Type called "MyPage"
    - Make sure the Content Type is created with a view
3. Create a new Content Type called "MyBlock"
    - Set "Is an Element Type" under the "Permissions" tab to **true**
4. Add a property to "MyBlock" called "Text"
    - Editor: Textstring
5. Create a new Data Type called "MyBlockList"
    - Property editor: Block List
    - Available blocks: "MyBlock"
6. Add a property called "BlockList" to the "MyPage" Content Type
    - Editor: MyBlockList
7. Render the text property of the blocks in "BlockList" in the "MyPage.cshtml" view
8. Create and Publish a node of type "MyPage" called "Duplication Test - Original"
    - Add a block to the "BlockList" property and fill in the "Text" property with "Original Text"
9. Create a Content Template based on "Duplication Test - Original" and call it "Duplication Test Template"
10. Create a node of type "MyPage" based on the "Duplication Test Template" Content Template and call it "Duplication Test - Copy"
11. Open the prefilled block in the "BlockList" property of the newly created "Duplication Test - Copy"
12. Change the "Text" property to "Copy Text"
13. Publish "Duplication Test - Copy"
14. Navigate to the front-end of "Duplication Test - Original" and to "Duplication Test - Copy" in another tab

### Expected result / actual result

**Expected**
_Front-end_: "Duplication Test - Original" should display "Original Text" and "Duplication Test - Copy" should display "Copy Text". 
_Backoffice_: If you inspect the GetById call in the network tab when opening "Duplication Test - Copy" the block Udi should be different from the block Udi of "Duplication Test - Original".

**Actual**
_Front-end_: "Duplication Test - Original" displays "Original Text" and "Duplication Test - Copy" displays "Original Text" aswel. 
_Backoffice_: If you inspect the GetById call in the network tab when opening "Duplication Test - Copy" the block Udi is the same as the block Udi of "Duplication Test - Original".

**Comment by nikolajlauridsen** [comment] 2023-03-02 09:05
Heya, thanks for the very detailed description, that's always appreciated. 

However, this seems to be a duplicate of #13413 and by extension #13698 (that's the root cause) so I'm going to go ahead and close down this issue, but thanks for reporting 👍 🐛 🕵️

**Closed by nikolajlauridsen** 2023-03-02 09:05 UTC
Labels: type/bug
