### ISSUE TITLE
v14.3 - BlockGrid - "Overlay editor size" - has no effect

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#17324] opened 2024-10-21 11:54 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3

### Bug summary

Setting the "Overlay editor size" to something other than "small" has no effect when editting the block grid element.

The feature works in version 13

### Steps to reproduce

Create element type with eg. a RTE property

Create "Block Grid" datatype
- add the element type created before as a block item

Create document type that can be created in root and add a property of the previous created datatype

Create a content node of the created document type
- Add block item and add some content to the editor.
- Save the node
- Click the edit-pencil on the property and see that the side panel width is approx 40 %

Edit the blockgrid datatype
- edit the blocks item
- switch to the "Advance" tab
- change the "Overlay editor size" to Large or Full
- Submit -> Save

Edit the content node
- Click the edit-pencil on the property
- The side panel has the same size as before :-(

![image](https://github.com/user-attachments/assets/1b2ad05f-fbaf-46fd-b276-fd54d11711fe)

### Expected result / actual result

Actual: In v14.3 - With "Large" as value
![image](https://github.com/user-attachments/assets/e288581d-36c0-4075-84a1-b8ebf1adbcfc)

Expected: In v13 - with "Large" as value
![image](https://github.com/user-attachments/assets/f2af4616-f95d-4d20-a74b-888e12d1bfc8)

**Comment by nielslyngsoe** [comment] 2024-10-21 13:07
Hi @mjpraxis thanks for reporting, this is thought already reported. So I'm closing this one :-)

**Comment by nielslyngsoe** [comment] 2024-10-21 13:08
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/17000

**Closed by nielslyngsoe** 2024-10-21 13:08 UTC
Labels: type/bug
