### ISSUE TITLE
Can't highlight username on login screen

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#6023] opened 2019-07-30 14:31 UTC
Type in a username on the login screen and then try to select the text with the mouse. You simply can't. Only way to clear the text box is put the cursor in the box at the end and delete. Very odd!

Frustrating when trying to login with different credentials to the ones Chrome has remembered. Seems to only be a Chrome issue, tried it in Edge v44 and IE11.

Doesn't appear to be a CSS thing (I tried disabling some styles in dev tools). I think there is an event that is firing which is stopping it. If you wiggle the mouse up and down while going side ways sort of in a zigzag then it does end up highlighting it just but its painful!

![image](https://user-images.githubusercontent.com/1674590/62137597-2123f800-b2de-11e9-8154-7d0c3366f123.png)

![image](https://user-images.githubusercontent.com/1674590/62137850-8a0b7000-b2de-11e9-9339-33bbd2af131d.png)

Can't see this getting to the top of anyones hit list of "hot fixies in v8.2!" but if someone likes a challenge then this might be a fun one to check out.

**Comment by nul800sebastiaan** [comment] 2019-08-02 05:51
Hmm, I'm on Chrome 77 already so maybe it's a Chrome bug but I can't repro. Have you checked in incognito mode too without any add-ons activated?

![6023](https://user-images.githubusercontent.com/304656/62347497-370e0480-b4fa-11e9-9c05-17f259393a31.gif)

**Comment by stevemegson** [comment] 2019-08-02 09:25
I can reproduce it in v7, but not v8. It looks like ng-swipe-right is grabbing mousemove events on the form.

**Comment by nul800sebastiaan** [comment] 2020-05-04 11:51
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6204

**Closed by nul800sebastiaan** 2020-05-04 11:51 UTC
Labels: community/pr, release/7.15.5, type/bug

**Comment by PeteDuncanson** [comment] 2020-05-04 11:54
Woot! Good debug skillz @stevemegson :)
