### ISSUE TITLE
Umbraco allows to rename user to contain space but doesnt let create user with space 

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#14822] opened 2023-09-18 14:48 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

Found as part of:
https://github.com/umbraco/Umbraco-CMS/issues/14808

### Steps to reproduce

set UsernameIsEmail to false
try to create user with name containing a space in login
you will noticed user wan't created

**Comment by Zeegaan** [comment] 2023-09-19 13:39
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14810 😁

**Closed by Zeegaan** 2023-09-19 13:39 UTC
Labels: type/bug

**Comment by bielu** [comment] 2023-09-19 15:32
@Zeegaan it is not fixed based on your comment from original Ticket, as it didnt let you create user without space. so this ticket is if it should blocked both or it should allow both :)

**Comment by Zeegaan** [comment] 2023-09-19 16:32
@bielu My original comment was before applying your fix, with your fix applied, this did work as intended 😁

**Comment by bielu** [comment] 2023-09-19 17:06
Ah so I fix both by incident 🤣

**Comment by Zeegaan** [comment] 2023-09-19 17:08
Yep 🤣
