### ISSUE TITLE
Unable to click the List/Grid to select how to view the Child Items bacause content pop down list

### ISSUE THREAD

**Issue by syska** [umbraco/Umbraco-CMS#6842] opened 2019-10-24 21:06 UTC
Reproduction
------------
Umbraco CMS version 8.2.0
Install starter template

### Steps to reproduce

Go to the "Products" node ... try to click the icon to switch view type.

### Expected result

Being able to switch Grid/List view ... 
![image](https://user-images.githubusercontent.com/317770/67525142-6627b280-f6b2-11e9-9a6b-bb84f22c7804.png)

### Actual result

![image](https://user-images.githubusercontent.com/317770/67525174-78a1ec00-f6b2-11e9-8aba-8c4c5a6d62a7.png)

The items from the "Content" pops up over the icon ...

**Comment by kjac** [comment] 2019-10-25 05:16
Hi @syska! 

I think this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/6794 which will be fixed in an upcoming release.

**Closed** 2019-10-25 08:35 UTC
