### ISSUE TITLE
Bug: Cant install Umbraco 8 using nuget on website projects

### ISSUE THREAD

**Issue by jesperordrup** [umbraco/Umbraco-CMS#4818] opened 2019-03-01 17:09 UTC
Installing using nuget on regular web application works fine but when installing using project type "ASP.NET Empty Website" the installer fails. Initially it looks great. It runs until you enter email and password. Then install stops with an error.

Reproduction
------------

### Steps to reproduce

In visual studio, create a "ASP.NET Empty Website"
Open package manager
Run Install-Package umbracoCms
Disable build
Run (with or without debugging, doesnt matter)
Install starts
Enter name and email details and submit form.
Install stops (see screenshot).

### Expected result

I expected the install to continue just as when using "ASP.NET Web application"  projects. 
This also works using Umbraco 7

### Actual result

Install stops. See screenshot and log
After submitting the form you get:

![image](https://user-images.githubusercontent.com/3120151/53653617-ff99e400-3c4b-11e9-9e19-27f670183551.png)

### Log says:

{"@t":"2019-03-01T15:31:04.3003229Z","@mt":"Installation step {Step} failed.","@l":"Error","@x":"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlServerCe.SqlCeException: Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8902. Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details.\r\n   at System.Data.SqlServerCe.NativeMethods.LoadNativeBinaries()\r\n   at System.Data.SqlServerCe.SqlCeEngine..ctor()\r\n   at Umbraco.Core.Migrations.Install.DatabaseBuilder.ConfigureEmbeddedDatabaseConnection(IUmbracoDatabaseFactory factory, ILogger logger)\r\n   at Umbraco.Web.Install.InstallSteps.DatabaseConfigureStep.ConfigureConnection(DatabaseModel database)\r\n   at Umbraco.Web.Install.InstallSteps.DatabaseConfigureStep.ExecuteAsync(DatabaseModel database)\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__14.MoveNext()","Step":"DatabaseConfigure","SourceContext":"Umbraco.Web.Install.Controllers.InstallApiController","ProcessId":45436,"ProcessName":"iisexpress","ThreadId":5,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-EOTDOFL","Log4NetLevel":"ERROR","HttpRequestNumber":2,"HttpRequestId":"d31f3b50-9af7-4d2b-8aae-314ab31b59bb"}

**Comment by nul800sebastiaan** [comment] 2019-03-01 17:13
Does it work from a ZIP install?

Does your bin folder contain the x86 / amd64 folders?

![image](https://user-images.githubusercontent.com/304656/53654239-869b8c00-3c4d-11e9-9279-075ca7c16dc4.png)

**Comment by nul800sebastiaan** [comment] 2019-03-01 17:15
Aha, so empty website project doesn't work.. pdd. It's not really supported but it probably should work. I'll run some tests. Still would be good to know if the two folders are in your bin.

**Comment by nul800sebastiaan** [comment] 2019-03-01 17:18
How do you start a new website project? This option no longer exists in VS2017 (and you'll need VS2017) to use v8.

**Comment by jesperordrup** [comment] 2019-03-01 17:25
> Does it work from a ZIP install?

Yes it does. Unzipping, open as website, run. It works.
Unexpected bonus info: Also completing using a Web application project then open as website works.

 
> Does your bin folder contain the x86 / amd64 folders?
Both folders are missing

**Comment by jesperordrup** [comment] 2019-03-01 17:26
> How do you start a new website project? This option no longer exists in VS2017 (and you'll need VS2017) to use v8.

![image](https://user-images.githubusercontent.com/3120151/53655020-6a98ea00-3c4f-11e9-9e0f-6c0551168ae3.png)

Im using the lastest and greatest VS17 - 15.9.7 and im selecting .net framework 4.7.2

**Comment by nul800sebastiaan** [comment] 2019-03-01 17:57
Cool, you must have an older install that included that template and it carried over while upgrading. I don't have this template and it seems unsupported now: https://stackoverflow.com/a/47782728

In any case, looks like you have found alternatives. I remember that we tried to make this work in v7 for the longest time and it involved getting the paths in the install scripts "just right" to work with both a web application and a web site project. I can't find how we fixed it though and I am not even sure it actually worked in v7 (do you?).

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by jesperordrup** [comment] 2019-03-02 16:01
@nul800webastiaan
Yep - it works in 7. 

From the link it seems they've moved it around, not sure it's unsupported. 

I could have a look at it. Any pointers?

(Or we could move to web apps - but I don't feel for them)

**Comment by nul800sebastiaan** [comment] 2019-08-29 19:18
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-08-29 19:18 UTC
Labels: community/up-for-grabs, help wanted, type/feature
