### ISSUE TITLE
IMemberManager.FindByIdAsync does not work in event handler (outside request context?)

### ISSUE THREAD

**Issue by glenatron** [umbraco/Umbraco-CMS#14633] opened 2023-08-02 16:06 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

I needed to get a member from their Id after start-up so I created a class that implements `INotificationAsyncHandler<UmbracoApplicationStartedNotification>` and has several services passed in.  These are called in separate async tasks. One of these includes an `IMemberManager` which it used by calling `await _memberManager.FindByIdAsync(id.ToString());`

### Specifics

Calling  `await _memberManager.FindByIdAsync(id.ToString());` causes an immediate crash: 
```
'_memberManager.FindByIdAsync(id.ToString())' threw an exception of type 'System.ObjectDisposedException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146232798
    HelpLink: null
    InnerException: null
    Message: "ObjectDisposed_Generic\r\nObjectDisposed_ObjectName_Name"
    ObjectName: "MemberManager"
    Source: "Microsoft.Extensions.Identity.Core"
    StackTrace: "   at Microsoft.AspNetCore.Identity.UserManager`1[[Umbraco.Cms.Core.Security.MemberIdentityUser, Umbraco.Infrastructure, Version=10.6.1.0, Culture=neutral, PublicKeyToken=null]].ThrowIfDisposed()\r\n   at Microsoft.AspNetCore.Identity.UserManager`1[[Umbraco.Cms.Core.Security.MemberIdentityUser, Umbraco.Infrastructure, Version=10.6.1.0, Culture=neutral, PublicKeyToken=null]].FindByIdAsync(String userId)\r\n   at <>x.<>m0(<GetMembers>d__24 <>4__this)"
    TargetSite: {Void ThrowIfDisposed()}
```

My guess would be that the underlying identity provider doesn't work outside of a request context, but that is a guess.

Note that in my real-life case, all the other Umbraco services provided by the IOC container work correctly, it is only the IMemberManager that suffers from this problem.

### Steps to reproduce

This is happening in a very complex application and I don't have time to create a minimal reproduction but I would expect the following to do the trick:

Create a class that injects `IMembershipManager` - I'll call this `MemberCrasher`

Create a class that implements `INotificationAsyncHandler<UmbracoApplicationStartedNotification>` - probably any other event notification would work as well - and inject the `MemberCrasher` into this on startup.

```
public class MemberCrashTrigger: INotificationAsyncHandler<UmbracoApplicationStartedNotification> {

private MemberCrasher _memberCrasher;

public MemberCrashTrigger( MemberCrasher crasher ) {
         _memberCrasher = MemberCrasher;
}

public Task HandleAsync(UmbracoApplicationStartedNotification notification, CancellationToken cancellationToken)
    {
        return Task.Run(async() => _memberCrasher.CrashMemberAsync())
    }
}
```

Include it in your composer: `builder.AddNotificationAsyncHandler<UmbracoApplicationStartedNotification, MemberCrashTrigger>();`

Note that because it happens in a background thread the crash may only show up in the output of your server or in a debugger, it won't cause Umbraco pages to fail.
 

### Expected result / actual result

Ideally it would be nice if the `IMembershipManager` allowed one to retrieve a user instead of silently crashing.

**Comment by bergmania** [comment] 2023-08-03 05:29
Pretty sure this is related to https://github.com/umbraco/Umbraco-CMS/issues/14574

**Comment by bergmania** [comment] 2023-08-03 05:40
Yeah, just tested after that fix with the following code, and that seems to work.

I'll close as duplicate, but thanks for the detailed description.

```cs
public class TestComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.AddScoped<MemberCrasher>();
        builder.AddNotificationAsyncHandler<UmbracoApplicationStartedNotification, MemberCrashTrigger>();
    }
}

public class MemberCrashTrigger: INotificationAsyncHandler<UmbracoApplicationStartedNotification> {

    private MemberCrasher _memberCrasher;

    public MemberCrashTrigger(MemberCrasher crasher ) {
        _memberCrasher = crasher;
    }

    public Task HandleAsync(UmbracoApplicationStartedNotification notification, CancellationToken cancellationToken)
    {
        return Task.Run(async () => _memberCrasher.CrashMemberAsync());
    }
}


public class MemberCrasher
{
    private readonly IMemberManager _memberManager;

    public MemberCrasher(IMemberManager memberManager)
    {
        _memberManager = memberManager;
    }

    public async Task<MemberIdentityUser> CrashMemberAsync()
    {
        var id = -1;
        var x = await _memberManager.FindByIdAsync(id.ToString());
        return x;
    }
}
```

**Comment by bergmania** [comment] 2023-08-03 05:42
Duplicate of #14574

**Closed by bergmania** 2023-08-03 05:42 UTC
Labels: type/bug
