### ISSUE TITLE
Block List Editor: Block Appearance - Label displays angular statement on initial creation

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco-CMS#14365] opened 2023-06-08 16:42 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

The block list editor with a custom label utilizing {{propertyAlias}} no longer work on initial creation of a block. The backoffice label outputs the actual plain text of the label angular statement.

### Specifics

For example, when setting up a block to use in the block list editor that has a property with the alias "heading", when you initially create that block in the block list, the label will reflect the {{heading}} text.

Example of initial creation of a block in block list editor. Note the angular statement appears in the label area.
![image001](https://github.com/umbraco/Umbraco-CMS/assets/4968254/54520e5e-d8e2-40a4-8916-7418d08bb255)

The configuration of the block list editor block label looks like this:
![image003](https://github.com/umbraco/Umbraco-CMS/assets/4968254/424a7ad6-959d-48d3-b8b1-47b7a033ea08)

In Umbraco version 11.2.0 this was working and on initial creation the block label would not display the angular statement.
![image002](https://github.com/umbraco/Umbraco-CMS/assets/4968254/a79eb1e9-b675-44c6-9d61-403dd77d4f82)

### Steps to reproduce

1. Create a doctype element (example headline) with a textstring property with the alias of heading
2. Create a block list editor that allows the headline element in the block list
3. Configure the block appearance label to utilize the alias of the heading {{heading}}
4. Create a doctype that is allowed in your content tree that contains the block list editor 
5. Create the doctype in your content tree
6. Click to Add content to your block list editor property
7. Notice when the dialog opens, the label for that dialog will reflect the angular statement

**NOTE:** After you have added a heading and saved the block list element, the heading will be reflected correctly. It is  the initial load of the null/empty state that displays the angular statement.

### Expected result / actual result

When you create block list content that utilizes a custom label, on initial load that custom label would not display because it is empty.

Example: "Full Width -" 
![image002](https://github.com/umbraco/Umbraco-CMS/assets/4968254/6b46172e-6538-4d6a-8283-442503d7b4cb)

**Comment by nikolajlauridsen** [comment] 2023-06-09 06:29
Hey @bkclerke this is a duplicate of #14105 so I'll go ahead and close this one, but thank you for reporting, it is appreciated 😄

**Closed by nikolajlauridsen** 2023-06-09 06:29 UTC
Labels: type/bug
