### ISSUE TITLE
14.3: Clicking name in mediapicker opens item as folder

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#17210] opened 2024-10-08 07:59 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3

### Bug summary

When using the MediaPicker and browsing for an image, you see the two parts of an image. The Image itself and a title. Click the image results in selection of the item. Click the name results in opening the image as a folder.

### Steps to reproduce

Add a few images. 
Add a mediapicker
Try to select a image. Click on the title, image opens as folder
![image](https://github.com/user-attachments/assets/014f67dd-424a-470c-b372-1afcd57b7350)
![image](https://github.com/user-attachments/assets/1fa91159-a765-4737-a687-8bfcde157b5a)

### Expected result / actual result

Image is selected, unless it is actually a Folder

**Comment by iOvergaard** [comment] 2024-10-08 13:14
Hello, thanks for the report. The media item is potentially a folder (at least you can have files nested underneath any media item, and the media picker can't check if you have, so it defaults to all items acting as folders). There is a duplicate of this report over at #16398, and I would like to track the progress there, where we intend to improve on the UX of the media picker. Hope it's ok that I close this one!

**Closed by iOvergaard** 2024-10-08 13:14 UTC
Labels: type/bug

**Comment by Ambertvu** [comment] 2024-10-09 06:23
All good, couldn't find the other ticket :-)

Thanks!
