### ISSUE TITLE
[v9.0.0-beta003] PostSetUserTour doesn't seem to persist until apppool recycle

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#11081] opened 2021-09-12 16:17 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9.0.0-beta003

### Bug summary

Upon upgrading from 002 to 003, clicking "Don't show this tour again", doesn't seem to actually persist. On next refresh, it will simply popup again.

Only after I did a recycle of the apppool, did it stop bothering me.

### Steps to reproduce

Upgrade a beta002 to beta003, login, click "Don't show this tour again", then refresh. The popup will show again.

### Expected result / actual result

The popup doesn't come back.

---
_This item has been added to our backlog [AB#13863](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13863)_

**Comment by nul800sebastiaan** [comment] 2021-09-13 08:56
I can reproduce, it's saving my TourData correctly but apparently not reading it correctly again after that:

![image](https://user-images.githubusercontent.com/304656/133054830-35343af9-b62b-4824-b567-e7eec9fd2cd7.png)

**Comment by Zeegaan** [comment] 2021-09-22 08:20
This is a bit embarrasing but i've been looking at this issue the past few days, and I just cannot find out what causes this bug.

I can replicate the issue just as described, and I've been doing some digging 🕵️ 
It seems that we save the TourData of the User just fine in the database, but something goes wrong in the cache, when I'm stepping through it.

It clears just fine, and the new TourData is saved in the cache, but all of a sudden it just comes back for no apparent reason, so until we can find out what is causing this Issue, the workaround sadly has to be that you just recycle the app pool 😖

**Comment by nul800sebastiaan** [comment] 2021-09-22 08:26
Thanks @Zeegaan - let's go with the "solution" being: recycle the app pool. It fixes the problem and the tour popup seems to behave properly after that! I'll close this issue for now but let us know if that doesn't seem to help for you @LennardF1989!

**Closed by nul800sebastiaan** 2021-09-22 08:26 UTC
Labels: project/v9, state/sprint-candidate, type/bug

**Comment by LennardF1989** [comment] 2021-09-22 21:53
This is acceptable for me :) I think the bigger question is: what causes the cache to reintroduce a cleared value. If it happens here, I can only assume it happens elsewhere as well, potentially even during runtime operation of the CMS itself - which is a lot more concerning than me having the recycle to get rid of the tour popup :P

**Comment by Zeegaan** [comment] 2021-10-05 11:51
I found out what was causing the issue, it was an artifact from migrating from 7.11 - 7.12, and we had to ignore tourdata when updating! This is now obsolete and has been removed in https://github.com/umbraco/Umbraco-CMS/pull/11277
