### ISSUE TITLE
Adding a settings model to a blocklistblock throws unexpected errors

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco-CMS#10031] opened 2021-03-22 13:20 UTC
I'm running into this issue in multiple versions of Umbraco inclusing 8.12.1 and also in content.
If you add settings to a existing block and add a property this will throw errors on existing content.

How to reproduce:
- Add a blocklist editor to a page without settings.
- Create content
- Render content (all is fine)
- Add a settings model with a property
- Access in the template by doing for example: `Model.Settings.Value("key");`

I expected it to return a value or null.

What happens is that I get a null exception.
If you want to push this change to live you need to do null checks on settings or you need to resave all content using that block.

**Comment by emma-hq** [comment] 2021-03-24 10:02
Hey Frans, 

Thanks for reporting! I'll follow the steps to reproduce and let you know what I find.

Emma

**Comment by mastrup** [comment] 2021-08-12 11:59
Switching from one settings model to another will throw an error on all existing blocks.
You need to keep using the first chosen settings model if you want your existing blocks to keep working.
Resaving existing blocks will not fix it.

Tested on 8.15.0.

**Comment by ronaldbarendse** [comment] 2021-08-12 22:18
This is expected behavior: when there are no settings stored/saved, `Model.Settings` will indeed return `null`. This also can't be easily fixed, because just constructing an empty settings model might end up with different default values. Checkboxes for example can be enabled by default, but that is something done in the data editor when it's rendered in the back-office. It's also possible to set default values using `EditorModelEventManager`, which is also something only used by the back-office.

This is also the same for mandatory properties: you can have content saved without values before making it mandatory. Expecting it to always have a value would then be a wrong assumption and you'd also have the write checks to guard against this.

Somewhat related might be PR https://github.com/umbraco/Umbraco-CMS/pull/8854, which fixes an exception after changing the settings model/element type.

**Comment by RBerntsen** [comment] 2021-08-23 14:04
> You need to keep using the first chosen settings model if you want your existing blocks to keep working.
> Resaving existing blocks will not fix it.

I'm the co-creator of #10373 that mentions this problem and I still believe this is a bug. The UI allows you to change the settings model from one type to another but the type is never changed, even though you save and publish etc. This means you can never change a blocks settings model without recreating the content, which of course is not a solution.

**Comment by ronaldbarendse** [comment] 2021-09-02 14:58
@RBerntsen Yes, PRs #8854 and #10993 indeed fixes issues with adding/changing a Block List settings model. But even then, you'd need to re-save/publish your content to populate the `Model.Settings` value, otherwise it will still return `null` (as there's no settings data stored yet).

**Comment by RBerntsen** [comment] 2021-09-03 06:41
@ronaldbarendse That sounds all right to me :)

**Comment by ronaldbarendse** [comment] 2021-09-09 11:48
@FransdeJong I'll close this issue, as the fixes are part of 8.17 (the RC is released today, in case you already want to test this out). And if `Model.Settings` is `null`, it should only be because there's no settings data (of the correct element type) stored for that block.

**Closed by ronaldbarendse** 2021-09-09 11:48 UTC
Labels: state/needs-investigation

**Comment by FransdeJong** [comment] 2021-09-09 11:51
@ronaldbarendse,  So the null exception from my initial description is now solved?

**Comment by ronaldbarendse** [comment] 2021-09-10 09:19
> So the null exception from my initial description is now solved?

You should still always check whether `Model.Settings` is not null before trying access it, e.g. using `Model.Settings?.Value("key")` or `@(Model.Settings?.Value("key"))` (when using inline Razor code). It's still possible there's no settings data stored or the stored settings type doesn't match the configured one, which would result in a `null` value (which is expected). In that regard, the expectation in your initial description is actually not correct (as you haven't re-saved the content, so the settings data is stored).

One of the PRs contains an example showing this using the generic model type: https://github.com/umbraco/Umbraco-CMS/pull/8854#issuecomment-906421607 and for PR https://github.com/umbraco/Umbraco-CMS/pull/10993 there's a video showing what's not fixed: https://github.com/umbraco/Umbraco-CMS/issues/10373#issuecomment-906490036.
