### ISSUE TITLE
v13: Blocks in RTE not rendering after save

### ISSUE THREAD

**Issue by mttblss** [umbraco/Umbraco-CMS#15516] opened 2024-01-01 08:35 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

In the back-office, when editing a content page that includes an RTE with blocks, following a Save or Save and Publish the following happens:
- The edit link on the embeded block cannot be clicked
- The html/angular preview does not display correctly (content is missing)

**Before**:
<img width="778" alt="Before" src="https://github.com/umbraco/Umbraco-CMS/assets/69298283/69a6c11c-c285-4a50-9c85-5b01d24d1042">

**After**:
<img width="779" alt="After" src="https://github.com/umbraco/Umbraco-CMS/assets/69298283/e0e1c6a2-7400-4a9d-b6d6-33d56cac6c5b">

### Specifics

I've checked this in Umbraco 13.0.3 using both Safari and Chrome browsers

### Steps to reproduce

1. Install a new Umbraco 13.0.3
2. Create an element type for a block (in my example it was a heading)
3. Configure the RTE to use the block
4. Create a cshtml rendering view for the front-end
5. Create an html/angular rendering view for the back-office
6. Create a page type that includes the RTE 
7. Edit the new content page and add a block
8. It will be rendering correctly in the back-office
9. Save or Save & Publish the page
10. The block content disappears and the block edit link no longer works

### Expected result / actual result

The blocks in the RTE should render and be editable as they were before the Save

---
_This item has been added to our backlog AB#42480_

**Comment by jannemartensgard** [comment] 2024-02-01 08:42
I can confirm that this is still an issue in a fresh install on 13.1.0 (testing on Chrome/Firefox on Windows). The block is editable when first loading the document in the backoffice, but turns uneditable when saving (clicking the edit icon produces a "Cannot read properties of undefined" error in the console). Moving the block within the editor turns it editable again.
Inspecting the block object I can see that the blockObject does not include content or data properties when the document has just been saved, whereas if I move the block the content and data properties are there (see included images).

https://github.com/umbraco/Umbraco-CMS/assets/78088981/388f2a0f-3417-4b7d-acac-c7e4e4283e05
![umbraco-issue](https://github.com/umbraco/Umbraco-CMS/assets/78088981/7f59a5df-89db-40bc-aa88-64ef7694ae77)
![umbraco-issue-2](https://github.com/umbraco/Umbraco-CMS/assets/78088981/52cae76c-893c-4cd3-9bf1-9d7b61a83eec)
![umbraco-issue-3](https://github.com/umbraco/Umbraco-CMS/assets/78088981/fd7ec769-5f1d-4d0d-8b9b-ff4d1ce0a274)

**Comment by Zeegaan** [comment] 2024-02-01 09:43
@jannemartensgard Could you give me some steps to follow from a clean install, so I can reproduce this? 🙈

**Comment by kulwinderk13** [comment] 2024-07-17 02:04
Hi @jannemartensgard Did you find a fix for this? Its still happening for me in umbraco 13.

**Comment by kulwinderk13** [comment] 2024-07-25 02:00
Hi there I have installed version 13.4.1 and have the same issue where blocks not being able to edit after hitting Save/Publish. I am attaching a few screenshots of the errors I can see in the browser console. 3)	I put a debug point on **editBlock function** and noticed that it throws error while accessing **blockObject.config.settingsElementTypeKey**. That is because the **blockObject.config** is **
![RTE](https://github.com/user-attachments/assets/9e1f7be0-c9a1-4ac8-8bba-6dd40c4a6b83)
![ConsoleError1](https://github.com/user-attachments/assets/8e35bf10-80d2-4d31-a505-6c9ddbf410e6)** as shown on the right.
![Debug](https://github.com/user-attachments/assets/c724c70e-b58e-458b-a3ac-97d0fa61e2c0)

**Comment by kulwinderk13** [comment] 2024-07-29 23:39
@kasparboelkjeldsen I can see that the issue has been closed now. I tried the Knowit.Umbraco.InstantBlockPreview but it does not seem to solve the above issue. I guess this package is for Block Grid and Block List in RTE and not the blocks we add through the toolbar.

**Comment by kasparboelkjeldsen** [comment] 2024-07-30 09:23
@kulwinderk13 they aren't really related. I'm just mentioning this issue over there as a warning that even with the feature I'm building there, there are currently issues with block elements in the RTE.

**Comment by leekelleher** [comment] 2024-08-13 08:28
Fixed in #16864 for v13.5.0.

**Closed by leekelleher** 2024-08-13 08:28 UTC
Labels: type/bug, area/frontend, affected/v13, release/13.5.0

**Comment by kulwinderk13** [comment] 2024-08-19 22:14
Hi @leekelleher Could you tell when 13.5.0 will be available for upgrade as I can only see until 13.4.1.

**Comment by leekelleher** [comment] 2024-08-20 10:17
@kulwinderk13 I don't know the exact date, it should be in a few weeks (mid-September).
