### ISSUE TITLE
Content version cleanup not working

### ISSUE THREAD

**Issue by jono-k** [umbraco/Umbraco-CMS#14432] opened 2023-06-22 10:24 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

I am trying to clear out the previous versions of some content nodes, and I've added the following to the appsettings.json, and then restarted the application, but it still holds onto the version history, even after several hours:

{
  "Umbraco": {
    "CMS": {
      "Content": {
        "ContentVersionCleanupPolicy": {
          "EnableCleanup": true,
          "KeepLatestVersionPerDayForDays": 0,
          "KeepAllVersionsNewerThanDays": 0
        }
      }
    }
  }
}

### Steps to reproduce

Using an Umbraco site with a content node published many times over multiple months. Setup the ContentVersionCleanupPolicy JSON in appsettings.json, restart the website in IIS, wait a few hours, and the 'History' section in the 'Info' tab still shows all of the rollback points.

**Comment by Zeegaan** [comment] 2023-06-22 12:11
@jono-k Heyo! 👋 
Just to make sure here, have you also configured this on your document type ? 😁 
This will override whatever you have in your appsettings 👍 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/63ef787b-8229-4e48-a104-318965d3b0ac)

**Comment by jono-k** [comment] 2023-06-22 20:37
@Zeegaan no I haven't configured this on the document type, here's the screenshot.
![download - 2023-06-23T063658 310](https://github.com/umbraco/Umbraco-CMS/assets/51493600/dd648022-5a78-4d5a-9cf9-408d952cd5bb)

**Comment by andr317c** [comment] 2023-06-27 07:46
Hey! 

I just took a look at your issue. I'm a bit unsure if you are trying to remove contentNode History or the contentNode Versions. I just tried reproducing this issue on v11.4.2. And the ContentVersionCleanup works as intended. It deletes all versions of the contentNode except the current. Remember that the history in your contentNodes is not the same as the data in your database. Please check that you can't roll back to prior versions. And that the prior versions are deleted in the database, the table: `umbracoContentVersionCleanupPolicy`

I will go ahead and close this issue since I can't reproduce it.

Please re-open the issue if you can roll back to a prior version after you have cleaned up.

**Closed by andr317c** 2023-06-27 07:46 UTC
Labels: state/needs-more-info, type/bug
