### ISSUE TITLE
V8 Grid "reorder" gets stuck after splitview

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/Umbraco-CMS#4886] opened 2019-03-06 10:27 UTC
1. Open split-vew.
2. Scroll down to a grid-view property.
3. Close split-view

**Comment by nul800sebastiaan** [comment] 2019-03-14 18:44
At the moment I can't reproduce in the latest code, this might have been fixed already, so I'm going to close this for now!

**Closed by nul800sebastiaan** 2019-03-14 18:44 UTC
