### ISSUE TITLE
IPublishedProperty PropertyTypeAlias naming

### ISSUE THREAD

**Issue by StefanoChiodino** [umbraco/Umbraco-CMS#3203] opened 2018-10-08 16:10 UTC
PropertyTypeAlias is populated with the property alias, not its type alias.

Reproduction
------------

### Bug summary

Inspect `IPublishedProperty`'s `Proprieties`, It's a collection of `IPublishedProperty` and the concrete type is `XmlPublishedProperty`. The `PropertyTypeAlias` is actually the alias of the property, not the property's type. This seems to be confirmed by the summary on the property ("Gets the alias of the property.")

E.g. if you have a text property called `Title` you'd expecty `propertyTypeAlias` to be `Umbraco.Textbox`, not `title`.

### Steps to reproduce

Hook into the published event. Load the respective `IPublishedContent` from the cache and inspect.

### Expected result

Should either be called `PropertyAlias` or return the alias of the property type.

**Comment by kjac** [comment] 2018-10-16 05:13
While @StefanoChiodino makes a good point, this change will break *a lot* of sites.

If this is to be changed I suggest renaming the property to `PropertyAlias` in V8 and leave it be 'till then. Mind you it will still be a breaking change for a lot of upgrades to V8.

**Comment by Shazwazza** [comment] 2018-10-16 05:43
There is some confusion here about naming conventions.

`propertyTypeAlias` is *not* the alias of a "Property Editor" a "Property Type Alias" is the alias of the "Property Type" so in the example above like `title`, that is correct.  The value of `Umbraco.Textbox` is the alias of the "Property Editor" assigned to the "Data Type" that the "Property Type" is using.

**Comment by kjac** [comment] 2018-10-16 06:51
Even better.

**Comment by nul800sebastiaan** [comment] 2018-10-17 07:29
👍 Closing this since it works as intended.

**Closed by nul800sebastiaan** 2018-10-17 07:29 UTC
