### ISSUE TITLE
Cancelling Publish event does not work on a node that has multiple cultures in V8

### ISSUE THREAD

**Issue by Xiaohao112** [umbraco/Umbraco-CMS#6852] opened 2019-10-25 12:50 UTC
Cancelling a publish event does not prevent the event from happening on a node with multiple cultures.

Reproduction
------------

Added the following to cancel a publish event:

```
        public void Initialize()
        {
            ContentService.Publishing += ContentService_Publishing;
        }

        private void ContentService_Publishing(IContentService sender, ContentPublishingEventArgs e)
        {
            e.CancelOperation(new EventMessage("Publish", "Cancelled", EventMessageType.Error));
        }
```

### Bug summary

When a publish event is added to cancel the publish the cancel message is shown in Umbraco when publishing but the event still takes place. The logs contains the cancel message: Document "Test" (id=1123) cannot be published: "publishing was cancelled".

### Specifics

Tested using Umbraco v8.1.1 in Chrome. Not checked in other browsers.
 The log contains the cancel message: Document "Test" (id=1123) cannot be published: "publishing was cancelled".

### Steps to reproduce

Add the code above to a Component and try to publish an unpublished node that has multiple cultures.

### Expected result

Publish is cancelled and the node is not published.

### Actual result
The cancel message is shown and the node is published.

**Comment by nul800sebastiaan** [comment] 2019-10-28 20:52
Unfortunately I can't reproduce this behavior in the latest version. So either this has been fixed in the mean time (but I don't remember seeing anything related to this) or something else is wrong. The exact code you posted definitely prevents me from publishing both multilingual and non-multilingual content.

**Closed by nul800sebastiaan** 2019-10-28 20:52 UTC
