### ISSUE TITLE
Umbraco Cloud content publish with schedule in HK failed to select the next hour value

### ISSUE THREAD

**Issue by kanalhui** [umbraco/Umbraco-CMS#16928] opened 2024-08-19 10:47 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

Im currently in Hong Kong and when I save the content, I can see the content history is showing the UTC +8 date & time, which is algin with my current location.
However, when I set the schedule publish date value to 1 hour later, the system show the error message and it show " The release date cannot be in the past"

### Steps to reproduce

1. Go to CMS and open the content.
2. Select the next minute or hour to publish content
3. Click "Schedule" button to save the setting
4. Error show on the screen

**Comment by NguyenThuyLan** [comment] 2024-08-20 07:37
Hi @kanalhui , thank for reporting this issue.

Unfortunately, I couldn't reproduce this issue as this below video:

https://github.com/user-attachments/assets/80ffb3ea-4dde-43cf-9352-9c6beed2305f

I'm currently in Vietnam and using East Australia region.
So I will close this issue.

Feel free to reopen it when you have more details 😊

**Closed by NguyenThuyLan** 2024-08-20 07:37 UTC
Labels: type/bug
