### ISSUE TITLE
Umbraco 9 - Can't add CORS because netcore configuration is hidden in UseUmbraco

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#10682] opened 2021-07-14 14:23 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

I am trying to add CORS to a specific endpoint in my project. For this I need to add UseCors in the configure method of the startup.cs. Sadly this is not possible because it needs to be between UseRouting and UseAuthorization which both are wrapped in a compiled UseUmbraco method.

https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0
```The call to UseCors must be placed after UseRouting, but before UseAuthorization. For more information, see Middleware order.```

### Steps to reproduce

Install umbraco 9 and try to add cors in startup

### Expected result / actual result

Is it not better to keep the NetCore middleware outside of any wrapped method so it's possible for developers to add their own middleware or middleware from others that might need to go "in between" standard NetCore middleware? If this is done for ease of use then I suggest moving the extensions class out of the assembly and place it in de root of the project so it can be edited without the need to ~~copy/paste~~ (nvm the copy/paste `UmbracoApplicationBuilder` is an internal class so that is not possible).

---
_This item has been added to our backlog [AB#12884](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12884)_

**Comment by deMD** [comment] 2021-07-14 14:31
Btw this also looks a bit sketch..

```csharp
public static IUmbracoApplicationBuilder UseUmbraco(this IApplicationBuilder app)
        {
            IOptions<UmbracoPipelineOptions> startupOptions = app.ApplicationServices.GetRequiredService<IOptions<UmbracoPipelineOptions>>();

           // Shouldn't the null check come before the RunPrePipeline call?
            app.RunPrePipeline(startupOptions.Value);
            if (app == null)
            {
                throw new ArgumentNullException(nameof(app));
            }
            ...
}
```

**Comment by Shazwazza** [comment] 2021-07-14 17:45
> // Shouldn't the null check come before the RunPrePipeline call?

yes :) would be fab if you could submit a PR for that

> Is it not better to keep the NetCore middleware outside of any wrapped method so it's possible for developers to add their own middleware or middleware from others that might need to go "in between" standard NetCore middleware? 

I don't know about 'better'. The issue is that middleware must go in the correct order. It is very easy to get this wrong and we don't want to require developers to have dozens of lines of Using code that they need to remember to boot Umbraco.

> The call to UseCors must be placed after UseRouting, but before UseAuthorization. 

That's unfortunate but also not surprising. IMO the main issue with middleware are the strict ordering that some of them require and it's not clear all of the time when one can exist after another, nor is it clear when a middleware is a terminating middleware (i.e. UseEndpoints). 

Here's some suggestions that we could do:

1. Just add UseCors() where it needs to go. Then you can use `services.Configure<CorsOptions>(x => ....)` to configure the Cors options you need. 
1. Add a callback parameter to the `UseUmbraco` method like `Action<Action<IApplicationBuilder>> requiredMiddlewares = null` so that an end user can customize the mandatory middlewares pipeline entirely while also being able to execute some before and after without having to register a `IUmbracoPipelineFilter`. Could look like this:
   ```cs
       app.UseUmbraco(requiredMiddlewares =>
        {
            // TODO: You could register some before

            // TODO: You could skip calling this entirely and
            // take total control over the required middlewares.
            requiredMiddlewares(app);

            // TODO: You could register some after
        })
        .WithMiddleware(u =>
        {
            u.WithBackOffice();
            u.WithWebsite();
        })
        .WithEndpoints(u =>
        {
            u.UseInstallerEndpoints();
            u.UseBackOfficeEndpoints();
            u.UseWebsiteEndpoints();
        });
   ```
1. Or, we extend the `IUmbracoMiddlewareBuilder` to be able to have a similar callback style as the above for an end user to replace the required middlewares within the `WithMiddleware` call. (might be nicer syntax).
1. Or we can have a callback (either in the `UseUmbraco` or `IUmbracoMiddlewareBuilder`) that can execute for every required middleware called so the end user doesn't have to copy/paste all required middlewares and ordering (which could be problematic) and instead can check what is currently being called and respond accordingly. For example that could look something like:
   ```cs
       app.UseUmbraco()
        .WithMiddleware(u =>
        {
            u.OnRequiredMiddlewareRegistered(m =>
            {
                // Called to execute the default registration
                // So you could register something before or
                // after it.
                m.Register();

                if (nameof(app.UseRouting) == m.MethodName)
                {
                    // Example, to register a custom one after
                    // UseRouting.
                    app.UseCors();
                } 
            });

            u.WithBackOffice();
            u.WithWebsite();
        })
        .WithEndpoints(u =>
        {
            u.UseInstallerEndpoints();
            u.UseBackOfficeEndpoints();
            u.UseWebsiteEndpoints();
        });
   ```
1. Or, Update the `IUmbracoPipelineFilter` to have a method like:  `Action<IApplicationBuilder> OnPipeline(IApplicationBuilder app, Action<IApplicationBuilder> next);` and then the `UseUmbraco` method would call this to register it's required middlewares. As an end user you could create a pipeline filter and set the OnPipeline method and you can either not call 'next(app)` and ensure all of the required middlewares are registered in the correct order (this would be a copy paste of the Umbraco code), or you could add middlewares before/after the defaults. This would be a chained call like middleware itself. The issue here is that I'm unsure a package developer should ever change this since it could totally break installs. IMO if this default middleware ordering needs to change or have others inserted, it should be up to the end user (So I prefer the previous options).
   ```cs
    app.RunPipeline(startupOptions.Value, app =>
            {
                app.UseUmbracoCore();
                ...
                app.UseRouting();
                ...
            });
   ```

Thoughts?

**Comment by vsilvar** [comment] 2021-07-15 09:08
I've ran into this as well, so here's my thoughts:
> 1. Just add UseCors() where it needs to go. 

This isn't really a viable solution imo, as there is a multitude of other middleware that might be needed e.g `ResponseCaching`.
And also, if the middleware isn't required by Umbraco I don't see why it should be registered preemptively.

> 2. Add a callback parameter to the UseUmbraco method like `Action<Action<IApplicationBuilder>> requiredMiddlewares = null`

Not sure if I get it, but what would be the added flexibility versus just receiving an `Action<IApplicationBuilder> = null` to override the required registrations? (the callback would simply be executed after RunPrePipeline)
Because the user can already add middleware before calling `app.UseUmbraco` and within `WithMiddleware` to register middleware before and after.

> 3. Or, we extend the IUmbracoMiddlewareBuilder to be able to have a similar callback style as the above

Do you have an example of how this would look? Because if it would be something like this it would be nice:
```c#
app.UseUmbraco() // Simply returns the IUmbracoApplicationBuilder
     .WithMiddleware(u =>
     {
         u.WithPrePipeline(); // This could still be done in UseUmbraco()
         u.WithRequiredMiddleware(); // This could then be replaced by the user
         u.WithPostPipeline(); // I don't see a way of not requiring this to be called here
         u.WithBackOffice();
         u.WithWebsite();
     })
```

> 4. Or we can have a callback [...] that can execute for every required middleware

I don't mind this being an option, but I think I would just end up using the options where you fully replace the RequiredMiddleware if available.
As those result in code where you can more easily see what middleware gets called when.

> 5. Or, Update the `IUmbracoPipelineFilter` to have a method like: `Action<IApplicationBuilder> OnPipeline(IApplicationBuilder app, Action<IApplicationBuilder> next);`

Seems more convoluted than 4 for the end user and I agree not something packages should be able to change.

**Comment by deMD** [comment] 2021-07-15 09:16
If option 3 looks anything like @vsilvar mentions then that would be my goto.

**Comment by Shazwazza** [comment] 2021-07-15 14:59
Thanks for the feedback :) 

So the consensus is really to just have a reasonable way to replace the entire required middleware calls.

I'll assign to the sprint and we'll go from there.

**Comment by Shazwazza** [comment] 2021-07-16 22:14
Hi all,

I've pushed a PR here with some details: https://github.com/umbraco/Umbraco-CMS/pull/10702

I ended up going a slightly different route because:

* We want to reduce the amount of startup code required for most end users, it should be the minimal amount. I looked at option 3 from @vsilvar but it would require that this code exists in all installs which is more than the minimum we'd like. 
* I could have made some along the lines of this option 3 without requiring the end user to call all of those methods but it would have required callbacks in callbacks which is a bit ugly.

I'm going to close this issue since the changes in the PR will allow you to customize the entire pipeline. If you have time it would be greatly appreciated to provide feedback on the PR.

**Closed by Shazwazza** 2021-07-16 22:14 UTC
Labels: state/sprint-candidate, type/bug

**Comment by Shazwazza** [comment] 2021-07-19 22:11
BTW, AddCors is already called internally by MVC :) see https://github.com/dotnet/aspnetcore/blob/a5faf6c59a0d3fb2d7ff6042661e148957e94ccf/src/Mvc/Mvc/src/MvcServiceCollectionExtensions.cs#L141

So when we call `AddControllersWithViews` it makes this call so you could just configure the CORS options and you should be in business.

**Comment by deMD** [comment] 2021-07-20 09:22
Looks like that is only the service and not the middleware, so not sure if adding our own options would just work by default :(

**Comment by Shazwazza** [comment] 2021-07-20 16:00
oh right yes I see that now. thanks!

**Comment by deMD** [comment] 2022-06-22 07:59
Sadly this became a problem again in U10 with the changes to how the `WebRootFileProvider` is registered:
```
webHostEnvironment.WebRootFileProvider.ConcatComposite(
                                new PrependBasePathFileProvider(mediaRequestPath, mediaFileProvider));
```
`ConcatComposite` lives in an internal extensions class so it isn't usable in the `WithCustomMiddleware` call.
