### ISSUE TITLE
Content node with umbracoAccess and without umbracoAccessRule breaks the whole website [12.3.0]

### ISSUE THREAD

**Issue by grigormargaritov** [umbraco/Umbraco-CMS#15024] opened 2023-10-23 12:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Content node with umbracoAccess and without umbracoAccessRule breaks the whole website. Version 12.3.0

### Bug summary

During loading of a page, on various places is called function PublicAccessService.GetEntryForContent()
deeper inside it is called PublicAccessRepository.PerformGetAll() which calls PublicAccessEntryFactory.BuildEntity()

If, for some reason one of the content nodes has in the database umbracoAccess record but is missing its umbracoAccessRule entries from the database then inside PublicAccessEntryFactory.BuildEntity() we will get exception on line 15: dto.Rules.Select(x => new PublicAccessRule(x.Id, x.AccessId)
because dto.Rules is null
Because of this exception the whole GetAll will fail.
The effect is that if one node has missing AccessRule then all the nodes can not be loaded and the whole website is completely inaccessible. Both the frontend and the umbraco part.
1) This is quite difficult to diagnose and localize whats the problem
2) Just because one node is broken the whole website should not be completely broken

This can easily be avoided if there is a check against null. Like that the website could still work and only the problematic page could be inaccessible or something  like that. Example:
if (dto.Rules != null)

or at least throw a meaningful exception including the nodeId so that it is easily diagnosed what exactly is the problem (throwing exception still means that the whole website will be broken just because of that problematic one node)

Also a very good idea would be to log a meaningful message including the nodeId.

### Steps to reproduce

I don't know how i managed to do that but in one moment i ended up with a node that had record in umbracoAccess table and did not have record in umbracoAccessRule.
And my whole website couldn't be accessed any more. I also couldn't even access the the content tree inside umbraco and so i couldn't edit/delete the access rules for that node.

To reproduce the problem i am talking about:
1. Create a content node, 
2. Set its access rules. 
3. In the database manually delete the record for this node inside the table umbracoAccessRule.
4. Try to reload the website
5. you'll get a weird error very difficult to diagnose and the whole website can not be loaded any more.
6.

### Expected result / actual result

 I would expect because of one broken node the website to still function and be accessible
I would expect a meaningful log including the problematic nodeId.

**Comment by kjac** [comment] 2023-11-01 07:48
Hi @grigormargaritov,

Thanks for reaching out, and sorry for the belated response.

I can reproduce this. How you ever managed to get your database into that state is beyond me, but fact is you did 😄 

We haven't seen any similar issue reports, which leads me to believe this is a one-off. I have a fix on hand, which will prevent the breakage while keeping the page protected. Obviously no-one will have access to the page, since the access rule has gone missing, but editors can then re-configure the public access from the back-office.

**Comment by grigormargaritov** [comment] 2023-11-01 15:16
See the last two comments in this post:
https://our.umbraco.com/forum/developers/api-questions/63238-Programmatically-add-Public-Access-to-document

Now i see this is a very similar to how i broke my database and ended up with a node without access rules.

Those two guys have had the exact same problem as i have reported here. Poor lads didn't understand what has happened and had to restore the whole database instead of adding manually the missing AccessRule in the database.

**Comment by elit0451** [comment] 2023-11-02 07:45
Fixed in #15081

**Closed by elit0451** 2023-11-02 07:45 UTC
Labels: type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12
