### ISSUE TITLE
Image not in memory cache after deploy

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11744] opened 2021-12-08 11:32 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

After upgrading Umbraco from v9.0.1 to v9.1.1 (or the patch update afterwards to v9.1.2) when deploying to Umbraco Cloud I get a 500 internal server error.

In log I noticed this:

![image](https://user-images.githubusercontent.com/2919859/145198013-1b2be5ee-1225-4b43-b663-9059ea5594a5.png)

at line 15 it requests a logo (svg) selected from Media Picker v3.

```
var logo = settings.Logo;
```

When rebuilding memory cache again everything is working again.

![image](https://user-images.githubusercontent.com/2919859/145201182-2b86ff08-7626-403e-8d8b-36f813565bb1.png)

I haven't had this issue with v9.0.0/9.0.1 .. not sure if it is an issue in Umbraco core or related specially to Umbraco Cloud.

### Steps to reproduce

Make some changes to various document types, re-generate models and deploy to Umbraco Cloud.
Not sure there's an easy way to reproduce, but ensure to have a property using Media Picker v3 referencing an image and requesting the property in the view.

I wonder if in could be related to history cleanup in v9.1 also this project hasn't history cleanup enabled yet.

**Comment by nul800sebastiaan** [comment] 2022-01-05 12:02
Hi @bjarnef - apologies for the late reply here. It's a bit difficult to tell what happened here since you did multiple different kinds of deploys it seems (code and content). I suspect it will be a content deploy issue but we'd need to be able to  reproduce it. Have you seen it again and does it occur when you deploy the same (type of) content?

A code deploy would just restart the site and clear the in-memory caches anyway, so it's probably not that.

**Comment by bjarnef** [comment] 2022-01-05 13:00
@nul800sebastiaan no I haven't seen it recently. It may be a random bug since it easy to reproduce.
I'll keep a eye with the issue and if it should occur again.

**Comment by nul800sebastiaan** [comment] 2022-01-05 14:49
Yeah it's a tough one! I'll close this for now but let us know here if you have more info! 👍

**Closed by nul800sebastiaan** 2022-01-05 14:49 UTC
Labels: state/needs-more-info, type/bug

**Comment by bjarnef** [comment] 2022-01-13 08:51
@nul800sebastiaan I just had this error again today on same project after deployment.

![image](https://user-images.githubusercontent.com/2919859/149297009-d9f7794a-e365-4f9d-9618-30dea0ee5f0a.png)

Reloading memory cache fixed the issue though, but I am wondering what is causing the error.

![image](https://user-images.githubusercontent.com/2919859/149297148-669bd7e6-8160-4974-8772-7e8ffcb599f9.png)

**Comment by nul800sebastiaan** [comment] 2022-01-13 09:13
Can you please describe in detail what you did before the problem occurred?

**Comment by bjarnef** [comment] 2022-01-13 10:05
We made a few adjustments to block properties, styling. layout in views and a bit a markup and on a testimonial document type we changes a property using Media Picker 3 to another Media Picker 3 datatype instance using local crops.

![image](https://user-images.githubusercontent.com/2919859/149307830-6a99813f-a260-4053-b852-1cd2da7bcefb.png)

However none of the changed are related to Master.cshtml and the image property (logo) on a Settings node, where the logo is request in master template.
