### ISSUE TITLE
Improved error handling for Examine indexing

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#15006] opened 2023-10-18 20:52 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7, 12.2

### Bug summary

Hello - something about our content is causing the ExamineIndexRebuilder to fail on populating the external index, meaning the backoffice search doesn't return anything, and so and we can't use the index for the basis of a site search as per https://docs.umbraco.com/umbraco-cms/reference/searching/examine/quick-start either.

This is occurring on Umbraco 10.7, but I also tried the running the website on Umbraco 12.2 and it had the same problem.

### Specifics

`{"@t":"2023-10-18T20:23:46.3101079Z","@mt":"Index populating failed for populator {Populator}","@l":"Error","@x":"Newtonsoft.Json.JsonSerializationException: Error converting value \"{guid}\" to type 'System.Guid'. Path '[0].key', line 1, position 16.\r\n ---> System.ArgumentException: Could not cast or convert from System.String to System.Guid.\r\n   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)\r\n   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)\r\n   --- End of inner exception stack trace ---\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Umbraco.Cms.Core.PropertyEditors.JsonPropertyIndexValueFactoryBase`1.GetIndexValues(IProperty property, String culture, String segment, Boolean published, IEnumerable`1 availableCultures)\r\n   at Umbraco.Cms.Infrastructure.Examine.BaseValueSetBuilder`1.AddPropertyValue(IProperty property, String culture, String segment, IDictionary`2 values, IEnumerable`1 availableCultures)\r\n   at Umbraco.Cms.Infrastructure.Examine.ContentValueSetBuilder.GetValueSetsEnumerable(IContent[] content, Dictionary`2 creatorIds, Dictionary`2 writerIds)+MoveNext()\r\n   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)\r\n   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)\r\n   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.IndexAllContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)\r\n   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)\r\n   at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes, TimeSpan delay, CancellationToken cancellationToken)","Populator":"Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator","SourceContext":"Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder","ProcessId":7484,"ProcessName":"iisexpress","ThreadId":8,"ApplicationId":"161095de6b5657dcc3731fe3e1593a929989e658","MachineName":"workpc","Log4NetLevel":"ERROR"}`

### Steps to reproduce

I've tried various debugging avenues to try and identify the culprit but not had much success. As Indexing runs as a background task, it makes it hard to "step into" umbraco code with sourcelink or similar https://docs.umbraco.com/umbraco-cms/reference/debugging

the stack trace indicates something in the ContentValueSetBuilder  process is expecting some property value to be JSON and failing. 

Would a reasonable expectation for something as crucial as indexing be that its wrapped in a try catch so that if it does fail the Umbraco logs could include information about the problematic content node (to accompany the exception stack trace)? If so, this would be a bug rather than a feature request. I don't have replication steps to report, but might if Umbraco had some handling along these lines.

open to thoughts and feedback

Thanks
Andrew

### Expected result / actual result

Expected: Examine indexing includes additional information about a particular IContent item that failed

**Comment by kjac** [comment] 2023-10-31 13:32
Hi @shearer3000,

Thank you for reaching out. Sorry for the belated response.

Judging from your log, some property has stored the value `"{guid}"` while it should have stored an actual GUID (possibly as a string value). It would be good to know if this is caused by a core property editor or an add-on / custom property editor.

All the same it would be fine to wrap [this line](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Infrastructure/Examine/BaseValueSetBuilder.cs#L37) in a try/catch and log the error instead of crashing the entire thread.

I'll put this up for grabs, in case anyone would like to have an attempt at fixing it. 

A fix entails injecting a logger into `BaseValueSetBuilder` via the concrete implementations. Changing constructor parameters is a breaking change, so please remember to make things backwards compatible by adding new constructors and obsoleting the old ones. There are plenty of examples on how to do it throughout the codebase - [here is one](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs#L23).

**Comment by shearer3000** [comment] 2023-10-31 19:44
hi @kjac thanks for following up. As it turned out, yes the "{guid}" value was ultimately our fault, but i still think a try catch around this process in Umbraco would make for a more resilient product and help with troubleshooting 😊 thanks for making it up for grabs

**Comment by nul800sebastiaan** [comment] 2023-11-30 18:18
We believe that https://github.com/umbraco/Umbraco-CMS/pull/14971 should definitely help with (if not fix) this issue. So I'll close this for now and unless there's evidence saying otherwise, we think this issue is fixed by that PR!

**Closed by nul800sebastiaan** 2023-11-30 18:18 UTC
Labels: community/up-for-grabs, type/bug, area/backend, affected/v10, affected/v11, affected/v12
