### ISSUE TITLE
Can not upload an SVG directly to a folder

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco-CMS#15774] opened 2024-02-26 16:17 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.2

### Bug summary

When uploading an SVG to a folder the error "Can not upload this file, the media type with alias "File" is not allowed here

![image](https://github.com/umbraco/Umbraco-CMS/assets/10153922/3bba858e-4d3e-4799-8e33-ff36650d973f)

 Here is the uSync structure for the folder being uploaded to:
 
 <?xml version="1.0" encoding="utf-8"?>
<MediaType Key="8ac26d37-0bf0-4d6c-aee3-8cd66fdbeeca" Alias="imageFolder" Level="1">
  <Info>
    <Name>Image Folder</Name>
    <Icon>icon-folder-close</Icon>
    <Thumbnail>folder.png</Thumbnail>
    <Description></Description>
    <AllowAtRoot>True</AllowAtRoot>
    <IsListView>False</IsListView>
    <Variations>Nothing</Variations>
    <IsElement>false</IsElement>
    <Compositions />
  </Info>
  <GenericProperties>
    <GenericProperty>
      <Key>46afaaa1-3dc1-44d6-b393-6a7e19991e9e</Key>
      <Name>Contents:</Name>
      <Alias>contents</Alias>
      <Definition>3a0156c4-3b8c-4803-bdc1-6871faa83fff</Definition>
      <Type>Umbraco.ListView</Type>
      <Mandatory>false</Mandatory>
      <Validation></Validation>
      <Description><![CDATA[]]></Description>
      <SortOrder>0</SortOrder>
      <Tab Alias="content">Content</Tab>
      <MandatoryMessage></MandatoryMessage>
      <ValidationRegExpMessage></ValidationRegExpMessage>
      <LabelOnTop>false</LabelOnTop>
    </GenericProperty>
  </GenericProperties>
  <Structure>
    <MediaType Key="cc07b313-0843-4aa8-bbda-871c8da728c8" SortOrder="0">Image</MediaType>
    <MediaType Key="8ac26d37-0bf0-4d6c-aee3-8cd66fdbeeca" SortOrder="1">imageFolder</MediaType>
  </Structure>
  <Tabs>
    <Tab>
      <Key>a33d176b-a2bc-4acb-a7f6-12d4c4a7742c</Key>
      <Caption>Content</Caption>
      <Alias>content</Alias>
      <Type>Group</Type>
      <SortOrder>0</SortOrder>
    </Tab>
  </Tabs>
</MediaType>

### Steps to reproduce

Try and upload an SVG to the folder by drag and droping into the folder as defined above.

### Expected result / actual result

Allowed to upload an image to this folder

**Comment by Zeegaan** [comment] 2024-03-08 10:39
Heyo 👋 
I am not able to reproduce this sadly, at least on a standard folder, this works just fine 😁 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/f2dfc469-c247-4a82-83ec-0e52b97f8b97)

Could you try this from a clean install without uSync? 🙈

**Comment by lauraneto** [comment] 2024-03-11 16:41
@Zeegaan I think this might be related to a PR I merged some time ago.
Apparently the fix never made it to v10.
This was the change: https://github.com/umbraco/Umbraco-CMS/pull/14892/commits/e64b5e2a5cbe5f428cdd17262c7ae41217dfb881

**Comment by Zeegaan** [comment] 2024-03-12 09:59
@lauraneto Maybe you are willing to give it a review? Since you're the one that originally merged the PR 🙈

**Comment by Zeegaan** [comment] 2024-04-24 11:45
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15868

**Closed by Zeegaan** 2024-04-24 11:45 UTC
Labels: type/bug, release/13.3.1
