### ISSUE TITLE
ImageCropper invalid image upload can cause app pool to crash

### ISSUE THREAD

**Issue by LouisHol4net** [umbraco/Umbraco-CMS#3026] opened 2018-09-24 14:16 UTC
When using the ImageCropper data type an invalid image upload can cause the app pool to crash

<h2>Specifics</h2>
I'm using Umbraco 7.11.1 

<h2>Steps to reproduce</h2>

1.  Log into the Umbraco Backoffice
2.  Create a document type whichs uses the ImageCropper data type
3. Upload any invalid image (for example a change any file to a .jpg extension) in the ImageCropper

<h2>Result</h2>

![image](https://user-images.githubusercontent.com/25605559/45957035-57d11800-c014-11e8-8046-64c3aa439aeb.png)

`System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at Umbraco.Web.PropertyEditors.ImageCropperPropertyValueEditor.ProcessFile(ContentPropertyData editorValue, ContentItemFile file, String currentPath, Guid cuid, Guid puid)
   at Umbraco.Web.PropertyEditors.ImageCropperPropertyValueEditor.ConvertEditorToDb(ContentPropertyData editorValue, Object currentValue)
   at Umbraco.Web.Editors.ContentControllerBase.MapPropertyValues[TPersisted](ContentBaseItemSave`1 contentItem)
   at Umbraco.Web.Editors.ContentController.MapPropertyValues(ContentItemSave contentItem)
   at Umbraco.Web.Editors.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)`

I've encountered muliple times that this can cause the app pool to crash probably due to the IIS rapid fail protection. Is there a way to validate a image before it is been send? 

I have tried the following events, but those aren't triggered when uploading a corrupt image 

ContentService.Published 
ContentService.Publishing
ContentService.Created
ContentService.Saving
ContentService.Saved

**Comment by kjac** [comment] 2018-10-04 20:15
One might argue that this isn't an Umbraco problem, and that uploading invalid images through the backoffice could be considered malicious use. On the other hand, crashing app pools really does sound like an Umbraco problem, malicious use or not.

I don't know... the core team should probably weigh in here.

I can't reproduce an actual app pool crash, but I can reproduce the error, and I have some code ready to fix it. Say when and I'll submit a PR. It's basically just a try/catch (having done a bit of research it seems to be the only way to solve the problem) and some additional logging. Nothing fancy 😄 

/cc @abjerner

**Comment by LouisHol4net** [comment] 2018-10-05 06:49
Hi @kjac 

Thanks for the reply, i'm interested in the PR, this has caused us some real trouble.

**Comment by kjac** [comment] 2018-10-06 08:08
@LouisHol4net done. I can't promise it'll be merged in though 😄

**Closed** 2018-10-09 09:12 UTC
