### ISSUE TITLE
Redirect URL Management is not working with ContentService.SaveAndPublish in C# code

### ISSUE THREAD

**Issue by petr-vojtech** [umbraco/Umbraco-CMS#12491] opened 2022-05-25 20:23 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

Hi, I'm changing the content of the page programmatically and saving it using ContentService.SaveAndPublish(newContent).

**The problem is that when I change the page name, automatic Redirect URL Management does not work.**

If I make a change using the CMS and the Save And Publish button, Redirect URL Management registers the change and creates a redirect.

**How do I force automatic redirect if I save directly from C # code?**

Thank you very much for help.

### Steps to reproduce

Try to change the page name programmatically. Redirect URL Management does not work.

### Expected result / actual result

Redirect URL Management will work.

**Comment by Zeegaan** [comment] 2022-12-29 10:04
Hey @petr-vojtech sorry for the late reply, and you've probably already got a solution now 🙈 
But I tested this in 10, and changing the "Name" & "PublishName" it worked just as intended 💪 
Sample code:
```
var content = _contentService.GetById(1059)!;
content.Name = "NewRoute";
content.PublishName = "NewRoute";
_contentService.SaveAndPublish(content);
```

I will close this for now as it works as intended, but please do not hesitate to re-open this if you run into it again!

**Closed by Zeegaan** 2022-12-29 10:04 UTC
Labels: type/bug
