### ISSUE TITLE
Nested content mandatory field is not empty, but getting validation errors

### ISSUE THREAD

**Issue by renaldas** [umbraco/Umbraco-CMS#8954] opened 2020-09-24 05:49 UTC
## Umbraco version

I am seeing this issue on Umbraco version: 8.7.0

Reproduction
------------

### Bug summary

After update from version 8.6.4 to 8.7.0, some nested element mandatory fields showing errors and prevents to save document. I noticed its only happens, when property names are general like 'name', 'image', it doesn't happen on other properties.

### Specifics

![umbraco_bug](https://user-images.githubusercontent.com/1375078/94105856-1a393c80-fe32-11ea-9491-05f60202e06b.jpg)

---
_This item has been added to our backlog [AB#9075](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9075)_

**Comment by nul800sebastiaan** [comment] 2020-09-24 06:45
Hi @renaldas, I can't reproduce the problem on my end. Did you happen to give the property alias of this `Name` field the alias `name`  somehow? If you try to do this from the doctype editor you would get an error:

![image](https://user-images.githubusercontent.com/304656/94109790-cdf5f880-fe41-11ea-99e0-ec74b7aa1ccb.png)

But maybe you've managed to do it some other way?

I can create `Image` with the alias `image` and I don't get validation errors when it's mandatory and has content.

**Comment by Lars-OJ** [comment] 2020-10-14 09:04
@nul800sebastiaan @renaldas I have the same problem in Umbraco v8.7 and 8.8.
I can reproduce this issue by creating a nested content item with a mandatory image. 
When I first save and publish the page without an image selected, I get an error that this field is mandatory (which is correct). But if I then select an image and try to save an publish the page again, nothing happens and the error still shows. no network-calls are done after the first Save and publish.
I also made a GIF which shows me reproducing it:  https://puu.sh/GCRsf/e58df33ab0.gif (note, the cursor in this gif is misplaced. based on the hover states you can see where I actually am)

**Comment by poornimanayar** [comment] 2020-10-22 18:20
I can reproduce this with a mandatory url picker :( in v8.8

**Comment by poornimanayar** [comment] 2020-10-26 09:50
@nul800sebastiaan I can reproduce this on many data types like url picker, media picker, MNTP to name a few. More over NC does not seem to respect the minimum items as well

**Comment by nul800sebastiaan** [comment] 2020-10-27 16:10
I can repro, if you get a validation error, they don't get cleared after correcting the error. Then after correcting it again, it does actually save. 

This is a regression and we'll have to fix that.

**Comment by poornimanayar** [comment] 2020-10-27 16:36
Happy to help test this when we have a fix.. 🙂

**Comment by rubbad** [comment] 2020-11-09 09:50
Not sure if this is related but in 8.8 and 8.9-rc I get a 404 PostSave error after fixing validation errors in Nested Content items with mandatory properties.

**Comment by nul800sebastiaan** [comment] 2020-11-09 09:52
@rubbad That is not related. Please make sure to upgrade to v8.9.0 final or better yet, version 8.9.1 which is coming out tomorrow.

**Comment by rubbad** [comment] 2020-11-09 10:33
@nul800sebastiaan Tried it in 8.9.1 and still get the 404 PostSave error.

**Comment by nul800sebastiaan** [comment] 2020-11-09 11:04
@rubbad Okay, sounds weird. Make sure to create a new issues with steps to reproduce the error. Ideally we would like to know if this is an issue on a clean install of 8.9.1 as well.

**Comment by Lars-OJ** [comment] 2021-01-13 14:06
@nul800sebastiaan Is there any progress regarding this issue or in what version of Umbraco this will be fixed? We have some clients that experience this issue a lot and do not have any alternatives for them.

**Comment by develoNiklas** [comment] 2021-02-04 13:28
I also have this issue on 2 umbraco sites. Updating has not solved the issue.

**Comment by emma-hq** [comment] 2021-02-09 11:19
Looking into this issue I am able to recreate with the latest release (8.11.1). 

![saveandpub](https://user-images.githubusercontent.com/78740801/107356237-742c5d00-6ac8-11eb-81ac-45180103eb25.gif)

**Steps to reproduce:**
1. On a nested content element, add a mandatory media picker property editor (or link picker)
2. Attempt to save and publish the page for validation to fail
3. Add content to the media picker property and try to save again.
This will fail

**Expected behaviour:**
You can see in the gif below that the text field behaves the way the user would expect.
![saveandpubtext](https://user-images.githubusercontent.com/78740801/107356274-7f7f8880-6ac8-11eb-89f5-253ad854d059.gif)

**Notes:**
If you refresh the page and try again, the validation passes. The naming of the property editor does not have any effect on the validation. The text fields are fine and the user is able to save again without encountering problems. This issue only appears to happen using the media picker or link picker.

**Comment by juanlondonoforero** [comment] 2021-02-10 08:28
Can we have an update on this please? this is happening on version 8.11.1 thanks

**Comment by emma-hq** [comment] 2021-02-10 08:48
Hi @juanlondonoforero - I took a look yesterday and added new steps for reproduction and testing. Any progress updates will be added here.

**Comment by amirmoradi** [comment] 2021-03-15 09:15
Any updates for this issue? 
Checked 8.12 release notes and it seems it's not included in the list?

**Comment by nul800sebastiaan** [comment] 2021-03-18 16:28
Note: we have the same problem with block list editor as detailed here: https://github.com/umbraco/Umbraco-CMS/issues/9997
So for any fixes, we need to make sure to also test those for block list editors.

**Comment by Shazwazza** [comment] 2021-03-19 08:05
The problem is:

With server side validation enabled on complex editors, property level validation needs to be able to clear based on user input for a property. The way this is all done is using angularjs ngModel since that is the only way that data and forms work with angularjs (properly). The problem with things like the media picker is that the media picker editor and form do not contain any ngModelController instances that track it's current value which means there is no reasonable way to know when that value changes. It is not feasible to put a $watch on nested content/block values instead of relying on ngModel because those values are enormous. ngModel allows us to define custom callbacks via validators to know when the data for an editor has changed and this is done reasonably efficiently.

I'll need to go through the editors to find out which ones do not expose an ngModelController within their form that allows monitoring for value changes. Media picker is one of them along with some others mentioned above. This may also mean that some custom property editors that exist outside of the core may need to be updated as well to have this requirement if server side validation in these complex editors is going to work for them. The requirement is very easy to fulfil (see PR)

I've started a PR for this here https://github.com/umbraco/Umbraco-CMS/pull/10013 

I'll continue with this on Monday.

**Comment by Shazwazza** [comment] 2021-03-24 23:17
I have tried several different avenues to resolve this but none will ever work without modifying some property editors to support this correctly. 

The underlying problem is that all input, value and validation logic in AngularJs is controlled by ngModel and we haven't made this a requirement for property editors. For all of this to work we need to know when a property editor value changes and the only way to know that is with ngModel. 

We cannot rely on AngularJs's FormController because those $dirty changes cascade upwards so it's impossible to know if a value changed for that form or a nested form (or nested/nested form, etc...). We cannot rely on manual $watch expressions for a model value because complex editors like nested content, block editors, etc... have a model that is ... well ... nested. Watching on that value would be horrible for performance and because it's nested we cannot tell which actual property is changed (same issue with monitoring FormController). 

If we were to rebuild property editors in AngularJs: They would be components that require `ngModel` (i.e. like this https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#custom-control-example).

There's all sorts of hacks in place in property editors due to the fact that many are not using ngModel. Anytime we are doing things like: `angularHelper.getCurrentForm($scope).$setDirty();` to set a property editor to be marked as $dirty when user interaction occurs. This should not be required if ngModel was used correctly. We also have newer/modern components that are not using ngModel when they should be such as the `umb-toggle` component. In AngularJs **anytime** there is a value being bound that changes with user input, the component should be backed with ngModel so that it can be properly validated, and monitored. 

But we can't go back in time so the only way to fix this is with more hacks 😢 

1. Anywhere this is used `angularHelper.getCurrentForm($scope).$setDirty();` in property editors means that this property editor doesn't use an ngModel to track it's current value and one will need to be added as a hidden input field. Because hidden input fields cannot be interacted with by the user, they need to be manually set to $dirty, but that's ok. This just means that the call to manually set the editor to dirty would be done more explicitly with this new field like: `vm.modelValueForm.modelValue.$setDirty()`
1. After doing 1) Need to go through every property editor to ensure that it uses an ngModel in some way to track it's model value

I'll post again when I've updated.

**Comment by Shazwazza** [comment] 2021-03-25 08:13
Ready for review https://github.com/umbraco/Umbraco-CMS/pull/10013

**Comment by nul800sebastiaan** [comment] 2021-05-12 09:26
Fixed for the upcoming 8.14 release in: https://github.com/umbraco/Umbraco-CMS/pull/10013

**Comment by nul800sebastiaan** [comment] 2021-05-25 14:34
@develoNiklas Please give us more details? What version? Did you try 8.14-RC, where do you see the problem? Screenshots? Etc. 😄 I've just identified a problem with the rich text editor, so maybe if you're on 8.14-RC then check out if this is the same problem as you're seeing: https://github.com/umbraco/Umbraco-CMS/issues/10249

**Comment by nul800sebastiaan** [comment] 2021-05-25 14:35
Oops updated link above to https://github.com/umbraco/Umbraco-CMS/issues/10246

**Comment by shearer3000** [comment] 2021-08-02 23:05
Still an issue in 8.14.1

**Comment by nul800sebastiaan** [comment] 2021-08-03 07:55
@shearer3000 Thanks, this is fixed in 8.15.0 https://github.com/umbraco/Umbraco-CMS/issues/10520

**Comment by emma-hq** [comment] 2021-08-03 12:59
Hey @shearer3000 

I'll take a look at the latest and re-open this one if we need to. Thanks for flagging!

Emma

**Comment by emma-hq** [comment] 2021-08-03 13:07
This is an issue again in 8.15.1 - steps to reproduce are above in my previous comment. I'll take a look at which release this last worked.

Emma

**Comment by nul800sebastiaan** [comment] 2021-08-05 12:10
I'm going to close this issue again since some of this was fixed in 8.14.0 - we're continuing updates on fixing this on issue https://github.com/umbraco/Umbraco-CMS/issues/10788

**Closed by nul800sebastiaan** 2021-08-05 12:10 UTC
Labels: release/8.14.0, status/regression, type/bug

**Comment by nul800sebastiaan** [comment] 2021-08-06 12:15
FYI: more fixing is coming: https://github.com/umbraco/Umbraco-CMS/issues/10788

We'd love it if people could test the builds:

8.14 - https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=69291&view=results
8.15 - https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=69293&view=results

The build artifacts will appear in about 45 minutes from now where you can click "3 published, 1 consumed":

![image](https://user-images.githubusercontent.com/304656/128508615-2e89cf78-4ed5-4147-8a1e-4db9cb6942c1.png)

After copying in the new files, make sure to update the version of your ClientDependency.config (just make it 1 higher or lower) and then you should be able to test it out.

Releases for 8.14/8.15 are coming on the 17th of Aug, the RC of 8.16 is coming on the 12th. So hopefully in the mean time this will work and help people.

**Comment by shearer3000** [comment] 2022-03-30 01:51
Hello - i get this error after upgrading a site from 8.6.1 to latest 8.18. Basically it seems, if nested content exists on a content node, and the nested content doctype has a property called "Name" then the property validation fails saying "Value cannot be null" despite there being values. This prevents an existing page with existing valid content from be republished after the upgrade.
