### ISSUE TITLE
ReplaceLineBreaks HTML extension method doesn't work as expected

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9689] opened 2021-01-20 13:10 UTC
Based on Umbraco v8.9.0 we have the following two HTML extension methods:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/HtmlHelperRenderExtensions.cs#L883-L908

- ReplaceLineBreaksForHtml (deprecated)
- ReplaceLineBreaks

With reCAPTCHA v3 it is possible to hide the default reCAPTCHA badge via CSS if having a text near the form:
https://developers.google.com/recaptcha/docs/faq

On a current project I have the following text in a textarea property on a settings node.

```
This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
    <a href="https://policies.google.com/terms">Terms of Service</a> apply.
```

With the deprecated method the links are rendered as HTML.

```
if (!string.IsNullOrWhiteSpace(settings?.GoogleRecaptchaMessage))
{
     <p>@Html.Raw(Html.ReplaceLineBreaksForHtml(settings.GoogleRecaptchaMessage))</p>
}
```

![image](https://user-images.githubusercontent.com/2919859/105178972-0627f200-5b29-11eb-918e-9a5f4b885d32.png)

but with the newer method `ReplaceLineBreaks` it just output the HTML as text.

```
if (!string.IsNullOrWhiteSpace(settings?.GoogleRecaptchaMessage))
{
     <p>@Html.Raw(Html.ReplaceLineBreaks(settings.GoogleRecaptchaMessage))</p>
}
```

![image](https://user-images.githubusercontent.com/2919859/105179200-4e471480-5b29-11eb-9fbe-8ab08aef95f6.png)

**Comment by bjarnef** [comment] 2021-01-20 13:18
I have changed the datatype to a Richtext editor with a simple configuration for now.

The property "GoogleRecaptchaMessage" returns `IHtmlString` like the newer `ReplaceLineBreaks`, but it seems there are issues with handling line breaks or maybe the anchors.

```
if (!string.IsNullOrWhiteSpace(settings?.GoogleRecaptchaMessage?.ToString()))
{
      <p>@Html.Raw(settings.GoogleRecaptchaMessage)</p>
}
```

![image](https://user-images.githubusercontent.com/2919859/105180097-69665400-5b2a-11eb-9e97-784e793e19e7.png)

**Comment by bjarnef** [comment] 2021-01-20 16:25
It seems there is a difference how the underlying utility method convert to text to HTML.

**ReplaceLineBreaksForHtml**
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/HtmlStringUtilities.cs#L28

**ReplaceLineBreaks**
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/HtmlStringUtilities.cs#L40-L45

**Comment by bjarnef** [comment] 2021-01-20 18:35
I think the issue is the new method not only replace line breaks, but also encode the text.
https://dotnetfiddle.net/l8h9qZ

```
string text = @"This site is protected by reCAPTCHA and the Google <a href=\""https://policies.google.com/privacy\"">Privacy Policy</a> and <a href=\""https://policies.google.com/terms\"">Terms of Service</a> apply.";
		
var val1 = HttpUtility.HtmlEncode(text)?
                .Replace("\r\n", "<br />")
                .Replace("\r", "<br />")
                .Replace("\n", "<br />");
		
var val2 = text.Replace("\r\n", @"<br />").Replace("\n", @"<br />").Replace("\r", @"<br />");
		
Console.WriteLine($"Value 1: {val1}");
Console.WriteLine($"Value 2: {val2}");
```

which output the following:

```
Value 1: This site is protected by reCAPTCHA and the Google &lt;a href=\&quot;https://policies.google.com/privacy\&quot;&gt;Privacy Policy&lt;/a&gt; and &lt;a href=\&quot;https://policies.google.com/terms\&quot;&gt;Terms of Service&lt;/a&gt; apply.
Value 2: This site is protected by reCAPTCHA and the Google <a href=\"https://policies.google.com/privacy\">Privacy Policy</a> and <a href=\"https://policies.google.com/terms\">Terms of Service</a> apply.
```

**Comment by nul800sebastiaan** [comment] 2021-01-21 08:48
PR https://github.com/umbraco/Umbraco-CMS/issues/6275 make sure the non-deprecated method sends you HtmlEncoded text as is required for `IHtmlString`. 

I don't know what your doing but this works for me: `@Html.Raw(Model.Value("test"))` (where `test` is the alias of my textarea).

**Comment by nul800sebastiaan** [comment] 2021-01-21 09:06
Ah I, forgot your removing linebreaks. Yep you will need to do some extra decoding and Raw'ing, or use the deprecated method.

I'll close this issue as this is expected behavior. Ideally, you want to have a controller to send you the correct model or a  propertyvalueconverter to do this work.

**Closed by nul800sebastiaan** 2021-01-21 09:06 UTC

**Comment by bjarnef** [comment] 2021-01-21 09:25
@nul800sebastiaan yes, I guess the new method works in same way if you only have text content and line breaks. But with any HTML content like in this example, it need the additional `HttpUtility.HtmlDecode(val)` and then `Html.Raw()` where the additional decode wasn't necessary with the deprecated method.

**Comment by nul800sebastiaan** [comment] 2021-01-21 09:27
I can only tell you that this is how "official" ASP.NET MVC works. We just never implemented it properly.
