### ISSUE TITLE
v8, v7: There is no possibility to copy with descendants from listview

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#7702] opened 2020-02-23 16:36 UTC
I was shocked, when I get knew that the regular feature to copy nodes with descendants not implemented in custom listview.

![Fiy4VXmcU9](https://user-images.githubusercontent.com/12345710/75115584-ee25c500-5670-11ea-9dc7-b24f241989f7.gif)

It is pretty odd to make it possible to copy a single node with it descendants but forbid it for nodes set.

Why it is so important?
------------------

1. Manually testing feature for developers and users would become much easier
2. Make a possibility to manipulate giant count of content out of the box without programming 
3. Especialy for multilingual Umbraco 7 solutions, when user would like to duplicate nodes for other languages

Thanks for attention

**Comment by nul800sebastiaan** [comment] 2020-02-24 06:36
Yes that is odd. I'll have to check if there's a specific reason for that but it seems like an oversight.

**Comment by kjac** [comment] 2020-02-25 13:28
@ReVoid thanks for reporting this! 

#6903 already fixed this for V8. The fix is slated for the upcoming 8.6-release 😄

**Comment by nul800sebastiaan** [comment] 2020-02-29 10:36
Great, I'll close this as a duplicate of #6903 - we are in bugfix-mode only for v7 so it won't be getting this update.

**Closed** 2020-02-29 10:36 UTC
