### ISSUE TITLE
HideTopLevelNodeFromPath setting throws exception - unable to save node 

### ISSUE THREAD

**Issue by Lachanophobia** [umbraco/Umbraco-CMS#10916] opened 2021-08-22 00:59 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

V9 RC2

### Bug summary

HideTopLevelNodeFromPath setting throws an exception when I am trying to save a node without URL in the Root.

### Specifics

I have a multi culture website with 2 nodes at Root. "Home" and "Settings". The settings node does not have a template so there is no URL assigned to it. The  "HideTopLevelNodeFromPath"  was never turned on.

### Steps to reproduce

-  2 Nodes at root. One without template (no URL) 
-  The node without URL and its properties should be allowed to vary culture. 
-  Try to change/add some values and publish the node
-  The following error will been thrown in a modal in Umbraco Back Office

If you turn off the "allow vary by culture" for the node without URL the error will disappear 

One more thing that would be worth to mention is that initially I had 2 cultures which I removed. I did some work on the docTypes and then I re-add them. I am not sure if that cause the issue as I didn't test it with my initial docTypes.

```
Received an error from the server

an error occurred
Failed to get node at /.

Exception Details
System.Exception, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Failed to get node at /.

at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.ApplyHideTopLevelNodeFromPath(IPublishedContent content, IList`1 segments, Boolean preview)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetRouteByIdInternal(Boolean preview, Int32 contentId, Nullable`1 hideTopLevelNode, String culture)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.<>c__DisplayClass13_0.<GetRouteById>b__0()
   at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0()
   at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Core.Cache.FastDictionaryAppCache.Get(String cacheKey, Func`1 getCacheItem)
   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetRouteById(Boolean preview, Int32 contentId, String culture)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetRouteById(Int32 contentId, String culture)
   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.StoreOldRoute(IContent entity, OldRoutesDictionary oldRoutes)
   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.StoreOldRoutes(IEnumerable`1 entities, IStatefulNotification notification)
   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.Handle(ContentPublishingNotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher.PublishCancelable(ICancelableNotification notification)
   at Umbraco.Cms.Core.Services.Implement.ContentService.StrategyCanPublish(IScope scope, IContent content, Boolean checkPath, IReadOnlyList`1 culturesPublishing, IReadOnlyCollection`1 culturesUnpublishing, EventMessages evtMsgs, IReadOnlyCollection`1 allLangs, IDictionary`2 notificationState)
   at Umbraco.Cms.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, EventMessages eventMessages, IReadOnlyCollection`1 allLangs, IDictionary`2 notificationState, Int32 userId, Boolean branchOne, Boolean branchRoot)
   at Umbraco.Cms.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String[] cultures, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method3961(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Expected result / actual result

To be able to save a node at Root that is varying by culture with no URL/template assigned to it.

**Comment by Lachanophobia** [comment] 2021-08-22 02:37
Found the source of issue! 
So the error occurs when you have a multi culture website with a node in the root without URL.

So in my case the settings node had no template, so I added one and give it some domains in "Cultures and Hostnames".
After that error is gone!!!

It doesn't seem like an actual error/bug if URLs are required for the cultures. Maybe needs to be handled better and return a more meaningful message to the editor.

**Comment by Lachanophobia** [comment] 2021-08-22 17:06
I am leaving this one here in case can help someone else to work around this issue.

To bypass the error I created a template with name "RedirectToHome" with this code.

```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
    Layout = null;
    Context.Response.Redirect(
        Umbraco
            .ContentAtRoot()
            .FirstOrDefault(x =>
                string.Equals(x.ContentType.Alias, HomePage.ModelTypeAlias, StringComparison.OrdinalIgnoreCase)).Url()
        );
}
```

**Comment by nul800sebastiaan** [comment] 2021-08-30 10:59
@Lachanophobia I've tried all kinds of things, adding languages, removing languages, new nodes in the root, old nodes in the root. `HideTopLevelNodeFromPath` to `true` and to `false` (I couldn't figure out what you had your setting set to), but unfortunately I can't reproduce your error at all. 

I just had a look at the code and none of the related code seems to have been changed for at least 2 years (in other words, it's the same as in v8). So I feel like you have some kind of edge case going on, possibly related to the language you removed and added, maybe? I am not sure.

At this point I don't think we can do much to help here, but I would encourage you to try to debug against Umbraco's source to see where the error might come from. It seems to be something is missing but I have no clue what. 😬 

I'll close this one for now but we'd be happy to have another look if you have more info or can reproduce on a clean install. Alternatively if you are allowed to share the site + db that you're working on now privately with us then let me know as well, then we can actually attach a debugger and see what's up!

**Closed by nul800sebastiaan** 2021-08-30 10:59 UTC
Labels: project/v9, type/bug

**Comment by Lachanophobia** [comment] 2021-08-30 17:45
HI @nul800sebastiaan, thanks for looking into this. I manage to reproduce it in a clean Umbraco installation. I have never try to debug against Umbraco's source, I ll give it a shot (I am not sure if I ll be successful :D ) and I ll come back to you!

**Comment by JFSeibert** [comment] 2021-09-21 12:45
I had similar issues in local project.
When I've set up different domains and amended applicationUrl it works for me
`"applicationUrl": "https://localhost:44305;https://localhost:44306;https://localhost:44307;http://localhost:42890",`

hope that helps tracking it
