### ISSUE TITLE
v8 : UmbracoApplication.OnApplicationError does not get triggered when a boot failed error happens

### ISSUE THREAD

**Issue by AlexandreLocas** [umbraco/Umbraco-CMS#5505] opened 2019-05-21 18:07 UTC
When a "Boot failed: Umbraco cannot run." exception happens, UmbracoApplication.OnApplicationError does not get called. We need a way to deal gracefully with this type of exception so that end-users do not see the yellow screen of death.

**Comment by nul800sebastiaan** [comment] 2019-05-31 11:52
Hi @AlexandreLocas - I think we'd be much more interested in why this error actually happens, do you have examples and possible causes?
This error happens before Umbraco can even wire up the OnApplicationError event and I think it would be quite impossible to "half" boot Umbraco just to wire it up. 

Have you looked into actually hooking into the .NET error handling for this, which might kick in before Umbraco's boot error?

**Comment by AlexandreLocas** [comment] 2019-05-31 12:18
Hi @nul800sebastiaan, the error is already fixed (it was the file Umbraco.Web.PublishedModels.dll that was left in the bin folder after changing ModelsMode to LiveAppData). 

The problem i'm trying to resolve is **to catch these types of boot errors** (if they ever come back) that do not seem to get handled by standard .NET exception handling (like OnApplicationError and such). Under no circomstance we want to show the client the yellow screen of death.

Thank you

**Comment by nul800sebastiaan** [comment] 2019-06-03 10:54
@AlexandreLocas Yep, I understand you perfectly. I think you'd need to hook into the .NET handlers for that, the umbraco one you mentioned (`UmbracoApplication.OnApplicationError`) gets wired up too late. Have you tried hooking into the standard .NET one instead?

**Comment by AlexandreLocas** [comment] 2019-06-03 12:30
@nul800sebastiaan Yes I did (HttpApplication Application_Error) and it also does not get triggered, maybe it has something to do with lightinject ? Thank you

**Comment by nul800sebastiaan** [comment] 2019-06-03 14:44
I've had a bit of a chat about this and the conclusion is: make sure to configure custom error and you can set up a custom error page in your web.config.

The problem is that it is impossible to have an error handler in place before even asp.net can hook that up. This is not an Umbraco problem but a general asp.net problem. If the site can't boot for some reason, it can also not give you an error handling hook. 

There's nothing more we can do in Umbraco to improve this experience I'm afraid. I'll close this issue accordingly. :)

**Closed by nul800sebastiaan** 2019-06-03 14:44 UTC
Labels: state/hq-discussion-cms
