### ISSUE TITLE
Breaking Change or Bug: Vary by Culture BlockList-property demands Vary By Culture Properties in Block Element

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#14149] opened 2023-04-24 12:50 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

There is a breaking change in this that is not documented. If you have BlockList on a DocumentType that is set to Vary by Culture, then ALL the properties of the Block Element in that BlockList ALSO need to be Vary by Culture. Otherwise ther SetValue exception of Property will trigger:

```
        if (!PropertyType.SupportsVariation(culture, segment))
        {
            throw new NotSupportedException(
                $"Variation \"{culture ?? "<null>"},{segment ?? "<null>"}\" is not supported by the property type.");
        }
```

To me, this seems like an unintended scenario. Just because the BlockList itself is vary by culture, doesn't mean the Element Type has to be. This would only make sense if Block Elements themselves would actually be vary-able - but they aren't (yet). I'll make an issue.

Actual effect: This will prevent Examine from re-indexing properly.

### Steps to reproduce

1. Create Doctype with Blocklist
2. Set Blocklist to Vary by Culture
3. Add a Block Element, leave as non-varyable.
4. Create page and setup Block with at least 1 entry.
5. Save and Publish, exception will be logged.
6. Re-index Examine, exception will be logged.

End-result is missing items in index, as index will also stop rebuilding. The exception is not properly caught in the try-catch of `GetIndexValues`, reinforcing the idea this is not intended to happen.

### Expected result / actual result

This scenario does not require the Block Element to be Vary by Culture nor its properties.

**Comment by nikolajlauridsen** [comment] 2023-04-25 13:44
Duplicate of #14096 thanks for reporting though, more info is always appreciated :) 

I'll go ahead and close this issue for now though since it's a duplicate 😄

**Closed by nikolajlauridsen** 2023-04-25 13:44 UTC
Labels: type/bug
