### ISSUE TITLE
Variant Children of non-variant node are not listed

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#5886] opened 2019-07-14 14:33 UTC
Testing and PR notes: https://github.com/umbraco/Umbraco-CMS/issues/5886#issuecomment-513100527

---

Release 8.1.0 includes some breaking changes regarding `IPublishedContent.Children()` - gone - and its replacement properties `.Children` and `.ChildrenForAllCultures` (see [this discussion](https://github.com/umbraco/Umbraco-CMS/issues/5170#issuecomment-499824646)).
But it looks like the implementation does not work as expected:

If you have a **non-variant parent** with a mix of culture-variant and non-variant children:
* Only the non-variant children are listed in the `Children` property. 
* The culture-variant children are not listed, even if they have a published version in the current language. 
* The related methods `.FirstChild()` , `.FirstChild<T>()`, etc. also fail to retrieve any culture-variant children.

The only way to access the culture-variant children is the `ChildrenForAllCultures` property. I don't think this is by design, is it?

---
_This item has been added to our backlog [AB#1721](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1721)_

**Comment by kjac** [comment] 2019-07-15 05:45
Whoa. That sounds like an oversight ☹️

**Comment by zpqrtbnk** [comment] 2019-07-15 06:27
Not by design. Bug.

**Comment by Shazwazza** [comment] 2019-07-15 07:11
That is an interesting one and potentially depends on where these invariant children exist.

The Children property should return children that are contextual to the current request. In this case the Children that are variant which exist underneath an invariant document should correspond to the culture in the `IVariationContextAccessor`.

I'd have to look to see what is going on but would have thought this was already the case. 

@JoseMarcenaro To confirm with your setup though, do you have cultures assigned to the tree where you have non-variant nodes?

**Comment by JoseMarcenaro** [comment] 2019-07-15 10:29
@Shazwazza - I'm not sure I understand your question, but I can confirm this behavior happens down the tree, below the node where the "Culture and Hostnames" are set, i.e.
```
Website
  |- Home     // variant, hostname bindings are set here 
  |    |- Panels    // invariant
  |    |    |- Child1  // variant
```
When rendering 'Home', children of the 'Panels' folder are not retrieved by the .Children property.

**Comment by JoseMarcenaro** [comment] 2019-07-15 14:04
@Shazwazza  - in case you don't experience the same behavior, let me know and I'll post a "Steps to reproduce" sequence starting from a blank Umbraco 8.1.0 site.

**Comment by JoseMarcenaro** [comment] 2019-07-15 21:58
### Steps to reproduce

Install a brand new Umbraco 8.1.0 website

Create the following *document types*:
* InvariantSection (doctype without template) - add no properties, keep all defaults
* VariantSection (doctype without template) - add no properties, enable "Allow varying by culture"
* HomePage (doctype) - add no properties, enable "Allow as root" and "Allow varying by culture", add InvariantSection and VariantSection as allowed children

In the content tree:
* Create the root HomePage, publish with the default language (en-US)
* Create an InvariantSection child under the home (Section1) and publish 
* Create a VariantSection child under the home (Section2) and publish 

Edit the Homepage template:
```
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
}
<ul>
    @foreach (var child in Model.Children)
    {
        <li>@child.Name</li>
    }
</ul>
```

Add a "Culture and Hostnames..." entry to the home page, using the single language available (en-US)

Run the site: this is what you'll get:
* Section1
* Section2

So far, so good.
Now change the HomePage document type as **invariant** and republish the content item.

Run the site, and this is what you get:
* Section1

Whoa! Note that this is not related to the fact that the invariant node is the home page (where the binding is set). If you keep the home page as culture-variant and add a "Sections" (invariant) folder between the home page and the two sections, you'll get the same behavior.

**Comment by ronaldbarendse** [comment] 2019-07-16 09:34
I still think there should be a clear seperation between content and structure, as only content can be variant by culture, as I commented earlier: https://github.com/umbraco/Umbraco-CMS/issues/5170#issuecomment-499278717. But as we now have `ChildrenForAllCultures` on `IPublishedContent`, this will just be the way it is...

Regarding this issue: it looks like the culture can be `null`, an empty string or `*` (when getting/filtering the children). The `Children` property invokes `this.Children()` (using `culture = null`), which is then changed to an empty string and thus filters all children using `IsInvariantOrHasCulture()`:

https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Core/PublishedContentExtensions.cs#L102-L127

This checks whether the content type has a `ContentVariation.Culture` flag set, so this probably isn't reset when changing from variant to invariant.

**Comment by JoseMarcenaro** [comment] 2019-07-16 10:36
@ronaldbarendse  
No. Using `Model.Children(Model.GetCultureFromDomains())` only lists Section1 (the invariant one).   Only `Model.ChildrenForAllCultures` returns both sections.

Anyway, that's not the point. We need the full set of properties and methods to work correctly:
* `Children`
* `Children<T>`
* `FirstChild()`
* `FirstChild<T>`

In a multilingual site, it make senses to make some "structural" nodes as invariant, and that should not break the entire set of navigational properties / methods.

**Comment by ronaldbarendse** [comment] 2019-07-16 13:50
In your final example, `HomePage` is invariant and has it's culture set to `en-US` via the 'Culture and Hostnames' (so `Model.GetCultureFromDomains()` should return this culture, as this is saved as a wildcard domain behind the scenes).

So `Model.Children(Model.GetCultureFromDomains())` should return all invariant children and variants with `en-US` published/available. Is this the case for `Section2`?

**Comment by JoseMarcenaro** [comment] 2019-07-16 14:42
@ronaldbarendse  no, it is not the case.  That is what should happen, but it does not. 
`Section2` is ignored.

**Comment by ashansen** [comment] 2019-07-17 06:35
I ran into this issue as well, and if I've debugged/understand correctly it does look like the issue is with 
https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Core/PublishedContentExtensions.cs#L102-L127
and is relatively simple.

If the content is invariant and culture is not *, culture will always be set to empty string and context culture will not be used as culture is no longer null.
This means if using a specific culture, it'll be overwritten by empty string because the content is invariant.
So it seems using the culture overload will do nothing if the content you're getting children for is invariant.
If using "*" as culture it looks like it's basically the same as just calling ChildrenForAllCultures.

Children will be attempted filtered for culture empty string in IsInvariantOrHasCulture but if they have a cultures other than empty string they'll not be returned. 

I would think a possible fix could be to change the IsInvariantOrHasCulture or create one specifically for children which takes context culture into consideration if the child content is not invariant, but the parent is?

(Or has I misunderstood the code?)

**Comment by ronaldbarendse** [comment] 2019-07-17 07:02
@ashansen It's probably more complicated, as invariant content still has a culture: either set via 'Culture and Hostnames', inherited from parent nodes or as fallback the default culture...

So if the invariant content has a culture of 'en-US', I would expect all children to be invariant or the same culture (and not just all children).

**Comment by ashansen** [comment] 2019-07-17 07:16
@ronaldbarendse There might be some culture fallback issues and I've not dug into how Umbraco handles those (fallback) culture aspects (yet), however I would doubt (hope) that it does not mean they're saving culture specific content on other cultures or invent a specific 'invariant culture or similar but simply load content with the fall back cultures.

And that's why I think that when looking up children, you should not rely on the parents culture if the parent is invariant (and thus have no culture), but the context culture and if the child is invariant.
Something similar to:
```
 return (content.ContentType.VariesByCulture() && content.Cultures.ContainsKey(culture)) 
                || !content.ContentType.VariesByCulture();

```
Now I know that's not a universal fix and just snipped into the codebase and all that because of complexities - however, the extension method for Children and the IsInvariantOrHasCulture does look to be relatively isolated.

**Comment by Shazwazza** [comment] 2019-07-19 03:53
Just working through all this but have found another related bug which is in the `ContentCache.FollowRoute` method which calls into `content.Children(culture)` which fails when you have a  tree like:

variant -> non-variant -> variant 

The last variant node will have a message saying that it is published but the item is not routable, this is because the FollowRoute fails due to the Children not returning the correct thing so this bug isn't just limited to the front-end.

There's a bunch of unit tests under `NuCacheChildrenTests` which all pass but means that it's not testing these scenarios, i will add to these tests and then can get a fix in place.

**Comment by Shazwazza** [comment] 2019-07-19 05:51
Here's a PR https://github.com/umbraco/Umbraco-CMS/pull/5946

The problem was the odd logic in PublishedContentExtensions.Children where it did this:

```cs
            // invariant has invariant value (whatever the requested culture)
            if (!content.ContentType.VariesByCulture() && culture != "*")
                culture = "";
```

I'm actually unsure why this logic exists and it may actually be a copy/paste problem. This similar logic exists in the Name and UrlSegment methods but in those methods it makes sense since they are returning single values. Perhaps @zpqrtbnk has some thoughts on that.

You can see in the PR that I've removed this logic which fixes these issues. I've added unit tests to prove this (these were failing before adding the fix). Please also have a look at the code comments/notes I've added.

## For testing:

* Follow these steps https://github.com/umbraco/Umbraco-CMS/issues/5886#issuecomment-511585905
* Create a tree structure in the back office with variant -> invariant -> variant and navigate to the deepest variant and ensure that it's URLs are generated and it can be routed to

**Comment by ashansen** [comment] 2019-07-19 06:06
It looks good to me and is similar to an extension method I made in my current project to circumvent the issues while waiting for an official fix :)

**Comment by zpqrtbnk** [comment] 2019-07-19 06:27
Thinking that @Shazwazza is right, and the code he's removing is indeed a copy/paste error - it should not be there.

As for "empty string", it means "invariant culture" and has indeed a different meaning than null, which means "use the default/current culture".

**Comment by warrenbuckley** [comment] 2019-07-22 13:55
Closed due to this PR merged in for 8.1.1
https://github.com/umbraco/Umbraco-CMS/pull/5946

**Closed by warrenbuckley** 2019-07-22 13:55 UTC
Labels: release/8.1.1, state/estimation, type/bug

**Comment by brahim19** [comment] 2020-09-24 14:59
![1600941880203-1736243787](https://user-images.githubusercontent.com/38589738/94162748-521e9f00-fe87-11ea-8287-278b15c419a7.jpg)
please,who can solve this problem

**Comment by JoseMarcenaro** [comment] 2020-09-24 15:04
Hi brahim19 - this does not look to be related to the reported issue - which was fixed, by the way.
If the Children() method was returning an empty collection, that would not be a null reference exception.
Are you sure Model is not null ?

**Comment by brahim19** [comment] 2020-09-24 15:09
Yes,I'm sure

**Comment by brahim19** [comment] 2020-09-24 15:10
Yes,I'm sure

**Comment by JoseMarcenaro** [comment] 2020-09-24 15:19
Can you please put a breakpoint at the foreach and test (in the Inmediate or Watch windows) the values of
```
Model
Model.Children()
```

**Comment by brahim19** [comment] 2020-09-24 15:27
![Error](https://user-images.githubusercontent.com/38589738/94166054-2c939480-fe8b-11ea-86c7-96895068a526.png)
first, I thank you for the answer.I did it.but I got this error

**Comment by JoseMarcenaro** [comment] 2020-09-24 15:48
Brahim, do not modify the razor view (by the way, the trailing ";" is missing).
Can you attach a debugger and stop the execution in the @foreach statement?

**Comment by brahim19** [comment] 2020-09-24 16:02
if I stop @foreach statement, it will run quite normally.

**Comment by JoseMarcenaro** [comment] 2020-09-24 16:33
@brahim19 - please open a thread in https://our.umbraco.com/forum/ to get help on this issue with your code, as it is not an Umbraco issue. Thx
