### ISSUE TITLE
Disable user from user page

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13552] opened 2022-12-09 08:48 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Sometimes when inviting users fails (either on Umbraco Cloud or non-Cloud) either the mail isn't delivered or something else, a workaround is from users overview to select the user and disable the use and enable the user afterwards.

Furthermore the password could be changed, so the client can get access and change the password again.

Howeever it seems odd it isn't possible to disable/enable a user from the user page as well.

When a user is invited there is user the "Delete User" and "Resend Invitation" buttons.

For active user the disable button is shown though, why isn't it available to invited users as well, when it is in overview via bulk actions at top?

### Steps to reproduce

Invite some users. Notice is it possible to disable these from overview via bulk actions at top, but not on the use page itself.

---
_This item has been added to our backlog [AB#24998](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24998)_

**Comment by nikolajlauridsen** [comment] 2022-12-09 09:30
Hey Bjarne, I just had a look at it, and I can indeed see that you can disable the users from the listview overview.

However I must admit that disagree with the solution, I think the problem here isn't that you can't disable the user from the user page, the problem is that you can disable the user at all. 

When a user is invited it's already disabled in the database, and is in a "Invited" state, however, if you go and cycle the enabled state, it's no longer in an "Invited" state, but instead in an "Inactive" state. This means that when the user then clicks the link they won't get prompted to select a password, so you now have a user that doesn't know their password.


So I think the solution to this, is really to ensure that a user that's in an "Invited" state will never be enabled since that causes the mentioned issues, and of course, the button should be removed.

**Comment by bjarnef** [comment] 2022-12-09 09:41
Hi @nikolajlauridsen 

Outside Umbraco Cloud without Umbraco ID when user invitation fails (and previous when it wasn't possible to resend invitation) this was useful to disable the user and enable the user, generate a password and change that on the user.

On Umbraco Cloud is also possible to change password locally, but in noticed on Development environment with Umbraco ID is isn't possible to change password on the enabled user and the email is locked.

However the issues we have with Umbraco ID on a few Umbraco Cloud projects are that when inviting users (I suspect it happens for users not already on Umbraco ID) when accepting the invitation email we get this message. A few colleagues get the same error and the customer as well.

![image](https://user-images.githubusercontent.com/2919859/206672218-d453b10f-e544-454c-b1c4-a867206a14df.png)

However in Umbraco Cloud portal we can see the invitations being active and should first expire on December 14, 2022.
So not sure what is expired.

**Comment by nikolajlauridsen** [comment] 2022-12-09 09:47
I'm not sure about cloud, that sounds more like an issue with the user invite flow for the cloud tracker. 

But from a CMS perspective as I mentioned you shouldn't be able to enable/disable an invited user, since as I mentioned that causes all sorts of trouble, but instead use the resend invitation button as you mentioned, I realize that in the past this wasn't there, but then I'd suggest instead deleting the invited user and recreating it, or if you just want to assign a password manually then using the "Create user" function instead, to create the user and then go to their profile to change the password.

**Comment by bjarnef** [comment] 2022-12-09 09:56
@nikolajlauridsen yeah, I have submitted a few issues related this and Umbraco ID on Umbraco Cloud.

https://github.com/umbraco/Umbraco.Cloud.Issues/issues/624
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/625

**Comment by bjarnef** [comment] 2022-12-09 09:59
Btw. the disable/enable user was useful in "old" days when it wasn't possible to resend invitation and since the user couldn't be deleted and re-create.

Furthermore on Umbraco Cloud the "Create user" button is not available - only on local environment, so the user has to be invited through backoffice or portal.

**Comment by nikolajlauridsen** [comment] 2022-12-21 09:07
This has been fixed in #13600 so I'll go ahead and close this

**Closed by nikolajlauridsen** 2022-12-21 09:07 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, area/frontend, area/backend, affected/v10, affected/v11
