### ISSUE TITLE
Content picker search is broken 

### ISSUE THREAD

**Issue by StudioBravo** [umbraco/Umbraco-CMS#17343] opened 2024-10-23 06:43 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

The content picker search functionality seems to be searching across all content across the site rather than the restricted content for the picker. 

### Steps to reproduce

- Setup a document type that contains a field with a content picker
- Restrict the content picker only to select certain document types and also specify a starting node
- Create a page with the new document type and navigate to the content picker to add content
- The content picker selection flyout shows all available content (it correctly displays the restricted set of content to chose from)

![image](https://github.com/user-attachments/assets/c8eb38a5-a162-4fc2-a4e3-86da3d7df686)

- Start typing on the search box and it seems to find all the content cross the site that matches the text. 

![image](https://github.com/user-attachments/assets/18185653-b2ff-468b-8598-88c314e42151)

### Expected result / actual result

The search functionality should be looking through the restricted documents rather than across the whole site. 

---
_This item has been added to our backlog AB#45280_

**Comment by Zeegaan** [comment] 2024-10-24 07:14
I can reproduce this, looks like when we are calling the search endpoint, we are no longer accounting for the context of the content picker 😁

**Comment by nikolajlauridsen** [comment] 2024-11-04 13:15
I just looked at this, and this turns out to be a frontend issue. 

On 13 there was a "start from" query parameter on the tree search, which would limit the search to a specific start node. This query parameter is still there for `/item/document/search`  just called `parentId` now which the frontend should use but doesn't. 

Similarly, on V13 the frontend did a lookup on the datatype and used the filter property to filter out the document types that aren't allowed according to the configuration, this doesn't happen either 😄

**Comment by madsrasmussen** [comment] 2024-11-19 09:20
This is now fixed and will be available in 15.1

**Closed by madsrasmussen** 2024-11-19 09:20 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v14, affected/v15

**Comment by McGloud74** [comment] 2025-01-09 13:20
Will this fix also become available with a  in v14?
