### ISSUE TITLE
Unable to get just created Media from published content

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco-CMS#13670] opened 2023-01-12 19:29 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Hi,

It's not possible to get just created Media from published content cache in any notification handler, no matter if you use IUmbracoContextFactory or IPublishedContentQuery.

It's worth to mention that when you do the same in any Controller then you will get published Media.

Probably it's not working in v9-v11, but I need to ensure.

It's not working in v8.18.5.

Best!

### Steps to reproduce

Create a notification handler as bellow and you will notice that publishedMedia is null in both cases.

```
public class MyCustomNotification : INotificationHandler<ContentMovingNotification>
{
    private readonly IMediaService _mediaService;

    private readonly IUmbracoContextFactory _umbracoContextFactory;

    private readonly IPublishedContentQuery _publishedContentQuery;

    public MyCustomNotification(
        IMediaService mediaService, 
        IUmbracoContextFactory umbracoContextFactory, 
        IPublishedContentQuery publishedContentQuery)
    {
        _mediaService = mediaService;
        _umbracoContextFactory = umbracoContextFactory;
        _publishedContentQuery = publishedContentQuery;
    }

    public void Handle(ContentMovingNotification notification)
    {
        var justCreatedMedia = _mediaService.CreateMediaWithIdentity("New folder name", existingParentId, Constants.Conventions.MediaTypes.Folder, -1);

        using (var ctx = _umbracoContextFactory.EnsureUmbracoContext())
        {
            var publishedMedia = _publishedContentQuery.Media(justCreatedMedia.Id);

            publishedMedia = ctx.UmbracoContext.Media.GetById(justCreatedMedia.Id);
        }
    }
}
```

**Comment by kjac** [comment] 2023-01-13 05:41
Hi there @wtct,

Thank you for reaching out 😄 

This is entirely by design. The `*ing*` notifications (e.g. `ContentMovingNotification`) execute within a scope, which might get cancelled by other notification handlers. Thus changes aren't committed until all handlers have executed.

Fortunately the `*ing*` notifications have a handy state, which allows you to pass data to the corresponding `*ed*` notification handler - in this case `ContentMovedNotification`. Here's a code sample:

```csharp
public class MyCustomNotification: INotificationHandler<ContentMovingNotification>, INotificationHandler<ContentMovedNotification>
{
    private readonly IMediaService _mediaService;
    private readonly IPublishedContentQuery _publishedContentQuery;

    public MyCustomNotification(
        IMediaService mediaService,
        IPublishedContentQuery publishedContentQuery)
    {
        _mediaService = mediaService;
        _publishedContentQuery = publishedContentQuery;
    }

    public void Handle(ContentMovingNotification notification)
    {
        IMedia justCreatedMedia = _mediaService.CreateMediaWithIdentity(
            $"My new folder {Guid.NewGuid().ToString("D").Split('-').First()}",
            Constants.System.Root,
            Constants.Conventions.MediaTypes.Folder,
            Constants.Security.SuperUserId);

        notification.State["MyNewFolderId"] = justCreatedMedia.Id;
    }

    public void Handle(ContentMovedNotification notification)
    {
        if (notification.State.TryGetValue("MyNewFolderId", out var value) == false ||
            int.TryParse(value?.ToString(), out var id) == false)
        {
            return;
        }

        IPublishedContent? publishedMedia = _publishedContentQuery.Media(id);
        // do stuff with the media item
    }
}

public class MyCustomNotificationComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<ContentMovingNotification, MyCustomNotification>();
        builder.AddNotificationHandler<ContentMovedNotification, MyCustomNotification>();
    }
}
```

**Closed by kjac** 2023-01-13 05:41 UTC
Labels: type/bug

**Comment by wtct** [comment] 2023-01-13 10:19
Hi @kjac,

Do you want to tell me that all "ing" notifications are transaction scoped and all changes I've made through built-in Umbraco Services will be reverted in case of canceling? If so, it's one of the best information related to Umbraco I have ever heard :)

I haven't seen that information in any Umbraco documentation nor blog posts etc.

What about "ing" events in v8? Are they also transaction scoped?
