### ISSUE TITLE
V7 - Multinode Treepicker bug allow items of type

### ISSUE THREAD

**Issue by EmbraceSBS-Umbraco** [umbraco/Umbraco-CMS#5421] opened 2019-05-08 08:36 UTC
With Umbraco 7.1.4.0 The Umbraco.MultiNodeTreePicker2 doesn't working correct with the setting 'allow items of type'. I can select other items than allowed. Can this with high prio solved? Because it is now possible to select other items than allowed.

Reproduction

See video for reproduce steps, with standard Umbraco 7.14.0 with the example database of
Umbraco. 
[Multinodetreepicker-wrong-nodes.zip](https://github.com/umbraco/Umbraco-CMS/files/3156359/Multinodetreepicker-wrong-nodes.zip)

**Comment by kjac** [comment] 2019-05-08 19:44
Pretty sure this is a duplicate of #5137 which has a PR in #5199 ?

**Comment by EmbraceSBS-Umbraco** [comment] 2019-05-09 06:24
> 
> 
> @EmbraceSBS-Umbraco Quick follow up: specifying a node under "Node type" - I used the xpath option ($site) - got it working for me!

Yes, that is a workaround, but it is time consuming to change all our installations, so we prefer a fix in UmbracoCMS.

**Comment by Shazwazza** [comment] 2019-06-19 03:35
Can confirm this is a duplicate, fixed in #5137

**Closed by Shazwazza** 2019-06-19 03:35 UTC
