### ISSUE TITLE
Creating members breaks database cache

### ISSUE THREAD

**Issue by DavePearcey** [umbraco/Umbraco-CMS#8329] opened 2020-06-23 13:07 UTC
When creating new members using a custom method for member registration, the Database cache status is "Database cache is NOT ok (rebuild?)".

### Umbraco version

I am seeing this issue on Umbraco version: 8.6.0 - 8.6.3

Reproduction
------------
### Bug summary

Regardless of wither in my live or dev environment, whenever a new member gets created, it breaks the database cache. With over a thousand members and 5,100 content items and growing, it takes a while to rebuild it every time it breaks.
I've seen others mention on [our.umbraco](https://our.umbraco.com/forum/using-umbraco-and-getting-started/99780-umbraco-82-creating-a-member-causes-database-cache-is-not-ok-rebuild-how-to-rebuild-database-from-code) about older versions and just building in a check to rebuild. But that's an insufficient solution, as with as many content nodes I have, it locks up the entire website for several minutes at a time.
While in a state of "Not ok" the website has a severe impact on speed. Which is very noticible when there's ~50 requests/second.

### Specifics   
     
    IMember member = Services.MemberService.CreateMemberWithIdentity(model.Username, model.Email, model.Username, "Member");

    member.SetValue("gender", model.Gender);
    member.SetValue("referrer", model.Referrer);
    // many more custom fields being populated by default, not included to keep short.

    Services.MemberService.SavePassword(member, model.Password);
    Services.MemberService.AssignRole(member.Id, "Member");
    Services.MemberService.Save(member);

### Expected result

I would expect the database cache remain stable when a new member is created.

### Actual result

Database cache breaks and requires rebuilding.

**Comment by mcl-sz** [comment] 2020-06-26 09:16
We have the same issue and it indeed causing performance issues.

**Comment by Chris-N1** [comment] 2020-06-30 14:53
It appears both this and #8279 are caused by the issue fixed in the PR here:

https://github.com/umbraco/Umbraco-CMS/pull/7021

I have tested locally and that seems to resolve the issue.

**Comment by DavePearcey** [comment] 2020-06-30 14:57
> 
> 
> It appears both this and #8279 are caused by the issue fixed in the PR here:
> 
> #7021
> 
> I have tested locally and that seems to resolve the issue.

That interesting and thanks for the super sleuthing! hopefully it actually rectifies the performance issues!

**Comment by nul800sebastiaan** [comment] 2020-07-02 12:47
I never realized this PR was related, great find @Chris-N1! 👍 I'll close this one as fixed in #7021 

We're preparing an 8.6.4 patch release [with a few other fixes](https://github.com/umbraco/Umbraco-CMS/issues?q=label%3Arelease%2F8.6.4) as well. We'd love it if you could test this one using the build from the build server if you could please and give some feedback on if it eliminates the issue and helps with your performance issue: https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=43686&view=results (download from the "3 published" artifacts).

**Closed by nul800sebastiaan** 2020-07-02 12:47 UTC
