### ISSUE TITLE
ViewComponent "Cannot return the IPublishedContent because the UmbracoHelper was not constructed with an IPublishedContent"

### ISSUE THREAD

**Issue by Phil-B** [umbraco/Umbraco-CMS#16713] opened 2024-06-28 09:46 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.0

### Bug summary

The following error is thrown when `Umbraco.AssignedContentItem` is referenced in a ViewComponent

> InvalidOperationException: Cannot return the IPublishedContent because the UmbracoHelper was not constructed with an IPublishedContent.

### Steps to reproduce

1. Create a ViewComponent with the following in the View

```razor
@inject Umbraco.Cms.Web.Common.UmbracoHelper Umbraco
@{
    var currentItem = Umbraco.AssignedContentItem;
}
```

2. Invoke the ViewComponent from a View:
```razor
@(await Component.InvokeAsync("MyViewComponent"))`
```

The error only occurs when the calling View doesn't reference UmbracoHelper. Just adding the following is enough to fix the issue:

```razor
@{
  var foo = Umbraco;
}
```

**Comment by nikolajlauridsen** [comment] 2024-07-01 13:34
Hi @Phil-B I just had a look at this. 

This is by design I'm afraid, since the `UmbracoHelper` is designed to be used within a view.  The `AssignedContentItem` is resolved when the `get` method for it is called. This is necessary because the `AssignedContentItem` is contextual to the view itself, that is it tries to use the model in the `ViewData` instead of solely relying on the `PublishedRequest`.

Because of this I'll go ahead and close this as won't fix, I'd recommend instead passing the `UmbracoHelper` to your view component as a parameter, to ensure that `AssignedContentItem` is always the expected content item

**Closed by nikolajlauridsen** 2024-07-01 13:34 UTC
Labels: type/bug

**Comment by nikolajlauridsen** [comment] 2024-07-02 06:43
Absolutely, never hesitate to make an issue 😄 I'm sorry I might have been a bit fast, it was the end of the day 😉 but thanks for making the issue 😄
