### ISSUE TITLE
Unhandled controller exception in ImagesController when filename contains special character

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco-CMS#14056] opened 2023-04-04 14:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.7

### Bug summary

Since the update from Umbraco 8.18.4 to 8.18.7, we occasionally receive the following error:
```

2023-04-04 11:27:48.906 +02:00 [Error] Unhandled controller exception occurred for request '"https://<hosname>/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=%2Fmedia%2F...../image.jpg&rnd=0.2167963272731348"'
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.UriBuilder..ctor(String uri)
   at Umbraco.Web.Editors.ImagesController.IsAllowed(String imagePath) in D:\a\1\s\src\Umbraco.Web\Editors\ImagesController.cs:line 106
   at Umbraco.Web.Editors.ImagesController.GetResized(String imagePath, Int32 width) in D:\a\1\s\src\Umbraco.Web\Editors\ImagesController.cs:line 64
```

### Specifics

It seems that this problem occurs when the file name contains a special character such as ë or ï.
When the file is renamed without these characters and the api is called, the error doesn't occure.

### Steps to reproduce

- Upload a file to Media with an ë or ï in the filename.
- Call the url `https://<hosname>/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=/media/<folder>/filënäme.jpg&rnd=0.2167963272731348`

---
_This item has been added to our backlog [AB#28439](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/28439)_

**Comment by lucavice** [comment] 2023-04-06 09:33
I can confirm exactly the same issue reported by @mcl-sz , which has been introduced for us with upgrading from Umbraco 8.18.4 to 8.18.7.

The actual impact is that images containing a special character cannot be previewed in Media Pickers.
See here the same image with `Birthday` vs `Bìrthday`
![image](https://user-images.githubusercontent.com/14258744/230336066-12d84e0b-e9db-4d13-b04d-2bd45c0a5986.png)

This is actually problematic for us, since some languages use these special characters constantly and the media gallery functionality is impacted significantly.

**Comment by mcl-sz** [comment] 2023-04-11 13:36
@UmbracoHQ can you confirm that this is a side effect of Umbraco 8.18.7? Like @lucavice , this is quite an annoying problem for us as many file names have a special character in them.

**Comment by kjac** [comment] 2023-04-13 07:17
Quick update: We'll be looking into this issue in the coming weeks and release a patch to fix it for V8.

**Comment by inetzo** [comment] 2023-04-21 10:54
Hi @kjac , is there any idea when a solution to this problem can be expected? Several customers have been complaining about this issue since upgrading to 8.18.7.

**Comment by kjac** [comment] 2023-04-25 04:58
Hi @inetzo,

We're looking at it in this sprint; the patch will likely be released next week 😄

**Comment by Danish-Refugee-Council** [comment] 2023-04-28 11:51
+1

**Comment by Zeegaan** [comment] 2023-05-03 05:59
Heyo! 👋 This has now been fixed in https://github.com/umbraco/Umbraco-CMS/pull/14192
New sprint starts for us on monday, so it is our goal to release a patch including this fix, during that sprint 🚀

**Closed** 2023-05-03 05:59 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/backend, affected/v8
