### ISSUE TITLE
Umbraco Cloud deploy error "Cannot save content with an empty name." for "Content Templates" with "Allow vary by culture" enabled.

### ISSUE THREAD

**Issue by mcsagittarius** [umbraco/Umbraco-CMS#9895] opened 2021-02-24 19:10 UTC
## Description

"Content Templates" / "document-blueprint" based on document types with "Allow vary by culture" enabled breaks Umbraco Cloud transfer/restore functionality. Trying to do a transfer of a content template based on a document type that allow language variants will give the "Cannot save content with an empty name" error.

As this is a pretty basic feature (setting up default content elements for certain page-types) and it completely breaks "core" functionality (transfer/restore), this is fairly critical and a bit of a deal-breaker for our customers.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

Reproduction
------------

1. Create Umbraco Cloud project with at least two environments (for content transfer)
2. Create an extra language (so there is at least two cultures/languages).
3. Create 2 document types. One with "Allow vary by culture" set to true (let's call it "AllowVary"), and another where it's set to false (let's call that "NoVary"). Both have "Allow as root" checked. Neither have any groups or fields of any kind. Neither have any template changes (default empty Razor view). Deploy these changes to staging/live as needed.
4. Create a content template for both document types.
5. Right click the content template for "NoVary" and select "Queue for transfer...", go to the queue and transfer to the next environment. Notice that it complets just fine.
6. Duplicate step 5 for the "AllowVary" content template and notice that it gives the error "Cannot save content with an empty name."
7. Optional step. Try to save the content template for "AllowVary" in each language manually. Notice that it makes no difference.

### Bug summary

This seems to be a bug relating to how Umbraco handles language variants. 
When doing regular content and creating a new language variant you have to manually re-type the name of the item. Otherwise, you can't save it (this is annoying, but a separate matter).

It seems like "something" is being created for variant content templates that needs its name set. This "something" is hidden as doing step 7 (i.e. saving a variant of the content template for each language manually) does nothing to resolve this.

There is very little that can actually be seen or edited on a content template, so there's nothing further to try in the UI.

### Specifics
Closely related to the Umbraco 8 feature of having multiple language variants of the same item as well as the "Content Templates" feature.

I found a mention of this on the forum here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/100587-umbraco-cloud-deploy-error-document-blueprint and I've added a reply to that thread as well.

I have been in contact with "André" from Umbraco support today and he has confirmed the issue as well.

I have checked in both Firefox and Chrome (though it's clearly not browser related).

All my testing has been done on Umbraco Cloud projects (tried two separate ones).

### Expected result

Content template being transferred correctly. Also, that "Full restore" works (it's permanently broken while a content template for an allow-vary document type exists).

### Actual result

![image](https://user-images.githubusercontent.com/12056340/109051117-7999c200-76da-11eb-9838-8aaae5c13d74.png)

`964b337a - Executing, 10% - Get remote session
964b337a - Executing, 20% - Create manifest on source
964b337a - Executing, 25% - Review manifest on target
964b337a - Executing, 28% - Negotiate files transfer.
964b337a - Executing, 30% - Create package on source
964b337a - Executing, 30% - Complete local session
964b337a - Executing, 35% - Process package on target
964b337a - Executing, 80% - Exception!
964b337a - Executing, 80% - Abort remote session
964b337a - Failed, 80% - Total time 00:00:01.817.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.InvalidOperationException: Cannot save content with an empty name.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #3 failed for artifact umb://document-blueprint/6af08cc7a4ea4e418c9821cdd71af39d.
 On: <umb://document-blueprint/6af08cc7a4ea4e418c9821cdd71af39d>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-- UDIS --------------------------------------------------------
<umb://document-blueprint/6af08cc7a4ea4e418c9821cdd71af39d>
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__16.MoveNext()

REMOTE:
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #3 failed for artifact umb://document-blueprint/6af08cc7a4ea4e418c9821cdd71af39d.

   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass13_0.<<BeginProcessPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--> System.InvalidOperationException: Cannot save content with an empty name.

   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.EnsureInvariantNameExists(IContent content)
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.SanitizeNames(IContent content, Boolean publishing)
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistNewItem(IContent entity)
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Create(TEntity entity, Action`1 persistNew)
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.Save(TEntity entity)
   at Umbraco.Core.Services.Implement.ContentService.SaveBlueprint(IContent content, Int32 userId)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentBlueprintConnector.Process3(ArtifactDeployState`2 dart, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentBlueprintConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
`

---
_This item has been added to our backlog [AB#10774](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10774)_

**Comment by HamDerAndrew** [comment] 2021-02-24 19:20
I can confirm that this issue appears after having tested it also.

I hope this gets some 💙  since one of the nice things about v.8 is Multilingual site functionality 😃

**Comment by nul800sebastiaan** [comment] 2021-07-20 12:34
Hey there @mcsagittarius and @HamDerAndrew - I am sorry for the delay on this one, it got a bit lost on the CMS tracker, it should probably have been on the Deploy tracker.

I've just tried out this scenario and I had to add a property on the doctype (as you can see in the video) to even be able to make content templates, which makes sense (there's no "template" if you don't pre-fill some properties). But other than that this seems to work as expected in Umbraco 8.14.1 and with Deploy 4.1.2.

https://user-images.githubusercontent.com/304656/126324769-500fe42c-64e5-42da-9257-bde6a58a1e20.mp4

Please review the video above and if I missed some kind of step then I'm happy to have a look again. For now however I will close this as it seems like it works as expected. 👍

**Closed by nul800sebastiaan** 2021-07-20 12:34 UTC
Labels: state/sprint-candidate, type/bug
