### ISSUE TITLE
error_description:This server only accepts HTTPS requests.

### ISSUE THREAD

**Issue by AbsoDao** [umbraco/Umbraco-CMS#16424] opened 2024-05-27 12:55 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0--rc.preview.116.g365e3b3

### Bug summary

When I deploy umbraco with nginx reverse proxy, I get the following error when I log in to the backend after the setup is complete.

### Specifics

url:https://xxxx.xxx/umbraco/

error:invalid_request
error_description:This server only accepts HTTPS requests.
error_uri:https://documentation.openiddict.com/errors/ID2083

### Steps to reproduce

rror:invalid_request
error_description:This server only accepts HTTPS requests.
error_uri:https://documentation.openiddict.com/errors/ID2083

**Comment by BElluu** [comment] 2024-05-27 17:01
It looks like wrong configuration in NGINX. Show me your configuration from nginx, how did you set up this application in sites-available.

**Comment by AbsoDao** [comment] 2024-05-28 00:01
I'm using Umbraco with nginx deployment on Fedora. I use nginx reverse proxy Umbraco to run the service.

 My Umbraco services are as follows:

[Unit]
Description=App running on Linux
[Service]
WorkingDirectory=/mydir/publish/
ExecStart=/mydir/publish/ubr.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=dotnet-Umbraco
User=root
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
Environment=ASPNETCORE_URLS=http://localhost:5001
[Install]
WantedBy=multi-user.target


My nginx configuration location are as follows:

location / {
            proxy_pass         http://localhost:5001;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
        }

I searched online for a similar issue, but I don't know if it's useful.
https://github.com/openiddict/openiddict-core/issues/864

**Comment by bergmania** [comment] 2024-06-27 08:50
Should be fixed by a combination of https://github.com/umbraco/Umbraco-CMS/pull/16660 and https://github.com/umbraco/Umbraco-CMS/pull/16614.

I'll close the issue, as it fells like a duplicate of the others

**Closed by bergmania** 2024-06-27 08:50 UTC
Labels: type/bug
