### ISSUE TITLE
8.1 Cannot delete Hostnames after setting them

### ISSUE THREAD

**Issue by Sibren** [umbraco/Umbraco-CMS#5873] opened 2019-07-12 14:39 UTC
I tried the variants-thing, created an extra language, set some variants.
Then set the hostnames on a node. Then tried to remove (one of) them. The overlay disappears, but nothing happens.
No error comes up.

### Bug summary
As above

### Specifics
Tried on various nodes. Using Umbraco 8.1.0

### Steps to reproduce
Create second language (Dutch), set some Hostnames (Node -> RMB ->Culture and Hostnames).
Create two (http://localhost:590080/ and http://localhost:590080/nl). Save.
Try to delete.

### Expected result
Removing the hostnames

### Actual result
Nothing happens.

**Comment by kjac** [comment] 2019-07-12 19:47
Duplicate of #5815 ?

**Comment by Shazwazza** [comment] 2019-07-15 02:10
yep, closing this one

**Closed by Shazwazza** 2019-07-15 02:10 UTC
