### ISSUE TITLE
15.1-rc: Can't move groups nor properties to other tabs in content type editor

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#17677] opened 2024-11-29 09:28 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1-rc

### Bug summary

Following up from #17676 I thought a workaround could be to simply move the properties from the generic tab to a real tab. But that doesn't seem to be possible. At least not the way it used to in the old backoffice.

### Specifics

This happens in the content type editor, when I try to reorder tabs and properties. Previously you could drag groups and properties onto a new tab, but that doesn't seem to be possible anymore.

### Steps to reproduce

![thorium_72H5gQjtWj](https://github.com/user-attachments/assets/7d5f85e9-4fe8-4886-abfc-4c359e30b18b)

### Expected result / actual result

I expected to be able to move groups and properties to other tabs, or create new tabs from groups.

**Comment by Zeegaan** [comment] 2024-11-29 09:38
This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/17462, I will go ahead and close this 😁

**Closed** 2024-11-29 09:44 UTC
Labels: type/bug
