### ISSUE TITLE
v8: Template is created on blur

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4287] opened 2019-01-28 19:36 UTC
In v8 when creating a new template, entering a name and then either click outside input (or hit tab key). Now it has created the template, without hitting save button (or using the shortcut `ctrl+s`).

![2019-01-28_20-35-27](https://user-images.githubusercontent.com/2919859/51861502-b8fb5600-233c-11e9-8b90-dcbc44583641.gif)

**Comment by kjac** [comment] 2019-01-29 10:34
Got this 👍 PR incoming.

**Comment by kjac** [comment] 2019-01-29 10:53
This is apparently by design -  see #2742

The use case here is creating a new template with an alias that corresponds to an existing view on disk. Since the scaffold is loaded before the name is entered, the editor won't see the existing view contents. However, upon creation the existing view is *not* overwritten (also by design), so any changes to the scaffold are discarded and replaced by the existing view.

Makes sense?

**Comment by bjarnef** [comment] 2019-01-29 10:59
@kjac okay, but why doesn't it only try to create the template, when one actually hit save button (or use the shortcut `ctrl+s`)?

At the moment it is a bit confusing it created templates, when you loose focus on the input or just be mistake click outside the input.

**Comment by kjac** [comment] 2019-01-29 11:23
@bjarnef I agree it's confusing when you don't know the reason behind it. I tried to explain the reason in my previous comment... but here's another go at it.

Imagine you've got an existing view on disk called `test.cshtml`, but no corresponding template in the UI. Now if you create the template `Test` in the UI, you don't want Umbraco to overwrite the existing view. Thus the general rule is "no matter what, don't overwrite existing views when creating a new template".

Now when you create the `Test` template you probably have no idea about this rule. And Umbraco loads the default scaffold for your new template, because at creation time you have yet to name it. To avoid you spending time on writing a bunch of Razor only to have it discarded because of the existing `test.cshtml`, Umbraco explicitly saves your template when you've entered its name (on blur/enter). The save operation subsequently reloads the view inside the editor, and you'll see the contents of `test.cshtml` in the editor.

It looks like this:

![create-template-on-blur](https://user-images.githubusercontent.com/7405322/51905027-7b401100-23c0-11e9-9e89-4564335b9dde.gif)

**Comment by bjarnef** [comment] 2019-01-29 11:32
@kjac yes, I get the issue with overwriting existing templates, but I still feel it is a bit inconsistent with the rest of the UI. And e.g. if creating a document type with a template, e.g. "Blog Post" the tree node is named "Blog Post" and the partial view becomes "BlogPost.csthml".

What happens if you have a physical file on disk names `test.cshtml` with some code and then create a document type with template named "Test". Is the `test.cshhtml` template then overwritten?

**Comment by kjac** [comment] 2019-01-29 11:34
I hope not 😄

**Comment by clausjensen** [comment] 2019-01-29 13:57
@bjarnef I agree it is inconsistent with the rest of the UI. We tried out various solutions and tried to come up with the various use case scenarios/workflows that this would affect.
We couldn't really come up with a better solution right now.

We figured the most important part of this was that we do not by accident end up overwriting - or put the user in a situation where they can end up overwriting existing templates on disk.
Since templates aren't fetched directly from disk (template entities live in the database and then have a corresponding file on disk), we don't really have a good way of detecting and handling this (like maybe even showing them in the UI...)

So .. we know the solution we chose isn't really optimal. But it did solve the most important part of it: not accidentally overwriting things.
I'm however very open to other ways the problem can be solved. I'll close this issue for now but it can be reopened (or a new one) if you come up with something that is better 😃

**Closed by clausjensen** 2019-01-29 13:57 UTC
