### ISSUE TITLE
ContentService.Publishing event is missing data from content

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#11013] opened 2021-09-02 03:15 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

The ContentService.Publishing event no longer passes content that already has an Id and CreateDate set. Previously this data was available in 8.13.1.

### Specifics

When handling the ContentService.Publishing event the content does not have an Id or CreateDate set. Previously when creating content and saving and publishing as the first action the Id and create date was set. Log messages show Document {name} with (id=0) was published

### Steps to reproduce

Register an event handler on ContentService.Publishing
Create a new content item.
Fill in the properties of the content.
Click Save and Publish.
The ContentService.Publishing event handler fires, in the EventArgs the Content is missing an Id and CreateDate

### Expected result / actual result

The ContentService.Publishing event handler fires, in the EventArgs the Content has an Id and CreateDate. The published content log message should have the content id

**Comment by nul800sebastiaan** [comment] 2021-09-02 15:27
Haven't tested this yet but marking as a regression since it sure sounds like one. Could this have anything to do with the 8.15 refactorings for messagepack etc?

**Comment by nzdev** [comment] 2021-09-02 22:19
@nul800sebastiaan I don't think it would be related. Kind of seems like the publishing event is being fired before the saved event.

**Comment by nzdev** [comment] 2021-09-03 00:16
https://github.com/umbraco/Umbraco-CMS/issues/11022 sounds possibly related

**Comment by nul800sebastiaan** [comment] 2021-09-14 12:18
Sorry, I forgot to get back to this one, I was testing it and seeing this on 8.11.1: 

![image](https://user-images.githubusercontent.com/304656/133255612-4e06dcaa-dcd7-49e3-8a27-631770ae1bb8.png)

Then I realized: of course! You are Publish`ing` - so this data is not yet available, it's a completely new content item, hasn't been saved in the database yet, you have a chance to prevent that in this event. So this is completely expected behavior. :-)

**Closed by nul800sebastiaan** 2021-09-14 12:18 UTC
Labels: status/regression, type/bug
