### ISSUE TITLE
Umbraco 8.7 breaks existing multiurlpicker content when upgrading from umbraco 8.6.5

### ISSUE THREAD

**Issue by stefanbesteman-weareyou** [umbraco/Umbraco-CMS#9115] opened 2020-10-08 11:51 UTC
A brief description of the issue goes here.
multiurlpicker content must be reselected again and publish before it is working again

## Umbraco version

I am seeing this issue on Umbraco version: 8.7

Reproduction
------------
after upgrade from 8.6.5 to 8.7

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce
take an 8.6.* instance with multi url picker on a doctype which has a internal page selected as content. Then upgrade to 8.7 and rerender site. Url gives null, while if you open it in umbraco it is still selected. After publishing this node, it works again. Publishing with child nodes from a parent doesn't work

### Expected result
After a database compare, I see the following difference after a publish
**Umbraco 8.7**
{"pd":{"link":[{"c":"en","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"cs-cz","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesceskoslovensko/\"}]"},{"c":"el-gr","v":"[{\"name\":\"Facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesgreece/\",\"queryString\":\"\"}]"},{"c":"nl-nl","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational\"}]"},{"c":"pl-pl","v":"[{\"name\":\"facebook\",\"url\":\"https://www.facebook.com/farmfritespolska/\",\"queryString\":\"\"}]"},{"c":"ru-ru","v":"[{\"name\":\"Facebook\",\"url\":\"https://www.facebook.com/farmfritesrussia/\"}]"},{"c":"sv-se","v":"[{\"name\":\"facebook\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"de-de","v":"[{\"name\":\"Facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"en-gb","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/FarmFritesUKandIreland/\"}]"},{"c":"hu-hu","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"ja-jp","v":"[{\"name\":\"Facebook\",\"target\":\"_blank\",\"udi\":\"umb://document/17444cdb43fd4321b49318e5efc2a212\"}]"},{"c":"lt-lt","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"lv-lv","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"pt-br","v":"[{\"name\":\"https://www.facebook.com/farmfritesinternational/\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"c":"en-sg","v":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"}]},"cd":{"en":{"nm":"facebook","us":"facebook","dt":"2020-10-08T14:20:15.7940095+02:00","isd":false},"cs-cz":{"nm":"facebook","us":"facebook","dt":"2020-05-12T11:12:23.74Z","isd":false},"el-gr":{"nm":"Facebook","us":"facebook","dt":"2020-05-12T11:21:22.303Z","isd":false},"nl-nl":{"nm":"Facebook","us":"facebook","dt":"2020-05-12T11:05:53.937Z","isd":false},"pl-pl":{"nm":"Facebook","us":"facebook","dt":"2020-05-12T11:07:13.233Z","isd":false},"ru-ru":{"nm":"Facebook","us":"facebook","dt":"2020-05-12T11:41:02.577Z","isd":false},"sv-se":{"nm":"facebook","us":"facebook","dt":"2020-05-12T11:43:03.31Z","isd":false},"de-de":{"nm":"Facebook","us":"facebook","dt":"2020-05-12T11:47:11.683Z","isd":false},"en-gb":{"nm":"facebook","us":"facebook","dt":"2020-07-01T13:12:38.683Z","isd":false},"hu-hu":{"nm":"facebook","us":"facebook","dt":"2020-07-15T14:16:37.793Z","isd":false},"ja-jp":{"nm":"facebook","us":"facebook","dt":"2020-10-07T11:34:20.65Z","isd":true},"lt-lt":{"nm":"facebook","us":"facebook","dt":"2020-07-15T14:12:10.52Z","isd":false},"lv-lv":{"nm":"facebook","us":"facebook","dt":"2020-07-15T08:47:48.39Z","isd":false},"pt-br":{"nm":"Facebook","us":"facebook","dt":"2020-07-14T13:59:20.543Z","isd":false},"en-sg":{"nm":"facebook","us":"facebook","dt":"2020-07-01T10:43:20.723Z","isd":false}},"us":"facebook"}

**Umbraco 8.6.5**
{"properties":{"link":[{"culture":"en","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"cs-cz","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesceskoslovensko/\"}]"},{"culture":"el-gr","seg":"","val":"[{\"name\":\"Facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesgreece/\",\"queryString\":\"\"}]"},{"culture":"nl-nl","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational\"}]"},{"culture":"pl-pl","seg":"","val":"[{\"name\":\"facebook\",\"url\":\"https://www.facebook.com/farmfritespolska/\",\"queryString\":\"\"}]"},{"culture":"ru-ru","seg":"","val":"[{\"name\":\"Facebook\",\"url\":\"https://www.facebook.com/farmfritesrussia/\"}]"},{"culture":"sv-se","seg":"","val":"[{\"name\":\"facebook\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"de-de","seg":"","val":"[{\"name\":\"Facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"en-gb","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/FarmFritesUKandIreland/\"}]"},{"culture":"hu-hu","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"ja-jp","seg":"","val":"[{\"name\":\"Facebook\",\"target\":\"_blank\",\"udi\":\"umb://document/17444cdb43fd4321b49318e5efc2a212\"}]"},{"culture":"lt-lt","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"lv-lv","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"pt-br","seg":"","val":"[{\"name\":\"https://www.facebook.com/farmfritesinternational/\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"},{"culture":"en-sg","seg":"","val":"[{\"name\":\"facebook\",\"target\":\"_blank\",\"url\":\"https://www.facebook.com/farmfritesinternational/\"}]"}]},"cultureData":{"en":{"name":"facebook","urlSegment":"facebook","date":"2020-05-12T11:47:16.68Z","isDraft":false},"cs-cz":{"name":"facebook","urlSegment":"facebook","date":"2020-05-12T11:12:23.74Z","isDraft":false},"el-gr":{"name":"Facebook","urlSegment":"facebook","date":"2020-05-12T11:21:22.303Z","isDraft":false},"nl-nl":{"name":"Facebook","urlSegment":"facebook","date":"2020-05-12T11:05:53.937Z","isDraft":false},"pl-pl":{"name":"Facebook","urlSegment":"facebook","date":"2020-05-12T11:07:13.233Z","isDraft":false},"ru-ru":{"name":"Facebook","urlSegment":"facebook","date":"2020-05-12T11:41:02.577Z","isDraft":false},"sv-se":{"name":"facebook","urlSegment":"facebook","date":"2020-05-12T11:43:03.31Z","isDraft":false},"de-de":{"name":"Facebook","urlSegment":"facebook","date":"2020-05-12T11:47:11.683Z","isDraft":false},"en-gb":{"name":"facebook","urlSegment":"facebook","date":"2020-07-01T13:12:38.683Z","isDraft":false},"ja-jp":{"name":"facebook","urlSegment":"facebook","date":"2020-10-07T11:34:20.6514674+00:00","isDraft":true},"pt-br":{"name":"Facebook","urlSegment":"facebook","date":"2020-07-14T13:59:20.543Z","isDraft":false},"en-sg":{"name":"facebook","urlSegment":"facebook","date":"2020-07-01T10:43:20.723Z","isDraft":false},"lv-lv":{"name":"facebook","urlSegment":"facebook","date":"2020-07-15T08:47:48.39Z","isDraft":false},"lt-lt":{"name":"facebook","urlSegment":"facebook","date":"2020-07-15T14:12:10.52Z","isDraft":false},"hu-hu":{"name":"facebook","urlSegment":"facebook","date":"2020-07-15T14:16:37.793Z","isDraft":false}},"urlSegment":"facebook"}

**Comment by nul800sebastiaan** [comment] 2020-10-09 08:43
While the data might be stored differently, you shouldn't notice the difference. 

I just tried this out, selected 3 types of links in 8.6.5 (external, internal, media) and then upgraded to 8.7.0. The links are still there for me and the frontend still works as well. 

If you have additional steps to reproduce then I'm all ears but as far as I can tell it might be something that went wrong somehow in your upgrade, not sure what though. I'll close this for now but if you have more reproduction steps we can take a look again.

**Closed by nul800sebastiaan** 2020-10-09 08:43 UTC

**Comment by stefanbesteman-weareyou** [comment] 2020-10-09 09:10
The links are stil there in umbraco, but if you throw away your cache in appdata/temp and then you rerender the frontend, you will notice that the links are corrupt

**Comment by nul800sebastiaan** [comment] 2020-10-09 13:03
Hmm, sorry, I still can't reproduce, I've deleted `App_Data/TEMP` and restarted IIS, everything still works as expected both backoffice and frontend 🤔
