### ISSUE TITLE
Issues with free text search in log viewer

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13715] opened 2023-01-23 09:20 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

I noticed in log viewer on some v10 projects that a free text search didn't seem to return any results, e.g. with latest 10.4.0 (but also on 10.3.2). We noticed this because we wasn't really able to find results, which we know we logged in e.g. from Hangfire jobs.

I tried another project on v10.0.1 as well.

E.g. I can find results on "FindTemplate" using.

```
SourceContext='Umbraco.Cms.Core.Routing.PublishedRouter'
```

![image](https://user-images.githubusercontent.com/2919859/214003606-7219d391-44a7-42a8-b71a-1ee1557a102a.png)

but when I search "FindTemplate" as free text it doesn't return any result.

![image](https://user-images.githubusercontent.com/2919859/214003653-c5b60443-af70-4332-b5b4-bd0c3e43de8c.png)

I tried a project using Umbraco v9.4.1 where it does work.

![image](https://user-images.githubusercontent.com/2919859/214003945-81b1e465-935b-4e20-adbf-9b1042d486cf.png)

![image](https://user-images.githubusercontent.com/2919859/214003986-3f44c223-7a83-4d02-9b96-7b2b57e02a33.png)

### Steps to reproduce

Search on any free text which you know exists in log, e.g. "ExternalIndex" og "Index".

**Comment by bjarnef** [comment] 2023-01-23 09:20
@bergmania @elit0451 do you know if something regarding this has been affected by upgrade to .NET6?

**Comment by bjarnef** [comment] 2023-01-23 09:26
I guess there's an issue somewhere with `GetLogs()` here:
https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs#L93-L110

In both cases `filterExpression` is set correct.

![image](https://user-images.githubusercontent.com/2919859/214005328-62eacbba-1f79-46b6-a975-9a0959d59357.png)

**Comment by Zeegaan** [comment] 2023-01-23 12:16
@bjarnef did it work on 10.0.1? 🤔

**Comment by bjarnef** [comment] 2023-01-23 12:19
@Zeegaan no, it doesn't.. but in a project on Umbraco v9.4.1 it does 😉
So I suspect it has something to do with .NET6 or nullable references?

**Comment by Zeegaan** [comment] 2023-01-23 12:22
Hmm wierd indeed, I'll have a look at reproducing and see if i find something obvious 😁

**Comment by Zeegaan** [comment] 2023-01-23 13:54
I think i found the culprit commit here: bd6334ecdc95234699e3ac4fbbda622237c6860f
Seems like we switched to Serilog.Expressions and it broke the `PerformMessageLikeFilter` function.

V9 method: 
```
private Func<LogEvent, bool> PerformMessageLikeFilter(string filterExpression)
{
    var filterSearch = $"@Message like '%{FilterLanguage.EscapeLikeExpressionContent(filterExpression)}%'";
    if (FilterLanguage.TryCreateFilter(filterSearch, out var eval, out _))
    {
        return evt => true.Equals(eval(evt));
    }

    return null;
}
```

V10 method:
```
private Func<LogEvent, bool>? PerformMessageLikeFilter(string filterExpression)
{
    var filterSearch = $"@Message like '%{SerilogExpression.EscapeLikeExpressionContent(filterExpression)}%'";
    if (SerilogExpression.TryCompile(filterSearch, out CompiledExpression? compiled, out _))
    {
        // `compiled` is a function that can be executed against `LogEvent`s:
        return evt =>
        {
            LogEventPropertyValue? result = compiled(evt);
            return ExpressionResult.IsTrue(result);
        };
    }

    return null;
}
```

This happens because the LogEventPropertyValue? result is null, so something wrong happens there 🤔

**Comment by Zeegaan** [comment] 2023-01-23 13:55
I will put this up for grabs for now as we know where it happens and why, so hopefully should be enough information to help 👍

**Comment by bjarnef** [comment] 2023-01-23 18:10
Maybe @warrenbuckley is more familiar with Serilog and has an idea how this should work?

**Comment by warrenbuckley** [comment] 2023-01-27 08:57
@bjarnef & @Zeegaan OK a quick look into this something is odd indeed.

Doing a search just for `FindTemplate` returns no results but the underlying query that it changes it to if you enter that directly as the query then that works?!

```
// This Fails
index

// This works
@Message like '%index%'
```

Will poke around to see if I can figure out what is happening or going wrong

**Comment by warrenbuckley** [comment] 2023-01-27 09:26
@Zeegaan a PR fixing this is here
https://github.com/umbraco/Umbraco-CMS/pull/13748

**Comment by Zeegaan** [comment] 2023-01-30 09:33
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13748

**Closed** 2023-01-30 09:32 UTC
Labels: status/regression, type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12

**Comment by nul800sebastiaan** [comment] 2023-03-16 09:58
Cherry picked for 10.5 in 06b89963e4fbbcade4b75eea63edea9893386ea8
