### ISSUE TITLE
Creating a new content type in block list, creates a template too

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8874] opened 2020-09-11 11:27 UTC
I am seeing this issue on Umbraco version: 8.7.0

Reproduction
------------

In the block list configuration, add a new content type. Upon creation, a new template has been created too including a cshtml file.

This does not make any sense, as element types can't have templates.

If anything, the view should be placed in Partials/Blocks/Components to follow the core way of handling block views.

![uppHYgsOVh](https://user-images.githubusercontent.com/3726467/92920359-795e8080-f432-11ea-92c8-4137ba399127.gif)

**Comment by nul800sebastiaan** [comment] 2020-09-11 13:06
Yep, this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8646 👍

**Closed by nul800sebastiaan** 2020-09-11 13:06 UTC
