### ISSUE TITLE
UX Block Editor: Show editing mode when there is a single Block

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#8912] opened 2020-09-16 03:42 UTC
The advantage of Nested Content is the user experience allowing you to add/edit the content quickly.

With Block List Editor, you always have to choose a block before adding your content. It may be a better experience if you have just a single block, go directly to start adding content without the step of selecting the block. Given everything is possible through the Infinite Editor, with nested blocks (and specially single block inside single block), the experience becomes slightly overwhelming with too many clicks.

**Comment by bjarnef** [comment] 2020-09-16 07:25
Seems like a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8760
It does however also need to ensure nothing is available in clipboard before adding the item directly.

**Comment by nul800sebastiaan** [comment] 2020-09-16 07:35
Yep, thanks! This duplicates #8760, I'll close this one, make sure to follow progress on there! 👍

**Closed by nul800sebastiaan** 2020-09-16 07:35 UTC
