### ISSUE TITLE
V7 - BulkInsert does not work with the decimal type

### ISSUE THREAD

**Issue by jerpenol** [umbraco/Umbraco-CMS#4859] opened 2019-03-05 10:43 UTC
As this issue (https://issues.umbraco.org/issue/U4-9399) states:

"When doing an ApplicationContext.DatabaseContext.Database.BulkInsertRecords(dayPaytypes); where my DayPayTypeDto contains a Decimal field it fails in

BulkDataReader.cs line 369

if (!numericPrecision.HasValue || !numericScale.HasValue) { throw new ArgumentException("numericPrecision and numericScale must be specified for "decimal" type columns."); }

This is because the scale and precision is never set.

I assume the DefinitionFactory.GetTableDefinition should set these two values"

Please fix this.

**Comment by JKoppenol** [comment] 2019-03-05 11:02
I have experienced the same problems with Float and Double typing

**Comment by nul800sebastiaan** [comment] 2019-03-07 12:43
Interesting. :-)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-08-29 19:17
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-08-29 19:17 UTC
Labels: community/up-for-grabs, help wanted, type/bug

**Comment by sekmenhuseyin** [comment] 2019-12-26 10:03
Hi,

I have the same problem. Umbraco gives error on bulk insert of decimal type. If I insert the rows one by one everything works normal.

```
public class FrmActivityCategoryPoints 
{        
      public decimal Point { get; set; }
 }

var entities= list.Select(item => new FrmActivityCategoryPoints
{
    Point = 1
}).ToList();

//gives error: "numericPrecision and numericScale must be specified for "decimal" type columns."
 _context.Database.BulkInsertRecords(entities, _context.SqlSyntax); 
```

**Comment by enkelmedia** [comment] 2020-10-24 18:39
The issue is still present in V8, a "workaround" would be to use NPocos, InsertBulk which worked for me on SQL Server express, I guess this would not work in SqlCe.

```
using (var scope = _scopeProvider.CreateScope())
{
        scope.Database.InsertBulk(dtos);
        scope.Complete();
}
```
