### ISSUE TITLE
V12 RC1: Content Delivery API does not respect "AddTrailingSlash" setting

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#14273] opened 2023-05-20 21:19 UTC
While playing around with the Content Delivery API (Awesome stuff! 😎) I noticed the url's are returned containing a trailing slash, like in this example **/blogposts/blog-post-1/**. I tried to disable the trailing slash being added by adding this so my `appsettings.json` would look like this

```
"RequestHandler": {
  "AddTrailingSlash": false,
}
```

Expecting the url mentioned to become **/blogposts/blog-post-1** - However it seems that the trailing slash is still being added, despite the setting.

---
_This item has been added to our backlog [AB#29663](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29663)_

**Comment by kjac** [comment] 2023-05-21 18:13
Hi @BatJan 👋 

Thanks for reporting! We'll check it out and see what we can do to mend this.

It should be entirely doable, and I can see how it would be useful to apply the returned paths directly to the output in your preferred format (with/without trailing slashes). There will be edge cases where a trailing slash is likely not going to be possible - specifically thinking of previewing content that has no route. But we'll see; if nothing else we should be quite able to handle this for published content, which in all fairness is likely the most critical case.

**Comment by nul800sebastiaan** [comment] 2023-05-22 09:29
@BatJan I'd really very much like to know what the use case for adding trailing slashes is these days, other than "this is how I always do it". 🙂

**Comment by kjac** [comment] 2023-05-23 06:20
I honestly don't think it has any importance SEO wise. I might be mistaken 😄 but as long as there aren't duplicate URLs (both with and without slashes), I believe it boils down to a matter of taste.

That being said, I still think it makes sense to support it. Even though the `path` of an item is theoretically "just" a resource identifier, it can double just fine as a routable URL, and we want people to be able to use the API output as-is without having to manipulate the paths

Fun(ish) fact: Incidentally, path manipulation is one of the "grievance learnings" we have incorporated from the Heartcore learnings over the past versions of the Heartcore REST API. Not at all tied to trailing slashes, though 😆

**Comment by kjac** [comment] 2023-05-23 16:45
So.. having dug a little deeper here, `AddTrailingSlash` is already honoured by the API. I _did_ have a feeling it would be 😆 however, one must restart the site after changing the setting for it to take fully effect, because some paths are added to the runtime property level cache. 

Here's with `"AddTrailingSlash": true`:

<img width="533" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/ef90609a-8e6b-42dd-8a96-43ae10d91ac9">

And here's the same request with `"AddTrailingSlash": false` (after a restart):

<img width="549" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/bc666676-e06c-497a-9f6f-8be718c65c1e">

The issue still stands for "purely unpublished URLs" (which is an upcoming feature for 12.0), but we've already got that added to the backlog. So I'm going to close this issue as being a non-issue 😄 

Thanks again for testing and reporting ❤️

**Closed by kjac** 2023-05-23 16:45 UTC
Labels: state/sprint-candidate, type/bug, area/backend, affected/v12

**Comment by BatJan** [comment] 2023-05-23 21:27
Hmm I could have sworn that I did restart the site but without seeing any changes. But I'll make sure to double check once I get a chance to do so - But as long as it works as one would expect I'm happy 😃 Cheers!

**Comment by kjac** [comment] 2023-05-24 05:34
@BatJan thanks mate 🚀 please do reopen if you can reproduce!
