### ISSUE TITLE
TinyMCE Image picker

### ISSUE THREAD

**Issue by IainMartin-Ayr** [umbraco/Umbraco-CMS#9218] opened 2020-10-19 15:53 UTC
When using the TinyMCE Image picker, once you have selected your image it goes to the Alternative Text overlay. The Select Media footer div is hiding the footer of this overlay and therefore you can't save the image back to TinyMCE

I am seeing this issue on Umbraco version: V8.7.0

Reproduction
------------

Edit some text in TinyMCE and click on the Media Picker icon.
Select an Image to put into the TinyMCE editor.

Result as shown in attatched image.
![TinyMCE_Error](https://user-images.githubusercontent.com/50440987/96475114-89386400-122b-11eb-98f9-3a7753a10b29.jpg)

**Comment by nul800sebastiaan** [comment] 2020-10-20 08:36
Hi @IainMartin-Ayr, that is really strange. Unfortunately for you I can't reproduce this in a fresh install of v8.7.0:

![image](https://user-images.githubusercontent.com/304656/96561475-e8e04f00-12bf-11eb-9626-aece493d946e.png)

Could it be that you've upgraded this site from another version to 8.7? This might be a problem during your upgrade. Often people forget to update the version in ClientDependency.config (just make it 1 higher or lower). If it's still not working then, maybe refer to this blog post, it's a bit old but still applies: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

I'll close this for now, but if you can still reproduce after checking all these things we might need to re-open it.

**Closed by nul800sebastiaan** 2020-10-20 08:36 UTC

**Comment by IainMartin-Ayr** [comment] 2020-10-20 10:13
Hi Seb,

Still getting it, changed the ClientDependency number (that's caught me out a few times) and removed any stylesheets that I had created in the Admin section just in case there was something in that causing the issue but it's still there.

But if you're not getting the error, more than likely it's something I've done somewhere, so I'll keep digging and see if I can find it. It will be something (a) simple and (b) stupid.

**Comment by nul800sebastiaan** [comment] 2020-10-20 10:36
@IainMartin-Ayr It will probably be easier to upgrade to Umbraco 8.6 or higher, that way you get the officially supported version and as an added bonus many other bugs have been fixed and lovely features added 😅

**Comment by IainMartin-Ayr** [comment] 2020-10-20 11:28
I’m running 8.7.0 at the moment – it’s more than likely I’ve burst something somewhere down the line.

 

Did upgrade to 8.8.0 but it bursts ModelBuilders API in the back-end, but I’ve raised a support ticket on GitHub for that as well 😊

**Comment by IainMartin-Ayr** [comment] 2020-10-26 16:52
Hi Seb,

Found the issue - it's in the Matryoshka tabbed content plugin - there's a setting in there on line 92, .umb-editor-container, that has a z-index of 2. Your footer is z-index:30 so the media plugin container is sitting below the footer because of that. Set the Matryoshka z-index to something stupid and it works again.

If you weren't using that plugin then you wouldn't see the issue.

Cheers,
Iain

**Comment by IainMartin-Ayr** [comment] 2020-10-26 16:58
AND..... I've just noticed there is an update to that package that resolves that bug, so we're sorted :-)
