### ISSUE TITLE
Nested Content - Copying an item

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#8020] opened 2020-04-27 12:39 UTC
Umbraco 8.6.1 

Hey,

If you copy a nested content item to within the same nested content block, when it is rendered out the item you selected to copy is duplicated regardless of updating the content on the new item. 

Even if you update the content in the first item, it is then rendered where the 2nd item should be. I'm assuming it could be something like the same Guid is reused and its getting it out of the cache?

* AFAIK - this worked fine in 8.6.0 (_i think_ although I wasn't paying attention to it at the time)

Happy to provide further info if needed?

Cheers
Ric

**Comment by jbjc** [comment] 2020-05-04 11:10
This has been going on for a while now unfortunately: #7113 and #5913

**Comment by nul800sebastiaan** [comment] 2020-05-11 12:05
Thanks for the report! I'll close this as a duplicate of #5913 - we'll have a look at this again soon! Sorry for the inconvenience.

**Closed by nul800sebastiaan** 2020-05-11 12:05 UTC
