### ISSUE TITLE
The partial view 'blockgrid/default' was not found

### ISSUE THREAD

**Issue by nickcollinsiom** [umbraco/Umbraco-CMS#13777] opened 2023-02-02 13:29 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0 & 11.0.1

### Bug summary

Created a brand new Umbraco 10.4.0 solution and created a new document type with the block grid editor. After rendering on the newly created template, the following error is displayed:

```
InvalidOperationException: The partial view 'blockgrid/default' was not found. The following locations were searched:
/App_Plugins/Views/Render/blockgrid/default.cshtml
/App_Plugins/Views/Shared/blockgrid/default.cshtml
/App_Plugins/Views/Partials/blockgrid/default.cshtml
/App_Plugins/Views/MacroPartials/blockgrid/default.cshtml
/Views/blockgrid/default.cshtml
/Views/Shared/blockgrid/default.cshtml
/Views/Partials/blockgrid/default.cshtml
/Views/MacroPartials/blockgrid/default.cshtml
/Views/Render/blockgrid/default.cshtml
/Views/Shared/blockgrid/default.cshtml
```

It seems to be missing the following files as references in this method here:

```
"areas.cshtml",
"default.cshtml",
"items.cshtml"
```

[https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_3_0/AddBlockGridPartialViews.cs](https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_3_0/AddBlockGridPartialViews.cs)

### Steps to reproduce

1. Create new Umbraco 10.4.0 or 11.0.1 solution using Visual Studio
2. When prompted set the Framework version to `.NET 6` and Umbraco Version to `10.4.0`
4. Create a new document type
5. Create a new property called Content Blocks
6. Add a new Block Grid data type
7. Install the sample blocks
8. Save
9. Add @await Html.GetBlockGridHtmlAsync(Model, "contentBlocks") to the document type template

**Comment by huwred** [comment] 2023-02-03 13:58
If I could add some info to this, it seems that if you first install a lower version say 10.0.0. or 10.3.2 and then do a nuget update to 10.4.0 the views do get created.

I haven't tested this with 11, but based on an U 11.0.1 test project I have, I would suggest the behaviour is the same and updating from 11.0.0 works but a straight install of 11.0.1 does not

**Comment by kjac** [comment] 2023-02-06 10:57
Hi @nickcollinsiom,

That's really strange... I can't reproduce this at all 😞 

I've used the [CLI templates](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates) here, but it should not matter.

```
> dotnet new umbraco --name Issue13777 --version 10.4
> cd .\Issue13777\
> dotnet run
```

![image](https://user-images.githubusercontent.com/7405322/216951984-ece773b4-72da-40a7-aa0c-ba29eade6e3c.png)

Once the installation is complete, the partial views are present on disk under `\Views\Partials\blockgrid`:

![image](https://user-images.githubusercontent.com/7405322/216952042-4ffc70f0-0bfa-488c-be60-07c345eced34.png)

If I render a page with a grid, things render as expected - nothing blows up.

Any chance you can add steps to reproduce the issue on your end?

**Comment by huwred** [comment] 2023-02-06 11:08
I am not using the CLI to do the install, I am installing from within Visual Studio. So maybe @nickcollinsiom isn't either

**Comment by nickcollinsiom** [comment] 2023-02-06 11:19
@kjac I create new solutions through VS using the installed .NET templates rather than CLI. However, I've just tried the steps you outlined above, same project name and version and the `blockgrid` folder is still missing:

![image](https://user-images.githubusercontent.com/17923409/216958349-606c5525-8651-43a9-bbaf-1af481a59f65.png)

I also ran `dotnet run` and went through the Umbraco setup to see if that was required before the folder would show but no luck.

**Comment by huwred** [comment] 2023-02-06 11:20
![install10 4](https://user-images.githubusercontent.com/4870243/216958125-df4245f6-fa74-4d82-9e93-170bfd098d8b.JPG)

After run the site in Visual studio, there are no blockgrid templates
![partials](https://user-images.githubusercontent.com/4870243/216958568-db2560a5-e5c4-43d7-9a06-28e34a631767.JPG)

Same result as @nickcollinsiom

**Comment by huwred** [comment] 2023-02-06 11:30
I have discovered the issue I think. I still have the template for version 10.0.0 installed, if I do

```
PS E:\umbraco-dev> dotnet new install Umbraco.Templates::10.4.0
The following template packages will be installed:
   Umbraco.Templates::10.4.0

Umbraco.Templates (version 10.0.0) is already installed, it will be replaced with version 10.4.0.
Umbraco.Templates::10.0.0 was successfully uninstalled.
Success: Umbraco.Templates::10.4.0 installed the following templates:
Template Name    Short Name      Language  Tags
---------------  --------------  --------  ------------------------------
Umbraco Package  umbracopackage  [C#]      Web/CMS/Umbraco/Package/Plugin
Umbraco Project  umbraco         [C#]      Web/CMS/Umbraco
```

And then redo the install I now get the partial views 😄

**Comment by nickcollinsiom** [comment] 2023-02-06 13:21
@huwred I can confirm I get the same behaviour as you. If you don't have the 10.4.0 templates installed but reference 10.4.0 in the VS configuration screen like below, it installs without the blockgrid folder.
![image](https://user-images.githubusercontent.com/17923409/216981864-b9ca7eec-e701-41e5-81bc-1e2bf1b5aa72.png)

**Comment by huwred** [comment] 2023-02-06 13:39
@nickcollinsiom @kjac 

I'm guessing this isn't strictly an Umbraco bug then, but maybe something that needs to be made clear in the docs or release notes. As I'm sure it will catch out others too 😃

**Comment by kjac** [comment] 2023-02-07 07:41
Hi @nickcollinsiom and @huwred,

Great job digging into this 💪 and what a silly error.

I'd love nothing more than to update [the docs](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/visual-studio) on this, but they do already state that in order to install with Visual Studio, one must first "Install the newest Umbraco dotnet templates." - although it's easy to forget, but a docs update won't really solve that 😄 

It would be awesome if the dotnet templates could set restrictions on that VS dialog, but that doesn't seem to be possible 😞 

I'm going to close this one now. If anyone comes up with a brilliant addition to the docs, feel free to amend them - the link is above 👍

**Closed by kjac** 2023-02-07 07:41 UTC
Labels: state/needs-more-info, type/bug
