### ISSUE TITLE
Can't clear/reset value of Date/Time in v.9.2.0

### ISSUE THREAD

**Issue by KlyssingJ** [umbraco/Umbraco-CMS#11954] opened 2022-02-08 13:26 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v9.2.0

### Bug summary

When using the date/time property editor after publishing a value it can't be cleared. When clearing the field and publishing again, the old value just reappears.

### Steps to reproduce

1. Add the common date/time property editor with default values to a element.
2. Include the element in some content as set a date
3. Publish the content with the date
4. Verify it is included in the published content
5. Clear the date and publish with an empty date
6. Check the published content that the date/time is still there with previous value

### Expected result / actual result

I expected the field to reset to minimum DateTime value as per default behavior when adding the date/time to content and not setting it.

---
_This item has been added to our backlog [AB#17351](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17351)_

**Comment by nikolajlauridsen** [comment] 2022-02-14 14:12
Hey @KlyssingJ, thanks for your report, unfortunately I'm unable to reproduce your issue. I've tried with both a normal property, and as a property within an element type and both seems to work as intended on my end. I've added a gif of my attempt, can you take a look and see if I'm doing something different to you? 😄 

![datetime](https://user-images.githubusercontent.com/16456704/153879939-833c89d3-5a96-4f24-977b-b423f737acbc.gif)

**Comment by KlyssingJ** [comment] 2022-02-16 08:23
Thank you for your time @nikolajlauridsen, must be something custom on our end then which produces this behavior. 😀

**Comment by nikolajlauridsen** [comment] 2022-02-16 08:29
You're welcome, a thing to check might be if you have any notification handlers that handles the `ContentSavingNotification`, since you can change the content that's being saved there. 

I'll go ahead and close this for now then 😄👍

**Closed by nikolajlauridsen** 2022-02-16 08:29 UTC
Labels: state/sprint-candidate, type/bug
