### ISSUE TITLE
File gets uploaded to Media root when uploading to a folder in Media

### ISSUE THREAD

**Issue by amfh** [umbraco/Umbraco-CMS#16570] opened 2024-06-07 08:31 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

File gets uploaded to Media root when trying to upload to a folder in Media.

### Specifics

Same issue on Chrome and Firefox

### Steps to reproduce

1- Create a folder called MyFolder in Media Root
2- Drag and drop a image file onto MyFolder page
3- Image is uploaded not in MyFolder, but it gets uploaded in Media root

### Expected result / actual result

Image file must be uploaded to the folder its dropped onto. This was working nice in UmbV13.

**Comment by Zeegaan** [comment] 2024-06-07 08:42
Heyo, as this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16524 I will go ahead and close this 😁 
Some additional information is that, there is luckily already a PR with a fix for this issue open 💪 https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1987

**Closed by Zeegaan** 2024-06-07 08:42 UTC
Labels: type/bug
