### ISSUE TITLE
Publishing parent and descendants doesn't refresh the content tree.

### ISSUE THREAD

**Issue by garpunkal** [umbraco/Umbraco-CMS#2991] opened 2018-09-17 11:09 UTC
If you have a content tree with parent and children that are unpublished, when publishing including descendants, it doesn't update the children in the content tree.

### Specifics
What version of Umbraco are you using (down to the very last digit!):
Umbraco version 7.11.1

What browser and version you are using:
69.0.3497.92 (Official Build) (64-bit)

Please mention if you've checked it in other browsers as well:
Firefox 62.0 (64-bit)

### Steps to reproduce:
Open the content section.
Click on a unpublished content tree with children. 
Right click and select publish.
Check "publish X and all its subpages". 
Check "include unpublished subpages". 
Click Publish. 

### Expected result
The content tree should reload to show the state changes. 

### Actual result
The content tree only updates the item selected, not the children.

**Comment by nul800sebastiaan** [comment] 2018-09-18 06:44
Can reproduce, this has been a problem possibly since at least 7.1.8 it looks like.

Relates to https://issues.umbraco.org/issue/U4-5666

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ismailmayat** [comment] 2018-09-20 08:35
will take this on as part of krakow hackathon, have managed to recreate on v7.13.0, you have to manually re load to get correct published status of child pages.

**Comment by nul800sebastiaan** [comment] 2018-10-21 09:02
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3265

**Closed** 2018-10-21 09:03 UTC
Labels: community/pr, release/7.13.0, type/bug
