### ISSUE TITLE
VariationContext not returning non variants for non default culture

### ISSUE THREAD

**Issue by laputaworkuk** [umbraco/Umbraco-CMS#12951] opened 2022-09-06 03:06 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

version 10.2.0--rc.preview.61.g9cf7e96

### Bug summary
As mention in Umbraco 10.2,  It allow editing a value from any language.
For normal case : I create the one document, set the document Allow vary by culture is true and create two textbox which both of them Allow vary by culture is false (it require from Client)
as below 
![image](https://user-images.githubusercontent.com/109957839/188536588-3bcb8965-c30f-4f07-9a3f-e08d4304e40a.png)
![image](https://user-images.githubusercontent.com/109957839/188536609-49ff1238-a747-4b57-9e54-caa44e929fd8.png)
After I input the value under default culture and click publish., I will get the publish document id
When I call `publishedContentQuery.Content({id})`; it can return the value 
![image](https://user-images.githubusercontent.com/109957839/188536919-c3bd236f-53c3-4350-9860-4d8d77a9b315.png)

However, when this document edit in non-default culture . I can't get any value from publishedContentQuery

### Specifics

The case will happen when you create the document 
1. Allow vary by culture is true
2. Edit Document in Non Default Culture

As per Version 10.2 describtion, it allow user to edit invaraint value and show share, but it cannot return value 

### Steps to reproduce

First Create the document as below 
![image](https://user-images.githubusercontent.com/109957839/188592793-3ed082f9-6f9d-4b43-a1db-0086ddd8c4f5.png)
Language setting define as below 
![image](https://user-images.githubusercontent.com/109957839/188537835-411f5717-f457-4a8f-a516-6ee110ba26b9.png)
Input value for two properties (TheWordWithMultiVary & TheWordSingleVary) where [TheWordSingleVary] is non Vary by Culture
![image](https://user-images.githubusercontent.com/109957839/188538243-774b27a4-c5eb-4c67-bc9a-814c3e811aa5.png)
and get the document id 
![image](https://user-images.githubusercontent.com/109957839/188538350-fda9b005-417a-4287-84da-641bcef57664.png)
In the visual code 
Run the code` var content = publishedContentQuery.Content(id);` when id value is 1083

### Expected result / actual result

The actual result 
![image](https://user-images.githubusercontent.com/109957839/188538534-02341fdb-a8c3-4b41-b1b7-f78198b24e81.png)
We expected result should be 
We can get all values from TheWordWithMultiVary and TheWordSingleVary, but the result is empty.
As it can work on Umbraco version 8.18, but right now, it failure to do in latest version

**Comment by nikolajlauridsen** [comment] 2022-09-07 09:38
Hi there @laputaworkuk I've tried to reproduce the issue however everything seems to work just fine on my end, I can get both the invariant and variant properties without any issue, I've tried to attach a gif of me trying to reproduce, can you check if I've misunderstood something? 

![variant](https://user-images.githubusercontent.com/16456704/188845884-5b15d009-72ea-4750-98c5-6d75012b8d47.gif)

**Comment by laputaworkuk** [comment] 2022-09-07 11:27
Hi @nikolajlauridsen , 
Thanks for your quick reply,  We are using umbraco as a host for multiple sites containing different languages (some don't require the the overall default language) which in your example is the en-US. We are filtering these out using notification variants. So the overall default language will not get published and instead the sites languages do, which works as we set the language to be default in the variants.

This used to work in umbraco 8.18 but now as the overall default language is not published the non variant values are not published.

We noticed that in the database in the umbracoPropertyData that if the default language was published that there are two versions stored (even if we only published once) . So in your example the home node would contain two versions (as if the default language was published twice)

We have a workaround for now where we force a publish for that node in the overall site default language, but this shouldn't really be needed (or at least it version 8 it is not needed)

**Comment by nikolajlauridsen** [comment] 2022-09-07 13:27
Ah okay, so how I understand it is you have a site with multiple languages, let's say English and Danish, where you want some root nodes to be only published in English and some to only be published in Danish 

* English site only published in english
	* English only node
* Danish site only published in danish
	* Danish only node

But if you only publish the non default language (danish in this case), like you would on the danish site, the invariant properties will not be published. 


This is (or was), actually expected behaviour, previously you were only allowed to edit the invariant properties from the default language (in this case English)

However, it's actually precisely this issue that we've fixed in 10.2 😄 

There is a caveat though, that by default this new behaviour (being able to publish invariant properties from a non-default language) is disabled though an appsetting. So you have to enable this.

In the version you're mentioning (`10.2.0--rc.preview.61.g9cf7e96`), the setting you need to enable is `Umbraco:CMS:Security: AllowEditInvariantFromNonDefault`. However in the final, which we will release tomorrow, we've moved this setting to `Umbraco:CMS:Content:AllowEditInvariantFromNonDefault` due to user feedback. 

So if you enable this it should work as expected.

This does also mean that you probably don't need to use notifications to hack around anything.

![variant](https://user-images.githubusercontent.com/16456704/188890031-5cd94b83-cff8-4603-8cf6-9fd021562569.gif)

**Comment by laputaworkuk** [comment] 2022-09-07 14:07
@nikolajlauridsen ,
Thank you very much, it's work

**Comment by nikolajlauridsen** [comment] 2022-09-07 14:14
Awesome 👍 I'll go ahead and close this issue then 😄

**Closed by nikolajlauridsen** 2022-09-07 14:14 UTC
Labels: type/bug
