### ISSUE TITLE
Published, Saved Events happen before nucache is updated

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#13339] opened 2022-11-01 09:45 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

9-10.3

### Bug summary

Hi Umbraco Team!
I am listening to Saved and published events and noticed there is a chance nuCache is not updated before the event is raised.
From my understanding published event should mean any operation on the item is finished.

### Steps to reproduce

Register handler like one below:
```
    public class ContentEventsNotificationNotificationHandler2 :
        INotificationAsyncHandler<ContentPublishedNotification>

    {
        private readonly IUmbracoContextFactory _provider;

        public ContentEventsNotificationNotificationHandler2(IUmbracoContextFactory provider)
        {
            _provider = provider;
        }

        public async Task HandleAsync(ContentPublishedNotification notification, CancellationToken cancellationToken)
        {
            var items = notification.PublishedEntities?.ToList();
            if (!items?.Any() ?? true)
            {
                return;
            }
            using (var context = _provider.EnsureUmbracoContext())
            {
                var umb = context.UmbracoContext;
                var itemsTarget = items.Select(x =>
                {
                    return umb.Content.GetById(x.Id);
                }).ToList();
                ///notice some of items are empty
            }
        }
    }
```
Noticed itemsTarget will contains null objects

**Comment by nikolajlauridsen** [comment] 2022-11-08 08:31
Hey @bielu 

I just looked at this, and unfortunately, this is more of a design choice than an actual bug as far as I can tell. 

The reason the cache might be null when you handle your notification is that the cache itself uses a notification to update, specifically the `ContentTreeChangeNotification`, this notification is published as a scoped notification, alongside the `ContentPublishedNotification`, since this is a scoped notification it will only be published once the scope is completed, this is needed to ensure everything was successful before we update the cache. But since different notifications, and handlers has no knowledge of each other we don't really have a way to ensure that one happens before the other. 

I'm wondering though what use case you're trying to solve, by getting the content from the cache, since you already have it in your notification handler? We of course want to ensure your use case can be solved, so it might be a matter of a missing notification or something.

**Comment by bielu** [comment] 2022-11-10 10:31
@nikolajlauridsen I am using abstraction to speak with IPublishContent, but the notification gives me only IContent and if I am not wrong there is no direct way of switching between them.  
For me Published/Saved notification should be the stage where we can "read-only" and not modify actual content, so a cache refresher should happen before it :)

**Comment by nikolajlauridsen** [comment] 2022-11-14 14:07
Okay, if you really need to use the `IPublishedContent` I'm afraid you'll have to use a different event, as mentioned, this is a design choice, we can't guarantee that the content will be in the cache when the `ContentPublishedNotification` is handled. This is even more apparent if you use load balanced, where the server messenger is required to update the cache, here it can a bit to update the cache, so there we have even less of a change (albeit the `ContentPublishedNotification` should only be published on the scheduler, but the point stands.)

We cannot guarantee that it will be in the cache when the `ContentPublishedNotification` is handled.


If you want though you can use the `ContentCacheRefresherNotification`, this notification is for exactly this purpose, it will be raised once the cache gets updated. I've made a rough example here that can get you started: 

```C#
public class NotificationTest : INotificationAsyncHandler<ContentCacheRefresherNotification>
{
    private readonly IUmbracoContextFactory _contextFactory;

    public NotificationTest(IUmbracoContextFactory contextFactory)
    {
        _contextFactory = contextFactory;
    }

    public Task HandleAsync(ContentCacheRefresherNotification notification, CancellationToken cancellationToken)
    {
        if (notification.MessageObject is not ContentCacheRefresher.JsonPayload[] payloads)
        {
            return Task.CompletedTask;
        }

        foreach (ContentCacheRefresher.JsonPayload payload in payloads)
        {
            if (payload.ChangeTypes is not TreeChangeTypes.RefreshNode)
            {
                return Task.CompletedTask;
            }

            using (UmbracoContextReference context = _contextFactory.EnsureUmbracoContext())
            {
                IPublishedContent? published = context.UmbracoContext.Content?.GetById(payload.Id);

                // Do stuff
            }
        }

        return Task.CompletedTask;
    }
}
```

**Comment by bielu** [comment] 2022-11-15 10:35
@nikolajlauridsen issue with that event is that it is happening on any cache update, not only on publish :) so if there is corruption of nucache or fresh boot and there is no nucache it will run as well.

**Comment by nikolajlauridsen** [comment] 2022-11-15 14:01
I'm sorry to hear that, but unfortunately, as stated, this is by design, and not a bug, so unfortunately we won't be changing how this works at this time, so I'll close this for now. We're happy for suggestions, but at this point, it's not something that we are able to fix.

**Closed by nikolajlauridsen** 2022-11-15 14:01 UTC
Labels: state/sprint-candidate, type/bug

**Comment by wtct** [comment] 2024-02-02 11:11
Hi @bielu & @nikolajlauridsen,

Honestly, I have been aware of this problem since the beginning of Umbraco.

Currently, I couldn't reproduce the issue on localhost, because the cache refresher is always fired before the `ContentPublishedNotification`. I know it could be specific to the localhost.

However, I would like to just ensure that nothing has changed.

@nikolajlauridsen Could you please confirm that nothing has changed?

Thanks in advance!

BTW, You can find information in our blog how we deal with this issue: [How to access currently published content in Umbraco](https://umbracare.net/blog/how-to-access-currently-published-content-in-umbraco/)

**Comment by nikolajlauridsen** [comment] 2024-02-02 11:52
To my knowledge, nothing has changed

**Comment by wtct** [comment] 2024-02-02 12:33
> To my knowledge, nothing has changed

Thank you for confirmation!

**Comment by bielu** [comment] 2024-02-02 15:31
@wtct this issue still occurs, even on v13, it is less dominant, as there is more async operations, but it still occurs. 
It is easiest to notice that when you have a lot of content publish at same time (Either by api or by scheduling). 

> Honestly, I have been aware of this problem since the beginning of Umbraco.
this issue was introduced in umbraco 8 so it can't be from beginning of umbraco ;) v7 had different types of issues.

**Comment by wtct** [comment] 2024-02-02 16:22
> @wtct this issue still occurs, even on v13, it is less dominant, as there is more async operations, but it still occurs. It is easiest to notice that when you have a lot of content publish at same time (Either by api or by scheduling).

@bielu Of course, there are several factors like amount of concurrent operations, number of nodes, performance of servers / service plans, number of distributed servers etc.

> this issue was introduced in umbraco 8 so it can't be from beginning of umbraco ;) v7 had different types of issues.

I'm pretty much sure that the issue with accessing just published content exists from the beginning. I was struggling with obtaining a URL on the `Published` event even in the V4.
