### ISSUE TITLE
Getting parent property in SurfaceController throws NullReferenceException

### ISSUE THREAD

**Issue by BramvdBogaard** [umbraco/Umbraco-CMS#11119] opened 2021-09-16 11:45 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0

### Bug summary

I'm trying to add some values to a DocTypeGridEditor by using a SurfaceController and a partial class.
When the "submit" button is pressed in the DocTypeGridEditor the IPublishedContent of the root node has been replaced with an UnpublishedContent representing the DocTypeGridEditor.

To add the required values to the grid I need to access the root node, the parent of the grid.
However, the AssignedContentItem has now changed which means that I need to use the Id of the current AssignedContentItem to get it's Parent.

This throws a NullReferenceException. Please note that this concerns both the IPublishedContent from the UmbracoHelper as the IContentService.

### Specifics

The AssignedContentItem contains a lot of NullReferenceErrors when using it with a DocTypeGridEditor. As seen in the following screenshots. The first one shows the location of the error, the second shows the AssignedContentItem.

![afbeelding](https://user-images.githubusercontent.com/33619813/133605685-d5a8210d-4942-41ee-a3a4-d7a498cd652e.png)

![afbeelding](https://user-images.githubusercontent.com/33619813/133605888-df7e4465-d01f-44e7-acc2-15c919b3217e.png)

### Steps to reproduce

1. Create a new DocTypeGridEditor
2. Add the editor to a page
3. Run ModelsBuilder
4. Create a SurfaceController that implements `DoctypeGridEditorSurfaceController<YOUR_EDITOR>`
5. inject the UmbracoHelper and create a variable to debug the AssignedContentItem with.
6. Load the page with the editor, open the editor and click "submit"

The following image shows my complete code:
![afbeelding](https://user-images.githubusercontent.com/33619813/133606194-de4b3c9d-9fd1-46f5-908c-aaf23e586588.png)

### Expected result / actual result

**Expected**
The correct values are retreived and set in the DocTypeGridEditor

**Actual**
The AssignedContentItem has changed, forcing you to get it's parent to retreive the correct values from.
The Parent throws a NullReferenceException.

**Comment by soreng** [comment] 2021-09-22 21:50
Hi @BramvdBogaard 

First of all, I would suggest not using the content service in your frontend - it does queries against the database, which is not really geared for the load that the frontend may receive.

The DocTypeGridEditorSurfaceController inherits from SurfaceController, so you don't need to inject the UmbracoHelper. Maybe that could be the cause of your issue?

Looking at your screenshot, it also seems that your DocumentTypeAlias is your grid editor. Maybe this is becuse the DocTypeGridEditorSurfaceController is not handling the umbraco content, but only the grid element? @skttl ?

It seems more like an issue with how the DocTypeGridEditorSurfaceController works, than the umbraco services.

**Comment by skttl** [comment] 2021-09-23 06:14
You don't have to inject UmbracoHelper, DocTypeGridEditorSurfaceController inherits from SurfaceController, which has the UmbracoHelper in `Umbraco`.

DocTypeGridEditorSurfaceController works on the `IPublishedElement` of the grid item, but you should be able to get the current node via `Umbraco.AssignedContentItem`. What does `Umbraco.AssignedContentItem.Id` give you?

**Comment by BramvdBogaard** [comment] 2021-09-28 08:26
Sorry for my late reply. 
Umbraco.AssignedContentItem returns null which is the root of my problem.
After looking into it a bit further it seems that the context of the DocTypeGridEditor has completely changed from the Report node that contains it.

This seems to have been done by design but I have no clue why. As a result it has become impossible to get the correct values from the parent node because of the AssignedContent being null and thus not having a parent.

The only workaround that my colleagues and I have found is saving the correct Id in a RuntimeCache and using that to get the correct values from IContent in the DocTypeGridEditorSurfaceController. The AssignedContent is of type UnpublishedContent so I cannot use the IPublishedContent from the UmbracoHelper which is why I'm using IContent.
This is obviously not ideal and quite an ugly workaround but it seems to have done the trick.

If someone has a better workaround I'd love to know it.

**Comment by nul800sebastiaan** [comment] 2021-10-05 13:50
Good to hear that you've at least found the cause of the problem. I think this would be up to DocTypeGridEditor to fix since when that's not used, the scenario works as expected. Not sure what is being changed there but it sounds like it would be possible for DTGE to expose a content item that you could use somehow. 

I'll close this one for now! 👍

**Closed by nul800sebastiaan** 2021-10-05 13:50 UTC
Labels: type/bug
