### ISSUE TITLE
8 version 8.5.5 to 8 latest we found webp images height * width 200 * 200 

### ISSUE THREAD

**Issue by rajasrmit** [umbraco/Umbraco-CMS#14834] opened 2023-09-19 14:04 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.5.5

### Bug summary

We notice that when we upload the web image type form backoffice the height and width is taken 200 * 200
When I check this link it was fixed on 8.0.1 but I still face the same issue on 8.5.5 version and lates 8.18.8. Can you please help here.

We have shared the video recordings for this issue for 8.5.5 to 8.18.8

https://www.loom.com/share/6f19c5008ec54946b6091750901dd317?sid=e5e383e4-962f-45a2-889e-8586f68d0946 -- 8.5.5

https://www.loom.com/share/ead46d61b146448689997094adaf5afe?sid=a0bf9cd7-cd9d-45e9-80c5-aa61500fc35c -- 8.18.8

### Steps to reproduce

Open Umbraco backoffice 
Go to Media  -> Upload any webp image 
After clicking the save and publish it is showing  height   width 200 * 200 

We have shared the video recordings for this issue for 8.5.5 to 8.18.8

https://www.loom.com/share/6f19c5008ec54946b6091750901dd317?sid=e5e383e4-962f-45a2-889e-8586f68d0946 -- 8.5.5

https://www.loom.com/share/ead46d61b146448689997094adaf5afe?sid=a0bf9cd7-cd9d-45e9-80c5-aa61500fc35c -- 8.18.8
![MicrosoftTeams-image (4)](https://github.com/umbraco/Umbraco-CMS/assets/19611367/3362edb6-443a-4aa2-a6ca-1f59747229fa)

### Expected result / actual result

Open Umbraco backoffice 
Go to Media  -> Upload any webp image 
After clicking the save and publish, It should show the actual image height and width not 200 * 200. 

![MicrosoftTeams-image (5)](https://github.com/umbraco/Umbraco-CMS/assets/19611367/09088e36-4e93-4361-be47-b3d12410cafa)

**Comment by rajasrmit** [comment] 2023-09-22 06:24
Team, please have someone look into this issue as the EOL date approaches.

**Comment by andr317c** [comment] 2023-09-22 08:24
Hey! 

A workaround could be adding an event handler when you save the image. to get the actual width and height of the image.
As it has been an issue since 8.5.5, we are not fixing it in v8. We are only fixing regressions 😁 

With that, I'm going to go ahead and close this issue, thanks for reporting 🐛

**Closed by andr317c** 2023-09-22 08:24 UTC
Labels: type/bug

**Comment by vishban07** [comment] 2023-09-27 10:46
@andr317c  Eventhandler is no more supported in umbraco 8 onwards right ? So is there any alternate option for workaround ?

Thanks.
