### ISSUE TITLE
Pressing '1' or '2' in RTE results in selecting Content or Info tab

### ISSUE THREAD

**Issue by GitCorne** [umbraco/Umbraco-CMS#7168] opened 2019-11-18 14:15 UTC
When adding a property of type RTE (Distraction free) and typing in '1' or '2' the current behavior is a bit strange. Instead of displaying '1' or '2' Umbraco selects the 'Content' (1) or 'Info' (2) tab. So it seems that when you have RTE of type distraction free on you content page that pressing 1 or 2 is acting as a shortcut to Content and/or Info.

Umbraco 8.2.1

**Comment by marcemarc** [comment] 2019-11-18 19:16
duplicate of https://github.com/umbraco/Umbraco-CMS/issues/6508 ?

**Comment by nul800sebastiaan** [comment] 2019-11-20 09:22
Yes, will close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/6508. Thanks @GitCorne, make sure to follow #6508 for progress on this issue.

**Closed by nul800sebastiaan** 2019-11-20 09:22 UTC
