### ISSUE TITLE
MediaPicker3 Not showing selection after removal

### ISSUE THREAD

**Issue by DanDiplo** [umbraco/Umbraco-CMS#10431] opened 2021-06-10 10:44 UTC
### Which Umbraco version are you using?

8.14

### Bug summary

In a specific set of circumstances I get a JavaScript error from the new MediaPicker3 saying: `vm.model.value.splice is not a function` that prevents the image being selected.

### Specifics

If you have a non-mandatory image field with new `MediaPicker3` and then publish, remove and publish again you can't re-select a new image without triggering a JavaScript error in the Angular model.

### Steps to reproduce

- Create a new non-mandatory property using the new MediaPicker3
- Select an image
- Save & Publish the page
- Remove the image (using the trashcan icon)
- Save & Publish the page again (so it saves with no image)
- Select an image again
- The image won't be selected because of the following JS error:

```
angular.js?cdv=494828325:15635 TypeError: vm.model.value.splice is not a function
    at umbraco.directives.js?cdv=494828325:20243
    at Array.forEach (<anonymous>)
    at Object.submit (umbraco.directives.js?cdv=494828325:20238)
    at Object.submit (umbraco.controllers.js?cdv=494828325:3303)
    at fn (eval at compile (angular.js?cdv=494828325:1), <anonymous>:4:232)
    at UmbButtonController.destination.<computed> [as action] (angular.js?cdv=494828325:11475)
    at UmbButtonController.clickButton (umbraco.directives.js?cdv=494828325:2264)
    at fn (eval at compile (angular.js?cdv=494828325:1), <anonymous>:4:245)
    at callback (angular.js?cdv=494828325:29019)
    at ChildScope.$eval (angular.js?cdv=494828325:19461)
```

![image](https://user-images.githubusercontent.com/6676168/121511726-df3b6100-c9e0-11eb-9d60-0166d5c05692.png)

### Expected result / actual result

After removing an image in these circumstances I expect to be able to select a replacement image.

---
_This item has been added to our backlog [AB#12541](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12541)_

**Comment by patrickdemooij9** [comment] 2021-06-10 20:21
I did some investigating and I was able to figure out why this is happening. Whenever you submit an empty mediapicker v3, the value will be an empty string on the return of PostSave:
![image](https://user-images.githubusercontent.com/11466511/121589205-19375200-ca37-11eb-8ed2-febc8cbc6a5c.png)

This then sets the vm.model.value to an empty string, which causes the splice to give an error. The reason that this wasn't an issue in the older version (at least, I think) is because it holds an array of ids separate from the vm.model.value and only syncs when the value changes. 

I think the best way to fix this is to do the same. Hold a separate variable for the images and only sync it to vm.model.value whenever it's updated. The other way is to recheck the vm.model.value for an empty string after the postsave has been done, but I don't think there is a JS event to look for that.

**Comment by nul800sebastiaan** [comment] 2021-06-23 06:44
Thanks for the report @DanDiplo and the proposed fix @patrickdemooij9 - I just need to know one important thing: why can't I reproduce the problem? 😅 Clearly I'm doing something wrong if you can both reproduce!

This is my attempt:

https://user-images.githubusercontent.com/304656/123048798-15c0a500-d3ff-11eb-8ce1-34bcb7dea159.mp4

**Comment by DanDiplo** [comment] 2021-06-23 09:04
Strange, I can reproduce it ever time. I think one of the variables is that you need to add the MP3 to an existing page that is already published, rather than a new page. My page was also varying by culture, but don't think that is significant.

I'll attach my screencap - it didn't capture the console output but just imagine the JS error being there :)

https://user-images.githubusercontent.com/6676168/123068989-4b1ec000-d40a-11eb-93b2-1cae507f9f7f.mp4

**Comment by nul800sebastiaan** [comment] 2021-06-23 14:02
Ah maybe variant as an issue, I didn't try that. I forgot to add that I did try with an existing doc as well, which is why I did my second try with a new doc to make sure I covered both cases. I'll try with variants!

**Comment by nul800sebastiaan** [comment] 2021-06-23 16:17
Yep, that was it, when the doctype and the property is multilingual, I get the error as well! 👍 

We're looking at it soon, thanks for helping with the reproduction!

**Comment by nielslyngsoe** [comment] 2021-07-09 09:41
Hi, thanks for a well-described issue, never the less I wasn't able to reproduce it, without awareness about how that comes.
I do though still see the issue by reading the code, and we clearly missed implementing the `onvalueChanged` callback, to ensure model-value is good always.
I have implemented this in this fix, which they should fix this issue as well.
Please test it out to ensure you agree, as I wasn't able to reproduce it.

https://github.com/umbraco/Umbraco-CMS/pull/10633

Thanks in advance.

**Comment by jemayn** [comment] 2021-07-19 10:59
Hey @nielslyngsoe 

Just wanted to say I hit the same issue that was reported here, and when I lifted your changes and threw them directly into the umbraco.directives.js file it solved the issue 🙂

**Comment by nielslyngsoe** [comment] 2021-07-19 11:01
@jemayn Thanks a lot, great to know that it solved the issue :-D

**Comment by nul800sebastiaan** [comment] 2021-07-20 07:54
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10633 and cherry picked for 8.14.1 in 3def2ee2ad2897e1d1c6d9b1d077e4c4652d01d4

**Closed by nul800sebastiaan** 2021-07-20 07:54 UTC
Labels: community/pr, state/in-sprint, status/regression, type/bug
