### ISSUE TITLE
UmbracoContext.ContentCache.GetByRoute is null when using custom Hostname

### ISSUE THREAD

**Issue by skidmow** [umbraco/Umbraco-CMS#3850] opened 2018-12-10 17:29 UTC
Accessing a page by route will return a null object if the requested content has a custom Hostname configured. This is a hierarchical issue, which means it also effects child pages and descendants of any page with a Hostname assigned.

Reproduction
------------
### Specifics

Version: v7.12.4. This also affects the dev-v7 branch.

### Steps to reproduce

- Create some nested pages in Umbraco (e.g. use The Starter Kit).
- Change the hostname of a page. If using the starter kit, change the hostname for `People` to http://mydomain.local/new-people
- View the page. You will see that it serves correctly.
- Now request the page by the UmbracoContext.ContentCache.GetByRoute() method. E.g. `IPublishedContent node = UmbracoContext.ContentCache.GetByRoute("/new-people/");`

### Expected result

I would expect the node to be populated with content for the `people` node.

### Actual result

The node object is null. From investigation, the reason the page loads perfectly fine on request is because the `ContentFinderByNiceUrl` class uses an alternative method to get content that has a new Hostname value (see logic inside HasDomain == true). This method uses the rootNodeId to generate a valid route path. This works! However it is not possible to use the parentId if you only have the string route, not the docRequest.

See the ContentFinderByNiceUrl code logic here:

```
public virtual bool TryFindContent(PublishedContentRequest docRequest)
{
    string route;
    if (docRequest.HasDomain)
	route = docRequest.Domain.RootNodeId.ToString() + DomainHelper.PathRelativeToDomain(docRequest.DomainUri, docRequest.Uri.GetAbsolutePathDecoded());
    else
	route = docRequest.Uri.GetAbsolutePathDecoded();
    
    var node = FindContent(docRequest, route);
    return node != null;
}
```

**Comment by skidmow** [comment] 2018-12-11 15:31
Having investigated a little deeper, I can see that the source of the issue is with the XML Cache itself  and the private method that iterates that cache document to find the route. `Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.NavigateElementRoute(XmlElement elt, string[] urlParts)`

This method iterates the ContentCache by each URL part. In the example above it would be looking for an element with a urlName of "new-people". This will never be found because the actual urlName of the page is still "people".

A possible solution would be to include any hostname subfolder path added via the Culture and Hostnames entry (you don't need the domain, just the subfolders) in the XML document and to also check this value. Url Parts are found from left to right, so it should be workable to only include the domain sub folders at the root level and not each nested element afterwards. This would help to prevent unnecessary bloat in the XML file.

**Comment by vaags** [comment] 2019-08-29 10:37
I could reproduce this in v8 as well.

**Comment by zpqrtbnk** [comment] 2019-08-29 10:45
A "route" as used by `GetByRoute` is not 100% the url path.

If no hostname is configured, then the route would be `/path/to/page` - however if a hostname is configured, then the route becomes `1234/path/to/page` where `1234` is the ID of the node carrying the hostname.

Therefore, once a hostname is configured, you cannot really use `GetByRoute` the way you are trying to.

**Comment by vaags** [comment] 2019-08-29 11:23
Thanks for the quick reply! I got it working :)

In my case I don't actually have a custom hostname, but a path for each language (```/english```, ```/norwegian``` etc). So, to get it working, I also had to remove the language from the path. Or else the path will be ```1234/english/path/to/page```, which does not work.

**Comment by nul800sebastiaan** [comment] 2019-08-29 12:55
Seems like we're all good here, I'll close this issue. :)

**Closed by nul800sebastiaan** 2019-08-29 12:55 UTC
Labels: state/hq-reply

**Comment by vaags** [comment] 2019-08-29 14:05
It seems i spoke too soon. In v8 it seems that all language variants have the same id(?). At least that is what shows inside backOffice. So how to you query a specific language?

**Comment by zpqrtbnk** [comment] 2019-08-29 14:31
This is by design, too. `GetByRoute`, as well as `GetById` etc, returns a *document* and a document does not have a specific language - it has all languages. So yes, those two routes will return the same *document* hence the same ID. Now once you have the document, you can get values from it for different cultures.

**Comment by vaags** [comment] 2019-08-29 14:40
Thanks for the speedy reply! I guess it would be nice to have a version of ```GetByRoute()``` that simply accepts the full path and returns the specified language(?)

**Comment by nul800sebastiaan** [comment] 2019-08-29 15:06
Hmm, does the same go for `IPublishedContent.Url` / `IPublishedContent.GetUrl()` @zpqrtbnk ? https://github.com/umbraco/Umbraco-CMS/issues/6199

**Comment by zpqrtbnk** [comment] 2019-08-29 16:15
unrelated, I believe - that other issue is weird
