### ISSUE TITLE
V8: Moving image into different folder resulted in Null reference exception

### ISSUE THREAD

**Issue by yaplex** [umbraco/Umbraco-CMS#5112] opened 2019-03-29 20:01 UTC
Steps to reproduce:
Add image picker on the page. 
select image from media library
Go to Media, create a different folder and move the image into that folder. 
The image URL stays the same and when refreshing page containing that image it should just work, but it gives Null Reference exception.

The interesting part, it gives an exception for a completely different piece of code but removing that image from page solved the issue. 

![image](https://user-images.githubusercontent.com/1596776/55259301-aec1df00-523b-11e9-88d7-752f78b59efe.png)
![image](https://user-images.githubusercontent.com/1596776/55259353-d6b14280-523b-11e9-816c-67da98dbc2f0.png)
![image](https://user-images.githubusercontent.com/1596776/55259420-f8122e80-523b-11e9-87cf-b5b1aed55c9e.png)

**Comment by Shazwazza** [comment] 2019-04-01 00:06
Sounds like an annoying issue! I've marked up-for-grabs and help-wanted to see if any community members might be able to assist with having a look and replicating and potentially fixing with a PR. Thanks for reporting

**Comment by kjac** [comment] 2019-04-01 14:36
Looks like this only happens for images uploaded before the image URL was shortened.

I can reproduce this with images that have URLs like this: */media/0e8fbdcf75e84a20bbb8aea1f707f21f/00000006000000000000000000000000/99-pull-request.png*, but not when the image URL is like this: */media/orsnteob/105-compromise.png*. 

@yaplex any chance your image was uploaded in a pre-release of V8? And... could you try to reproduce this with a newly uploaded image?

**Comment by yaplex** [comment] 2019-04-01 16:30
@kjac, I using 8.0.1
I never seen that long url you mentioned, my url looks like
/media/orsnteob/105-compromise.png

**Comment by yaplex** [comment] 2019-04-09 17:46
I got the latest dev version from Github and I can't reproduce this issue there, looks like somebody already fixed it.

**Comment by kjac** [comment] 2019-04-09 17:54
Matches my observations as well 👍

**Comment by Shazwazza** [comment] 2019-04-10 00:51
I will close this issue then unless someone else has steps to replicate with the latest codebase. Thanks!

**Closed by Shazwazza** 2019-04-10 00:51 UTC
Labels: community/up-for-grabs, help wanted, type/bug
