### ISSUE TITLE
Umbraco user login with external openid - error saying - Could not find external authentication provider registered: {LoginProvider}

### ISSUE THREAD

**Issue by jericyuen** [umbraco/Umbraco-CMS#12225] opened 2022-04-05 10:50 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

V8.16.0

### Bug summary

I'm trying to setup the OpenId connection for an external provider (Okta) for the back office user. But there's a bug in Umbraco that keeps saying the below error after the user has been logged in from the external provider and came back to the Umbraco login screen, and just got stuck there. I've tried to turn on autoLinking and also without autoLinking. Still the same error.

I keep getting the below error in the logs which i can't figure out why. 

It comes with like a curly bracket saying {LoginProvider} which I'm not sure where is it trying to pull that value from. 

The logs looks like
"Could not find external authentication provider registered: {LoginProvider}","@l":"Warning","LoginProvider":"https://trial-1275325.okta.com","SourceContext":"Umbraco.Web.Editors.BackOfficeController"

Do anyone know if we need to set any specific claims for Umbraco to work within the **SecurityTokenValidated** ?

Codes that I've got as below.

```
public class OktaOwinStartup : UmbracoDefaultOwinStartup
    {
        protected override void ConfigureUmbracoAuthentication(IAppBuilder app)
        {           
            base.ConfigureUmbracoAuthentication(app);

                        var oktaOptions = new OktaMvcOptions
            {
                OktaDomain = AppSettings.OktaDomain,
                ClientId = AppSettings.OktaClientId,
                ClientSecret = AppSettings.OktaClientSecret,
                AuthorizationServerId = string.Empty,     // This will either be "default" or empty string, else Umbraco sends you to /umbraco/ExternalLogin with 401 Unauthorized. 
                RedirectUri = AppSettings.OktaRedirectUri,
                PostLogoutRedirectUri = AppSettings.OktaPostLogoutRedirectUri,
                Scope = new[] { "openid", "profile", "email" }
            };

            var issuer = UrlHelper.CreateIssuerUrl(oktaOptions.OktaDomain, oktaOptions.AuthorizationServerId);
            var options = new OpenIdConnectAuthenticationOptionsBuilder(oktaOptions).BuildOpenIdConnectAuthenticationOptions();



            options.Caption = "Okta";
            options.ForUmbracoBackOffice("btn-microsoft", "fa-openid");
            options.RequireHttpsMetadata = !HttpContext.Current.IsDebuggingEnabled; // Set this value to false when debug is true (meaning it's local). As Open Id keeps asking for Https even on local
            options.SignInAsAuthenticationType = Constants.Security.BackOfficeExternalAuthenticationType;
            options.AuthenticationType = issuer;
            options.SetBackOfficeExternalLoginProviderOptions(new
            BackOfficeExternalLoginProviderOptions
            {
                AutoRedirectLoginToExternalProvider = false,
                DenyLocalLogin = false,
                AutoLinkOptions = new ExternalSignInAutoLinkOptions(AppSettings.OktaEnableUmbracoAutoLinking, new[] { Constants.Security.AdminGroupAlias })
                {
                    AllowManualLinking = false
                }
            });


            // Debugging on failed authentication and callback after logged in
            options.Notifications = new OpenIdConnectAuthenticationNotifications
            {
                AuthenticationFailed = OnAuthenticationFailed,
                AuthorizationCodeReceived = OnAuthorizationCodeReceived,
                SecurityTokenValidated = OnSecurityTokenValidated,
                RedirectToIdentityProvider = OnRedirectToIdentityProvider
            };

            app.UseOpenIdConnectAuthentication(options);
        }

        #region Private Methods

        private Task OnAuthenticationFailed(AuthenticationFailedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            // Skipping nonce error
            if (notification.Exception.Message.InvariantContains("IDX21323"))
            {
                notification.SkipToNextMiddleware();
            }
            else
            {
                //breakpoint somewhere in here to see that is happening.
                var errorMessage = notification.ProtocolMessage.ErrorDescription != null
                    ? $"Authentication Failed: {notification.ProtocolMessage.ErrorDescription}"
                    : "Authentication Failed";

                Current.Logger.Warn(typeof(OktaOwinStartup), errorMessage);
            }

            return Task.FromResult(0);
        }

        private Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedNotification notification)
        {
            // Use this to debug authorization code (if needed)
            return Task.FromResult(0);
        }

        private Task OnSecurityTokenValidated(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            var user = notification.AuthenticationTicket.Identity;

            user.AddClaim(new Claim(ClaimTypes.Name, user.FindFirst("name").Value));
            //user.AddClaim(new Claim(ClaimTypes.Email, user.FindFirst("preferred_username").Value));
            user.AddClaim(new Claim("access_token", notification.ProtocolMessage.AccessToken));
            user.AddClaim(new Claim("id_token", notification.ProtocolMessage.IdToken));
            return Task.FromResult(0);

        }

        private Task OnRedirectToIdentityProvider(RedirectToIdentityProviderNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            if (notification.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
            {
                var idTokenHint = notification.OwinContext.Authentication.User.FindFirst("id_token").Value;
                notification.ProtocolMessage.IdTokenHint = idTokenHint;
            }
            return Task.FromResult(0);
        }

        #endregion

    }
```

### Steps to reproduce

1. As I'm using Okta, you will need to setup the free Okta app, create a new application. The setup is straight forward as I've been following the guide here
https://effect.nz/our-thoughts/november-2021/umbraco-and-okta-integration/

2. Once we got the Key and Secret and domain. I've then use it with the code above on a fresh install of Umbraco V8.16.0

3. Remember to add the web.config settings for 
ClientId
ClientSecret
OktaDomain
RedirectUri
PostRedirectUri
AutoLinking 

4. Swap out the owin:appStartup in the web.config to use the one from the codes above which is OktaOwinStartup

5. And then we're good to test things out. Set the site to load in https and then once it's loaded go to the Umbraco backoffice
and click on the blue button to login to Okta

6. Once you've logged into Okta later it will callback to the Umbraco Login screen and get stuck there. Upon checking the logs, you get the error mentioned above

### Expected result / actual result

Expected Result - Should detect the email and see if the Umbraco User is there (when autolinking is on) and then login the user to the back office based on that

Actual Result - It just got stuck at the Umbraco Backoffice login once you got callback from Okta

**Comment by nikolajlauridsen** [comment] 2023-01-06 13:19
Hey, @jericyuen first off, sorry about the late answer. 

I've looked at this, and it works fine for me in both 8.16 and the latest 8.18. It does however seem like the article you're linking to, has some missing code, for instance, the authentication type when creating `OpenIdConnectAuthenticationOptionsBuilder`. 

I'm going to go ahead and close this issue for now since everything seems to work as intended. But before I do so I'll just post the code I got working here for inspiration, and of course I'll recommend reaching out to our community, either on [the forums](https://our.umbraco.com/forum/) or [our Discord server](https://community.umbraco.com/get-involved/community-discord-channel/), if you a few more sets of eyes 😄.

```C#
using EightSixteenOkta;
using Microsoft.Owin;
using Okta.AspNet;
using Okta.AspNet.Abstractions;
using Owin;
using Umbraco.Core;
using Umbraco.Web;
using Umbraco.Web.Security;

[assembly: OwinStartup("OktaOwinStartup", typeof(OktaOwinStartup))]
namespace EightSixteenOkta
{
    public class OktaOwinStartup : UmbracoDefaultOwinStartup
    {
        protected override void ConfigureUmbracoAuthentication(IAppBuilder app)
        {
            // Must call the base implementation to configure the default back  office authentication config.
            base.ConfigureUmbracoAuthentication(app);

            var oktaOptions = new OktaMvcOptions
            {
                OktaDomain = "<Your Okta domain>",
                ClientId = "<YourClientID>",
                ClientSecret = "<YourClientSecret>",
                AuthorizationServerId = string.Empty,
                RedirectUri = "https://localhost:44305/umbraco",
                PostLogoutRedirectUri = "https://localhost:44305/umbraco",
                Scope = new string[] { "openid", "profile", "email" }
            };

            var options = new OpenIdConnectAuthenticationOptionsBuilder(
                    Constants.Security.BackOfficeExternalAuthenticationType /* This was missing from the post*/,
                    oktaOptions).BuildOpenIdConnectAuthenticationOptions();

            options.Caption = "Okta";
            options.ForUmbracoBackOffice("btn-microsoft", "fa-openid");
            options.SignInAsAuthenticationType = Constants.Security.BackOfficeExternalAuthenticationType;
            options.AuthenticationType = UrlHelper.CreateIssuerUrl(oktaOptions.OktaDomain, oktaOptions.AuthorizationServerId);
            options.SetBackOfficeExternalLoginProviderOptions(new BackOfficeExternalLoginProviderOptions
            {
                AutoRedirectLoginToExternalProvider = false,
                DenyLocalLogin = true,
                AutoLinkOptions = new ExternalSignInAutoLinkOptions(true, new[] { Constants.Security.WriterGroupAlias })
                {
                    AllowManualLinking = true
                },
            });

            app.UseOpenIdConnectAuthentication(options);

        }
    }
}
```

**Closed by nikolajlauridsen** 2023-01-06 13:19 UTC
Labels: type/bug
