### ISSUE TITLE
Installation: Cannot access a disposed object. Object name: 'IServiceProvider'.

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#15125] opened 2023-11-03 09:05 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc1

### Bug summary

During installation of v13 RC1 I get the following error:

```
Error during installation
One or more errors occurred. (One or more errors occurred. (Cannot access a disposed object. Object name: 'IServiceProvider'.))

See the log for full details (logs can typically be found in the umbraco\Logs folder).
```
![image](https://github.com/umbraco/Umbraco-CMS/assets/1782524/c71dc06c-7123-4e52-81ce-70451319b324)

After restarting the app, the following error is thrown:

```
[10:04:31 ERR] Unhandled exception in AppDomain (terminating).
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: umbracoOpenIddictApplications'.M
```

### Specifics

I'm getting an error during a fresh installation, upgrading an existing site does not seem to yield the same error.

### Steps to reproduce

* Install dotnet SKD 8.0.100-rc.2.23502.2
* Install Umbraco.Templates (13.0.0rc1)
* `dotnet new umbraco -n MySite`
* `dotnet build`
* `dotnet run`
* Choose `SQLite` option and continue install.

### Expected result / actual result

Installer should work =D

**Comment by kjac** [comment] 2023-11-03 13:45
Hi @enkelmedia,

Thank you for testing the RC and for reporting this 💪 

Something must be up. I can't reproduce it, but it's been reported over here too: https://github.com/umbraco/Umbraco-CMS/issues/15090

I'm going to close this, so we can keep all communication on #15090 moving forward.

**Closed by kjac** 2023-11-03 13:45 UTC
Labels: type/bug
