### ISSUE TITLE
Umbraco - Content synchronisation problem on load balanced environment

### ISSUE THREAD

**Issue by JohnLHGeary** [umbraco/Umbraco-CMS#3222] opened 2018-10-09 15:06 UTC
### Bug summary

On occasion we find that when a user saves and publishes content within the Umbraco CMS it is not refreshing on all of our servers.  It is updating the umbraco.config on each of the servers but doesn't appear to force a refresh of the memory cache.  We often find that there is an IO error on the server around the time of the content save/publish.

We have had a few problems with the synchronisation between the servers after a network routing issue and then an upgrade of Umbraco. We have ironed out most of these faults out over time but can't get past this occasional one that is left. 

As this has been going on for sometime it is fairly high profile issue with the client.

### Specifics

Umbraco v7.9.0
We have three load balanced web servers and one database server (server 2012 R2).
Internal and external traffic access through URL's via the load balancer.
Particular users access the CMS via the IP address of the first web server.
This web server (WEB01) is for both the CMS and internal/external site access.
Each server IP is bound to the main site.
As well as the main site we have a smaller other site within the same instance.
Our App_Data directory is in a share that is syncronised between the 3 web servers but excludes TEMP and umbraco.config.
We define the web servers and CMS in the UmbracoSettings.config.  WEB01 is the first listed so should be the parent server.

We have the IO error examples attached.  Any help or guidance is much appreciated.  We are struggling to find anything that we haven't already review or tried.  

### Steps to reproduce

1. Client makes update
2. Saves and publishes
3. Checks each server and finds that content isn't visible on one
4. Although the content is in the Umbraco.config it doesn't refresh until an application pool restart in IIS
5. We often find IO errors about a missing or locked Examine Index file

### Expected result

Content refreshes onto each server shortly after user publishes.

### Actual result

On the example last Friday.  This refreshed onto 2 of the 3 servers.

[20181005 121723.txt](https://github.com/umbraco/Umbraco-CMS/files/2460966/20181005.121723.txt)
[20181005 121723_2.txt](https://github.com/umbraco/Umbraco-CMS/files/2460967/20181005.121723_2.txt)
[20181005 121723_3.txt](https://github.com/umbraco/Umbraco-CMS/files/2460968/20181005.121723_3.txt)

**Comment by nul800sebastiaan** [comment] 2018-10-22 17:02
Hey @JohnLHGeary - Unfortunately I'm going to have to close this as "can't reproduce" for now. We're not aware of other people having this problem and in order to be able to say something sensible about this we really need clearer steps to reproduce I'm afraid. 

Please make absolutely sure that you've followed all of the recommendations in the documentation to the letter: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible

One thing from that documentation: make sure the examine indexes are written to a local temp folder, not the shared drive.

I'd recommend you also leave a post on the forum to see if other people have similar problems and possible solutions. If there's anything that you can point to like: when I do "x" when there's a full moon and the clock is exactly at 12 past the hour then maybe we can deduce something from that.

**Closed by nul800sebastiaan** 2018-10-22 17:02 UTC

**Comment by JohnLHGeary** [comment] 2018-10-23 07:11
Hi,
It is a bit difficult to put down re-creation steps as it doesn’t happen every time and it is a general content synchronisation problem across our three web server set-up.  I have been through the flexible load balancing document and as far as I can see the environment is set-up as per the guidance and our indexes are written to the individual local drives.  We do have a sync running but it avoids TEMP and the umbraco.config.

I have previously posted on the forums regarding this and have followed that guidance with no luck.  The one main clue to the source I think was the error message I posted regarding the locked index files, is there any thoughts about what might be causing that or guidance on how we can get more information out of it.  I posted this as a bug as this has been ongoing for some time and although we have improved things it’s not ideal to go back to the client and say, this has been closed pending a recreation steps request which is going to virtually impossible to replicate and describe to sufficient detail.

Regards,

John Geary
IT Support Analyst

Capita Application Services

[cid:image001.png@01D1E0DF.7D8593D0]+44 (0) 7584 408198 (Mobile)
[cid:image002.png@01D1E0DF.7D8593D0]john.geary@capita.co.uk<mailto:john.geary@capita.co.uk>
[cid:image003.png@01D1E0DF.7D8593D0]www.capita.com<http://www.capita.com/>
    [cid:image004.jpg@01D1E0DF.7D8593D0]     [cid:image005.jpg@01D1E0DF.7D8593D0]  [cid:image006.png@01D1E0DF.7D8593D0]

PLEASE NOTE:
This email and its content is confidential and is intended for the exclusive use of the recipient to which it was addressed.
If you are not the addressee, any disclosure, reproduction, distribution or other dissemination or use of this email is strictly prohibited.
