### ISSUE TITLE
.Url(culture) not working with lowercase cultures

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11787] opened 2021-12-23 11:58 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

In our code we are encountering an issue that wasn't there in v8. We iterate on all the cultures of an item and then do .Url(culture) on it. However, the cultures returned from the item are in lowercase and apparently the .Url function doesn't allow lowercase cultures.

Using this to test:
![image](https://user-images.githubusercontent.com/11466511/147236954-7c0bc217-de53-4e21-b98c-56914eb0e6b8.png)
Returns this as result:
![image](https://user-images.githubusercontent.com/11466511/147236979-5dd74525-09b7-4a9a-ac45-d3160d7fa861.png)

So using something like this to render alternate urls:
![image](https://user-images.githubusercontent.com/11466511/147237111-e244df86-44b8-48fb-9cbe-e65147449674.png)
Doesn't work while this is something that worked in v8 at one point.

### Steps to reproduce

- Create a new v9 installation
- Create a new language
- Create a new document type with varied with culture enabled
- Create the page with both languages
- Set your domains up for both languages. I simply set it up as '/nl-nl' for Dutch and 'en-gb' for English.
- Use the snippet above to test the values

### Expected result / actual result

.Url should return the url even if the culture is all lower case.

**Comment by nul800sebastiaan** [comment] 2022-01-03 13:34
This seems to be a regression issue: https://github.com/umbraco/Umbraco-CMS/issues/11687

I'll close this one as a duplicate of #11687 - and we should look at what went wrong there.

**Closed by nul800sebastiaan** 2022-01-03 13:34 UTC
Labels: type/bug
