### ISSUE TITLE
Composition checkbox property always false until doctype is saved

### ISSUE THREAD

**Issue by hundebol** [umbraco/Umbraco-CMS#5224] opened 2019-04-10 12:31 UTC
A checkbox in a compostion will always return false until the doctype where the composition is included is saved again.

**Reproduce:**

1. Imagine having a doctype named "Home"
2. In this doc type you have a composition named "Settings"
3. Now add the Checkbox (or true/false) property to the "Settings" composition and save.
4. The Checkbox is now present and can be edited in a page with the doc type "Home", but no matter if true or false, it will always show false.

Solution: Save the doctype "Home" - and now the the checkbox value can actually be both true and false

This was tested in Umbraco 8.0.1 but has been there before, as I found this old thread which was Umbraco 7.4.1: https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/75326-truefalse-editor-always-returning-false  

### Expected result
I expected that the property would actually work, even though it was added via a composition.

### Actual result
The property always returned false, until I saved the doc type where the composition was added.

**Comment by Shazwazza** [comment] 2019-04-11 04:05
That does seem quite odd! Have marked as a bug and up for grabs to see if the community might be able to assist

**Comment by kjac** [comment] 2019-04-25 08:37
I dug a bit in this, and just to clarify a few things:

1. The issue happens while rendering the content, *not* in the backoffice - the composition property values are actually saved correctly.
2. This seems to happen for all composition properties (I have replicated with textbox and checkbox).

It's a caching issue. Something isn't flushed when the composition content type is updated, leaving Umbraco unaware of the added properties when rendering for frontend. If you do a restart of the site after adding new properties to the composition, everything works as expected.

Not sure if @zpqrtbnk has any pointers where to start on this?

**Comment by nul800sebastiaan** [comment] 2019-08-15 10:55
Thanks for the report and investigation. I've followed the steps above in v8.1.2 and can't reproduce any more so I am assuming this was fixed along the way.

**Closed by nul800sebastiaan** 2019-08-15 10:55 UTC
Labels: community/up-for-grabs, help wanted, type/bug
