### ISSUE TITLE
Callback url from external login provider longer than default max query length

### ISSUE THREAD

**Issue by ksolberg** [umbraco/Umbraco-CMS#13930] opened 2023-03-08 15:19 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

Sometimes the callback URL from an external login provider exceeds the max query length (2048). This will result in a 404.15 IIS error. This happened to me when using Microsoft Azure AD.

![image](https://user-images.githubusercontent.com/144644/223751302-98514f72-d1c8-4d73-8db7-180a0263777b.png)

### Steps to reproduce

1. Register an app in Azure AD
2. Configure login providers in Umbraco code as described in docs with clientid and secret from step 1
3. Insert default login macro that generates login form for registered login providers
4. Login and inspect callback url.

If it works, try different users. 

### Expected result / actual result

Expects that at least the documentation highlights this and describes how to deal with it.

**Comment by kjac** [comment] 2023-03-09 16:02
Hi there @ksolberg,

That sounds annoying! I can't recall having seen anything like this before for external login providers.

Your screenshot also raises a few questions:

1. Why does this only happen to some members (I assume we're talking members here, since you're logging in via macros)?
2. What is the `state` and `session_state` doing, and would you be in the clear query string length wise if they weren't there?
3. Which of these query string parameters is of varying length in between users?

It's tempting to conclude that your `state` and `session_state` are bound to the member somehow, and that the variation in query length has to do with these states. Perhaps you could look into that to start with?

**Comment by nikolajlauridsen** [comment] 2023-03-27 05:49
Hi @ksolberg 

We haven't heard back from you in 14 days, so I'll go ahead and close this issue, hope you got it resolved on your end, otherwise do not hesitate to comment here again and we can have another look at it 😄

**Comment by ksolberg** [comment] 2023-03-27 08:14
Nothing special, just straight from the docs. Not sure where state and session_state comes from. 

Login macro:

```
@inherits Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage

@using Umbraco.Cms.Web.Common.Models
@using Umbraco.Cms.Web.Common.Security
@using Umbraco.Cms.Web.Website.Controllers
@using Umbraco.Cms.Core.Services
@using Umbraco.Extensions
@inject IMemberExternalLoginProviders memberExternalLoginProviders
@inject ITwoFactorLoginService twoFactorLoginService
@{
    var loginModel = new LoginModel();

    // You can modify this to redirect to a different URL instead of the current one
    loginModel.RedirectUrl = null;

    var isLoggedIn = Context.User?.Identity?.IsAuthenticated ?? false;

    if (isLoggedIn) return;
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

@if (ViewData.TryGetTwoFactorProviderNames(out var providerNames))
{

    foreach (var providerName in providerNames)
    {
        <div class="2fa-form">
            <h4>Two factor with @providerName.</h4>
            <div asp-validation-summary="All" class="text-danger"></div>
            @using (Html.BeginUmbracoForm<UmbTwoFactorLoginController>(nameof(UmbTwoFactorLoginController.Verify2FACode)))
            {
                <text>
                    <input type="hidden" name="provider" value="@providerName" />
                    Input security code: <input name="code" value="" /><br />
                    <button type="submit" class="btn btn-primary">Validate</button>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                </text>
            }
        </div>
    }
}
else
{
    <div class="login-form">
        @{
            var loginProviders = await memberExternalLoginProviders.GetMemberProvidersAsync();
            var externalSignInError = ViewData.GetExternalSignInProviderErrors();

            if (loginProviders.Any())
            {
                if (externalSignInError?.AuthenticationType is null && externalSignInError?.Errors?.Any() == true)
                {
                    @Html.DisplayFor(x => externalSignInError.Errors)
                }

                @foreach (var login in await memberExternalLoginProviders.GetMemberProvidersAsync())
                {
                    @using (Html.BeginUmbracoForm<UmbExternalLoginController>(nameof(UmbExternalLoginController.ExternalLogin)))
                    {
                        <button class="btn btn-primary" type="submit" name="provider" value="@login.ExternalLoginProvider.AuthenticationType">
                            Logg inn med @login.AuthenticationScheme.DisplayName
                        </button>

                        if (externalSignInError?.AuthenticationType == login.ExternalLoginProvider.AuthenticationType)
                        {
                            @Html.DisplayFor(x => externalSignInError.Errors)
                        }
                    }
                }
            }
        }
    </div>
}
```

There's only one externalmemberloginproviders registered:

```
 public static class FrontendAuthenticationExtensions
    {
        public static IUmbracoBuilder ConfigureAuthenticationMembers(this IUmbracoBuilder builder)
        {
            builder.Services.ConfigureOptions<FrontendExternalLoginProviderOptions>();

            builder.AddMemberExternalLogins(logins =>
            {
                const string schema = MicrosoftAccountDefaults.AuthenticationScheme;

                logins.AddMemberLogin(
                    frontendAuthenticationBuilder =>
                    {
                            frontendAuthenticationBuilder.AddMicrosoftAccount(
                                // the scheme must be set with this method to work for the back office
                                frontendAuthenticationBuilder.SchemeForMembers(schema) ?? string.Empty,
                                options =>
                                {
                                    var config = builder.Config;
                                    var tenantId = config["Authentication:Frontend:TenantId"];

                                    options.CallbackPath = "/ad-frontend-signin";
                                    options.ClientId = config["Authentication:Frontend:ClientId"];
                                    options.ClientSecret = config["Authentication:Frontend:ClientSecret"];
                                    options.TokenEndpoint = $"https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token";
                                    options.AuthorizationEndpoint = $"https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize";
                                });
                        });
            });
            return builder;
        }
    }
```

And MemberExternalLoginProviderOptions:

```
public class FrontendExternalLoginProviderOptions : IConfigureNamedOptions<MemberExternalLoginProviderOptions>
    {
        public const string SchemeName = "Microsoft";

        private readonly IDataService _dataService;
        private readonly IMemberService _memberService;

        public FrontendExternalLoginProviderOptions(IDataService dataService, IMemberService memberService)
        {
            _dataService = dataService;            
            _memberService = memberService;
        }

        public void Configure(string name, MemberExternalLoginProviderOptions options)
        {
            if (name != Constants.Security.MemberExternalAuthenticationTypePrefix + SchemeName)
            {
                return;
            }

            Configure(options);
        }

        public void Configure(MemberExternalLoginProviderOptions options) =>

            options.AutoLinkOptions = new MemberExternalSignInAutoLinkOptions(
                // Must be true for auto-linking to be enabled
                autoLinkExternalAccount: true,

                // Optionally specify the default culture to create
                // the user as. If null it will use the default
                // culture defined in the web.config, or it can
                // be dynamically assigned in the OnAutoLinking
                // callback.
                defaultCulture: null,


                // Optionally specify the default "IsApprove" status. Must be true for auto-linking.
                defaultIsApproved: true,

                // Optionally specify the member type alias. Default is "Member"
                defaultMemberTypeAlias: "Member",

                // Optionally specify the member groups names to add the auto-linking user to.
                defaultMemberGroups: Array.Empty<string>()
            )
            {
                // Optional callback
                OnAutoLinking = (autoLinkUser, loginInfo) =>
                {
                    // You can customize the member before it's linked.
                    // i.e. Modify the member's groups based on the Claims returned
                    // in the externalLogin info
                    //autoLinkUser.AddRole("Employee");
                },
                OnExternalLogin = (user, loginInfo) =>
                {
                    // You can customize the member before it's saved whenever they have
                    // logged in with the external provider.
                    // i.e. Sync the member's name based on the Claims returned
                    // in the externalLogin info

                    return true; //returns a boolean indicating if sign in should continue or not. (Ps. Member will still be created)
                }
            };
    }
```

And here's startup.cs

```
public void ConfigureServices(IServiceCollection services)
        {
            services.ConfigureOptions<BackendExternalLoginProviderOptions>();
            services.ConfigureOptions<FrontendExternalLoginProviderOptions>();

            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .AddAzureBlobMediaFileSystem()
                .ConfigureAuthenticationBackend()
                .ConfigureAuthenticationMembers()
                .Build();

            services.AddApplicationInsightsTelemetry();
        }
```

**Comment by ksolberg** [comment] 2023-04-05 17:43
Why does this only happen to some members (I assume we're talking members here, since you're logging in via macros)?

Not sure, but it has only happened with my personal google account that was invited to the AD directory. 

What is the state and session_state doing, and would you be in the clear query string length wise if they weren't there?

No idea what state and session_state is for. Nothing I have added.

Which of these query string parameters is of varying length in between users?

As far as I can remember, and from what it seems from my screenshot it is 'code'.

**Comment by Migaroez** [comment] 2024-07-11 11:28
Hey @ksolberg I know it has been a long while but I might have an insight into this issue if it is still relevant

All parameters passed onto the callback are generated by the external provider. 
About a month before you posted this issue, Microsoft released a blog post regarding the increase in the code parameter length increase
https://techcommunity.microsoft.com/t5/microsoft-entra/azure-ad-b2c-authorization-code-and-refresh-token-size-increase/m-p/3770890
Since then it has been marked obsolete as, I presume, they reverted or optimized the change.

If you are still having issues with this, I would advice you to look at the mitigations listed in the post.

I will be closing this issue as the cause/solution both seem to be outside of Umbraco's influence in the mvc/auth pipeline.

**Closed by Migaroez** 2024-07-11 11:28 UTC
Labels: state/needs-more-info, type/bug
