### ISSUE TITLE
Tour 3 recurring issue on step 3/4

### ISSUE THREAD

**Issue by cpboyd** [umbraco/Umbraco-CMS#16268] opened 2024-05-11 20:04 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

Created brand new dotnet project from template.
Followed the first 2 tours, copying+pasting sample text exactly.
After clicking the 3 dots on step 3 of tour 3, I get the `Oh, we got lost!` error.

### Specifics

I've double-checked that everything from the first 2 tours matched as expected (and specifically `Allow as root`)

### Steps to reproduce

1. Created brand new dotnet project from template.
2. Followed the first 2 tours, copying+pasting sample text exactly.
3. After clicking the 3 dots on step 3 of tour 3, I get the `Oh, we got lost!` error.

### Expected result / actual result

Should be able to proceed, but even better would be the option to skip specific steps and/or tours.

I can't even start tour 4 without finishing tour 3 and Googling indicates this is a recurring issue:
https://our.umbraco.com/packages/starter-kits/the-starter-kit/feedback/94137-getting-started-tour
https://our.umbraco.com/forum/using-umbraco-and-getting-started/90616-tour-issue

**Comment by NguyenThuyLan** [comment] 2024-07-22 03:32
Hi @cpboyd , thanks for reporting this.
Unfortunately, I couldn't reproduce this issue. As you can see in this video below I reproduced step 3 on v13.4.1

https://github.com/user-attachments/assets/c06c1270-a2ed-4bea-879f-56e3c9b9a616

Btw, we should not skip steps/tours because the after-tours need sources created previously. I will close this issue because I couldn't reproduce it. Feel free to reopen it if you have any more details 😊

**Closed** 2024-07-22 03:32 UTC
Labels: type/bug
