### ISSUE TITLE
Scheduling displays "Invalid date" in Umbraco 12.3.1

### ISSUE THREAD

**Issue by matteus-hemstrom-nltg** [umbraco/Umbraco-CMS#15202] opened 2023-11-14 15:08 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

When upgrading to Umbraco 12.3.0 we found that the scheduling function stopped working. We have since then upgraded to 12.3.1 hoping that it would resolve our issue as it is addressed in the release note "Scheduling Posts gives invalid date in Umbraco 12.3". Unfortunately, we still have an issue with the scheduling modal. The date picker still show "invalid date" in the scheduling modal.

### Specifics

Note that this seems to be a frontend issue only, because if one proceed to schedule the document with "invalid date", the document will still be scheduled and published according to the date and time that was selected.

I have tracked the issue down to the following code:
- `formatDatesToLocal` in schedule.controller.js, see https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.controller.js#L279-L286
- `getLocalDate` and `convertToLocalMomentTime` in util.service.js, see https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Web.UI.Client/src/common/services/util.service.js#L78-L117

The date returned from `convertToLocalMomentTime` is not valid (e.g. `'Nov 14th 2023, 13:08-00:00'`).

I have also found it works if I modify `Umbraco.Sys.ServerVariables.application.serverTimeOffset` so that `serverTimeNeedsOffsetting` is evaluated to `false`. However, I'm not sure if that will cause timezone issues when publishing. This means that you need to have a different server time zone than your browser to reproduce the issue. The issue is therefore likely not reproducible locally because the server and browser will use the same time zone.

### Steps to reproduce

I think you diff in server timezone and browser timezone to trigger the issue, then:

1. Open the scheduling modal by clicking "Schedule..."
2. Select a date using the date picker
3. Notice that the date picker button now shows "Invalid date"

### Expected result / actual result

The selected dates should be visible in the scheduling modal.

**Comment by bergmania** [comment] 2023-11-14 15:17
Hi @matteus-hemstrom-nltg 

What version did you update from? That could make it easier to find the root cause?

**Comment by matteus-hemstrom-nltg** [comment] 2023-11-14 15:22
> Hi @matteus-hemstrom-nltg
> 
> What version did you update from? That could make it easier to find the root cause?

We think that it was working on 12.2.0.

**Comment by andr317c** [comment] 2023-11-15 10:06
Hey! Thanks for reporting this issue, I was able to reproduce it on versions 12.3.1 and 12.3.0. I followed the reproduction steps by changing my browser timezone to a different one than the server, which led me to:
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/f36f78b1-4089-46e6-99c4-bd0d31a72e45)

I tested it on version 12.2.0 and it worked without any issues, so the issue occurred between 12.2.0 and 12.3.0
I will mark this issue as a sprint candidate

**Comment by andr317c** [comment] 2023-11-15 10:11
The issue also occurs on version 13.0.0-rc2

**Comment by rongrisnich** [comment] 2023-11-15 11:58
Facing the same issue on Umbraco Cloud with 12.3.1.

**Comment by andr317c** [comment] 2023-11-16 07:55
Hey @bjarnef 
This issue seems to be caused by this PR #13500. Could you maybe have a look into it? 😄

**Comment by matteus-hemstrom-nltg** [comment] 2023-11-16 08:12
> Hey @bjarnef This issue seems to be caused by this PR #13500. Could you maybe have a look into it? 😄

Just looking at that PR, it seems like `parsingFormat` should be passed to `convertToLocalMomentTime` instead of `format`:
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/common/services/util.service.js#L111

**Comment by bjarnef** [comment] 2023-11-16 08:35
@matteus-hemstrom-nltg no, I don't think that is correct.

Before it didn't sent in format to this.
https://github.com/umbraco/Umbraco-CMS/pull/13500/files#diff-277b13396c90722385a98d599dbfea84855ff088949d00d4b5d14259208ed034R111

which used the format `YYYY-MM-DDTHH:mm:ss` by default. Parsing format is different `YYYY-MM-DD HH:mm:ss` and used when one know a specific format of a datetime and want to convert that.

I think the issue it that where `getLocalDate()` is called different format is passed in, e.g. `LLL` or `MMM Do YYYY, HH:mm"`, but the format in moment is used how the date should be formatted, which is also used in the end.
https://github.com/umbraco/Umbraco-CMS/pull/13500/files#diff-277b13396c90722385a98d599dbfea84855ff088949d00d4b5d14259208ed034R115

**Comment by bjarnef** [comment] 2023-11-16 08:37
I don't think `format` should be passed in here:
https://github.com/umbraco/Umbraco-CMS/pull/13500/files#diff-277b13396c90722385a98d599dbfea84855ff088949d00d4b5d14259208ed034R111

at least the format before was `YYYY-MM-DDTHH:mm:ss`.

**Comment by bjarnef** [comment] 2023-11-16 08:54
@andr317c any change you can test with this PR? https://github.com/umbraco/Umbraco-CMS/pull/15223

**Comment by andr317c** [comment] 2023-11-16 09:38
Hey @bjarnef 
I just tested your PR and it works! I'll go ahead and merge it in contrib 😄 

And I'll close this issue.

**Closed by andr317c** 2023-11-16 09:38 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v12, affected/v13
