### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by bourpie** [umbraco/Umbraco-CMS#13713] opened 2023-01-20 19:35 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

9.2.0

### Bug summary

Error while trying to upgrade from 9.2.0 to 10.3.2.

### Specifics

I don't need to upgrade to 9.2.0 ! I'm already in 9.2.0. I need to go to 10.3.2
![image](https://user-images.githubusercontent.com/4865432/213788596-fa1f0807-c8a6-4bfc-bc09-92b689d75fe3.png)

Error
![image](https://user-images.githubusercontent.com/4865432/213788425-0790110c-2555-4f1d-bc84-4c868b223506.png)

From the log:
`{"@t":"2023-01-20T14:25:36.0569003Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\\Inetpub\\web\\app_documentation\\umbraco\\Data\\TEMP\\DistCache\\ad114eca32827dcb6b99639c2e2cb8200c8a55e3-lastsynced.txt'.\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\r\n   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\r\n   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)\r\n   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)\r\n   at System.IO.File.WriteAllText(String path, String contents)\r\n   at Umbraco.Cms.Infrastructure.Sync.LastSyncedFileManager.SaveLastSyncedId(Int32 id)\r\n   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync()\r\n   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync(Object state)","SourceContext":"Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask","ProcessId":7948,"ProcessName":"w3wp","ThreadId":131,"ApplicationId":"f45c7161b0790663dce3d045410fe24d3f8cadcc","MachineName":"SRVIISSTG111","Log4NetLevel":"ERROR"} `

### Steps to reproduce

1. In localhost, upgrade from 9.2.0 to 10.3.2
2. Run the installer
3. Test locally : OK
4. Publish the project to another environment that runs Umbraco 9.2.0
5. Run installer to this environment
6. Error in detecting the current version : tries to upgrade to 9.2.0
7. Click to upgrade : "The database failed to upgrade. ERROR: The database configuration failed with the following message: The migration plan does not support migrating from state "{AD3D3B7F-8E74-45A4-85DB-7FFAD57F9243}"."

### Expected result / actual result

Expected result : Successful upgrade to 10.3.2

**Comment by Zeegaan** [comment] 2023-01-23 12:03
Hey @bourpie and thanks for reporting! This is a hard one to reproduce, as this works just fine for me 🤔 
Your screenshots help a lot here, seems like you are on 9.2 (AD3D3B7F-8E74-45A4-85DB-7FFAD57F9243) on the error screen.
But in the upgrade screen, it claims you are already on 10.2 (79D8217B-5920-4C0E-8E9A-3CF8FA021882) so that's a weird one 🤔 Could i get you to send me a screenshot of your `umbracoKeyValue` table in the database? I'm specifically looking for what state you are in: 
![image](https://user-images.githubusercontent.com/70372949/214035184-c1c076dc-67c6-427c-ad3b-21fb797f747b.png)

**Comment by bourpie** [comment] 2023-01-23 14:23
Thank you @Zeegaan. Here's a screenshot of my umbracoKeyValue table in the database

![image](https://user-images.githubusercontent.com/4865432/214062691-c4892c58-feeb-4b1b-b3e5-106b2ce9ec53.png)

**Comment by Zeegaan** [comment] 2023-01-26 10:34
Hey @bourpie Hmm seems right, I cannot reproduce this on my end 🤔 
From your screenshot: 
![image](https://user-images.githubusercontent.com/70372949/214814600-b003f613-a279-459e-bbe4-051a75c712f8.png)

It seems to me that you have already upgraded the database, but have the old 9.2 DLL's somehow 🤔 And therefore it tries to "upgrade" to the 9.2 version from 10.2 which is not supported

I'd recommend following this guide: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific#steps-to-upgrade-using-visual-studio

Or reaching out on the forum or discord for help. 

As we cannot reproduce this, I have to close the issue, feel free to re-open if you find some reproduction steps 🐛 

Thanks again for reporting 😊

**Closed by Zeegaan** 2023-01-26 10:34 UTC
Labels: state/needs-investigation, type/bug
