### ISSUE TITLE
Umbraco.Slider does not accept negative values

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#14591] opened 2023-07-22 15:37 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

Umbraco.Slider does not accept negative values such as -10 -20 -30 etc...

### Specifics

If you wish to have 0 in the middle then add positive to the right and negative to the left it crashes the backoffice

### Steps to reproduce

Add number with a - in front of them as the values

### Expected result / actual result

You should be able to use negative values

**Comment by kjac** [comment] 2023-07-24 06:15
Hi @deanleigh,

I'm afraid I can't reproduce this. I have tried V10 and V11, with and without step increments. It seems to just work:

[14591.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/9297af97-e1a8-4ad2-9f4e-090ca044cfea)

Could you please elaborate on the steps to reproduce the issue?

**Comment by deanleigh** [comment] 2023-07-24 06:29
OK so a few extra steps may be required to reproduce.
I have the slide as a property in an Element Type.
![image](https://github.com/umbraco/Umbraco-CMS/assets/6745929/05aa921c-41ad-4610-ba77-cb621c0129b2)
The Element Type is used in a composition in another Element Type
![image](https://github.com/umbraco/Umbraco-CMS/assets/6745929/cd835055-ce63-4b6f-8955-94a545a00fcc)
This is then used as the Settings in a Block in Block Grid
![image](https://github.com/umbraco/Umbraco-CMS/assets/6745929/6729a30d-2f4a-4cad-aac5-81f68d601fcc)
However, I was unable to save the slider without crashing the browser in the original element type with the following settings
![image](https://github.com/umbraco/Umbraco-CMS/assets/6745929/674b15d1-5964-47a6-b2e4-f8579d4e911d)

**Comment by kjac** [comment] 2023-07-25 05:15
Hi again @deanleigh,

Now I get it. And I am able to reproduce.

The culprit is your configuration. The negative step increments cause the majority of the problem. After all, it's not possible to _increment_ with a negative value 😄 

Your minimum and maximum values are also off, so the slider will still misbehave after fixing the step increments. The maximum value must be the biggest for the slider to work.

This configuration should work for you:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/b21cf799-d600-461b-8579-e6042c2d9888)

It is of course pretty bad that a misconfiguration can crash the entire backoffice. Unfortunately we don't have a lot of options for configuration validation at this point, but I'll look into a fix that will ensure no backoffice crashses.

**Comment by deanleigh** [comment] 2023-07-25 05:21
I was using the - as a separator so I added that to the code instead of in the configuration.
This is not urgent for me and is probably an edge case so possibly not urgent overall.
However as you say the fact it crashes the whole back office doesn't look good for the CMS.
I would suggest for example this is less important than being able to set default values for radio buttons and checkboxes and select menus.
Thank you for looking into it and confirming the issue.

**Comment by kjac** [comment] 2023-07-25 05:30
PR to amend this in https://github.com/umbraco/Umbraco-CMS/pull/14601

**Comment by kjac** [comment] 2023-07-25 06:54
Fixed in #14601 - thanks again for reporting this 💪

**Closed by kjac** 2023-07-25 06:54 UTC
Labels: state/in-sprint, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11, affected/v12, release/12.1.0, release/10.7.0
