### ISSUE TITLE
Macro in RTE issue in IE v11

### ISSUE THREAD

**Issue by ranjit0829** [umbraco/Umbraco-CMS#3235] opened 2018-10-10 10:02 UTC
Hello,

Macro in RTE issue and on edit RTE is fully disabled. 

Reproduction
------------

Reference Link: https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/67322-issue-with-macro-in-rte#comment-297595 

### Specifics

    * Umbraco version: v7.10.4
    * Browser IE v11
    * FF and Chrome works well
    * Screen shot attached

### Steps to reproduce

1. Add a macro in rte with couple of text fields
2. Insert macro with values and save and publish
3. revisit the macro in rte and try to edit values in text box
4. Usually macro has a yellow box, now 2 yellow boxes appears
5. Rte completely disabled

### Expected result

macro values should be updated and rendered via RTE

### Actual result

RTE is disabled in dashboard due to css class "mceNonEditable".

Kindly suggest!

Thanks,
Ranjit J. Vaity

**Comment by nul800sebastiaan** [comment] 2018-11-20 16:03
Oh no, that sounds annoying.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Matthew-Wise** [comment] 2019-01-19 17:19
The cause is because there is nothing else for the cursor to target as the the full RTE is the macro.

Interestingly if you use the arrow/enter/backspace/delete keys it creates a p tag and you can continue typing beneath the macro.

Only thing I can think of doing is adding an additional key press watch on the macro container, to repeat the action.

**Comment by CharLUON** [comment] 2019-03-12 14:19
Have the same issue in IE11 (version: 11.523.17134.0)

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:30
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:30 UTC
Labels: community/up-for-grabs, help wanted, type/bug

**Comment by Myster** [comment] 2019-06-26 04:45
Shouldn't the issue be open if it's not fixed? 
I just came across this issue in a project.

**Comment by nul800sebastiaan** [comment] 2019-06-26 06:39
We're happy to re-open when a PR comes in to fix it. :-)
