### ISSUE TITLE
Access Error for Specific User Group Member

### ISSUE THREAD

**Issue by martinthogersen** [umbraco/Umbraco-CMS#17496] opened 2024-11-12 08:24 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

I've created a new user and assigned them to a new user group, with permissions configured as shown in the image:

![image](https://github.com/user-attachments/assets/66e40dac-4aeb-43cb-a5ba-c6fe9dec18b9)

Additionally, I set up a custom member type and created a member instance of this new type. My administrative account can access this new member without any issues. However, when the new user (from the newly created user group) attempts to access the same member, the XHR request to retrieve the member type redirects back to the login page.

Below is a side-by-side comparison of the network requests:

![image](https://github.com/user-attachments/assets/2467e36f-14e8-4ce6-900e-77d81f5286a8)

In the left panel (with the dark background), we see the new user's request to /umbraco/management/api/v1/member-type/ee4f93c6-9db3-4407-8699-ef5206faf554 returning an HTTP 302 response instead of the expected HTTP 200.

### Steps to reproduce

See above.

---
_This item has been added to our backlog AB#46441_

**Comment by NguyenThuyLan** [comment] 2024-11-21 07:19
Thank @martinthogersen for reporting this issue 🐞
This bug happens on both v14.3.1 and v15.0.0, APIs that get members' information have the status code Forbidden
<img width="590" alt="image" src="https://github.com/user-attachments/assets/b2b53be6-1ce6-489a-bf8e-ef9160502010">

**Comment by kjac** [comment] 2024-11-27 13:43
Hi @martinthogersen,

Thank you for reporting 👍 

This looks like a duplicate of #17339 which is solved in #17440. I also can't reproduce this on the latest V15, so I believe it's fixed 😄

**Closed by kjac** 2024-11-27 13:43 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/backend, affected/v14, affected/v15

**Comment by martinthogersen** [comment] 2024-11-27 14:10
@kjac Thank you. Could you release a fix for Umbraco 14 as well, please?

**Comment by kjac** [comment] 2024-11-28 11:55
Hi @martinthogersen,

V14 will likely not receive anymore updates except of course security patches, as it has entered the "Support phase". See https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/ for details.
