### ISSUE TITLE
UX: Show type dialog for nested content if paste-option(s) is available

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6311] opened 2019-09-09 12:27 UTC
In relation to the new Copy/Paste feature for properties( https://github.com/umbraco/Umbraco-CMS/pull/5706 ),  there is an UX-issue in regards to Nested Content with only one Element-Type available.

With the current solution the Element-Type picker dialog only appears if you have multiple types to pick from. meaning the the paste option only works on Nested-Content properties that has multiple element type to pick from.

My suggestion would be to make a check when clicking "Add content", that figures out if there is any possible paste-options available, if so, showing the dialog, so you can paste.

I hope it makes sense, thanks.

**Comment by kjac** [comment] 2019-09-09 18:02
@nielslyngsoe good to see you back! 

I'm afraid I can't reproduce this; it seems to me like NC does exactly what you're asking already:

![nc-copy-single-item-config](https://user-images.githubusercontent.com/7405322/64554951-a4eced80-d33c-11e9-8b4e-ac3e4c2187f2.gif)

**Comment by nul800sebastiaan** [comment] 2019-09-26 09:20
I can't repro either, let's close this for now :)

**Closed by nul800sebastiaan** 2019-09-26 09:20 UTC
