### ISSUE TITLE
Multiple nestedcontent queries gives incorrect result.

### ISSUE THREAD

**Issue by Appstract-fjellvang** [umbraco/Umbraco-CMS#7040] opened 2019-11-01 13:29 UTC
Hi.

We have an issue one one of our sites. We have a parent document type, where all of its children document types have a list of nested content. From the parent object we want to display all the children and their nested content, but alot of the children documents display identical data, even though they have unique data saved and published.

Reproduction
------------

Create an element type with 5 properties:

- Title, textstring

- Number, textstring

- isNumberPercentage, boolean

- average, textstring

- color - approver color picker (set black and red as the two approved colors)

Create a Data type, nested content using this element type.

Create a "Library document type" i called it news area, with various properties.

Create a news item document type, various properties but be sure to add your nested content to this, i called the property "Statistics". Add this is an allowed child of the library document type.

Create the library in the content tree and create a few news items. i created 11. on each of these 11 news articles i create atleast 3 nested content items. I created 3 on all of them.

Ensure that  all the data on the nested contents are unique.

Print out the data in the template for the news area library item. I have the following code:
![image](https://user-images.githubusercontent.com/46595925/68027623-1b5dfa00-fcb3-11e9-9547-939331d7de1f.png)

Notice you will get duplicate data in the view:
![image](https://user-images.githubusercontent.com/46595925/68027720-61b35900-fcb3-11e9-81b0-77f4a67f7426.png)

i've highlighted the duplicate data in orange, and the individual news item in purple, lightblue and green respectivly.

if i for instance inspect "News (1) (2) (1)" its clear that different data should be displayed:
![image](https://user-images.githubusercontent.com/46595925/68027821-a7702180-fcb3-11e9-8e6a-2be9f47a46f6.png)

I've tried to republish and change the data. To no avail.

My guess is that its the umbraco cache that somehow gets previous entries when querying multiple nested contents in one request.

We initially encountered the error in a different production environment running umbraco 8.2.2. The above example is recreated in a dummy project running 8.1.5

**Comment by stevemegson** [comment] 2019-11-01 15:01
I think this is being caused by #5913. When you copy a page, the nested items in the copy have the same keys as the originals. The caching is based on the key, so you end up seeing previous items wrongly returned from cache.

**Comment by nul800sebastiaan** [comment] 2019-11-04 07:40
@Appstract-fjellvang Can you confirm that this scenario works with a few test pages where you haven't copied them?

**Comment by Appstract-fjellvang** [comment] 2019-11-04 09:02
@nul800sebastiaan seems like thats the case. We'll disable our customers ability to copy nodes

**Comment by Appstract-fjellvang** [comment] 2019-11-04 14:42
Can you let us know when it is fixed?

**Comment by nul800sebastiaan** [comment] 2019-11-05 14:25
Make sure to follow the progress on #5913 - we're working on this in the next few weeks but I don't have an exact date yet. I've close this one as a duplicate of #5913.

**Closed by nul800sebastiaan** 2019-11-05 14:25 UTC
