### ISSUE TITLE
Large amount of tags result in error [String or binary data would be truncated in table 'umbraco.dbo.umbracoPropertyData']

### ISSUE THREAD

**Issue by bakx** [umbraco/Umbraco-CMS#10358] opened 2021-05-29 20:58 UTC
### Which Umbraco version are you using?

9.0 beta 3

### Bug summary

When storing the TAG type as JSON, it seems that the database field backing it has a limit set. 
When adding lots of tags, a SQL error gets produced.

A work around is storing the data as CSV.

### Specifics

An error occurred

```
String or binary data would be truncated in table 'umbraco.dbo.umbracoPropertyData', column 'varcharValue'. Truncated value: '["Aland Islands","Albania","Andorra","Bahrain","Bangladesh","Belarus","Bolivia","Bosnia and Herzegov'. The statement has been terminated.
Exception Details
System.Data.SqlClient.SqlException, System.Data.SqlClient, Version=4.6.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: String or binary data would be truncated in table 'umbraco.dbo.umbracoPropertyData', column 'varcharValue'. Truncated value: '["Aland Islands","Albania","Andorra","Bahrain","Bangladesh","Belarus","Bolivia","Bosnia and Herzegov'. The statement has been terminated. 

```

### Steps to reproduce

Create a document type that has a tag type.
Create content from the document type.
Enter a lot of tags (e.g., 45+ countries).
Press save

### Expected result / actual result

I expected the page to save successfully.

**Comment by nul800sebastiaan** [comment] 2021-05-31 08:13
This is an issue carried over from v8, I'll close this as a duplicate of: https://github.com/umbraco/Umbraco-CMS/issues/8468

**Closed by nul800sebastiaan** 2021-05-31 08:13 UTC
Labels: project/v9, type/bug
