### ISSUE TITLE
U8 (8.1.0 Cloud) - Can't add or edit approved color

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#5985] opened 2019-07-23 18:39 UTC
Dear all,

When I try to add or edit a color in my approved colors list, the default value field (#000000) behaves like read-only, can't click on it to change the value.

![2019-07-23_22-36-41](https://user-images.githubusercontent.com/14230396/61738178-c0a33100-ad9a-11e9-8b5f-86e9f04e49f8.png)

**Comment by kjac** [comment] 2019-07-23 20:05
Humm... on my local install it works as expected:

![image](https://user-images.githubusercontent.com/7405322/61743539-cb0efc00-ad95-11e9-9a26-2501153b54c9.png)

What browser are you using? 

Could you try force reloading your client, or maybe log in to Umbraco in incognito mode to force a refresh?

**Comment by Baracuda011** [comment] 2019-07-23 20:31
@kjac tried all the above. Both on Development environment in the Cloud and on my local copy, which is a clone of Dev.

This was working weeks ago when I initially created the list. But today I needed to update some of the hexa values and that's how I discovered this.

**Comment by kjac** [comment] 2019-07-24 06:19
@Baracuda011 I tried a fresh 8.1 install from nuget, suspecting this might be a production JS build issue. I still can't reproduce your issue.

Do you see any console errors?

**Comment by Baracuda011** [comment] 2019-07-25 05:41
@kjac apologies for the late reply. Handling a super tight deadline :)

Here is the screenshot:

![2019-07-25_09-40-03](https://user-images.githubusercontent.com/14230396/61848804-600e1400-aec0-11e9-9c15-e53ca9b45b4c.png)

**Comment by nul800sebastiaan** [comment] 2019-07-25 05:42
@Baracuda011 I also had a go on Cloud and that all seems to work as well:

![image](https://user-images.githubusercontent.com/304656/61848721-5def8980-aeaf-11e9-8b2c-1720c6f9b195.png)

There is something else going on for you as well, this toggle does not look right, the white circle is a bit too low:

![image](https://user-images.githubusercontent.com/304656/61848779-84adc000-aeaf-11e9-8820-387e5fdb3c89.png)

I would be inclined to say that you have some custom code in your site that is conflicting with Umbraco. Like @kjac suggests: look for console errors etc. 

In any case, it's working correctly in Umbraco so I'm afraid I'm going to have to close this one. Make sure to [post on the forum](https://our.umbraco.com) for more help with this!

**Closed by nul800sebastiaan** 2019-07-25 05:42 UTC

**Comment by Baracuda011** [comment] 2019-07-25 05:46
@nul800sebastiaan please check my screenshot.

**Comment by nul800sebastiaan** [comment] 2019-07-25 05:52
@Baracuda011 Yeah I've just seen. Something is going on. :-)

I would do a compare (I love BeyondCompare for this, with these settings applied [BCSettings20190725.zip](https://github.com/umbraco/Umbraco-CMS/files/3429893/BCSettings20190725.zip)) of your current site to a clean zip of 8.1.0 and see what might be different for you, it might give some clues.

**Comment by Baracuda011** [comment] 2019-07-25 06:14
@nul800sebastiaan BC is a brilliant tool and a life saver.

Sure, I will download a clean 8.1.0. Tell me please which folders you want me to focus on?

**Comment by Baracuda011** [comment] 2019-07-26 10:35
@nul800sebastiaan can you please tell me what to check and compare? Thanks.

**Comment by stevemegson** [comment] 2019-07-26 12:02
@Baracuda011 I'd start with `/Umbraco/lib/spectrum`. The simplest cause of that error would be spectrum.js not loading correctly. Maybe also check that spectrum.js is showing up in the Sources tab of DevTools.

**Comment by Baracuda011** [comment] 2019-07-28 02:53
Hi @stevemegson, I have compared the folders, everything's identical. But, as you suggested, spectrum.js in not showing up in the console.

Is it also worth to mention that this is an Umbraco Cloud project which started literally on day 1 when U8 was released.

Thanks.

![2019-07-28_06-50-48](https://user-images.githubusercontent.com/14230396/62001557-74dae980-b104-11e9-9f15-1d75e87fac44.png)

**Comment by Baracuda011** [comment] 2019-07-31 02:28
@stevemegson @nul800sebastiaan can we please reopen this issue? Thank you.
