### ISSUE TITLE
Startup error after configuring blob storage

### ISSUE THREAD

**Issue by cadehymer** [umbraco/Umbraco-CMS#14452] opened 2023-06-23 15:57 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc4

### Bug summary

On a clean install of 12.0.0-rc4, after adding configuration for Azure blob storage, application throws an error during startup.

### Specifics

An error occurred while starting the application.
TypeLoadException: Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Unknown location

ReflectionTypeLoadException: Could not load all types from "Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService: Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)

Loader Exceptions:
Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
TypeLoadException: Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Show raw exception details
ReflectionTypeLoadException: Could not load all types from "Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping: . System.TypeLoadException on Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService: Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. Method 'ExecuteQuery' in type 'Umbraco.Cms.Api.Delivery.Services.ApiContentQueryService' from assembly 'Umbraco.Cms.Api.Delivery, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses, Func<Type, bool> additionalFilter)
Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses)
Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType<T>(ITypeFinder typeFinder, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses)
Umbraco.Cms.Core.Composing.TypeLoader+<>c__DisplayClass21_0<T>.<GetTypes>b__0()
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypes<T>(bool cache, IEnumerable<Assembly> specificAssemblies)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
ICO.Web.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            services.AddUmbraco(_env, _config)
System.RuntimeMethodHandle.InvokeMethod(object target, Void** arguments, Signature sig, bool isConstructor)
System.Reflection.MethodInvoker.Invoke(object obj, IntPtr* args, BindingFlags invokeAttr)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, object instance)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass14_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
Microsoft.Extensions.Hosting.HostBuilder.Build()
Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
ICO.Web.Program.Main(string[] args) in Program.cs
+
            => CreateHostBuilder(args)

Show raw exception details
.NET 7.0.7 X64 v7.0.0.0    |   Microsoft.AspNetCore.Hosting version 7.0.5+d47e49e9c1e173ac90821f7e89cc38e710274241    |    Microsoft Windows 10.0.19045    |   [Need help?](http://go.microsoft.com/fwlink/?LinkId=517394)

### Steps to reproduce

Create a new vanilla project as described [here](https://docs.umbraco.com/umbraco-cms/v/12.latest/test-the-release-candidate).
Setup blob storage as described [here](https://docs.umbraco.com/umbraco-cms/extending/filesystemproviders/azure-blob-storage).
Run the project.

**Comment by kjac** [comment] 2023-06-26 14:54
Hi @cadehymer,

Thanks for reaching out 👏 

I can't really reproduce this. But if you're following the docs for the storage providers exactly to the point, I do suspect you might have a version conflict.

You must install the latest RC versions of `Umbraco.StorageProviders.AzureBlob` and `Umbraco.StorageProviders.AzureBlob.ImageSharp` to test them with Umbraco 12.0.0-rc4. At the time of writing, you need:

```bash
dotnet add package Umbraco.StorageProviders.AzureBlob --version 12.0.0-rc3
dotnet add package Umbraco.StorageProviders.AzureBlob.ImageSharp --version 12.0.0-rc3
```

As mentioned I can't reproduce this so I'm going to close it as a non-issue. If you keep experiencing problems with the storage providers, please don't hesitate to reopen the issue with additional steps to reproduce 😄

**Closed by kjac** 2023-06-26 14:54 UTC
Labels: type/bug
