### ISSUE TITLE
Cannot change password of user in backoffice using Edge

### ISSUE THREAD

**Issue by raulribeiro** [umbraco/Umbraco-CMS#3440] opened 2018-10-25 10:36 UTC
Cannot change password of user in backoffice using Edge, email required
Umbraco version 7.12.3 assembly: 1.0.6837.12334

https://user-images.githubusercontent.com/6097393/47494686-2aad9a80-d84a-11e8-8933-20a030cda3ee.png

**Comment by nul800sebastiaan** [comment] 2018-10-25 13:38
Seems related to this one? https://github.com/umbraco/Umbraco-CMS/issues/3071

**Comment by kjac** [comment] 2018-10-26 06:38
I think I've found the cause of this... will submit a PR sometime later or this weekend.

Curious note: It works fine in V8. Maybe it's an angular version issue. But the fix I've found should work fine in V8 as well.

**Comment by kjac** [comment] 2018-10-27 06:19
Fix in #3456

**Comment by nul800sebastiaan** [comment] 2018-10-30 16:19
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3456

**Closed by nul800sebastiaan** 2018-10-30 16:19 UTC
