### ISSUE TITLE
Cancel Content Page Deletion: Delete Slideout Keeps Spinning

### ISSUE THREAD

**Issue by reneemhaas-diagram** [umbraco/Umbraco-CMS#12725] opened 2022-07-21 14:49 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

When canceling deletion of a content page through TrashingEvent/ContentService.Trashing the slideout on the CMS keeps spinning suggesting to content editors that its still processing.

### Steps to reproduce

1. Implement a trashing content service event https://our.umbraco.com/documentation/reference/events/contentservice-events/
2. In the service cancel the deletion and display an event message

`e.Cancel = true; EventMessage message = new EventMessage("Not Deleted", "This page has not been deleted.", EventMessageType.Error); e.Messages.Add(message);`

From the CMS go to a content page and try to delete.

![Child Pages Delete Test](https://user-images.githubusercontent.com/67076986/180243805-d4de3edd-2efc-44f1-8490-763731bdeb0d.jpg)

### Expected result / actual result

Expected result: The spinner stops and the slide out closes.
Actual result: The spinner keeps spinning and nothing changes.

**Comment by nul800sebastiaan** [comment] 2022-07-21 15:09
Thanks I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9614

**Closed by nul800sebastiaan** 2022-07-21 15:09 UTC
Labels: type/bug
