### ISSUE TITLE
Reordering Tabs - The order number on tabs looks very odd!

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16364] opened 2024-05-23 14:07 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

In v13 we could see a input field with the order number of the tab 
<img width="750" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/b568fe2c-cbb2-40b2-aec7-b9ffd4089b62">

In v14 it looks like a label
<img width="783" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/90d4a2f2-f135-41c6-8872-4ace0f86b831">

### Steps to reproduce

As before

**Comment by Zeegaan** [comment] 2024-06-20 13:50
This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16320, so I will close this 😁

**Closed by Zeegaan** 2024-06-20 13:50 UTC
Labels: type/bug
