### ISSUE TITLE
IPublishedRequestBuilder.SetRedirectPermanent not triggering

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#13738] opened 2023-01-25 21:31 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

In one of our custom content finders (IContentFinder) we set SetRedirectPermanent on the request with the url the request should redirect to.

The code is being hit, but the request/browser never actually redirects to the supplied url.

The remarks on this method say: _“Does not actually perform a redirect, only registers that the response should redirect. Redirect will or will not take place in due time.”_

So how to verify/confirm the redirect should take place?

Is this a known/reproducible issue?

### Steps to reproduce

a custom content finder (IContentFinder) registered/added to ContentFinders chain, and sets/calls SetRedirectPermanent() with the intended redirect url.

### Expected result / actual result

expected result: the request redirects to the supplied url
actual result: request not redirected, and in this case the our custom 404 handler kicks in (being that its defined as the SetContentLastChanceFinder)

**Comment by Zeegaan** [comment] 2023-01-26 13:27
Hey @shearer3000 I cannot reproduce this issue, the permanent redirect works just fine for me 👌 
Below is a gif attached, where you see me navigate to the "/demo" URL, and the first time it enters my if clause, but as you see on my second call, it has been permanently redirected, and thus the path will already start out with "/" and not "/demo" anymore 👍 
![PermanentRedirectWithContentFinder](https://user-images.githubusercontent.com/70372949/214846903-626244df-1b4d-42cb-9898-cccf2d8723b5.gif)

My ContentFinder code: 
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Web;

namespace Umbraco.Cms.Web.UI;

public class MyContentFinder : IContentFinder
{
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;

    public MyContentFinder(IUmbracoContextAccessor umbracoContextAccessor)
    {
        _umbracoContextAccessor = umbracoContextAccessor;
    }

    public Task<bool> TryFindContent(IPublishedRequestBuilder request)
    {
        if (request.Uri.GetAbsolutePathDecoded().StartsWith("/demo"))
        {
            _umbracoContextAccessor.TryGetUmbracoContext(out var umbracoContext);
            var content = umbracoContext!.Content!.GetRouteById(1059)!;
            request.SetRedirectPermanent(content);
            return Task.FromResult(true);
        }

        return Task.FromResult(false);
    }
}

// Register the IContentFinder
public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) => builder.ContentFinders().InsertBefore<ContentFinderByUrl, MyContentFinder>();
}

**Comment by shearer3000** [comment] 2023-01-26 22:53
thanks for investigating @Zeegaan
 
I realised your example doesn't call "SetPublishedContent" at any stage, but i was as per https://docs.umbraco.com/umbraco-cms/reference/routing/request-pipeline/icontentfinder

I removed "SetPublishedContent" and now my SetRedirectPermanent works as expected. Thanks again for help, please close ticket.

**Comment by Zeegaan** [comment] 2023-01-27 07:10
@shearer3000 Great to hear!
Closing this 😁

**Closed by Zeegaan** 2023-01-27 07:10 UTC
Labels: state/needs-more-info, type/bug

**Comment by Myster** [comment] 2023-06-21 05:17
In my particular scenario I call one of the built in content finders, then check a 'redirect to page' property on the found content, and if a URL is set I want to redirect. The built in finder does the SetPublishedContent, and I do the SetRedirectPermanent.

So we've created conflicting messages for umbraco and it gets confused.
In earlier versions of umbraco (8?) this would redirect, but in umbraco 10.5.0 I get 404 **Which is neither the found content nor the redirect.** Umbraco is confused by the conflicting signals being sent.

To work around this I set the published content to null first like so:
	request.SetPublishedContent(null);
	request.SetRedirectPermanent(redirect.Url);

**Comment by ianleeder** [comment] 2023-11-03 00:41
In MY particular scenario, this still didn't work.

It works fine if the `ContentFinder` is inserted into the `ContentFinders` collection, but it still doesn't work if it's registered as the `SetContentLastChanceFinder`.  I needed to split the "look for redirects" logic, from the "return custom 404 page" into two different content finders.
