### ISSUE TITLE
Unable to unlock locked out backoffice users

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#10145] opened 2021-04-20 05:00 UTC
A brief description of the issue goes here.

Unable to unlock locked out backoffice users. Appears to work then when refreshing their user profile they are still showing as locked out, and are unable to log in.

## Umbraco version

I am seeing this issue on Umbraco version: 8.12.2

Reproduction
------------

### Bug summary

An umbraco backoffice user locks out their account, unlocking via the backoffice fails. I had to work around by updating the database using SQL and restarting the app pool.

### Specifics
Latest Chrome on Window

### Steps to reproduce

Lock an umbraco backoffice account out.
Log into the backoffice with an admin account and click the unlock button for the user in the users section.
Refresh the users profile in the user section. 

### Expected result

It should not still show the user as being locked out.
The user should be able to log in.

### Actual result

User unable to log in. User profile still showing the user locked out.

**Comment by emma-hq** [comment] 2021-04-20 08:07
Hey Chad, 

Thanks for reporting this. I'll see when the last time this worked was and tag as a regression accordingly.

Emma

**Comment by emma-hq** [comment] 2021-04-20 08:38
Well that was easy 😂 It's working in 12.2.1 so we'll need to look at why that is. 

Emma

**Comment by nzdev** [comment] 2021-04-20 23:22
It also appears to work on 8.12.2 if you keep clicking unlock 4+ times.

**Comment by thomashdk** [comment] 2021-07-12 07:43
Haveing the same issue on 8.14.1

Any workaround?

**Comment by thomashdk** [comment] 2021-07-12 10:29
Changing the user language made it work ? 

It was like it didn't look at the values in the database? Triede to change the loginattepts to 0 in the database but the value didn't change in the user in the backoffice

**Comment by nul800sebastiaan** [comment] 2021-08-05 12:17
I think it might be something with a stored time - we're tracking this one here - https://github.com/umbraco/Umbraco-CMS/issues/10678

I believe your database was a v7 before, right @nzdev? 

@thomashdk if you change the db you need to  recycle the app pool first for umbraco to read the new values. 

Closing this one as a duplicate of #10678

**Closed by nul800sebastiaan** 2021-08-05 12:17 UTC
Labels: status/regression, type/bug
