### ISSUE TITLE
When using UmbracoAuthorizedApiController any exceptions aren't rethrown up the pipeline

### ISSUE THREAD

**Issue by harry-gordon** [umbraco/Umbraco-CMS#12392] opened 2022-05-11 15:32 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

It seems that exceptions thrown by controllers inheriting from `UmbracoAuthorizedApiController` are not rethrown up the pipeline. Interestingly, I switched to using `UmbracoApiController` and then my middleware did start seeing the exceptions from the controller.

I spotted this issue while working with back-office API controllers, I was trying to handle exceptions using a middleware (just a simple class called `ApiExceptionMiddleware`). This is my pipeline configuration below:

```c#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseCors();
    }

    app.UseMiddleware<ApiExceptionMiddleware>(env);

    app.UseUmbraco()
        .WithMiddleware(u =>
        {
            u.UseBackOffice();
        })
        .WithEndpoints(u =>
        {
            u.UseInstallerEndpoints();
            u.UseBackOfficeEndpoints();
        });

    ...
}
```

### Other notes

I tried to get to the bottom of this but I can't see an obvious reason why `UmbracoAuthorizedApiController` would behave like this. I thought it might be one of the attribute decorations:

```c#
[IsBackOffice]
[UmbracoUserTimeoutFilter]
[Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]
[DisableBrowserCache]
[UmbracoRequireHttps]
[CheckIfUserTicketDataIsStale]
[MiddlewareFilter(typeof(UnhandledExceptionLoggerFilter))]
public abstract class UmbracoAuthorizedApiController : UmbracoApiController
```

I tried attaching all of these (apart from `CheckIfUserTicketDataIsStale`, which is private) to my own controller and it didn't reproduce the problem. I'm curious to know what the issue is!

### Steps to reproduce

1. Create an app pipeline in which you're trying to handle exceptions (see the example above)
1. Create a back-office controller that inherits from `UmbracoAuthorizedApiController` and has a test method to call that throws an exception
1. Set a breakpoint in your middleware that handles exceptions
1. Test the endpoint
1. Notice that the middleware breakpoint isn't hit
1. Change your controller so that it inherits from `UmbracoApiController` (you may wish to also add `[Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]` so that it's still roughly equivalent).
1. Retest the endpoint
1. Notice that the middleware breakpoint is now hit!

### Expected result / actual result

`UmbracoAuthorizedApiController` should rethrow exceptions just like `UmbracoApiController`. I suspect this behaviour is accidental and not intended.

**Comment by Zeegaan** [comment] 2022-12-30 08:46
Hey @harry-gordon and sorry for the late answer here 🤔 This one is really hard to replicate for me, how did your `ApiExceptionMiddleware` look? 🤔

**Comment by harry-gordon** [comment] 2023-01-02 11:24
@Zeegaan no worries, it's a bit of a niche issue 😉. For the removal of doubt, I retested this and did reproduce it. Here is the middleware:

```
public class ApiExceptionMiddleware
{
    private readonly RequestDelegate _next;
    private readonly IWebHostEnvironment _env;

    public ApiExceptionMiddleware(RequestDelegate next, IWebHostEnvironment env)
    {
        _next = next;
        _env = env;
    }

    public async Task InvokeAsync(HttpContext httpContext)
    {
        try
        {
            await _next(httpContext);
        }
        catch (Exception ex)
        {
            if (_env.IsDevelopment() && ex is not ApiException)
            {
                throw;
            }

            await HandleExceptionAsync(httpContext, ex);
        }
    }

    private async Task HandleExceptionAsync(HttpContext context, Exception exception)
    {
        context.Response.ContentType = "application/json";
        var response = context.Response;

        var errorResponse = new ErrorResponseDto(false);
        switch (exception)
        {
            case ApiException ex:
                response.StatusCode = (int)ex.StatusCode;
                errorResponse.Message = ex.Message;
                break;
            default:
                response.StatusCode = (int)HttpStatusCode.InternalServerError;
                errorResponse.Message = "Internal Server error";
                break;
        }

        await context.Response.WriteAsJsonAsync(errorResponse);
    }

    public class ErrorResponseDto
    {
        public ErrorResponseDto(bool success, string message = null)
        {
            Success = success;
            Message = message;
        }

        public string Message { get; set; }
        public bool Success { get; set; }
    }
}
```

**Comment by nikolajlauridsen** [comment] 2023-01-03 09:24
Hey @harry-gordon I just had a second look at this, and I believe that this is actually intended behaviour. 

It's caused by the `JsonExceptionFilter` attribute, which for `UmbracoAuthorizedApiController` catches the errors and turns them into JSON responses. 

This causes the exception to be considered handled and stops the propagation of the exception (since we write to the `Result` property). 

So I'll go ahead and close this as intended behaviour for now at least 😄

**Closed by nikolajlauridsen** 2023-01-03 09:24 UTC
Labels: state/needs-more-info, type/bug
