### ISSUE TITLE
Error when following Getting Started "The Media Libary"

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#12758] opened 2022-08-01 10:46 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0 (Contrib Branch)

### Bug summary

When following the Media Libary I created the folder "My Images" after I saved the folder it keeps telling me "lost the next step Upload images and don't know where to go.". (See GIF
![UmbracoGettingStartedError](https://user-images.githubusercontent.com/73799582/182131803-d37974e6-e3c8-49ad-8d59-cbd7981103dd.gif)
)

### Steps to reproduce

Follow "The Media Libary" tutorial

### Expected result / actual result

That I would be able to complete the tutorial and add images to the folder.

**Comment by kjac** [comment] 2022-12-14 14:20
Hi @andr317c,

Thank you for reporting this 👍 and sorry for the late reply.

I can't reproduce this on the latest V10.3.2 ... likely sometime in between you reporting this and now, the issue has been fixed. I guess that's good news 😂 

I'll go ahead and close this now. Please feel free to reopen if you are still experiencing this issue on V10.3.2 or later.

**Closed by kjac** 2022-12-14 14:20 UTC
Labels: type/bug
