### ISSUE TITLE
Content Delivery API is slow with Umbraco Hybrid Cache

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#17353] opened 2024-10-24 11:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

When using the new Umbraco Hybrid cache, the Content Delivery API is very slow. It takes about 1500ms per request, depending on the number of properties.

### Steps to reproduce

- Configure umbraco to use the new Hybrid Cache
- Enable the delivery api
- Create a document type with some properties
- Request the content item by path with the Delivery API.

**Comment by bergmania** [comment] 2024-10-25 19:37
Hi @DanielToft 

Thanks for letting us know..

I can confirm it is slower then expected, and it seems to be because the routing is not using a cache to look up domains. The request to the hybird cache takes less then 1 ms on my tests..

**Comment by nikolajlauridsen** [comment] 2024-10-29 09:04
Fixed in #17371, thanks for reporting 😄

**Closed by nikolajlauridsen** 2024-10-29 09:04 UTC
Labels: type/bug
