### ISSUE TITLE
List View not working with granular permissions

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#11085] opened 2021-09-13 10:40 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0

### Bug summary

When creating a user group with no default permissions but granular permissions to browse a node with list view enable, the subnodes is not shown. If I change the node to not use list view, all the sub nodes will now show up (whit the same permissions).

Note: I've created another issue with granular permissions regarding sorting as well: https://github.com/umbraco/Umbraco-CMS/issues/11066

### Steps to reproduce

1. Create a node with two or more children
2. Enable List view on the parent node
3. Create a new user group with the following permissions
![image](https://user-images.githubusercontent.com/2575817/133069138-a08950e1-df29-452c-8d7f-509f5966a53a.png)
4. Add a user to the user group and login with that user
5. Notice that the children is not shown
![image](https://user-images.githubusercontent.com/2575817/133069336-9ca56ccd-b406-475d-b31e-c730157655a8.png)

If you disable the List view the children will be shown
![image](https://user-images.githubusercontent.com/2575817/133069455-4a9aa39d-a337-495a-9d3e-2d21bd6d847f.png)

### Expected result / actual result

Setting the browse permission on granular permission should give browse permission to all subnodes no matter if the node has List view enabled or not.

**Comment by jesperweber** [comment] 2021-09-13 10:52
It seems like this is actually a dupliucate of the following issue: https://github.com/umbraco/Umbraco-CMS/issues/10502

**Comment by nul800sebastiaan** [comment] 2021-09-13 11:50
Yes, thanks Jesper that's a duplicate of #10502 - I'll close this as duplicate.

**Closed by nul800sebastiaan** 2021-09-13 11:50 UTC
Labels: type/bug
