### ISSUE TITLE
Smidge On-Disk Cache not being generated with Timestamp CacheBuster

### ISSUE THREAD

**Issue by Nathan-H-Thinix** [umbraco/Umbraco-CMS#14608] opened 2023-07-26 14:55 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

The "Timestamp" cache buster runtime minification setting does not produce an on-disk cache when "UseInMemoryCache" is set to false (cache should be made on-disk and not stored in memory with this setting)

### Specifics

Using the combination of `"UseInMemoryCache": false` and `"CacheBuster": "Timestamp"` for `"RuntimeMinification"` settings in appsettings fails to produce an on-disk cache. 

### Steps to reproduce

**appsettings.json**
```
  "Umbraco": {
    "CMS": {
      "Content": {
        "MacroErrors": "Throw"
      },
      "Hosting": {
        "Debug": true
      },
      "RuntimeMinification": {
        "UseInMemoryCache": false,
        "CacheBuster": "Timestamp"
      }
    }
  }
```

**Bundling logic**
```
        public void Handle(UmbracoApplicationStartingNotification notification)
        {
            if (_runtimeState.Level == RuntimeLevel.Run)
            {
                _runtimeMinifier.CreateJsBundle("js-bundle",
                BundlingOptions.NotOptimizedAndComposite,
                new[] { "~/assets/js/core.min.js", "~/assets/js/vendor.prismjs.min.js", "~/assets/js/vendor.swiper.min.js", "~/assets/js/vendor_bundle.min.js", 
                    "~/assets/plugins/js/lite-yt-embed.js" });

                _runtimeMinifier.CreateJsBundle("js-jquery-bundle",
                BundlingOptions.NotOptimizedAndComposite,
                new[] { "~/assets/js/jquery-3.6.0.min.js", "~/assets/js/jquery.appear.js", "~/assets/js/jquery.parallax-1.1.3.js", "~/assets/js/jquery.browser.min.js",
                    "~/assets/js/jquery.validate.min.js", "~/assets/js/jquery.validate.unobtrusive.min.js" });

                _runtimeMinifier.CreateCssBundle("css-min-bundle",
                    BundlingOptions.NotOptimizedAndComposite,
                    new[] { "~/assets/css/core.min.css", "~/assets/css/vendor_bundle.min.css", "~/assets/css/vendor.prismjs.min.css", "~/assets/plugins/css/font-awesome.min.css" });

                _runtimeMinifier.CreateCssBundle("css-bundle",
                    BundlingOptions.OptimizedAndComposite,
                    new[] { "~/assets/plugins/css/lite-yt-embed.css", "~/assets/css/style.css" });
            }
        }
```

### Expected result / actual result

A cache should be made on-disk since the "UseInMemoryCache" runtime minification setting is set to false and "Timestamp" is used as the cache buster. 

Maybe I missed something  about how "Timestamp" works that would make it obvious that it doesn't work with on-disk cache, but I didn't see anything in the documentation on Umbraco or Smidge's repository that says anything about these two not able to work together. If there is a logical reason why they don't work together then using an alternative method for either runtime minification setting is okay as a solution (but preferably would be able to use both).

**Comment by kjac** [comment] 2023-07-27 09:38
Hi @Nathan-H-Thinix,

Thank you for raising this 💪 

This behaviour is entirely by design. Unfortunately [the docs](https://docs.umbraco.com/umbraco-cms/reference/configuration/runtimeminificationsettings) aren't clear about that.

`"CacheBuster": "Timestamp"` is explicitly interpreted as "don't write anything to disk". It happens [here](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.Common/RuntimeMinification/SmidgeOptionsSetup.cs#L19).

The other options (`"Version"` and `"AppDomain"`) both write files to disk - for example this configuration:

```json
  "Umbraco": {
    "CMS": {
      "Content": {
        "MacroErrors": "Throw"
      },
      "Hosting": {
        "Debug": true
      },
      "RuntimeMinification": {
        "UseInMemoryCache": false,
        "CacheBuster": "Version",
        "Version": "12345"
      }
    }
  }
```

...yields a new cache folder on disk for each new version:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/5a59fb66-35f9-48cd-ac0d-1037495d8fe4)

I believe you can change the built-in behaviour by implementing and invoking your own `IConfigureOptions<SmidgeOptions>`. Do consider though that the cache folder likely will fill up pretty quickly if `"Timestamp"` writes to disk, thus you will have to clean it up more often.

I'm going to close this issue for now. I will cross-link a docs PR to amend the documentation.

**Closed by kjac** 2023-07-27 09:38 UTC
Labels: type/bug

**Comment by kjac** [comment] 2023-07-27 09:45
Docs PR: https://github.com/umbraco/UmbracoDocs/pull/5322
