### ISSUE TITLE
Block list editor doesn't open on create, if first tab of element only features inherited properties

### ISSUE THREAD

**Issue by nickosv** [umbraco/Umbraco-CMS#14076] opened 2023-04-12 07:10 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.1

### Bug summary

If an element in a block list's first tab only includes properties that are inherited from compositions, the editor won't open on "Add". 

If a property is added to the element's first tab, the "Add" will open the editor.

https://user-images.githubusercontent.com/9071126/231371525-91e08d9a-f303-440b-b648-f3ee4dbb57ea.mp4

### Specifics

Function `userFlowWhenBlockWasCreated(createIndex)` evaluates whether first tab has any properties using 

`_blockObject$content$ = blockObject.content.variants[0].tabs[0]`
`_blockObject$content$.properties.length > 0`

In the first case `blockObject.content.variants[0].tabs[0].properties.length` is `0`. 
`blockObject.content.variants[0].tabs` produces the following JSON response:
[example.zip](https://github.com/umbraco/Umbraco-CMS/files/11208201/example.zip)

Notice that on line 20 in example.json, the properties that are present in the first tab when editing the content are also available.

### Steps to reproduce

Add a block list with an element that only features inherited properties in the first tab, and add it to any document type.

![image](https://user-images.githubusercontent.com/9071126/231372768-12d3f1a2-c060-47f3-b8a3-fa52f2b4a688.png)

### Expected result / actual result

I would expect the editor to open, however it doesn't.

**Comment by markadrake** [comment] 2023-04-14 06:38
I'm on `Umbraco version 11.3.0-rc.preview.73` and, if I followed your steps correctly, I can't reproduce this issue.

Here's what I did:

1. Create an element type. Give it (1) a tab and (2) some properties.
2. Create another element type. It's composed of my first element type only. No other tabs or properties were added.
3. Create a content type. Add a block list, and configure the block list to only allow the 2nd element type I created. 

Clicking "Add" works every time. 

I'm happy to try this again @nickosv. Did I misinterpret or skip anything? Thanks.

**Comment by kjac** [comment] 2023-04-14 08:22
Hi @nickosv,

Thanks for reaching out 👍 

Like @markadrake I can't reproduce this either. This is a screencast from the V11 latest:

[14076.webm](https://user-images.githubusercontent.com/7405322/231987280-1740b3c2-e982-41e5-a3cf-03d52770e649.webm)

Perhaps something has been fixed between V11.2.1 and V11 latest? 

I'm going to close this issue for now. If the issue persists for you, please don't hesitate to reopen with additional details to reproduce 😄

**Closed by kjac** 2023-04-14 08:22 UTC
Labels: type/bug

**Comment by nickosv** [comment] 2023-04-14 12:33
@markadrake @kjac Thanks for your swift responses. Awesome!

Anyway, looks like I wasn't thorough enough when reporting the issue - sorry for wasting your time. I've updated the "Steps to reproduce" part of the original post.

**Comment by nickosv** [comment] 2023-04-14 13:32
@markadrake Hmm, can't see any difference between your setup and mine. I'll try digging a bit deeper and get back to you guys if it's needed. Thanks for the effort so far :)
