### ISSUE TITLE
URL Picker styling breaks when inline RTE is on same document type

### ISSUE THREAD

**Issue by rbottema** [umbraco/Umbraco-CMS#16778] opened 2024-07-12 09:16 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4

### Bug summary

We have noticed that whenever an inline RTE is on a document type, some of the stylesheet applied to it 'leaks out'. This is at least visible in the URL picker, where the 'Link to page' and 'Link to media' texts take over the h5 styling of the stylesheet.

![image](https://github.com/user-attachments/assets/bb026a68-6435-4e73-b530-8b43b77b4b51)

### Steps to reproduce

- Create a style.css that applies visible styling to `h5`, for example by making it noticeably larger. Place in wwwroot
- Configure the RTE to use this stylesheet:
``` 
"Umbraco": {
  "RichTextEditor": {
    "CustomConfig": {
      "content_css": "style.css"
    }
  }
}
```
- Create a rich text editor data type with mode set it 'Inline'
- Create a document type with a property using the data type from the previous step, along with a URL picker property. Allow at root to be able to create an instance
- Create an instance of the document type and open the URL picker modal. Observe stylesheet styling is applied to 'Link to page' and 'Link to media' headings

**Comment by elit0451** [comment] 2024-07-17 07:02
Hi @rbottema 👋 

Thanks for reaching out! I, unfortunately, couldn't reproduce this in v13.4.1:

https://github.com/user-attachments/assets/01d6e7f7-94a5-4e9b-b180-02ba8d287bc3



Have a look and see if I am missing something.

Also, I noticed that we need to place `"RichTextEditor"` block inside `"Umbraco"::"CMS"` in **appsettings** as pointed out [here](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-plugins#adding-a-plugin) and not in just `"Umbraco"` as you initially thought, but unfortunately, that didn't make a difference and things worked as expected.

**Comment by rbottema** [comment] 2024-07-17 07:28
Hi @elit0451, thanks for trying to replicate! I'll check later to see if I missed anything in my reproduction steps.

On the video I do see that you are styling on `.h5` (i.e: a class named h5) instead of `h5` (i.e: the h5 HTML tag). Could that explain the difference?

**Comment by elit0451** [comment] 2024-07-17 07:49
YES, that was it 🙌 

I was able to reproduce it and here is a video of my reproduction steps:

https://github.com/user-attachments/assets/e2e831d2-19f1-4ad2-adac-134ea7053395




We would like some help fixing this, so I will mark it as up for grabs 🙂

**Comment by rbottema** [comment] 2024-11-11 18:47
#16954 Seems to be the same issue but more detailed, so this can probably be closed in favor of that issue.

**Comment by elit0451** [comment] 2024-11-12 09:59
Thanks for letting us know @rbottema. I will close this as a duplicate of #16954 🙁

**Closed by elit0451** 2024-11-12 09:59 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/frontend, affected/v13
