### ISSUE TITLE
Umbraco Grid layout can only configure allowed rows for one column

### ISSUE THREAD

**Issue by D-Inventor** [umbraco/Umbraco-CMS#9825] opened 2021-02-16 10:10 UTC
When creating and configuring a Grid datatype, I want to configure particular rows for particular sections in a layout. When attempting this, I find that I can only configure one section and then the configuration of all the other sections (including ones in a different layout) are gone / reset.

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1 & 8.10.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The allowed rows configuration of a section in an umbraco grid layout datatype seems to be maintained only for a single section.

### Specifics

Using Umbraco version 8.9.1, but the same behaviour also occurs on version 8.10.1
Using Edge version 88.0.705.68 (64 bit)
Also checked with Firefox version 84.0.2 (64 bit)
No error messages

### Steps to reproduce

1. Log in to backoffice
2. Go to Settings and create a new Grid layout data type
3. Create a layout with 2+ columns
4. Create 2+ row configurations
5. Select the layout, select a column and disable "Allow all row configurations" and enable or disable a few row configurations
6. Select another column in this layout and repeat previous step with different rows enabled/disabled
7. Go back to previous column and notice that the row configurations are now the same as on the second
8. Go back to the second column and notice that the row configuration has been reset and "Allow all row configurations" is enabled again

### Expected result

I expected to configure different allowed rows for different columns in a grid layout. I expect the configurations to be maintained for each column.

### Actual result

After configuring 2 columns, the configuration for one of the columns disappears / resets.
Following gif shows the behaviour that I'm seeing:
![ezgif-5-93cdbd2d0bc9](https://user-images.githubusercontent.com/25585418/108047960-b9abd580-7046-11eb-892b-4ac878ce9cca.gif)

---
_This item has been added to our backlog [AB#10595](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10595)_

---
_This item has been added to our backlog [AB#10593](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10593)_

**Comment by nul800sebastiaan** [comment] 2021-02-23 11:00
Thanks for the detailed report @D-Inventor! I can reproduce this and I tried it in a few versions. Looks like this broke in 8.8.0, and I am thinking it had something to do with @bjarnef's PR here: https://github.com/umbraco/Umbraco-CMS/pull/8357 - maybe Bjarne can quickly spot the problem, but we'll have to look into it for sure as that is a regression bug!

**Comment by bjarnef** [comment] 2021-02-23 13:10
@nul800sebastiaan sure, we need to have a look at this.
I wonder if it has something to do we the toggle or the checkboxes.
Would be great to output the values of model using in the toggle to narrow down the issue :)

**Comment by bjarnef** [comment] 2021-02-23 17:23
@nul800sebastiaan okay, I think I know what is going it.

When clicking the toggle, it seems to reverse the toggle state in the other column, but not only for the toggle. A similar behavious seems to happen for the checkboxes, when disabling the "Allow all row configurations".

Will investigate further.

**Comment by bjarnef** [comment] 2021-02-23 18:25
I noticed click on the column itself actually change the `allowAll` scope property here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.controller.js#L67

![A0cdBN9esx](https://user-images.githubusercontent.com/2919859/108889540-ca42e980-760c-11eb-9a65-767d8f6e3353.gif)

**Comment by bjarnef** [comment] 2021-02-23 18:56
I found something in this older commit, which might conflict with this new approach:
https://github.com/umbraco/Umbraco-CMS/commit/96f529c6698f7430e3e324972d550cad792d7bb8#diff-56f1a0867246f520ea0d0a25b700e8e1d1f6401c52e69afa96cfcf2e8194b66b

**Comment by bjarnef** [comment] 2021-02-23 20:24
Currently I think part of the issue is when having multiple column and because rows are listed, but not unique, so when clicking either checkbox or button, it change model of `row.allowed`, but this is the same under all columns.

![P8soOyHaiM](https://user-images.githubusercontent.com/2919859/108903340-7f7d9d80-761d-11eb-96a5-9d6fcb6908c3.gif)

**Comment by nul800sebastiaan** [comment] 2021-05-17 11:31
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9887

**Closed by nul800sebastiaan** 2021-05-17 11:31 UTC
Labels: status/regression
