### ISSUE TITLE
Tags: Inconsistent Value Type Update in Database When Switching Datatype Option from JSON to CSV and Vice Versa

### ISSUE THREAD

**Issue by Musealali** [umbraco/Umbraco-CMS#14457] opened 2023-06-26 09:45 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

version 11.4.1

### Bug summary

There is an issue with the tags datatype in the CMS.  

If you change the storage type for the tags from JSON to CSV:

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/ec341f5e-1fb0-4765-9994-2189552d04fa)

It will store the Data in the VARCHARVALUE in the database:

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/283515aa-e0db-4c70-acb5-f583cda19c09)

However if you change it back to JSON it will not update the value type in the DB which means it will stay as VARCHARVALUE and not change back to textValue!

![image](https://github.com/umbraco/Umbraco-CMS/assets/20074364/a1b1ba64-c065-4ece-835a-0eba7ea93da8)

This is ofc a problem because now we are limited to X amount of tags added because of the VARCHARVALUE limit... 

### Steps to reproduce

1. Create doc type
2. Add a tags property
3. create a content node and add some tags
4. check DB -> you will see data stored as textValue
5. Now change the tags datatype to store data as CSV
6. Add more tags to content and check the DB you will see the type in db is varcharvalue
7. Now change back to JSON - add some more tags/change some tags - check DB again
8. You will see the data still being stored as VARCHARVALUE

### Expected result / actual result

Should change back to textValue when changing storage type from CSV to JSON

---
_This item has been added to our backlog [AB#30805](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30805)_

**Comment by kjac** [comment] 2023-06-27 08:39
Hi @Musealali,

Thanks a lot for reporting this 👏 I can reproduce it.

It turns out the default Tags datatype (created at install) is configured to store data in the `textValue` column, while the property editor is built to store data in the `varcharValue` column. This leads to a quite confusing result, as you've noticed 😄 

We'll look into fixing this in an upcoming sprint. The proposed fix is:
- To ensure that Tags store data in the `textValue` column, so we don't risk capping the stored data due to the `varcharValue` column limitations.
- To create a migration that ports existing Tags property data from the `varcharValue` column to the `textValue` column.

**Comment by nikolajlauridsen** [comment] 2023-07-07 12:24
Fixed in #14510, thanks again for reporting 💪

**Closed by nikolajlauridsen** 2023-07-07 12:24 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12
