### ISSUE TITLE
System.TimeoutException: Failed to enter the lock within timeout

### ISSUE THREAD

**Issue by TomDaria** [umbraco/Umbraco-CMS#5572] opened 2019-06-03 15:33 UTC
We are on Umbraco 7.11.1 with ASP>NET 4.6.1.
We are seeing the subject error repeated in the logs and sometimes users call and say they can't login to Umbraco (login spins for 2 minutes then times out).  When they try logging in a few minutes later it works!

We are using IE Edge, Latest version of Chrome.

Full error 
System.TimeoutException: Failed to enter the lock within timeout.
   at Umbraco.Core.AsyncLock.Lock(Int32 millisecondsTimeout)
   at Umbraco.Core.MainDom.Acquire()
   at Umbraco.Core.ApplicationContext.Init()
   at Umbraco.Core.CoreBootManager.CreateApplicationContext(DatabaseContext dbContext, ServiceContext serviceContext)
   at Umbraco.Core.CoreBootManager.Initialize()
   at Umbraco.Web.WebBootManager.Initialize()
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)

**Comment by nul800sebastiaan** [comment] 2019-06-03 16:43
Unfortunately there's not much I can tell you here... I'm aware that this a problem that some people have but nobody seems to have found a pattern as to why this occurs. I would recommend upgrading to 7.14.0 at least and monitoring the situation. If you can find any cause for this problem on 7.14 then we can have a look at it again, for now I'll close this issue until we have more information.

**Closed by nul800sebastiaan** 2019-06-03 16:43 UTC

**Comment by joecklau** [comment] 2022-01-07 05:48
I'm also facing same issue.
My Umbraco 7.15.7 site is hosted on Azure App Service.
The site has several instances hosted on (1 master 1 slave) IIS@VM and Azure App Service (2 slaves) with "Flexible load balancing" setup.
_**This problem only happens on 2 slave instances on Azure App Service**_; while the IIS instances just works normally.
I'd like to highlight these configurations on 2 slave Azure App Service instances as that's the difference I can see between them and IIS instances:
- appSettings "umbracoLocalTempStorage" set to "EnvironmentTemp" following https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps-v7#umbraco-xml-cache-file-and-other-temp-files
- Disabled overlapped recycling following https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps-v7#recommended-configuration

Especially "Disabled overlapped recycling", same error happens on different (test/live) environments randomly after applying this settings. I have no strong evidence to say it must be the cause, but that's a recent change before I get such error.

Here's a full cycle of the error. It just repeat same messages for each browsing attempts.
For my site's case, recycling via changing web.config doesn't help.
It can be fixed by force-restarted the App Service via Azure portal only.
```
 2022-01-07 12:07:00,727 [P16620/D3/T408] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.15.7 application starting on RDXXXXXXXXXXXX
 2022-01-07 12:07:00,993 [P16620/D3/T408] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2022-01-07 12:07:01,086 [P16620/D3/T408] INFO  Umbraco.Core.PluginManager - Hash determined (took 81ms)
 2022-01-07 12:07:01,274 [P16620/D3/T408] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2022-01-07 12:08:31,309 [P16620/D3/T408] ERROR ASP.global_asax - An error was found
System.TimeoutException: Failed to enter the lock within timeout.
   at Umbraco.Core.AsyncLock.Lock(Int32 millisecondsTimeout)
   at Umbraco.Core.MainDom.Acquire()
   at Umbraco.Core.ApplicationContext.Init()
   at Umbraco.Core.CoreBootManager.CreateApplicationContext(DatabaseContext dbContext, ServiceContext serviceContext)
   at Umbraco.Core.CoreBootManager.Initialize()
   at Umbraco.Web.WebBootManager.Initialize()
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
 2022-01-07 12:08:45,588 [P16620/D3/T424] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
 2022-01-07 12:08:46,088 [P16620/D3/T424] INFO  Quartz.Impl.StdSchedulerFactory - Using object serializer: Quartz.Simpl.BinaryObjectSerializer, Quartz
 2022-01-07 12:08:46,154 [P16620/D3/T424] INFO  Quartz.Core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
 2022-01-07 12:08:46,184 [P16620/D3/T424] INFO  Quartz.Core.QuartzScheduler - Quartz Scheduler v.3.0.7.0 created.
 2022-01-07 12:08:46,184 [P16620/D3/T424] INFO  Quartz.Simpl.RAMJobStore - RAMJobStore initialized.
 2022-01-07 12:08:46,213 [P16620/D3/T424] INFO  Quartz.Core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

 2022-01-07 12:08:46,213 [P16620/D3/T424] INFO  Quartz.Impl.StdSchedulerFactory - Quartz scheduler 'QuartzScheduler' initialized
 2022-01-07 12:08:46,213 [P16620/D3/T424] INFO  Quartz.Impl.StdSchedulerFactory - Quartz scheduler version: 3.0.7.0
 2022-01-07 12:08:46,228 [P16620/D3/T424] INFO  Quartz.Core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED shutting down.
 2022-01-07 12:08:46,244 [P16620/D3/T424] INFO  Quartz.Core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED paused.
 2022-01-07 12:08:46,275 [P16620/D3/T424] INFO  Quartz.Core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED Shutdown complete.
```
