### ISSUE TITLE
Listview batch publishing on multi language site, publishes all variants

### ISSUE THREAD

**Issue by christerj** [umbraco/Umbraco-CMS#13755] opened 2023-01-30 14:19 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

 8.17.1

### Bug summary

When publishing from a Listview on a multi language site. All cultures are published, regardless of whether they are checked or not.

### Steps to reproduce

Make a batch (one page or more) publish in a multi language site

### Expected result / actual result

Only checked variants should be published, but all are, checked or not.

**Comment by nikolajlauridsen** [comment] 2023-01-30 14:43
Hey @christerj just had a look at this, and I can indeed reproduce it.


Looking at this the issue is that the frontend, when publishing from list view is posting to the `PostPublishById` endpoint in the content controller, this doesn't take a culture and therefore will publish everything regardless.

This fix for this would be to create a new endpoint which takes both the ID of the content items, and the culture(s) that should be published, and then does exactly the same as the existing `PostPublishById` but also assed in the culture from the request to the call to `_contentService.SaveAndPublish`, and then call that endpoint from the frontend with the selected cultures. 

Now looking at this, it has been a problem for a long time, so it's unlikely to be fixed for V8, however we'd love some help to take a look at it for version 10 and 11, so I'll go ahead and mark this as up for grabs 😄

**Comment by christerj** [comment] 2023-01-31 06:52
I would like to see the affected/v8 label for this one, to help others at least.

**Comment by nikolajlauridsen** [comment] 2023-01-31 07:21
Yeah that's a good point, my bad, I've gone ahead and added the label now 👍

**Comment by mennomout** [comment] 2023-02-01 22:27
I've made some progress towards fixing this issue with thanks to your directions @nikolajlauridsen 

There is a PR here: https://github.com/umbraco/Umbraco-CMS/pull/13772

Like I mention in the PR, there were a few occasions when the fix wasn't behaving like it should. But I'm not sure what caused it and cannot replicate them consistently.

**Comment by nul800sebastiaan** [comment] 2023-02-27 11:32
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13772

**Closed by nul800sebastiaan** 2023-02-27 11:32 UTC
Labels: type/bug, area/frontend, area/backend, affected/v8, affected/v10, affected/v11
