### ISSUE TITLE
10.3RC: Issues with placement information of Block Grid Editor

### ISSUE THREAD

**Issue by andyfelton-equatedigital** [umbraco/Umbraco-CMS#13154] opened 2022-10-10 15:39 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3RC

### Bug summary

I have been using the release candidate of the block editor and seems to be an issue with placement information not being available on the front end.

### Specifics

If I create a block grid editor with no areas defined but allow it to occupy between 1 and 12 columns I can end up setting the grid in the back office to look like follows:
![image](https://user-images.githubusercontent.com/96947768/194901858-df8b1303-5e8f-4d4c-a1f0-a87fe660279b.png)

With this, I've ended up creating a second row but when this is rendered I am not able to determine where to place the blocks as there is now information about where the block starts on a row or column basis. I could create areas which may help this but this would remove the flexibility of a block being able to be placed by an editor.

In addition the one of the blocks on the first row is forced right this information does not seem to be populated in the partial view of the textPanel partial view (or

### Steps to reproduce

As described in specifics above - text panel is configured as follows:
![image](https://user-images.githubusercontent.com/96947768/194902690-cf69d8db-c650-4880-b139-7caae122f627.png)

My model contains 4 blocks as follows:
0 - ColumnSpan 4, RowSpan 1, ForceLeft False, ForceRight False,
1 - ColumnSpan 2, RowSpan 1, ForceLeft False, ForceRight False,
2 - ColumnSpan 2, RowSpan 1, ForceLeft False, ForceRight False,
3 - ColumnSpan 4, RowSpan 1, ForceLeft False, ForceRight False,

### Expected result / actual result

Either the editor should automatically ensure all rows are filled (so the front end can assume how rows are filled) or information about the positioning of the blocks (IE. start column and row) should be available within the structure.

**Comment by nielslyngsoe** [comment] 2022-10-11 08:20
Hi @andyfelton-equatedigital 

Thanks for reporting this. It's for sure a bug, and I've reproduced it. We will have someone looking at fixing this.

Thanks

**Comment by andyfelton-equatedigital** [comment] 2022-10-11 08:31
Hi @nielslyngsoe 

Thanks for that could you possibly describe what the fix would be so that I can continue to test and use the block grid editor?

Thanks
Andy

**Comment by nielslyngsoe** [comment] 2022-10-12 09:32
Hi @andyfelton-equatedigital

The issue is within the Razor/C# part of the building render method. We are working on a PR for fixing this. When it's ready you will see it referred on this issue. If the fix turns out to be a change to Razor code you will most likely be able to transfer that fix onto your project.

**Comment by Zeegaan** [comment] 2022-10-13 06:25
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13190

**Closed by Zeegaan** 2022-10-13 06:25 UTC
Labels: type/bug, release/10.3.0

**Comment by andyfelton-equatedigital** [comment] 2022-10-13 08:16
@nielslyngsoe Fix looks good for the ForceLeft/ForceRight, but see no response to the whole issue on the positional information.

**Comment by nul800sebastiaan** [comment] 2022-10-17 09:08
Hi @andyfelton-equatedigital - I am not sure what we're talking about, so let's start with how it works now, I reproduced your scenario, the block that needs to float right is doing that, I can see there's still 12 positions in the grid and only 3 are taken, one of them ending up on the right. 

Is that what your concern is, that only 3 out of 12 slots are filled? And why would that be a problem?


https://user-images.githubusercontent.com/304656/196137066-9e38e4b3-566c-4d28-8663-933509cd8a68.mp4

**Comment by nielslyngsoe** [comment] 2022-10-17 09:29
Hi @andyfelton-equatedigital 

I guessed you feel this paragraph was unanswered?

"With this, I've ended up creating a second row but when this is rendered I am not able to determine where to place the blocks as there is now information about where the block starts on a row or column basis."

I would like to highlight why it is so, but I also would like to ask for the use case of this for my own understanding, thanks :-)

We do not store where Blocks are located, which is by design. We want to store as little data about the layout as possible and have gone for an auto-placement architecture, which is more flexible in terms of responsiveness. What this means is that we do not dictate the column or row number that a Block appears at.

By storing only: Column-span, row-span, force-left and force-right. We have a dataset for each block that is not relying on the other blocks. The layout is then made by the Blocks inserted top-left to right. Blocks can then be inserted/removed and the layout can adopt. This is also one of the reasons for the force-left feature, which makes it possible to have a Block that should appear on the left side, in other words resetting the layout for that point.

I can summon this into two main reasons:

1. Responsiveness
You might want to manipulate the column span of the blocks based on viewport-width. This would happen at runtime and then the col-position data would be wrong.

2. Hidding or making stuff appear at runtime. If this happens then the col-position data would be wrong again.

So this is why I hope it helps with your understanding.

I would still like to know the use case where you feel this data is needed, thanks :-)

**Comment by andyfelton-equatedigital** [comment] 2022-10-17 09:53
Hi Niels,

Thanks for coming back to me you've understood the issue exactly and understand where you're coming from re blocks auto placing, makes perfect to me. The issue would then be the back office does not seem to be auto placing and that block left on the second row should have been automatically moved to the first row as blocks are reflowed so the back office and website can use the same logic and appear the same.

Does that make sense?

Thanks
Andy

**Comment by nielslyngsoe** [comment] 2022-10-17 10:57
@andyfelton-equatedigital oh, yeah. makes sense. This is what the fix should correct. :-) Do you have the ability to test the current 10.3 branch(which includes this fix https://github.com/umbraco/Umbraco-CMS/pull/13190)
