### ISSUE TITLE
Value cannot be null. (Parameter 'key1') when trying to get .Value in RecurringHostedService (or other background services)

### ISSUE THREAD

**Issue by remkovb** [umbraco/Umbraco-CMS#15801] opened 2024-02-29 13:06 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

When trying to get .Value from any IPublishedContent item this doesn't work when not passing culture, even if this property doesn't have the checkbox for "Vary by culture" checked.

So whenever we try to get value we always have to pass culture to .Value("propertyKey", "culture") extension.

This is already from U10+ to latest version while before this never happened. When upgrading sites we discovered lot's of this "Value cannot be null. (Parameter 'key1')" errors in our logs.

### Steps to reproduce

- Create any Service with RecurringHostedServiceBase base for instance "TestService"
- Make sure it's added to hosted services: builder.Services.AddHostedService<TestService>();
- Next try to get any value from any node, so: 
 var umbracoNaviHideValue = node.Value<bool>("umbracoNaviHide");

![image](https://github.com/umbraco/Umbraco-CMS/assets/54794463/3fc4ff83-8e4d-454a-a9c4-c2d80fb8c195)

Message, exception:
![image](https://github.com/umbraco/Umbraco-CMS/assets/54794463/04c7418b-3f82-4b59-acc3-6167272ff824)

When doing this, everything is ok:
 var umbracoNaviHideValue = node.Value<bool>("umbracoNaviHide", "nl-NL");

### Expected result / actual result

I should expect I don't have to pass culture argument if this isn't necessary. I mean, when trying to get value from property that doesnt have culture variant, this should not be needed right?

**Comment by remkovb** [comment] 2024-02-29 13:19
I guess this is also related to this: https://github.com/umbraco/Umbraco-CMS/issues/14954

But the other issue talks about segment, while this is about culture that needs be passed to bypass this error?

**Comment by SandraGeisha** [comment] 2024-03-02 01:06
Also faced this one, as I understood it and mentioned in https://github.com/umbraco/Umbraco-CMS/issues/15749 it's actually because the document itself is variant. Meaning that you'll have to specify a culture. If the doctype and the property isn't variant you should be able to get it without having to specify the value. As mentioned in the original PR it was to fix something to do with a caching issue. Not sure if they'll revert this one as it does make some logical sense.

**Comment by RosenPetrovFFW** [comment] 2024-04-11 20:30
We also experience that error when we plug code in Examine indexing.

**Comment by Migaroez** [comment] 2024-04-29 08:37
Just tried out something similar using a more conventional entry point (apicontroller) and it seems to work just fine.
```csharp
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Web;

namespace Umbraco.Cms.Web.UI.App_Data;

[ApiController]
public class ApiController : ControllerBase
{
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;

    public ApiController(IUmbracoContextAccessor umbracoContextAccessor)
    {
        _umbracoContextAccessor = umbracoContextAccessor;
    }

    [HttpGet("api/invariant")]
    public IActionResult Get()
    {
        if (_umbracoContextAccessor.TryGetUmbracoContext(out IUmbracoContext? context) is false)
        {
            return BadRequest("Could not build UmbracoContext");
        }

        IPublishedContent document = context.Content!.GetAtRoot().First(d => d.ContentType.Alias == "invariantPage");

        return Ok(document.Value<string>("title"));
    }
}
```
result
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/01b9cbe7-4208-4b84-a5db-b04c35436471)

**Comment by Migaroez** [comment] 2024-04-29 08:52
Seems to work just fine in a RecurringHost too
```csharp
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.HostedServices;

namespace Umbraco.Cms.Web.UI.App_Data;

public class RecurringHost : RecurringHostedServiceBase
{
    private readonly ILogger<RecurringHost> _logger;
    private readonly IRuntime _runtime;
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    private static TimeSpan HowOftenWeRepeat => TimeSpan.FromSeconds(30);

    private static TimeSpan DelayBeforeWeStart => TimeSpan.FromSeconds(10);

    public RecurringHost(
        ILogger<RecurringHost> logger,
        IRuntime runtime,
        IUmbracoContextFactory umbracoContextFactory) : base(logger, HowOftenWeRepeat, DelayBeforeWeStart)
    {
        _logger = logger;
        _runtime = runtime;
        _umbracoContextFactory = umbracoContextFactory;
    }

    public override async Task PerformExecuteAsync(object? state)
    {
        if (_runtime.State.Level is not RuntimeLevel.Run)
        {
            await Task.CompletedTask;
        }

        using UmbracoContextReference umbracoContextReference = _umbracoContextFactory.EnsureUmbracoContext();


        IPublishedContent document = umbracoContextReference.UmbracoContext.Content!.GetAtRoot().First(d => d.ContentType.Alias == "invariantPage");

        var value = document.Value<string>("title");

        _logger.LogInformation("the value is {Value}", value);
        await Task.CompletedTask;
    }
}

public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) => builder.Services.AddHostedService<RecurringHost>();
}
```
Result
`{"@t":"2024-04-29T08:50:45.5930282Z","@mt":"the value is {Value}","Value":"The Title","SourceContext":"Umbraco.Cms.Web.UI.App_Data.RecurringHost","ProcessId":33952,"ProcessName":"Umbraco.Web.UI","ThreadId":19,"ApplicationId":"4236a0fa0bb1fb0fa2fd7f216a2c9f0d5111a2c9","MachineName":"RAVNIKA","Log4NetLevel":"INFO "}`

**Comment by Migaroez** [comment] 2024-04-29 09:04
As I cannot reproduce it with the supplied information, I will be closing this issue. Feel free to reopen it if you have more information

**Closed by Migaroez** 2024-04-29 09:04 UTC
Labels: type/bug
