### ISSUE TITLE
Redirects are not shown on info tab of a content item

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#8705] opened 2020-08-21 14:35 UTC
Somewhere in V7 @marcemarc introduced showing redirects on the info tab (https://github.com/umbraco/Umbraco-CMS/pull/2452)

Today I was working on #8703 and I noticed these are not shown anymore

## Umbraco version

I am seeing this issue on Umbraco version: latest version of v8/contrib branch

Reproduction
------------

Do a clean install of the latest v8/contrib branch and use the starter kit. Rename a node. Check if the redirect is added by looking at the redirects dashboard.

Now go to the item and check the info tab. No redirects are shown

This is probably because of the style display:none on the div element https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html#L23

But if you use a debugger you can see the code to get the redirects is still executed each time you switch to the info tab.

I don't know the reason why this is not shown anymore.

But either fix this by removing the code entirely to reduce unneeded api requests. Or show the redirects again.

**Comment by nul800sebastiaan** [comment] 2020-08-24 08:23
Aha! That code hasn't changed for 2 years (since that PR) so I suspect at some point that this test `!urlTrackerDisabled && hasRedirects`  was broken somehow. I can reproduce in v8.6 as well by the way.

**Comment by nul800sebastiaan** [comment] 2020-08-24 08:39
Nope.. it was just the `display:none;` - strange that it stopped working.. Added a PR: https://github.com/umbraco/Umbraco-CMS/pull/8713

**Comment by dawoe** [comment] 2020-08-24 08:40
Maybe it has something to do that V8 uses a newer version of angular compared to v7

**Comment by nul800sebastiaan** [comment] 2020-09-03 07:34
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8713

**Closed by nul800sebastiaan** 2020-09-03 07:34 UTC
Labels: community/pr, release/8.6.5, type/bug
