### ISSUE TITLE
V12 Blockgrid cant re-open some element-types

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/Umbraco-CMS#15102] opened 2023-11-02 11:39 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

After maaany tries a manage to replicate it.
Blockgrid cant re-open/edit content if the element-type was created with a tab first and then a group.

![image](https://github.com/umbraco/Umbraco-CMS/assets/7071187/86a7c19c-e00a-414a-8d2b-ada756cec5de)

### Specifics

Test site

user: test@test.com
pass: testtesttest

[demo.zip](https://github.com/umbraco/Umbraco-CMS/files/13238336/demo.zip)

### Steps to reproduce

1. Create a element-type, name it "Element"
2. Create a Tab, name it "Content Tab"
3. Create a Group, name it "Content Group"
4. Add a property to the group.
5. Save it.

6. Create a blockgrid-editor with the element-type.
7. Create a doc-type (name it "Page")  with the newly created block blockgrid-editor.

8. Create a page with the "Page" doctype.
9. Add a grid-block
10. Try opening the same block.

Nothing happens and no errors.

If you change order of 2 and 3 it will work

**Comment by andr317c** [comment] 2023-11-03 13:46
Hey! 
Thanks a lot for the clear reproduction steps, we really appreciate it! I was able to reproduce your issue on version 12.2.0. Afterward, I tried reproducing it on version 12.3.0, where I was able to open the BlockGrid Element without any issues. So the issue seems to be fixed on version 12.3.0. 😃 Please upgrade to version 12.3.0 to fix the issue!

Since the issue is fixed, I'll go ahead and close this issue. 😄

**Closed by andr317c** 2023-11-03 13:46 UTC
Labels: type/bug

**Comment by madsoulswe** [comment] 2023-11-06 08:13
@andr317c awesome, yes it seems to be fixed in 12.3 !

![TropicalnorsemanHobergGIF](https://github.com/umbraco/Umbraco-CMS/assets/7071187/38a3c449-a4cb-4cf8-9e42-2e1b2f90e98a)
