### ISSUE TITLE
v8: Creating pending changes breaks url

### ISSUE THREAD

**Issue by shushdelivery** [umbraco/Umbraco-CMS#6918] opened 2019-10-28 11:17 UTC
Saving an edit to a document type (blog in my case) but not publishing it will break the url of that document.

Reproduction
------------
Create a new umbraco site with the starter template.
Create a new blog post and publish it.
Visit the url.
Go back and edit the article content, but hit save instead of save & publish.
Visit the url listed in the info section in the top bar
The page will return 404.

You may or may not need to also preview the document.

It should display the unedited published document.

**Comment by stevemegson** [comment] 2019-10-28 16:21
I think this is caused by previewing. In [CreateContentNodeKit](https://github.com/umbraco/Umbraco-CMS/blob/0868b2e1b6e4b2b68e5de7451f591428f59f8eb8/src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs#L230), the `UrlSegment` property is populated for the published `ContentData`, but it's left null for the edited one. That means that when in preview mode, we can't generate the correct URL for that page or find it in `ContentFinderByUrl` when the URL is requested.

**Comment by nul800sebastiaan** [comment] 2019-10-28 21:27
Hmm, there's something there about still being in Preview mode, once you exit the preview mode, the URL works again..

**Comment by stevemegson** [comment] 2019-10-29 08:38
It looks like the same underlying issue as #6830, and the PR there should also fix this issue.

**Comment by rbottema** [comment] 2019-11-11 15:06
We are having this issue as well, and I can confirm that preview mode is required for the issue to show up. I have the following reproduction steps:

- Go to any page and publish it -> verify that the URL works
- Preview the page and don't close preview mode
- Refresh URL -> page now gives a 404

The following will make the page work again:
- Open URL in Incognito
- Clear cookies
- Close preview mode by clicking the X (not by closing the tab)
- Publish the page

And I think they all achieve the same effect: making sure you are not in preview mode any more.

I hope the mentioned issue fixes it! Will it help you if I test the change myself, and see if it solves the issue?

**Comment by rbottema** [comment] 2019-11-11 21:01
A side effect of this I noticed is that all pages under the page with pending changes will not have correct URLs as well in preview mode. An extreme (but common) result is that whenever the home page has pending changes (and this happens relatively often due to #6423) all internal links stop working in preview mode.

The mentioned PR fixes the bug for me, so I hope it can get merged soon =)

**Comment by nul800sebastiaan** [comment] 2019-12-18 11:59
The PR has been merged, so I'll close this one and refer to https://github.com/umbraco/Umbraco-CMS/issues/6830 as being the fix for this! It will be included in v8.6.0, so a bit of a wait still.

**Closed by nul800sebastiaan** 2019-12-18 11:59 UTC
