### ISSUE TITLE
Umbraco property editor keeps removing space after comma in a tag

### ISSUE THREAD

**Issue by MarbleDaemon** [umbraco/Umbraco-CMS#3209] opened 2018-10-09 03:08 UTC
### Bug summary

Umbraco 7.11 - 7.13. One of my Document Types has a Tag (Json format) property. If one of the tag values contains ", " - with a space after comma, Umbraco always removes the space after "," (comma) when loading the value to the Property Editor.

### Specifics

- URL: `umbraco/backoffice/UmbracoApi/Content/GetById?id=`
- Version: 7.11.1 - 7.13.0
- Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Steps to reproduce

1. The content editor creates a node using the above document type
2. The content editor enters a tag `a, b and c`
3. The content editor saves and publishes the node
4. A new cmsTags is now created with the value `a, b and c`
5. The content editor reopens the above node
6. The loaded value of the above property is now `a,b and c` - without the space after ","
7. The content editor makes a few changes to the node then saves and publishes the node
8. A new cmsTags is now created with the value `a,b and c` - without the space after "," - and has the above document as related
9. The previously created tag `a, b and c` now has no document related

### Expected result

The tag property value should be loaded with preserved space after comma (e.g. `a, b and c`).

### Actual result

The tag property value should be loaded without space after comma (e.g. `a,b and c`).

**Comment by nul800sebastiaan** [comment] 2018-11-20 16:08
Ah, weird that it does that :-)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment] 2018-11-22 08:53
@MarbleDaemon I am utterly unable to reproduce this on the latest codebase.

I have tried:

1. Using an existing Tags datatype.
2. Using a newly created Tags datatype.
3. Reinstalling Umbraco and doing it all over again.
4. Scratching my head.
5. Wearing my lucky hat.

All I see is:

![tags-with-comma-1](https://user-images.githubusercontent.com/7405322/48891547-eb1fa180-ee3b-11e8-8672-5c95abbe122b.gif)

...and on another page, subsequent to creating the first one:

![tags-with-comma-2](https://user-images.githubusercontent.com/7405322/48891565-fd99db00-ee3b-11e8-8ed1-8727b52f0cda.gif)

This leaves me to two possible conclusions:

1. Something has automagically fixed the Tags editor in the latest codebase.
2. You're experiencing some weird upgrade issue. 

Perhaps you could create a new Tags datatype and assign it to the doctype instead of the existing one? It should be perfectly compatible with the existing data, provided of course that you choose the same tag group.

**Comment by MarbleDaemon** [comment] 2018-11-23 02:42
Hello @kjac,

Thank you for your help. Here's how this bug occurs in my Umbraco:

![tagerror](https://user-images.githubusercontent.com/4795076/48926804-a52e1080-ef03-11e8-9e91-5e3f2b52a24e.gif)

It doesn't happen all the time, only most of the time. The customer had to stop using comma in their tags and switch to space instead.

With the website already on Live, it might not be possible to change the data type.

My regards

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:30
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:30 UTC
Labels: community/up-for-grabs, help wanted, type/bug
