### ISSUE TITLE
404.15 Error when creating/opening a content page with a Block List picker containing alot of blocks (40+ in that case)

### ISSUE THREAD

**Issue by psclrzn** [umbraco/Umbraco-CMS#10718] opened 2021-07-21 02:19 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.rc001

### Bug summary

When trying to create a new content page with a Document Type that includes a Block List Property Editor with alot of available blocks, I get a 404 error and the property is greyed out.

### Specifics

I have a Document Type that has a Block List property editor with more than 40 blocks available to select (To be more precise, it's the Sections Block Picker from the Umazel template that I am trying to make it work in Umbraco 9)

When I try to create a new content page with this document type, or if I try to open this Document Type in the backend, I get an 404 error:

![image](https://user-images.githubusercontent.com/41126535/126419115-90b0f58e-ac56-4a67-a2da-c0f5a4e8ac94.png)

Opening Chrome's DevTools, I can see that the backend is trying to call the following URL:

![image](https://user-images.githubusercontent.com/41126535/126419289-a92a870f-4753-4b0f-9eb2-0311b999a7b7.png)

And by inspecting closely, I can see that the query string part of the URL exceeds the maximum number of characters allowed in a URL.  A Key-Value Pair is created and passed in the URL for every block type I have available for this property.  Also, IIS seems to reject the request and returns a 404.15 error.

### Steps to reproduce

Use Umbraco 9.0-rc001.

- Create new Document Types to be selected as Blocks in a Block List Property Editor.  (Mine had 44)
- Create a new Data Type of type Block List.
- Add all the document types created earlier as "Available Blocks" and Save.
- Create a new Content Page with the Document Type created earlier.

-or-
(this is closer to my current setup)

- Have a fresh copy of the Umazel 8 template on a Umbraco 8 website.
- Install uSync and export all Document and Data Types.
- Have a clean Umbraco 9.0-rc001.
- Install uSync 9.0-rc001.
- Import the previously imported Document and Data Types into the Umbraco 9.0-rc001 build.
- Go to the Content tab, and create a new Home Page.

### Expected result / actual result

I should not have a 404 error and should be able to create a new Content Page.

**Comment by psclrzn** [comment] 2021-07-21 02:26
I did a quick test and clone the 9.0-rc001 repo.

In the content.resource.js file, I changed line 698 to :

  `{ contentTypeKeys: scaffoldKeys.join(","), parentId: parentId })),`

and it seems to work.

So instead of sending a query string that would look like this:

`someurl?contentTypeKeys[]=x&contentTypeKeys[]=y&contentTypeKeys[]=z&contentTypeKeys[]=a&contentTypeKeys[]=b...`

it sends a query string that looks liek this:

`someurl?contentTypeKeys=x,y,z,a,b...`

which seems to be interpreted by the API endpoint correctly, as if contentTypeKeys is an array without the need for extra code/methods in the API endpoints.

By reducing the number of the times the key appears in the query string, it keeps it under the maximum number of character limit defined by IIS or the Web Server.

There may be better solution, but this was my first investigation.  Another possible solution would probably convert the API endpoint from a GET to a POST.

**Comment by meyntony** [comment] 2021-07-21 12:47
We also noticed this is a problem on v8 

We were able to reproduce the problem by installing the [uskinned package](https://uskinned.net/) on v8.15.0 , the sample/demo content installed by the package fails with the same error.

**Comment by xanderekpl** [comment] 2021-07-22 09:48
I have same issue 
I think it's connected with https://github.com/umbraco/Umbraco-CMS/pull/10235
it;s createing LONG GET with all guids/ Imho should be post

**Comment by xanderekpl** [comment] 2021-07-22 10:06
@psclrzn can you update name again, it's not umbraco 9 releated but v8.15

**Comment by nikolajlauridsen** [comment] 2021-07-22 10:06
Hey thanks for reporting, and thanks for the very detailed report, love to see it 👍 

@xanderekpl is entirely correct, this was introduced in #10235 as a performance optimization for the blocklist editor. I'm unsure why we add `contentTypeKeys[]` as a parameter over and over again, this is certainly not the intention, I don't recall seeing that when reviewing PR. 

But regardless, I think you're bringing up some good points, since there's no real limit to how many elements types a blocklist can contain, this will still be a problem, even if we fix the `contentTypeKeys[]` aspect, given enough element types, the only thing that changes is the number of element types you need for the blocklist to cause this error. 

Part of me thinks that it's a bit odd to send a post request in order to request resources, however I agree that this would probably be the best solution, then we can add as many GUIDs in the body as we desire, without hitting some limit. Another potential solution I can see would be to chunk up the get requests after a certain amount of content type keys, however, that seems more complicated to me, and will also negate some of the performance benefits of being able to request all the content types in one request. 

Since this occurs in V8 as well, I think it would be best to fix this in V8 and then let it get merged up to V9.

**Comment by xanderekpl** [comment] 2021-07-22 10:08
possible workaround is allso longer requests(not safe solution at all ):

change the following to your web.config:

<system.webServer>
  <security>
    <requestFiltering>
      <requestLimits maxQueryString="32768"/>
    </requestFiltering>
  </security>
</system.webServer>

and:

<system.web>
    <httpRuntime maxQueryStringLength="32768" maxUrlLength="65536"/>
</system.web>

**Comment by nul800sebastiaan** [comment] 2021-07-22 13:07
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10726 for 8.15.1.

It will eventually be merged up to v9 as well.

**Closed by nul800sebastiaan** 2021-07-22 13:07 UTC
Labels: release/8.15.1, status/regression, type/bug
