### ISSUE TITLE
Update a color in Color Picker doesn't update label

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco-CMS#13717] opened 2023-01-23 14:20 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

On the Color Picker data type, you have the ability to update an existing color. Doing so works as expected. 
But, it seems like the "label" part of the color isn't updated. This causes a validation error if you later try to add the color, that was once present before it was updated. This causes the inability to add back colors that have been updated.

### Specifics

It seems like this is caused by the data stored for the Color Picker not being updated. See that the label is showing a different color. This is the original color, before it was updated. It seems like the validation is happening on the label, instead of the color. And since you can't add duplicate colors, you are unable to add the color. 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6904597/214062530-318e491a-0879-42ed-a594-8878b9702d80.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6904597/214062540-ce219d84-ba9a-4e9f-bf0e-090876c87b79.png)

### Steps to reproduce

- Go to a Color Picker data type
- Update an existing color, remember the original color
- Try to add back the original color
- The field showing the color will have a red outline, and you will be unable to add the color.

https://user-images.githubusercontent.com/6904597/214062249-2dee0c8b-b342-4e5c-ad15-6a6198242401.mp4

### Expected result / actual result

To be able to add a color that was previously there, but wasn't deleted, but simply updated.

**Comment by Zeegaan** [comment] 2023-01-24 07:41
Hey @aguyfromdenmark thanks for reporting, I can definitely reproduce this! 
While looking into it, it seemed like you were indeed right and the labels where not getting updated properly, I have made a PR https://github.com/umbraco/Umbraco-CMS/pull/13720 that should amend this 😁

**Comment by kjac** [comment] 2023-02-01 06:38
Oops - looks like this issue wasn't closed automatically by merging https://github.com/umbraco/Umbraco-CMS/pull/13720 ... I'll go ahead and close it now 😄

**Closed by kjac** 2023-02-01 06:38 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v10, affected/v11, affected/v12
