### ISSUE TITLE
Saving datatype trigger models ood

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14533] opened 2023-07-10 08:18 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0

### Bug summary

In a working project I have noticed each time we make adjustment to Block Grid configuration it trigger models generation or the `ood.flag` to the generated even though no changes as been made content types.

I think saving datatypes shouldn't trigger any models generation.

### Steps to reproduce

Configure following ModelsBuilder mode and notice when saving a datatype the `ood.flag` is generated.

```
 "ModelsBuilder": {
    "ModelsDirectory": "~/../MyProject.Core/Models/",
    "ModelsMode": "SourceCodeManual",
    "AcceptUnsafeModelsDirectory": true,
    "Enable": true
}
```

**Comment by nikolajlauridsen** [comment] 2023-07-10 12:13
Heya, I understand why this might seem a bit weird, but it's actually expected behaviour, the reason is that the data type can affect the generated models. 

For instance when testing this, I tried creating a doc type using an image picker, when the `Pick multiple items` is disabled the modelsbuilder generates a field like so: 

```C#
public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Im => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "im");
``` 

When I enable it and regen the models it now generates it with en `IEnumerable`: 

```C#
public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops> Im => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops>>(_publishedValueFallback, "im");
```

So we have to rebuild the models on datatype saves since it can change the models.


I'll go ahead and close this one, since it's intended 😄

**Closed by nikolajlauridsen** 2023-07-10 12:13 UTC
Labels: type/bug

**Comment by bjarnef** [comment] 2023-07-10 12:23
@nikolajlauridsen okay, in that case maybe the property editor (or probably more in PVC) could have a property, so only PVC's implementing this property trigger models generation? Configuration of most property editors doesn't affect change in generated model.

**Comment by nikolajlauridsen** [comment] 2023-07-10 12:28
Unfortunately, that wouldn't work since the property value converter is not responsible for refreshing of the flag. 

This is done in the `OutOfDateModelsStatus` class, which listens to the `DataTypeCacheRefresherNotification` (This way it covers both save, delete, etc). If we really wanted to I gues we could work out some kind of opt-in system for datatypes. However, I personally don't think that the added complexity overhead of a solution like that is justified given the circumstances.
