### ISSUE TITLE
Swapping file in media section does not update links in rich text editor

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#5632] opened 2019-06-09 21:18 UTC
I'm not a 100% sure this issue can be characterized as a bug but in short - When an editor has uploaded a file and made a link to the file from within the rich text editor the link is not updated if the editor overwrites/swaps the file in the media section. For the update to happen the document type needs to be published again.

For single case scenarios this would be perhaps be good enough but in scenarios where editors may have many content nodes to keep track of they perhaps forget, which node the file was being referenced on after they have made the update to the new file in the media section.

So I'm wondering if there is a way to have the link updated without the need for triggering the publish action? 🤔 

I have made a screen recording of the scenario here as well showing how to reproduce the scenario: https://youtu.be/zeFK_0QcOsw

**Comment by kjac** [comment] 2019-06-11 06:17
Oh this is definitively a bug 😢 

The same thing is happening with images in RTE's, although this was fixed in #4001. It seems the V8 cache is preventing the update; restarting the site causes the image to update in frontend.

Not really sure how to handle this. Editing an image somehow needs to invalidate the cached properties where the image is used.

/cc @zpqrtbnk

**Comment by nul800sebastiaan** [comment] 2019-09-30 08:38
I can't reproduce this any more, seems to work great, so I'll close this isuse!

**Closed by nul800sebastiaan** 2019-09-30 08:38 UTC
Labels: state/hq-discussion-cms
