### ISSUE TITLE
Umbraco shouldn't store JSON property data as indented

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#2996] opened 2018-09-18 20:07 UTC
### Bug summary

When saving a content or media item in Umbraco backoffice, the data of properties that store JSON will be saved as indented, which takes up more space in the database. Ideally JSON data shouldn't be indented when saved.

If saved via the content service, it instead depends on the specific implementation whether JSON data is indented or not, making it a bit inconsistent.

### Steps to reproduce

For instance, when saving a page with a grid property, the JSON value saved inthe database is something like:

```json
{
  "name": "1 column layout",
  "sections": [
    {
      "grid": 12,
      "rows": [
        {
          "label": "Section",
          "name": "Section",
          "areas": [
            {
              "grid": 12,
              "hasConfig": false,
              "controls": [
                {
                  "value": "Here is a headline",
                  "editor": {
                    "alias": "headline"
                  },
                  "active": false
                }
              ],
              "active": false
            }
          ],
          "hasConfig": false,
          "id": "e96ffdff-bfd2-8238-0909-33f1717cf7f3",
          "active": false
        },
        {
          "label": "Section",
          "name": "Section",
          "areas": [
            {
              "grid": 12,
              "hasConfig": false,
              "controls": [
                {
                  "value": {
                    "id": 1058,
                    "udi": "umb://media/31e5d65860174179b4052d54eca304b5",
                    "image": "/media/1031/photo-1460901419481-3fc27f0cdae9.jpg",
                    "caption": "Here is a bird"
                  },
                  "editor": {
                    "alias": "media"
                  },
                  "active": true
                }
              ],
              "active": true,
              "hasActiveChild": true
            }
          ],
          "hasConfig": false,
          "id": "1e4639a7-e8e2-00f7-c92a-7c9e27ef1140",
          "hasActiveChild": true,
          "active": true
        }
      ]
    }
  ]
}
```

```json
{"name":"1 column layout","sections":[{"grid":12,"rows":[{"label":"Section","name":"Section","areas":[{"grid":12,"hasConfig":false,"controls":[{"value":"Here is a headline","editor":{"alias":"headline"},"active":false}],"active":false}],"hasConfig":false,"id":"e96ffdff-bfd2-8238-0909-33f1717cf7f3","active":false},{"label":"Section","name":"Section","areas":[{"grid":12,"hasConfig":false,"controls":[{"value":{"id":1058,"udi":"umb://media/31e5d65860174179b4052d54eca304b5","image":"/media/1031/photo-1460901419481-3fc27f0cdae9.jpg","caption":"Here is a bird"},"editor":{"alias":"media"},"active":true}],"active":true,"hasActiveChild":true}],"hasConfig":false,"id":"1e4639a7-e8e2-00f7-c92a-7c9e27ef1140","hasActiveChild":true,"active":true}]}]}
```

The indended JSON string has a size of 1668 bytes, while the non-intended JSON string ha a size of 744 bytes. That is a reduction of roughly **44%**. It may be even more for larger JSON strings.

For a site with thousands of pages, which each may have lots of versions, this will be a lot of extra and unnecessary white space that is being saved to the database.

Another example is when uploading a new image in the media section, the crops of the image is automatically generated and saved (probably directly from C#). The crops are stored something like:

```json
{"src": "/media/1031/photo-1460901419481-3fc27f0cdae9.jpg", "crops": []}
```
Although the result here still has a few spaces here and there, there are no line break or indentation. However if an editor later saves the image through the backoffice, the JSON will instead be stored as indented:

```json
{
  "src": "/media/1031/photo-1460901419481-3fc27f0cdae9.jpg",
  "focalPoint": {
    "left": 0.51166666666666671,
    "top": 0.3575
  }
}
```

### Fix?

I haven't yet found the part of the code where the property values are being serialized to JSON. With a few hints in the right direction, I'd be happy to create a PR for this ;)

**Comment by soreng** [comment] 2018-11-12 00:50
@abjerner isn't serialization done in all the property converters?

**Comment by abjerner** [comment] 2018-11-12 07:50
@abjerner yes, you may be able to handle this individually for each property value converter, but a global solution would be preferred.

I do however suspect that handling this in the property value converter may also add some extra (unnecessary) serializing/deserializing, but I haven't tested this part yet.

**Comment by benjaminhowarth1** [comment] 2019-09-24 16:07
I'm about to delve into this & open a PR.

**Comment by benjaminhowarth1** [comment] 2019-09-24 16:17
Question for core: should Formatting.Indented be when debug="true" in the web.config? I'm suspecting so, similar to ClientDependency.

**Comment by ronaldbarendse** [comment] 2019-09-24 19:40
@benjaminhowarth1 The saved data should always be as compact as possible and reproducible (e.g. not different based on the debug mode), especially because it can be transferred to a different environment later on.

Only indenting the returned data in debug mode doesn't seem to add anything, as browser tools can format/beautify JSON responses and AngularJS has a filter to display indented JSON: https://docs.angularjs.org/api/ng/filter/json.

**Comment by benjaminhowarth1** [comment] 2019-09-24 19:46
@ronaldbarendse understood, but whilst in development/debug mode, you might want to manually analyse JSON objects in environments that aren't devtools. The PR I've sent in minifies JSON in the same way that ClientDependency does, only in release mode.

**Comment by abjerner** [comment] 2019-09-24 20:27
> The saved data should always be as compact as possible and reproducible

I fully agree with this part. It's important that the JSON saved in the database is serialized in exactly the same way across environments.

I don't think ClientDependency and saving JSON can be compared. The output of ClientDependency is both temporary and specific to a given environment, and it makes sense to be able to debug in the browser.

**Comment by benjaminhowarth1** [comment] 2019-09-24 20:35
I've updated my PR accordingly, I think it's up to HQ to decide what's useful/necessary here.

**Comment by nul800sebastiaan** [comment] 2019-09-26 11:35
Fixed for v7 in https://github.com/umbraco/Umbraco-CMS/pull/6416 - need to have a look for v8 too,

**Comment by nul800sebastiaan** [comment] 2019-09-26 11:48
And merged to v8 as well. https://github.com/umbraco/Umbraco-CMS/commit/5831cd915931f4784185bb9c848b65267b277268

**Comment by nul800sebastiaan** [comment] 2019-09-26 12:00
re-opening as.. maybe it doesn't actually do anything 😅

**Comment by benjaminhowarth1** [comment] 2019-09-26 13:02
Odd. I'm struggling to find the actual point where JSON-based datatypes get serialized...

**Comment by benjaminhowarth1** [comment] 2019-09-26 13:10
OK, I think I've found it. A number of classes that implement JsonConverter have a WriteJson method which never uses the passed JsonSerializer settings.

**Comment by nul800sebastiaan** [comment] 2019-09-30 16:14
Alright, on the retry, this update actually does fix the issue: https://github.com/umbraco/Umbraco-CMS/pull/6473

Cherry picked for 7.15.4 - a37b1075a100b3b50b32382bb6af68477f6179a5

In v8, we already remove whitespace for JSON propertydata so this fix is not needed there.

**Closed by nul800sebastiaan** 2019-09-30 16:14 UTC
Labels: community/pr, release/7.15.4, type/feature

**Comment by ronaldbarendse** [comment] 2020-03-12 14:04
@nul800sebastiaan Looks like when merging/cherry picking, some unused lines of code are added:

https://github.com/umbraco/Umbraco-CMS/blob/7dc6ddf3a8ac62bdb3b73616f223082a1952665f/src/Umbraco.Web/Editors/BackOfficeController.cs#L180-L181

https://github.com/umbraco/Umbraco-CMS/blob/7dc6ddf3a8ac62bdb3b73616f223082a1952665f/src/Umbraco.Web/Editors/BackOfficeController.cs#L233-L234

https://github.com/umbraco/Umbraco-CMS/blob/7dc6ddf3a8ac62bdb3b73616f223082a1952665f/src/Umbraco.Web/Editors/BackOfficeController.cs#L247-L248

Not a big deal, but quite easy to fix 😉

**Comment by ronaldbarendse** [comment] 2020-03-12 14:07
And another one:

https://github.com/umbraco/Umbraco-CMS/blob/7dc6ddf3a8ac62bdb3b73616f223082a1952665f/src/Umbraco.Core/Serialization/JsonNetSerializer.cs#L64
