### ISSUE TITLE
Member password reset checkbox doesn't hide "new" and "confirm" password fields.

### ISSUE THREAD

**Issue by tomhicklingnc** [umbraco/Umbraco-CMS#6099] opened 2019-08-12 10:26 UTC
On an Umbraco 8 site, editing the password of a member presents you with a checkbox entitled "Reset password" and 2 password boxes. On previous versions of umbraco, ticking the "Reset password" checkbox would hide the two password boxes, and upon saving the changes would show you the new random password that was generated for the member. In 8, the checkbox doesn't seem to do anything, and saving the page with it checked presents validation errors if you didn't also put values into the "new" and "confirm" fields.

---
_This item has been added to our backlog [AB#2266](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2266)_

**Comment by nul800sebastiaan** [comment] 2019-08-13 12:10
Hey there @tomhicklingnc - thanks, I can reproduce in 8.1.2! 

I hear that this might be a merge issue (merging changes from v7 to v8). I'm sorry that this one slipped through, we'll work on it soon!

**Comment by kjac** [comment] 2019-08-13 21:00
PR in #6119

**Comment by Shazwazza** [comment] 2019-08-14 02:40
I'm fixing this up but it turns out that member saving has other issues and the changed values are not re-bound to the UI after saving so am fixing this too.

**Comment by Shazwazza** [comment] 2019-08-14 02:50
New PR: https://github.com/umbraco/Umbraco-CMS/pull/6120

**Comment by nul800sebastiaan** [comment] 2019-09-02 11:01
It

**Comment by nul800sebastiaan** [comment] 2019-09-02 11:02
This seemed fix but running a quick test just now shows it wasn't completely fixed, see PR #6120 
I'm moving this to the next release, unfortunately we won't have time to fix it for 8.1.4 which is due out tomorrow morning.

**Comment by nul800sebastiaan** [comment] 2019-09-02 12:27
Well, that is weird! After retesting in several browsers, this works as expected. I'll have to do a thorough cache clean in my Chrome. 8.1.4 is still good then! :)

**Closed by nul800sebastiaan** 2019-09-02 12:27 UTC
Labels: release/8.1.4, type/bug
