### ISSUE TITLE
v8: Bug/Error. Nested Content + Multiple Link (new Conrol) + Folder 3 level and more level

### ISSUE THREAD

**Issue by OAOVLD** [umbraco/Umbraco-CMS#4879] opened 2019-03-06 08:44 UTC
Hello
v8: Bug/Error. Nested Content + Multiple Link (new Conrol) + Folder 3 level and more level.

EN: Control (Multiple Link) does not get a value when a link to the third or higher level of the folder is specified

Rus: Контрол (Multiple Link) не получает значение когда указывается ссылка на третий и выше уровень папки

EN: Example: the file is located in the home> Users > 1 folder.png (link will be received)
EN: Example: the file is located in the home> Users > New > 2019_folder > folder_01 > folder_15 > 2 folder.png (link will not be received, null)

RUS: Пример: файл находится в папке Home> Users > 1.png (ссылка будет получена)
RUS: Пример: файл находится в папке Home> Users > New > 2019_folder > folder_01 > folder_15 > 2.png (ссылка не будет получена, null)

**Comment by OAOVLD** [comment] 2019-03-06 08:44
Please fix this bug in version 8.0.1 on March 12. we cannot use umbraco 8 in production because of this error.

**Comment by nul800sebastiaan** [comment] 2019-03-06 10:07
Hi @OAOVLD - thanks for reporting bugs. We can not promise you all of them will be fixed at a specific date. Remember, you can still use v7 instead of v8 for now.

**Comment by OAOVLD** [comment] 2019-03-06 13:54
thank (

**Comment by OAOVLD** [comment] 2019-03-06 14:01
https://umbraco.com/blog/umbraco-7-to-umbraco-8-a-developer-s-perspective/

:)

Is it ready to use?
With the initial release of Umbraco 8 coming up very soon, a common question is: "Is it really ready for production or should I wait to use it?"

The answer: It is ready - you don’t have to wait!

**Comment by abjerner** [comment] 2019-03-06 21:53
@OAOVLD I've tried testing this, and I haven't been able to reproduce the problem so far. Would it by any chance be possible for you to share the code that fails? I've tested both with and without Models Builder.

**Comment by OAOVLD** [comment] 2019-03-07 06:39
View: 

@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{

 //Nested Content - Docs
IEnumerable<PublishedElementModel> el_Docs_Elems = Model.Value<IEnumerable<PublishedElementModel>>("Docs_Elems");

 if (el_Docs_Elems != null && el_Docs_Elems.Count() > 0)
    {
        foreach (var elem in el_Docs_Elems)
        {
	    Link elem_Content_Link = elem.Value<Link>("Content_Link"); // if the level is greater than 3 and higher, we get null
	}
    }
}

**Comment by OAOVLD** [comment] 2019-03-07 06:42
EN: Surprisingly, if you move the folder from level 4 to the first, then everything starts to work. Maybe this is a problem because now folders instead of numbers are called symbols ?

RUS: Удивительно, если переместить папку с 4 уровня на первый, то все начинает работать. Может быть это проблема из-за того что сейчас папки вместо цифр стали именоваться символами ?

**Comment by nul800sebastiaan** [comment] 2019-03-07 07:24
It seems like there's something wrong on your site, both Anders and I can't reproduce the problem with the code you've given us. I would recommend you try to get some help from our community on the forum at https://our.umbraco.com

**Closed by nul800sebastiaan** 2019-03-07 07:24 UTC
