### ISSUE TITLE
Cache not updated after setting property using member picker

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10132] opened 2021-04-14 08:46 UTC
Using Umbraco v8.12.2 on a project where I using ContentService to create an edit some content nodes/entities.

One if the properties being set is an "Author" property, which is also updated in backoffice:

![image](https://user-images.githubusercontent.com/2919859/114681316-4fde3e00-9d0e-11eb-98a4-799e337919a9.png)

![image](https://user-images.githubusercontent.com/2919859/114679892-e4e03780-9d0c-11eb-88ca-7d6802af50f3.png)

However in frontend it seems the cache isn't being updated:

```
<h3>@Model.Name</h3>

@Html.Raw(Model.Description)

<div>Author: @(Model.Author?.Name)</div><br />
```

![image](https://user-images.githubusercontent.com/2919859/114679671-aba7c780-9d0c-11eb-89be-b4c724536a0b.png)

However since other properties like the description property using Richtext Editor is rendered, I guess it may be a bug in the value converter for the Member Picker `Umbraco.MemberPicker`.

It also seems the Examine entry in External index is updated:

![image](https://user-images.githubusercontent.com/2919859/114681405-697f8580-9d0e-11eb-8bfa-af690bdbb5ae.png)

If a "Save and Publish" the node the cache is updated and the author is rendered.

![image](https://user-images.githubusercontent.com/2919859/114681618-9df34180-9d0e-11eb-8463-a0a7fce07daf.png)

**Comment by bjarnef** [comment] 2021-04-14 08:50
Not sure if it is correct the value converter use `PropertyCacheLevel.Snapshot`:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/PropertyEditors/ValueConverters/MemberPickerValueConverter.cs#L27

Most other property editors use `PropertyCacheLevel.Element`:
https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Core/PropertyEditors/ValueConverters/TinyMceValueConverter.cs#L21

**Comment by bjarnef** [comment] 2021-04-15 17:35
@nul800sebastiaan @Shazwazza do you know if it is expected these property editors use `PropertyCacheLevel.Snapshot`?

**Comment by nul800sebastiaan** [comment] 2021-04-16 11:42
Not sure what's going on here, I'll ask around and get back to you.

Are you publishing the node in your contentservice code?

**Comment by nul800sebastiaan** [comment] 2021-04-16 11:44
I'm assuming author is a UserPicker?

**Comment by nul800sebastiaan** [comment] 2021-04-16 12:14
I can't reproduce this, can you add the code you use? I have this simple attempt: 
 
```csharp
var cs = Current.Services.ContentService;
var node = cs.GetById(Model.Id);
var newAuthor = new StringUdi(new Uri("umb://member/7b3fcfdd48504c5a83a8fd9fc7154073"));
node.SetValue("author", newAuthor);
cs.SaveAndPublish(node);
```

All good here, value immediately updates on the page.

**Comment by bjarnef** [comment] 2021-04-16 12:22
@nul800sebastiaan does it make a difference if the value is set as `Guid` instead of `StringUdi`.

```
node.SetValue("author", model.Author);
```

Maybe it should just be set as `Udi` instead. I guess it might work in backoffice, because the lookup works with `Udi`, `Guid` and `int` and the save and publish may resolve the value.

**Comment by nul800sebastiaan** [comment] 2021-04-16 12:26
What type is `Model.Author`?

**Comment by bjarnef** [comment] 2021-04-16 13:37
It's a `Guid` :)

**Comment by nul800sebastiaan** [comment] 2021-04-16 14:35
Alright, I don't understand how that would work, a regular member picker stores a UDI, so that's probably why it doesn't work for you. 

I'll close this issue and encourage you to set it as a UDI, if it's already a Guid anyway you can do: `new GuidUdi("member", new Guid(model.Author));`. 
If setting that and doing a Publish doesn't update your cache then we can look again.

**Closed by nul800sebastiaan** 2021-04-16 14:35 UTC
Labels: state/needs-more-info

**Comment by bjarnef** [comment] 2021-04-16 16:39
@nul800sebastiaan you are right. Not sure why I originally store a `Guid` when member picker expect an `Udi`.
However it did show the member entity in backoffice, because it use `entityResource.getByIds()`
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/memberpicker/memberpicker.controller.js#L106

and which has three overloads to fetch members by `int`, `Guid` and `Udi`:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/EntityController.cs#L79

However the value converter only handle `int` and `Udi`.
https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/PropertyEditors/ValueConverters/MemberPickerValueConverter.cs#L36-L41

It could probably try convert to `Guid` as well, but not sure if we want that?

Anyway on "Save and publish" the value was transformed to an `Udi` and therefore it worked in frontend.

![Ww3EzZT8V3](https://user-images.githubusercontent.com/2919859/115056407-17dc2400-9ee3-11eb-8cea-a2b9fab21cec.gif)
