### ISSUE TITLE
Notifications added through SendingContentNotification handler are not displayed

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco-CMS#13812] opened 2023-02-08 15:40 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0, 11.1.0

### Bug summary

Notifications added through SendingContentNotification handler are not displayed in backoffice.

### Steps to reproduce

Try to create notification handler as below:

```
    public class TestSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
    {
        public void Handle(SendingContentNotification notification)
        {
            notification.Content.AddSuccessNotification("Test 1", "Msg 1");
            notification.Content.Notifications.Add(new BackOfficeNotification("Test 2", "Msg 2", NotificationStyle.Success));
        }
    }
```

Then register the created notification handler in any composer as below:

```
    public class TestComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.AddNotificationHandler<SendingContentNotification, TestSendingContentNotificationHandler>();
        }
    }
```

Finally, try to open any node and notifications will not be displayed.

**Comment by nathanwoulfe** [comment] 2023-02-10 06:39
Had a quick look into this one - issue is due to content mapping not mapping the notifications. Refer to https://github.com/umbraco/Umbraco-CMS/blob/665328f01c97d0e215c70b4aa8377058adadcb77/src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs#L131 for an example of a content map and note there's no reference to the Notifications property.

Not sure if this in intentional. It does make some sense to not map notifications as they are transient and not part of the data model. However, that doesn't mean there isn't a valid use case, and given it's straightforward to add notifications (per the issue description), and that it's possible to add notifications before mapping (resulting in (transient) data loss) it probably makes sense to update the mapping, assuming doing so won't cause problems...

**Comment by kjac** [comment] 2023-02-12 09:33
I can reproduce this as well. I'm marking it as up for grabs - would be nice to get this fixed 👍

**Closed** 2023-03-02 13:23 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12

**Comment by piotrbach** [comment] 2023-03-03 10:41
Thanks, Guys🤝, for solving the issue. 
Looking forward to the release. @wtct
Best, Piotr
