### ISSUE TITLE
Replication servers not updating with published content

### ISSUE THREAD

**Issue by alanwthom** [umbraco/Umbraco-CMS#12615] opened 2022-06-23 14:07 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.0.0

### Bug summary

We have a v10.0.0 deployed to a load-balanced solution on Azure Web Apps, but have some issues with content not reliably (very rarely) being pushed from the admin server to the replication frontend servers. We've followed the [load balanced](https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/load-balancing/), [advanced](https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/load-balancing/flexible-advanced) and [file system replication](https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/load-balancing/file-system-replication#examine-directory-factory-options) documentation to configure each server, setup Examine and assign server roles. The admin server is not set in the `dbo.umbracoServer` table, but I'm led to believe this table is a fallback for when not server role is set explicitly? There doesn't seem to be anything obvious in log files 

Admin server configuration:
- `IServerRoleAccessor` set to `SchedulingPublisher`
- `Umbraco.CMS.Examine.LuceneDirectoryFactory` set to `SyncedTempFileSystemDirectoryFactory`
- `Umbraco.CMS.Global.MainDomLock` set to `SqlMainDomLock`
- `Umbraco.CMS.Hosting.LocalTempStorageLocation` set to `EnvironmentTemp`

Frontend server configuration:
- `IServerRoleAccessor` set to `Subscriber`
- `Umbraco.CMS.Examine.LuceneDirectoryFactory` set to `TempFileSystemDirectoryFactory`
- `Umbraco.CMS.Global.MainDomLock` set to `SqlMainDomLock`
- `Umbraco.CMS.Hosting.LocalTempStorageLocation` set to `EnvironmentTemp`

The server registration is configured via the following composer:

```
public class SchedulingPublisherServerRoleAccessor : IServerRoleAccessor
{
    public ServerRole CurrentServerRole => ServerRole.SchedulingPublisher;
}

public class SubscriberServerRoleAccessor : IServerRoleAccessor
{
    public ServerRole CurrentServerRole => ServerRole.Subscriber;
}

public class SetServerRegistrarComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var settings = new Settings();
        builder.Services.BuildServiceProvider().GetService<IConfiguration>().GetSection("SectionName").Bind(settings);

        if (settings.IsAdminServer)
        {
            builder.SetServerRegistrar<SchedulingPublisherServerRoleAccessor>();
        }
        else
        {
            builder.SetServerRegistrar<SubscriberServerRoleAccessor>();
        }
    }
}
```

I have been able to verify that the servers have been configured as expected by interrogating the `IServerRoleAccessor` service on each server (returning `SchedulingPublisher` and `Subscriber` respectively). 

### Steps to reproduce

1. Install Umbraco v10.0.0 and set server roles via the above method (optionally set additional configuration as well)
2. Deploy solution to two Azure Web Apps in a load-balanced manner
3. Publish content on admin server and attempt to view content on frontend server

**Comment by bergmania** [comment] 2022-06-24 20:03
> The admin server is not set in the `dbo.umbracoServer` table, but I'm led to believe this table is a fallback for when not server role is set explicitly?

Correct..

Overall this sounds like a very hard issue to reproduce..  Maybe you can help us reduce the scope..

Can you confirm that the ID in the `*-lastsynced.txt` file is the same on all servers when this happens - And the same as the last ID in the `umbracoCacheInstruction`.

**Comment by alanwthom** [comment] 2022-06-27 09:12
Hi @bergmania, thank you very much for your reply. 

I've included an example of an entry that is created in `umbracoCacheInstruction` when a content node is published. Regarding the `*-lastsynced.txt` file, accessing this via the same method as [LastSyncedFileManager](https://github.com/umbraco/Umbraco-CMS/blob/c0c9c50e2110a88afab800abbf0e4a6b6a08c62d/src/Umbraco.Infrastructure/Sync/LastSyncedFileManager.cs#L76), on content publish the ID on the admin server updates to match the `umbracoCacheInstruction` table, but the front-end server does not (both files have the same path, e.g. `C:\local\Temp\UmbracoData\abc6f00c9224de0018dbcc16bd9a5b2cd1b22def\DistCache\12347f3bc1f41dd9bfb25914d049063cdce1b789-lastsynced.txt`). Is there something I've missed here in regards to configuration as I believe both web apps should be sharing the temp storage location?

`[{"RefreshType":4,"RefresherId":"900a4fbe-df3c-41e6-bb77-be896cd158ea","GuidId":"00000000-0000-0000-0000-000000000000","IntId":0,"JsonIds":null,"JsonIdCount":1,"JsonPayload":[{"Id":1141,"Key":"3e6caac6-002e-485c-9b01-e8d9a057759f","ChangeTypes":2}]}]`

**Comment by jrunestone** [comment] 2022-06-27 09:21
I had some issues with the `subscribers` not picking up the sync jobs 100% of the time (https://github.com/umbraco/Umbraco-CMS/pull/12474) but it was merged into U10. Can you enable debug logging as it logs some information about the sync process?

**Comment by bergmania** [comment] 2022-06-27 09:34
I would expect the front-end servers to have different file paths.. When the path is the same, they do end up having same MachineName and ApplicationId. 

To ensure another ApplicationId, you can implement a custom [IApplicationDiscriminator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.infrastructure.iapplicationdiscriminator?view=aspnetcore-6.0)

```cs
    public class CustomComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.Services.AddUnique<IApplicationDiscriminator, CustomApplicationDiscriminator>();
        }
    }
    
    public class CustomApplicationDiscriminator : IApplicationDiscriminator
    {
        public string? Discriminator => "Something deterministic unique for this server";
    }
```

**Comment by jrunestone** [comment] 2022-06-27 09:50
@bergmania The default discriminator implementation (https://github.com/umbraco/Umbraco-CMS/pull/12037) takes into account the machine name, which would be different on two Azure instances I believe. @alanwthom maybe if you tried switching from `SqlMainDomLock` to `FileSystemMainDomLock` instead which should work OOTB for Azure setups? This is what we use currently in our LB Azure setup, because we were getting acquisition errors with the `SqlMainDomLock` mode. Replication is also working for us.

**Comment by alanwthom** [comment] 2022-06-27 10:24
Hi @bergmania @jrunestone, thanks again for your replies. 

I've updated `Umbraco.CMS.Global.MainDomLock` to `FileSystemMainDomLock` and do now see content updates appearing immediately on the replication servers which is great news. This does seem to contradict the [Azure Web App documentation](https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps#recommended-configuration) though, so would the preferred option be a custom application discriminator instead (would this apply per individual web app - i.e. per individual publisher/subscriber instance - or just per web app type - publisher/subscriber) or should the documentation be updated (I would be happy to open a PR for this)?

Thanks

**Comment by jrunestone** [comment] 2022-06-27 10:31
I think the new recommended mode for Azure hosted apps is the `FileSystemMainDomLock` at least according to the comments in https://github.com/umbraco/Umbraco-CMS/issues/11935 (which leads up to the PR i linked), because "it works OOTB". It's unclear however if that means that the `SqlMainDomLock` mode should be deprecated.

Also in the PR linked above it suggests if using the `SqlMainDomLock` mode, a custom discriminator should be used in the case of slot deployments in Azure. 

So yeah I think the documentation page you linked to should be updated, at least to reflect the two options.

**Comment by bergmania** [comment] 2022-06-27 11:15
Ill ensure the docs are updated

**Comment by alanwthom** [comment] 2022-06-27 11:29
@bergmania @jrunestone Thanks again both for your help 🙏

**Comment by jrunestone** [comment] 2022-06-28 06:28
@alanwthom feeling good closing the issue if everything's sorted? :)

**Closed** 2022-06-28 08:10 UTC
Labels: type/bug

**Comment by d-gibbs** [comment] 2022-09-12 12:24
> Ill ensure the docs are updated

Hey @bergmania, did the docs ever get updated? We've just run into this problem too due to the guidance from: https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/load-balancing/azure-web-apps#appdomain-synchronization

Just wondering if this page should be updated as well? Thanks

**Comment by bergmania** [comment] 2022-09-12 12:42
Hi @d-gibbs..

Thanks for letting me know.
I updated that file too (- the joy of duplicated information).

https://github.com/umbraco/UmbracoDocs/pull/4375
