### ISSUE TITLE
Umbraco 8.8.0: can not login when Media Start node is not defined

### ISSUE THREAD

**Issue by gerwim** [umbraco/Umbraco-CMS#9319] opened 2020-10-30 13:16 UTC
When logging in and the user is assigned to a group which has a content start node selected but not a media start node, results in an "empty" Umbraco screen (as shown below) and the user is not logged in (hitting F5 will return to the login page) and no obvious error occurs.

<img width="1792" alt="CleanShot 2020-10-30 at 14 09 48@2x" src="https://user-images.githubusercontent.com/1841721/97708942-d59c6300-1ab9-11eb-81c2-028a7fe99ac8.png">

## Umbraco version

I am seeing this issue on Umbraco version: 8.8.0

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

You can not login when there's no media start node defined.

### Steps to reproduce

1. Create a new group
2. Give it a content start node
3. Don't give it a media start node
4. Create a new user
5. Assign this user to the group
6. Login with this user

### Expected result

Give an error on login (when not defining a content start node, there's an actual error on the login page) or on the group creation page.

### Actual result
Umbraco forwards you from the login page to the backoffice, but never logs _actually_ logs you in:
<img width="1792" alt="CleanShot 2020-10-30 at 14 09 48@2x" src="https://user-images.githubusercontent.com/1841721/97708942-d59c6300-1ab9-11eb-81c2-028a7fe99ac8.png">

**Comment by nul800sebastiaan** [comment] 2020-11-03 11:24
Thanks! This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9319

**Comment by nul800sebastiaan** [comment] 2020-11-03 11:24
Thanks! This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/7682

**Closed by nul800sebastiaan** 2020-11-03 11:24 UTC
