### ISSUE TITLE
Member Restricted Public Access does not redirect to login page, shared view components still display content from restricted page

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#13462] opened 2022-11-22 16:27 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 10.3.2

### Bug summary

Unexpected behavior when implementing Restricted Public Access whereby view components shared by login page and restricted page display restricted content on login page based on the return values of current page as _context.GetRequiredUmbracoContext().PublishedRequest.PublishedContent

### Specifics

If I have a restricted access page set-up specifying a login page and allowed roles per the normal restricted access page set-up processes and try to access that page in a non-loggedin state.

1. The page does not redirect to login page, rather the URL stays set on the restricted access page. (This might be by design now in .net core - I don't know.)
2. The internal content switches to the login page content with the url (as mentioned) staying set on the restricted access page.
3. Any view components shared by both the login page and the restricted page will display content from the restricted page - not the login page. Its as if the context (based on the url) is still set for viewcomponents via the current url and not the login page.

### Steps to reproduce

Set up a login page and a restricted access page. Add a view component (such as a breadcrumb) to both login and restricted access page. Note in my case the VC is using it's own controller and view model. That component is relying on getting the current page as follows (and probably this is part of the issue):

`var currentPage = _context.GetRequiredUmbracoContext().PublishedRequest.PublishedContent;`

Even though the VC is decorated with [UmbracoMemberAuthorize] the _context.GetRequiredUmbracoContext().PublishedRequest.PublishedContent returns with the current page as marked in the URL and not the login page as expected.

### Expected result / actual result

I would expect that the page either redirect to the login page (as with previous versions of umbraco) or that the context be switched for Viewcomponents using _context.GetRequiredUmbracoContext().PublishedRequest.PublishedContent to the login page and not the current page.

Any workarounds if this is expected behaviour?

Thanks!

Jamie

**Comment by Zeegaan** [comment] 2022-12-01 09:02
Hey @jattwood This is intended behavior.
I would recommend instead of trying to get the content via an IUmbracoContextAccessor, do instead pass the IPublishedContent when invoking the view component.
I have based my example on the Using Viewcomponents in Umbraco documentation which can be found here: https://docs.umbraco.com/umbraco-cms/reference/templating/mvc/viewcomponents

So my view component looks like this instead: 
```
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Models.PublishedContent;

namespace Umbraco.Cms.Web.UI;

public class ProductViewViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(IPublishedContent content)
    {
        var currentPage = content;
        List<string> products = new List<string>() {
            "Product 1", "Product 2", "Product 3", "Product 4", "Product 5"
        };

        return View(products);
    }
}
```

And I then invoke my viewcomponent from the View like this: `@(await Component.InvokeAsync("ProductView", Model))
`

I will close this for now as resolved 👍

**Closed by Zeegaan** 2022-12-01 09:02 UTC
Labels: type/bug

**Comment by jattwood** [comment] 2022-12-01 15:54
Thanks @Zeegaan. So IUmbracoContextAccessor works in all cases except when a login re-write occurs... Here is my issue: 

Supposing that my ViewComponent is using a ViewModel that inherits from a modelsbuilder partial model. To initialize the modelsbuilder partial we need not only the model but the IPublishedValueFallback as well. Any ideas on how to accomplish that? I am unable to inject that into the view correctly and pass that to the VC.

**Comment by Zeegaan** [comment] 2022-12-02 11:57
@jattwood Not sure what you mean here, sorry 😕 
But you could use the IHttpContextAccessor like this: `var currentPage = httpContextAccessor.GetRequiredHttpContext().Features.Get<UmbracoRouteValues>()!.PublishedRequest.PublishedContent!;`

**Comment by jattwood** [comment] 2022-12-02 17:37
@Zeegaan Thank you! Yes this does work from inside my View Component Controller now. I'll use this in any VC's that are shared between restricted pages and the login page.

Cheers!

Jamie
