### ISSUE TITLE
Multilingual site - RTE url picker resolving domain incorrectly

### ISSUE THREAD

**Issue by ghost** [umbraco/Umbraco-CMS#12627] opened 2022-06-27 16:18 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5

### Bug summary

Multilingual site with multiple domains.
Not every page exists for all languages.

The issue I'm coming against is when an editor goes to add a link from one domain to another it replaces the target domain to its current domain.

E.g. as an editor i switch to de-DE in the content tree and navigate to a page on the www.{anon}.de domain, in a rich text editor I add a link from another domain www.{anon}.com/some-link. when submitting the link, the something strips out the domain and ends up trying to navigate to www.{anon}.de/some-link which doesn't exist.

### Specifics

domain seems to be replaced incorrectly at the point of submitting the url and before saving the document.

### Steps to reproduce

A multilingual site with multiple domains
en-us - www.somesite.com
de-de - www.somesite.de

1. Editor navigates to de-de content tree for www.somesite.de 
2. Editor navigates to a page with a rich text editor
3. Editor clicks 'insert/edit link'
4. Editor pastes link from en-us site e.g. https://www.somesite.com/events
5. Editor submits link

### Expected result / actual result

**Expected**
Pasted link to retain its original domain/culture 
https://www.somesite.com/events

**Actual**
Pasted link's domain is replaced by current culture domain
https://www.somesite.de/events

This link will now throw a 404 as that page doesnt exist in the de-de site

**Comment by robjakedorsett** [comment] 2022-08-15 13:27
Also getting this issue, has there been a fix yet?

**Comment by Blake-Ellis** [comment] 2022-08-17 12:01
Also having this issue, looking for a fix

**Comment by alina-tincas** [comment] 2023-05-16 13:44
Hello! 👋 

Since v9 has currently reached[ end-of-life](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/), which means it is out of support, I have therefore tried to reproduce this issue on the latest version of v10 of CMS (10.5.1), and here it is working. 

With this, I will close this issue and  if you have any other issues do not hesitate to create a new issue! Thank you as well for reaching out 🙌

**Closed by alina-tincas** 2023-05-16 13:44 UTC
Labels: type/bug
