### ISSUE TITLE
A Multinode Treepicker on a vary by culture content, cannot set root which does not vary by culture.

### ISSUE THREAD

**Issue by rasmuseeg** [umbraco/Umbraco-CMS#5667] opened 2019-06-15 07:40 UTC
A Multinode Treepicker on a vary by culture content, cannot set root which does not vary by culture.

Reproduction
------------

I created the following structure:
 - Website
   - Articles
     - Article (Vary by culture)
   - Tags (Does not vary)
     - Tag (Does not vary)

On the article document, create a property of Multinode Tree Picker, and set root by query by xpath to: `$site/tags` 

I know the scenario ins't a proper use case. But i was having a hard time figuring out why it was not able to set tree root.

### Bug summary

A Multinode Treepicker on a vary by culture content, cannot set root which does not vary by culture.

### Specifics

* Umbraco v8.0.2
* Brave Browser Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
* Havent checked other browsers

**Comment by nul800sebastiaan** [comment] 2019-06-17 06:49
> I know the scenario ins't a proper use case. 

Seems fine to me?

Unfortunately, I've tried this scenario and can't reproduce it. Maybe there's something else wrong in your setup or in the xpath query?

I'll close this for now, let me know if you have more info.

![5667](https://user-images.githubusercontent.com/304656/59583813-b37c8d80-90dc-11e9-82ac-8b1eec8ed661.gif)

**Closed by nul800sebastiaan** 2019-06-17 06:49 UTC

**Comment by rasmuseeg** [comment] 2019-06-17 06:57
Hi @nul800sebastiaan try it when, the blog is unpublished, or the article.
