### ISSUE TITLE
Media module, select multiple images but no action options

### ISSUE THREAD

**Issue by 1179vn** [umbraco/Umbraco-CMS#16560] opened 2024-06-05 10:47 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

I am using version 14, when entering the Media module, I need to move a series of images to another folder, but when selecting the images, there are no other action menus other than the Clear button.

### Steps to reproduce

![image](https://github.com/umbraco/Umbraco-CMS/assets/92634542/c6ef50d5-ff66-4e66-8ece-d245bc58d26c)

**Comment by Zeegaan** [comment] 2024-06-05 11:00
I can reproduce this, thanks for reporting 🐛

**Comment by iOvergaard** [comment] 2024-06-05 12:10
Hi @1179vn, thanks for testing! This seems to be equivalent to the functionality described in #16272 and as such, I will go ahead and close this issue. Feel free to reopen it if you think this was done in error 👍

**Closed by iOvergaard** 2024-06-05 12:10 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v14
