### ISSUE TITLE
Umbraco 8 Grid Layout Issue When Adding Content in Source View

### ISSUE THREAD

**Issue by UPtamang** [umbraco/Umbraco-CMS#4972] opened 2019-03-13 09:03 UTC
I faced and issue while copying html content to grid layout RTE source view. I copied HTML content from existing site and paste it in source view (view source code button) of the

 RTE. After clicking submit button in source view I see RTE is not showing there. Instead of RTE I see my content (same situation when we are not focused within the RTE). Then I pressed save and publish button, now I see all my content are gone. If I paste content within the RTE text container then there is no issue. I see it's working. Only the problem is when I copy content into the source view and submit.

Please check attached image to reproduce the issue.

![2019-03-13_14-45-011](https://user-images.githubusercontent.com/45009265/54266109-d7d94300-459e-11e9-9b4f-850cdaf49a5e.gif)

**Comment by nul800sebastiaan** [comment] 2019-03-14 19:54
Yeah that looks like a bug, not sure what's going on there.

**Comment by ArnoldV** [comment] 2019-03-21 08:17
Also when there is sourcecode and you change someting in the source view, that is also not saved.
When using the formats dropdown everything works, it's purely the source view that causes the issue.

**Comment by alicia123456** [comment] 2019-04-08 22:27
I'm seeing the same issue. See attached file for detailed description ... if it helps. We really need to be able to edit in source code view.
[Source code editing.docx](https://github.com/umbraco/Umbraco-CMS/files/3056453/Source.code.editing.docx)

**Comment by Shazwazza** [comment] 2019-04-09 00:48
Does anyone know if this exact problem exists in the RTE when used on it's own? (i.e. not within the grid)

**Comment by alicia123456** [comment] 2019-04-09 00:59
I just confirmed that it is NOT an issue when the RTE editor is on it's own (not within a grid).

**Comment by Shazwazza** [comment] 2019-04-09 01:18
Thanks! That is a bit odd since the underlying tinymce configuration is all the same so there's probably something odd perhaps going on with the html id targeting or something along those lines. We'll have to investigate. Have marked up for grabs in the meantime in case the community might be able to assist.

**Comment by nul800sebastiaan** [comment] 2019-05-14 09:29
As Niklas mentioned, this should be fixed in 8.1.0

**Comment by nul800sebastiaan** [comment] 2019-05-14 09:29
I'll mark as duplicate of https://github.com/umbraco/Umbraco-CMS/issues/5075

**Closed by nul800sebastiaan** 2019-05-14 09:29 UTC
Labels: community/up-for-grabs, help wanted, type/bug
