### ISSUE TITLE
Upgrade path 7.7.6 ->7.12.4 ERROR Invalid column name 'isSensitive

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco-CMS#3716] opened 2018-11-19 14:40 UTC
### Bug summary
Upgrade path 7.7.6 ->7.12.4 LOGS an error when trying to sign into the backoffice to start the upgrade
"Invalid column name 'isSensitive'."

### Specifics
Error from logs
```[P8172/D8/T150] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (6c9f9d2d).
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'isSensitive'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 235
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass5_0.<ExecuteReaderWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteReaderWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteReaderWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteReaderWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.<Query>d__115`1.MoveNext()
ClientConnectionId:faf7e122-619d-46aa-b80e-416ac98f6547
Error Number:207,State:1,Class:16
```

sql being executed
```
'SELECT umbracoNode.*, cmsContentType.*, cmsPropertyType.id AS PropertyTypeId, cmsPropertyType.Alias, cmsPropertyType.Name, cmsPropertyType.Description, cmsPropertyType.mandatory, cmsPropertyType.UniqueID, cmsPropertyType.validationRegExp, cmsPropertyType.dataTypeId, cmsPropertyType.sortOrder AS PropertyTypeSortOrder, cmsPropertyType.propertyTypeGroupId AS PropertyTypesGroupId, cmsMemberType.memberCanEdit, cmsMemberType.viewOnProfile, cmsMemberType.isSensitive, cmsDataType.propertyEditorAlias, cmsDataType.dbType, cmsPropertyTypeGroup.id AS PropertyTypeGroupId, cmsPropertyTypeGroup.text AS PropertyGroupName, cmsPropertyTypeGroup.uniqueID AS PropertyGroupUniqueID, cmsPropertyTypeGroup.sortorder AS PropertyGroupSortOrder, cmsPropertyTypeGroup.contenttypeNodeId
FROM [umbracoNode]
INNER JOIN [cmsContentType]
ON [cmsContentType].[nodeId] = [umbracoNode].[id]
LEFT JOIN [cmsPropertyType]
ON [cmsPropertyType].[contentTypeId] = [umbracoNode].[id]
LEFT JOIN [cmsMemberType]
ON [cmsMemberType].[propertytypeId] = [cmsPropertyType].[id]
LEFT JOIN [cmsDataType]
ON [cmsDataType].[nodeId] = [cmsPropertyType].[dataTypeId]
LEFT JOIN [cmsPropertyTypeGroup]
ON [cmsPropertyTypeGroup].[contenttypeNodeId] = [umbracoNode].[id]
WHERE (([umbracoNode].[nodeObjectType] = @0))
ORDER BY ([umbracoNode].[uniqueID])'
```

### Steps to reproduce
Upgrade from 7.7.6 to 7.12.4

### Expected result
Being able to log in and start the upgrade

### Actual result
Generic can't login message and an error in the logs.

**Comment by Migaroez** [comment] 2018-11-19 14:46
Workaround:
run SQL `ALTER TABLE cmsMemberType add isSensitive bit`
No errors during migration.

**Comment by nul800sebastiaan** [comment] 2018-12-07 13:32
@Migaroez would it be possible for you to send us a backup of your database before you upgraded it? That's the only good way we would have to debug this problem, I couldn't reproduce this on a clean install of 7.7.6 upgraded to 7.12.4.

**Comment by Migaroez** [comment] 2018-12-07 18:38
I will check with the customer if this is allowed.

**Comment by bijeshtank** [comment] 2019-02-13 15:31
Hi, is there any update in this? We get the same issue as well, but upgrading from 7.5.6 -> 7.12.4.

We have a custom oauth service that does GetMembersByMemberType(). Could it be something to do with that? Since 7.9 there is a new field called 'isSensitive' was introduced with the GDPR update.

**Comment by bijeshtank** [comment] 2019-02-14 12:52
Hi, just to update you, it seems like we had an issue with another package that was causing an error with the upgrade. We recently updated the package in question and now the upgrade seems to be working fine.

**Comment by nul800sebastiaan** [comment] 2019-02-14 21:21
Thanks for the follow-up @bijeshtank - care to share what the package was, it might help.

I'll close this issue for now since we can't reproduce, we can always re-open when there's more info available!

**Closed by nul800sebastiaan** 2019-02-14 21:21 UTC
