### ISSUE TITLE
Validation issue when using nested block editor properties/custom view file

### ISSUE THREAD

**Issue by Matt-At-DurableDigital** [umbraco/Umbraco-CMS#12179] opened 2022-02-15 08:41 UTC
### Issue description

We are experiencing an issue when using nested block list editors to create a grid layout. We have a blocklist editor configured to create 'rows' which have multiple 'columns' which are also block list editors configured to use element type components that represent cells/grid components.
When we configure this to use custom views to give editors the WYSIWYG type editing experience we encounter a validation issue identical to this issue raised (and fixed) previously https://github.com/umbraco/Umbraco-CMS/issues/8954 there is also another issue like this specific to the block editor which also seems to be fixed https://github.com/umbraco/Umbraco-CMS/issues/9997

Unfortunately, the same fix doesn't seem to work for nested block list editors when using custom view files and we see false validation errors being displayed.

This issue can be recreated by:

- Creating an element type to represent a grid component with a media picker and an RTE which both are mandatory
- Creating a new Block list data type 'block list content' configured to use the grid elements in the previous step
- Creating an element type to represent a 2 column row with 2 properties both of type 'block list content from previous step'
- Creating a new document type configured with a property type of block list editor configured to use the row created above and the custom view set to the file attached.
- Creating a new content based on the type made in previous step
- Adding a new row then the new grid component
- Do not configure the image or RTE values and submit, then publish
- You will see validation errors that cannot be fixed by setting values that are required
- The only way to fix the issue is to save the page and refresh then to set the values before any validation errors occur

Umbraco versions: **9.2.0 & 9.3.0**
[CustomRowPreview.txt](https://github.com/umbraco/Umbraco.Cloud.Issues/files/8067272/CustomRowPreview.txt)

---
_This item has been added to our backlog [AB#18538](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/18538)_

**Comment by nul800sebastiaan** [comment] 2022-03-25 09:12
Apologies for the late reply @Matt-At-DurableDigital - seems like this ended up in the wrong issue tracker so I didn't see it! 

Nested block list editors sounds like a bit of inception 😅, but definitely should work properly! The frontend team will have a look at this in one of their upcoming sprints.

**Comment by iOvergaard** [comment] 2022-04-05 13:31
Hello @Matt-At-DurableDigital 

This bug report is scheduled to be looked into during next week or the week after. We will then figure out what needs to be done and eventually assign it to the nearest possible Umbraco release from then on.

**Comment by iOvergaard** [comment] 2022-04-11 12:38
Hello again @Matt-At-DurableDigital 

From our reproduction of this issue it looks like your custom view tries to go outside its own "block" scope by looking through all child properties and then somehow loses its scope when showing the umb-property's inline in the block editor.

This had us stumbled for a while, but we started comparing your custom view to Umbraco's own inline editing view, which programmatically speaking looks a lot like yours and can be enabled in the block list editor. There we have to preserve the scope of each property to mark for validation, and this is done by giving each `umb-property` the key of the block that it exists within.

We tried this on your custom view and by chance it now seems to work with this slightly modified version:

```html
<button type="button" class="btn-reset umb-outline blockelement-labelblock-editor blockelement__draggable-element"
        ng-focus="block.focus"
        ng-class="{ '--active': block.active, '--error': parentForm.$invalid && valFormManager.isShowingValidation() }"
        val-server-property-class=""
        style="padding:11px;">
    <div class="section-view w-100">
        <div class="section-view__card blockelement-labelblock-editor ">
            <div class="section-view__section w-100">
                <div class="section-view__column flx-g1" ng-repeat="property in block.content.variants[0].tabs[0].properties" ng-style="{'flex-basis': (100 / block.content.variants[0].tabs[0].properties.length)}">
                    <umb-property property="property" element-key="{{block.content.key}}">
                        <umb-property-editor model="property"></umb-property-editor>
                    </umb-property>
                </div>
            </div>
        </div>
    </div>
</button>
```

You will notice that the `umb-property` has an additional attribute "element-key":

```html
<umb-property property="property" element-key="{{block.content.key}}">
```

@skttl: Upon researching this issue, we came across [your blog post](https://24days.in/umbraco-cms/2020/grid-nouveau-block-list/) describing much the same custom view. This is just to ping you to say that it looks like your custom view would have the same bug as we discovered here with the missing "element-key" attribute.

**Closed by iOvergaard** 2022-04-11 12:38 UTC
Labels: state/sprint-candidate
