### ISSUE TITLE
Back Office: Tag suggestions getting hid by Summary field 

### ISSUE THREAD

**Issue by chrisklay** [umbraco/Umbraco-CMS#14302] opened 2023-05-25 19:04 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

Document Library Back-Office: If there are multiple tag suggestions by the text entered in the “Tags” field, the list gets hidden underneath 

![Umbraco Bug](https://github.com/umbraco/Umbraco-CMS/assets/48740218/69d1565e-a9d0-4f0d-aaf5-1c1fd44379de)
the Summary field text box.

### Steps to reproduce

Create an Umbraco Document Type with content properties of a Tags field and Text Editor field

### Expected result / actual result

I expect that the dropdown list would be overlaid on top of the other property fields when looking at suggestions, but it is buried underneath the other properties

**Comment by kjac** [comment] 2023-05-26 08:14
Hi @chrisklay,

Thank you so much for reporting 👍 

I can reproduce this. Much to my surprise, this even happens for simple editors such as text areas:

<img width="593" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/2daabaf5-a0cc-4ff7-a554-755aeaf54d1f">

We'd love some help fixing this. I'm going to put it up for grabs.

**Comment by rammi987** [comment] 2023-06-01 07:13
Hellp @kjac,

We need to have discusstion on this. I was trying to fix this, but I found something where I need someone exstra.

- If I try bump op the z-index to max it has no effect.
- Turn off all position:relative for all parent elements has no effect.
- The tt-typeahead-overlaye instead of position absolue, replace it to fixed. No efffect.

I tryied to find the source of why the problem started. From Umbraco 11.1.0 and down, this bug is not occuring. So i drive deep down into the commit between 11.1.0 to 11.2.0. And i found this commit https://github.com/umbraco/Umbraco-CMS/commit/8463d906a747868ddbda3b1c01465f6cee1a589a

If you revert the styling contain: layout; to contain: style; then everything work again. But here is where I need accully your help, i don´t dare to just revert it, becouse i don´t why the change was made in a first place.

Only thing left is that I see 2 posibliy solution.
1) Revert the commit
2) New UX to the tags property, so it is not a position aboslute or fixed overlay.

Let me hear your thougs

**Comment by kjac** [comment] 2023-06-01 11:17
Hi @rammi987,

Thanks for digging into this 💪 

The mentioned commit was a fix for another fix that broke something 🙈 in short, we can't rollback that commit because it fixes this issue (and few other property editor z-index issues if I recall): https://github.com/umbraco/Umbraco-CMS/issues/13495

Sounds like option two is worth investigating?

**Comment by rammi987** [comment] 2023-06-01 11:52
@kjac then good I didn’t just revert and pushed it as a pr 🤣 i had that in mind it was intentional.

i’ll will rethinking it a bit and make a pr for suggestion on how it can look for the future, without the overlay

**Comment by chrisklay** [comment] 2023-07-05 16:40
@rammi987 @kjac 

Hi there,

Thank you for taking the time to look into this ticket issue. Are there any updates in when this bug may be patched in a future release?

**Comment by kjac** [comment] 2023-07-17 04:52
Hi @chrisklay,

The issue is still up for grabs. I don't know if @rammi987 had any luck rethinking the fix... perhaps you could help out?

**Comment by enkelmedia** [comment] 2023-08-21 07:41
Hi!

I have seen this little change have a big impact on property editors that need extra space while active. One is a custom one that I've built but also core-editors like tag picker, color picker etc.

I'm not sure but I think that this was introduced at the same time when work was made to be able to inactive and overlay property editors that should not be edited. E.g when editing a language variation while some properties are not allowed to vary by culture.

In my custom editor I made a hack that solved the problem but in a hacky way. When my property editor needs to span outside I will basically change the layout property temporarily and then revert the change. Similar to this:


```
 let parentPropertyEditorContainer = $element.closest('.umb-property-editor');
if(parentPropertyEditorContainer.length > 0) {
   parentPropertyEditorContainer.css('contain','inherit');
}
```

In my scenario, this works without side-effects but it might be situations where there are site effects.

Maybe if there were a public API to support something like there where the editor enters some kind of "active" mode which means it could span outside it's boundaries. I also think that if this change was introduced lightly maybe we have to understand why it was introduced and challenge that, maybe just revert until a sustainable option can be introduced.

**Comment by iOvergaard** [comment] 2023-09-12 08:30
I think we can solve this with a compromise. We will detect if the property editor is in what we call "preview mode" and only then activate the stricter `contain: layout;` styling. This effectively reverts the commit that @enkelmedia outlined above.

There's an open pull request to test this out at #14796

**Comment by iOvergaard** [comment] 2023-09-14 11:35
A fix has been merged and will be released in upcoming versions of v10 and v12.

Thank you so much for reporting this issue!

**Closed by iOvergaard** 2023-09-14 11:35 UTC
Labels: type/bug, area/frontend, affected/v11, affected/v12, release/12.3.0, release/10.7.1
