### ISSUE TITLE
Media cache issue when having a freshly cloned site from Cloud

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4751] opened 2019-02-26 10:36 UTC
What we've been seeing is that when cloning a site from Cloud, the media caches have not been populated. This results in all media items returning null in the frontend.

This can be fixed by using the Published Status dashboard (last orange button).

Not really sure if this belongs on the Deploy tracker or here, but creating on Core for now as we can look into both to locate the problem.

Could be related to https://github.com/umbraco/Umbraco-CMS/issues/4729

**Comment by JimBobSquarePants** [comment] 2019-02-26 22:08
> This results in all media items returning null in the frontend.

Shouldn't a cache by design fetch the content from the source if none exists in the cache?

**Comment by zpqrtbnk** [comment] 2019-03-04 09:10
If the cache is read-through, yes - but the content and media front-end caches are not

**Comment by JimBobSquarePants** [comment] 2019-03-04 09:48
I’m curious. Is there an advantage I’m missing to not doing this?

**Comment by zpqrtbnk** [comment] 2019-03-04 15:20
Reproduced.

**Comment by zpqrtbnk** [comment] 2019-03-04 15:40
Fixed in referenced commit.

**Comment by nul800sebastiaan** [comment] 2019-03-04 15:53
I guess this hasn't been reviewed / tested. But I've cherry-picked for 8.0.1 so if changes are needed we'll need to update that one too.

**Comment by Shazwazza** [comment] 2019-03-05 03:49
I think the `TODO` in this code should really be fixed but we can make a separate task for that, it says:

`// TODO: should this be fatal (ie, an exception)?`

and the answer is YES, this would be fatal, if it were the case we would have discovered the bug much earlier ;)

**Comment by Shazwazza** [comment] 2019-03-05 04:49
I can confirm that this code fixes it and I've tested with a cloud site and the updated DLLs before and after.

**Closed by Shazwazza** 2019-03-05 04:49 UTC
Labels: release/8.0.1, state/review, type/bug

**Comment by AndersBrohus** [comment] 2019-03-07 20:09
I'm currently had a very mysterious problem with my image field was null, then i tried pressing the last orange button on the Published Status dashboard and then it worked :)

Guess this fixes it aswell?
Because this happened on a freshly installed NuGet version of V8 still running local :)
