### ISSUE TITLE
Sortable mode should be disabled for single block mode

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14116] opened 2023-04-18 12:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When enabling single block mode in Block List editor the sortable mode should be disabled as there is only on possible block (either inline or opened in overlay).

https://user-images.githubusercontent.com/2919859/232783258-22738465-52a7-49bd-9486-3866e9a6f465.mp4

Furthermore it seems the properties need a bit spacing and when dragging, the richtext editor is collapsed to zero height.

### Steps to reproduce

Enable a Block List editor instance as single block mode (and minimum and maximum set to 1).

**Comment by elit0451** [comment] 2023-04-20 06:36
Hey @bjarnef 👋 

I can confirm that there is a slight movement due to the sorting mode in both Umbraco 10 and 11. So I will mark this as up for grabs if anyone wants to give it a go.

I cannot reproduce the spacing issue you are seeing though. Here is my Block List configuration and then how it looks in a content node:
![BlockList](https://user-images.githubusercontent.com/21998037/233277830-2481f719-2abe-4b58-b59d-be62c2a6d2f0.png)

</br>

![ContentNode](https://user-images.githubusercontent.com/21998037/233277853-2dd359ca-7228-49ed-9b01-8b60759124b9.png)

**Comment by bjarnef** [comment] 2023-04-20 06:40
Hi @elit0451 

Can you try add the properties under a tab "Content" on the element type?

**Comment by elit0451** [comment] 2023-04-20 06:49
It didn't seem to make a difference 🙁 

![ContentTab](https://user-images.githubusercontent.com/21998037/233282663-f5819c75-381b-4f14-9062-83c07b6cce9e.png)

And I have the exact same margin:
![Controls](https://user-images.githubusercontent.com/21998037/233283498-f8c3ad77-dc3b-45e0-a8ec-c4b92012969a.png)

These screenshots are taken from a fresh 10.5.0 install but I also tried it in v11.3.0 and it is still the same

**Comment by bjarnef** [comment] 2023-04-20 06:54
Okay, it is this part which override the bottom margin.

![image](https://user-images.githubusercontent.com/2919859/233284267-ebdd3ef8-875f-4523-a190-16d1743c9ba6.png)

which comes from this: https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/less/main.less#L174

it may depend in which order Smidge bundle the CSS assets.

**Comment by rammi987** [comment] 2023-04-27 21:18
Hello @bjarnef 

When i look into this for a PR i noticed it´s not only the block list witch have some funnyness to it.
Also the Multi Url picker is the sorting a littel bit fun

[screen-capture.webm](https://user-images.githubusercontent.com/5937899/234992079-fe89c5cd-62d1-4e04-8862-3a4817332dcb.webm)

Also the Multi node Treepicker does it same

[screen-capture (1).webm](https://user-images.githubusercontent.com/5937899/234992906-fd256ce9-66b9-464c-8b0e-4029ad13619e.webm)

**Comment by bjarnef** [comment] 2023-05-16 09:05
@elit0451 submitted PR https://github.com/umbraco/Umbraco-CMS/pull/14252

**Comment by emmagarland** [comment] 2023-06-08 09:31
Thakns @bjarnef, merged #14252 closing this issue.

**Closed** 2023-06-08 09:31 UTC
Labels: community/pr, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11
