### ISSUE TITLE
Compositions broken on v13 - v14 upgrade

### ISSUE THREAD

**Issue by MGreengrassSM** [umbraco/Umbraco-CMS#16610] opened 2024-06-17 13:35 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

On old and newly created document types, compositions are not available after upgrading the database from v13.latest to v14

### Steps to reproduce

I.e. even when creating two brand new empty document types, neither is available as a composition in the other. This behaviour is not exhibited by a fresh umbraco 14 install

![Screenshot 2024-06-17 143146](https://github.com/umbraco/Umbraco-CMS/assets/121936243/89b74223-5d3d-4c22-8cc6-3dc50f876326)

### Expected result / actual result

Compositions work

**Comment by Zeegaan** [comment] 2024-07-08 11:00
Heyo 👋 
I cannot reproduce this behaviour sadly 😢 
Here is mine after upgrading from latest 13 -> v14.0.0
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/d66812e6-e82b-4327-820c-6c2e12450fda)
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/6f47fede-7bb1-4c0a-b940-a59b3987eabf)

Could you come up with some steps, so that I Can reproduce this 🙈

**Comment by anujlattice** [comment] 2024-08-20 16:26
Hi Team,

I facing issue with fresh install of umbraco 14.1.1. I am not able to see compositions. Please help me to get fix this issue.

![image](https://github.com/user-attachments/assets/a3aea957-625c-4799-b87d-7c85c599e05e)

Thanks
Anuj Tripathi

**Comment by Borc92** [comment] 2024-10-02 10:06
Hi,

same issue with fresh install of umbraco 14.2.0...

It is even missing in the documentation in the printscreen of "Create doc type":
[https://docs.umbraco.com/umbraco-cms/fundamentals/data/defining-content/default-document-types](https://docs.umbraco.com/umbraco-cms/fundamentals/data/defining-content/default-document-types)

It is a problem to create more complex pages with the current fresh install because of this... (missing in backoffice structure and consequently in the frontend as a models builder interfaces...)

**Comment by iOvergaard** [comment] 2024-10-02 14:36
Hello @anujlattice and @Borc92, the documentation has not been very clear on this, as we also discussed in the other thread, @Borc92. I have submitted a PR to explain this more explicitly. The procedure is to create any document types you need, then go into the one that should inherit the others and click the "Compositions" button in the top right corner.

As for any migrations from 13 to 14, they should be fixed in at least 14.1, but please reopen this issue if it still occurs - 14.3 will be released tomorrow, and it contains the latest of all migrations, so please try that out.

Link to UmbracoDocs PR: https://github.com/umbraco/UmbracoDocs/pull/6497

**Closed by iOvergaard** 2024-10-02 14:36 UTC
Labels: state/needs-more-info, type/bug
