### ISSUE TITLE
Block settings decimal property value always returns zero

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11682] opened 2021-11-22 18:50 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1

### Bug summary

A decimal property value in block settings saves correctly but always returns zero from the content cache (IPublishedContent).

### Steps to reproduce

Add a decimal property to block settings and try to get its value from the content cache (IPublishedContent)

### Expected result / actual result

Actual decimal value is expected, obviously :)

**Comment by bergmania** [comment] 2023-01-04 10:31
Hi @argentini.

Sorry for the ridiculously late answer 🙈 
Just tested this and cannot reproduce. I tested both 9.1 and latest v10.

I created a block list with a single block named `Tal` with a single property named `Decimal`. When I use this template it return the expected value

```cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListItem>;
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    var content = (ContentModels.Tal)Model.Content;
    var settings = (ContentModels.Tal)Model.Settings;
}

// Output the value of field with alias 'heading' from the Element Type selected as Content section
<h2>@content.Value("decimal")</h2>
<h2>@settings.Value("decimal")</h2>

<h2>@content.Decimal</h2>
<h2>@settings.Decimal</h2>

```

**Comment by argentini** [comment] 2023-01-04 17:20
Did you try settings.Value<decimal>("decimal")?

**Comment by bergmania** [comment] 2023-01-04 17:45
Same result, but had to save the result in variables, to avoid a `cannot convert from 'method group' to 'object'`

```cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListItem>;
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    var content = (ContentModels.Tal)Model.Content;
    var settings = (ContentModels.Tal)Model.Settings;

    var decimalContent = Model.Content.Value<decimal>("decimal");
    var decimalSettings = Model.Settings.Value<decimal>("decimal");
}

// Output the value of field with alias 'heading' from the Element Type selected as Content section
<h2>@Model.Content.Value("decimal")</h2>
<h2>@Model.Settings.Value("decimal")</h2>

<h2>@content.Value("decimal")</h2>
<h2>@settings.Value("decimal")</h2>

<h2>@decimalContent</h2>
<h2>@decimalSettings</h2>

<h2>@content.Decimal</h2>
<h2>@settings.Decimal</h2>

// Types
<h2>@Model.Content.Value("decimal").GetType().FullName</h2>
<h2>@Model.Settings.Value("decimal").GetType().FullName</h2>

<h2>@content.Value("decimal").GetType().FullName</h2>
<h2>@settings.Value("decimal").GetType().FullName</h2>

<h2>@decimalContent.GetType().FullName</h2>
<h2>@decimalSettings.GetType().FullName</h2>

<h2>@content.Decimal.GetType().FullName</h2>
<h2>@settings.Decimal.GetType().FullName</h2>

```

**Comment by argentini** [comment] 2023-01-04 19:02
Perhaps that was what I ran into. Thanks for all this testing!

**Comment by bergmania** [comment] 2023-01-05 06:48
`@(Model.Content.Value<decimal>("decimal"))` also works.. I will close this issue. Thanks for the quick feedback :)

**Closed by bergmania** 2023-01-05 06:48 UTC
Labels: state/needs-more-info, type/bug
