### ISSUE TITLE
v14-rc4 - History cleanup settings are still missing in document types

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16355] opened 2024-05-23 11:31 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4 

### Bug summary

The history cleanup settings in the document types are still missing. 
(i don't think this is listed anywhere as a known issue for this release?)

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/2f112040-b4fb-4b1c-bf30-a2dfa1580c06)

### Steps to reproduce

- create a doc type 
- go to the setting tab

### Expected result / actual result

there should be some UI for history, and not a TODO ?

**Comment by iOvergaard** [comment] 2024-05-23 11:52
Thanks for testing, @KevinJump. You are right. This appears to be a duplicate of #16295 which is still open, so I will go ahead and close this one :)

**Closed** 2024-05-23 11:52 UTC
Labels: type/bug
