### ISSUE TITLE
v14 richtext editor not showing any block options

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#17003] opened 2024-09-04 05:05 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

After setting up the Richtext editor with "Available blocks":
![image](https://github.com/user-attachments/assets/08743660-9cfc-4209-97f0-722021f71827)
and choosing the 'Insert Block' toolbar like so:
![image](https://github.com/user-attachments/assets/bcbb6633-deb9-4566-b845-b6c1a4d684cb)

The flyout/overlay doesn't actually contain the block option:
![image](https://github.com/user-attachments/assets/6c7af408-2379-410a-86e0-99e8bc282389)

Pretty sure the https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-blocks doc has been followed correctly - is there a known/new issue in 14.2? I thought this was working prior to the latest minor upgrade.

### Steps to reproduce

Any Richtext editor configured with blocks

### Expected result / actual result

Expected: Insert block button in RTE toolbar show flyout with configured block types
Actual: flyout that is empty, and this error in the browser devtools console:
![image](https://github.com/user-attachments/assets/3a193391-c7bc-438d-91d0-1e3ae139b2f8)

**Comment by NguyenThuyLan** [comment] 2024-09-04 10:26
Hi @shearer3000, thank you for reporting this. However, I couldn't reproduce this issue like you did. Actually, there is another issue happening here #16949. So I will close this issue to avoid duplicate, and let's check the issue I mentioned.
Feel free to reopen it if you have more details.

**Comment by arcjawsh** [comment] 2024-09-05 03:57
I am also experiencing a similar problem post upgrade to 14.2 from 14.1.1 on my development machine.

When clicking the "Insert Block" button the RTE, the Url changes to https://localhost:44300/umbraco/section/content/dashboard/dashboardTabsContentIntro.

**When using the inline editor**: Modal does not close and nothing happens.
**When using regular editor:** the page navigates back to getting started.

In addition I cannot edit existing blocks inserted into the RTE either, but they do show.

Please let me know if I can provide any more information.

**Comment by shearer3000** [comment] 2024-09-05 22:49
hi @NguyenThuyLan I see this ticket was closed and then reopened - does that mean you were able to replicate it in the end or are you still looking for more steps on how to reproduce?

**Comment by NguyenThuyLan** [comment] 2024-09-09 03:11
Hi @shearer3000 , I'm still looking for more steps on how to reproduce , I can only reproduce as the issue I mentioned

**Comment by shearer3000** [comment] 2024-09-09 21:14
hi @NguyenThuyLan 

I reported this issue from an install of Umbraco that started as an earlier version of 14 and has been subsequently upgraded to the latest (14.2.0). Thinking that might be a potential cause, I started a fresh project install and recreated the scenario again but still strike the issue.

Replication steps

1. Install umbraco 14.2.0
2. Create page doctype ("doctype with template")
3. Create some example Block element doctypes (I used "Rich Text", "Call to action" and "Feature Image").
4. Create a Block grid editor property and choose the block types from step 3. Add to page doctype as a property (I used a "Blocks" property)
5. Create a block element to be used in the RTE (I used one called "Insert Quote")
6. add block element from step 5 to Rich Text editor datatype in the Available blocks section, tick "insert block" toolbar
7. Create a content page, add the Rich Text block and attempt to add "Insert Quote" RTE block

Result
No RTE block to choose from (empty flyout), error in browser console:

![image](https://github.com/user-attachments/assets/2941856b-da1e-4bb6-97ff-0dac9f06e34c)
![image](https://github.com/user-attachments/assets/9f858775-b7b8-44b5-b707-864b773b935a)


Other Reference screenshots

![image](https://github.com/user-attachments/assets/c425f349-ceeb-4177-95d1-bf4f1cb45433)

![image](https://github.com/user-attachments/assets/0f09f478-e7ca-4c8c-9cf2-517c086017ed)

![image](https://github.com/user-attachments/assets/6afc0f11-a754-47ef-8eba-f1dae3ee79bc)

![image](https://github.com/user-attachments/assets/f65d061e-d3a9-45bf-b85f-ce068fad716f)

**Comment by shearer3000** [comment] 2024-09-09 21:16
NB @NguyenThuyLan I notice that my scenario happens when trying to add an RTE block to an existing Rich Text block (i.e. has already been added to page and published). If i try to add a new RTE and insert block, then i observe the 16949 issue you also mention. Does umbraco go through any type of QA process before being released?

**Closed** 2024-09-11 05:45 UTC
Labels: type/bug

**Comment by iOvergaard** [comment] 2024-09-11 05:50
I believe we were able to nail this issue down and fix it. The fix is slated to go out with 14.3, which will see its first release candidate next week.
