### ISSUE TITLE
JsonCamelCaseFormatter as XML

### ISSUE THREAD

**Issue by alexanderkarlsson** [umbraco/Umbraco-CMS#7238] opened 2019-11-28 05:50 UTC
A brief description of the issue goes here.

When i use the **JsonCamelCaseFormatter** for getting a camelcase JSON i don´t get a json, i get a xml version and no camelcasing

## Umbraco version

I am seeing this issue on Umbraco version: 8.3.0

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
On my UmbracoApiController i set the attribute JsonCamelCaseFormatter. So i want a camelcased json when i return my typed model.

```
[JsonCamelCaseFormatter]
public class SearchController : UmbracoApiController
{
  [System.Web.Http.HttpGet]
  public SearchAsYouTypeResultViewModel Search(string query, int pageSizeProducts = 10, int pageSizePages = 10)
  { 
```
When i also remove the **XmlMediaTypeFormatter** it works!

```
public class JsonCamelCaseFormatter : Attribute, IControllerConfiguration
    {
        public void Initialize(HttpControllerSettings controllerSettings, HttpControllerDescriptor controllerDescriptor)
        {
            //remove all json formatters then add our custom one
            var toRemove = controllerSettings.Formatters.Where(t => (t is JsonMediaTypeFormatter) || (t is XmlMediaTypeFormatter)).ToList();
            foreach (var r in toRemove)
            {
                controllerSettings.Formatters.Remove(r);
            }

            var jsonFormatter = new JsonMediaTypeFormatter
            {
                SerializerSettings =
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver()
                }
            };
            controllerSettings.Formatters.Add(jsonFormatter);
        }
    }
```

**Comment by nul800sebastiaan** [comment] 2019-11-28 09:22
I'm guessing your testing this out by going to your search endpoint in a browser?

This is "regular" MVC and if you don't send a header (`Accept:application/json`) in your request to let the endpoint know if you want JSON or XML, it will guess what you want. 
If you do the request in a browser by hitting the endpoint URL, you will get XML.

I'll close this issue for now as I believe it works as intended, let me know if I am missing something.

**Closed by nul800sebastiaan** 2019-11-28 09:22 UTC

**Comment by abjerner** [comment] 2019-11-28 10:14
Hi @alexanderkarlsson and thanks for creating this issue,

Based on the description in the XML documentation for this class, one could argue that it's purpose is only to remove the default JSON formatter, but not the XML formatter.

> Applying this attribute to any webapi controller will ensure that it only contains one json formatter with a camelCase formatter

I've only been able to find a single controller in Umbraco that uses this attribute:

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/Editors/TemplateQueryController.cs#L19

The controller extends `UmbracoAuthorizedJsonController`, which then has the `AngularJsonOnlyConfiguration` attribute ensuring the XML formatter is removed.

Would using the `AngularJsonOnlyConfiguration` attribute in your own controller solve the issue?

The default WebAPI behavior is to send either a JSON or an XML response depending on the `Accept` header of the request, so if possible given your context, you could also set the `Accept` header to `application/json`.

**Comment by abjerner** [comment] 2019-11-28 10:16
Hmm. I've had the issue open in a tab from before @nul800sebastiaan's answer, so I hadn't seen that he had replied (GitHub normally updates automatically).
