### ISSUE TITLE
Migration from 8 to 9, cannot login to backoffice with existing user

### ISSUE THREAD

**Issue by vamone** [umbraco/Umbraco-CMS#11366] opened 2021-10-13 12:39 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc003

### Bug summary

When migrating from 8 to 9, I'm unable to login to backoffice as it says that my password is invalid. 
In the console I can see following:

Invalid password for user.
User failed to provide the correct password. 

Has anything changed in the database logic for login users, hash key? Algorithms? 

As mentioned the database structure should be the same. 

My valid password is for some reason is invalid.

### Steps to reproduce

 1. Create new umbraco 9 project and connect to your umbraco 8 database.
 2. Try to login to backoffice

---
_This item has been added to our backlog [AB#15151](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15151)_

**Comment by vamone** [comment] 2021-10-14 17:34
I remember when migrating from 7 to 8, you had to change UmbracoMembershipProvider setting in web.config in order to login to backoffice. Password format was "Hashed". If I understand it correctly, there are some settings in the Startup.cs that needs to be done?

**Comment by Squiff-cmd** [comment] 2021-11-05 09:32
I have the same problem when upgrade from v8.17.0 to v9.
I too cannot login using users from restored database.

The "PostLogin" request results in the following 500 from the AuthenticationController
![image](https://user-images.githubusercontent.com/56453153/140489196-f717e19e-04f5-416a-b536-50954d00ab73.png)

**Comment by GeorgeBR** [comment] 2021-11-16 10:22
Got to say the Umbraco migration path has been shockingly painful. It's the first time I've been disappointed by Umbraco. I'm stuck with the exact same problem (v8 uses machineKey, v9 uses DataProtection API).

**Comment by bergmania** [comment] 2021-11-23 11:42
Not sure if this issue has multiple smaller issues in the comments, but I can confirm and reproduce this:
Can't login using a user from Umbraco 8, where the following settings was used:
```xml
<add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="4" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" passwordFormat="Hashed" />
```

The issue is that the user saved in the database states it uses the `HMACSHA256` algorithm, but this is overridden by the `useLegacyEncoding="true"`, so it actually uses `HMACSHA1`. This is handled in this PR https://github.com/umbraco/Umbraco-CMS/pull/11684

**Comment by bergmania** [comment] 2021-11-23 11:45
@ircnelson
Even that the machinekey is used to generate the salt, it should not be a problem - because the salt is part of the password saved in the database.

Can you see if you also used the `useLegacyEncoding="true"` config?

**Comment by bergmania** [comment] 2021-11-23 11:46
@GeorgeBR
I will need more info if I have to help you. How was you v8 users configured?

**Comment by bergmania** [comment] 2021-11-23 11:47
BTW, I tried migrating a v8.4.2 Umbraco database to latest v9.1.1, with default config, there was no problems in that configuration.

**Comment by nul800sebastiaan** [comment] 2022-01-04 09:22
We'll close this for now as the issues should be fixed in v9.1.2, if there's still remaining issues, please create a new issue with specific details about what's not working. Thanks!

**Closed by nul800sebastiaan** 2022-01-04 09:22 UTC
Labels: state/needs-more-info, state/sprint-candidate, type/bug

**Comment by p-m-j** [comment] 2022-03-09 16:35
See also #12117

**Comment by p-m-j** [comment] 2022-04-13 15:39
@nickornotto - there were some additional fixes in 9.4 relating to backoffice user password migration so it's definitely worth attempting to migrate from 8.x to the latest v9 release (9.4.3).

If that's not working for you please open a new issue with details and we will try get to the bottom of it.

**Comment by nickornotto** [comment] 2022-04-13 16:29
I have logged in successfully after I did the following:

1. In Umbraco 8.17.1 version changed `useLegacyEncoding `to `false` on `UserMembershipProvider`
2. Re-run Umbraco 8.17.1
3. Added a new admin user
4. Pointed 9.1.0 database to the 8.17.1 database with the new user added in point 3
5. Upgraded successfully

After the upgrade I noticed that my original admin user with id = -1 is not present on the list of users at all. But I am not sure why (that user used also non-email username unlike other new & old users that are present in Users section). That user is still in the database. Even if I change its username to email-like - it is still not appearing on the users list in the CMS.

New users all have "PBKDF2.ASPNETCORE.V3" unlike old users that have it as "HMACSHA256".

**Comment by techpara** [comment] 2022-06-23 06:29
Following steps works for me:

1) Create fresh database by setting fresh Umbraco 9. 
2) During setup you will have to create a user.
3) Get userPassword, passwordConfig, securityStampToken from newly create d  Umbraco 9 database and update into existing database.

Update umbracoUser SET 
userPassword='AQBAAAEAACcQAAAAEHGhLE8/y2kijtjDdY/SJPPzTXiNe7yX622ejnRT41h3Yv1EJGovXUlhqf4Adl15Tg==',
passwordConfig='{"hashAlgorithm":"PBKDF2.ASPNETCORE.V3"}',
securityStampToken='JVXS3CYZNAT2ISJXI6I4NNHFK5SHZYY1'
WHERE id=1
