### ISSUE TITLE
Uploading images to a link in RTE doesn't allow to upload images

### ISSUE THREAD

**Issue by PratheesRavindrakumarUmbraco** [umbraco/Umbraco-CMS#10643] opened 2021-07-09 16:48 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

First they experienced this:
They basically create a new page > add an RTE to the page - add some text and link it to a file > URL/File editor window opens > they select Select Media > and instead of picking an existing media file they want to Upload it (as it doesn't exist yet) 

When trying to create a link in an RTE and instead of picking an existing media item he uses the Upload button in the picker it will prompt a yellow message "Upload is not allowed in this section"

### Steps to reproduce

![image](https://user-images.githubusercontent.com/74538774/125110720-3d915780-e0e5-11eb-868e-507517efda0c.png)

![image](https://user-images.githubusercontent.com/74538774/125110909-86491080-e0e5-11eb-89c2-5eb56dea6556.png)

If you go to the page in the CMS > Highlight the link as in step 2 > Select "Select Media" button

Then try and upload media as in step 4

OR try and search for something as in step 5

### Expected result / actual result

I managed to "make it work" by clicking the "Type to search" field after not allowing to upload and voila! it works. It was a coincidence but a bug nonetheless.

**Comment by nul800sebastiaan** [comment] 2021-08-13 15:08
Hey @PratheesRavindrakumarUmbraco I am afraid I can't reproduce this, maybe I'm doing something wrong but I'll close this one for now.


https://user-images.githubusercontent.com/304656/129378016-a92945fa-03ba-42d0-91f2-cc2ab63c53a5.mp4

**Closed by nul800sebastiaan** 2021-08-13 15:08 UTC
Labels: type/bug
