### ISSUE TITLE
ncRichText no longer working in v13

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#15181] opened 2023-11-10 14:36 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc1

### Bug summary

Whilst testing out v13rc1 I came across this issue

In the block list, when using the ncRichText angular filter in the label for a block list item, it is not returning anything

### Specifics

Label configuration using ncRichText angular filter

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/2700483c-f114-47bb-b3cc-1d35b38eec80)

Doesn't show the value anymore

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/f887473d-5ddd-4e9d-85b9-5e68f965fc5d)

I think it may have been broken by this PR

https://github.com/umbraco/Umbraco-CMS/commit/915b63db29c79c6c07fe735dba946bce09cbd805

### Steps to reproduce

Create a block list data type
Add a block list item to the available blocks, this item needs to have a property on it which is a rich text property.
In configuration for the block , add this to the label field, when content is the alias of the rich text field:

```
Rich Text: {{ content | ncRichText }}
```
You will see that it only returns the first part of the label like this:

```
Rich Text:
```

but it doesn't return anything for the value of the property.

If you take the `| ncRichText` filter off it does return the value in the label but as html which is what you would expect anyway.

### Expected result / actual result

I expected the html to be returned as text in the label for a block list item but instead I got nothing.

---
_This item has been added to our backlog AB#34799_

**Comment by andr317c** [comment] 2023-11-12 19:26
Hey! 
Thanks for posting this issue! I was able to reproduce this on both the BlockListEditor and the BlockGridEditor in version 13.0.0-rc1. I tried testing it on version 12.3.1, where it was working without any issues. I will mark this issue as a sprint candidate 😄

**Comment by prjseal** [comment] 2023-11-13 15:18
Hi @andr317c 
When you work on this, please can you check the other filters too, I couldn't get the truncate one to work either, but I don't think this needs to be in a separate issue.

This cheat sheet is a good place to get the filters to check as a lot of people use it as a reference.

https://joe.gl/ombek/blog/umbraco-angularjs-filter-cheat-sheet/

Tagging @glombek so he is aware of the regression in v13.

Kind regards

Paul

**Comment by ronaldbarendse** [comment] 2023-12-01 09:24
@prjseal The commit you linked to (which is part of PR https://github.com/umbraco/Umbraco-CMS/pull/15166) actually contains the fix, but that was merged after 13.0.0-rc1 and therefore only part of 13.0.0-rc2 (and up), see the release diffs: https://github.com/umbraco/Umbraco-CMS/compare/release-13.0.0-rc1...release-13.0.0-rc2#diff-54a73489aa5044a683072a1ba688498710b5750f89c4d31e865222e16c036d88.

Can you retest this using the latest RCs and report whether we actually fixed it correctly? 😄

**Comment by andr317c** [comment] 2023-12-01 09:44
Hey again, 
I tried testing this on rc3. And it seems to be working without any issues! 
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/74510b4d-4dfd-4f11-b301-251fa5821fba)
Since this issue is fixed I'll go ahead and close this issue. 😄

**Closed by andr317c** 2023-12-01 09:44 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v13

**Comment by Andrei-** [comment] 2025-01-23 20:45
I just hit this bug in v13.5.3. Did it come back? Happens to blocks in Umbraco.NestedContent type
I didn't see this bug in a previous upgrade to v13.4.1 with block list though. Perhaps this is still affecting Umbraco.NestedContent?
