### ISSUE TITLE
Block List Inline editing mode does not work

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#16594] opened 2024-06-13 17:17 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Block List Inline editing mode does not work. You can add an item but cannot view or edit it. Also the content editor window pops up, even though it is in inline mode.

### Specifics

Block List Inline editing mode does not work. You can add an item but cannot view or edit it. Also the content editor window pops up, even though it is in inline mode.

I took a video.

https://github.com/umbraco/Umbraco-CMS/assets/87725234/d9afbc28-e21d-46d6-988c-11d2c7dc3477

### Steps to reproduce

1. In settings, add a block list data type to a content type, make it inline mode.
2. In content, add an item to the block list. Try to view the contents.

### Expected result / actual result

1. Users should be able to view and edit block list items. The content editor should not pop up when adding block items in inline mode.

**Comment by iOvergaard** [comment] 2024-06-25 07:13
Hello, and thanks for testing. I agree this is a duplicate of #16298 so I will go ahead and close this. Feel free to add to the discussion in the other issue, if you feel there is more to it!

**Closed by iOvergaard** 2024-06-25 07:13 UTC
Labels: type/bug
