### ISSUE TITLE
DocTypeGridEditor previews broken after upgrade due to IContentService.GetById(int id) returning null

### ISSUE THREAD

**Issue by tcollettCDSM** [umbraco/Umbraco-CMS#15464] opened 2023-12-15 11:42 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.2

### Bug summary

Previews in DocTypeGridEditor (v10.0.1) no longer work after upgrading from umbraco 10.7.0 to v10.8.2

### Specifics

DocTypeGridEditor tries to get the content to display in the preview by calling [GetById](https://github.com/umbraco/Umbraco-CMS/blob/release-10.8.2/src/Umbraco.Core/Services/IContentService.cs#L77)  [in its constructor](https://github.com/skttl/umbraco-doc-type-grid-editor/blob/dev-v10/src/Our.Umbraco.DocTypeGridEditor/Models/UnpublishedContent.cs#L22) and then [tries to get the content type from this](https://github.com/skttl/umbraco-doc-type-grid-editor/blob/dev-v10/src/Our.Umbraco.DocTypeGridEditor/Models/UnpublishedContent.cs#L30)

After doing some debugging locally, I found that the GetById was returning null despite the fact a POST to `/umbraco/backoffice/umbracoapi/content/PostSaveBlueprint` has happened by this point (demonstrated by video in repro steps)
![image](https://github.com/umbraco/Umbraco-CMS/assets/55742614/e752b2c3-4455-445e-b115-760e33a134ac)

This was working in 10.7.0, so the issue probably was introduced after that point (changelog for 10.8.0 mentions performance optimisations for blocks which might be relevant?)

### Steps to reproduce

1. Author a NestedContent item with an element type inside (I use a rich text editor in this example)
2. Open devtools & click submit in the editor
3. See the preview not update and the 500 error in devtools

https://github.com/umbraco/Umbraco-CMS/assets/55742614/fddf1acd-e07d-4850-8e0d-44179012c3e2

### Expected result / actual result

IContentService.GetById(int id) should not return null  when it didn't before

**Comment by Zeegaan** [comment] 2023-12-15 11:56
I will close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/15464
Seems the /umbraco/backoffice/umbracoapi/content/PostSaveBlueprint has been broken

**Closed by Zeegaan** 2023-12-15 11:56 UTC
Labels: type/bug

**Comment by tcollettCDSM** [comment] 2024-01-11 09:36
Updated to 10.8.3 but the issue I flagged still remains unfortunately, any chance this'll be looked at at again?

**Comment by Zeegaan** [comment] 2024-01-11 09:56
There has been a discussion on https://github.com/umbraco/Umbraco-CMS/issues/15460 about DocTypeGridEditor, so I will refer you to that issue 😁
