### ISSUE TITLE
V8.7RC BlockList - Datatype switch hangs in CMS

### ISSUE THREAD

**Issue by ault** [umbraco/Umbraco-CMS#8733] opened 2020-08-26 10:40 UTC
- Doctype has property using "BlockListA" as editor. 
- Some content has been entered. 
- Property editor is changed to "BlockListB". Warning is accepted that content will be lost
- On the pages where content existed, nothing is displayed. Not the new editor, not the old editor. Just the JS action indicator (three swelling dots).
- Clicking on the property actions and selecting "Remove all items" brings up a delete confirmation screen - but the Delete button does nothing.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7rc

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Changing the datatype for the property editor from one Block List to another leads to a hanging cms editor when a node had content in the property. The  "Remove all items"  dialog does not work.

### Specifics

Firefox 78.0.2
Edge 84.0.522.63 

### Steps to reproduce

1. Create content in a blocklist property
2. Change that doctype property to use a different blocklist editor
3. Attempt to edit the original node

### Expected result

I would expect an empty node where there had previously been content.

### Actual result

Can see the property label, and "in progress" js dots where the content/blocklist editor should be.
Devtools console report included as txt and (better readability) image. 

Sorry if there is a better way to report this, I'm a complete noob at working on open source.
![devtools console error ](https://user-images.githubusercontent.com/7056441/91293984-241b4180-e799-11ea-810b-92e79aaecc48.png)
[devtools console error.txt](https://github.com/umbraco/Umbraco-CMS/files/5129238/devtools.console.error.txt)

**Comment by nul800sebastiaan** [comment] 2020-08-27 09:50
Thanks @ault - I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8709

**Closed by nul800sebastiaan** 2020-08-27 09:50 UTC
