### ISSUE TITLE
Grid Rte Media Item File Path Not Being Rendered

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#7248] opened 2019-11-28 15:11 UTC
In the grid, inside a rich text editor, when I add an image, the image file path does not get rendered on the front end. It shows fine in the back office, but on the front end, in the img src attribute it just has the query string without the file path.

Like this:

```html
<img src="?width=730&amp;height=451.73267326732673" alt="" width="730" height="451.73267326732673" data-udi="umb://media/37ad87fd4336456b8a58257f59799aa5">
```

## Umbraco version

This is happening in an Umbraco Cloud site currently on version 8.3
This site was originally created in version 8.15

I have set up a new installation of cloud on 8.30 to test it and it works fine, so it might be something that was not fixed by the upgrades from 8.15 to 8.3

**Comment by prjseal** [comment] 2019-11-28 15:41
I seem to have been able to fix it by installing a fresh instance of umbraco and copy all of the files in `/umbraco` and `/Views/Partials/Grid/`

There are lots of differences, so it seems that when Umbraco cloud does its upgrade, these files don't get updated.

The file which seems to be the one which has resolved the issues is `/Views/Partials/Grid/Editors/Rte.cshtml`

It was previously like this:

```csharp
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider))
```

And is now like this

```csharp
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates
@{
    var value = TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider);
    value = TemplateUtilities.ResolveUrlsFromTextString(value);
    value = TemplateUtilities.ResolveMediaFromTextString(value);
}
@Html.Raw(value)
```

What is now more worrying is that the Umbraco Cloud upgrades are not upgrading all of the files meaning things like this will be missed off when upgrading.

**Comment by nul800sebastiaan** [comment] 2019-11-28 17:01
Thanks @prjseal - that is obviously a mistake! I will pass this on to the Cloud team and close this one as it's not an actual Umbraco issue. Thanks very much for digging in! 👍

**Closed by nul800sebastiaan** 2019-11-28 17:01 UTC

**Comment by huwred** [comment] 2020-07-29 09:40
It would appear this is an issue in 8.6.3 nuget package, my /Views/Partials/Grid/Editors/Rte.cshtml was exhibiting the same issue, changing the code to 

`@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates
@{
    var value = TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider);
    value = TemplateUtilities.ResolveUrlsFromTextString(value);
    value = TemplateUtilities.ResolveMediaFromTextString(value);
}
@Html.Raw(value)`

Resolved the problem, but in VS it complains that TemplateUtilities is deprecated, so what should the correct code for 8.6.3 actually be

**Comment by huwred** [comment] 2020-07-29 10:14
problem was caused by installing the codeshare starter package, in case anyone else trys this.
