### ISSUE TITLE
Validation messages for blocklists show HTML markup.

### ISSUE THREAD

**Issue by Eaglef90** [umbraco/Umbraco-CMS#15697] opened 2024-02-10 00:04 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.0

### Bug summary

If you have a blocklist that has a min/max requirement when the page is validated and a validation error is shown the html markup is shown instead of processed. My screenshot is from my 13.1.0 install but bug 15368 has screen shots showing it in 12.2.0 as well.

![Screenshot 2024-02-09 185843](https://github.com/umbraco/Umbraco-CMS/assets/4780824/d0d978fe-3dc9-4a0b-b6b1-4c910191ad87)

### Steps to reproduce

Create a Blocklist with either a minimum or maximum amount of entries.
Create a content node based off of a document type that includes this blocklist.
Do not meet the validation requirements when hitting "save"

### Expected result / actual result

Either the HTML markup is processed correctly or just striped out and ignored.

**Comment by andr317c** [comment] 2024-02-15 07:39
Hey! 
Thanks for reporting this issue, it seems like it is a duplicate of #15368. I will go ahead and close this issue

**Comment by Eaglef90** [comment] 2024-02-15 11:27
This is not a duplicate of that issue. That issue is talking about validation triggering when it should not. My issue is about the HTML markup code displaying in the validation error message. I only linked to that issue to show it existed in older versions as well.

**Comment by andr317c** [comment] 2024-02-15 11:38
I must've misunderstood, sorry about that. I will reopen the issue 😄

**Comment by andr317c** [comment] 2024-02-15 11:44
I was able to reproduce this issue on versions 13.1.1 and 12.3.7. I will mark this issue as an up for grabs

**Comment by mikecp** [comment] 2024-03-09 00:27
Closed as per merging of PR #15852

**Closed by mikecp** 2024-03-09 00:27 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/frontend, affected/v12, affected/v13
