### ISSUE TITLE
Button overlaps block items when availableBlockTypes == 1

### ISSUE THREAD

**Issue by pdavis86** [umbraco/Umbraco-CMS#11803] opened 2021-12-29 16:19 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

I have a block list data type that only allows one block type and the button for adding items covers the items I have added:
![image](https://user-images.githubusercontent.com/30239659/147681902-522a02bc-54d4-42ee-937d-5ad423a5739b.png)

If I use Dev Tools to delete the button I can see the items underneath:
![image](https://user-images.githubusercontent.com/30239659/147681984-fb13ed34-f952-4b5f-a93f-dd7a7e1a49ee.png)

### Steps to reproduce

- Create a new data type of type "Block List"
- Select only 1 block type
- Save
- Create a document type and save
- Create a property that uses the data type above
- Observe than when items are added, the button overlays them

### Expected result / actual result

The button should be in the same place for block lists that allow multiple items:
![image](https://user-images.githubusercontent.com/30239659/147682497-157fe6ca-ca54-46f3-b4eb-1927b6e8420f.png)

**Comment by nul800sebastiaan** [comment] 2022-01-03 14:39
Hi there @pdavis86 - that doesn't look right.. But not sure what's going on, I can't reproduce the given scenario: 

https://user-images.githubusercontent.com/304656/147942954-8c28490f-ead3-4d53-beb6-88dff5dc3179.mp4

 Do you have more info on how to reproduce this on a clean install? 
 
The only thing I can think of at the moment is that you might have upgraded from v9.0.x to 9.1.x and not all the files in the Umbraco folders have been updated correctly. Might help to delete `~/wwwroot/umbraco` completely and do a new build and run. 

I'll close this issue for now but if you have more info on how to reproduce or see what I did differently from you then please leave a comment and we can have another look.

**Closed by nul800sebastiaan** 2022-01-03 14:39 UTC
Labels: type/bug

**Comment by pdavis86** [comment] 2022-01-04 09:29
OK, found the problem. It because I name the property "navigation". Umbraco outputs a button with id="navigation" which then picks up styling which was not intended for that button.

**Comment by nathanwoulfe** [comment] 2022-01-04 23:16
There's a pending V8 PR to refactor the use of IDs for styling - #9087

Been hanging around for a while but I can't merge my own PR...
