### ISSUE TITLE
Umbraco 9 custom language files

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#12096] opened 2022-03-03 14:29 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

User language files causing error.

### Specifics

Unable to override default language files.

### Steps to reproduce

Create file at /umbraco/config/lang/en_us.user.xml

### Expected result / actual result

Should be able to override default language translations. Adding the user language file for your chosen language causes the following error:

`CultureNotFoundException: Culture is not supported. (Parameter 'name') en-us.user is an invalid culture identifier.`

**Comment by KevinJump** [comment] 2022-03-03 14:51
Hi, 

I am not sure if it's wrong in the docs (some one else has mentioned this to me recently) - but i think the lang files actually go in 

`~/config/lang` 

so at the root of the site, you need to create the config folder its not the /umbraco one .

**Comment by uSkinned** [comment] 2022-03-03 15:11
Wierd, must have read it wrong. Although now added to ~/config/lang and no override is happening.

**Comment by nul800sebastiaan** [comment] 2022-03-04 09:08
This one works for me: ~/config/lang/en_us.user.xml`

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<language alias="en_us" intName="English (US)" localName="English (US)" lcid="" culture="en-US">
    <area alias="login">
        <key alias="greeting0">uSkinned super Sunday</key>
        <key alias="greeting1">uSkinned manic Monday </key>
        <key alias="greeting2">uSkinned tubular Tuesday</key>
        <key alias="greeting3">uSkinned wonderful Wednesday</key>
        <key alias="greeting4">uSkinned thunderous Thursday</key>
        <key alias="greeting5">uSkinned funky Friday</key>
        <key alias="greeting6">uSkinned Caturday</key>
	</area>
</language>
```

![image](https://user-images.githubusercontent.com/304656/156733185-1ce8bb00-9740-47e7-9daa-7e8efdbc65f7.png)

Remember to restart the site to see the updated text. I made a mistake as well, forgot `</area>`, my console told me about it, so maybe you see some errors like this in yours too?

![image](https://user-images.githubusercontent.com/304656/156733498-d460730b-0884-48f9-ba30-056e1d9b80db.png)

In any case, this all works as expected so I'll close this issue. If you have any steps to reproduce it not working on a fresh install we can have another look though.

**Closed by nul800sebastiaan** 2022-03-04 09:08 UTC
Labels: type/bug

**Comment by uSkinned** [comment] 2022-03-04 14:52
Thanks @nul800sebastiaan all good. Sorry to waste your time on this. I was missing the xml and language tags.

**Comment by nul800sebastiaan** [comment] 2022-03-05 08:34
No worries, I re-learned all about the translation files again! ;-)
