### ISSUE TITLE
If Umbraco.EmailAddress isn't mandatory it should be posible to be saved as empty

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#3013] opened 2018-09-21 08:17 UTC
Reproduction
-----------

I have created a DocType with the Umbraco.EmaillAdress DataType, and the e-mail is not set to required.

### Expected result

I expected the validation to only be invoked when the field had content.

### Actual result

Umbraco wont save the doctype without a valid e-mail, it says: "Property has errors".

**Comment by renetruelsen** [comment] 2018-10-25 14:55
I was able to reproduce this issue. 
It seems that there are some conflicts between different levels of validations on the Umbraco.Email field vs RegEx. I'll try and dig into it

**Comment by renetruelsen** [comment] 2018-10-27 07:11
Ok. Here is what I got so far. The problem with the Email PropertyEditor is that it by default undergoes two different checks for correct email syntax. 
1) It uses a client side angular regex: /^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i  (this specific validation rule has been changed a bit forth and back in 2016 and again in september 2017). This client side validation is used several places in the backend, for example when creating a user.

2) And the propertyeditor also uses the build in .NET "EmailAddressAttribute". 

The problem is basically that these two validate differently and is thus handled differently. 
For example "test@test" is by 1) considered valid, but by 2) not considered valid. The result is that the data is stored but when the page is updated, it gives an "Email is invalid"-error. 
But notice! The data is actually stored, and on a node refresh (F5), there is no information that the email is invalid.

...for now I've decided to keep the custom regex validation out of the discussion, but this is also serverside validation, and thus acts similar to 2).

My question is - what is the proper solution for this? 
My suggestion is either to align the email-syntax validation between the angular front-end and "EmailAttribute" back-end, and at the same time change the default "Validate as an email address"-expression to be the same as the one used in the angular check.
Or - maybe completely remove the backend syntax check on email addresses, since it's redundant?

What do you think?

**Comment by renetruelsen** [comment] 2018-10-31 06:44
...submitted a PR for this issue

**Comment by stevetemple** [comment] 2020-08-18 10:41
If the PR is being rejected on the grounds of it being for v7.x and that not having any new bug fixes/features. Is this still happening in v8 or can we close this as won't be done.

**Comment by nul800sebastiaan** [comment] 2020-08-18 10:49
@stevetemple Hmm, I probably should have closed this issue too. However, if it's still a problem in v8 (I am assuming that's why you're asking?) then I'd love to see it fixed in v8! Did you have the experience of this still being a problem Steve?

**Comment by stevetemple** [comment] 2020-08-18 10:51
I'm going to check now, realised when I wrote that I was being lazy.

**Comment by stevetemple** [comment] 2020-08-18 10:59
OK, so in V8 if you add email address and say it's required on the email datatype itself but not mandatory when added to the doctype you'll get validation errors despite the field not showing as required.

![image](https://user-images.githubusercontent.com/113788/90505051-e93a5d80-e149-11ea-9833-b06ae2bca89a.png)

If it's not required and not mandatory it's fine. Mandatory but not required it works as expected with required indicator showing

**Comment by nul800sebastiaan** [comment] 2020-08-18 11:05
Thank you! Alright, so: while confusing, it's workable. 

We really shouldn't have the "required" property on the datatype but removing it now would be breaking. I know we have ideas around making mandatory/regex validation/default values better in the future so this would be part of the cleanup.

I would suggest we remove "required" from the datatype view (so just from the html file), and always set it to false. That way we don't break backwards compat and we have all the features we need to make it mandatory. The `Required` property can then be marked as obsolote. 
Does that make sense?

**Comment by stevetemple** [comment] 2020-08-18 11:21
Sounds workable, want me to take a run at that tonight?

**Comment by nul800sebastiaan** [comment] 2020-08-18 11:24
@stevetemple 🙏 Would be awesome!

**Comment by poornimanayar** [comment] 2020-08-19 13:05
Fixed in #8655

**Closed by poornimanayar** 2020-08-19 13:05 UTC
Labels: community/pr, release/8.8.0, type/bug
