### ISSUE TITLE
V8 - Mapping a route to a backoffice Mvc Controller

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#5005] opened 2019-03-18 11:57 UTC
I'm not saying 'I want' to do this, and support for this may have been dropped in V8 - however I'm updating the documentation to use composition and components where previously applicationstarting event examples exist - (prioritisation driven by forum questions)

I'm looking at this page: 

https://our.umbraco.com/documentation/reference/routing/Authorized/

which outlines advice for running an MVC Controller (not api controller) in the backoffice, this does appear to work in V7.

The equivalent I have perceived for V8 is:

```
namespace Umbraco8.Components
{
    public class RegisterCustomBackofficeMvcRouteComposer : ComponentComposer<RegisterCustomBackofficeMvcRouteComponent>
    {

    }

    public class RegisterCustomBackofficeMvcRouteComponent : IComponent
    {
        public void Initialize()
        {
            var umbracoPath = System.Configuration.ConfigurationManager.AppSettings["Umbraco.Core.Path"];
            if (umbracoPath.StartsWith(SystemDirectories.Root)) // beware of TrimStart, see U4-2518
                umbracoPath = umbracoPath.Substring(SystemDirectories.Root.Length);
           umbracoPath = umbracoPath.TrimStart('~').TrimStart('/').Replace('/', '-').Trim().ToLower();
            RouteTable.Routes.MapRoute("cats", umbracoPath + "/backoffice/cats/{action}/{id}", new
            {
                controller = "cats",
                action = "meow",
                id = UrlParameter.Optional
            });
        }

        public void Terminate()
        {
            throw new NotImplementedException();
        }
    }
}
```
with Cats Controller defined as:

```
namespace Umbraco8.Controllers
{

    public class CatsController : UmbracoAuthorizedController
    {
        // GET: Cats
        public ActionResult Meow()
        {
            return View();
        }
    }
}
```
This appears to route correctly to the CatsController when you visit the url /umbraco/backoffice/cats/meow 

but LightInject throws an error

Unable to resolve type: Umbraco8.Controllers.CatsController, service name:

see screen grab

![image](https://user-images.githubusercontent.com/260802/54528380-bf896f80-4974-11e9-8993-8201f6cf38b6.png)

UmbracoAuthorizedApiControllers are just fine, but I suspect it's because they are autorouted...and so somehow LightInject is aware of their service name.

Also UmbracoMapRoute is fine for front end custom route mapping with a virtual node route handler.

This is specifically mapping a custom route for an MVC controller to be used in the backoffice (so it's either a bug, or different in V8 or no longer supported, and I can update the docs accordingly)

**Comment by nul800sebastiaan** [comment] 2019-03-25 13:07
Interesting, I thought they were auto-routed too. I'll have to discuss at HQ and figure out what is going on.

**Comment by marcemarc** [comment] 2019-03-25 14:37
They aren't auto-routed, as you have to supply the route for them to work.... but what I think is they aren't auto registered with the LightInject container... it seems like 'PluginControllers, UmbracoAuthorizedApiControllers etc are but not UmbracoAuthorizedControllers (the comments seem to indicate that scanning by type is really expensive, so wonder if it's a conscious decision not to scan for them?)

**Comment by Shazwazza** [comment] 2019-03-26 05:29
We can't auto register every controller in every assembly. It would grind startup down startup time. We auto-scan some Mvc and Webapi controllers, so based on the ones we auto scan for, we also auto register those ones too. For controllers we don't auto scan for, these will have to be manually registered in DI in the composer.

Part of the reason the above description is a little confusing is the difference between WebApi and MVC which are totally different things in .Net Framework. The mention of `UmbracoAuthorizedController` is MVC (not WebApi) and it's namespace is `Umbraco.Web.Mvc.UmbracoAuthorizedController`. It's certainly a more rare thing to have an MVC controller used in the back office. These controllers are neither auto routed or auto scanned so they cannot be auto registered.

For MVC, all things inheriting from `Umbraco.Web.Mvc.PluginController` are auto registered. A `SurfaceController` is auto routed and inherits from `PluginController` so it's auto registered too. All implementations of `IRenderMvcController` which are used for route hijacking are auto registered. 

For any custom MVC or WebApi controllers, developers will need to register these themselves in DI that are not a sub class of: `IRenderMvcController`, `PluginController`, `UmbracoApiController`.

To do that in the most efficient way, a developer would do this in their composer:

```cs
public override void Compose(Composition composition)
{
   //You can do this for a single controller - Lifetime is MEGA important
   composition.Register(typeof(MyController), Lifetime.Request);
}
```

Unfortunately, we haven't exposed publicly our `RegisterControllers` ext method which we definitely should to make this easier. Currently this method is in `Umbraco.Web.Composing.CompositionExtensions.Controllers`. If we make this public then you can do:

```cs
public override void Compose(Composition composition)
{
   //You can do this for a single controller
   composition.RegisterControllers(new[] { typeof(MyController) });

   //You can do this for a multiple controllers
   composition.RegisterControllers(new[] { typeof(MyController), typeof(MyOtherController) });
}
```

**Comment by marcemarc** [comment] 2019-03-26 07:51
Hi @Shazwazza, thanks! yes, not 'for' type scanning - I'm just trying to understand why,  so I can reply to forum question and update docs! It's a niche scenario to run an MvcController in the backoffice - so having an extra step to register the controller is fine, as long as it's possible and we document it. I'll double check that 'register' works as I did try this...

I did find (from reading the CompositionExtensions) - if I make the controller inherit from PluginController and use the [IsBackOffice] attribute (from the api namespace!) then the custom route works via /umbraco/backoffice and it is registered with lightinject too.. but presumably that will be missing stuff from UmbracoAuthorizedController - although most of that functionality comes from the [UmbracoAuthorize] attribute.

But all makes sense, if I can get the controller registered manually I'll report back and update the docs.

**Comment by Shazwazza** [comment] 2019-03-26 08:28
`PluginController` is not auto-routed, the *only* controllers that are auto-routed are: SurfaceControllers (which does inherit from PluginController) and UmbracoApiController. The IsBackOffice attribute is just for these auto-routed controllers.

PluginController is really just a nice-to-have thing if you want to create MVC controllers since these will be auto-registered. So yes, if you want to have an authorized MVC controller that is auto registered you can inherit from PluginController and add these attributes: [UmbracoAuthorize], [DisableBrowserCache] and it will behave exactly the same as UmbracoAuthorizedController.

**Comment by marcemarc** [comment] 2019-03-26 09:48
Yep, (you still supply the route!) ... right have tested, manually registering the UmbracoAuthorizedController works (as of course it should) - I think I tried to register it with an interface in my experiment, didn't realise it was as simple as that!

so I'll update the docs to still suggest to use UmbracoAuthorizedController for this kind of thing + manual composing, I can see dev's thinking that the PluginController is 'one less class' to create, but they'd need to remember to decorate with the correct attributes etc, and seems less intuitive to teach.

I did have an unrelated question, that I should probably create under a new issue... apologies but if I want to promote the use of a 'Service' class... for common code to be called from different controllers in a solution eg
```
public class MySuperNewsArticleFetchingService : ISuperNewsArticleFetchingService
{
private readonly IPublishedContentQuery _contentQuery;

public MySuperNewsArticleFetchingService(IPublishedContentQuery contentQuery){
_contentQuery = contentQuery;
}

public IEnumerable<IPublishedContent> GetTopNews(id siteId){
 var site = contentQuery.Content(siteId);
//etc
}
}
```
What would be the best way of wiring this up via DI so I could inject this custom service into the controllers?

If I use an IUserComposer, then we're not guaranteed to have an UmbracoContext at this time, so I'm not sure how to inject only the IPublishedContentQuery aspect

```
    public class RegisterMySuperNewsArticleFetchingServiceComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Register<ISuperNewsArticleFetchingService, MySuperNewsArticleFetchingService>(Lifetime.Request);

}
```

in Ninject I'd pass it in during registration from the Request scope (which of course might only work by luck)

So I know I can inject IUmbracoContextAccessor, and call EnsureUmbracoContext() and use the ContentCache...

...but what I'm trying to find is a way to promote writing common code outside of a Controller/View but using the familiarity of the methods exposed in those contexts eg IPublishedContentQuery methods, butwithout having to 'new' up the services, eg 
`var newsService = new MySuperNewsArticleFetchingService(Umbraco.ContentQuery); `

eg working 'with' the new simple DI approach.

 (I'm not suggesting a base UmbracoBaseService class which is typed scanned :-P)

Maybe I just need to think about this more, apologies for the brain dump!

**Comment by Shazwazza** [comment] 2019-03-26 10:08
what you had will work just fine:

```cs
composition.Register<ISuperNewsArticleFetchingService, MySuperNewsArticleFetchingService>(Lifetime.Request);
```

During composition, nothing is resolved, you are just telling the container 'hey, when something asks you to make a `ISuperNewsArticleFetchingService`, use the concrete implementation of `MySuperNewsArticleFetchingService` and make sure it's scoped to a request. And you'd definitely want it scoped to a request because the dependency `IPublishedContentQuery` is scoped to a request.

Now, if you want to allow this service to access the content cache with a singleton scope (default) since maybe you want to use this on a background thread or something, you can still do that but it's more work. But definitely please do not use `IUmbracoContextAccessor` + `EnsureUmbracoContext`, instead you would inject: `IUmbracoContextFactory` and do this (for example):

```cs
        using (var reference = _umbracoContextFactory.EnsureUmbracoContext())
        {
            var content = reference.UmbracoContext.ContentCache.GetById(1103);
            if (content == null) throw new Exception("!");
            _logger.Debug<TestComponent>("DEBUG " + content.Name);
        }
```

**Comment by marcemarc** [comment] 2019-03-26 10:55
Yes, which is where I started via intuition....

      composition.Register<ISuperNewsArticleFetchingService, MySuperNewsArticleFetchingService>(Lifetime.Request);

but as soon as I have IPublishedContentQuery in the constructor

`public MySuperNewsArticleFetchingService(IPublishedContentQuery contentQuery){`

and start up the site, I get a 'Boot Fail', and I assumed I was doing it wrong:

So I suspect somehow that IPublishedContentQuery is not something it knows how to inject?

 System.NullReferenceException: Object reference not set to an instance of an object.
  at Umbraco.Web.Runtime.WebInitialComposer.<>c.<Compose>b__0_5(IFactory factory)
  at Umbraco.Core.Composing.LightInject.LightInjectContainer.<>c__DisplayClass20_0`1.<Register>b__0(IServiceFactory f)
  at DynamicMethod(Object[] )
  at LightInject.ServiceContainer.<>c__DisplayClass150_0.<WrapAsFuncDelegate>b__0() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3798
  at LightInject.PerRequestLifeTime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6207
  at DynamicMethod(Object[] )
  at LightInject.ServiceContainer.<>c__DisplayClass150_0.<WrapAsFuncDelegate>b__0() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3798
  at LightInject.PerRequestLifeTime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6207
  at DynamicMethod(Object[] )
  at LightInject.ServiceContainer.<>c__DisplayClass150_0.<WrapAsFuncDelegate>b__0() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3798
  at LightInject.ServiceContainer.<>c__DisplayClass198_0.<EmitLifetime>b__1() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4657
  at LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6169
  at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4656
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__1(IEmitter methodSkeleton) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4649
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4158
  at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4120
  at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4080
  at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4034
  at LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3929
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__2(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4649
  at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3776
  at LightInject.ServiceContainer.<>c__DisplayClass198_0.<EmitLifetime>b__1() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4657
  at LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6169
  at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4656
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__1(IEmitter methodSkeleton) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4649
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4158
  at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4120
  at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4080
  at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4034
  at LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3929
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__0(IEmitter methodSkeleton) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4646
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4158
  at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4120
  at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4080
  at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4034
  at LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3929
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__0(IEmitter methodSkeleton) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4646
  at LightInject.ServiceContainer.EmitNewArray(IList`1 emitMethods, Type elementType, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3631
  at LightInject.ServiceContainer.<>c__DisplayClass187_0.<CreateEmitMethodForEnumerableServiceServiceRequest>b__6(IEmitter e) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4570
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4158
  at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4120
  at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4080
  at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4034
  at LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3929
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__0(IEmitter methodSkeleton) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4646
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3776
  at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4743
  at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4705
  at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3437
  at Umbraco.Core.Composing.LightInject.LightInjectContainer.GetInstance(Type type)
  at Umbraco.Core.Composing.ComponentCollectionBuilder.CreateItem(IFactory factory, Type itemType)
  at Umbraco.Core.Composing.CollectionBuilderBase`3.<>c__DisplayClass10_0.<CreateItems>b__0(Type x)
  at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
  at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
  at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at Umbraco.Core.Composing.CollectionBuilderBase`3.CreateItems(IFactory factory)
  at Umbraco.Core.Composing.ComponentCollectionBuilder.CreateItems(IFactory factory)
  at Umbraco.Core.Composing.CollectionBuilderBase`3.CreateCollection(IFactory factory)
  at Umbraco.Core.Composing.LightInject.LightInjectContainer.<>c__DisplayClass20_0`1.<Register>b__0(IServiceFactory f)
  at DynamicMethod(Object[] )
  at LightInject.ServiceContainer.<>c__DisplayClass150_0.<WrapAsFuncDelegate>b__0() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3798
  at LightInject.ServiceContainer.<>c__DisplayClass198_0.<EmitLifetime>b__1() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4657
  at LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6169
  at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4656
  at LightInject.ServiceContainer.<>c__DisplayClass197_0.<ResolveEmitMethod>b__1(IEmitter methodSkeleton) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4649
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3776
  at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4743
  at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4705
  at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3437
  at Umbraco.Core.Composing.LightInject.LightInjectContainer.GetInstance(Type type)
  at Umbraco.Core.FactoryExtensions.GetInstance[T](IFactory factory)
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)

**Comment by Shazwazza** [comment] 2019-03-26 11:23
Where are you consuming your `ISuperNewsArticleFetchingService` ? Like where are you injecting this into? IPublishedContentQuery is registered in DI, but its registered with a factory. I have a feeling it's throwing a null ref because it's trying to be resolved in a non-request thread and the IUmbracoContextAccessor.UmbracoContext is null at that point.

(closing this issue)

**Closed by Shazwazza** 2019-03-26 11:23 UTC
Labels: state/hq-discussion-cms

**Comment by marcemarc** [comment] 2019-03-26 11:37
A Hijacked RenderMvcController

   public class BlogPostController : Umbraco.Web.Mvc.RenderMvcController
    {        // GET: BlogPost   
        private readonly ISuperNewsArticleFetchingService _superNewsArticleFetchingService;
        private readonly ILogger _logger;
        public BlogPostController(ISuperNewsArticleFetchingService superNewsArticleFetchingService, ILogger logger)
        {
            _superNewsArticleFetchingService = superNewsArticleFetchingService;
            _logger = logger;
    
        }

**Comment by Shazwazza** [comment] 2019-03-26 12:08
Ah, if you are injecting things into controllers, you **must** call the controller's non-empty constructor! non-empty constructors on controllers are only there for people that just refuse to to DI.

You can easily generate this constructor on your controller in VS by pressing ctrl + . next at the end of the ` : RenderMvcController` statement, see 

![image](https://user-images.githubusercontent.com/1742685/54995908-0c77e080-501c-11e9-8bdb-e537a0d4aa91.png)

Then you can add you own custom ctor params.

**Comment by marcemarc** [comment] 2019-03-26 14:18
Yes, so I can't decide if it's a bug or I'm being monumentally stupid... :-) there is often a thin line between the two:

if I have this:

```
      public BlogPostController(IGlobalSettings globalSettings, IUmbracoContextAccessor umbracoContextAccessor, ServiceContext services, AppCaches appCaches, IProfilingLogger profilingLogger, UmbracoHelper umbracoHelper, ILogger logger, ISuperNewsArticleFetchingService superNewsArticleFetchingService) : base(globalSettings, umbracoContextAccessor, services, appCaches, profilingLogger, umbracoHelper)
        {
            _superNewsArticleFetchingService = superNewsArticleFetchingService;
            _logger = logger;
        }
```
Then it blows up when my superNewsArticleFetchingService tries to inject IPublishedContentQuery as a dependency

```
public MySuperNewsArticleFetchingService(IPublishedContentQuery contentQuery){
_contentQuery = contentQuery;
}
```

but if instead I inject 'other' dependencies'

```
public MySuperNewsArticleFetchingService(ILogger logger, IUmbracoContextFactory contextFactory){
            _logger = logger;
            _contextFactory = contextFactory;
}
```
it's all fine, as you and I would expect... 

... so the issue appears to be with injecting IPublishedContentQuery, but that seems registered ok here:

```
   composition.Register<IPublishedContentQuery>(factory =>
            {
                var umbCtx = factory.GetInstance<IUmbracoContextAccessor>();
                return new PublishedContentQuery(umbCtx.UmbracoContext.PublishedSnapshot, factory.GetInstance<IVariationContextAccessor>());
            }, Lifetime.Request);
```

https://github.com/umbraco/Umbraco-CMS/blob/6880937b906beec04aa2a991323e373da70f1b99/src/Umbraco.Web/Runtime/WebInitialComposer.cs#L99

Anyway if you think it 'should' work then I'll create it as a separate issue, as I'm doing that annoying thing of gabbling on, on a closed issue!

**Comment by Shazwazza** [comment] 2019-03-28 04:10
@marcemarc it is odd! I mean it should work and `IPublishedContentQuery` is already being injected into things like UmbracoHelper, TagQuery, etc...  Do you get an issue if you inject UmbracoHelper into your service and access `helper.ContentQuery`?

**Comment by marcemarc** [comment] 2019-03-29 00:06
Yes it is the same error with injecting UmbracoHelper

**Comment by Shazwazza** [comment] 2019-03-29 00:17
That seems very odd. I haven't had time to replicate just yet, must be something I'm not seeing by just looking at your code. Maybe best to raise another issue with reproduction steps.

**Comment by marcemarc** [comment] 2019-03-29 19:43
Yep, will do, I'll pull the source and step through as well, maybe it's something obvious - and thanks for help on the backoffice route - code examples now updated in the docs: https://our.umbraco.com/documentation/Reference/Routing/Authorized/

**Comment by marcemarc** [comment] 2019-04-08 23:11
@Shazwazza It all works as expected (in case you wanted closure on this :-)) - in addition to the controller I was testing the custom service and the injection of IPublishedContentQuery in, I had also previously injected it into an IContentLastChanceFinder! - so it was this which was blowing up, not the injection into a service used in a controller. So all new solution, wired up as above, all 'just works' which is nice.

**Comment by Shazwazza** [comment] 2019-04-09 01:16
@marcemarc thanks for letting me know :)
