### ISSUE TITLE
Link to non-image in RTE is not updated after updating the file in Media section

### ISSUE THREAD

**Issue by intoxicating** [umbraco/Umbraco-CMS#15278] opened 2023-11-21 15:48 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

7.15.1

### Bug summary

In context:
My solution is using UmbracoCMS v7.15.1 and Azure Blob as media storage v0.5.2-beta. 
I am using RTE in most of pages to allow content editors to add link and images as content. 

However, i noticed that after updating an existing media item using a different file name from Media section, the updates did not reflect to the RTE where the file was being referenced and the links leads to 404

### Steps to reproduce

1. Upload a non-image file in Media section (e.g Test1.pdf)
2. Go to a page with RTE and insert a link referencing the pdf file from the media section and save and publish
3. Access the page and the file can be open from the link
4. Using the media item uploaded in step 1, replace the existing file with other non-image (e.g Test2.pdf/ABC.xlsx)
5. Refresh the page in Step 3 and the link is still pointing to the Test1.pdf

**Comment by kjac** [comment] 2023-11-27 08:01
Hi @intoxicating,

Thanks a lot for reaching out and reporting this 💪 

As you might be aware, V7 is end of life and no longer actively supported. 

I have tried reproducing this without luck in V8 and V10, so I assume it must have been fixed somewhere along the line. I highly recommend you upgrade your site to V8 or later 😄 

As I can't reproduce on current versions I'm going to close this issue now.

**Closed by kjac** 2023-11-27 08:01 UTC
Labels: type/bug
