### ISSUE TITLE
CacheRefresher CacheUpdated gives incorrect data when using it async

### ISSUE THREAD

**Issue by Malthebp** [umbraco/Umbraco-CMS#7485] opened 2020-01-21 11:18 UTC
Hi Umbraco. 

The issue is: 
When we listen to CacheRefresherBase<ContentCacheRefresher>.CacheUpdated and afterwards starts a new thread and ensures the Umbraco Context the cache is not updated. 

So what we do when we listen to this event: 
1.	We fetch the models from the Content Cache – and yes these models are correct at this point
2.	Now we go async and we ensure the Umbraco Context by doing: Current.Factory.GetInstance<IUmbracoContextFactory>().EnsureUmbracoContext()
3.	Now we use this newly ensured UmbracoContext but the cache within this new context is the old cache and when we try to retrieve a property or an URL it is the old data we get.

## Umbraco version

I am seeing this issue on Umbraco version: 8.2.0 and 8.5.1

### Bug summary
CacheRefresherBase<ContentCacheRefresher>.CacheUpdated in an async thread will not give you the updated data.. 

### Steps to reproduce

1. Copy/paste the code below and create a IUserComposer and append the component. 
```
public class CacheRefreshed : IComponent
    {
        public void Initialize()
        {
            CacheRefresherBase<ContentCacheRefresher>.CacheUpdated += CacheUpdated;
        }

        private void CacheUpdated(ContentCacheRefresher sender, CacheRefresherEventArgs e)
        {
            var payloads = e.MessageObject as ContentCacheRefresher.JsonPayload[];
            if (payloads == null)
            {
                return;
            }

            var umb = Current.UmbracoContext;
            var id = payloads.FirstOrDefault().Id;
            var content = umb.Content.GetById(id);
            var contentUrl = content.Url();

            Task.Run(() =>
            {
                var container = Current.Factory.Concrete as ServiceContainer;
                var umbracoContextFactory = container.GetInstance<IUmbracoContextFactory>();
                using (var umbNew = umbracoContextFactory.EnsureUmbracoContext())
                {
                    var newUmbracoContent = umbNew.UmbracoContext.Content.GetById(id);
                    var newUmbracoContentUrl = newUmbracoContent.Url();
                }
            });
        }

        public void Terminate()
        {
        }
    }
```
2. Now put a breakpoint somewhere in the code and attach to your process (or press F5).
3. Now go into Umbraco  and change the name of a node and publish it. 
4. Now you will see that the URL is the old one.

### Expected result
When **CacheUpdated** is being executed I would expect that I would be able to create a new thread and still get the new and updated cache. 

### Actual result
I get the previous data. 

---
_This item has been added to our backlog [AB#4645](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4645)_

**Comment by stevemegson** [comment] 2020-01-21 16:56
I think the problem is in `HybridAccessorBase<T>`, which is used by `EnsureUmbracoContext`:

```c#
protected T Value
{
    get
    {
        var httpContext = _httpContextAccessor.HttpContext;
        if (httpContext == null) return NonContextValue;
        return (T) httpContext.Items[ItemKey];
    }

    set
    {
        var httpContext = _httpContextAccessor.HttpContext;
        if (httpContext == null)
            NonContextValue = value;
        else if (value == null)
            httpContext.Items.Remove(ItemKey);
        else
            httpContext.Items[ItemKey] = value;
    }
}
```

When no `HttpContext` is available, `NonContextValue` uses `CallContext.LogicalSetData` to store values in a way which flows between async calls. But there's no mechanism for values to flow between HttpContext-based storage and `NonContextValue`.

In this case, we have access to `HttpContext` in the `CacheUpdated` method, and we're using the `UmbracoContext` stored there. But the async task has no `HttpContext` available, and reads `NonContextValue` instead. That's still null so far, so a new `UmbracoContext` is created and returned.

There may be a catch I'm missing, but I think the `Value` setter should always set `NonContextValue`, as well as updating `HttpContext` when applicable.

**Comment by Shazwazza** [comment] 2020-01-21 23:45
## Explanation

It's because of Scopes. Cache refreshers execute from within a Scope - as in, the Scope hasn't completed yet. When a Scope completes everything is written to cache but during a Scope it is not, except however for the currently executing context which we force to be 'current' even though the scope hasn't completed. By spawning a new thread, it's just like another request is coming in while the Scope hasn't completed so the previous cache is still the 'current'. The term 'async' here isn't quite right since there's no 'async' operations, it's just a set and forget threadpool thread.

## With and without HttpContext

Cache Refreshers also execute on both HttpContext context and non-HttpContext contexts, depending on what is happening. If you save/publish in the back office, they will execute within context, however these instructions are also written to the database and in the case of an app restarting while saving, then these instructions will be read on a background thread and in those cases Cache Refreshers will execute on a background thread without an HttpContext. In Load Balancing scenarios, all replica/front-end servers will only execute cache refreshers on a background thread because they only process them by reading instructions from the database. 

This means that your event handler here will fail in some cases because you are just expecting this to be in an HttpContext and that an UmbracoContext will be available. The result of this `var umb = Umbraco.Web.Composing.Current.UmbracoContext;` can be null in non-HttpContext contexts. 

## Logical call context

> There may be a catch I'm missing, but I think the Value setter should always set NonContextValue, as well as updating HttpContext when applicable.

Although doing this would 'work' because it would mean that when we initially create the UmbracoContext for the request we'd also assign to the logical call context which would 'flow' to the spawned threadpool thread **but** this is dangerous because now the same context exists in 2x call contexts and either can and will be disposed at different times meaning that one of the threads innevitably will access a disposed object. If this was a real `async` operation and the Task.Run was awaited or in this  non-async usage would have a `Wait()` appended, then in this case we'd know the UmbracoContext will not be disposed while we're using it, but that is not a guarantee for other scenarios. 

## Real life scenario?

The main question about this code is: Why is a new thread being spawned within this event? The example above is just an example but I would like to know the real world scenario for this requirement as to understand what the 'best' way to achieve what you are trying to do is.

## How to make it work

I'd love to know what the real life scenario is since there's numerous ways to probably achieve that. 

That said, if we want to make this particular scenario work of spawning a background thread within a cache refresher event while ensuring that the background thread receives the updated cache even though the Scope hasn't completed, this is how. The trick here is to `Enlist` a custom action to execute at the end of the Scope when the transaction is completed and everything is committed. There's some examples of this in the Core too. 

_Also note that there's no reason to use `Current` or the `Concrete` container_

```cs
public class CacheRefreshed : IComponent
{
    private readonly IUmbracoContextFactory _umbracoContextFactory;
    private readonly IScopeProvider _scopeProvider;

    /// <summary>
    /// Constructor - inject dependencies
    /// </summary>
    /// <param name="umbracoContextFactory"></param>
    /// <param name="scopeProvider"></param>
    public CacheRefreshed(IUmbracoContextFactory umbracoContextFactory, IScopeProvider scopeProvider)
    {
        _umbracoContextFactory = umbracoContextFactory ?? throw new ArgumentNullException(nameof(umbracoContextFactory));
        _scopeProvider = scopeProvider ?? throw new ArgumentNullException(nameof(scopeProvider));
    }

    public void Initialize()
    {
        CacheRefresherBase<ContentCacheRefresher>.CacheUpdated += CacheUpdated;
    }

    private void CacheUpdated(ContentCacheRefresher sender, CacheRefresherEventArgs e)
    {
        var payloads = e.MessageObject as ContentCacheRefresher.JsonPayload[];
        if (payloads == null)
        {
            return;
        }

        // We may be in a background thread so need to be safe and use the IUmbracoContextFactory
        using (var umbNew = _umbracoContextFactory.EnsureUmbracoContext())
        {
            // This loop is purely here to demonstrate obtaining URLs from within the current context
            // where we know the current cache snapshot is up-to-date even though the Scope hasn't completed yet.
            foreach(var payload in payloads)
            {
                var content = umbNew.UmbracoContext.Content.GetById(payload.Id);
                var contentUrl = content.Url();
            }

            // Add a callback to the current Scope which will execute when it's completed
            _scopeProvider.Context.Enlist("MyCacheRefreshedBackgroundThread", scopeCompleted => OnScopeCompleted(scopeCompleted, payloads));
        }
    }

    /// <summary>
    /// Callback that is executed when the Scope completes
    /// </summary>
    /// <param name="scopeCompleted"></param>
    /// <param name="payloads"></param>
    private void OnScopeCompleted(bool scopeCompleted, ContentCacheRefresher.JsonPayload[] payloads)
    {
        // Do not continue if the scope did not complete - the transaction may have been canceled and rolled back
        if (!scopeCompleted) return;

        Task.Run(() =>
        {
            // We are in a background thread, we need to ensure a new context
            using (var umbNew = _umbracoContextFactory.EnsureUmbracoContext())
            {
                foreach (var payload in payloads)
                {
                    var newUmbracoContent = umbNew.UmbracoContext.Content.GetById(payload.Id);
                    var newUmbracoContentUrl = newUmbracoContent.Url();
                }   
            }
        });
    }

    public void Terminate()
    {
    }
}
```

**Comment by Shazwazza** [comment] 2020-01-21 23:47
I will close this issue as this is the expected behavior but I'd love to know what is actually being attempted here since there may be a better way to achieve that than the solution above.

**Closed by Shazwazza** 2020-01-21 23:47 UTC
Labels: state/sprint-candidate

**Comment by Malthebp** [comment] 2020-01-22 06:54
Hi @Shazwazza 

Thank you very much for you very explanatory answer and a possible solution - I will try that. 

### Real life scenario
So what we use it for and why it is important that it is a new thread, is because we do a ton of calculations based on the published content. 
In short what we do: 
1. We create a new view model based on the published content
    * Includes traversing the tree to make a navigation, breadcrumb, list, etc.
    * Getting content/media by id 
    * etc
2. Saves that new model into a new storage

These view models can take multiple seconds to finish creating and we do not want our editor to have a bad editor-experience, so we do it async - and yes we fire and forget, but it is still an _async_ operation that we do. Also referering to Microsofts documentation it states: 
![image](https://user-images.githubusercontent.com/18698439/72870876-a0244700-3ce9-11ea-8a55-364939041201.png)
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=netframework-4.8
And for the reason above, we cannot await it. :-) 

### Still a bug
Even though that your solution might make it possible for us to do something in a new thread and get the updated cache, I still think this is a bug. Because the event you are actually firing is in past tense (updated) and I would expect that I could do whatever I would like to do now, but that is not situation, because the cache is actually not done updating. Couldn't it be a solution to wait firing the event till the scope is completed aswell? Then you are 100% sure that you are done doing all your calculations and you can let the external developer do whatever they want to do, whether that is to throw an exception, make a new thread, create a new Scope or whatever?

**Comment by clausjensen** [comment] 2020-01-22 07:58
@Malthebp The problem by doing this is that if we decide to move the firing of the event outside the scope completion, then this event would not allow you to rollback the entire transaction/scope in case it needed to be.

You could have a case where something that is happening in this cache updated event would require this whole action to be rolled back - which would simply be impossible if the scope was at that point already completed/committed.

I do however agree that it is not very obvious to anyone except from those who wrote this and that this should be documented better so you won't end up in a situation like yours. The suggested solution from @Shazwazza should make it possible to do what you need to do, while at the same time not "breaking" what having the event fire inside the scope allows us to do.

**Comment by Malthebp** [comment] 2020-01-22 08:36
@clausjensen 

It does make sense that it should fire within the context of where we are, but the cache is not done updating - and as far as I understand from both you and @Shazwazza we agree on that. But what you could do is the same as the fix Shannon suggested me and then wait for you to complete your scope and then fire the event. Then the tense is correct and the external developer can do whatever - and things works as expected.

And yes, the solution from Shannon does work, but I really think that you should consider doing something about the CacheUpdated event. :-)

**Comment by Shazwazza** [comment] 2020-01-23 04:55
@Malthebp Like much of Umbraco many of it's parts come with a story of both legacy and backwards compatibility :) 

## History

CacheRefreshers themselves evolved in enormous ways in v7 to make them work correctly and make load balancing seamless and was all done without breaking changes but the end result maybe isn't so pretty. In v8 they were slightly modified but not revisited to be re-engineered. 

Then there's a story about how caches work. In v7 the XML cache is not actually 'safe' between requests. While one request updates the cache another request that may have already started reading the cache may suddenly get results from an updated cache. There is no sense of 'snapshots' in v7. In v7 these cache refreshers and their events would actually mean cache 'Updated'. 

V8 works differently (better) and we work in snapshots. Updating the cache is 'safe' while other requests or threads read from it's current snapshot. At some stage v8 was updated to force the current Scope's snapshot to be updated ... for the very reaon IIRC in case people were using this event and needed access to the 'Updated' cache. I don't recall when/how/why it was done the way it is but it was.

## Behavior change?

I think it would be possible to change this cache refresher to Enlist it's own callback and then raise the event. That would solve the problem you are havinig but this comes with some risk that we don't break anything relying on the current behavior. For example, if you are using the approach described above and then we changed this I don't know what will happen, maybe it would work but i'm not sure since i don't know what happens when you enlist a callback during a Scope's enlisted callback execution. 

## Real life scenario

Thanks for providing details on what you are doing. We do a similar thing for Models Builder and PureLive when changing doc types and data types. When that happens we basically set a flag on a service (and some other stuff) but don't regenerate models then. They are re-generated lazily when another request comes in that requires them.

I guess there's various approaches you could take to inform your service to generate new models/data like you are doing. Doing this approach is certainly one but without knowing the ins/outs of your setup I can't really say if there would be a better one so will leave that up to you. My only concern with fire and forget and executing that on every publish is that can add up to a lot of concurrent background threads doing potentially the same thing so you'll prob want to handle that in some way. Another approach would be to have a single dedicated background thread for running these operations.

What I meant by not `async` is that if something is not awaited then the term `async` isn't quite right since async generally means passing the current execution to another IO bound or CPU bound thread and then re-acquiring that execution once it's done which is why Task is awaitable. During this async behavior there's synchronization contexts at play which is what I was first thinking was a potential problem when seeing the term `async` but that's not the case with fire/forget, so all good.

**Comment by Malthebp** [comment] 2020-01-24 16:55
@Shazwazza  

Thank you very much for all your time. I do get that the backwards compatibility is very important and that we do have an edge case that (maybe) not so many are experiencing at the moment.  

There are different ways of achieving what we are trying to do but because of the scale of most of our customers, we need something that can scale and that keeps scaling. So we do _transform_ the IPublishedContent model on publishing time, because then we have everything ready for display when an end-user requests it - no need for query caching. 

Lets talk more about that at Code Garden 2020 ;-)
