### ISSUE TITLE
EntityRepository is fetching all property data for media

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3457] opened 2018-10-27 10:37 UTC
`EntityRepository` is fetching all property data for media items since this commit (https://github.com/umbraco/Umbraco-CMS/commit/34cebe989f093065fa03c45754a647ae1f7782ac#diff-2528351576cfa71144920691d767da0bR126).

Not really sure why... `EntityRepository` should really only be fetching really slim versions of entities, but I guess there was a reason why this was done this way back then.

The problem is that since the `EntityService` / `EntityRepository` is also being used by other things such as the tree, this can easily create performance issues. The tree cannot use paging for its queries (since a tree needs to list everything at once) so these queries will be fetching all entities, with all property data even though the property data isn't really needed for trees.

When a site has a large amount of property data to query in (this can be any data - such as many content versions = a lot of property data) - this will basically kill the database having to query in this table with the joins created by this code.

The best solution would be to clean up the `EntityRepository` to not do this and move the responsibility for getting media entities with property data somewhere else. This would however mean a breaking change, so instead we could create new internal methods that work around this issue - meaning we won't break any existing API functionality, but we still make sure the media tree doesn't kill the database in these circumstances.

**Comment by Shazwazza** [comment] 2018-11-01 00:31
PR: https://github.com/umbraco/Umbraco-CMS/pull/3460

**Comment by Shazwazza** [comment] 2018-11-01 04:00
I've updated the PR and it's all merged in now. Unfortunately i forgot to do a squash merge, so it's just merged. If we need to put this into a path release then we can cherry pick the 3 or so commits.

**Closed** 2018-11-01 04:01 UTC
Labels: state/in-progress, type/bug

**Comment by andrew-at-rm** [comment] 2020-05-25 15:27
I believe this performance issue has re-introduced itself. 
See https://github.com/umbraco/Umbraco-CMS/commit/23b8e1cce8107aabd8ba5ebbcb0a3ee33aff212d#diff-897fc6d5e36286e24d7c97cf10871f00

I'm getting SQL timeouts when trying to navigate through the media section on version 7.15 and up.

**Comment by Shazwazza** [comment] 2020-05-25 23:54
@andrew-at-rm the commit you referenced is just what it says it is:

> Removes the remaining part of the EntityRepository that was loading in ALL properties for media which we don't want whatsoever which means some other code is cleaned up/removed

It does not re-introduce the problem, that commit actually fixes up more of the problem and ensures that no matter what, no calls to the EntityRepository will load in all property data. I've verified this in the SQL profiler, this is the SQL that executes for rendering the media tree and each branch (as an example):

```sql
exec sp_executesql N'SELECT umbracoNode.id, umbracoNode.trashed, umbracoNode.parentID, umbracoNode.nodeUser, umbracoNode.level, umbracoNode.path, umbracoNode.sortOrder, umbracoNode.uniqueID, umbracoNode.text, umbracoNode.nodeObjectType, umbracoNode.createDate, COUNT(parent.parentID) as children, contenttype.alias, contenttype.icon, contenttype.thumbnail, contenttype.isContainer, media.mediaPath
FROM umbracoNode umbracoNode
INNER JOIN cmsContent content
ON content.nodeId = umbracoNode.id
LEFT JOIN cmsMedia media
ON media.nodeId = umbracoNode.id
LEFT JOIN cmsContentType contenttype
ON contenttype.nodeId = content.contentType
LEFT JOIN umbracoNode parent
ON parent.parentID = umbracoNode.id
WHERE (umbracoNode.nodeObjectType = @0)
AND (([umbracoNode].[parentID] = @1))
GROUP BY umbracoNode.id, umbracoNode.trashed, umbracoNode.parentID, umbracoNode.nodeUser, umbracoNode.level, umbracoNode.path, umbracoNode.sortOrder, umbracoNode.uniqueID, umbracoNode.text, umbracoNode.nodeObjectType, umbracoNode.createDate, media.mediaPath, contenttype.alias, contenttype.icon, contenttype.thumbnail, contenttype.isContainer
ORDER BY umbracoNode.sortOrder',N'@0 nvarchar(40),@1 int',@0=N'b796f64c-1f99-4ffb-b886-4bf4bc011a9c',@1=1118
```

If there's SQL timeouts then I would think it must be something else since this single query should be the cause for that. If you run sql server profiler you should be able to determine what the issue is.

**Comment by andrew-at-rm** [comment] 2020-05-26 11:58
@Shazwazza Thanks for pointing me in the right direction. I ran sql server profiler on version 7.15.5 and found that it is timing out on the query you mentioned. On the same database I ran it on version 7.14 (which doesn't time out for me) and the query is slightly different. 

`
exec sp_executesql N'SELECT umbracoNode.id, umbracoNode.trashed, umbracoNode.parentID, umbracoNode.nodeUser, umbracoNode.level, umbracoNode.path, umbracoNode.sortOrder, umbracoNode.uniqueID, umbracoNode.text, umbracoNode.nodeObjectType, umbracoNode.createDate, COUNT(parent.parentID) as children, contenttype.alias, contenttype.icon, contenttype.thumbnail, contenttype.isContainer
FROM umbracoNode umbracoNode 
INNER JOIN cmsContent content
ON content.nodeId = umbracoNode.id
LEFT JOIN cmsContentType contenttype
ON contenttype.nodeId = content.contentType
LEFT JOIN umbracoNode parent
ON parent.parentID = umbracoNode.id
WHERE (umbracoNode.nodeObjectType = @0)
AND (([umbracoNode].[parentID] = @1))
GROUP BY umbracoNode.id, umbracoNode.trashed, umbracoNode.parentID, umbracoNode.nodeUser, umbracoNode.level, umbracoNode.path, umbracoNode.sortOrder, umbracoNode.uniqueID, umbracoNode.text, umbracoNode.nodeObjectType, umbracoNode.createDate, contenttype.alias, contenttype.icon, contenttype.thumbnail, contenttype.isContainer
ORDER BY umbracoNode.sortOrder',N'@0 nvarchar(40),@1 int',@0=N'b796f64c-1f99-4ffb-b886-4bf4bc011a9c',@1=-1
`

There is no join to the cmsMedia table and there is no grouping on media path.  Not sure why it's timing out; if its just my media table is too large(400k records) or some index I am missing. Anyways thought I'd point that out in case anybody else is running into SQL time outs when viewing the media tree.

**Comment by Shazwazza** [comment] 2020-06-03 00:20
Hi @andrew-at-rm, would you be able to run this query against your db in the Sql management studio with "Include actual execution plan" enabled and see what it says? It should probably tell you that an index is missing and I'd like to know what it says. Locally it against my db it doesn't tell me any indexes are missing but that's probably because I don't have near as much data as you. Either that or potentially one of your upgrades to the version you are on hasn't applied all indexes to your DB.

**Comment by Shazwazza** [comment] 2020-09-24 04:01
@andrew-at-rm Hi sorry it's been a while but i was just trying to see what was in your shared doc there but It says access denied, are you able to re-share it?

**Comment by andrew-at-rm** [comment] 2020-09-24 12:58
@Shazwazza I believe it should be available now. Thanks.

**Comment by Shazwazza** [comment] 2020-09-24 15:14
Thanks @andrew-at-rm that doesn't look like anything out of the ordinary and there's no crazy table or index scans taking place. Does this query still timeout on you? And if so, when? Does this query execute for loading a branch of the tree? or when you are in list view? and how many rows does this return?

**Comment by andrew-at-rm** [comment] 2020-09-24 16:07
@Shazwazza It's been awhile since I've run but I think it was the root tree it times out on.  I did run the query without the group by path field and it ran under a second. So I believe it has to do with a grouping on a text field that slows it down. I don't remember how many records it returns. But I believe it took a few days to complete. I can re-run it if you like.

**Comment by Shazwazza** [comment] 2020-09-24 23:27
> But I believe it took a few days to complete.

days?? that doesn't seem possible 🤔 

The Group By all fields is required because there's a COUNT operation taking place so whenever there's an aggregate function all other fields must be in the GROUP BY clause. I haven't heard other reports of this query being slow and SQL management studio isn't reporting any issues with the query or index so it does seem strange that this is an issue. If this issue is still affecting you and you don't mind sharing your DB you can send it to my email and I can run some tests against it. Just let me know.

**Comment by andrew-at-rm** [comment] 2020-11-19 14:16
@Shazwazza It is still affecting me. I can not share my database as there is some sensitive data in it. I can see if I can strip some of the sensitive stuff and if you think its still necessary to diagnose this problem.  I did find that if I move `LEFT JOIN cmsMedia media ON media.nodeId = umbracoNode.id` to the bottom of the join statements it does run quickly without timing out.

`SELECT umbracoNode.id,
       umbracoNode.trashed,
       umbracoNode.parentID,
       umbracoNode.nodeUser,
       umbracoNode.level,
       umbracoNode.path,
       umbracoNode.sortOrder,
       umbracoNode.uniqueID,
       umbracoNode.text,
       umbracoNode.nodeObjectType,
       umbracoNode.createDate,
       COUNT(parent.parentID) AS children,
       contenttype.alias,
       contenttype.icon,
       contenttype.thumbnail,
       contenttype.isContainer,
       media.mediaPath
FROM umbracoNode umbracoNode
INNER JOIN cmsContent content ON content.nodeId = umbracoNode.id
/*LEFT JOIN cmsMedia media ON media.nodeId = umbracoNode.id*/
LEFT JOIN cmsContentType contenttype ON contenttype.nodeId = content.contentType
LEFT JOIN umbracoNode parent ON parent.parentID = umbracoNode.id
LEFT JOIN cmsMedia media ON media.nodeId = umbracoNode.id /* Moved here */
WHERE (umbracoNode.nodeObjectType = N'b796f64c-1f99-4ffb-b886-4bf4bc011a9c')
  AND (([umbracoNode].[parentID] =-1))
GROUP BY umbracoNode.id,
         umbracoNode.trashed,
         umbracoNode.parentID,
         umbracoNode.nodeUser,
         umbracoNode.level,
         umbracoNode.path,
         umbracoNode.sortOrder,
         umbracoNode.uniqueID,
         umbracoNode.text,
         umbracoNode.nodeObjectType,
         umbracoNode.createDate,
         media.mediaPath,
         contenttype.alias,
         contenttype.icon,
         contenttype.thumbnail,
         contenttype.isContainer
ORDER BY umbracoNode.sortOrder`

I believe just changing the ordering of the left join statements might fix the problem.
