### ISSUE TITLE
RTE styles stripped in BlockGrid Views

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#14403] opened 2023-06-17 19:48 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.2

### Bug summary

When trying to align text or adding any inline styles to RTE content they are stripped out when viewed in a BlockGrid view

### Specifics

The RTE Slide out shows the correct style, the front end web page shows the correct style yet the view used in the back office BlockGrid strips out the inline styles completely.  

Back office slide out editor
![image](https://github.com/umbraco/Umbraco-CMS/assets/1143883/f14cfc92-6fc5-47b3-b37c-72608ba94cd3)

Back office BlockGrid view
![image](https://github.com/umbraco/Umbraco-CMS/assets/1143883/532d8fe6-b473-4d90-9359-23a5831b2f51)

Web page
![image](https://github.com/umbraco/Umbraco-CMS/assets/1143883/97622a8d-6e20-4a51-9977-e9ac79dc6eb5)

As you can see the formatting is not there for the BlockGrid view.  This is also the case on the Umbraco BlockGrid Demo site.

### Steps to reproduce

1. Create an RTE BlockGrid iaw the docs.  Also create a back office view for the BlockGrid.  
2. Use the RTE block in a page's BlockGrid and edit it's content. 
3. Using the RTE toolbar, or manually, set some text to align center and submit the change. Note the text in the BlockGrid view is still left aligned.  
4. Save and publish the page and/or save and preview, either way, view the web page and notice the text added is centre aligned.

### Expected result / actual result

Expected the Block Grid RTE to faithfully reflect the edited content

What happened was the RTE content was stripped of all inline styles in the BlockGrid view.

**Comment by andr317c** [comment] 2023-06-19 10:22
Hey! 

Thanks for posting the issue 😄. I was able to reproduce this issue on v10.5.1, 11.4.0 and 12.0.0-rc3. I will mark it as an up for grabs.

A gif of the issue: 
![RTEStyles](https://github.com/umbraco/Umbraco-CMS/assets/73799582/8c5454e1-3511-42bb-b4d4-14ef494c4b57)

**Comment by kasparboelkjeldsen** [comment] 2023-10-05 06:59
Working on this - seems to be the default sanitization of angular removing the style tags created in the rich text.

**Comment by nielslyngsoe** [comment] 2024-11-27 20:11
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/14923
So closing the issue. Thanks for reporting this.

**Closed by nielslyngsoe** 2024-11-27 20:11 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11, affected/v12, community/hackathon
