### ISSUE TITLE
UmbracoMultiUrlPicker: dialog closes abruptly 

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#5132] opened 2019-04-02 21:30 UTC
A pre-existing bug with RJP.UmbracoMultiUrlPicker (version 2.2.1, umbraco 7.13.2) :

Action: Open RJP dialog window, then right-click and drag the mouse (from right to left) to select text within field.

Result: entire dialog window closes. 

Expected result: dialog stays open and the text within a field highlights for selection.

NB Multi Url Picker is available as a built-in property editor in Umbraco 7.14+ and 8.0+, this ticket is to fix this issue in these cores.

**Comment by Shazwazza** [comment] 2019-04-02 23:36
Thanks for reporting, for now I've marked up for grabs to see if anyone from the community can assist

**Comment by Myster** [comment] 2019-04-03 02:53
I have noticed this too, it is not limited to RJP picker.
It appears the determining factor is where the mouse-up occurs.
If it is within the pane then it is ok, if it's outside the pane it closes.

My suggestion is mousedown (or mouse click) outside the pane should close it, not mouse up.

**Comment by kjac** [comment] 2019-04-04 17:22
Isn't this a duplicate of #4934?

**Comment by shearer3000** [comment] 2019-04-04 20:18
hi - yes it reads very much that way.

**Comment by Shazwazza** [comment] 2019-04-04 22:14
So shall i close this one then? (just want to be sure!)

**Comment by shearer3000** [comment] 2019-04-05 00:57
yes please (sorry for dup)
I'll add this as a test case on the existing ticket.

**Closed** 2019-04-08 02:06 UTC
Labels: community/up-for-grabs, help wanted, type/bug

**Comment by mjbarlow** [comment] 2019-08-11 18:42
Can this be reopened, as far as I can see they are separate issues.
