### ISSUE TITLE
tagsController val-property-validator="validateMandatory" doesn't fire on create new content..

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#4644] opened 2019-02-19 01:20 UTC
I have a mandatory tag datatype on a doctype,  umb 7.13.2

when creating content, if the tags are just left blank and we click publish there is no indication that we don't have a single tag. (and the page is created left in an unpublished state)

If you add a single tag, and then remove it (without publishing) then on change to no tags the error is shown.

Adding console.log into the directives.js file 
```
var validate = function (viewValue) {
                    console.log("valPropertyValidator");...}
```

you can see that the validate function is only called on change to the property editor, and not when we don't interact and leave blank and hit publish.

The same seems to happen with textarea, but that can be worked around by adding in an ng-required="model.validation.mandatory" - presumably angular default then handles this for us.

`<textarea ng-model="model.value" id="{{model.alias}}" name="textarea" rows="{{model.config.rows || 10}}" class="umb-editor umb-textarea textstring" val-server="value" ng-keyup="model.change()" ng-required="model.validation.mandatory"></textarea>`

Any ideas on a solution to the tags issue greatly recieved.

**Comment by mistyn8** [comment] 2019-02-19 10:04
An easy way to repeat this.. 

Set up a vanilla umbraco 7.13.2 with started kit.
Access the admin and create a new blog post under blogs, enter no content and hit publish.
![image](https://user-images.githubusercontent.com/12418214/53006219-b61bee80-342c-11e9-997a-8b8c3b09d19e.png)

If you now fill in the pageTitle and the node name and again hit publish.. you now see errors for description and tags (both set as mandatory), but the page has been saved in an unpublished state
![image](https://user-images.githubusercontent.com/12418214/53006458-26c30b00-342d-11e9-8ea0-c7adf7ba35f3.png)

![image](https://user-images.githubusercontent.com/12418214/53006428-1874ef00-342d-11e9-8a7f-5e18b26406b1.png)

TextBox is the only controller using the ng-required simple validation and that seems to work on create, text area uses val-server and tags val-property-validator, both of these only seem to work if the content is existing.

I would also have expected the serverside validation to stop creation of the content in the error state of no tags or no textarea content, also where I have this and the content should be listed in the tree view, when the node is created in the unpublished state the tree view doesn't refresh (and the admin remains at the create content url), so you can end up creating mutliple nodes.

**Comment by nul800sebastiaan** [comment] 2019-02-19 10:56
Hi @mistyn8 - looks like a bug indeed!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Shazwazza** [comment] 2019-02-20 04:19
Server side validation absolute does not stop the content from being created - this is expected behavior. Any server side validation that fails will save the content - you wouldn't want your editors to lose a bunch of updates that they've spent hours doing and cannot save even with validation errors ;) that is why we prevent it from publishing if publishing is requested.

So the bug here is just that the tags editor hasn't nicely implemented a client side required check, this same problem will exist for many property editors. The important part here is that validation *is* working as expected since server side validation is the most important one.

**Comment by mistyn8** [comment] 2019-02-20 08:39
Have things changed since https://issues.umbraco.org/issue/U4-6194 then as thought in umbraco 7 mandatory meant mandatory on either save or publish?
"you wouldn't want your editors to lose a bunch of updates that they've spent hours doing" wasn't that what others were wanting in umb7 that isn't now possible.. complete half an update and save.. leaving mandatory fields to be completed later?

And this is only on create.. if I create the page and then edit it.. and remove all tags at this point the nice client side validation on tags (and textarea and colour picker) all then prevent any save if the mandatory requirements aren't satisfied, but only textbox prevents save on page creation.
So I don't think it is a case of no client side validation as it does it does via the val-property-validation, just that it doesn't fire if no interaction made for the create dialogue. 

If I cast my mind back to umb4/6 where the save rather than publish if mandatory failed you got a nice, we've saved it but not published notification was present, that's missing here, and also the tree doesn't refresh to show the saved but unpublished?

Also don't you have the situation where editors will lose content, if they can't fill in the details of a mandatory textbox, as the client side validation there works in the create dialogue preventing any saving?

**Comment by Shazwazza** [comment] 2019-02-20 09:00
ah fair call on my quote :P

Save action does not require validation passes on the server - but client side validation needs to pass to send it to the server - else there's no point in having client side validation at all.

So what to do then? People like client side validation - but with this argument they don't. Unfortunately you can't really have both worlds.

**Comment by nul800sebastiaan** [comment] 2019-02-20 09:33
So 2 things here:

First: client side validation should be fixed here.

Second: I've long been an advocate of not using so much validation. IMHO it is hostile to the editor if you don't absolutely have to have the content you require them to fill in. 

Yes, you're going to get them to enter the information you demand of them, but what are they going to put in those tags? Probably "content" or "general" because they just want to move on and they don't care that much.

I know, I know, this is not always the case, but if you demand more info you're going to get more junk info. Instead, think about adding a sensible default, even if that means tags (or other required properties) are empty for some documents.

Anyway, that's my rant for the day! ;-)

**Comment by mistyn8** [comment] 2019-02-20 09:41
I think most will have got used to the mandatory means mandatory by now.. (even though I'm with @nul800sebastiaan on it would be nice to have a draft, akin to the old can save a node without validation, as the work around of a default just means you end up with the default persisted across all your content)

 For me I think consistency between create dialogue and save/publish dialogue is what's required.

So textbox seems to be the only propeditor I've found who's client side validation implementation works correctly in the create node dialogue, as mentioned it's using the ng-required simple angular validation.
Other validators seem to use the val-server or val-property-validator directives, and these don't seem to attach the watcher unless you interact with them. Unfortunately that's as far as my angular skills extend :-(

@Shazwazza Not to speak to others but perhaps the client side validation should be contextual on the action.. publish it's validation, save it's an indication of things to fix prior to publish (but allows a draft to be saved).. a gross over simplification and you've already answered why this isn't possible in the current pipe line.

**Comment by Shazwazza** [comment] 2019-02-20 10:47
`val-server`, etc... *Is* server side validation, that is how the server side wires up messages from the server to the client. So what you are asking can be done (and already does this) but to do what you wish means removing all client side validation. *We* could do that and not have required client side validation in *our* property editors, but we can't stop custom property editors from doing that.

**Comment by mistyn8** [comment] 2019-02-20 13:45
Sorry I didn't want to steer this issue back onto the mandatory means mandatory debate.

So back to the issue of validation best practice implementation on prop editors.... and currently only talking about prop editors that ship with the core

I did also stumble on...
https://our.umbraco.com/forum/umbraco-7/developing-umbraco-7-packages/46988-Custom-property-editors-how-to-stop-a-page-from-being-saved#comment-168535
Did the documentation you mentioned ever get created, it might help me to try and contribute to fixing the issue?

If not.. just want to see if I have it right

https://github.com/umbraco/Umbraco-CMS/blob/patch-7.13.2/src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
TextArea.. so val-server="value" that's server validation hook up

So textArea out of the box has no client side validation, so adding the ng-required="model.valiation.mandatory" adds this in as a simple not empty.
textArea errors out of the box should only ever show after a round trip to the server?.. and they stop content saving.

(also noticed the dev-v8 branch text area now includes a show-validation-on-submit angular directive.. so possibly already being fixed?)

Tags.. that has val-property-validation.. which seems to point at a angular method, so I presume that is client side, and we need to use that as more complex validation of >0 rather than empty. But has no serverside validation.

However, val-property-validation is only activated on interaction with the control, not in a create and don't touch scenario (on instantiation).
However, ng-required doesn't require that interaction...

rambling now so going to stop.. thanks for the help guys.

**Comment by Shazwazza** [comment] 2019-02-20 14:05
* `show-validation-on-submit` is just a UI toggle thing
* val-server and in some cases val-server-field is the server validation messages once the POST has been done either creating or saving
* if you add ng-required="model.validation.mandatory", then you are adding the client side validation for if the property is flagged as mandatory at the property type level. This can work easily for some property editors like ones that are just text fields but will not work for complicated property editors like tags, etc...  (Adding this will prevent you from being able to create/save the content until this client side validation passes)
* For tags since validating the 'required' data, it needs to do custom things, so yup the callback assigned to `val-property-validation` is that. This is a custom validation directive so potentially it's not firing on load or something. Also note, this issue may already be resolved in v8 and the tags editor is overhauled.
* All properties have server side validation, it's just that some property editors html might not be using val-server. `val-server` is used to wire up a specific message into the property editor UI. Some property editors may define several fields, and val-server allows you to wire up individual server side validation messages with each of these fields. That said, if these directives are not present in the html, you will always get the big red property level error with the server message in there. 

hope that makes sense!

**Comment by mistyn8** [comment] 2019-02-20 14:23
makes perfect sense...
so textarea can be fixed with ng-required="model.validation.mandatory"

and  just need a bright spark to work out how to fix the val-property-validation not firing in the create dialogue. :-)

ps just tried on Umbraco version 8.0.0-alpha.58.1553 assembly: 8.0.0.0

and same functionality.. create dialogue with mandatory textbox and textArea
text box - client side validation with no possible save/publish until filled in
textarea - doesn't validate clientside.. so allows a save, though doesn't prompt you on publish that it was only saved

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:42
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:42 UTC
Labels: community/up-for-grabs, help wanted, type/bug
