### ISSUE TITLE
 GetMediaByPath - Umbraco strips "403x328" from file

### ISSUE THREAD

**Issue by andemt** [umbraco/Umbraco-CMS#11707] opened 2021-11-29 13:07 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.0

### Bug summary

Hi,
Our customer uploaded a file named "image_1200x920.jpg". We have a media-middleware to check special access to images.  We use mediaService.GetMediaByPath(path), and it returns null.

I found the source code, and Umbraco strips away important part of customer image path:
[MediaRepository.cs](https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaRepository.cs)

Why? 

### Specifics

Is this code correct? When is this used in Umbraco? Never heard of that function...

```
const string pattern = ".*[_][0-9]+[x][0-9]+[.].*";
var isResized = Regex.IsMatch(mediaPath, pattern);

// If the image has been resized we strip the "_403x328" of the original "/media/1024/koala_403x328.jpg" URL.
if (isResized)
{
       var underscoreIndex = mediaPath.LastIndexOf('_');
       var dotIndex = mediaPath.LastIndexOf('.');
       umbracoFileValue = string.Concat(mediaPath.Substring(0, underscoreIndex), mediaPath.Substring(dotIndex));
}
```

### Steps to reproduce

Upload an image with name "example_800x600.jpg" and use mediaService.GetMediaByPath()

**Comment by bielu** [comment] 2021-11-29 15:56
@andemt that is correct code, umbraco is using imagesharp to crop images, so storing information about path with size doesnt really matter from umbraco perspective as Umbraco will not serve full size in most of cases as it will use .getCropUrl :)

**Comment by andemt** [comment] 2021-11-29 16:25
Hi @bielu 
I don't really understand your answer. "Its correct code" and "doesnt really matter" :) 
But, that means if an editor upload an image with that name, it will not work if we use GetMediaByPath() ? 

Imagesharp uses query? When are imagesharp use size in filename in Umbraco?

**Comment by bielu** [comment] 2021-11-29 16:39
@andemt Umbraco by removing sizes avoiding files with duplicate names, but different sizes - it is why code is correct. Cropping should be done in umbraco, so you have one source not 20 :)

By it doesn't matter if it is doing that or not, I mean even if umbraco is removing them, that doesnt matter for most of situation. 
I would argue method is doing that correctly. Not sure if Umbraco is doing that also on upload, but if it doesnt I would argue it is bug on upload, not on read :)

**Comment by emma-hq** [comment] 2021-11-30 14:19
Hi folks!

Thanks for reporting the issue @andemt  - and thanks to @bielu for taking a look too. The way that imagesharp works, by the time the middleware intercepts the request, you won't have what you need to use GetMediaByPath(). You'll need to intercept the request at an earlier stage and while I'm not able to help you with that here, I'd like to point you to [our forum](https://our.umbraco.com/forum/) where there are lots of Umbraco devs who can help you to solve the issue. 

As the code in MediaRepository.cs is working as intended, I'm going to close the issue but head over to the forum if you would like a bit of support getting to where you need to be.

Emma

**Closed by emma-hq** 2021-11-30 14:19 UTC
Labels: type/bug
