### ISSUE TITLE
Umbraco.DropDown.Flexible not saving within Nested Content

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#3700] opened 2018-11-16 15:07 UTC
Hi,

We have recently upgraded to Umbraco 7.12.4 what we have noticed is that dropdowns are now of type Umbraco.DropDown.Flexible - any dropdowns used within Nested Content, do not persist a value. I have looked at the IPublishedContent.Property.DataValue and the JSON contains the property with a blank value. The value has been populated in the Umbraco back office. Dropdowns that are of the original type work as do NuPicker dropdowns.

Kind regards,

Ric

**Comment by kjac** [comment] 2018-11-17 08:32
I can't reproduce this... this is what I see:

![dropdown flexible nested content](https://user-images.githubusercontent.com/7405322/48659019-846d4300-ea4b-11e8-8283-557bc4843c51.gif)

**Comment by Ric-Carey** [comment] 2018-11-17 12:18
Apologies, I worded that wrongly. The value saves, however when you access it via the IEnumberable and then GetPropertyValue on the Ipublished content, there is no value.

**Comment by kjac** [comment] 2018-11-18 11:17
@Ric-Carey hmm... I still can't reproduce it.

My doctype has a Nested Content property called `nestedContent`. The property contains one item, where the dropdown is of type `Umbraco.DropDown.Flexible`:

![image](https://user-images.githubusercontent.com/7405322/48671623-9cb48f00-eb2b-11e8-87b4-9ce0702de3e6.png)

Given this template:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}
<html>
    <body>
        <h1>Nested Content</h1>
        @foreach(var item in Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("nestedContent")) {
            <div>
                <h2>@item.DocumentTypeAlias</h2>
                <ul>
                @foreach(var property in item.Properties) {
                    <li><strong>@property.PropertyTypeAlias:</strong> @item.GetPropertyValue(property.PropertyTypeAlias)</li>
                }
                </ul>
            </div>
        }
    </body>
</html>
```

...this is the output produced:

![image](https://user-images.githubusercontent.com/7405322/48671638-c79ee300-eb2b-11e8-94e5-a63af85744bc.png)

**Comment by nul800sebastiaan** [comment] 2018-11-18 19:58
Thanks for trying @kjac I'll close this for now pending new info to reproduce.

**Closed by nul800sebastiaan** 2018-11-18 19:58 UTC
