### ISSUE TITLE
417 missing token problem - after Umbraco upgrade from v7.5.7 to v7.13.0

### ISSUE THREAD

**Issue by NurhakKaya** [umbraco/Umbraco-CMS#4138] opened 2019-01-18 11:45 UTC
This doesn't look like a new bug as it [has been reported before](https://our.umbraco.com/forum/using-umbraco-and-getting-started/85747-417-missing-token-suddenly-occurring-on-all-our-sites#comment-301285) for multiple Umbraco versions but as the problem still happens with one of the latest Umbraco version (v7.13.0), I am creating a new bug for this again;

As you can see my notes for Issue #2157 this problem happens after upgrading Umbraco version from v7.5.7 to v7.13.0. Things work fine locally on my Dev machine  but after deploying v7.13.0 code to an Azure App Service, then I can't see Umbraco sections & node details due to 417 missing token problem, please see details below;

**Request headers**

GET /umbraco/backoffice/UmbracoApi/Section/GetSections HTTP/1.1
Host: cms-uat.MYPROJECTNAME
Connection: keep-alive
Accept: application/json, text/plain, /
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
X-XSRF-TOKEN: r3LbNLgTHrDXREbMSDPkEvfrTAJttdnkfDLg-G6i7GTVRn81FH0250Ef8bbFLuj63_zA86fl00x_ofvoj0Q2LSuXkehjrmaFeLozBnrN24j2fY1AsysQR8fQMtcbSkS80
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,tr;q=0.7
Cookie: ai_user=gEdMC|2018-09-20T12:49:32.027Z; MYPROJECTNAMECookieNotification=1; _ga=GA1.3.1439173144.1547483328; _gid=GA1.3.1024177007.1547572201; XSRF-TOKEN=r3LbNLgTHrDXREbMSDPkEvfrTAJttdnkfDLg-G6i7GTVRn81FH0250Ef8bbFLuj63_zA86fl00x_ofvoj0Q2LSuXkehjrmaFeLozBnrN24j2fY1AsysQR8fQMtcbSkS80; XSRF-V=4V0mV3Vi4HxD4pOmPKazbyXdi0hwxMez930AUYyWUeqXfp3sSRGgZaS1uz90FVxohtmLmzcDaZuRmpxZkxEU0b4Gwf0NcOCrPrDTeyk-M-Q1; ARRAffinity=58959f315ae110c77c27b360c2c2aa988f5fa92288eacf5bf282dfe6e588a5e9; umb_installId=48139884-58bf-46b9-a51e-cacba83937e9; UMB_UCONTEXT_C=2019-01-18T11%3A05%3A57.4886248%2B00%3A00; UMB_UCONTEXT=FDE184EE0BCC9A666F7F1F89E21A02C6D3802D2FB31FDD6EB089B2ADB0B1A9AA54A1ECBE5C0A6017068A0F8EC7753E12314DAC446E7A0AECE5705A178C7113E5EADDC1FC63C020C851379C072738F03263ECF79736E4D956CEC33EA2E67D0C50127DE7B9034F5AE95AE0267D0FAD0442FB166C316283925CE9067EB1244936CAFF8AA6F2E8C44BAE067AAAE4DC6E11683AB03A7357585BC2BE427DD18E29B32D34ECCB2AA8917A2F561316CAD0EBEC76F298E1E7026B09F69380A2347FE86F0A5E5EDEE57F772E9971681501D451D1125190ED2DCBADC195A9D138B148B6F2FEE65E731C88CFEF6BBE97217763F44217DEA7AD5FFBDD155188D3A0A2D97DD734683D44E6BEE48E02B543118E63B04BE64BF9A9FDD6149B0B22A1B8EF0C58E30E84597B980BE86D6F1468DE82274F0CC5DE6620A3070A20CF927B0D9D44E4150D86B1443EBDA37ECEB0795762959FACEDC130CD243F3EB9C4C3A4AA3FC75695642C3ED5A9AC9D13044F724DD521F3718FBB3979FE74FB195AD0B2EC2A83A27C17D0245379FC086A98E1D4BDBB701F3F39204DB87E95C63CB8E071CE77E1F422DBB19FB7DEBDC740C2C44568D339C7BC880E7C54AEDD99C2D0E526CF1B3C7434CE2DA02DAD10508FAE9B5E76B1E286F1D4D3CBD7A5474AC0869016906896174220CB5E6D574FB38AEF00855BB08AEE84FEF92C675D98098D2B9EE82DAAE44A683E9A1A7521E8F1AC830FBE629F26B7BCBB1215254BDBDF2BB5939CFB99C440280BA2706336A6DC60BB74E65328B0D24D8D38B1DF3FA5F8074A8976E186E77016006884082727FFA07D483C3E6F78C602F17AFAA8FDAF44DB264D48298A10FE09DC545FC231FABBBB4BE77C1446800196727C0EF1F8F619A7F3B55092C157A1E692A75AD579AF08DD86D49F0F45F487D45D27C56F644D234C9ADBEC58EDEC43A6BE437A502F73FB71B69146376E18C13EABA13205881BAD2B3CD537F320C872450E93A65AEFE98F09B2B37C94A6DA8F1F787C7D5F1C02B7894CB79E85FEAD547707281893B2456656348BEFF762F0E9FE5CA3CCED49FB4E92EC4B8C24DDB66D929671253BFAEDFBED4E13E14EFA045DC38D611B452755130DAE35B6573A69F8DAE2633D6C516EDA822EFCC16A76D623BB1D8B52AEAA2D30D1D24EBE36907DA13165BA9D127277B4B948B249E3086FC9001DC8F888AFC7736E34ABF3164941497338B388EB8AA9845959E24C18C45BC1D0C5; UMB-XSRF-TOKEN=0LJ0BYQADkQoj6vB8l_l2eTzgfwjkBiyBuTxohuish7L5jlm5MyfvrOTa6xIeZIfBdJY26jP7XomECMTrKeoJGPYHfBxk0jw9Uvq7rioqlPtdVCg2hpZGVkdOuMiyCQ00; UMB-XSRF-V=xAzv0VchzsvRLVQAZWcN-mBrCJE0gsfJcKkGwQDNkIYUxT5g_9UMNH1OSXzWiQnaM-Ew--DoWYf_z3kBV_472GEmk2p_LnaC0SbBrnDENZU1

**Request Cookies** |   |   |   |   | 2620 |   |   |   |  
ARRAffinity | 58959f315ae110c77c27b360c2c2aa988f5fa92288eacf5bf282dfe6e588a5e9 | N/A | N/A | N/A | 78 |   |   |   |  
UMB-XSRF-TOKEN | 0LJ0BYQADkQoj6vB8l_l2eTzgfwjkBiyBuTxohuish7L5jlm5MyfvrOTa6xIeZIfBdJY26jP7XomECMTrKeoJGPYHfBxk0jw9Uvq7rioqlPtdVCg2hpZGVkdOuMiyCQ00 | N/A | N/A | N/A | 146 |   |   |   |  
UMB-XSRF-V | xAzv0VchzsvRLVQAZWcN-mBrCJE0gsfJcKkGwQDNkIYUxT5g_9UMNH1OSXzWiQnaM-Ew--DoWYf_z3kBV_472GEmk2p_LnaC0SbBrnDENZU1 | N/A | N/A | N/A | 119 |   |   |   |  
UMB_UCONTEXT | FDE184EE0BCC9A666F7F1F89E21A02C6D3802D2FB31FDD6EB089B2ADB0B1A9AA54A1ECBE5C0A6017068A0F8EC7753E12314DAC446E7A0AECE5705A178C7113E5EADDC1FC63C020C851379C072738F03263ECF79736E4D956CEC33EA2E67D0C50127DE7B9034F5AE95AE0267D0FAD0442FB166C316283925CE9067EB1244936CAFF8AA6F2E8C44BAE067AAAE4DC6E11683AB03A7357585BC2BE427DD18E29B32D34ECCB2AA8917A2F561316CAD0EBEC76F298E1E7026B09F69380A2347FE86F0A5E5EDEE57F772E9971681501D451D1125190ED2DCBADC195A9D138B148B6F2FEE65E731C88CFEF6BBE97217763F44217DEA7AD5FFBDD155188D3A0A2D97DD734683D44E6BEE48E02B543118E63B04BE64BF9A9FDD6149B0B22A1B8EF0C58E30E84597B980BE86D6F1468DE82274F0CC5DE6620A3070A20CF927B0D9D44E4150D86B1443EBDA37ECEB0795762959FACEDC130CD243F3EB9C4C3A4AA3FC75695642C3ED5A9AC9D13044F724DD521F3718FBB3979FE74FB195AD0B2EC2A83A27C17D0245379FC086A98E1D4BDBB701F3F39204DB87E95C63CB8E071CE77E1F422DBB19FB7DEBDC740C2C44568D339C7BC880E7C54AEDD99C2D0E526CF1B3C7434CE2DA02DAD10508FAE9B5E76B1E286F1D4D3CBD7A5474AC0869016906896174220CB5E6D574FB38AEF00855BB08AEE84FEF92C675… | N/A | N/A | N/A | 1775 |   |   |   |  
UMB_UCONTEXT_C | 2019-01-18T11%3A05%3A57.4886248%2B00%3A00 | N/A | N/A | N/A | 58 |   |   |   |  
XSRF-TOKEN | r3LbNLgTHrDXREbMSDPkEvfrTAJttdnkfDLg-G6i7GTVRn81FH0250Ef8bbFLuj63_zA86fl00x_ofvoj0Q2LSuXkehjrmaFeLozBnrN24j2fY1AsysQR8fQMtcbSkS80 | N/A | N/A | N/A | 142 |   |   |   |  
XSRF-V | 4V0mV3Vi4HxD4pOmPKazbyXdi0hwxMez930AUYyWUeqXfp3sSRGgZaS1uz90FVxohtmLmzcDaZuRmpxZkxEU0b4Gwf0NcOCrPrDTeyk-M-Q1 | N/A | N/A | N/A | 117 |   |   |   |  
_ga | GA1.3.1439173144.1547483328 | N/A | N/A | N/A | 33 |   |   |   |  
_gid | GA1.3.1024177007.1547572201 | N/A | N/A | N/A | 34 |   |   |   |  
ai_user | gEdMC|2018-09-20T12:49:32.027Z | N/A | N/A | N/A | 40 |   |   |   |  
MYPROJECTNAMECookieNotification | 1 | N/A | N/A | N/A | 26 |   |   |   |  
umb_installId | 48139884-58bf-46b9-a51e-cacba83937e9 | N/A | N/A | N/A | 52 |   |   |   |  
Response Cookies |   |   |   |   | 0

![417 missing token problem after umbraco v7 13 0 upgrade](https://user-images.githubusercontent.com/3273376/51385116-32fa3680-1b16-11e9-8f39-c9618aeaa3f0.png)
![umbraco menu is not shown](https://user-images.githubusercontent.com/3273376/51385123-38f01780-1b16-11e9-9c68-9cf1c4047c59.png)
![request_cookies](https://user-images.githubusercontent.com/3273376/51385127-3beb0800-1b16-11e9-8d99-29aa735b724c.png)

**Comment by nul800sebastiaan** [comment] 2019-01-18 11:52
Thanks for reporting again, unfortunately, we're not able to reproduce on a clean install at the moment. 

As soon as we can reproduce the problem somehow we can have a look at fixing it. Until then I'm going to close this until we get more information as to what might be causing this.

**Closed by nul800sebastiaan** 2019-01-18 11:52 UTC

**Comment by NurhakKaya** [comment] 2019-01-18 16:46
Thanks for the reply but as mentioned in the bug; the problem occurs after an Umbraco upgrade from v7.5.7 to v7.13.0 and this problem has been reported for multiple Umbraco versions and multiple times. I can see that you have spent some time to fix this problem but saying "we're not able to reproduce on a clean install" doesn't change the reality which is there is a bug from v7.5.7 to v7.13.0 which is causing this 417 missing token problem and this is a critical bug as you can't do anything in the Umbraco backoffice. Please check my logs and lead me to the correct direction at least. Thanks in advance.

**Comment by guruprasad83** [comment] 2019-01-24 12:48
@NurhakKaya - (incase if you are still facing the issue) 
Finally it worked for me now. I followed below approach and finally worked.
From this source - https://issues.umbraco.org/issue/U4-9873

Steve Edson 23 Jan 2018, 11:39:33
I had the same issue and none of the above would fix it.

I eventually solved it by deleting the umbraco and umbraco_client folders from my main project, and copying them back from the packages -> UmbracoCMS -> UmbracoFiles folder. This immediately solved the issue.

**Comment by NurhakKaya** [comment] 2019-01-24 17:17
@guruprasad83 thank you for the message, I have seen that solution but haven't tried it, yet. I will let you know about my result - hopefully a positive result.

**Comment by NurhakKaya** [comment] 2019-02-07 17:46
@guruprasad83 just to update you that it didn't work for me sadly :( But thanks for you help.

**Comment by cheeseytoastie** [comment] 2019-03-08 09:50
I'm seeing this on a client site. Worked fine on v7.11.1 now we've upgraded to v7.13.2 **and installed all outstanding server updates** we're now seeing this.

Backoffice works fine on first load - after a few clicks and publishes the save and publish stops working with this 417 error. 

I've cleared the app_data folder, rebuilt indexes etc and cleared all session cookies (also changed useUmbracoSSL to true) - nothing seems to fix it. 

The server is windows 2016 hosted on Azure - is that the same for you NurhakKaya?

**Comment by NurhakKaya** [comment] 2019-03-08 12:04
@cheeseytoastie The server is hosted on Azure and [KUDU](https://blogs.msdn.microsoft.com/benjaminperkins/2017/12/07/how-to-check-if-azure-app-service-is-on-2016-what-version-of-iis/) tells me that OS version is Microsoft Windows NT 10.0.14393.0.

And here is my structure;
- One App Service Plan for all live Apps and Slots
- One App Service for the Umbraco backoffice
- One App Service for the Front-end website (I will move this into a new App Service Plan to create multiple instances for load balancing, but this will be in the future)
- Some other App Services and Staging slots for API and deployment

**Comment by cheeseytoastie** [comment] 2019-03-08 12:21
I've isolated the issue to this. 

If you load the backoffice everything works. 
If you load the backoffice and then, in another tab, open the front end then in your other tab the save and publish now fails with a 417. 

So it seems to be something in the front end code killing the session and/or cookies that Umbraco relies on. 

Do you see the same behaviour? I think this is not an Umbraco thing for us but rather some custom code causing issues.

**Comment by cheeseytoastie** [comment] 2019-03-08 12:39
As an update - I can see that the UMB-XSRF-TOKEN cookie is being killed by the frontend. 

In our instance there is some javascript (possibly an AJAX call) that is killing this just after the page load. If i disable JS and load the frontend everything continues as normal. I'm still looking at it and will do further digging. My struggle is I can't recreate this locally.

**Comment by cheeseytoastie** [comment] 2019-03-08 12:55
OK - It's due to a third party cookie control tool that someone installed on our website. Despite accepting the cookies the javascript that it calls is killing the UMB-XSRF-TOKEN token. 

I wonder if the Umbraco backend should be checking for the existence of this cookie and bouncing users to the login splash screen as a protection though clearly this issue is *not* Umbraco's fault in our case. 

I hope the above helps you Nurhak - I'd be interested if it's exactly the same tool?

**Comment by NurhakKaya** [comment] 2019-03-09 00:52
I've had a quick look @cheeseytoastie , I think you are right, I could login to Umbraco backoffice and then I rendered the FE website and I have started to see this problem. When I disable the javascript in the browser and then refresh the Umbraco backoffice, then I don't see this problem in Umbraco website any longer. I will investigate this further and update you here, thanks and stay in touch @cheeseytoastie !

**Comment by digbyswift** [comment] 2019-04-25 13:05
Just adding this a reference in case someone else comes here as I have. As discussed, this is almost always an issue with the front end loading some cookie preference javascript.

In my case the issue was still occurring even when the backoffice was the only tab open. In this scenario, I checked the browser's dev tools Network view and I could see that a backoffice resource was 404ing and so was in turn loading a front end page and loading the page's cookie preference javascript.

**Comment by cheeseytoastie** [comment] 2019-04-25 13:14
> Just adding this a reference in case someone else comes here as I have. As discussed, this is almost always an issue with the front end loading some cookie preference javascript.
> 
> In my case the issue was still occurring even when the backoffice was the only tab open. In this scenario, I checked the browser's dev tools Network view and I could see that a backoffice resource was 404ing and so was in turn loading a front end page and loading the page's cookie preference javascript.

Nice detective work! Glad my post has helped someone else in some way.

**Comment by simonproctor** [comment] 2019-05-13 06:46
I've posted this to Umbraco, but in case someone comes here and doesn't see my comment I'll post my own symptoms and diagnosis of the issue.

When I see the white screen of death (WSOD) I've found its because the ASP.NET session ID cookie is missing. This happens when I go straight to /umbraco. Because that cookie isn't set, anything relating to XSRF doesn't seem to work.

Logging in only sets the affinity cookie (if you're on ucloud) and the umbcontext. If you then hit the front end of your site (immediately after WSOD) and then go back to the back end, you'll get your ASP.NET session cookie.

You can do this without logging out and in again. The editing screen loads for me straight away. 

Note that this may not be the only resolution, it may be multiple issues, but this definitely fixes it for me. Previously we had thought it was custom redirects but those have been removed as part of this testing.

**Comment by dave0504** [comment] 2020-12-08 09:09
Just in case anybody else stumbles across this issue, for us the 3rd party cookie control was indeed the culprit. In this case is was provided by [Civic UK](https://www.civicuk.com/cookie-control/documentation) and the fix is pretty simple change to the config object used for initialisation, just add 'UMB*' wildcard: 

necessaryCookies: ['ASP.NET_SessionId', 'XSRF-TOKEN', 'XSRF-V', '__RequestVerificationToken', '__zlcmid', 'UMB*']

**Comment by digbyswift** [comment] 2020-12-08 10:32
@dave0504 Just my opinion but I don't think it would generally be a good idea to put anything in the front end that identifies the backoffice techonology. The way I have got round this is to exclude the Civic UK code from the 404 page which seems to be the combined source of the issue.

**Comment by dave0504** [comment] 2020-12-08 10:53
@digbyswift 

Ours wasn't being caused by any 404 issues, it was on any page where the Civic UK plugin was setting cookie preferences, with the user then going back into the back office.

**Comment by digbyswift** [comment] 2020-12-08 11:24
@dave0504 Interesting, I wouldn't expect that to happen since the cookies should only be removed on pages where the Civic script is called. When a backoffice page loads, the cookie should be reinstigated but since you wouldn't have the Civic plugin loading on a backoffice page, it shouldn't get removed again.

Our issue was becuase an Ajax call to a nested content data type resulted in a 404 for an image. The 404 page had the Civic script in it (via the master view) so this resulted in the cookie from being removed from the response.

There's a thread here 
https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/60627-417-Missing-token-in-the-backoffice#comment-306510 where you can put your findings.
