### ISSUE TITLE
Can't upload large media files on Cloud

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco-CMS#12239] opened 2022-04-08 10:43 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.2

### Bug summary

When trying to upload a large mp4 file on cloud I get errors in the console saying the file is too large

This issue is not present when trying to upload it on locally on a clone of same environment.

It just fails with no error from the backoffice, in console it gives you some errors like:
 `"data":"The page was not displayed because the request entity is too large.",`

`MaxRequestLength` and `MaxQuertStringLength` has been set according to our documentation in both `appsettings.json` and `appsettings.Production.json` when testing this.

I have tested this with a small mp4 file, no issues there, gets uploaded just fine.

### Specifics

When drag and dropping the 60MB file on cloud I get the following errors in console
![image](https://user-images.githubusercontent.com/54025229/162418257-dc7ec7e9-8098-47c3-811e-6de2a2d66500.png)

When I try to "Create" a video instead, i get the following errors in the console, and it just keeps spinning.
![image](https://user-images.githubusercontent.com/54025229/162418462-c644c31f-bc48-41f2-b414-d5e8e2f400dc.png)

```
"umbraco-backoffice-js.js.v198fc2fdfc142f031ab542ea94f2dd17b251be95":"152 Possibly unhandled rejection":{
   "data":"The page was not displayed because the request entity is too large.",
   "status":413,"
```

### Steps to reproduce

1. Have a v9 project on cloud

2. [Include following in appsettings.json](https://our.umbraco.com/documentation/Reference/V9-Config/MaximumUploadSizeSettings/#using-kestrel) (also tried with appsettings.Production.json as it was live, didn't change anything)
3. 
```json
"Runtime": {
      "MaxQueryStringLength": 250,
      "MaxRequestLength": 500000
      }
```
      
4. Go to media
5. Open console
6. Drag and drop large mp4 file (I used this one, its around 60mb https://www.pexels.com/video/man-using-vacuum-cleaner-in-forest-6636083/)
7. Get error

### Expected result / actual result

Expected result: A successful upload of mp4 file
Actual result: Error in console and not a successful media upload.

**Comment by nul800sebastiaan** [comment] 2022-04-08 11:43
Thanks @jesperlange - is the site hosted in IIS? Because if it is, you need to add a web.config as described in the documentation with the correct settings. https://our.umbraco.com/documentation/Reference/V9-Config/MaximumUploadSizeSettings/#using-iis

**Comment by Frost117** [comment] 2022-04-08 14:29
Hey @nul800sebastiaan 

I am getting the same kind of issue in version 9.4.3 and my project is running in Azure. 

In order for to reproduce I first needed to install v9 on Azure and I followed this:
https://24days.in/umbraco-cms/2021/scripting-azure-deployment/ 

I get this error when I try and upload the file that is above 60 mb:

`umbraco-backoffice-js.js.v59ef5dfbd8842d5ef98465f28a2fe58814a408ba:152 Possibly unhandled rejection: {"data":{"ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":null,"StackTrace":null},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/umbraco/backoffice/umbracoapi/media/PostAddFile","fields":{"currentFolder":"-1","contentTypeAlias":"umbracoAutoSelect","propertyAlias":"umbracoFile"},"file":{"key":"9424fee0-c653-46c4-ab66-1c0a1ed7617d","messages":[]},"_isDigested":true,"_chunkSize":null,"headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-UMB-SEGMENT":null,"X-UMB-XSRF-TOKEN":"CfDJ8DmREbBiWmFAli0xT1RsIQxtt6QlGb2g0oxr6PodYHAbXycPzvK30tsuZX9jrM0O5M2HU-gCW9Wa7h3i1BTZlm610NHpV12eRrJsMad6Ubs9tVGFxYbrXm1vzUY3vM9nbz984hmap2hzvzGPe_fxfo7wa59zGGzBXRjNHFtF1acdpx9pcqj0Kff7TV2LxSqqiA"},"_deferred":{"promise":{}}},"statusText":"","xhrStatus":"complete"}`

Anything below 60mb works fine. 

If you want access to the site then I can share the details with you

**Comment by aguyfromdenmark** [comment] 2022-04-19 07:59
I reported this bug originally, to the support team. 
The sites where the bug was reported on is running on cloud. 

I have found a kind of funny workaround. 
With the site setup locally on IIS, adjust the maxRequestLength in the web.config file. 
Then, upload the files to your local solution, and then transfer them to your cloud environment.

**Comment by nul800sebastiaan** [comment] 2022-04-19 08:47
@Frost117 @aguyfromdenmark Do you have a web.config with the configuration as mentioned in that link I posted on your IIS (cloud) server?

**Comment by aguyfromdenmark** [comment] 2022-04-19 08:51
@nul800sebastiaan  Nope, that is only present on my local IIS setup. I am also able to transfer the files from DEV to LIVE on cloud. But I can't upload them directly to any of the cloud environments.

**Comment by nul800sebastiaan** [comment] 2022-04-19 08:52
Alright, the web.config needs to be on the server as well, try that out please.

**Comment by meyntony** [comment] 2022-04-19 08:56
@aguyfromdenmark 
On v9 for cloud the web.config transforms are done differently (in case you need different values for the environments), you could check this post on how it should be done. https://github.com/umbraco/Umbraco.Cloud.Issues/issues/456#issuecomment-934687647

You may close the issue after you confirm this fixes the issue.

**Comment by aguyfromdenmark** [comment] 2022-04-19 09:04
@nul800sebastiaan @meyntony I can confirm that configuring the web.config file with the "IIS method", and pushing those changes to the cloud, fixes the issue. I will make a pull request for the documentation, clarifying that you need to use the IIS method in order for this to work on Cloud, as both the support team and I was very confused by this.

**Comment by nikolajlauridsen** [comment] 2023-01-05 07:20
Hey all, looks like this issue has been resolved by updating the web.config 😄 So I'll go ahead and close this down, please feel free to let us know if this is in fact not resolved 😄

**Closed by nikolajlauridsen** 2023-01-05 07:20 UTC
Labels: type/bug

**Comment by nielslynggaard** [comment] 2023-01-09 10:02
I had the same issue and couldn't quite get it to work on Azure. It turned out that on Azure this would only work for me if the appsettings.config file didn't contain the maxrequest-settings and these settings were only present in a web.config file.
