### ISSUE TITLE
Disappearing action button

### ISSUE THREAD

**Issue by SaDa1337** [umbraco/Umbraco-CMS#3097] opened 2018-10-01 13:57 UTC
Hey,

Recently we've upgraded our setup to umb 7.12.2. On that version we've noticed a problem that the action button (top right - see next screenshot) can disappear from time to time IF you open the document in backoffice through the url (not by clicking on the nav tree)

working:
![image](https://user-images.githubusercontent.com/28300975/46292900-56fb3180-c592-11e8-8042-59241982269b.png)

after refresh, missing:
![image](https://user-images.githubusercontent.com/28300975/46292934-6ed2b580-c592-11e8-98c1-bf780fc88471.png)

Reproduction
------------

### Bug summary

Disappearing action button

### Specifics

Happens only from time to time (50% of refreshes). Did not happen on 7.8 umbraco. We have a bit of customizations done on top of backoffice, but they most likely do not affect this.

### Steps to reproduce

Refresh the backoffice page a few times. 

### Expected result

The content of the page is the same every time

### Actual result

Observe the action button disappear (does not happen 100% of the time)

**Comment by nul800sebastiaan** [comment] 2018-10-03 08:54
✔ I can reproduce the problem.

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by KimHolzmann** [comment] 2018-10-04 11:09
if I select the script section and a fil in there, "/umbraco#/settings/scripts/edit/umbraco-starterkit-app.js"
It fails on almost every refresh, it dosn't get the node from the loadtree (args.Node empty).
I have tried to fix it but with no luck :-(
But seem like it's identical  to issue #3141

**Comment by dawoe** [comment] 2018-10-04 13:55
I don't think it's related to #3141 because that was introduced in upcoming 7.13. But i can reproduce it my self

**Comment by dawoe** [comment] 2018-10-04 14:17
I think I boiled down again to navigationService.syncTree... the tree is not fully initialized when this called from the edit controller. So the syncTree is not setup yet.

Will try to find a solution.

Dave

**Comment by KimHolzmann** [comment] 2018-10-04 14:36
I get stuck the same place :-)

**Closed** 2018-12-19 14:03 UTC
Labels: community/up-for-grabs, help wanted, type/bug
