### ISSUE TITLE
Grid List Editor's 'CreateButtonLabel' Does not Respect Translation 

### ISSUE THREAD

**Issue by IbrahimMNada** [umbraco/Umbraco-CMS#17233] opened 2024-10-10 05:35 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14+

### Bug summary

When having the Umbraco Backoffice as any other language than the default for example Arabic. 
The Create Button at the grid list editor does not respect any translations. (Image Bellow) .

<img width="716" alt="image" src="https://github.com/user-attachments/assets/5aeef469-a607-45bc-b3ab-b142362b1a61">

### Steps to reproduce

1-Create a block list for any doc type with translations
2- Go to block type and Check the `CreateButtonLabel`
3-you will notice that its in the name of the doc type, not the Translation 

### Expected result / actual result

Expected result => show the translation value for the document type. 
actual result => the Doc type name is shown without any respect for translations
```[tasklist]
### Tasks
```

**Comment by IbrahimMNada** [comment] 2024-10-10 05:49
fixed at https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2435

**Comment by iOvergaard** [comment] 2024-10-10 07:14
I believe this issue is a duplicate of #17179 but please correct me if I'm wrong. I believe it will be fixed with https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2424.

**Comment by IbrahimMNada** [comment] 2024-10-10 07:18
@iOvergaard  I'm Not really Sure ,I can validate today and get back to with more info

**Comment by iOvergaard** [comment] 2024-10-11 07:26
Testing this, I think there is a missing case that your PR fixes. I will reopen this.

**Closed** 2024-10-11 07:32 UTC
Labels: type/bug, area/frontend, affected/v14, affected/v15
