### ISSUE TITLE
Decimal field not saved in Russian localization

### ISSUE THREAD

**Issue by alek92wis** [umbraco/Umbraco-CMS#13135] opened 2022-10-06 12:20 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

In the Content section, an error pops up when trying to store a value in the Decimal field.
The error is observed in Russian localization.

### Steps to reproduce

1. Select Russian localization.
2. Create a new page, add a decimal field
3. Add a value for this field to the Content and try to save

**Comment by nikolajlauridsen** [comment] 2022-12-07 09:03
Heya I can reproduce this as well, there seem to be something odd going on with parsing strings with locales here. 

I also found another issue, that if you put the backoffice in German, the save will go through, but the value will be wrong if you set the value to be `0,7` and then save and publish, navigate away an then navigate back you'll see that the value is now 7 for some reason.

**Comment by nikolajlauridsen** [comment] 2023-01-27 10:00
I'll go ahead and close this one as it's a duplicate of #12757

**Closed by nikolajlauridsen** 2023-01-27 10:00 UTC
Labels: type/bug, state/reproduced, affected/v10, affected/v11

**Comment by Zeegaan** [comment] 2023-01-27 10:20
Hey @alek92wis can you confirm that this issue is fixed with? https://github.com/umbraco/Umbraco-CMS/pull/13741, I believe it is 😊
