### ISSUE TITLE
PluginController / UmbracoAuthorizedApiController returns 404 when defined in a separate project

### ISSUE THREAD

**Issue by Yannis-S-Standaert** [umbraco/Umbraco-CMS#14584] opened 2023-07-20 10:57 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

The exact same controller is not found when placed in a separate project referenced by the umbraco project, but it is found when placed in the umbraco project.

### Steps to reproduce

Two csproj:

1. My.Package (referenced by My.Website)
``` csharp
// /umbraco/backoffice/mypackage/my/dosomething -> 404
[PluginController("mypackage")]
public class MyController : UmbracoAuthorizedApiController {

    [HttpGet]
    public IActionResult DoSomething() {
        return Ok("Done");
    }
}
```

2. My.Website
``` csharp
// /umbraco/backoffice/mypackage/my/dosomething -> 200
[PluginController("mypackage")]
public class MyController : UmbracoAuthorizedApiController {

    [HttpGet]
    public IActionResult DoSomething() {
        return Ok("Done");
    }
}
```

### Expected result / actual result

Regardless of where the controller is defined, shouldn't it be picked up by Umbraco / .NET and registered as a controller with route /umbraco/backoffice/{area}/{controller} ?

---
_This item has been added to our backlog [AB#31447](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31447)_

**Comment by Zeegaan** [comment] 2023-07-21 08:35
I can certainly reproduce this 🐛 
I used a `UmbracoApiController`
The route `/umbraco/mypackage/my/dosomething` disappears when its put in another project 🤔

**Comment by Zeegaan** [comment] 2023-07-21 08:40
With further investigation, this happens in all versions, I will take this up with the team Monday to discuss this behavior 😁

**Comment by Zeegaan** [comment] 2023-07-24 08:10
Ah I've been trying this all wrong, my bad! 🙈

**Comment by kjac** [comment] 2023-07-24 09:41
Hi @Yannis-S-Standaert,

I have taken over on this issue. However, I can't reproduce it.

The solution structure looks like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/02520628-34ef-4c8b-bea1-9223277504d2)

As the screenshot shows, there are controllers placed within the project ("internal" controllers) controllers in a referenced class library ("external" controllers). There are public and protected (authorized) controllers for both cases.

The "Site" project references the "Controllers" project.

The dashboard in App_Plugins consumes to both the internal controllers and the external controllers, and it is able to invoke all of them:

[14584.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/91abf2c0-dcd8-416b-8561-3c0e372a7a1a)

I have attached the solution [here](https://github.com/umbraco/Umbraco-CMS/files/12144141/Umbraco12.zip), in case you'd like to test it for yourself.

I'm going to close this issue now. If you keep experiencing this, please reopen with additional steps to reproduce.

**Closed by kjac** 2023-07-24 09:41 UTC
Labels: type/bug

**Comment by Yannis-S-Standaert** [comment] 2023-07-25 11:39
@kjac 

Thank you for looking at this, your test solution is indeed exactly as I described and works perfectly as intended. I will see if I can figure out the minimal setup needed to reproduce this myself based on my project.
