### ISSUE TITLE
GetCropUrl returns null with valid cropAlias param V8

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/Umbraco-CMS#5737] opened 2019-06-27 13:31 UTC
### Bug summary
ImageCropperTemplateExtensions.GetCropUrl returns null when provided a valid cropAlias parameter unless you save each image in your media library after adding a new crop.

### Specifics
This occurs in 8.0.2 and v8/dev using Chrome (but should affect all browsers)

### Steps to reproduce
- V8 with SK installed
- Update Image Media Type -> Update umbracoFile Image Cropper DataType settings to include a crop type (ie square)
- Update Products.cshtml / template with `<img src='@product.Photos.GetCropUrl("square")' />`
- View page on frontend & confirm image renders (they don't)
- Goto Media Section & Choose a Product Image
- Set manual crops for the image
- View page on frontend & confirm image renders (they do)

### Expected result
The images should be rendered. See reproduction for more details.

### Actual result
The images are not. See reproduction for more details.

**Comment by nul800sebastiaan** [comment] 2019-06-27 19:26
Yes, unfortunately this will be true for any updates you will do for datatypes. We do not update existing data when a datatype updates simply because it is an expensive operation that could take a very long time and much processing power. 

It's up to you to do some defensive querying for this or possibly provide a migration tool for when you know things will need to change. Just be aware that you'll need to be careful with that migration script in case you have a large number of nodes (see previous paragraph).

**Comment by nul800sebastiaan** [comment] 2019-06-27 19:37
Hmm, I just saw your related PR, and it's not what I thought you wanted to get solved. ;-)

I'll have a look at it soon, this might be an okay solution, not sure yet.

**Comment by kjac** [comment] 2020-01-02 12:04
@cleversolutions I can't reproduce this issue on the latest codebase. `GetCropUrl(string alias)` returns URLs for newly added crops on the image cropper datatype, even if the image in question hasn't been saved with the newly added crops.

Could I ask you to try this out again on the latest codebase?

**Comment by cleversolutions** [comment] 2020-01-06 00:29
Thanks @kjac I’ll retest and confirm tomorrow.

**Comment by cleversolutions** [comment] 2020-01-07 14:30
Hi @kjac I reproduced it this morning from a fresh clone of v8/dev. 
I created a new site with the starter kit.
Added a 100x100pixel crop to ImageCropper data type called Test.
![cropper](https://user-images.githubusercontent.com/23444011/71902384-fad97280-312f-11ea-9616-7f4778a9b306.JPG)

Then on line 35 of Products.cshtml changed the line to use the crop
```
<div class="product-grid">
            @if (Model.FeaturedProducts != null)
            {
                foreach (Product product in Model.FeaturedProducts)
                {
                    <a href="@product.Url" class="product-grid__item" style="background-image: url('@product.Photos.GetCropUrl("Test")')">
                        <div class="product-grid__item__overlay">
                            <div class="product-grid__item__name">@product.ProductName</div>
                            <div class="product-grid__item__price">@Model.DefaultCurrency @product.Price.ToString("F")</div>
                        </div>
                    </a>
                }
            }
        </div>
```
No images render. I save the jacket image then it renders while the others don't. 
![result](https://user-images.githubusercontent.com/23444011/71902449-1ba1c800-3130-11ea-8366-526540f1d5bc.JPG)

**Comment by kjac** [comment] 2020-01-07 18:20
Hi again @cleversolutions 

This is mysterious! For the life of me I can't reproduce the issue 😞 

I have tried both with an imagecropper property directly on the content item and using an imagecropper on a picked media item. To no avail.

Here's how I have tested the first scenario (I'm guessing this is much along the lines of what you're experiencing):

1. I have some content based on a content type that has an imagecropper property named `Media`.
2. I am rendering the `Media` property like this:
```cshtml
<ul>
    <li>Crop 1: @Model.Media.GetCropUrl("Crop 1")</li>
    <li>Crop 2: @Model.Media.GetCropUrl("Crop 2")</li>
    <li>Crop 3: @Model.Media.GetCropUrl("Crop 3")</li>
</ul>
```
3. Initially the imagecropper datatype has no crop named "Crop 3", so the last `<li>` is empty. But when I add "Crop 3" to the imagecropper datatype _without_ saving the content, the crop is immediately available to the rendering.

Here's a GIF of the whole thing:

![image-cropper-add-crop](https://user-images.githubusercontent.com/7405322/71918467-9bf11900-3182-11ea-83a6-18ae8deb2e1a.gif)

**Comment by cleversolutions** [comment] 2020-01-07 21:46
Perhaps the difference is your document type uses an image cropper directly where as starter kit uses a media picker. I’ll test this idea further tomorrow.

**Comment by kjac** [comment] 2020-01-08 08:33
@cleversolutions I tried the same thing with a media picker... same result.

**Comment by uppercuut** [comment] 2020-01-09 16:31
did any one fixed this issue ?

**Comment by nul800sebastiaan** [comment] 2020-01-10 08:00
@uppercuut We can't seem to reproduce the issue, so if you have more info on how to make it fail then we might have a chance to fix it.

**Comment by uppercuut** [comment] 2020-01-11 10:27
@nul800sebastiaan 

 Im using Umrbaco8  Image Cropper
   i retrieve the Data using:  "Model.Value<IPublishedContent("websiteImagecropped")" is always Null 

 "Model.Value<dynamic>("websiteImagecropped")" returns the url as string 
"Model.Value("websiteImagecropped")" returns the url as string  
umbraco doc says that: "The cropper returns a dynamic object, based on a json structure like this"

{
"focalPoint": {
"left": 0.23049645390070922,
"top": 0.27215189873417722
},
"src": "/media/SampleImages/1063/pic01.jpg",
"crops": [
{
"alias": "banner",
"width": 800,
"height": 90
},
{
"alias": "highrise",
"width": 80,
"height": 400
},
{
"alias": "thumb",
"width": 90,
"height": 90
}
]
}

**Comment by cleversolutions** [comment] 2020-01-11 13:00
We are launching a new Umbraco 8 site on Monday. Once it is live I’ll have a bit more time to spend testing this further. I’ll post a gif of reproduction maybe mid week.

**Comment by rbottema** [comment] 2020-01-20 12:48
@kjac Perhaps the difference is that you are going from 2 to 3 crops, where @cleversolutions is going from 0 to 1 crops?

**Comment by jesperbrasmussen** [comment] 2020-01-31 13:41
I had this issue as @cleversolutions describes on an Umbraco 8.1.5 installations, but after upgrading to 8.5.3 i looks like it's solved

**Comment by cleversolutions** [comment] 2020-03-06 19:41
I’ll record a screen capture after I get back from vacation. I was able to still reproduce the problem on a fresh 8.6 rc install.

**Comment by cleversolutions** [comment] 2020-03-23 14:37
Here is a screen video of the problem using 8.6 RC-0. I fire up a new starter site, show the default  products page working. I add a crop called "test" to the image cropper, update the products template to use the crop, show that the page doesn't render with the new cropper, then save the biker jacket image and reload the products page to show that the biker jacket image shows while the others do not. The expectation, if everything is working properly, is that all images should show without having to resave the images after adding the new crop alias to the image cropper. 

![2020-03-23-10-25-01](https://user-images.githubusercontent.com/23444011/77327482-adfa4680-6cf1-11ea-9d44-176832d26bd4.gif)

**Comment by cleversolutions** [comment] 2020-03-23 14:47
@rbottema good catch. I continued my test above adding a second crop, and it works as expected. It seems this problem only happens when going from 0 to 1 or more crops.

![2020-03-23-10-44-50](https://user-images.githubusercontent.com/23444011/77328937-a50a7480-6cf3-11ea-9db3-aab2abeb2684.gif)

**Comment by joepvtl** [comment] 2020-04-28 15:06
Hi @cleversolutions,

Have you tested this on 8.6.1?

**Comment by ronaldbarendse** [comment] 2020-04-28 18:20
@joepvtl This issue is verified to exist in the latest 8.6.1 release, but only happens when adding the first crop to the Image Cropper configuration. PR https://github.com/umbraco/Umbraco-CMS/pull/6950 fixes the problem, but that's waiting to get reviewed/merged.

**Comment by thaihoc2** [comment] 2020-07-25 06:52
I'm working with Umbraco 8.6.3 and got the same issue: GetCropUrl() returned the below value without Image Url 
<img src="?anchor=center&amp;mode=crop&amp;width=200&amp;height=200">
I think that's a very big issue, is there any plan to release the fixes?

**Comment by nul800sebastiaan** [comment] 2020-07-27 07:41
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6950

@thaihoc2 This PR is now merged but it's not for your issue, I think you have the problem as described in https://github.com/umbraco/Umbraco-CMS/issues/8116 (the short version of this is: try using `@Url.GetCropUrl("")`.

**Closed by nul800sebastiaan** 2020-07-27 07:41 UTC
Labels: community/pr, hacktoberfest/contrib-2019, release/8.8.0, type/bug
