### ISSUE TITLE
Section title is not clickable 

### ISSUE THREAD

**Issue by Amalie-Wowern** [umbraco/Umbraco-CMS#17203] opened 2024-10-07 13:22 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2 & 14.3 & 15.0.0-rc1

### Bug summary

When i go to a new section for example Content i can see the avaible dashboards for that area.
When I do something else in that section i cannot click on title and get back to the overview, i then need to click on the section again

![billede](https://github.com/user-attachments/assets/358f0f49-632a-4e77-8e90-9d5cf0bde4fd)

### Steps to reproduce

Open a umbraco 14.2+ 
Log in
edit a content node
click on the section title 

### Expected result / actual result

I would exspect the title to be clickable as in umbraco 10-13 

---
_This item has been added to our backlog AB#44886_

**Comment by iOvergaard** [comment] 2024-10-08 07:07
Thanks for the report. I agree, it's something we should get fixed.

**Comment by Amalie-Wowern** [comment] 2024-10-08 08:16
Maybe it could be a ticket for hacktober?

**Comment by IbrahimMNada** [comment] 2024-10-08 16:16
I'm working on it gonna deliver PR Soon

**Comment by IbrahimMNada** [comment] 2024-10-08 16:48
fixed on 
https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2428

**Comment by nielslyngsoe** [comment] 2024-10-09 07:49
Hi @Amalie-Wowern and @IbrahimMNada 

I'm sorry there has been a misunderstanding regarding this issue, which first has come to my awareness now.

Its on purpose that the sidebar headlines no longer are interactive, let me put a few words to why.

* First and foremost, its a common UX pattern to click on the actual link, in this case in the header to get back to the 'frontpage'/root of a section. (This has been fixed as of v.14, you most likely learned to click the sidebar headline cause in older version this was the only way to get back, clicking in the header again had no effect — confusing to a lot of new users)

* Secondly we sometimes have multiple sidebar headlines, especially if you have some packages installed. From a visual point of view multiple headlines would intuitively speak towards having multiple destinations of such. But going that route would mean the Overview page of a section would be different from the specific sidebar-headline destinations, unless the first one was the overview one, but again that would not be super intuitive.

So v.14 was the point in time to rip of the badge and teach users to use the top-navigation — leaving pro-users with a change, but making it more intuitive for new users. — Let me know how you feel about it and if you have tought which I have not covered.

There is also an previous issue on the same topic has been closed before here, with additional descriptions:
https://github.com/umbraco/Umbraco-CMS/issues/16680

Thanks and sorry for the inconvenience.

**Closed by nielslyngsoe** 2024-10-09 07:49 UTC
Labels: community/up-for-grabs, state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v14, affected/v15

**Comment by IbrahimMNada** [comment] 2024-10-09 08:37
@nielslyngsoe 

to answer your points ,I would really appreciate if you take a few minutes to check the PR 
its support multi url per tree and the Url is fully configurable.

the reasons you mentioned are well handled - i think-.

**Comment by IbrahimMNada** [comment] 2024-10-09 12:52
@iOvergaard 
Any insite technical wise would be much appreciated

**Comment by iOvergaard** [comment] 2024-10-11 06:48
Hi @IbrahimMNada 

Unfortunately, this is not something we want to support for the time being. Sorry for any inconvenience I may have caused by initially marking this as up-for-grabs as I was not aware of #16680.

I had a chat with the team, and we concluded that we would ideally like to solve the UX confusion by changing the way section titles are shown especially where there is only one section available in the menu.
