### ISSUE TITLE
Adding custom mediatype

### ISSUE THREAD

**Issue by MartinTiemens** [umbraco/Umbraco-CMS#15719] opened 2024-02-15 08:55 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.7

### Bug summary

We like to add a new mediatype for subtitle files (.vtt) but when the data type and media type are created I'm unable to select a subtitle file.

### Specifics

As a developer I like to add a new media type for subtitle files so we can give the content admins the option to add subtitles to mp4 videos. Because a subtitle is a file we like to use the media section and a media pciker for this.

### Steps to reproduce

**1. Create a new upload data type**
Create a new upload data type or duplicate an existing one. For the accepted file extensions add the expected file type, in our case vtt. 

![Datatype Upload Subtitle](https://github.com/umbraco/Umbraco-CMS/assets/39366212/fee3a779-852e-4781-9f79-d362fb891459)

**2. Create a new media type**
Create a new media type or duplicate an existing one. Make sure you use the newly created data type.

![Mediatype Subtitle](https://github.com/umbraco/Umbraco-CMS/assets/39366212/c63a970e-ec9c-4a15-b528-5aa7692fb9cb)

**3. Create a property woth the new media type**
Add a media picker property to a document type with the newly created media type

![Datatype Video Subtitle Optional](https://github.com/umbraco/Umbraco-CMS/assets/39366212/7fc42fbf-f740-49d0-be63-b5f92ea34887)

**4. Add a media item**
Try to add the media item in content with the specific media type. When you want to selected a file it's indicated that's the wrong type and you are unable to add the specific file.

![Vtt select not working](https://github.com/umbraco/Umbraco-CMS/assets/39366212/7f76bf7d-0449-432c-8df0-01e7f511982e)

### Expected result / actual result

I would have expected to add a file with the specific file extension. 

The only way I can solve this issue now is to add the 'file' media type besides the custom media type.

**Comment by andr317c** [comment] 2024-02-15 12:10
Hey!
Thanks for reporting this issue. I was able to reproduce this if the Subtitle MediaType was not allowed at root, and if the Folder MediaType didn't have the Subtitle as an allowed child node type. This is expected behavior as you would never be able to create a subtitle. Is your setup the same? 😄

**Comment by MartinTiemens** [comment] 2024-02-15 13:48
Hello Andr317c,

thanks for your reply. The subtitle MediaType was enable to be allowed at root but I didn't add the the MediaType under Folder rights. I've enabled the option but the problem remains. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/39366212/ad2c23f1-9767-425b-8fda-15f6bf4da692)


To be clear about the issue, I can upload a subtitle file directly I can't select it with the media picker when I use the subtitle media type. What do you mean with it's expected behavior, shouldn't it be possible to select media files based on specific file extensions?

**Comment by andr317c** [comment] 2024-02-15 14:34
Hey again!
What I meant about the expected behaviour was that if you didn't have the custom mediaType as allowed at the root, and it wasn't allowed in the child nodes for the folder mediaType either. Then you would have no way of creating a Subtitle mediaType(unless it was allowed under another mediaType). But that is not the issue.

I'm currently unable to reproduce your issue 😕.

Here is a GIF of what I have done. Please let me know if I did not follow your exact steps.
![vttFile](https://github.com/umbraco/Umbraco-CMS/assets/73799582/78f530ac-f3ce-436a-80c1-c254440355a8)

If not, you can try to see if you can reproduce this issue on a clean install. If you encounter the same problem, please let me know!

**Comment by MartinTiemens** [comment] 2024-02-15 14:39
Hello!

thanks for the explanation. I’ll double check it next week but as far as I can see we have the same implementation so I’m curious why it’s not working on my side. I'll create a clean and give it a shot, hopefully I see a difference. 

Thanks for the help so far.

**Comment by MartinTiemens** [comment] 2024-02-27 12:14
Hello @andr317c,

I've created a new project and added the media, data and document types and it worked like you described. Than I added the same things to the current project and it worked. When I compare both all types they are exactly the same. I'm confused.

**Comment by andr317c** [comment] 2024-03-11 07:07
Hey again!
It sure is weird 😕. However since you are not able to reproduce the bug from a clean install, I will close this issue. If you can reproduce it, please ahead and reopen this issue 😄

**Closed by andr317c** 2024-03-11 07:07 UTC
Labels: state/needs-more-info, type/bug
