### ISSUE TITLE
Pagination Missing for User Groups in Umbraco - Realy long loading times

### ISSUE THREAD

**Issue by Yinzy00** [umbraco/Umbraco-CMS#15822] opened 2024-03-03 21:29 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13

### Bug summary

User groups lack pagination functionality, leading to significant slowdowns when managing a large number of groups. This becomes particularly evident when dealing with hundreds of groups, causing performance issues and hindering user experience.

### Specifics

- The issue arises within the user groups section of Umbraco, where pagination is absent.
- The problem becomes pronounced as the number of user groups increases, causing significant performance degradation.
- Currently observed in a project with approximately 500 groups, with expectations of further growth.

### Steps to reproduce

1. Create a substantial number of groups, e.g., 500 (can be done using the provided test controller or similar method).
2. Navigate to the users section within Umbraco.
3. Choose one of the following options:
Option 1: Click on "Groups" directly.
Option 2: Click on a user and then proceed to click on "Add Group."
[TestController.zip](https://github.com/umbraco/Umbraco-CMS/files/14474646/TestController.zip)

### Expected result / actual result

The user groups dashboard should display a limited number of groups per page (e.g., 25) and provide pagination controls at the bottom of the page, similar to other dashboard functionalities within Umbraco.

**Comment by nul800sebastiaan** [comment] 2024-03-15 12:10
Just as an FYI before anyone starts working on this, we are looking for some more info first before we can work on this feature, as noted in the related PR #15824.

**Comment by Migaroez** [comment] 2024-04-30 12:28
The use case stated on the PR is on the extreme side and one could argue that managing 250+ different sites in one instances is a bad idea.

I however agree with the use case of specifying precise permissions and the amount of groups this might entail. Let's say you have editors, writers and reviewers and translators. You also have a general pages, blog with 10 different categories, business pages, news,... and the access to each of these content silo's need to be able to be segregated. Then you end up with 52+ user groups. So from an enterprise like setup where the moto is usually "only give access to what is absolutely required" this makes a lot of sense.

On top of that, pagination is never a bad idea as shown in the new Management API where we provide skip/take for the user groups.

I will talk to the team to see how we will proceed with this issue and the related PR.

Thank you for the clean report and the effort on the PR @Yinzy00 and my apologies for the delayed response.

**Comment by Migaroez** [comment] 2024-05-22 12:12
So, I had the chat and here is the conclusion.
We cannot accept the PR nor change the behavior in v13 for the reason @nul800sebastiaan highlighted in the linked PR and because of functional breaking changes.

It is true that pagination will lead to a better experience, one of the reasons why we changed this in v14, but it changes the designed/expected behavior of the product. For the backend and front-end services we can add this functionality while retaining backwards compatibility, but UI wise, we will break the expected behavior that users and or implementers may rely on. Since moving to [semantic versioning](https://umbraco.com/blog/moving-to-semantic-versioning/) we no longer willingly introduce breaking changes in anything but a major release.

Because of this conclusion I will be closing this issue as well.

**Closed by Migaroez** 2024-05-22 12:12 UTC
Labels: status/idea, type/feature
