### ISSUE TITLE
Umbraco 9 GetDictionaryValue not working?

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#10977] opened 2021-08-30 01:37 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0 RC2

### Bug summary

hi - using the following code in a view:
`var mydictionaryvalue = @Umbraco.GetDictionaryValue("My Key here");`
It always returns an empty string. 
The Language setup looks stock standard and the dictionary item does exist and has a value.

thanks

### Steps to reproduce

1. create dictionary with specified key
2. add code from description to view or partial view

### Expected result / actual result

expected results: GetDictionaryValue method returns value for key specified.
actual results: empty string

---
_This item has been added to our backlog [AB#13859](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13859)_

**Comment by nul800sebastiaan** [comment] 2021-08-30 08:42
Likely related to https://github.com/umbraco/Umbraco-CMS/issues/10927

**Comment by bergmania** [comment] 2021-08-30 11:22
I tried to reproduce, but i Can't

This is my setup.
- Languages
   - Untouched
![image](https://user-images.githubusercontent.com/1561480/131331529-29712f2a-6782-418c-abc9-b16321475c86.png)
- Doc types 
   - Created simple root without properties
![image](https://user-images.githubusercontent.com/1561480/131331619-85b45871-9426-45ab-be0e-f9ffcc63cf5a.png)
- Translations
   -Added single item
![image](https://user-images.githubusercontent.com/1561480/131331681-681269e9-9b9f-40e9-a2e6-876bff776e63.png)
- Template 
   - Prints the value of the translation
![image](https://user-images.githubusercontent.com/1561480/131331751-0b5fff1c-f0a2-4844-96c3-c5a434a2e6e6.png)
- Content 
  - Created simple root item, just to get a URL  
![image](https://user-images.githubusercontent.com/1561480/131331811-fdfca0b9-bf0a-45b9-96bd-6658614111f0.png)

- Website:
![image](https://user-images.githubusercontent.com/1561480/131331844-9bf914fa-2bce-4ea2-b2eb-41fd0112266d.png)

**Comment by Zeegaan** [comment] 2021-08-31 10:52
I've tried and i cannot replicate the bug either.

Can you try setting it up in a minimal setup and give me some specific steps to follow to reproduce? 🕵️

**Comment by nul800sebastiaan** [comment] 2021-08-31 14:57
I'll close this one for now but if we get more repro steps then we can have another look, let us know @shearer3000!

**Comment by shearer3000** [comment] 2021-09-02 20:23
hi everyone - thanks for confirming it must be something specific to my install. One point of difference is that i started with a database copy from an umbraco 8 site (to carry over existing content). The "install/migration" screen completed without reporting an error and the backoffice is all working happily otherwise, but i wonder if the dictionary issue relates to this somehow?

**Comment by nul800sebastiaan** [comment] 2021-09-03 06:15
Could very well be possible, but hard to tell. I don't know if there's been any changes with regard to dictionary items that could cause this. I'm afraid the only way to know for sure what's going on at this point is to attach a debugger to your site and see what's happening.

**Comment by nul800sebastiaan** [comment] 2021-09-03 06:27
A quick test of upgrading a v8 site with 2 dictionary items nested under each other also works for me, but items give me the translation they contain.

**Comment by bergmania** [comment] 2021-09-03 06:39
To my knowledge, there is not changes to this part of Umbraco between v8 and v9

**Comment by shearer3000** [comment] 2021-09-09 02:00
hi all - I tried reproducing this issue on a clean install of Umbraco 9 RC2 and have more info to share. 

If the default language is English (United States) or English (United Kingdom) then "Umbraco.GetDictionaryValue" will show my value just fine as expected. However, my default language is English (New Zealand) and this doesn't show the dictionary value no matter what i try.

Is this enough replication steps to go on? I didn't try other languages but it definitely seems the issue relates to the default language being unsupported (NZ in my case).

thanks
Andrew

**Comment by Zeegaan** [comment] 2021-09-09 07:27
Hi, @shearer3000, and thanks for following up! 🐛  

Sadly I still can't replicate the issue, even when my default language is New Zealand!

Could you try and make a GIF of you trying this out on a clean install? 🕵️ (ScreenToGif is usually the tool I use for that)

# Here are the steps I followed to replicate

- Install the Umbraco rc002 template with `dotnet new -i Umbraco.Templates::9.0.0-*`
- Make a clean project with `dotnet new umbraco -n MyTranslationTest`
- Run the Umbraco Installer
- Go to languages and set my default language to English(New Zealand) 
![image](https://user-images.githubusercontent.com/70372949/132641117-8dc04cb5-4454-462e-be73-3af940ec089b.png)
- Make an empty Document Type and allow it as root 
![image](https://user-images.githubusercontent.com/70372949/132641247-197bd847-ac5e-4054-8d2f-5373bd59de77.png)
-Edit the template to use a translation "My Key"
![image](https://user-images.githubusercontent.com/70372949/132641609-5a22eb08-d26c-4444-aac2-7366baf07719.png)
- Add the "My Key" in the Translation Dictionary
![image](https://user-images.githubusercontent.com/70372949/132641490-7d0b0987-c8d0-4e55-822e-de69153a39d8.png)
- The result is:
![image](https://user-images.githubusercontent.com/70372949/132641685-427d32da-b1d7-438a-8402-6f9380fd6a24.png)


Please tell me if I did anything wrong here, and thanks again for following up! 🐛

**Comment by shearer3000** [comment] 2021-09-10 03:48
Hi Zeegaan – I have updated to using a fresh install of RC3 and came up with some more detailed replication steps 👀🕵️‍♂️

**Replication steps**

- Install RC3 template using: dotnet new -i Umbraco.Templates::9.0.0-rc003
- Create new “Umbraco Project” in Visual studio 2019
- Run site and the umbraco installer
- Make an empty Document Type / template, and allow it as root (called Home)
- Make no changes to default Language, and add a translation “My Key”
![translation-us](https://user-images.githubusercontent.com/2433680/132796502-37dd7c5e-ba9b-4d2a-9227-6fb1aae7af13.png)
- Edit the template to use a translation "My Key"
![template](https://user-images.githubusercontent.com/2433680/132796519-17ea1ade-0198-4e33-8840-8ba38ba14820.png)
- Shows as expected on website
![website-us](https://user-images.githubusercontent.com/2433680/132796533-44c6a69c-4213-41da-bb00-480407245c55.png)
- change default Language to English (New Zealand), and change translation “My Key” value:
![translation-nz](https://user-images.githubusercontent.com/2433680/132796545-bf0ad6e4-0eb4-44f0-924c-50465412d68f.png)
- Doesn’t show as expected on website
![website-nz](https://user-images.githubusercontent.com/2433680/132796561-6431218c-5d2e-43fa-b0d5-ca5bc2b27193.png)

thanks
Andrew

**Comment by shearer3000** [comment] 2021-09-12 21:41
hi - can this ticket be reopened please (given the detailed replication steps above)? thanks

**Comment by bergmania** [comment] 2021-09-13 05:37
Hi @shearer3000 ..

Thanks for the new repro steps, we will try it out again :)

**Comment by Zeegaan** [comment] 2021-09-13 06:44
Hello there @shearer3000, thank you alot for the detailed replication steps, it was easy to follow 💪 🕵️ 

Unfortunately I still cannot replicate the bug 😕 

Below I've attached a GIF of me trying out the steps on a fresh install of the rc-003 template with  a localdb SqlServer installed
it is worth noting that I also tried this with SqlCE just to see if it would make a difference.

![Translation](https://user-images.githubusercontent.com/70372949/133035951-4539eef5-3886-434c-9166-638536dcff2a.gif)

Please tell me if I did something wrong here, and thanks again for following up! 🐛

**Comment by nul800sebastiaan** [comment] 2021-09-13 06:54
Could it be that because @shearer3000's locale on his computer is English (New Zealand) that there's a subtle problem there? What if you try the same with Danish and English (US) @Zeegaan ?

**Comment by Zeegaan** [comment] 2021-09-13 07:03
Great idea @nul800sebastiaan i didn't think of that!

Sadly that does not replicate the issue either 😕 

![image](https://user-images.githubusercontent.com/70372949/133038365-492a7dfe-2587-4af9-93be-8b2450967410.png)

![image](https://user-images.githubusercontent.com/70372949/133038386-0e774f15-75d9-41b9-8439-ef296aa734db.png)


![image](https://user-images.githubusercontent.com/70372949/133038402-e1dad158-3498-42ea-97a1-8c64a3fcf1dd.png)

**Comment by nul800sebastiaan** [comment] 2021-09-13 08:23
And I'm assuming your computer has the Danish locale, right? 😅 I have a weird mix of English and Danish, so I am not even sure what my default would be.

**Comment by Zeegaan** [comment] 2021-09-13 08:28
![image](https://user-images.githubusercontent.com/70372949/133050267-ac65d708-40c0-4faa-9a9d-eac381edb690.png)

Yea i have both Danish and English(US) on my computer 👍

**Comment by nul800sebastiaan** [comment] 2021-09-13 08:30
Maybe we can get a copy of your test site @shearer3000 to make sure we're not missing something silly?

**Comment by shearer3000** [comment] 2021-09-14 03:30
hi - pls find zip of VS solution and database attached. Compile and run in Visual Studio first, and the backoffice creds are admin@example.com | password1234
[10977-UmbracoRC3.zip](https://github.com/umbraco/Umbraco-CMS/files/7158713/10977-UmbracoRC3.zip)
thanks :)

**Comment by nul800sebastiaan** [comment] 2021-09-14 07:42
Super weird! 

![image](https://user-images.githubusercontent.com/304656/133215659-6174b8e3-e9cf-4218-91e5-a1d8ed29b717.png)

Aha, but here's the thing @Zeegaan - if I set the home node to be Danish (Denmark), it should show "hej":

![image](https://user-images.githubusercontent.com/304656/133215963-54de7619-809f-474f-a929-d29f63cecc77.png)

I added the Danish (Denmark) language to @shearer3000's test site and translated to Danish. When I switch the Home node to English (New Zealand), I get `"kia ora" just fine, nothing on Danish.

My native Dutch (Netherlands) works. So it's definitely something to do with the locale that the machine is running on!

**Comment by nul800sebastiaan** [comment] 2021-09-15 12:33
Right, so after fiddling with my languages on my machine, now suddenly I can't reproduce. But I suspect that we're inappropriately falling back to the default language somehow, when I attached a debugger (before I "fixed" my machine) I saw this:

![image](https://user-images.githubusercontent.com/304656/133433466-9e810420-5a89-4788-959f-6689f08b1793.png)

You'll note `en-US` there, which is incorrect, I do not have that as a language on the node, nor is it any of the installed languages in this site.

I suspect that this will fix it for you @shearer3000, can you confirm: 

![image](https://user-images.githubusercontent.com/304656/133433553-1b251757-6511-4147-a21e-8d20e35f9adb.png)

So adding `"DefaultUILanguage": "en-NZ"` in your `appsettings.json`. If you can confirm that this fixes it then we can look at why this is not being overruled with the culture that is set on the node. 

I suspect this is the area where it goes wrong:

https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs#L1065 

It's a bit annoying that I managed to "fix" my machine now, I was so close to the answer! 😬

**Comment by nul800sebastiaan** [comment] 2021-09-15 12:36
Oh and one more question, what language code do you see when you put `@System.Globalization.CultureInfo.CurrentUICulture.Name` in your template?

**Comment by shearer3000** [comment] 2021-09-16 01:22
hi @nul800sebastiaan - cool😀  ive added "DefaultUILanguage": "en-NZ"  to the config and @System.Globalization.CultureInfo.CurrentUICulture.Name to the template yeah it's changed the output to

nz
![revise-nz](https://user-images.githubusercontent.com/2433680/133534143-21c3aa2f-6a74-49f3-9ce4-86b5b5f6598d.png)

usa
![revise-us](https://user-images.githubusercontent.com/2433680/133534135-21916691-6ed1-4c6c-85eb-ea10cd4c3bd8.png)

**Comment by nul800sebastiaan** [comment] 2021-09-16 07:22
After some more fiddling yesterday I finally found the magic combination to make it fail on my machine:

![image](https://user-images.githubusercontent.com/304656/133567801-a2e19deb-81a8-411d-a75d-df463850aadf.png)

The last bit that I changed was the regional format, from `English (Denmark)` to `Danish (Denmark)`.

Now when I switch to Danish as a culture on the node, I get no translation. When I put `@System.Globalization.CultureInfo.CurrentUICulture` in the template, it results in `en-US` - which must be coming from `DefaultUILanguage` since I have not added an `en-US` language in Umbraco so it should not even be available.

**Comment by shearer3000** [comment] 2021-09-16 20:34
great there a confirmed replication steps now 😁

**Comment by Zeegaan** [comment] 2021-09-20 08:44
Hello @shearer3000, with some help from @nul800sebastiaan i was finally able to replicate the issue and find out what causes it 🕵️ 

It seems that we were only checking on the region culture, and never the UI culture, 
I've made a PR that fixes this issue: https://github.com/umbraco/Umbraco-CMS/pull/11136
Hopefully if it doesn't break everything it will be included in the next RC 💪 

Thanks again for the report, and for following up with us! 🐛

**Closed** 2021-09-20 09:42 UTC
Labels: project/v9, state/sprint-candidate, type/bug, release/9.0.0-rc004

**Comment by shearer3000** [comment] 2021-09-20 20:08
thanks everyone 😁
