### ISSUE TITLE
Umbraco tree currentState in custom tree dont work

### ISSUE THREAD

**Issue by rammi987** [umbraco/Umbraco-CMS#14684] opened 2023-08-16 08:52 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.0

### Bug summary

When inside the content section and view click on a node inside the tree you are able to see witch node in the tree you´re a currently on. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/5937899/7c9feb0a-8095-41c7-9847-0fe0ac8ea679)

But when you create you own section with a custom tree, this currectState dont work.
Nothing is getting the highlighted. Therefor you can lose track of where you stand in the tree.

### Steps to reproduce

1) Create a new custom section
2) Create a new custom tree
3) add some node to the root and add some children to the roots nodes.
4) navigate to one of the crated nodes.

### Expected result / actual result

Then on step 4 I expected the node was highlighted, to show that you stand and edit this node.
But nothing gets highlighted.  

After a little debug i could see inside the umbTreeItem directive when the method getNodeCssClass was reevaluated that the parameter node, was the expected node you currently are on but  `appState.getMenuState("currentNode")` return the wrong node, in my case the last visit node witch was under "Settings>Member types>Member"

**Comment by elit0451** [comment] 2023-08-17 06:02
Hi @rammi987 👋 

Can you set up a simple test scenario and post the custom code here? It will shorten the reproduction time :)

**Comment by kjac** [comment] 2023-09-05 13:58
Looks like this issue has gone somewhat quiet. We're going to close it for now. If the issue still persists, please reopen with additional steps to reproduce.

**Closed by kjac** 2023-09-05 13:58 UTC
Labels: state/needs-more-info, type/bug
