### ISSUE TITLE
Publishing errors on multilingual sites when using "Save & Publish" 

### ISSUE THREAD

**Issue by degofedal** [umbraco/Umbraco-CMS#17418] opened 2024-11-04 12:30 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

When clicking "Save & Publish" on sites with multi lingual content the message "Document was not published, but we saved it for you" appears even though all content has been filled correctly. Clicking "Save" (grey button) and three dots context menu and then "Publish" publishes the page without issue. 
Others have the same issue: https://our.umbraco.com/forum/using-umbraco-and-getting-started/114906-document-was-not-published-but-we-saved-it-for-you-when-using-an-optional-language

### Specifics

<img width="1865" alt="SCR-20241104-iwyg-redacted" src="https://github.com/user-attachments/assets/8894f8b5-5bd1-43cf-9b92-d3ce778a04ff">

https://github.com/user-attachments/assets/f6b5d04c-8e88-46c7-b287-476ba47dec5d

### Steps to reproduce

Edit content and use "Save & Publish" button on content node with multi lingual content. 
**Work-around:** Clicking "Save" (grey button) and three dots context menu and then "Publish" publishes the page without issue.

### Expected result / actual result

I expect the "Save & Publish" button to save and publish the content. the content is saved but is not published.

**Comment by NguyenThuyLan** [comment] 2024-11-21 04:28
Hi @degofedal , did you try it on a fresh install of Umbraco?
I could not reproduce it on 14.3.1 as in the video below so I will close this issue.
Feel free to reopen if you have further information 😊

https://github.com/user-attachments/assets/3cae3973-94a0-4962-b4f2-2d3828354d97

**Closed by NguyenThuyLan** 2024-11-21 04:28 UTC
Labels: type/bug
