### ISSUE TITLE
Umbraco 12, Content templates possibly populated with previously entered content node

### ISSUE THREAD

**Issue by FreshEggLtd** [umbraco/Umbraco-CMS#14870] opened 2023-09-27 14:10 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

We've had some content created using the "Content Templates", however I am seeing unexpected results, potentially loading data from the previously entered content node based upon the content template.

This potentially relates to Block Lists and/or Block Grids containing data in the Content Templates.

I can share some videos where I try and talk through the issue.

This relates to this Umbraco support ticket > https://support.umbraco.com/hc/en-us/requests/85323

### Specifics

I have managed to replicate a similar issue in a Vanilla un-customised Umbraco 12.2.0 cloud project.

https://www.s1.umbraco.io/project/hatch-vanilla

I am able to talk through the problem on a call if needed and give access to the project if required.

I have seen this in a client site also, however, re-publishing sadly does not seem to clear the problem in our client site.

I can potentially get around the problem, by copying the problematic folders into new content folders. However, the customer site has quite a lot of content, so it would be a large job.

### Steps to reproduce

I can share 2 videos replicating the issue in a vanilla Umbraco cloud site.

I am happy to talk through the related problems I am seeing in our customers site, however, this one is slightly different and might be better explained on a call.

https://github.com/umbraco/Umbraco-CMS/assets/6716484/7dab71e4-66db-4846-88e9-ba26b74a78c9

https://github.com/umbraco/Umbraco-CMS/assets/6716484/584fdeae-c3a3-4a17-b1bc-cb7c74fa0d68

### Expected result / actual result

Content entered in each content page based on Content templates should appear in delivery APIs.

---
_This item has been added to our backlog [AB#33455](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33455)_

**Comment by FreshEggLtd** [comment] 2023-09-27 14:39
Thinking about this further. I mention above that re-publishing doesn't appear to fix it for our clients, I think that might be wrong. It probably does, however, our custom code for our website build is slightly different as we run Umbraco headless.

We have a method that finds our "home page" by Id. 
we are the using the UmbracoContextAccessor and the Content.GetById() for this.

We then move through all the Children() and then all the child Children() records and so on.
When processing these Children() records, we find the incorrect 'old' content.
If I load the individual page by Content.GetById() directly, it's fine and does seem to serve the new published content.

**Comment by kjac** [comment] 2023-09-29 12:18
Hi @FreshEggLtd,

Thanks for reaching out 👏 

It seems really weird. Feels a lot like a caching issue, but that calls for an explanation as for why we do not encounter this when building content "from scratch". However... I can't help but notice that the item IDs for the `htmlEditor` block entries seem duplicated between the pages in the Delivery API output in first video. Can you confirm that?

Also, if this is indeed the case: Does re-publishing the impacted pages produce new IDs, or are they still reused?

**Comment by kjac** [comment] 2023-09-29 12:34
Quick update here. I created a content template with a block list containing nested block elements - like so:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/144fd049-05ef-41d8-8d13-0ad828a571e9)

When creating multiple pages using this template, the keys are indeed reused for the block list items - both the ones at root level (_Root Blocks_) and the nested ones (_Nested Blocks_).

However, I can still edit the individual pages and produce unique Delivery API output between them. For example. adding "edited" to all _Title_ fields in all blocks (root and nested) on one page does not affect the output of the other pages. The keys are not re-generated either, so fortunately the caching works as it should (per property per page).

**Comment by FreshEggLtd** [comment] 2023-10-02 10:05
Hi @kjac, I think they do keep the same Ids.

The example I demo'd the videos on is a completely fresh Cloud install without any code customisations.

I could happily invite you to the project and give you access so you can experience the issue?

Thanks
Andrew

**Comment by kjac** [comment] 2023-10-02 10:53
@FreshEggLtd that would be good - 'cause I'm having a hard time reproducing it locally. There must be some trick to it 😄

**Comment by kjac** [comment] 2023-10-05 06:49
Hi @FreshEggLtd - you can try inviting kja@umbraco.dk ... that ought to work 😄

**Comment by FreshEggLtd** [comment] 2023-10-05 10:47
Hi @kjac - perfect, I've sent you an invite. I'm also happy to jump on a screen share next week so we can chat it through and demo it together if you are having trouble seeing what I am seeing.

**Comment by NikiSkaarup** [comment] 2023-10-23 07:47
looks like when creating content based on content template, it is reusing the Ids from the content template, resulting in duplicate ids when you use said content template more than once

**Comment by jesperordrup** [comment] 2023-10-23 08:04
@FreshEggLtd @kjac

Reproduceable in v11 and v12 and also v8. I've created an issue on this earlier - cant seem to the issue though.

@nikiskaarup wrote

> looks like when creating content based on content template, it is reusing the Ids from the content template, resulting in duplicate ids when you use said content template more than once


workaround - copying a page rolls new id's and fixes the problem. 

This is a major problem that prevents the use of content templates.

**Comment by kjac** [comment] 2023-10-23 08:07
Hi all,

We _just_ had a talk about this one, and we definitively need to do something about it. The plan right now is to fix the problem (don't generate new duplicate keys) and then offer up some code that can migrate problematic content (existing duplicate keys).

At this time I have no estimate on either of the above 📆

**Comment by jesperordrup** [comment] 2023-10-23 08:11
Thanks @kjac - thinking about workarounds. 

You know where ID's are generated - frontend on insert in block grid or later server-side? Trying to determine if we should traverse JSON and clear or generate new ID's before saving or in umbraco server-side on before save event

**Comment by jesperordrup** [comment] 2023-10-23 09:26
I suggest that fixing the bug is most important and should be solved first. Maybe even a hotfix. 

Later a migration

**Comment by FreshEggLtd** [comment] 2023-10-30 16:05
Hi @kjac 

Thanks for the updates and I'm glad you have managed to replicate what I have experienced.

Cheers

**Comment by kjac** [comment] 2023-11-02 07:16
Cross linking similar issue reports:
- https://github.com/umbraco/Umbraco-CMS/issues/13698
- https://github.com/umbraco/Umbraco-CMS/issues/13698

**Comment by jesperordrup** [comment] 2023-11-02 08:12
I investigated this a bit and found that clipboard service has some interesting solutions on this. 

The clipboard story is somewhat is close to this:

1 copy content
2 paste content
3 replace contentUdi and settingsUdi

When/if I had the time (and the extra time to compensate for my lack of angular knowledge in Umbraco I would probably try solving this by adding a module that detects this is a page created with a content template (page has no id but content) and run a replaceUdi (grabbed from clipboard service.

**Comment by nielslyngsoe** [comment] 2023-11-20 18:05
I just want to add that it’s a general problem for all Property Editors that houses unique IDs when using Content Templates.
On top of my mind: Block List, Block Grid, RTE(Blocks) and Media Picker(not sure if there is any caching issue related to this one, but relatively sure the ID is not re-generated when made via Content Templates)

**Comment by andyfrost97** [comment] 2023-11-30 11:42
Hi, 

Just adding a comment as advised by Support that we are also experiencing issues with pages returning incorrect content. More specifically it is effecting copied nodes that contain custom Block List properties. It brings back content from the copied Umbraco node to how it was prior to updating the content for the new page.

Thanks 😁

**Comment by Zeegaan** [comment] 2024-01-10 11:23
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15541

**Closed by Zeegaan** 2024-01-10 11:23 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, affected/v12

**Comment by Pieter-vdh** [comment] 2024-02-09 10:01
Hi

I'm having the same issue in Umbraco 11, but I see that it was only fixed in 10, 12 and 13. Is there also a fix planned for 11 or do I need to upgrade to 12?

**Comment by Zeegaan** [comment] 2024-05-16 11:52
Heyo 👋 

As @kjac mentioned here: https://github.com/umbraco/Umbraco-CMS/issues/14870#issuecomment-1774645075
The plan was to immediately fix the bleeding by fixing the origin of the issue, and then provide some kind of code to fix already created stuff, but the last part hasn't been done yet 🤔 


I will have a talk with the team and come back to you on this 😁

**Comment by RuddyOne** [comment] 2024-05-16 11:57
@Zeegaan Ah I see, thanks for clearing that up. 

What versions was the fix for the bleeding released in? And also do you know of any workaround or "quick fix" to resolve this for existing data? We have noticed this problem in production and I have been working for 2 days to try and resolve it. Going as far to delete the content and recreate it via code (still working on this). 

Any insight you have would be super useful for us. 

Thanks again.

**Comment by Zeegaan** [comment] 2024-05-17 07:41
Fix is in 10.8.4, 13.1.0 & 12.3.7 😁 

Sadly no fix or workaround yet, that is what hasn't been done yet 😢

**Comment by RuddyOne** [comment] 2024-05-17 09:05
Thanks for the info. 

I am still looking into it and found a useful blog [here](https://cornehoskam.com/posts/umbraco-migration-tips-duplicate-nested-content-guids).

Updating this a little bit to suite our needs we can now generate new Guids for our block lists properties. We are still working it on but its looking promising.

One thing I cannot seem to understand is "umb://element/62422f32f825442ca02cca88876ad07b", what do these mean? As we are generating new random Guids for them, what is the reason they exist in the first place? Is replacing them (which seems to fix the issue) going to cause other issues?

**Comment by Zeegaan** [comment] 2024-05-21 07:25
I've talked with the team, and this task is on our board. It's very related to a bigger task, so we're planning to look in to it, but there is no timeline yet for when that happens 😁

**Comment by RuddyOne** [comment] 2024-09-02 10:36
@Zeegaan We have just had reports from our Prod website that is is happening again. 

We are on Umbraco, after some investigation it looks like the same IDs are being used after a copy of a parent node (the children have the same IDs).

**Comment by RuddyOne** [comment] 2024-09-03 08:25
The issue we are now seeing is when you copy parent content with children, before we were looking at copied single content. We have noticed that it happens about 90% of the time but not 100%. Any ideas?

**Comment by Migaroez** [comment] 2024-10-10 16:57
Hey @RuddyOne, I will be having a look at this in the coming days.

If you have any additional notes around setting up an installation to reproduce this, I am all ears.
From my first inspection of the code that does the copy with descendants it should be launching the `ContentCopyingNotification` just like on a normal copy.

**Comment by Migaroez** [comment] 2024-10-11 11:43
So I have been trying to replicate this to no avail, the notifications are being launched and consumed correctly on my end.

Since this seems to be a related but different issue I would also like to ask you to create a new issue with detailed reproduction steps.
