### ISSUE TITLE
Clicking on the save button in multi lingual site shows a save message for all languages

### ISSUE THREAD

**Issue by sandervandepas** [umbraco/Umbraco-CMS#12033] opened 2022-02-22 09:31 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

We have setup a multilingual site (Dutch and English) on Umbraco 9.2.0.
When on the Dutch Language, we Save the Website node (first node below Content) a popup appears with the text "Ready to Save?" and only the Dutch culture will be shown.

After clicking the Save button we got 2 warnings/messages that both cultures has been saved.

When we do this on the Homepage (node below the Website node) for example we only see the Dutch warning/message.

### Specifics

Discussed this with Umbraco Support (Alina-Magdalena Tincas + Muslim Al-Ali) in ticket https://support.umbraco.com/hc/en-us/requests/67453 and this is their latest reaction:

`Hey Sander - so the developers came back - and this is definitely a bug.

The reason for this is that whenever you add a language, you shouldn't have to rebuild the indexes and reload the db and memory cache`

### Steps to reproduce

1. Create 2 languages (Dutch (default) and English)
2. Create a website doctype and node that can exist as root node
3. Create a home doctype and node that can exist below the Website node
4. Save the Website node in Dutch and see that the popup shows only the Dutch culture and after clicking on the Save button in the popup see that you get 2 green messages that the content is saved in Dutch and English

For specific reproduction details please contact Alina-Magdalena Tincas or Muslim Al-Ali.

### Expected result / actual result

I expect that only the current language will be shown as culture in the message after the Website node is changed, so the same one as in the popup and not both cultures as it shows now.

---
_This item has been added to our backlog [AB#25457](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25457)_

**Comment by nul800sebastiaan** [comment] 2022-03-02 10:23
Might have something to do with the fact that the other language (EN for me) hadn't been created before and then somehow the first language (NL) doesn't show up in the save dialog, but it's just hiding and is really there, and checked on by default, so both will be saved. 
It only happens for me when one of the languages does not yet exist, if both exist it saving seems to work as expected.

I can reproduce, also on 8.14 so this has been around for a while. 

https://user-images.githubusercontent.com/304656/156343483-94b779de-f40e-4212-afa6-5c3b0e17a389.mp4

**Comment by LeeDalchow** [comment] 2022-05-14 18:10
I'll pick this one up! Seems like a good first contribution! Might take me a little longer to find my way around the codebase!

**Comment by LeeDalchow** [comment] 2022-05-14 22:11
This seems to be caused by something in the front-end setting Save=True for both variants within the contentItem object. The backend seems to use this flag to know if there are any modifications to the content, saves to the DB and sends the notifications back to be displayed. See screenshot below of the payload to the endpoint with the Save variables highlighted.

![image](https://user-images.githubusercontent.com/105460972/168449472-b2bbee55-951a-4e36-b356-c80c1044dbb7.png)

Tried to debug this on the front-end but unfortunately, my knowledge of Angular is not strong enough and I wasn't able to find where this object is being created. (I'm more of a backend guy). So this may need someone else to continue.

Will subscribe as I'd love to see how this one is solved!

**Comment by kjac** [comment] 2023-01-09 13:09
I can reproduce this in V10+ ... PR to fix in https://github.com/umbraco/Umbraco-CMS/pull/13649

**Comment by kjac** [comment] 2023-01-12 09:53
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13649

**Closed by kjac** 2023-01-12 09:53 UTC
Labels: state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v9, affected/v10, affected/v11, affected/v12
