### ISSUE TITLE
Media section SAVE button does nothing

### ISSUE THREAD

**Issue by pais-ribeiro** [umbraco/Umbraco-CMS#9603] opened 2021-01-02 17:35 UTC
When clicking SAVE button in media section no action takes place. Can not create folder, upload documento or image, or change crop of images using media section. The SAVE button simply do not work.
Can delete though.

I figured how to turn it arround... if when creating folder or uploading image or whatever, if you put the cursor in title and hit Enter it saves. Button SAVE don not work but Enter does.

I tested with a fresh installation.

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.0

Reproduction
------------
Just go to media section an create a folder... click save and check if anything happens.

**Comment by nathanwoulfe** [comment] 2021-01-03 08:34
Hi @pais-ribeiro thanks for raising this - it's a duplicate of #9600 so I'll close this one and keep the original open as it has some existing discussions.

**Closed by nathanwoulfe** 2021-01-03 08:34 UTC
