### ISSUE TITLE
Date Picker Formatting Error

### ISSUE THREAD

**Issue by briandeeker** [umbraco/Umbraco-CMS#13850] opened 2023-02-17 14:26 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

When using the Date Picker (Umbraco.DateTime), the date format does not accept any formats as mentioned in momentjs.com. Nothing entered in the Configuration field called Date format is accepted and the default of DD/MM/YYY 12:00:00 AM always shows.

See attached screenshots.
![date-picker](https://user-images.githubusercontent.com/94625617/219681330-f87cd658-502c-474c-b927-b323327d78bc.jpg)
![date-time](https://user-images.githubusercontent.com/94625617/219681334-df857596-4892-448c-acd6-d794a97f3cc7.jpg)

### Steps to reproduce

Dennis from the support team was able to reproduce the error.

**Comment by Zeegaan** [comment] 2023-02-20 07:39
@briandeeker I don't know if I misunderstood this, but as far as I understand it, the issue here is that when you set the `YYYY` configuration, the datepicker should actually become a year picker instead, here is me with the `YYYY` configuration: 
![image](https://user-images.githubusercontent.com/70372949/220042574-d756c916-9f19-44de-b9e0-c299b5ff02b8.png)
If that is the case then I can definitely reproduce this 😁

**Comment by briandeeker** [comment] 2023-02-20 14:17
Sorry, that is not what I am saying. I am saying that the date format doesn't work at all. Whatever is put in there does not show on the front end.

**Comment by nathanwoulfe** [comment] 2023-02-20 23:08
AFAIK the format provided for the property editor is for the backoffice only and has no impact on the front end. When rendering on the front end, the property value is a DateTime, and formatting is an implementation detail.

Pretty sure too that the picker itself doesn't change based on the format string, but will include the time picker if the format string contains a time (ie contains "H", "m" or "s")

**Comment by Zeegaan** [comment] 2023-02-21 06:54
As @nathanwoulfe has pointed out here, the format of the property editor has no impact on the frontend-value of the property editor, you will always get out a complete datetime, and it is then your responsibility to format that however, you'd like 👍 
In your case, if using the Razor models you can do `.ToString("YYYY")` to format it by only year 👍 I'll go ahead and close this 😁

**Closed by Zeegaan** 2023-02-21 06:54 UTC
Labels: type/bug

**Comment by Aaen** [comment] 2023-02-21 16:22
@Zeegaan I have been involved in this case in support. I have tried to do @Model.Value("date").ToString("YYYY") and when I do this the site returns an HTTP ERROR 500

**Comment by Zeegaan** [comment] 2023-02-22 07:55
@Aaen This works if you instead do @Model.Date.ToString("yyyy") (note: found out it has to  be lowercase yyyy)
This is because using `Model.Value` is not typesafe, and therefore returns an object, which has no `.ToString()` overload that takes a format string 😁 Hope that explains why 🙏
