### ISSUE TITLE
Bug defining editors allowances inside grid layout [inside grid data type]

### ISSUE THREAD

**Issue by catiarodriguescosta** [umbraco/Umbraco-CMS#9931] opened 2021-03-03 14:03 UTC
## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

### Bug summary

When you have editing your grid data type, you can more than one grid layout and more than one row.
A big potential here is that inside each grid layout you can define the number of columns and define which rows can appear as options in each column of that grid layout.

Let's assume I have a grid layout named "Grid with right sidebar" composed by 1 column of 8 and 1 column of 4.
I have 3 rows: 1 column row, 2 columns row and sidebar row.
The idea is having the smaller column (the sidebar column - 4) with only one option of row (sidebar) and the body column (the one with 8) with only 2 options of row (all except the sidebar row).
So resuming, in theory, clicking over the 8 column you can restrict it to the first two rows. and if you click back you can restrict it to the last row only. But that doesn't happen... When you save both columns has the same row restrictions.
However, if you decide to allow all the rows for the first column and restrict rows for the second column, that works.
This way, you can choose sidebar, 1 column row and 2 columns row for the body column and just sidebar for the sidebar column.
#### Conclusion:
I believe this is a bug because you allow to have different conditions for each column. **What doesn't work is having different restrictions for each column.**

<img width="1428" alt="Screenshot 2021-03-03 at 13 52 09" src="https://user-images.githubusercontent.com/34938764/109815647-c6742000-7c27-11eb-9c24-044496cb763b.png">

<img width="1427" alt="Screenshot 2021-03-03 at 13 52 23" src="https://user-images.githubusercontent.com/34938764/109815841-ffac9000-7c27-11eb-801e-accd3deb56f5.png">

### Actual result

<img width="995" alt="Screenshot 2021-03-03 at 13 46 39" src="https://user-images.githubusercontent.com/34938764/109814978-0686d300-7c27-11eb-87f9-26de6e65bda0.png">

### Expected result

<img width="995" alt="Screenshot 2021-03-03 at 13 46 39 copy" src="https://user-images.githubusercontent.com/34938764/109815188-464dba80-7c27-11eb-9b51-bd57a8f5a13a.png">

### Steps to reproduce

1. Create a new grid Data type
2. Create a grid layout with 2 columns
3. Create 2 different rows
4. Edit the grid layout you created before. Try to restrict one row into one column and the other into the other column. 
5. Save and check if your restrictions are saved as you expected.
6. You will see that something happened and the last allowed row is the one chosen in both columns (you expect to have a different option for each column).
7. Change one of the column to allow all editors. And save. You'll realize that one column will allow both rows and the other only one, as expected.

**Comment by bjarnef** [comment] 2021-03-03 14:26
I think this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9825 which have a PR in https://github.com/umbraco/Umbraco-CMS/pull/9887

//cc @nul800sebastiaan

**Comment by catiarodriguescosta** [comment] 2021-03-03 14:41
You are right @bjarnef, it's the same issue.
Do you have an idea when this fix will be merged/released?
Thanks!

**Comment by nul800sebastiaan** [comment] 2021-03-03 15:23
Yep, thanks! I believe it's in our current sprint so hopefully soon, subscribe to  the other issue for updates! I'll close this one as a duplicate, thanks for reporting! 👍 👍

**Closed by nul800sebastiaan** 2021-03-03 15:23 UTC
