### ISSUE TITLE
An error occurred when Add Language

### ISSUE THREAD

**Issue by SergheiBelyi** [umbraco/Umbraco-CMS#11789] opened 2021-12-23 13:38 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

Try do add new language and accept an error message.

### Specifics

```
An error occurred
Culture is not supported. (Parameter 'name') aa is an invalid culture identifier.

Exception Details
System.Globalization.CultureNotFoundException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Culture is not supported. (Parameter 'name') aa is an invalid culture identifier.
Stacktrace
at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at System.Globalization.CultureData.IcuEnumCultures(CultureTypes types)
   at System.Globalization.CultureData.GetCultures(CultureTypes types)
   at System.Globalization.CultureInfo.GetCultures(CultureTypes types)
   at Umbraco.Cms.Web.BackOffice.Controllers.LanguageController.GetAllCultures()
   at lambda_method874(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```
![Screenshot_1](https://user-images.githubusercontent.com/13329073/147248300-a1a817a6-4b70-41f1-b9b5-1c17bfb8ee3a.png)

### Steps to reproduce

New Umbraco instance jus installed and configured by default.
Trying to add new language.

**Comment by nul800sebastiaan** [comment] 2022-01-03 13:58
Hi there @SergheiBelyi - it seems like you're trying to add the `Afar` language (language code `aa`) and dotnet is telling you it is not supported on your system. I am not sure how that could happen. I seem to recall that we only list the languages supported on your machine when adding a language (in fact, it does work on my machine).

Could you post the system information found in the help panel of Umbraco please? When you click on the `?` at the top right of the backoffice: 

![image](https://user-images.githubusercontent.com/304656/147938964-821b771a-e8b7-479c-9ebc-1f7c470d5b31.png)

As you can see my mouse is hovering on the copy button in that screenshot, click that one and paste it here please.

**Comment by nikro412956** [comment] 2022-01-11 15:23
@nul800sebastiaan 
I get the same error.
This is the stacktrace:

> An error occurred
> Culture is not supported. (Parameter 'name') aa is an invalid culture identifier.
> 
> Exception Details
> System.Globalization.CultureNotFoundException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Culture is not supported. (Parameter 'name') aa is an invalid culture identifier.
> 
> 
> 
> Stacktrace
> at System.Globalization.CultureInfo.GetCultureInfo(String name)
>    at System.Globalization.CultureData.IcuEnumCultures(CultureTypes types)
>    at System.Globalization.CultureData.GetCultures(CultureTypes types)
>    at System.Globalization.CultureInfo.GetCultures(CultureTypes types)
>    at Umbraco.Cms.Web.BackOffice.Controllers.LanguageController.GetAllCultures()
>    at lambda_method2622(Closure , Object , Object[] )
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

This is the system info:
<html>
<body>


Category | Data
-- | --
Server OS | Microsoft Windows 6.3.9600
Server Framework | .NET 5.0.13
Default Language | en-US
Umbraco Version | 9.2.0
Current Culture | en-US
Current UI Culture | en-US
Current Webserver | IIS
Browser | Chrome 96.0.4664.110
Browser OS | Win32


</body>
</html>

Funny thing is that localhost does **not** get the error. On localhost i can add a language. On my test environment is throws the error. This is the system info for my localhost machine:
<html>
<body>


Category | Data
-- | --
Server OS | Microsoft Windows 10.0.19042
Server Framework | .NET 5.0.12
Default Language | en-US
Umbraco Version | 9.2.0
Current Culture | en-US
Current UI Culture | en-US
Current Webserver | Kestrel
Browser | Chrome 96.0.4664.110
Browser OS | Win32


</body>
</html>

**Comment by nul800sebastiaan** [comment] 2022-01-13 16:18
For the record, turns out `Microsoft Windows 6.3.9600` is Windows Servers 2012 R2.

@nikro412956 which language are you trying to add? Do any languages work or do you get this error regardless of the language you're trying to add?

**Comment by nikro412956** [comment] 2022-01-13 18:13
@nul800sebastiaan The error occurs when umbraco tries to load the dropdown with languages to pick from. Which in turns prevents the whole dropdown from being loaded. It also occurs when you try and edit an already selected language. 
![image](https://user-images.githubusercontent.com/22655656/149385934-bcbac602-a65f-4859-a6c4-74b4d03b260a.png)

**Comment by nikro412956** [comment] 2022-01-14 15:21
@nul800sebastiaan I got some clues as to what was wrong with the help of this: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c

Then i build the project targeting the runtime version of my test server. 
`dotnet build -r win81-x64  /p:Configuration=Release /p:Platform="Any CPU"`
This creates a self contained version of the umbraco website in the obj\Release\net5.0\win81-x64\PubTmp\Out\ folder.
When i put this self contained version on the server, it stops throwing the exception
I got the runtime identifier from here: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**My suspicion**
I think the problem is that runtime that is installed expects a certain version of windows and thus tries to retrieve the cultures for that version of windows.
I do hope this helps narrowing down if this is the actual problem or that this helps down finding the problem.

**Comment by SimonHilo** [comment] 2022-01-19 12:47
I have experienced this problem as well on windows server 2012, also with 9.1.2 and 9.2.0. I moved it to a windows server 2019 and it worked with no other modifications.

I didn't manage to make a build that worked as @nikro412956 suggested, so our solution is probably to host it somewhere else for now.

**Comment by nikro412956** [comment] 2022-01-20 14:34
@SimonHilo Your solution is obviously preferred. Especially with end of life dates for older windows server versions but if that is not an option for someone, creating a self contained app would offer an alternative. So i took another look at my previous comment and i figured out that the build command was not entirely correct. I think the self contained app still existed in that folder because i forgot to clean the project.
This is how i created the working self contained app:
I start powershell in the project folder; (I use powershell because i know the command i use works there)
I run the following command:`dotnet build -r win81-x64 /p:DeployOnBuild=true /p:SkipInvalidConfigurations=true /p:Configuration=Release /p:Platform="Any CPU"`
After the build is done you should see something like this just before "Build succeeded": `projectName -> path\to\project\folder\obj\Release\net5.0\win81-x64\PubTmp\Out\`
That is where the self contained app should have been deployed to;
If you copy the entire content of that folder to the root of the website folder on the server then is should work;
The above steps is how i got it working. I hope you can verify this alternative solution for people who can not change the OS version to a newer variant.

**Comment by SimonHilo** [comment] 2022-01-21 10:22
@nikro412956

Thanks for the help and the expanded suggestions. It still doesn't work on our server 2012, I'm afraid.

What I did was as straight forward as I could:

1. Update to newest templates, 9.2.0

`dotnet new -i Umbraco.Templates`

2. New Umbraco solution
`dotnet new umbraco --name UmbracoSprogBug`

3. Build using your command

```
cd UmbracoSprogBug
dotnet build -r win81-x64 /p:DeployOnBuild=true /p:SkipInvalidConfigurations=true /p:Configuration=Release /p:Platform="Any CPU"
```

Then I upload to server and set up on iis and install Umbraco on a new MSSql db. But i still can't add a new language. Everything else seems fine.

I do get a different error message when I try to add the language, this time. I get a generic message: 

Server error: Contact administrator, see log for full details.
Failed to get cultures

I take it that this is because it's a release build, but i'm not exactly sure. At this point it doesn't write anything to log, which i find strange, that wasn't a problem before.

**Comment by nikro412956** [comment] 2022-01-21 12:33
@SimonHilo I am curious why it does not work for you. What files does your deploy have? For some reason it sounds like it is not creating a self contained app but an app that is using the OS installed runtimes.

**Comment by nikro412956** [comment] 2022-01-21 16:02
@SimonHilo I tried what you did and it didn't work so i compared the new project and my working one. I figured out that i also disabled this code in the .csproj file: 

> 
>     

This might have also been the solution. My apologies. This is what happens when you throw solutions at the problem until something sticks.

**Comment by SimonHilo** [comment] 2022-01-25 12:27
@nikro412956 

That did it!
I did a publish first using your previous command, later just using this:

`dotnet publish -r win81-x64 -o c:\outputdirectory`

Both worked. I think the key is that it must be self-contained (using -r win81-x64) and that the ICU package is disabled in the project.

Thanks for all the help, @nikro412956.

Simon

**Comment by nikro412956** [comment] 2022-01-25 18:12
@SimonHilo I did some more testing myself and it looks like it does not have to be self contained after all. Which will make it easier to implement for people.

**Comment by nul800sebastiaan** [comment] 2022-02-21 09:53
It looks like this is now solved and should work better with the updated dotnet new templates we have which also has better ways of setting up the ICU references. https://github.com/umbraco/Umbraco-CMS/pull/11961

I'll close this for now and happy to see the issue has been resolved for you already! 👍

**Closed by nul800sebastiaan** 2022-02-21 09:53 UTC
Labels: state/needs-more-info, type/bug

**Comment by p-m-j** [comment] 2022-02-22 19:59
> It looks like this is now solved and should work better with the updated dotnet new templates we have which also has better ways of setting up the ICU references. #11961

That PR is about using app local ICU more frequently (e.g. also on Linux) but disabling app local ICU seems to be resolving issues here.

Without app local ICU on windows server < 2019 things will get weird for certain cultures, the cannonical example being 
Umbraco.Cms.Tests.UnitTests.Umbraco.Core.CoreThings.TryConvertToTests.ConvertToIntegerTest for sv-SE.

**Comment by p-m-j** [comment] 2022-02-22 20:03
Is it important that you use the `win81-x64` rid? What happens with app local ICU + not version-specific `win-x64` rid?

**Comment by biapar** [comment] 2022-12-10 14:32
Hi, I've the same problem with Umbraco 10 and Windows 2012R2
