### ISSUE TITLE
RTE content in block list is cleared when re-ordering items in the list (visual bug)

### ISSUE THREAD

**Issue by jso-dwarf** [umbraco/Umbraco-CMS#15281] opened 2023-11-22 09:11 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

We have tested this on 11.4.2 and 12.3.3.

When using document types in a Block List that has a Rich Text Editor field, reordering the items in the list while the block item is expanded, will result in the content in the RTE being cleared.
The issue seems to be visual only, as the actual content still seems to be there when closing/opening the item again.

### Steps to reproduce

See video:
https://share.vidyard.com/watch/Ksob5hH2wLHjMv97LZ2rVe

- Add 2 or more items to a Block List, where at least one has an RTE
- Enter some text in the RTE
- While the block is expanded, reorder any of the items in the list

### Expected result / actual result

I expect the content in the RTE continue to be visible after reordering the items.

**Comment by kjac** [comment] 2023-11-27 08:12
Hi @jso-dwarf,

Thanks a lot for reporting 💪 

This is a known issue for the Block List. If you do not use "inline editing mode" it should not happen.

The issue is up for grabs here: https://github.com/umbraco/Umbraco-CMS/issues/14191

I'm closing this as a duplicate. Thanks again for reaching out ❤️

**Closed by kjac** 2023-11-27 08:12 UTC
Labels: type/bug
