### ISSUE TITLE
umbracoLock timeout exceeded frequently for members

### ISSUE THREAD

**Issue by JohnBergman** [umbraco/Umbraco-CMS#11847] opened 2022-01-11 19:50 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

This is the same issue as #8433; in our circumstance we have around 15,000 members.  under heavy traffic we get this a LOT.  During login, we also update a field in the member database that is included in the Examine index.

The condition appears to be when we have several members doing member related reports and listing and lots of members logging in - we get caught in a situation where the write to the members record fails, and hence blocks the login.

The stack trace matches pretty close to what was in the mentioned issue #8433.

### Specifics

Most of the reporting calls use this to retrieve the members, and then filter / work with them after they are returned from this one

                IMemberLocatorService memberLocatorService = new MemberLocatorService(memberDao);
                var members = memberLocatorService.GetAllMembersJson();

### Steps to reproduce

Heavy load, lots of reads and writes to the member data causes lock related issue

### Expected result / actual result

Fewer lock timeouts;

**Comment by nul800sebastiaan** [comment] 2022-01-13 16:14
I don't know what's going on in that `GetAllMembersJson()` method, which might be doing some locking, no idea. Maybe try to do that out of band? I am not sure what it means what this is "to retrieve and filter/work" with members, that doesn't exactly sound like a good idea to be honest. We're providing ways to work with and filter members in the backoffice, using paging to make sure we don't create a big load on the database.


Unfortunately, people seem to still get this problem on rare occasions, but we haven't narrowed it down: https://github.com/umbraco/Umbraco-CMS/issues/9594

We'd more than welcome any and all investigations that can lead to a good idea of what is creating locks. We have (as you've seen in related issues) tried hard to make sure that we don't aggressively hold locks on anything.
Additionally, you can experiment with this setting: https://our.umbraco.com/Documentation/Reference/Config/webconfig/#umbracocoresqlwritelocktimeout - adding the value `<add key="Umbraco.Core.SqlWriteLockTimeOut" value="6000" />` to your web.config and maybe gradually increasing the timeout.

This might help but it might also give you larger and larger performance issues since.. the longer the timeout you set, the longer everybody has to wait if something is stuck.

I'm going to close this issue as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9594 and encourage you to do some reading, follow all the links, see if that gives you some hints.

Finally, please note that members are basically content items, they are complex and write operations are just as heavy as the ones on actual content items. So if things are being updated very often, then that does not scale very well, you'll have to keep throwing more and more beefy hardware at it. I would recommend you investigate if write operations that you need/want to do can be done in custom tables so it doesn't need to do a heavy update operation on the member object. Additionally, getting all members json is probably not going to scale either with the amount of members you have. You might need to rethink how that works and at the very least make sure that you get your data out of the Examine members index for better performance.

**Closed by nul800sebastiaan** 2022-01-13 16:14 UTC
Labels: type/bug

**Comment by JohnBergman** [comment] 2022-01-14 16:02
We are using the implementation in a forward facing administration; were we have a select group of users that perform those activities, but because of the business cannot also be users of the back office.

We will continue to investigate from this side as well and let you know our findings should we discover anything "helpful".
