### ISSUE TITLE
Headless Tour is broken

### ISSUE THREAD

**Issue by klutes** [umbraco/Umbraco-CMS#3322] opened 2018-10-17 17:21 UTC
The backoffice tour of Headless breaks after a few short steps.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by readingdancer** [comment] 2018-10-17 23:10
@klutes It would be good if you could edit your original comment and describe the steps taken to re-produce the issue, your current description is a little vague ;) It's a good idea when creating issues for any product to be as descriptive as possible to help whoever looks at the issue pinpoint it quickly.

Also, it's good to know things like the browser you are using, if you tested it in another browser is it also broken, etc.

I hope this is helpful :)

And congrats for raising your first issue on GitHub 👍

**Comment by nul800sebastiaan** [comment] 2018-11-14 17:18
Thanks Keith! Unfortunately as Chris points out, it's unclear what the problem is here. If you have an update then let us know. I'll close this for now but we'll be happy to re-open this when we know more.

**Closed by nul800sebastiaan** 2018-11-14 17:18 UTC
