### ISSUE TITLE
NetCore: Setup installation error

### ISSUE THREAD

**Issue by janborup** [umbraco/Umbraco-CMS#10239] opened 2021-05-06 15:57 UTC
Doing a clean installation from scratch... on af Danish Windows 10.

When installation setup appears, and finishing the setup credentials this error appears:

`System.Xml.XmlException: The 'language' start tag on line 2 position 2 does not match the end tag of 'area'. Line 1899, position 5
`
**c:\Work\UmbracoV9\MyCustomUmbracoSolution\umbraco\config\lang\da.xml**
I found the error is in this file, where there is a malformating, an **</area>** double in this file.

When correcting the error in the file an rerun, "DOTNET RUN" and run setup, the error in the file i recreated with the error.
But if I correct the error and run it, an save the file before the setup appears, It's able to finnish the setup installation.

/Happy coding

**Comment by igorssadm2** [comment] 2021-05-06 21:31
Hi!

You could shared you repository to me to understend more?

**Comment by rbottema** [comment] 2021-05-07 08:55
I think this is a duplicate of #10201, should be fixed in Beta 2. There also is a workaround posted in that issue.

**Comment by bergmania** [comment] 2021-05-10 14:18
Yep,
Duplicate of #10201

**Closed by bergmania** 2021-05-10 14:18 UTC
Labels: project/net-core
