### ISSUE TITLE
User - First ever "Last login" time is recorded or display in the wrong timezone.

### ISSUE THREAD

**Issue by TFAstudio** [umbraco/Umbraco-CMS#14612] opened 2023-07-28 06:58 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

The 1st back-office login by any new Umbraco User does not accurately reflect the local time of that user's device nor that of the hosting environment. The "Last login:" is wrong.

![image](https://github.com/umbraco/Umbraco-CMS/assets/19319418/a26033a7-62a6-4a2d-b680-46a2bc608b04)

### Specifics

Wrong time is displayed. Out by -10 hours here in Australia. So perhaps it is writing as UTC or GMT instead of local. 

_Note: Subsequent logins show the correct time._

### Steps to reproduce

1. Invite a new user.
2. Log in as that user (once) to the back-office.
3. Head to Users in the back-office and observe the "Last login" time for that new user.
4. Log out the new user, and log in again.
5. Head to Users in the back-office and observe the "Last login" time for that new user which is now displayed correctly.

### Expected result / actual result

The Last login time should always be accurate.

First login:
![image](https://github.com/umbraco/Umbraco-CMS/assets/19319418/1d553c8b-0bf9-4065-8c69-e5d0f716df31)

2nd login immediately afterwards:
![image](https://github.com/umbraco/Umbraco-CMS/assets/19319418/aed3d4c9-8d1e-45c9-83f1-9f8a94d54925)

**Comment by bergmania** [comment] 2023-07-31 13:41
Hi thanks for reporting and confirmation. 
I have a hard time reproducing, but maybe it's because my server is in same timezone as my user.  Did you reproduce with a local server or only on hosting?

**Comment by miguelcrpinto** [comment] 2023-07-31 13:49
@bergmania  I reproduced it locally. The issue is that in the PostSetInvitedUserPassword method of the CurrentUserController the LastLoginDate is being assigned the DateTime.UtcNow. From what I've seen in the CMS code, the LastLoginDate is always assigned the local time and not UTC.

I'll try to fix this later today and create a PR.

@bergmania do you know why is the user being saved using the _userService.Save instead of _backOfficeUserManager.UpdateAsync? Is there any specific reason for this? or can I replace?

**Comment by bergmania** [comment] 2023-07-31 13:54
> @bergmania do you know why is the user being saved using the _userService.Save instead of _backOfficeUserManager.UpdateAsync? Is there any specific reason for this? or can I replace?

No, I don't know why it uses _userService here. For the upcoming v14, we have managed to hide all the knowledge of the user stores, so all interaction have to be through the service.

**Comment by miguelcrpinto** [comment] 2023-07-31 19:16
Created [PR 14619](https://github.com/umbraco/Umbraco-CMS/pull/14619) to fix this issue.

@bergmania I tried to keep the changes to a minimum but I suggested an improvement in the PR description. Please check and let me know if I should apply it.

**Comment by nul800sebastiaan** [comment] 2023-07-31 20:14
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14619

**Closed** 2023-07-31 20:14 UTC
Labels: type/bug
