### ISSUE TITLE
[deployExternalContentTree] appearing in MultiUrlPicker content tree

### ISSUE THREAD

**Issue by lukehook** [umbraco/Umbraco-CMS#7429] opened 2020-01-07 19:09 UTC
## Umbraco version

I am seeing this issue on Umbraco version: 8.0.4 - notably after upgrade to Umbraco Deploy 3.3.0

Reproduction
------------

### Bug summary

After upgrading to Umbraco Deploy 3.3.0 in Umbraco Cloud which adds the ability to Partialy Restore from a parent site / environment, you now see an additional content tree item labelled [deployExternalContentTree] when using the Multi Url Picker property editor (possibly others but I have only witnessed it in this property editor).

Clicking on this tree item causes a large red error to appear on screen.

### Steps to reproduce

1. If not already, upgrade Umbraco Cloud project to Umbraco Deploy 3.3.0
2. Add a Multi Url Picker control to a document type (or edit content on an existing Multi Url Picker without a start node set)
3. Attempt to add link using Multi Url Picker property editor

### Expected result

I would expect to only see the accessible content tree and not that which is used by Umbraco Deploy.

### Actual result

![Annotation 2020-01-07 190916](https://user-images.githubusercontent.com/7995797/71921705-42d4b580-3181-11ea-883b-4a0f8062cb49.png)

---
_This item has been added to our backlog [AB#4359](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4359)_

**Comment by nul800sebastiaan** [comment] 2020-01-07 19:29
I guess this is a Deploy error and not a CMS one, but I've asked the team to provide feedback here. 👍

**Comment by lukehook** [comment] 2020-01-07 19:31
@nul800sebastiaan apologies if I put this in the wrong place - relatively new to the bug reporting process - if you'd rather I can duplicate in the correct place if you could put me in the right direction :)

**Comment by clausjensen** [comment] 2020-01-08 07:39
@lukehook Thanks for reporting! We'll get this looked at asap. I'm not sure where the fix made so it's fine that the issue is here for now.

**Comment by jeannieSoS** [comment] 2020-01-10 08:52
I'm getting exactly the same error as this on 2 cloud sites since upgrading.

**Comment by thomashdk** [comment] 2020-01-27 12:16
Hey
I'm also getting exactly the same error as this on my cloud sites since upgrading.

**Comment by clausjensen** [comment] 2020-01-27 13:27
The bug will be fixed in the upcoming 3.3.1 release of Deploy.

**Closed** 2020-01-28 10:10 UTC
Labels: state/in-sprint
