### ISSUE TITLE
Deleted child-nodes stay in the Examine Index

### ISSUE THREAD

**Issue by cryothic** [umbraco/Umbraco-CMS#13305] opened 2022-10-27 08:03 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2

### Bug summary

When you delete a single node, and it's sent to the recyclebin, you won't see it in the examin index.
When you delete a parent-node with children, the parent-node isn't available in the index but the children will show up in the index.

### Steps to reproduce

Create a structure like this:

- Jobs
  - Job_1
  - Job_2
  - Job_3

Now delete "Jobs".

### Expected result / actual result

Go to Settings \ Examine Management \ ExternalIndex
Search for "Job"
"Jobs" will not show up, but "Job_1", "Job_2" and "Job_3" will.

This results in deleted nodes showing up in the searchresults, until you manually rebuild the index.

**Comment by nikolajlauridsen** [comment] 2022-12-06 08:13
Yeah that's unfortunate, there's not much we can do if we can't reproduce it, but please do let us know if you find a way to reproduce it, or find the issue elsewhere, we can move along, or close this issue 😄

**Comment by dawoe** [comment] 2022-12-06 09:37
Hi @nikolajlauridsen @cryothic 

Maybe this is related to this one : https://github.com/umbraco/Umbraco-CMS/pull/12669#issuecomment-1338895236

Could be that merging of that one solves this issue as well.

I knew this has been a issue in the past as well, which was fixed in this PR : https://github.com/umbraco/Umbraco-CMS/pull/9010 for V8

Could be a regression bug.

Dave

**Comment by nikolajlauridsen** [comment] 2022-12-06 09:49
Hey @dawoe, thanks for the additional info 😄 It may be related, which would be fine, because then it's already fixed and headed for 10.4/11.1, which would be wonderful 😄 

But there's still the problem that I can't reproduce the issue, as far as I can see, there is no issue 😄 But hopefully we'll be able to find a way to reproduce in a clean install, and then we can continue on with it 😄

**Comment by cryothic** [comment] 2022-12-06 09:49
@nikolajlauridsen I understand :)
If I can't reproduce the problem this week in a new project, I will close this one.

**Comment by elit0451** [comment] 2022-12-21 09:51
Hey @cryothic 

Since we haven't been able to replicate your problem and we haven't heard from you in 14 days, I will go ahead and close this bug report. Feel free to reopen it if you have new info that can help us 😉

**Closed by elit0451** 2022-12-21 09:51 UTC
Labels: state/needs-more-info, type/bug
