### ISSUE TITLE
Content dropdown is showing when you hover your mouse under it

### ISSUE THREAD

**Issue by Emetico** [umbraco/Umbraco-CMS#6791] opened 2019-10-21 13:49 UTC
When upgraded to Umbraco 8.2.0, the Content dropdown begin to show when you hover under it. This makes it harder to edit content for users on smaller screens.

Reproduction
------------
1. Go to the Content Tree Section and click on a document.

2. Hover here:
![hoverError](https://user-images.githubusercontent.com/10114290/67210886-1f1f9000-f41a-11e9-9fee-d887d1c67b6c.PNG)

3. Then this show up:
![hoverErrorOpen](https://user-images.githubusercontent.com/10114290/67210910-26469e00-f41a-11e9-8f23-388ece95b676.PNG)

**Comment by bjarnef** [comment] 2019-10-21 16:05
@nul800sebastiaan I think this has already been fixed in https://github.com/umbraco/Umbraco-CMS/pull/6433

but it seems it is a "feature" in v8.2.0 release.

Original issue:
https://github.com/umbraco/Umbraco-CMS/issues/6794

Another issue regarding this in v8.2.0 :)
https://github.com/umbraco/Umbraco-CMS/issues/6430

**Comment by nul800sebastiaan** [comment] 2019-10-22 16:18
Thanks @bjarnef! I knew rand a bell. Closing as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/6430 - the fix will be part of 8.2.1.

**Closed by nul800sebastiaan** 2019-10-22 16:18 UTC
Labels: type/bug

**Comment by clausjensen** [comment] 2019-10-23 08:47
I'm closing this one as this is fixed elsewhere - and have been cherrypicked to be included in the `8.2.1` patch.
