### ISSUE TITLE
Cannot save a non-current version

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14357] opened 2023-06-08 06:59 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When saving a category node in Umbraco, we have a notification handler, which save & publish the selected courses in a picker.

This mostly works, but sometimes it fails with "Cannot save a non-current version".

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ca2a1296-9027-4d10-9dff-93e6d1ceccba)

### Steps to reproduce

Add a notification handler:

```
public class CourseReferenceChangedNotificationHandler : INotificationHandler<CourseReferenceChangedNotification>
{
    private readonly IContentService _contentService;
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;

    public CourseReferenceChangedNotificationHandler(
        IContentService contentService,
        IPublishedSnapshotAccessor publishedSnapshotAccessor)
    {
        _contentService = contentService;
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
    }

    public void Handle(CourseReferenceChangedNotification notification)
    {
        if (notification.Content.ContentType.Alias != Category.ModelTypeAlias)
            return;

        string propertyAlias = Category.GetModelPropertyType(_publishedSnapshotAccessor, x => x.Courses)?.Alias!;

        notification.Content.SetValue(propertyAlias, string.Join(",", notification.ItemsChanged));

        if (notification.Content.Published)
        {
            _contentService.SaveAndPublish(notification.Content);
        }
        else
        {
            _contentService.Save(notification.Content);
        }
    }
}
```

```
public class CourseReferenceChangedNotification : INotification
{
    public IContent Content { get; }

    public IEnumerable<Udi> ItemsChanged { get; }

    public CourseReferenceChangedNotification(IContent content, IEnumerable<Udi> itemsChanged)
    {
        Content = content;
        ItemsChanged = itemsChanged;
    }
}
```

and register it in a composer:

```
builder.AddNotificationHandler<CourseReferenceChangedNotification, CourseReferenceChangedNotificationHandler>();
```

and publish notification e.g. when category node is save & published:

```
public class CourseCategoryPublishingNotificationHandler : INotificationHandler<ContentPublishingNotification>
{
    private readonly IContentService _contentService;
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;
    private readonly IUmbracoContextFactory _umbracoContextFactory;
    private readonly ICoreScopeProvider _coreScopeProvider;

    public CourseCategoryPublishingNotificationHandler(
        IContentService contentService,
        IPublishedSnapshotAccessor publishedSnapshotAccessor,
        IUmbracoContextFactory umbracoContextFactory,
        ICoreScopeProvider coreScopeProvider)
    {
        _contentService = contentService;
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
        _umbracoContextFactory = umbracoContextFactory;
        _coreScopeProvider = coreScopeProvider;
    }

    public void Handle(ContentPublishingNotification notification)
    {
        foreach (var node in notification.PublishedEntities)
        {
            using var ctx = _umbracoContextFactory.EnsureUmbracoContext();

            var cache = ctx.UmbracoContext.Content;

            if (node.ContentType.Alias == Category.ModelTypeAlias)
            {
                var content = cache?.GetById(node.Id) as Category;

                var originalValue = content?.Courses?.Select(x => Udi.Create(Umbraco.Cms.Core.Constants.UdiEntityType.Document, x.Key)) ?? Enumerable.Empty<Udi>();

                var values = GetValues(node, Category.GetModelPropertyType(_publishedSnapshotAccessor, x => x.Courses)?.Alias) ?? Enumerable.Empty<Udi>();

                var toRemove = originalValue.Except(values);

                if (toRemove.HasAny())
                {
                    UpdatePropertyValues(node, toRemove, Course.ModelTypeAlias, Course.GetModelPropertyType(_publishedSnapshotAccessor, x => x.Categories)?.Alias);
                }
            }
        }
    }

    private void UpdatePropertyValues(IContent content, IEnumerable<Udi> udis, string contentTypeAlias, string? propertyAlias)
    {
        var nodes = _contentService.GetByIds(udis)
                        ?.Where(x => x.ContentType.Alias == contentTypeAlias);

        nodes ??= Enumerable.Empty<IContent>();

        if (string.IsNullOrEmpty(propertyAlias))
            return;

        foreach (var node in nodes)
        {
            if (!node.HasProperty(propertyAlias))
                continue;

            var vals = GetValues(node, propertyAlias) ?? Enumerable.Empty<Udi>();

            var remove = new[]
            {
                Udi.Create(Umbraco.Cms.Core.Constants.UdiEntityType.Document, content.Key)
            };

            var updatedVals = vals.Except(remove).Distinct() ?? Enumerable.Empty<Udi>();

            bool equals = updatedVals.OrderBy(x => x).SequenceEqual(vals.OrderBy(x => x));

            if (!equals)
            {
                using ICoreScope scope = _coreScopeProvider.CreateCoreScope();

                if (contentTypeAlias == Category.ModelTypeAlias)
                {
                    scope.Notifications.Publish(new CourseReferenceChangedNotification(node, updatedVals));
                }

                // Notification is published here when the scope is completed and disposed.
                scope.Complete();
            }
        }
    }

    private static Udi[]? GetValues(IContent content, string? propertyAlias)
    {
        if (string.IsNullOrEmpty(propertyAlias))
            return null;

        return content.GetValue<string>(propertyAlias)?
                .TrimStart("[")
                .TrimEnd("]")
                .Replace("\"", string.Empty)
                .Split(",", StringSplitOptions.RemoveEmptyEntries)
                .Select(x => UdiParser.Parse(x))
                .ToArray();
    }
}
```

For this purpose we have a custom picker, but MNTP can be used as well, as we based the custom picker on MNTP and the value is stored in same format where the property on category node has alias `courses`.

**Comment by bjarnef** [comment] 2023-06-21 09:03
Hi @andr317c 

It is probably difficult to reproduce and I don't get the error evertime.
The best is probably to get access to the Umbraco Cloud project and restore content locally, but because of lots of content and references, we previous had timeout issues restoring content and find it simpler just to take backup of the live db and restore it to a LocalDB or MSSQL db locally.

**Comment by andr317c** [comment] 2023-06-21 10:34
Hey again! 😄 

Since there is no apparent way for me to reproduce the issue I will go ahead to close this.

The best thing to do is probably to ask our Support Team for help. 😃

Please reach out if there are any more issues or if you have additional comments 💪.

**Closed by andr317c** 2023-06-21 10:34 UTC
Labels: state/needs-more-info, type/bug

**Comment by bjarnef** [comment] 2023-08-09 11:45
Hi @andr317c 

I have tried to convert this to default starterkit instead.
[RelationPicker.zip](https://github.com/umbraco/Umbraco-CMS/files/12302115/RelationPicker.zip)

Course -> Product
Category -> Person

On product there's a persons pickers.. when selecting persons the product is updated on these persons in a products picker.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/a40793a5-ddef-4717-90c7-37eedd3003af)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/9b1d0256-a936-4a0b-ae24-90ba72a59b3f)


Furthermore theres a custom "Relate Product Person" relation (relateProductPerson), where a relation is created with selecting products/persons.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ba04ff56-90de-4c38-b558-449b3aa1363d)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/99cc1638-8189-4b46-ba3c-5b7a1a402895)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/a409844f-3850-47ca-9dd4-d92466eb6ad0)

**Comment by LennardF1989** [comment] 2023-09-23 18:02
I have one such node in one of my installations now. Works fine one save, breaks if you save again. Will investigate. Seems mostly related to some sort of corruption.

**Comment by LennardF1989** [comment] 2023-09-25 10:54
Just as an update: the issue was caused by a Notification Handler that would do database queries without completing the scope. This causes the scope used by the SaveAndPublish call to fail.

You could see something was up, since after the first save and publish, it also wouldn't update the version history for the Content-node.

**Comment by bjarnef** [comment] 2024-05-01 08:31
Could possible be fixed in https://github.com/umbraco/Umbraco-CMS/pull/15207

**Comment by jaandrews** [comment] 2024-12-13 00:55
This doesn't seem to be fully resolved yet. I ran into this error with code that publishes the same node a a couple times before it finishes when working in **umbraco 13.5.2**. A simplified version of it can be seen below.

```csharp
public void Import(Guid key) {
    using (var scope = _scopeProvider.CreateScope()) {
          UpdateNodeProperty(key)
          UpdateOtherNodeProperty(key)
	  scope.Complete();
      }
}
```

Both UpdateNodeProperty and UpdateOtherNodeProperty call _contentService.GetById against the passed in key to get the IContent instance and then SaveAndPublish it, but the second one fails with "Cannot save a non-current version." I tried refactory to only call SaveAndPublish once and call SaveAndPublish the other times, but that didn't help.

**Comment by jaandrews** [comment] 2025-01-20 22:46
I poked at this a bit more and the issue appears to be caused by the scope. When I remove  the scope wrapped around those methods, it saves successfully. Ideally it would work with the scope though, as I would prefer it to roll back all changes if anything fails.

**Comment by jaandrews** [comment] 2025-01-31 19:19
@markadrake  One way you might be able to work around the issue is to store the data somewhere else when the umbraco forms workflow runs instead of saving it to the node, like storing it in a custom database table or the appCache. The hangfire job could then read that data and add it to the content node, in addition to the data it currently adds, before it saves. This would allow you to only trigger a single saveAndPublish to hopefully bypass the issue. 

You may want to reach out to umbraco support though, as there may be a better way to handle this and it might be something they can fix on their side.
