### ISSUE TITLE
Changing a property on multi language causes "This document is published but its url cannot be routed"

### ISSUE THREAD

**Issue by AreYouSureYouKen** [umbraco/Umbraco-CMS#7269] opened 2019-12-03 15:11 UTC
Using the currently newest version of Umbraco (Version 8.3.0) 

We are developing a new multi language website, currently dutch and english and have the hostname domains set up as

websitename.com.local for the Dutch variant
websitename.com.local/en for the English variant

Whenever we change a document type, e.g. add/edit/remove a property, the domain on which we initiated the change, starts throwing the "This document is published but its url cannot be routed" error for pages on the website. It looks like it's mostly pages that are affected by the change made to a document type/element type but sometimes other pages seem to be affected as well.

Deleting the Temp folder in App_Data and giving the IIS AppPool a recycle seems to fix the problem, however, this is definitely not something I feel comfortable putting into a live environment.

Edit: Deleting the Temp folder doesn't seem to be necessary, recycling the app pool looks to be enough.

**Comment by kjac** [comment] 2019-12-04 10:43
Hi @AreYouSureYouKen,

I'm trying to reproduce this on 8.4 (RC) and I can't really seem to. Here's what I've been testing:

![url-cannot-be-routed](https://user-images.githubusercontent.com/7405322/70135823-18c43b00-168b-11ea-8915-c0b3a53b8dd0.gif)

As you can see, the setup is much like the one you're describing.

When you say the site starts throwing errors, how exactly does this manifest? Is it in the backoffice or the frontend (or both)?

**Comment by AreYouSureYouKen** [comment] 2019-12-04 12:28
Hello @kjac 

I made a video as well showing how this looks on my end, for some reason it's affecting other pages. When I edit page A it goes well and the error doesn't pop up. But when I edit page B it goes wrong on page A. See gif below:

![CoWuJJhc3C](https://user-images.githubusercontent.com/5592855/70142618-f84fad00-1699-11ea-98c1-c6752d9c2b12.gif)

**Comment by kjac** [comment] 2019-12-04 13:21
@AreYouSureYouKen thanks! I'll give it another spin 👍

**Comment by kjac** [comment] 2019-12-04 13:31
Hmm no. Still can't repro on 8.4 (RC) despite trying with multiple doctypes and compositions.

**Comment by nul800sebastiaan** [comment] 2019-12-04 13:37
Thanks for the tests and helpful gifs @kjac and @AreYouSureYouKen!

@AreYouSureYouKen I would encourage you to take a backup of your site + DB and upgrade that to 8.4-rc and see if you can still make it fail. It looks like it doesn't fail on a clean 8.4 install, so I'll close this for now and assume it is either fixed or it has something to do with custom code you might have. 

Feel free to update this issue with new info, we can always re-open it if it's reproducible.

**Closed by nul800sebastiaan** 2019-12-04 13:37 UTC

**Comment by shearer3000** [comment] 2020-04-02 00:34
hi @AreYouSureYouKen - did you ever resolve this issue? thanks

**Comment by AreYouSureYouKen** [comment] 2020-04-02 07:21
Hello @shearer3000 unfortunately not no. It is still something that can happen when we change a document type or add a new one. Recycling still fixes this problem but it's not something you want to be doing on a live-server.

**Comment by hfloyd** [comment] 2020-04-16 01:41
I came across a more insidious version of this issue while working on a v7.15.4 -> 8.6 migration.

This site doesn't have any multi-lingual variants, but every single node was showing "This document is published but its url cannot be routed" in lieu of the URL link.

Deleting the App_Data/TEMP files, restarting, recycling the AppPool, even writing a webapi to loop through and re-save every content node in the site had no effect on the issue.

Finally, I tracked down the problem to custom code migrated from AppStarting/AppStarted events. When I commented out that code, rebuilt, and refreshed the back-office - now all the links have appeared.

**Comment by vladicaivanovski** [comment] 2021-01-22 09:37
8.9.1 still happening. I can't create nodes because of this error: This document is published but its url cannot be routed.

My app is hosted in Azure as App Service. I tried both Memory Cache - Reload and Database Cache - Rebuild, none of them helped.

Any plan for resolving this issue?
