### ISSUE TITLE
v9-rc001: Validation error when saving content with variants

### ISSUE THREAD

**Issue by vsilvar** [umbraco/Umbraco-CMS#10631] opened 2021-07-09 08:01 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-rc001

### Bug summary

Whenever content with more than one culture variant is being saved, if one of the variants is not created the save will return a 400.
This will cause both the Save modal to not be dismissed after saving and the Preview functionality to not work.

The content itself is saved correctly, the response simply erroneously returns a 400 model validation error.

### Specifics

When saving content with variants, the model validation runs for all variants even the ones that are not being saved.
In cases where one of the variants not being saved hasn't been created yet, the required validation on the Name field will fail due to it being set to an empty string.
This shouldn't be a problem, as the `ValidateCriticalData` method removes those variant's key from the ModelState, but it seems that although the `errorCount` is updated to 0, the `IsValid` property remains false.

### Steps to reproduce

- Add an extra culture to the CMS
- Try to Save a content item's primary culture (while keeping the second culture variant not created)

### Expected result / actual result

PostSave call should return a 200.
Save Modal should be dismissed but it's not.
Preview mode also doesn't work because of this.

---
_This item has been added to our backlog [AB#13791](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13791)_

**Comment by nikolajlauridsen** [comment] 2021-07-09 08:48
Hey @vsilvar thanks for reporting, I can reproduce this, so will have a look. 

From a cursory look, it does indeed seem like the error count is 0, but the model is still marked as invalid which is mighty weird 🤔

**Comment by bergmania** [comment] 2021-09-20 19:42
I cannot reproduce on latest `v9/dev`.. Seems like this is fixed by something else. @nikolajlauridsen can you verify it cannot be reproduced anymore?

**Comment by nikolajlauridsen** [comment] 2021-09-21 07:56
I can't reproduce anymore either, even if I follow the same steps as I did before, so I'll assume that this has been fixed, and will go ahead and close this issue.

**Closed by nikolajlauridsen** 2021-09-21 07:56 UTC
Labels: project/v9, state/sprint-candidate, type/bug
