### ISSUE TITLE
ContentService Copying e.CancelOperation returns an error in back end

### ISSUE THREAD

**Issue by pragneshmpatel** [umbraco/Umbraco-CMS#3253] opened 2018-10-11 08:59 UTC
When we try to cancel copying event it throws error

Reproduction
------------

Extend contentservice.copying and try to cancel operation in the copying event.

Sample code: 
```

 protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
    {
        ContentService.Copying += ContentService_Copying;
    }

      private void ContentService_Copying(IContentService sender, CopyEventArgs<IContent> e)
    {
        e.CancelOperation(new EventMessage("", "You can not copy", EventMessageType.Error));
    }
```
### Bug summary

    * If we cancel the copying operation it should cancel & show error message

### Specifics

    * More info: https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/92722-contentservice-copying-ecanceloperation-returns-an-error-in-back-end#comment-297650

    * Umbraco version 7.11.1 assembly: 1.0.6750.39767
    * What browser and version you are using - Chrome
    * Please mention if you've checked it in other browsers as well -Yes
    * 
System.NullReferenceException: Object reference not set to an instance of an object. Stacktrace

at Umbraco.Web.Editors.ContentController.PostCopy(MoveOrCopy copy)

at lambda_method(Closure , Object , Object[] )

at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>cDisplayClass10.9(Object instance, Object[] methodParameters)

at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)

at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Controllers.ApiControllerActionInvoker.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.ActionFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Controllers.ActionFilterResult.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.AuthorizationFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.AuthorizationFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Filters.AuthorizationFilterAttribute.

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Web.Http.Dispatcher.HttpControllerDispatcher.

### Expected result

    * It should cancel copy operation and show error message

**Comment by kjac** [comment] 2018-10-14 20:44
It looks like this is an issue for all copy and move operations throughout Umbraco. I'm working on a fix.

**Comment by kjac** [comment] 2018-10-15 07:33
OK. Fixing this is going to require a fair bit of refactoring and extension in parts, that are tagged for removal in V8 (`IContentServiceOperations` among other things). 

I believe this issue is best solved by applying a temporary fix until V8 - namely one that doesn't cause an error in the back office (basically some extra null checks), but unfortunately also one that won't propagate the error message to the back office. @nul800sebastiaan any thoughts here?

**Comment by nul800sebastiaan** [comment] 2018-11-14 17:33
I know that we put in a fix for #3387 so I think any other affected events should have a similar fix. 

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment] 2018-11-15 05:45
@nul800sebastiaan looks like #3599 is an attempt to fix this?

**Comment by bharanijayasuri** [comment] 2018-11-15 09:46
I have just added a simple null check to show the standard "Failed to copy content" error message in the back office when a content copy event is cancelled in code. I know it might not be that meaningful when the custom message entered by the user is not shown, but it is going to take a lot more refactoring which I am currently looking at to make sure any changes I make is not going to break existing functionality somewhere else in the project.

**Comment by bharanijayasuri** [comment] 2018-11-15 15:29
Alright, I might have a fix for content copy event cancellation notification as well now which is part of the pull request.

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:31
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:31 UTC
Labels: community/up-for-grabs, help wanted, type/bug
