### ISSUE TITLE
umbraco backoffice links reporting "http://www.mysite.com[object Object]" in url

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7869] opened 2020-03-31 21:23 UTC
hi there

quite frequently the link tab in the backoffice will report:

```
http://www.mysite.com[object Object]
This document is published but its url cannot be routed
```

Tyring to ‘save and publish’ again and/or using the Refresh Status/Memory cache Reload/Database cache Rebuild buttons will have mixed results (i.e. sometimes it will correct the issue, sometimes not), but ultimately the issue will appear again after time.

I have no precise replication steps, so let me know any technical information that might help troubleshooting this.

This is on umbraco 8.5 using language variants, But still happens after upgrading to 8.6

Thanks
Andrew

**Comment by nul800sebastiaan** [comment] 2020-04-01 08:01
Unfortunately we also can't reproduce it, so we're really waiting for someone to give us the final clue. I'm going to close this for now, but maybe the earlier closed issues might help you out: https://github.com/umbraco/Umbraco-CMS/issues?q=is%3Aissue+This+document+is+published+but+its+url+cannot+be+routed+is%3Aclosed

**Closed by nul800sebastiaan** 2020-04-01 08:01 UTC

**Comment by shearer3000** [comment] 2020-04-02 00:31
Hi Sebastiaan – appreciate you could have a look at this. I had a look at those earlier tickets and it appears they were all closed without a resolution either. Would it be possible to keep at least 1 ticket open to track this problem is it sounds like something multiple people are experiencing. Maybe it would be possible to provide you a copy of an umbraco database so you can see the problem in action?

**Comment by nul800sebastiaan** [comment] 2020-04-02 06:58
It's really no use keeping an issue open if we can't make progress on it. 

At the moment this seems to be a problem with a handful of implementation and is not reproducible. We'd love to investigate everybody's issues in depth but unfortunately we don't have the resources for that and we need to prioritize more common, reproducible issues.

**Comment by shearer3000** [comment] 2020-04-21 20:06
Hi Sebastiaan - as it turns out after some digging, this was a conflict between some of our javascript and umbraco. We have resolved it now. Apologies
