### ISSUE TITLE
Notification is hidden behind side menu on trashing action event cancel.

### ISSUE THREAD

**Issue by mPieczka** [umbraco/Umbraco-CMS#9736] opened 2021-02-01 09:44 UTC
Hi, I'm not sure if it is a bug or feathure request. I have added prevention of trashing used media item. When trashing media item event fires, system check if item is in use by relation service, if yes, action is canceled and notification is added. Part of notification is hidden behind side panel.

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.1 and 8.11.1

Reproduction
------------

### Bug summary

3rd party notification during trahing operation is hidden behind side menu.

### Specifics

My event handler code:
![obraz](https://user-images.githubusercontent.com/26299040/106438024-3733eb00-6476-11eb-8e8d-5a54bca81b1b.png)

Application view:
![obraz](https://user-images.githubusercontent.com/26299040/106440202-dc4fc300-6478-11eb-8784-b08acf180b99.png)

### Steps to reproduce

1) Developer add prevention of trashing action by canceling event.
2) User log in to the application
3) User goes to media tab, and try to delete media
4) If system cancel operation, side menu is still visible, so it hide notification.

### Expected result

Side menu is hidden when trashing operation is cancelled.

### Actual result

Side menu hide some part of notification

**Comment by nul800sebastiaan** [comment] 2021-02-01 13:06
Thanks! I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/9614

**Closed by nul800sebastiaan** 2021-02-01 13:06 UTC
