### ISSUE TITLE
MultiNode Treepicker allows selection of more than configured maximum number of items

### ISSUE THREAD

**Issue by ProNotion** [umbraco/Umbraco-CMS#16924] opened 2024-08-16 11:55 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.10

### Bug summary

When a maximum number of items is configured on the datatype users are still able to select more than the maximum number of nodes when selecting multiple content items in the tree picker in a single action. If links are added one at a time the maximum cannot be exceeded. 

The node cannot be published while there are more than the maximum number of items, however, the tab is highlighted on which the property exists but the property itself is not. The error message is present but since it is not highlighted can be easily missed.

### Specifics

When selecting more than maximum you are still able to add more than you should.
![image](https://github.com/user-attachments/assets/22504cd4-b306-4253-9a1b-7ee23d014cdf)

When adding items one at a time you cannot add more than maximum
![image](https://github.com/user-attachments/assets/e05ef231-145f-441c-94b3-a538ba1cc8ff)

### Steps to reproduce

1.  Create a datatype with a `Umbraco.MultiNodeTreePicker` property editor. Set a maximum number of items that can be selected.
2. Add a property to a content type using the new  datatype.
3. Add a new content item using the new content type
4. Click to add new content using the MutliNode Tree Picker and select more than the maximum number of items.

### Expected result / actual result

You should not be able to select more than the maximum number of items in the UI, regardless of how you add them.

**Comment by NguyenThuyLan** [comment] 2024-08-21 06:35
Hi @ProNotion , thank you for reporting this issue.
However, this is not a bug. We want the editors to be able to save invalid content in a draft state.
The thought behind this is: if one is writing up a page of content and gets interrupted in the middle of it all, they should be able to save whatever they have done so far, so as not to lose their work.
And of course, users can not publish content because of invalid content.
I will close this issue, feel free to reopen it or ask 😊

**Closed by NguyenThuyLan** 2024-08-21 06:35 UTC
Labels: type/bug
