### ISSUE TITLE
v8: Custom MVC route breaks PluginController routing in the backoffice

### ISSUE THREAD

**Issue by Harrysoon** [umbraco/Umbraco-CMS#6103] opened 2019-08-12 15:48 UTC
Hi,

I've got a basic route setup in my route table that's setup in an IComponent to get picked up on application startup.

`RouteTable.Routes.MapRoute(
                "CustomRoute",
                "custom/{controller}/{action}",
                defaults: new
                {
                    controller = "{controller}",
                    action = "{action}"
                }
            );`

The route works fine with my Html.Actions that I have in place on my site, but when I go to the back office models builder errors when trying to open it with the error:

> The view 'GetDashboard' or its master was not found or no view engine supports the searched locations...

When checking dev tools, the request is picking up my custom route

`http://localhost:64140/custom/ModelsBuilderBackOffice/GetDashboard` instead of `/umbraco/BackOffice/Api/ModelsBuilderBackOffice/GetDashboard`. 

I then tried making my route attribute a single controller, for example:

`RouteTable.Routes.MapRoute(
                "CustomRoute",
                "custom/MyController/MyAction",
                defaults: new
                {
                    controller = "MyController",
                    action = "MyAction"
                }
            );`

Only now, my HttpRoute I have set overrides the backoffice route, and I get the below as the request URL:

`http://localhost:64140/api/PublishedStatus/GetPublishedStatusUrl`

Not sure where I'm going wrong with my custom routes, anything I set seems to override the PluginController routing, which was never an issue in v7.

**Comment by stevemegson** [comment] 2019-08-12 16:19
In v8, your routes are registered earlier than they would have been when using `ApplicationStarted` in v7. As a result, your routes can take priority over the backoffice's routes when they wouldn't have before.

That'll probably change, but until then you can work around it with a composer like this:

```c#
[ComposeAfter(WebFinalComposer)]
public class MyComposer : IComposer 
{ 
        public void Compose(Composition composition)
        {
            composition.Components().Append<MyComponent>();
        }
}
```

The `ComposeAfter` attribute ensures that your component runs after the backoffice has registered its routes. You also have to use `IComposer` rather than `IUserComposer` to avoid a circular dependency, (with your IUserComposer asking to run after WebFinalComposer and WebFinalComposer asking to run after your IUserComposer).

**Comment by Shazwazza** [comment] 2019-08-13 05:29
This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/6045

**Closed by Shazwazza** 2019-08-13 05:29 UTC
