### ISSUE TITLE
Unable to View White SVG's in Media Section on Image Node

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/Umbraco-CMS#4004] opened 2019-01-08 22:15 UTC
I just installed Umbraco 7.13.0 with all the defaults.

I then updated the umbracoSettings.config to ensure SVG is recognized as an image file type. Search this page for "imageFileTypes" to find out how to do that: https://our.umbraco.com/documentation/reference/config/umbracosettings/

I then dragged an SVG image to the media section to upload it. Once it uploaded, I clicked the media item to view the details:

![white-svg](https://user-images.githubusercontent.com/5933222/50862108-ed8c7b00-1357-11e9-833f-56c64c6ae133.png)

As you can see, the white SVG is not really visible. Well, it is, except that the background is also white, and white on white is just a big sea of white. Other SVG images that are not white (e.g., blue) are visible.

Other places in Umbraco deal with this by adding a checkerboard pattern behind the image, which gives it the necessary contrast to make it visible. For example, the media picker and the grid view in the media section seem to do this. Seems like this spot was missed, however.

**Comment by dawoe** [comment] 2019-01-09 07:40
Hi @Nicholas-Westby 

Thanks for reporting this issue. Can you provide the SVG that you used so we can use it for reproducing and for testing ?

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment] 2019-01-09 08:33
[This one should work](https://upload.wikimedia.org/wikipedia/commons/d/da/White_dot.svg) (no that's not a blank page that opens, it's a white PNG 😉). We should have the checkered background behind it as well like we do in the list view overview, this is what it looks like in the list: 

![image](https://user-images.githubusercontent.com/304656/50886690-62f85a00-13f1-11e9-85db-5c0558ab18ef.png)

Of course when it's a completely solid white SVG I don't know what to do.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Nicholas-Westby** [comment] 2019-01-09 16:47
@nul800sebastiaan That is not correct. You are looking at the grid view rather than the actual media node itself. The media node itself, as you can see in my screenshot, is the place where this is an issue.

**Comment by Nicholas-Westby** [comment] 2019-01-09 16:48
@nul800sebastiaan My mistake, I misread your comment, so I deleted my previous comment. Thank you for finding the white SVG sample.

**Comment by skttl** [comment] 2019-01-10 07:49
Maybe also add a subtle drop-shadow to the image preview, like in the list-view? This would help for completely solid white images too.

**Comment by kjac** [comment] 2019-01-12 12:43
I've got a fix for this, will push later 👍

**Comment by kjac** [comment] 2019-01-12 18:56
PR in #4050

**Comment by Nicholas-Westby** [comment] 2019-01-13 02:05
You rock, @kjac!

**Closed** 2019-01-13 12:54 UTC
Labels: community/up-for-grabs, help wanted, type/feature
