### ISSUE TITLE
Cannot save and losing data in nested content after 8.1 upgrade (from 8.0.2)

### ISSUE THREAD

**Issue by miackers** [umbraco/Umbraco-CMS#5909] opened 2019-07-16 10:41 UTC
- When trying to save data, the data gets lost
- When editing nodes with nested content (from previous install), some of them lose their data.

Reproduction
------------

### Bug summary

When saving/editing nodes with nested content, some of them lose their data

### Specifics

This seems to happen when the nested content element is set to "allow varying by culture", but none/some of the element's properties is not set to vary.

### Steps to reproduce

1. Create doctype set to vary by culture, and make it an element type
2.1 Add property to the doctype, but not set it to vary.
2.2 (Optional: Add another but set it to vary - to see the difference)
3. Create nested content data type referencing above doc type (easiest to set min and max to 1, but not required)
4. Add nested content to your home node (for example). 
5. Ensure your site have more than one language (works if only 1 language - I think)
6. Try save information into nested content 

### Expected result

Content to save (and not lose data)

### Actual result

save loses data (and previous content from v8.0.2 gets deleted)

**Comment by miackers** [comment] 2019-07-16 10:42
I am still doing some investigations around this, so will update as I go along - but wanted to raise to see if anyone else is having the same issue/can be reproduced on another instance

**Comment by miackers** [comment] 2019-07-16 11:02
I've now managed to reproduce this in a clean Umbraco 8.1 installation, and updated the steps to reproduce this problem

**Comment by kjac** [comment] 2019-07-16 11:50
This might be a duplicate of #5817. 

@miackers let me see if I understand this correctly. You have defined the element type (used in Nested Content) as culture variant, and added a mix of culture variant _and_ invariant fields to the element type?

**Comment by miackers** [comment] 2019-07-16 12:08
Yes and no. Its not a requirement to have a mix - ie, all the fields can be invariant fields, and the issue will happen (I know in that scenario it doesnt make sense for the element type to be set as to have culture variants) 

One might ask why enable the nested element to have a culture variant - since currently (correct me if I am wrong) you can't make use of that functionality - ie, the UI doesnt allow you to inherit some fields from different languages anyway (I assumed this would work for 1 max/1 min, but not even for that?!)

So, currently for me the "fix" is to remove the "allow varying by culture" from my element types.

**Comment by miackers** [comment] 2019-07-16 12:18
updated steps to produce to make clear its an element type

**Comment by kjac** [comment] 2019-07-19 10:24
I've found the problem - will submit a fix shortly.

**Comment by kjac** [comment] 2019-07-19 11:02
PR In #5952

**Comment by mikeallen222** [comment] 2019-07-21 22:36
Thanks @kjac. I ran into the same bug after trying to make a nested content type with variant culture in 8.1.

**Comment by nul800sebastiaan** [comment] 2019-08-13 15:01
I think this is indeed a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/5817 - let's continue the conversation there, the fix provided by @kjac seems good so we'll test and review that one which should fix this as well. @miackers if you could try to apply the change manually on your current 8.1 install to see if you can test it then that would be awesome! 

In `~/Umbraco/Js/umbraco.controllers.js` around line 20042 replace this block:

                for (var v = 0; v < node.variants.length; v++) {
                    var variant = node.variants[v];
                    for (var t = 0; t < variant.tabs.length; t++) {
                        var tab = variant.tabs[t];
                        for (var p = 0; p < tab.properties.length; p++) {
                            var prop = tab.properties[p];
                            prop.propertyAlias = prop.alias;
                            prop.alias = $scope.model.alias + '___' + prop.alias;
                            // Force validation to occur server side as this is the
                            // only way we can have consistency between mandatory and
                            // regex validation messages. Not ideal, but it works.
                            prop.validation = {
                                mandatory: false,
                                pattern: ''
                            };
                            if (fromNcEntry && fromNcEntry[prop.propertyAlias]) {
                                prop.value = fromNcEntry[prop.propertyAlias];
                            }
                        }
                    }
                }


With this block:

                 var variant = node.variants[0];
                    
				for (var t = 0; t < variant.tabs.length; t++) {
					var tab = variant.tabs[t];
					for (var p = 0; p < tab.properties.length; p++) {
						var prop = tab.properties[p];
						prop.propertyAlias = prop.alias;
						prop.alias = $scope.model.alias + '___' + prop.alias;
						// Force validation to occur server side as this is the
						// only way we can have consistency between mandatory and
						// regex validation messages. Not ideal, but it works.
						prop.validation = {
							mandatory: false,
							pattern: ''
						};
						if (fromNcEntry && fromNcEntry[prop.propertyAlias]) {
							prop.value = fromNcEntry[prop.propertyAlias];
						}
					}
				}

That should do the trick. 

The best way to make sure your browser picks up the changes is to then update the version in ClientDependency.config (just make it 1 higher or lower).

Make sure to comment in https://github.com/umbraco/Umbraco-CMS/issues/5817 with the results!

**Closed by nul800sebastiaan** 2019-08-13 15:01 UTC
Labels: community/pr, release/8.1.3, type/bug
