### ISSUE TITLE
Editor - Fixed on scroll - Or option to do so

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco-CMS#8489] opened 2020-07-28 00:04 UTC
When clients are writing in content into an editor property and not using the grid and that text is more then say 30 lines and part of a Document type with other fields, especially with 8 and the loss of tabs to format they have to keep scrolling up and down to access the editor buttons.

It should have an option so on scroll it remains fixed at the top.
Something like this: 

<img width="1578" alt="Screenshot 2020-07-28 10 03 55" src="https://user-images.githubusercontent.com/304656/88770903-c2a68980-d17e-11ea-9a6c-85daf6bf2f32.png">

**Comment by nul800sebastiaan** [comment] 2020-07-29 07:34
I am not sure what the problem is? Do you have an illustration of the problem please?

**Comment by thenexus00** [comment] 2020-07-29 07:54
I have informed the clients in question who ask to hit the full screen option for now. Here when you have large content you got the full screen and the editor controls stay fixed.

I thought it would be good as you scroll that this did that as well in normal view without having to go there and the mock up shows that.
There are some challenges, with multiple editors when the next one comes into view you overlay that one but even Angular supports that scroll fix effect in it already.

**Comment by abjerner** [comment] 2021-06-14 08:28
I just stumbled upon this issue. This seems to be fixed in **8.10** due to this pull request: https://github.com/umbraco/Umbraco-CMS/pull/9316

As a result of this, I'm closing the issue. But feel free to comment again if it should not work after upgrading 😉

**Closed by abjerner** 2021-06-14 08:28 UTC
Labels: state/needs-more-info
