### ISSUE TITLE
Ajax to surface controller stop work after login request

### ISSUE THREAD

**Issue by eliranrefael** [umbraco/Umbraco-CMS#13932] opened 2023-03-08 16:35 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

Im using heavily on ajax and surface controllers.
im using antiforgery which i implant in the headers, like this: 
![image](https://user-images.githubusercontent.com/37138835/223771875-50355ad2-3521-4c16-ab55-378cbbef1d23.png)
![image](https://user-images.githubusercontent.com/37138835/223771944-e7fd68ca-8c4c-45a1-9356-316c1eb1b2e0.png)

i can do each call by it self or a sequence of calls and it works flawless. but if i do a login request, without refreshing, all other ajax calls will be refused with 400 error.

get fixed if page is refreshed or [IgnoreAntiForegery] tag is applied to the controller method.

### Specifics

checked only on chrome

### Steps to reproduce

- make simple ajax request in some surface controller.
- set up the headers for antiforgery as shown.
- set up HTTPOST and ANTIFORGERYKEY attributes to your surface controller's methods.
- call login using ajax to surface controller.
- call your simple surface controller afterwards.

### Expected result / actual result

Expected: 
ajax call works as it works without the login request.

Actual:
all ajax calls before the login call works, the login itself works, and afterwards no ajax call to surface controller works anymore.

**Comment by bergmania** [comment] 2023-03-08 19:11
Hi @eliranrefael 

Thanks for reporting. We will most likely need even more details to be able to reproduce.  This could potentially already have been fixed by https://github.com/umbraco/Umbraco-CMS/pull/13919.

Are you able to test it out directly from `v10/dev` branch?  Otherwise we will most likely need some small setup example code to reproduce.

**Comment by Zeegaan** [comment] 2023-03-20 06:57
Hello there! As it's been a while since we have heard from you, and we cannot reproduce this, we're going to go ahead and close this issue for now. Feel free to re-open if this is still an issue 🙏 🐛

**Closed by Zeegaan** 2023-03-20 06:57 UTC
Labels: state/needs-more-info, type/bug
