### ISSUE TITLE
UmbracoAuthorizedApiController returns invalid JSON response

### ISSUE THREAD

**Issue by balintbako** [umbraco/Umbraco-CMS#12656] opened 2022-07-04 21:35 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

The Backoffice API controllers (**UmbracoAuthorizedApiController**) return invalid JSON response.
The following characters sequence is added to the beginning of the response regardless of response type:
**)]}',**

### Specifics

The following test controller returns the invalid response:

```
using Umbraco.Cms.Web.BackOffice.Controllers;

namespace Umbraco10.Controller.Api
{
    public class TestBackofficeController : UmbracoAuthorizedApiController
    {
        public IEnumerable<string> GetArray()
        {
            return new List<string> { "value1", "value2" };
        }
    }
}
```

The respons to: GET https://localhost:44382/umbraco/Backoffice/Api/TestBackoffice/GetArray
```
)]}',
["value1","value2"]
```
So it has this on the front for apparent reason: **)]}',**

The exact same GetArray() method in a **UmbracoApiController** returns the correct response:
```
using Umbraco.Cms.Web.Common.Controllers;

namespace Umbraco10.Controller.Api
{
    public class TestController : UmbracoApiController
    {
        public IEnumerable<string> GetArray()
        {
            return new List<string> { "value1", "value2" };
        }
    }
}
```

GET https://localhost:44382/umbraco/Api/Test/GetArray
Response:
`["value1","value2"]`

This is while debugging in Visual Studio 2022 in a project that was created from the Umbraco 10 project template.
There are no other customizations in the Umbraco site.

### Steps to reproduce

Use the code above to reproduce the issue.

### Expected result / actual result

The actual response JSON:
```
)]}',
["value1","value2"]
```

The response JSON should be:
`["value1","value2"]`

**Comment by nul800sebastiaan** [comment] 2022-07-12 11:42
Thanks @balintbako - this is actually a security feature and if you consume the API call with AngularJS' `$http` module it will just work - see https://github.com/umbraco/Umbraco-CMS/issues/11663#issuecomment-973803376 for more info. 

I'll close as a duplicate of #11663 - a workaround is posted there as well using the `Authorize` annotation on a regular controller/apicontroller.

**Closed by nul800sebastiaan** 2022-07-12 11:42 UTC
Labels: type/bug

**Comment by ewuski** [comment] 2023-01-25 22:43
I have the same issue when calling from react that is called in custom section html view.

May I know why I must use `angularjs` from the backoffice and cannot do a request using react? If `UmbracoAuthorizedApiController` is apparently authorized anyway?

**Comment by jonathoncove1** [comment] 2023-05-24 10:03
I was able to return valid JSON data within an UmbracoAuthorizedApiController by using the following:
`public JsonResult GetArray()
{
    return new JsonResult(new List<string> { "value1", "value2" });
}`

You'll need a reference to `Microsoft.AspNetCore.Mvc;`
Tested on Umbraco 10.5.1

**Comment by IanIsFluent** [comment] 2023-08-04 14:22
> I was able to return valid JSON data within an UmbracoAuthorizedApiController by using the following: `public JsonResult GetArray() { return new JsonResult(new List<string> { "value1", "value2" }); }`
> 
> You'll need a reference to `Microsoft.AspNetCore.Mvc;` Tested on Umbraco 10.5.1

Nice - thanks! This is great :)

Can I just say:
![image](https://github.com/umbraco/Umbraco-CMS/assets/34126328/249e8caa-8d7f-4a26-af86-8a2fab132368)
