### ISSUE TITLE
Block Grid is not rendering the layout or contents in areas

### ISSUE THREAD

**Issue by mjamil4it** [umbraco/Umbraco-CMS#17604] opened 2024-11-21 09:53 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

Umbraco 15.0.0 is not rendering blocks in areas. 
If I add a block in the root, it gets rendered fine. But if I add a block in the area then try to render, it does not work. 

I have tested this on the fresh install of Umbraco 15.0.0 or upgraded V14 to V15, but areas do not get rendered.
There is no error in the logs. 

It seems like Block Grid completely ignores the areas. 

### Steps to reproduce

Create an element with RTE as a property, call this RTE Block 
Create an element with no properties, call this container layout

Create Block Grid property, Add RTE block and allow in area only.  Then  add Container layout allow in Root only and in area tab create a 12 grid area. Area can be two, three or any number of columns.   

Add this block grid property on the document type. 

Create a page using this document type and in block grid add container and within container add RTE block with some text. 
Save and publish. 

Nothing get rendered. 

This approach works from V12 to V14. 

### Expected result / actual result

Area should be rendered.

**Comment by jbrisnehan-AMG** [comment] 2024-11-25 23:07
We're having the same issue.  Since upgrading to v15, any new block grid content does not render on the frontend.  

Old content still renders, but if you create a new item on an existing grid/page or an entirely new page/grid; the front end will not render.  

Stepping through GetBlockGridHtmlAsync the Model exists but the model count is 0, therefore an empty string is returned:

`@await Html.GetBlockGridHtmlAsync(Model,"bodyGridView")`

I suspect the issue is related to the recent migration away from the Udi keys in v15.  Comparing the old content that does get rendered vs the new....  The content that is not rendering on the front-end does not have a contentUdi:

```
"contentUdi":null,
"settingsUdi":null,
"contentKey":"6be5e43d-520d-4567-9f7f-9f4758c956c3",
"settingsKey":"34e68bdd-be02-4d33-b4e5-fa3151f4a507"
```

However, the content that DOES render successfully via GetBlockGridHtmlAsync has a contentUdi:

```
"contentUdi":"umb://element/a2dd5ae02d2144c39186a961ac540304",
"settingsUdi":null,
"contentKey":"a2dd5ae0-2d21-44c3-9186-a961ac540304",
"settingsKey":"841a56d9-8955-4892-8997-2e9986c6a191"
```

**Comment by nielslyngsoe** [comment] 2024-11-26 09:24
Hi @mjamil4it 

Thanks for reporting, I'm able to replicate. If it is true that the layout block of yours is greyed out? — as seen in this screenshot:
![image](https://github.com/user-attachments/assets/73110346-a989-419e-ad0a-73abdf77a3a3)

This is clearly an issue originating from the new feature of Variant Blocks.
Its because the block is not `exposed` aka. created for the given variant jet. This can be solved by adding some properties to the layouts Content Element Type, which then enables you to open the editing modal and `create` it.
This experience has already solved in 15.1, which brings a create-button to Blocks without Content.

There is quite a few things important details regarding Block Editors that has been implemented and improved in 15.1. So please have a look at this version once it gets out. Its in RC later this week, released in about 2 weeks.

Sorry for the trouble, let me know how it works for you.

**Closed by nielslyngsoe** 2024-11-26 09:24 UTC
Labels: type/bug

**Comment by mjamil4it** [comment] 2024-11-26 15:51
Hi Niel, 

Just to confirm, by adding a property to an empty layout, it works. Layouts are not longer greyed out. 
Thank you for the quick solution. 

Looking forward to Umbraco 15.1. :)

**Comment by nielslyngsoe** [comment] 2024-11-26 15:59
Hi @jbrisnehan-AMG and @mjamil4it

Thanks a lot for replying on this, that was really nice of you both. — Please let me know how 15.1 works for you and as well if there is anything that is blocking, then I'll will make sure we look at it soon.

**Comment by jbrisnehan-AMG** [comment] 2024-12-03 17:55
Hmmm...  I'm testing Umbraco version 15.1.0-rc and this still appears to be an issue.

On v15.1.0-rc:
- I'm using Inline Edit mode on the block grid
- I "Add Content" to the bottom of an existing block grid.  It gets added but is greyed out.
- I add an RTE area to the new block.  The block is still greyed out.
- Add some test text to the RTE, save and publish
- My new block content is not visible on the front-end
- If I add a property to the block, then the block is no longer greyed out... save and publish and my content appears on the front-end

**Comment by nielslyngsoe** [comment] 2024-12-04 08:42
Hi @jbrisnehan-AMG

Thanks for returning to this case, I think its a UX issue, please confirm if my assumption is right.
The situation is that Blocks are not exposed(made available on the given variant) when created in Inline Mode, then you would additionally need to click this button: 

https://github.com/user-attachments/assets/03c08678-96e5-4b11-a1ab-87cb80055043

I see that is not optimal, we had thoughts about an auto-expose feature. And this would solve this case, so I've chosen to introduce this now. Here this the PR: https://github.com/umbraco/Umbraco-CMS/pull/17721

This will come in 15.2

**Comment by jbrisnehan-AMG** [comment] 2024-12-04 14:40
When I add a new block the "Add Content" is visible immediately in the area and the block is still greyed out:
![image](https://github.com/user-attachments/assets/bb55e4a2-f897-4022-8a0c-c9548c3360fb)

Then when I click "Add Content" in the area and add an RTE, the block is still greyed out:
![image](https://github.com/user-attachments/assets/f8eacea6-8b3f-4b59-9d42-23c81c4bbf0b)

If I click the "+" on the block at any time, or click the settings on the block and save a setting; then the block is no longer greyed out and will save properly.
If I click the "+" on the block, it doesn't change or do anything in the area (like in your video).  The only thing that happens is the block is no longer greyed out.
