### ISSUE TITLE
Block Editor Label shows code instead of resolving AngularJS values

### ISSUE THREAD

**Issue by TimmiX88** [umbraco/Umbraco-CMS#14474] opened 2023-06-28 10:08 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

When using an AngularJS filter to retrieve data in the label of a Block List item, there is a bug where the [AngularJS filter](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration) is not applied yet, so the label shows the full 'raw' code in the label.

I have a blocklist in which I retrieve a couple values from it's settings and the title field from the blocklist item itself. The label assigned is: 
`{{$settings.hideBlock == 1 ? "[hidden] " : ""}}Text & Image - {{title}}` 

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/50480553/de7c6b4d-9bf6-427a-9b34-0d5fa3f26003)

Within a page with the Blocklist, it shows the raw code label in the headline:
![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/50480553/c4c1b66a-18e7-4aae-a9f7-72567fc91708)

Once you create the blocklist item, the problem is resolved and the label is correct in the blocklist overview and in the popover when editting an item.
![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/50480553/c6044638-9297-46e2-baa9-129fb0824ffd)

So it seems like it either doesn't resolve the AngularJS code at all anymore, or there is some issue to retrieve the correct data or settings before the item is created,

This bug seems to be introduced in 10.5.0, before the hotfix we were on 10.4.2.
I suspect it might be related to this change, but I am not sure: https://github.com/umbraco/Umbraco-CMS/pull/13937

### Specifics

Bug persists in all 3 project we have recently upgraded to 10.5.1 and shows in multiple browsers.

### Steps to reproduce

See screenshots above

- Umbraco 10.5.1 installation
- Create a blocklistitem
- Try to retrieve the value of a field or it's settings in the label
- add the blocklistitem to the available items of a blocklist
- Add this blocklist to a page
- Add this new blocklist item to a page and see that the code is visible in the label
- Create the blocklist item and then edit it, see that the label is now correc.t

### Expected result / actual result

Make sure that the code is not visible in the label/headline.

**Comment by kjac** [comment] 2023-06-29 07:19
Hi @TimmiX88 👋 

Thank you for reporting this, and kudos for the super detailed description and root cause digging efforts 💪 

This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/14105 which has been fixed in https://github.com/umbraco/Umbraco-CMS/pull/14143. The fix will be included in v10.6, which is slated for release on July 6 (see https://our.umbraco.com/download/releases/1060).

**Closed by kjac** 2023-06-29 07:19 UTC
Labels: type/bug

**Comment by TimmiX88** [comment] 2023-06-30 06:52
@kjac Thank you for the quick reply and happy to see it's already fixed and rolling out soon!
