### ISSUE TITLE
PostSave error on most actions (save, publish, move)

### ISSUE THREAD

**Issue by ault** [umbraco/Umbraco-CMS#8625] opened 2020-08-12 09:00 UTC
Azure hosted site (still in dev) generates a PostSave error on most actions that save (eg move, save, publish), however the action has completed successfully (e.g. page has moved, content has saved, node has been published, etc.)

## Umbraco version: 

I am seeing this issue on Umbraco version: 8.6.1

### Bug summary

Azure hosted site (still in dev) generates a PostSave error on most actions that save (eg move, save, publish), however the action has completed successfully (e.g. page has moved, content has saved, node has been published, etc.). This happens on localhost as well. Error also present here: Settings: Examine Management (which is not surprising when you look at the log).

### Specifics

As above, but it is worth mentioning that the site is in 3 languages.
Edge Version 84.0.522.52  (but also occurs in Chrome 84.0.4147.105)

### Steps to reproduce

I cannot get any other site to do this. However, an example is saving some content.

### Expected result

I would expect a normal save action, or to see the contents of Settings: Examine Management
[u861errorlog.txt](https://github.com/umbraco/Umbraco-CMS/files/5061627/u861errorlog.txt)

### Actual result

See attached log report, the Properties are:

Timestamp | 2020-08-12T08:41:51.1931414+00:00
-- | --
@MessageTemplate | Unhandled   controller exception occurred for request '{RequestUrl}'
RequestUrl | https://triland01.azurewebsites.net/umbraco/backoffice/UmbracoApi/Content/PostSave
SourceContext | Umbraco.Web.Editors.ContentController
ProcessId | 8180
ProcessName | w3wp
ThreadId | 41
AppDomainId | 7
AppDomainAppId | LMW3SVC1458146404ROOT
MachineName | RD0003FF76BA25
Log4NetLevel | ERROR
HttpRequestNumber | 19
HttpRequestId | 2d6a58c2-c5cd-4f00-9498-29b6990280a0

**Comment by kjac** [comment] 2020-08-12 14:38
@ault sounds like Examine isn't able to access the Lucene indexes. Did you follow the directions for [hosting Umbraco in Azure](https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps)?

**Comment by ault** [comment] 2020-08-12 18:32
Yup...
      
      <add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />
      <add key="Umbraco.Core.LocalTempStorage" value="EnvironmentTemp" />
      <add key="Umbraco.Examine.LuceneDirectoryFactory" value="Examine.LuceneEngine.Directories.SyncTempEnvDirectoryFactory, Examine" />

**Comment by Shazwazza** [comment] 2020-08-13 08:58
The problem is fixed in 8.6.4. It is the MainDom issue: https://github.com/umbraco/Umbraco-CMS/pull/8398

**Closed by Shazwazza** 2020-08-13 08:58 UTC

**Comment by ault** [comment] 2020-09-20 13:35
@Shazwazza  Odd thing, this was fixed in 8.6.4, but now I am having the same experience with (a new site in) 8.7. Should I open another issue?

**Comment by Shazwazza** [comment] 2020-09-21 05:21
@ault if you have steps to replicate from a vanilla Umbraco install then yes please open a new issue with those steps, stack traces, details, etc... . Thanks!

**Comment by motocombotag** [comment] 2021-04-05 08:32
@ault @Shazwazza I'm having the same issue on my Umbraco site based on v8.6.1. Thanks for the issue and the fix. Can you guys explain how I can upgrade to 8.6.4? I checked Umbraco docs but there's no detailed guide on upgrading a minor version. Thanks for your help in advance!

**Comment by ault** [comment] 2021-04-06 07:52
If you are using Visual Studio, Nuget Package Manager will let you do this easily. If you are not using VS, I have no idea.
