### ISSUE TITLE
Block editor labels showing Angular JS on first load

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco-CMS#14105] opened 2023-04-17 11:45 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

The Block Label of Block Components is displaying Angular JS code rather than result on first load. If opened again the label displays correctly.

https://user-images.githubusercontent.com/22817718/232474714-0aee79c4-28fd-4d93-91a1-00391b502502.mp4

### Steps to reproduce

Guide on creating an Angular JS label can be found here:

https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration

---
_This item has been added to our backlog [AB#28759](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/28759)_

**Comment by elit0451** [comment] 2023-04-18 06:51
Hi @marcloveUSN 👋 

Thanks for reporting this! Seems like the problem was caused by https://github.com/umbraco/Umbraco-CMS/pull/13937 while trying to fix another issue with the Block editor label. I will mark it as up for grabs to see if anyone wants to give it a go 🙂

**Comment by Jalinco1** [comment] 2023-06-17 20:13
Any updates on this problem? still an issue in 11.4.0

**Comment by iOvergaard** [comment] 2023-06-21 06:35
> Any updates on this problem? still an issue in 11.4.0

Hello @Jalinco1 
Investigating this has turned out that some thing went wrong and we didn't get this fix into 11.4.0 after all. We have retagged the pull request with the fix for 11.4.1 which will be released tomorrow most likely. We are very sorry for the inconvenience.

**Closed** 2023-06-21 06:37 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/frontend, affected/v10, affected/v11

**Comment by DanDiplo** [comment] 2023-06-26 11:47
@iOvergaard Will this be merged into the latest 10.x LTS version, too, as it's also present there? Whilst it doesn't effect functionality, it does look really ugly and results in clients flagging what they think is a bug... Thanks!

![image](https://github.com/umbraco/Umbraco-CMS/assets/6676168/7996e0da-ecbe-494b-9a31-c1afc7984667)
