### ISSUE TITLE
RTE Property in custom backoffice view

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco-CMS#15474] opened 2023-12-18 14:45 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.1

### Bug summary

Hi,
We are upgrading an Umbraco 10 website to Umbraco 13 - We are facing some issues with the updated RTE, and only the RTE field.

The config for the RTE is the following,

```
thankYouText = {
    alias: 'thankYouText',
    editor: 'Umbraco.TinyMCE',
    label: 'Thank you text',
    hideLabel: false,
    description: '',
    view: 'rte',
    value: vm.model.data.thankYouText,
}
```

But we are getting an error in the console, Could not find umbVariantContent in the $scope chain

How should we "inject" this into our custom backoffice view?

### Steps to reproduce

Try to upgrade a website with a custom backoffice view which contains an RTE

### Expected result / actual result

A working RTE

**Comment by nielslyngsoe** [comment] 2024-01-05 10:05
Hi @AndersBrohus

Thanks for reporting this issue, I see the problem and I understand why you still want to be able to do this.

The problem originates in the implementation of Blocks, as the editing of Blocks works as a sub editor, giving us more requirements for the implementation of the Rich Text Editor.

That though does not make your use case less valuable, so sorry for the inconvenience.

I think your description is good, but it does not clarify enough for me to verify if this idea could be a solution to the problem, so please help me verify your needs:

I will suggest loosening the implementation requirements, to what was required before. With the down side of Blocks not being supported when only the minimal implementation is provided. In other words, you will be able to use the Rich Text Editor in your custom view again. But not insert Blocks into that Rich Text Editor.

The background for such begin that I think it would be a tough job for you to implement implement the new requirements correctly.

How does that sound?

Also, on a side note, and of personal interest. Could you describe a bit more of the use case of your custom view. What it is and what its used for.

Thanks in return

**Comment by AndersBrohus** [comment] 2024-01-08 07:49
Hi @nielslyngsoe 

That sounds like a great idea :)
We are interested in a simple TinyMCE for the editor to create an HTML string :)

On this specific case, we have a custom section where you can edit data from a custom database, but in a Umbraco like experience, this data has nothing to do with Umbraco, but is a part of the website :)

**Comment by abjerner** [comment] 2024-01-08 08:23
Just for reference, this also affects my [**Tables**](https://github.com/limbo-works/Limbo.Umbraco.Tables) package, so for now I'm unable to update the package to target Umbraco 13.

Unless I've missed Umbraco declaring this a breaking change for Umbraco 13, I'm seeing this a regression issue because `umbVariantContent` is now required in order to use the build-in RTE property editor in custom views.

Updating the build-in RTE property editor to not require `umbVariantContent`, but then not support nested blocks if `umbVariantContent` isn't available, will be an acceptable solution in my case 👍

**Comment by leekelleher** [comment] 2024-01-08 08:43
FYI (for the context in this discussion), I hit the same issue with Contentment (using the RTE in the data-type configuration, for the Notes editor). But because I didn't catch it early enough, Umbraco 13 had already been released so I ended up rolling my own custom RTE; ref: https://github.com/leekelleher/umbraco-contentment/pull/371/commits/c4926c257195a3e4a4f4d7d85baf496bde6f967a#diff-fd57691c707aae91e655d7b48b4c937f4341a51c3e8bb619bc283172b4500893

**Comment by Zeegaan** [comment] 2024-01-10 13:53
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15556 🚀

**Closed by Zeegaan** 2024-01-10 13:53 UTC
Labels: type/bug, area/frontend, affected/v13, release/13.1.0

**Comment by marcemarc** [comment] 2024-02-05 11:45
Thanking all! - this just saved the day! - in terms of use case, on this site being migrated to v13, the editing experience is extended beyond that of updating content on the website, to contain custom dashboards to manage content change requests made on the front end by members of the association, so the implementation uses an RTE to show the HTML changes requested and enable the site administrator to tweak the HTML and then Approve / Reject changes

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/2327c5fb-5b6f-4775-9d82-0b9ea7b14f41)

This was all built in the V7 days before Plumber and Umbraco UI Builder.

It doesn't need to be the same implementation as the backoffice RTE, (particularly as this evolves) but it really helps extend Umbraco if there are a bunch of common components you can just use without faff to build up your dashboards and sections.

**Comment by umbracocommunity** [comment] 2025-07-01 08:21
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/adding-rich-text-editors-to-custom-dashboards/4287/3
