### ISSUE TITLE
Updating from 8.0.2 to 8.1, moment.min.js reporting deprecation warning

### ISSUE THREAD

**Issue by DMCK96** [umbraco/Umbraco-CMS#5968] opened 2019-07-21 19:32 UTC
Date picker in back office has stopped working after upgrading from 8.0.2 to 8.1.

### Specifics

This warning appears in the console when selecting a date in the backoffice. Save & Publish clears the field and trying to access field in view returns DateTime.MinValue. 

`moment.min.js?cdv=126457885:formatted:134 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 21-07-2019, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:3000/umbraco/lib/moment/moment.min.js?cdv=126457885:1:3368)
    at Yt (http://localhost:3000/umbraco/lib/moment/moment.min.js?cdv=126457885:1:21353)
    at Ot (http://localhost:3000/umbraco/lib/moment/moment.min.js?cdv=126457885:1:22064)
    at Tt (http://localhost:3000/umbraco/lib/moment/moment.min.js?cdv=126457885:1:22146)
    at c (http://localhost:3000/umbraco/lib/moment/moment.min.js?cdv=126457885:1:209)
    at setDate (http://localhost:3000/umbraco/js/umbraco.controllers.js?cdv=126457885:15515:30)
    at ChildScope.$scope.inputChanged (http://localhost:3000/umbraco/js/umbraco.controllers.js?cdv=126457885:15497:13)
    at fn (eval at compile (http://localhost:3000/umbraco/lib/angular/angular.js?cdv=126457885:16387:15), <anonymous>:4:156)
    at callback (http://localhost:3000/umbraco/lib/angular/angular.js?cdv=126457885:28815:13)
    at ChildScope.$eval (http://localhost:3000/umbraco/lib/angular/angular.js?cdv=126457885:19356:28)`

**Comment by DMCK96** [comment] 2019-07-21 19:47
Updating Moment.Min.Js to latest version from their website resolved the issues in the backoffice, but the deprecation warning is still appearing.

**Comment by nul800sebastiaan** [comment] 2019-07-23 11:37
Works perfectly here, both when I add it as a datatype or when I use scheduled publishing. Are you sure you've bumped the version in your ClientDependency.config while upgrading?

I'll close this issue for now, if you have reproduction steps that work on a fresh install of 8.1.0 then I'm all ears! No idea where this error might be coming from for you.

**Comment by stevemegson** [comment] 2019-07-24 13:11
I think the steps to reproduce this are:
- Configure the date picker with a non-default format, in this case DD-MM-YYYY.
- Open the picker by clicking in the text box, rather than on the button next to it.
- After picking a date, move focus to another property.
- On blur, moment will be asked to parse the value that's in the text box, triggering the warning.
- If your browser can't parse the formatted value, for example if it tries to parse DD-MM-YYYY as MM-DD-YYYY, the field will be left empty.

I think I have a fix for this, though I haven't had chance to test it properly yet.

The other way to trigger the warning is just to type something like '24 Jul 2019' in the text box. This isn't really a problem, since in practice your browser will parse it OK (unless you've typed something very odd that we're probably not interested in supporting).

However, if and when we update to a version of moment which removes the fallback behaviour, any users who are used to typing '24 Jul 2019' won't be able to. We could deliberately opt in to the fallback parsing when dealing with user-entered values, removing the warning and the risk of a future change in behaviour.

**Comment by nul800sebastiaan** [comment] 2020-01-10 08:35
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6001

**Closed by nul800sebastiaan** 2020-01-10 08:35 UTC
Labels: community/pr, release/8.6.0, type/bug
