### ISSUE TITLE
V8: Import/export dictionary items for translation

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3524] opened 2018-11-07 07:30 UTC
It would be really nice to have a built-in way of exporting and importing the dictionary for specified languages. This could be super useful for sending the dictionary to a translation agency or similar.

Something along these lines, maybe:

![dictionary import export poc](https://user-images.githubusercontent.com/7405322/48116714-3d22cd80-e267-11e8-986b-e518798a3e31.gif)

I'd be happy to implement the feature 😉

**Comment by kjac** [comment] 2018-11-21 07:55
@nul800sebastiaan I really don't think it's got any implications on Courier/Deploy. This isn't a deployment feature for developers - it's a translation feature for editors. 

Besides, uSync already handles dictionary deployment pretty well 😉

**Comment by nul800sebastiaan** [comment] 2018-12-19 10:38
@kjac When importing new translations we still need to trigger the events that Courier and Deploy use, otherwise the new translations will not be serialized and transferred to the next environment.

If you trigger a save event for each dictionary item being imported, then all will be good! 👍

**Comment by Flaeng** [comment] 2019-04-25 13:58
It know its not 100% like in the original posts gif, but i think i got the functionality down. If you guys have any feedback at this point please let me know.

I hope to have fixed the last few bugs and make a PR in the coming week.

@nul800sebastiaan 
Should the import and export-actions implement Umbraco.Web.Actions.IAction ?

Branch:
https://github.com/Flaeng/Umbraco-CMS/commits/temp-3524

Preview:
![import-eksport-translations](https://user-images.githubusercontent.com/6176282/56740872-0cc9df80-6772-11e9-9210-40352c267ce0.gif)

**Comment by kjac** [comment] 2019-04-25 14:04
@Flaeng that's awesome 🎆 

How does it determine which language you're importing?

**Comment by nul800sebastiaan** [comment] 2019-04-25 14:21
Looks pretty good! 

I don't have answers on where to implement this at the moment but some initial feedback on the import: can we have just 1 format (namely: the format we exported as). I wouldn't expect anyone to know the difference between ANSI and ISSO-8859 ... Maybe this can be detected, but then again.. it should not be a choice at all really. I doubt that CSV is the best export format, but I'm not sure how people "normally" translate stuff. I would much much prefer JSON so we don't have to deal with issues for separators (nor encoding, I guess).

I am assuming "Override" means: overwrite all existing values?

**Comment by dawoe** [comment] 2019-04-25 14:34
A common format used by translation tools is XLIFF..so if we should settle on a format I think this should be it : https://en.wikipedia.org/wiki/XLIFF

Dave

**Comment by Flaeng** [comment] 2019-04-25 19:02
@kjac 
as of now its does so based on the first row which contains the "culturename" of the language... come to think of it it should be the 4-culture code instead i think. this way editors can use the automatic translator in google docs so they only have to proff read the translations. 

@nul800sebastiaan 
Youre right. the options are a bit too technical. if it should only import/export in one encoding, which should that be? which encoding contains all characters used in the nordic countries, asia, arabia?
i havent read anywhere that anyone uses json when translating texts manually (i could be wrong). i think csv would work great for translators that dont do it professionally as they can do it in excel or something like that.

yes, override means override non-empty translations. if f.x a dictionaryitem has a translation already and there is another translation in the imported file, the state of the checkbox decide if we keep the string from the file or the one already in the dictionary.

@dawoe 
i agree that at some point xliff-support should be implemented, but i also think an simple option should be available. 

Sorry for the poor formatting and capatilization. im on holidays with a new tablet

**Comment by Shazwazza** [comment] 2019-04-29 03:34
@simonech might have some input on this since he is the king of xliff and translations plus in know he was working on a translation tool for that in umbraco already.

**Comment by simonech** [comment] 2019-04-30 15:16
@Shazwazza @dawoe Indeed... that's the only "official" standard for translation requests 
I'll show a demo of what I'm doing at CG19... now sure when and how, but I guess I can do it during the package demo or during a open space during the last day.
@Shazwazza, what do you think would work better?

**Comment by Shazwazza** [comment] 2019-05-01 00:08
@simonech both if you can do it, if people are interested in the open space session then there will be plenty of folks to help and discuss

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:34
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:34 UTC
Labels: community/up-for-grabs, help wanted, type/feature
