### ISSUE TITLE
V7: Culture and Hostname is ignored when occupied by thrashed item

### ISSUE THREAD

**Issue by andersbrohall** [umbraco/Umbraco-CMS#5265] opened 2019-04-15 07:36 UTC
When setting a Culture and Hostname to a string that is already in use, but located in the Recycle bin, the value is not saved. Nor do you get a message about it being in use. 

Reproduction
------------
Set a hostname on any published node.
Reload, and check the Info tab. 
Delete the node.
Set the same hostname on any published node. 
Reload, and check the Info tab. 

Been there since forever, but also applies for 7.14.0

### Bug summary
The lack of information about the trigger being halted when saving confuses the user. Apart from that, I would assume that a thrashed node shouldn't block a Hostname. 

How about a condition in the save method that checks if the matched string is used in a recycled item, and if so - remove the old one?

Also, of course, a message about the system not being abele to save the ned Hostname would be great. Also applies when the Hostname is used on a published node.

**Comment by nul800sebastiaan** [comment] 2019-05-01 14:40
Yep, it would be great to improve the behavior here! 

Some background info: we really want to keep the hostnames configured on items in the trash as you might have accidentally put them there. If we were to delete the hostnames when you trash and item you'd never know that restoring them doesn't restore the hostnames/cultures.

But it could be really good when you're trying to add a new hostname that already exists on another node to give clear visual feedback saying something like: can't add because it already exists on node "bla" (and show where in the tree node "bla" is, for example: "home/contact/bla" or "recycle bin/home/contact/bla".

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-08-29 19:12
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-08-29 19:12 UTC
Labels: community/up-for-grabs, help wanted, type/feature
