### ISSUE TITLE
Changing document type template makes the document type unusable.

### ISSUE THREAD

**Issue by Luksor** [umbraco/Umbraco-CMS#6006] opened 2019-07-26 14:55 UTC
Whenever I change a default template in a document type Umbraco is no longer able to find it and render the content properly.

![image](https://user-images.githubusercontent.com/5837521/61959979-7c8f7680-afbc-11e9-9556-d29898f2253e.png)

![image](https://user-images.githubusercontent.com/5837521/61960011-903add00-afbc-11e9-9d52-174363a6070e.png)

Reproduction
------------

### Bug summary

Changing the default template produces 404 when rendering content and causes the backoffice to throw a 404 error when trying to open the template from the Content Info tab.

### Specifics

* Tested on Umbraco 8.1.0

### Steps to reproduce

* Create a new document type
* Create a content item using this document type
* Create a new template
* Change the default template in the document type to the newly created one and remove the old one
* Try accessing the page / Opening the template from the content info page.

### Expected result

The page should render using the new template.

### Actual result

The page is returning a 404 error.

**Comment by kjac** [comment] 2019-07-27 05:57
Uh ouh that doesn't sound good. Thanks for reporting 👍 I'll have a look later today.

**Comment by kjac** [comment] 2019-07-27 10:40
I can reproduce this if I delete the old template entirely, not just remove it from the document type templates. Was that also what you meant @Luksor?

The way I see this issue it's divided into two:

#### Rendering the page in frontend returns 404

This is not a bug, it's a feature 😄 

When you delete a template that is used by content, Umbraco can't automatically assign a new template to that content. You need to do so by hand. If Umbraco just went ahead and chose another template than the one that was originally assigned, the site might end up rendering things you didn't mean to render. So it's better to return a 404 in this case.

_Side note: If a template is in use, perhaps we shouldn't let the users delete it. However that's an entirely different issue._

#### The info tab in the back office

When you delete a template or remove it from the allowed templates on the document type, the "Open" will still open that template in infinite editing: 

- If the template is deleted entirely you'll get the back office error as you have pasted above. 
- If the template has just been removed from the allowed templates, the template will still open in infinite editing.

Both of the above are errors that needs fixing. I will get on that now.

**Comment by stevemegson** [comment] 2019-07-27 11:32
As well as the info tab on content, there also seems to be an issue editing a document type after deleting one of the allowed templates, giving the same 404 error. This is a problem because you now can't edit the document type to remove the template that's causing the error. This may be a caching issue, since I can't reproduce it reliably.

**Comment by kjac** [comment] 2019-07-27 19:22
Thanks @stevemegson, I'll have a look into that too 👍 

The original issue is in part solved by #6008. There is still a bit of funky stuff going on that needs fixing for things to work smoothly, but #6008 is at least part of the solution. I'll get back when I have the rest nailed.

**Comment by kjac** [comment] 2019-07-27 19:42
@stevemegson I can't really figure out how to crash the document type editor. Could you dig into steps to recreate?

That being said there certainly is a caching issue going on:

![image](https://user-images.githubusercontent.com/7405322/61998915-26ebc480-b0b7-11e9-90b9-f491f304ebb0.png)

...and the same after restarting the site:

![image](https://user-images.githubusercontent.com/7405322/61998928-58fd2680-b0b7-11e9-8aef-bc396c34f59a.png)

**Comment by stevemegson** [comment] 2019-07-28 17:04
@kjac I can't crash the document type editor now either. I'm not sure what I was doing before, but let's assume I imagined it unless anyone else reports otherwise.

**Comment by kjac** [comment] 2019-07-29 06:41
@stevemegson thanks for verifying. I have submitted a fix (#6012) that refreshes the content type cache when a template is deleted.

**Comment by nul800sebastiaan** [comment] 2019-08-09 14:56
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6008 and https://github.com/umbraco/Umbraco-CMS/pull/6012

**Closed** 2019-08-09 14:56 UTC
Labels: community/pr, type/bug
