### ISSUE TITLE
Backoffice listview displays everything as published in 7.13.1

### ISSUE THREAD

**Issue by bmargevicius** [umbraco/Umbraco-CMS#4104] opened 2019-01-16 20:47 UTC
Upgrade Umbraco from 7.12.4 to 7.13.1

In the backoffice, on a (custom) listview. When we publish to azure using the "release" profile items that are unpublished appear to be published (black font). If in debug, everything looks correct: published items are black, unpublished are greyed out.

Flipping debug=true/false in web.config does the same thing.
Inspecting the listview table elements in the backoffice you see a difference in the files loaded.
Release mode creates dependencyhandler.axd, debug mode uses umbraco.css.

Something is missing in build of the bundler on release.

**Comment by dawoe** [comment] 2019-01-17 07:40
Hi @bmargevicius 

As I think it works in debug mode. I think the problem is your client dependency cache.

Have you tried updating the version number of clientdepency in the config file and cleared your browser cache ?

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by stevemegson** [comment] 2019-01-17 10:54
This should be fixed by issue #4016. It's really a bug in ClientDependency, which changes the meaning of some CSS rules when minifying umbraco.css, but the CSS can be rewritten to avoid triggering the bug.

**Comment by nul800sebastiaan** [comment] 2019-01-17 11:17
Yep, should be fixed in #4016 👍

**Closed by nul800sebastiaan** 2019-01-17 11:17 UTC
