### ISSUE TITLE
Improvement on multilingual Nested Content in Umbraco 8

### ISSUE THREAD

**Issue by ragivi** [umbraco/Umbraco-CMS#5532] opened 2019-05-28 10:29 UTC
There are some situations when you only have one multilingual property in a Nested Content with a lot of properties that they aren't. In this case you have to fill all properties (although the values are the same) because not exists an interface of multilingual properties inside a Nested Content.

**Comment by nul800sebastiaan** [comment] 2019-05-31 13:24
Hey @ragivi - I'm not sure what you mean here. Can you give an example? Maybe you can add some screenshots to visualize a little bit better to give us an idea what you're working with?

**Comment by nul800sebastiaan** [comment] 2019-05-31 13:55
Ah, is this basically what you want to achieve @ragivi ? https://github.com/umbraco/Umbraco-CMS/issues/5551

**Comment by ragivi** [comment] 2019-06-03 09:55
Hi @nul800sebastiaan 

No exactly but it's a very interesting feature! :)

I mean that within a nested content we can have 10 properties and only one of them is multilanguage (for example, a property with the name of a room and other 9 properties like its capacity, whether or not it has wifi, etc.). )

I think that the interface is not implemented so that a Nested Content has multilanguage properties, but what may or may not be multilanguage is the entire nested content.

**Comment by Migaroez** [comment] 2019-08-13 14:00
I think I know what @ragivi is talking about. And I will try explain this with some gifs.

No Variance
![NC No variance](https://user-images.githubusercontent.com/6025797/62947634-29525c00-bde3-11e9-83d9-ced6ddf562f7.gif)

Activating full variance => Nested content items are lost, need to reenter everything
![NC Full variance](https://user-images.githubusercontent.com/6025797/62947681-3cfdc280-bde3-11e9-865a-9648a2b0b23c.gif)

Disable full variance, enable variance on NC => Existing items cant be adjusted
![NC Partial variance](https://user-images.githubusercontent.com/6025797/62947722-50a92900-bde3-11e9-8a95-a60e5cc47c66.gif)

Expected result with nested content variance enabled
![image](https://user-images.githubusercontent.com/6025797/62947618-22c3e480-bde3-11e9-8ac1-4f2bbbbce425.png)

Hope this makes sence

**Comment by nul800sebastiaan** [comment] 2019-08-13 14:53
Thanks all! I understand the issue now and I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/5817 - we'll fix it soon! 👍

**Closed by nul800sebastiaan** 2019-08-13 14:53 UTC

**Comment by evry-johan** [comment] 2020-09-22 23:19
@nul800sebastiaan https://github.com/umbraco/Umbraco-CMS/issues/5817 does not address this issue. Is there still no way to have a subset of the nested content fields multilingual?

**Comment by sotirisf** [comment] 2020-10-06 10:50
I can verify that this does not have to do with #5817 and that it's still a problem in 8.4 (probably later versions as well) where I was requested to have an image picker as invariant within a nested content element. I've got a nested content datatype that allows me to define images as well as literals, and the client needed the images to be invariant so that they won't have to set them up for every language (they need to use the same image in every language, just change the literals).

What we need there is a way for a variant nested content element to have some of its properties defined as invariant. Of course, this presents a challenge since having even a single property defined as invariant would mean that nested content would have to inherit all elements from the main language, but allow us to change variant properties. 

Currently it's either variant or invariant as a whole - meaning that either you get a variant NC property which allows you to define different elements for each language, or an invariant one that inherits all elements from the main language. There is no "variant NC with invariant properties" approach at all.

**Comment by ronaldbarendse** [comment] 2020-10-06 11:53
This can't be fixed without completely rewriting the way element types are stored, as currently all data is stored as JSON in a single property. There's a RFC to change this, but the feature to keep variants in sync is explicitly stated as being out of scope: https://github.com/umbraco/rfcs/pull/24.

**Comment by evry-johan** [comment] 2020-10-06 12:23
@ronaldbarendse Isn't that the case for V7 as well? The Vorto plugin seems to handle it well there.

**Comment by ronaldbarendse** [comment] 2020-10-06 14:51
@evry-johan Vorto wraps other data types and stores all culture variant data in a single property, Umbraco 8 stores culture variant property data as seperate rows in the database and only allows switching cultures on the whole document (all properties at the same time).

**Comment by evry-johan** [comment] 2020-10-07 08:41
Thanks for the info. I'm sticking to V7, copy-pasting content is just not an option in my book :/
