### ISSUE TITLE
No actions for selected media in media collection

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#17556] opened 2024-11-17 01:07 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

When selecting something in the media collection view there are no actions available. 

It would be very nice to be able perform at least these actions for selected media:
* Delete
* Move

![image](https://github.com/user-attachments/assets/04f863dc-86fb-4291-a1a9-9c74d2a58496)

### Steps to reproduce

Se above

**Comment by NguyenThuyLan** [comment] 2024-11-20 06:56
This issue needs to be fixed. Thank you @enkelmedia

**Comment by madsrasmussen** [comment] 2024-11-21 07:52
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/17324

**Comment by madsrasmussen** [comment] 2024-11-21 09:57
🤦 Sorry I referenced the wrong issue. Multi-tasking is hard. 

Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16272

**Comment by madsrasmussen** [comment] 2024-11-21 09:58
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16272

**Closed by madsrasmussen** 2024-11-21 09:58 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v14, affected/v15
