### ISSUE TITLE
Logs filled with NullReferenceException in "DocumentRepository.IsPathPublished"

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#13818] opened 2023-02-10 11:12 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.12.2

### Bug summary

Since about a week our logs are filled with the same error from _DocumentRepository.IsPathPublished(IContent content)_. 

Here is the complete StackTrace from the logs:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.IsPathPublished(IContent content) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 890
   at Umbraco.Core.Services.Implement.ContentService.IsPathPublished(IContent content) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 749
   at Umbraco.Core.Services.Implement.ContentService.StrategyCanPublish(IScope scope, IContent content, Boolean checkPath, IReadOnlyList`1 culturesPublishing, IReadOnlyCollection`1 culturesUnpublishing, EventMessages evtMsgs, ContentSavingEventArgs savingEventArgs, IReadOnlyCollection`1 allLangs) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 2731
   at Umbraco.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, ContentSavingEventArgs saveEventArgs, IReadOnlyCollection`1 allLangs, Int32 userId, Boolean raiseEvents, Boolean branchOne, Boolean branchRoot) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1151
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublishingExpiration(DateTime date, List`1 results, EventMessages evtMsgs, Lazy`1 allLangs) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1416
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1373
   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\a\1\s\src\Umbraco.Web\Scheduling\ScheduledPublishing.cs:line 68`

### Specifics

Here is a screenshot of the complete log entry:
![image](https://user-images.githubusercontent.com/25620488/218077520-7f8eeead-6560-4a80-a6a2-e66f66e2fba1.png)

### Steps to reproduce

There are no steps to reproduce, just that the logs is filled with this error. As of now it looks like this started happening at random. So it doens't seem like it's the result of a new release/changes.

**Comment by kjac** [comment] 2023-02-12 09:42
Hi @JeroenRoos,

I can see how that's really annoying 😞 

We don't really have a whole lot to go on here. If you didn't deploy any changes to provoke this, logic dictates that this must be caused by some editorial change. The stack trace points us at scheduled publishing, possibly somehow attempting to work on a null reference content or a piece of content that has no path - none of which should be possible (code [here](https://github.com/umbraco/Umbraco-CMS/blob/v8/8.12/src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs#L890)).

There are a few things you can try, to figure out what's going on here:

1. Copy the DB and setup a new vanilla Umbraco 8.12.2 site pointing at the DB copy. If this fixes the problem, you'll know that something in your site implementation is causing it.
2. If the problem persists on the vanilla 8.12.2, try upgrading the site to the latest V8 and see if that has an impact. Perhaps this is a known bug that has been fixed.
3. Look for suspicious content that could cause the scheduler to fail like this. I haven't got a whole lot of concrete ideas other than perhaps look for trashed content that is scheduled to be published. I hope you'll think of other things to look for in your concrete implementation.

**Comment by kjac** [comment] 2023-02-24 06:05
Hi @JeroenRoos,

Thanks for the update 😄 

The content version cleanup should definitively not remove the latest version of any content item, published or unpublished. Mind you, a content item exists in up to two "current" versions - the published one and the draft one. The draft one may contain different data from the published one. If content version cleanup were to delete the draft versions, important data would potentially be lost.

See more [in the docs](https://docs.umbraco.com/umbraco-cms/fundamentals/data/content-version-cleanup) 👍

**Comment by elit0451** [comment] 2023-03-14 09:41
Hi @JeroenRoos 👋 
It seems like your issue hasn't returned yet, so I will go ahead and close this one but do reopen it if you manage to come up with some reproduction steps 🙂

**Closed by elit0451** 2023-03-14 09:41 UTC
Labels: state/needs-more-info, state/needs-reproduction, type/bug
