### ISSUE TITLE
Conflict between `Umbraco:CMS:Plugins` and `Umbraco:CMS:RichTextEditor:Plugins`

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#12925] opened 2022-08-30 13:32 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

When defining `Plugins` in `Umbraco:CMS:RichTextEditor:Plugins` it seems to be conflicting with `Umbraco:CMS:Plugins` as I get an warning.

Intellisense says value must be a `string` for `Umbraco:CMS:RichTextEditor:Plugins`

![image](https://user-images.githubusercontent.com/2919859/187449464-6c97f0b3-f5dc-44f3-b987-521585aa7aee.png)

when defined as string it warns at `Umbraco:CMS` that `Umbraco/CMS/RichTextEditor/Plugins` must be either type of `null` or `array`.

![image](https://user-images.githubusercontent.com/2919859/187449557-8ee05783-20fa-47ee-8cf0-a76a6c2bf870.png)

When using intellisense it suggests two options for value: string or array.

![image](https://user-images.githubusercontent.com/2919859/187450155-05d49972-0236-4dc8-bcec-0a9597c85f86.png)

### Steps to reproduce

Try add a plugin to `Umbraco:CMS:RichTextEditor:Plugins` in appsettings.json

I get the same warning when using `fullscreen` plugin as added here: https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI/appsettings.Development.template.json#L45-L55

**Comment by PerplexDaniel** [comment] 2022-08-31 11:56
Related: #12916

**Comment by jannikanker** [comment] 2022-09-01 06:55
Funnily enough we are not getting the same error messages, but I guess that may just be down to which editor is being used. I created the #12916 issue which I'd say isn't just related, it's the exact same problem :-) But it looks like Bjarne is gettings somewhat more informative warnnings and have gotten closer to the core of the problem than I managed, so if we want to close one of the two, close "mine".

**Comment by nul800sebastiaan** [comment] 2022-09-01 13:31
👍 I'll close as duplicate of https://github.com/umbraco/Umbraco-CMS/issues/12916

**Closed by nul800sebastiaan** 2022-09-01 13:31 UTC
Labels: type/bug
