### ISSUE TITLE
V15-RC getting notification popup twice. 

### ISSUE THREAD

**Issue by harikrishna43** [umbraco/Umbraco-CMS#17252] opened 2024-10-11 18:54 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15-RC

### Bug summary

I am getting notifications twice when I create new document types.
I have created document types with Template. and I am assuming that it must be showing 2, 
1. Create Document type
2. when creating the template

It should specify the text of the badge/notification for a particular event. Something like Created document type and created template. or only show once when both are created.

![image](https://github.com/user-attachments/assets/cf829825-9df6-4b97-80ad-5d75089def65)

### Specifics

Creating new document types

### Steps to reproduce

create a new document type and click on the save button.

**Comment by iOvergaard** [comment] 2024-10-14 07:26
Hello, and thanks for reporting. I would say this is a duplicate of #16092, so I will go ahead and close this issue. Feel free to reopen if you feel there is more to it!

**Closed by iOvergaard** 2024-10-14 07:26 UTC
Labels: type/bug
