### ISSUE TITLE
Explicit Migration step with PK constraint breaking at runtime with SQLlite

### ISSUE THREAD

**Issue by giuunit** [umbraco/Umbraco-CMS#13728] opened 2023-01-24 15:15 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

It is currently not possible to create a custom table in Umbraco V11 with a primary key constraint while using SQLlite using MigrationBase, INotificationHandler<UmbracoApplicationStartingNotification> and the ICreateBuilder. 

### Specifics

The issue is triggered using both VS debugging and the 'dotnet run' command. I used VS 2022 Enterprise Edition on Windows 10 Enterprise. Because we are using explicit migration, it might be related to this issue: https://github.com/umbraco/Umbraco-CMS/issues/12506
```

public class CreateTableWithConstraint : MigrationBase
{
    protected readonly string tableName = "MyTable";

    public CreateTableWithConstraint(IMigrationContext context) : base(context)
    {
    }

    protected override void Migrate()
    {
        if (!TableExists(tableName))
        {
            Create.Table(tableName)
                .WithColumn("Id").AsInt16().NotNullable()
                .WithColumn("LastNumber").AsInt16().NotNullable()
                .Do();

            Create.PrimaryKey("PK_" + tableName)
                    .OnTable(tableName)
                    .Columns(new[] { "Id" })
                    .Do();
        }
    }
}
```

```
public class NotificationMigration : INotificationHandler<UmbracoApplicationStartingNotification>
{
    private readonly IKeyValueService _keyValueService;
    private readonly IMigrationPlanExecutor _migrationPlanExecutor;
    private readonly ICoreScopeProvider _coreScopeProvider;

    public NotificationMigration(
        IKeyValueService keyValueService,
        IMigrationPlanExecutor migrationPlanExecutor,
        ICoreScopeProvider coreScopeProvider)
    {
        _keyValueService = keyValueService;
        _migrationPlanExecutor = migrationPlanExecutor;
        _coreScopeProvider = coreScopeProvider;
    }

    public void Handle(UmbracoApplicationStartingNotification notification)
    {
        // Create a migration plan for a specific project/feature
        // We can then track that latest migration state/step for this project/feature
        var migrationPlan = new MigrationPlan("CreateTableWithConstraint");

        // This is the steps we need to take
        // Each step in the migration adds a unique value
        migrationPlan.From(string.Empty)
            .To<CreateTableWithConstraint>("test-migration");

        // Go and upgrade our site (Will check if it needs to do the work or not)
        // Based on the current/latest step
        var upgrader = new Upgrader(migrationPlan);
        upgrader.Execute(
            _migrationPlanExecutor,
            _coreScopeProvider,
            _keyValueService);
    }
}
```

```
public static class MigrationExtensions
{
    public static IUmbracoBuilder AddMigrations(this IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<UmbracoApplicationStartingNotification, NotificationMigration>();

        return builder;
    }
}
```

```
/// <summary>
/// Configures the services.
/// </summary>
/// <param name="services">The services.</param>
/// <remarks>
/// This method gets called by the runtime. Use this method to add services to the container.
/// For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940.
/// </remarks>
public void ConfigureServices(IServiceCollection services)
{
	services.AddUmbraco(_env, _config)
		.AddBackOffice()
		.AddWebsite()
		.AddComposers()
		.AddMigrations()
		.Build();
}
```

### Steps to reproduce

1. Create a clean instance of Umbraco 11 connected to SQLlite
2. Add the code to add a custom table with a PK constraint (see code or project in zip file)
3. Rebuild and run the website

### Expected result / actual result

Expected result: the custom table is added to the SQLlite database with the primary key.

Actual result: 

![bug](https://user-images.githubusercontent.com/16306379/214331087-935d0b0d-7971-4dd1-ac63-0009335b1e6a.PNG)

Logs: 
`
{"@t":"2023-01-24T15:07:57.7421765Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near \"CONSTRAINT\": syntax error'.\r\n   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)\r\n   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()\r\n   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()\r\n   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()\r\n   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()\r\n   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()\r\n   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 281\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()\r\n   at NPoco.Database.<>c__DisplayClass296_0.<ExecuteNonQueryHelper>b__0()\r\n   at NPoco.Database.ExecutionHook[T](Func`1 action)\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)\r\n   at NPoco.Database.Execute(Sql Sql)\r\n   at NPoco.Database.Execute(String sql, Object[] args)\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationExpressionBase.ExecuteStatement(StringBuilder stmtBuilder)\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationExpressionBase.Execute()\r\n   at Umbraco.Cms.Infrastructure.Migrations.Expressions.Common.ExecutableBuilder.Do()\r\n   at TestMigrationStep.Web.MigrationSteps.CreateTableWithConstraint.Migrate() in C:\\source\\TestMigrationStep\\TestMigrationStep\\TestMigrationStep.Web\\MigrationSteps\\CreateTableWithConstraint.cs:line 22\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.Execute(MigrationPlan plan, String fromState)\r\n   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, ICoreScopeProvider scopeProvider, IKeyValueService keyValueService)\r\n   at TestMigrationStep.Web.MigrationSteps.NotificationMigration.Handle(UmbracoApplicationStartingNotification notification) in C:\\source\\TestMigrationStep\\TestMigrationStep\\TestMigrationStep.Web\\MigrationSteps\\NotificationMigration.cs:line 41\r\n   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)\r\n   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)","InstanceId":"0ef0b40e","SourceContext":"Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase","ProcessId":6292,"ProcessName":"iisexpress","ThreadId":1,"ApplicationId":"9f353ebba16aee4e76a637ad5f0b0f4caceadb5f","MachineName":"CIS2108096","Log4NetLevel":"ERROR"}`

[TestMigrationStep.zip](https://github.com/umbraco/Umbraco-CMS/files/10491324/TestMigrationStep.zip)

**Comment by giuunit** [comment] 2023-01-24 15:33
This might be related: https://stackoverflow.com/questions/25069864/sqlite3sqlexception-near-constraint-syntax-error

**Comment by Zeegaan** [comment] 2023-01-25 09:43
Thanks for reporting @giuunit, I can definelty reproduce this!

**Comment by Zeegaan** [comment] 2023-01-25 09:48
And just as a workaround for you or anyone else who might run into the issue before it gets fixed, you can do it with DTOs like so: 

Dto class:

```
using NPoco;
using Umbraco.Cms.Infrastructure.Persistence.DatabaseAnnotations;

[TableName("BlogComments")]
[PrimaryKey("Id")]
[ExplicitColumns]
public class MyDto
{
    [PrimaryKeyColumn]
    [Column("Id")]
    public int Id { get; set; }

    [Column("LastNumber")]
    public int LastNumber { get; set; }
}
```

MigrationBase:

```
using Umbraco.Cms.Infrastructure.Migrations;

public class CreateTableWithConstraint : MigrationBase
{
    protected readonly string tableName = "MyTable";

    public CreateTableWithConstraint(IMigrationContext context) : base(context)
    {
    }

    protected override void Migrate()
    {
        if (!TableExists(tableName))
        {
            Create.Table<MyDto>().Do();
        }
    }
}

```

**Comment by Zeegaan** [comment] 2023-01-25 09:49
I am also marking this as up for grabs for now, as there is a workaround and we'd love some help with this 🙏

**Comment by simonech** [comment] 2023-01-25 13:00
Hi @Zeegaan 
we cannot use the DTO because this doesn't work well if a 2nd migration is introduced that adds new columns, and we install the system on a new empty database:

example:

we have a class with 2 properties, Id and LastNumber, we run the migration based on the DTO, and all is fine.
we add a new property to the class; we have to add a column in the 2nd migration manually.
Here is where issues start to happen: 
 - all is fine on DBs, where we performed both migrations
 - but in a new installation, the first migration, based on the DTO, will create the table with the 3 properties, and the 2nd migration will fail since the "additional column" is already there.

That's why we decided to adopt the explicit creation of the table.

But even with the DTO, you might have the same problem if you add a PK in a second migration, and this has to be done explicitly.
We are enterprise customers, I'll raise a ticket via enterprise support.

**Comment by Zeegaan** [comment] 2023-01-26 14:00
@simonech You are right, for that scenario you need to use the fluent builder 👍 

I just made this extra migration on top of the other ones to add a column:

```
using Umbraco.Cms.Infrastructure.Migrations;

namespace Umbraco.Cms.Web.UI.Migration;

public class AddColumnToTable : MigrationBase
{
    protected readonly string tableName = "BlogComments";

    public AddColumnToTable(IMigrationContext context) : base(context)
    {
    }

    protected override void Migrate()
    {
        if (ColumnExists(tableName, "NewColumn") is false)
        {
            Create.Column("NewColumn")
                .OnTable(tableName)
                .AsInt64()
                .Do();
        }
    }
}
``` 
And this works in both scenarios, hope that helps 🙏

**Comment by Zeegaan** [comment] 2023-01-26 14:13
And as for adding primary keys on a 2nd migration, you have to pull out the entire table, delete the table, and re-create it, we recently did this in a migration: https://github.com/umbraco/Umbraco-CMS/blob/v10/dev/src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_5_0/AddPrimaryKeyConstrainToContentVersionCleanupDtos.cs

I think is a Sqlite issue because you cannot add a primary key after creating the table, and thus you are basically forced to use DTOs

**Comment by Zeegaan** [comment] 2023-01-26 14:24
As i was writing the above comment, it occurred to me that you should just create the primary key in the same call, as that works just fine 😅 

So like this:
```
            Create.Table(tableName)
                .WithColumn("Id")
                    .AsInt16()
                    .NotNullable()
                    .PrimaryKey("PK_" + tableName)
                .WithColumn("LastNumber").AsInt16().NotNullable()
                .Do();
```
And with that I am closing the issue, sorry for the wall for text! 🐛

**Closed by Zeegaan** 2023-01-26 14:24 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/backend, affected/v10, affected/v11, affected/v12

**Comment by simonech** [comment] 2023-01-26 15:45
Thanks, indeed, if SQLite doesn't allow creating PK after the table was created, creating it in the initial creation makes sense.
Hopefully, we'll never need to add a PK as a 2nd or later migration 😄
