### ISSUE TITLE
V8 - Default controller - Unable to resolve type on startup

### ISSUE THREAD

**Issue by jpinto3488** [umbraco/Umbraco-CMS#7704] opened 2020-02-24 10:27 UTC
I created a Default Controller as described on Umbraco documentation, the calss is named CustomController, website running on Umbraco 8.5.3 on Umbraco Cloud.
Often on system startup, the Composing class fails to set the default controller, with the error "Unable to resolve type: CustomController"

The website shows that error on every page, as it is unable to start. Restarting the application "fixes" the issue, but the issue may happen again on the next deploy / restart

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

### Bug summary
* Using a custom default controller may lead to error: "Unable to resolve type: CustomController"

### IUserComposer class:
```
public class CmsSetupComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        composition.SetDefaultRenderMvcController<CustomController>();
    }
}

```
### Default Controller class:
```
public class CustomController : Umbraco.Web.Mvc.RenderMvcController
{
    private readonly IScopeProvider scopeProvider;

    public CustomController(IScopeProvider scopeProvider)
    {
        this.scopeProvider = scopeProvider;
    }
    public override ActionResult Index(ContentModel model)
    {
        try
        {
            using (var scope = scopeProvider.CreateScope(autoComplete: true))
            {
                Authentication.EmailAuth.EmailLogin.LoginByUrl(scope);
            }
        }
        catch (Exception ex)
        {
            USwissKnife.Tools.ManageExceptionAsString(this.GetType(), ex);
        }
        return base.Index(model);
    }
}

```
### Full error message:
![screenshot-20200224-091544](https://user-images.githubusercontent.com/48352698/75145076-929f1a00-56f8-11ea-9df1-cbe5b5d8cfdc.png)

**Comment by nul800sebastiaan** [comment] 2020-02-24 13:42
I think it's because of a timing issue, sometimes your Composer runs too soon. If you annotate it then it should work:

```
[RuntimeLevel(MinLevel = RuntimeLevel.Run)] 
public class CmsSetupComposer : IUserComposer 
{ 
    // etc 
}
```
 
Specifying `RuntimeLevel.Run` will make sure Umbraco is running before trying to set the default controller (the comment for that enum is: `The runtime has detected an up-to-date Umbraco install and is running.``).

**Comment by jpinto3488** [comment] 2020-02-24 14:11
@nul800sebastiaan Thanks, I tried what you suggested. After specifying RuntimeLevel.Run the same error occurs, but now it occurs always. While without RuntimeLevel.Run occurs often, but not always.
Therefor this isn't fixed, is there anything else I could try?

**Comment by jpinto3488** [comment] 2020-02-24 14:15
update: I tried using  RuntimLevel.Boot and it is actually working, for now,  But I don't know if this is the default value and I will have to wait and see if it crashes again on next restarts / deploys.

**Comment by nul800sebastiaan** [comment] 2020-02-24 14:17
Weird. Well at least now it's consistent. 😅 

Oh.. did you register the controller in the IOC container?

`composition.Register<CustomController>(Lifetime.Singleton);` - should be fine to add this just before `composition.SetDefaultRenderMvcController<CustomController>();`.

**Comment by nul800sebastiaan** [comment] 2020-02-24 14:18
I will need to ask around to see what the correct way of doing this is, it would be nice if it was predictable and documented.

**Comment by nul800sebastiaan** [comment] 2020-02-24 14:19
Whoops in an earlier comment I specified `Lifetime.Singleton`, don't do that for a controller, I've removed it above now, new code is: `composition.Register<CustomController>();`

**Comment by jpinto3488** [comment] 2020-02-24 14:21
thanks @nul800sebastiaan 
this is actually working:

`[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
public class CmsSetupComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        composition.Register<CustomController>();
        composition.SetDefaultRenderMvcController<CustomController>();
        composition.Components().Append<CmsSetupComponent>();
    }
}
`
I'll wait and see if the error occurs again

**Comment by nul800sebastiaan** [comment] 2020-02-24 14:23
It should work now since you're explicitly registering the controller and LightInject knows exactly what you mean. But I am not sure if it's required to do this, if it is then we should document that. I'll get back to this when I know more!

**Comment by dawoe** [comment] 2020-02-25 14:47
I just checked a project running 8.4.1 and we did not need to register the controller it self. Just setting it as default controller was enough. We also attributed the composer with  [RuntimeLevel(MinLevel = Umbraco.Core.RuntimeLevel.Run)]

Dave

**Comment by jamiepollock** [comment] 2020-02-26 16:19
I can also confirm the similar behavior outlined in @dawoe comment in 8.4.0. Actually we don't have the `RuntimeLevel` attribute on our composer. We do register any custom IoC dependencies before we call the `SetDefaultRenderMvcController()` though.

**Comment by nul800sebastiaan** [comment] 2020-02-26 16:34
Ah this is a good point @jamiepollock! So @jpinto3488 do you have any dependencies in your `CustomController` that need to be injected through LightInject? In your sample code there is nothing custom but of course if you have anything that your controller relies on that's not registered then you will get errors.

**Comment by jpinto3488** [comment] 2020-02-27 12:36
@nul800sebastiaan on my Custom Controller there's nothing else that should be injected, I guess. As you can see from the code, it just calls a method of another class.
Anyway, the error occurred again yesterday, fun fact, I was working on a laptop, local environment, it worked without errors for the whole time, until my battery reached 15%, I activated power saving mode, which limits CPU and PC resources. When on power saving mode, the error started happening, I tried to restart the app 10 times, always got the error. I suppose the PC on power saving mode has not enough "power" to run everything correctly before Umbraco launch, which leads to the error. Maybe was just strange odds, don't know. But the point is that after registering the component and adding the runtime, the problem is still not fixed (happened only on local with power saving mode though).

**Comment by nul800sebastiaan** [comment] 2020-02-27 13:36
Yeah so that definitely sounds like a timing issue. 

Could you try again to drain your battery.. ;-) And then remove `[RuntimeLevel(MinLevel = RuntimeLevel.Run)]`

The rest can stay the same:

```csharp
public class CmsSetupComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        composition.Register<CustomController>();
        composition.SetDefaultRenderMvcController<CustomController>();
        composition.Components().Append<CmsSetupComponent>();
    }
}
```

**Comment by nul800sebastiaan** [comment] 2020-02-27 13:38
Although Dave is doing it the opposite way, so he's doing:

```csharp
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
public class CmsSetupComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        composition.SetDefaultRenderMvcController<CustomController>();
        composition.Components().Append<CmsSetupComponent>();
    }
}
```

Note that CustomController is not explicitly registered.

**Comment by jpinto3488** [comment] 2020-02-28 15:40
@nul800sebastiaan Tried as you suggested, still got error :(

**Comment by nul800sebastiaan** [comment] 2020-03-02 10:32
At this point, with a few people saying they're using this successfully, I will need to assume that there's something else wrong in your code somewhere. I have no idea what it could be but whenever I have a mysterious problem that I can pretty reliably reproduce, I start commenting out more and more custom code to see when it stops acting up.

I will close this issue for now, since I have no other indications that `SetDefaultRenderMvcController` leads to this error. I have implemented all of your code almost exactly on a site that I run on Cloud though, so I will monitor that for a while and see if it's causing me the same error at some point. But so far it works just fine. Here's all the code:

```csharp
using Umbraco.Collaborators.Core.Components;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Web;

namespace Umbraco.Collaborators.Core.Composers
{
    public class RegisterServicesComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.SetDefaultRenderMvcController<CustomController>();
            composition.Components().Append<CustomExamineComponent>();
        }
    }
}
```

```csharp
using System;
using System.Web.Mvc;
using Umbraco.Core.Scoping;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace Umbraco.Collaborators.Core.Composers
{
    public class CustomController : RenderMvcController
    {
        private readonly IScopeProvider scopeProvider;
        public CustomController(IScopeProvider scopeProvider)
        {
            this.scopeProvider = scopeProvider;
        }
        
        public override ActionResult Index(ContentModel model)
        {
            try
            {
                using (var scope = scopeProvider.CreateScope(autoComplete: true))
                {
                    // dummy DB call just so we do "something" with this scope
                    var tagCount = scope.Database.ExecuteScalar<int>("SELECT COUNT(*) FROM cmsTags");
                    Logger.Info(typeof(CustomController), $"Tag count: {tagCount}");
                }
            }
            catch (Exception ex)
            {
                Logger.Error(typeof(CustomController), "Whoa, couldn't get tags count", ex);
                throw;
            }
            return base.Index(model);
        }
    }
}
```

```csharp
using Examine;
using Umbraco.Core.Composing;

// Just a dummy component so I can register something in my composer
namespace Umbraco.Collaborators.Core.Components
{
    public class CustomExamineComponent : IComponent
    {
        private readonly IExamineManager _examineManager;

        public CustomExamineComponent(IExamineManager examineManager)
        {
            _examineManager = examineManager;
        }

        public void Initialize() {}

        public void Terminate() {}
    }
}
```

**Closed by nul800sebastiaan** 2020-03-02 10:32 UTC
Labels: state/needs-investigation
