### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'JetBrains.Annotations, Version=2020.1.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#10801] opened 2021-08-05 20:46 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001, byt any V9 version really

### Bug summary

[JetBrains.Annotations](https://www.nuget.org/packages/JetBrains.Annotations/) is package for which the purpose is that you can add attributes to your code in your own libraries, which then will help improving intellisense with ReSharper in Visual Studio (and possibly also in Rider).

Here are a few examples on how it's used in my Skybrud.Essentials package:

https://github.com/skybrud/Skybrud.Essentials/blob/2ad8dd12918361679ca08f3ce6326ef45b19358c/src/Skybrud.Essentials/Common/PropertyNotSetException.cs#L33

https://github.com/skybrud/Skybrud.Essentials/blob/2ad8dd12918361679ca08f3ce6326ef45b19358c/src/Skybrud.Essentials/Strings/RegexUtils.cs#L18

For instance adding `[RegexPattern]` to a parameter in a method, will tell ReSharper that this parameter has the format of a regular expression, and that ReSharper should provide intellisense for it. In a similar way, `[InvokerParameterName]` can be used to indicate that a method parameter contains the name of another property/parameter, which then will make ReSharper suggest using `nameof(...)` instead of a string literal.

As the package targets code editors, JetBrains.Annotations will typically only be used as a development dependency, meaning it isn't added as a dependency when generating a NuGet package - eg. like this:

https://github.com/skybrud/Skybrud.Essentials/blob/7859ff37e5f3e9f42a8ad3c140048cdfafcb287a/src/Skybrud.Essentials/Skybrud.Essentials.csproj#L67

<hr />

To explain the usage a bit further, most of my Umbraco 8 packages have a dependency for my [Skybrud.Essentials](https://github.com/skybrud/Skybrud.Essentials) package, and we also use Skybrud.Essentials heavily throughout our client projects.

Skybrud.Essentials it self has a dependency for JetBrains.Annotations, but only as a development dependency. The dependency isn't used for anything within my package besides improving the developer experience a little when consuming my package.

This setup has worked fine with Umbraco 8. But in Umbraco 9, the type loader seems to hit these method parameters, and then trigger an exception as the types behind these attributes are declared in an assembly that is (intentionally) not there.

### Specifics

Here is the raw exception:

```
System.IO.FileNotFoundException: Could not load file or assembly 'JetBrains.Annotations, Version=2020.1.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'. The system cannot find the file specified.
File name: 'JetBrains.Annotations, Version=2020.1.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.GetReferences(Assembly assembly)+MoveNext()
   at Umbraco.Cms.Core.Composing.ReferenceResolver.Resolve(Assembly assembly)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.ResolveAssemblies()
   at Umbraco.Cms.Core.Composing.FindAssembliesWithReferencesTo.Find()
   at Umbraco.Cms.Core.Composing.DefaultUmbracoAssemblyProvider.get_Assemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetAllAssemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass51_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at UmbracoNineBeta.Startup.ConfigureServices(IServiceCollection services) in D:\Testing\UmbracoNineBeta\UmbracoNineBeta\Startup.cs:line 46
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at UmbracoNineBeta.Program.Main(String[] args) in D:\Testing\UmbracoNineBeta\UmbracoNineBeta\Program.cs:line 11
```

### Steps to reproduce

- Set up a new Umbraco 9 installation

- Install Skybrud.Essentials (as an example):
  ```
  dotnet add package Skybrud.Essentials --version 1.1.29
  ```

- Try to boot up Umbraco

    - Bootup will fail as the type loader will try to run through methods and their parameters within Skybrud.Essentials, which may have attributes where the type is declared in **JetBrains.Annotations**.

### Expected result / actual result

The expected result would be that having a development dependency for **JetBrains.Annotations** will not cause Umbraco's type loader to trigger an exception.

I'm not entirely sure why the loader hit's my own assembly. According to the stack trace, the type loader is called from the `AddAllCoreCollectionBuilders` method. So maybe Umbraco is looking to broadly if the method is only looking for it's own collection builders?

I understand that Umbraco 9 may be doing something that is required for Umbraco to work properly, but I'd prefer to have Umbraco 9 not trigger an exception like described 🤞 

If it isn't possible to change the current behavior in Umbraco, there is a rather simple fix as my packages could add JetBrains.Annotations as a normal dependency instead of just as a development dependency. But I'd rather avoid this as it is after all only used for development purposes.

**Comment by bergmania** [comment] 2021-08-06 09:48
Hi @abjerner..

Sounds like very related or or a even duplicate of https://github.com/umbraco/Umbraco-CMS/issues/10554

**Comment by bergmania** [comment] 2021-08-06 10:21
Adding `"JetBrains.Annotations,"` to `TypeFinder.KnownAssemblyExclusionFilter` also seems to fix the issue..

**Comment by abjerner** [comment] 2021-08-06 11:32
@bergmania thanks for the reply. I think Matt's issue may be a bit of the opposite, as his issue seems to be that Umbraco doesn't let him discover certain types out of the box, whereas my issue is that Umbraco automatically discovers types that it shouldn't.

I'll try to play around adding the name to `TypeFinder.KnownAssemblyExclusionFilter`, and submit a PR if I can confirm that it also works in my setup 👍

**Comment by abjerner** [comment] 2021-08-06 12:32
@bergmania I haven't really worked with the V9 source code yet. Any tips for getting it up and running locally?

This seems to be for V8 even though it should be the right branch: https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/.github/CONTRIBUTING.md

**Comment by nul800sebastiaan** [comment] 2021-08-06 12:42
@abjerner Open the .sln file in Visual Studio! ;-)  It's all pretty much the same otherwise.

Make sure to do a fresh clone for v9, it's near impossible to switch from the v8 to the v9 branch and back.

**Comment by abjerner** [comment] 2021-08-06 13:25
@nul800sebastiaan Probably just me being a bit slow, as I had to pick the right startup project (as it wasn't the one set by default). 

Following my own steps to reproduce as described earlier in this issue, I can confirm that adding `JetBrains.Annotations` to the exclusion list fixes the issue, so PR is here: https://github.com/umbraco/Umbraco-CMS/pull/10808

**Comment by nul800sebastiaan** [comment] 2021-08-06 13:58
@abjerner I know! Super annoying! It works differently from the .net framework version so I haven't been able to fix that (yet, need to do some more research).

**Closed** 2021-08-06 17:19 UTC
Labels: project/v9, type/bug
