### ISSUE TITLE
IPublishedContent.Url returns “#” if the item is set to have a scheduled publish time in the future

### ISSUE THREAD

**Issue by TakeitEasyAlan** [umbraco/Umbraco-CMS#17079] opened 2024-09-17 08:07 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

When an item is published, our solution has a **PublishingNotificationHandler : INotificationHandler** which we use to notify other systems that a new page has been published, edited and or deleted.

- When using the **IPublishedContent.Url** property, it correctly returns the absolute URL if the item is saved and published immediately.
- However, when the item is scheduled for a future publish date, when the **PublishingNotificationHandler** is called in the future, The **IPublishedContent.Url** returns **#** instead of the correct URL.

### Specifics

Any item that is published in the future, all browsers.

### Steps to reproduce

1. Create a **PublishingNotificationHandler : INotificationHandler<ContentPublishingNotification>**
2. Publish an item in the future
3. in the PublishingNotificationHandler  get the **IPublishedContent** and call **Url**

### Expected result / actual result

The correct URL is returned.

**Comment by NguyenThuyLan** [comment] 2024-10-18 09:06
Hi @TakeitEasyAlan ,
I was not able to reproduce your issue.
Here is how I get URL, then I will close this and feel free to reopen if you have more details
```
public class PublishingNotificationHandler : INotificationHandler<ContentPublishedNotification>
{
    private readonly UmbracoHelper _umbracoHelper;
    public PublishingNotificationHandler(UmbracoHelper umbracoHelper) {
        _umbracoHelper = umbracoHelper;
    }
    public void Handle(ContentPublishedNotification notification)
    {
        foreach (var publishedItem in notification.PublishedEntities)
        {
            //you can get URL like this
            var url = _umbracoHelper.Content(publishedItem.Id).Url();
        }
       
    }
}
```

**Closed by NguyenThuyLan** 2024-10-18 09:06 UTC
Labels: type/bug

**Comment by TakeitEasyAlan** [comment] 2024-11-15 10:18
_umbracoHelper.Content(publishedItem.Id) returns null, when caught in the publishing event handler!!!! 

So that code does not work
