### ISSUE TITLE
Examine rebuilds the indexes on startup before custom fields or transformers are registered

### ISSUE THREAD

**Issue by base33** [umbraco/Umbraco-CMS#8893] opened 2020-09-14 16:33 UTC
We have extended the External Searcher with some extra fields and have also attached an event to the TransformingIndexValues index event so that we can modify the values that are being indexed.

The problem is that Examine rebuilds the indexes on startup and wipes all the correct values in the index with lots of missing values.  It is basically rebuilding the index before our customisations were able to be applied.

From my own investigation, this is because Examine configures itself at the ICoreComposer stage and then registers the ExamineFinalComponent to run after all ICoreComposer's have finished.

See:
* https://github.com/umbraco/Umbraco-CMS/blob/db6714d3b8f8e04dceb607c3a25117331f6b525d/src/Umbraco.Web/Search/ExamineFinalComposer.cs

According to the documentation [here](https://our.umbraco.com/documentation/reference/searching/examine/indexing/), all examples register components at IUserComposer stage, which means we are too late to the party on startup.

Is this a documentation problem or a code issue?  I suppose more specifically, should Examine rebuild after all IUserComposer's and their components have complete?

I can confirm, if I change my custom composer to a ICoreComposer, then everything starts working again. 

I think this issue is worth recording because it can certainly go unnoticed unless you write a site that's heavily dependant on Examine like I am. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.1

Reproduction
------------

Set up a IUserComposer as per documentation that registers some custom examine fields, and also attach to the index TransformingIndexValues event to manipulate some values.

### Bug summary

Examine rebuilds the indexes on startup but completely ignores the custom code because the custom code hasn't run yet.

### Specifics

See above.

### Expected result

Examine would startup and rebuild the indexes, but would wait for me to apply my customisations before going ahead.

### Actual result

Missing stuff.

**Comment by base33** [comment] 2020-09-14 16:49
Bit more info.

If I want to implement my own IndexCreator, I have to register it at IUserComposer stage.  But adding to the index FieldDefinitionCollection and attaching to the TransformingIndexValues needs to happen at the ICoreComposer stage.

**Comment by Shazwazza** [comment] 2020-09-14 23:38
Examine final composer needs to run after everything but it doesn't actually do much:

* Ensures all lucene indexes are not locked and configured correctly
* initializes the index rebuilder to start after the site has booted up with a delay of 5 seconds but only if the indexes are empty

So something doesn't seem right here. ExamineFinalComposer/ExamineFinalComponent shouldn't be interfering with custom configuring of indexes or events and it only rebuilds when the indexes don't exist. 

Can you elaborate more on what customizations you are doing and provide some code snippets? Are you saying that your indexes are being rebuilt every startup? (that should not be happening)

**Comment by base33** [comment] 2020-09-15 08:19
Hi @Shazwazza ,

Thanks for taking a look at this.  

We have the following Composer:

```csharp
public class RegisterIndexerComponentComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<IndexerComponent >();
        }
    }
```

And the component:
```csharp
public class IndexerComponent : IComponent
    {
        private readonly IExamineManager examineManager;
        private readonly IUmbracoContextFactory umbracoContextFactory;
        private readonly ILogger logger;
        private readonly IContentService contentService;
        private readonly IPublicAccessService publicAccessService;

        public IndexerComponent(IExamineManager examineManager, IUmbracoContextFactory umbracoContextFactory, ILogger logger, IContentService contentService, IPublicAccessService publicAccessService)
        {
            this.examineManager = examineManager ?? throw new ArgumentNullException(nameof(examineManager));
            this.umbracoContextFactory = umbracoContextFactory ?? throw new ArgumentNullException(nameof(umbracoContextFactory));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.contentService = contentService;
            this.publicAccessService = publicAccessService;
        }

        public void Initialize()
        {
            if (examineManager.TryGetIndex("ExternalIndex", out IIndex externalIndex))
            {
                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("articleDate", FieldDefinitionTypes.Long));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("ageRange", FieldDefinitionTypes.FullTextSortable));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("gender", FieldDefinitionTypes.FullTextSortable));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("wellnessElements", FieldDefinitionTypes.FullTextSortable));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("articleType", FieldDefinitionTypes.FullTextSortable));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("articleContentType", FieldDefinitionTypes.FullTextSortable));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("eventContentType", FieldDefinitionTypes.FullTextSortable));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("priorityArticle", FieldDefinitionTypes.Integer));

                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("permissionGroups", FieldDefinitionTypes.FullText));

                ((BaseIndexProvider)externalIndex).TransformingIndexValues += 
                    IndexerComponent_TransformingIndexValues;
            }
        }

        private void IndexerComponent_TransformingIndexValues(object sender, IndexingItemEventArgs e)
        {
            if(int.TryParse(e.ValueSet.Id, out var nodeId))
            switch(e.ValueSet.ItemType)
            {
                case "articlePage": 
                case "eventPage": 
                case "reviewPage":
                        using (var umbracoContext = umbracoContextFactory.EnsureUmbracoContext())
                        {
                            var contentNode = umbracoContext.UmbracoContext.Content.GetById(nodeId);
                            if (contentNode != null)
                            {
                                var articleDate = contentNode.Value<DateTime>("articleDate");
                                e.ValueSet.Set("articleDate", articleDate.Date.Ticks);

                                var priorityArticle = contentNode.Value<bool>("priorityArticle");
                                e.ValueSet.Set("priorityArticle", priorityArticle ? 1 : 0);

                                var articleType = contentNode.Value<string>("articleType");
                                e.ValueSet.Set("articleType", articleType);

                                var articleContentType = contentNode.Value<string>("articleContentType");
                                if (!string.IsNullOrEmpty(articleContentType))
                                {
                                    articleContentType = articleContentType.Replace("/", string.Empty);
                                }

                                e.ValueSet.Set("articleContentType", articleContentType);

                                var eventContentType = contentNode.Value<string>("eventContentType");
                                e.ValueSet.Set("eventContentType", eventContentType);

                                var ageRange = contentNode.Value<List<IPublishedContent>>("ageRange");
                                if (ageRange != null)
                                {
                                    e.ValueSet.Set("ageRange", string.Join(" ", ageRange.Select(m => m.Name.Replace(" ", "")).ToList()));
                                }

                                var genderRange = contentNode.Value<List<IPublishedContent>>("gender");
                                if (genderRange != null)
                                {
                                    e.ValueSet.Set("gender", string.Join(" ", genderRange.Select(m => m.Name.Replace(" ", "")).ToList()));
                                }

                                var wellnessElements = contentNode.Value<List<IPublishedContent>>("wellnessElements");
                                if (wellnessElements != null)
                                {
                                    e.ValueSet.Set("wellnessElements", string.Join(" ", wellnessElements.Select(m => m.Name.Replace(" ", "")).ToList()));
                                }

                                var rawContent = contentService.GetById(nodeId);
                                var permissions = publicAccessService.GetEntryForContent(rawContent);

                                if (permissions != null && permissions.Rules.Any())
                                {
                                    e.ValueSet.Set("permissionGroups", string.Join("|", permissions.Rules.Select(m => m.RuleValue).ToList()));
                                }
                            }
                        }
                    break;
            }
        }

        public void Terminate(){}
    }
```

I do have an index creator set up to enable protected content:
```csharp
public class RegisterIndexCreator : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.RegisterUnique<IUmbracoIndexesCreator, CustomUmbracoIndexesCreator>();
        }
    }
```

and:
```csharp
public class CustomUmbracoIndexesCreator : UmbracoIndexesCreator
    {
        // ctor
        public CustomUmbracoIndexesCreator(IProfilingLogger profilingLogger, ILocalizationService languageService, IPublicAccessService publicAccessService, IMemberService memberService, IUmbracoIndexConfig umbracoIndexConfig)
            : base(profilingLogger, languageService, publicAccessService, memberService, umbracoIndexConfig)
        {
        }

        // override the Create method
        public override IEnumerable<IIndex> Create()
        {
            // create the default index definitions
            var defaultIndexes = base.Create().ToDictionary(x => x.Name, x => x);
            var internalIndex = defaultIndexes[Constants.UmbracoIndexes.InternalIndexName];
            var memberIndex = defaultIndexes[Constants.UmbracoIndexes.MembersIndexName];

            // create a custom external index
            var externalIndex = CreateExternalIndex();

            // return the Umbraco indexes - all 3 must be here with the correct names!
            return new IIndex[]
            {
            internalIndex,
            externalIndex,
            memberIndex
            };
        }

        private IIndex CreateExternalIndex()
        {
            var index = new UmbracoContentIndex(
                Constants.UmbracoIndexes.ExternalIndexName, // default
                CreateFileSystemLuceneDirectory(Constants.UmbracoIndexes.ExternalIndexPath), // default
                new UmbracoFieldDefinitionCollection(), // default

                // change the default analyzer from StandardAnalyzer
                new StandardAnalyzer(Lucene.Net.Util.Version.LUCENE_30),
                ProfilingLogger, // default
                LanguageService, // default
                new ContentValueSetValidator(true, true, PublicAccessService)); // default

            return index;
        }
    }
```

But on startup, the whole site reindexes itself which results in all of our code to add/update new fields and transform the values to not run. 

If I reindex the whole site after the web site is fully loaded via the Examine dashboard then everything runs perfectly.  But if I recycle the app pool it rebuilds and the data is reindexed without running the custom code.

Funny enough, registering the ``` IndexerComponent ``` in a ICoreComposer makes everything run fine on startup.

Do you see anything above where we might be going wrong?

**Comment by base33** [comment] 2020-09-15 09:00
Update:

I am wondering whether this Creator could be the cause of these weird issues.

I have now left the ``` ExamineComposer ``` as a IUserComposer, and changed the ``` RegisterIndexCreator ``` composer to a ICoreComposer and labelled it with the attribute to run after the Examine Composer:

```csharp
[ComposeAfter(typeof(ExamineComposer))]
    public class RegisterIndexCreator : ICoreComposer
    {
        public void Compose(Composition composition)
        {
            //in order to set protected to true (wtf)
            composition.RegisterUnique<IUmbracoIndexesCreator, CustomUmbracoIndexesCreator>();
        }
    }
```

I have cleared down the indexes and restarted the site, everything runs okay now.

I am wondering whether it's worth updating the documentation [here](https://our.umbraco.com/documentation/reference/searching/examine/indexing/#overriding-index-creation) to register Index Creators like the above?  

This doesn't seem as much of a bug now, it seems more like a race condition.  But the documentation may mislead others too.

Should I commit a change to the documentation to reflect this and make note of potential race conditions?

**Comment by Shazwazza** [comment] 2020-09-16 02:14
Why are you trying to create another index? That is entirely unnecessary since you aren't really modifying the actual index definitely anyways. You are already configuring fields individually which is fine but there's no need to override the index creator if you are just creating it with the default values anyways.

**Comment by base33** [comment] 2020-09-16 07:27
Hi @Shazwazza 
We needed to support protected content on the external index but by default it doesn't. 
Is there an easier way?

**Comment by Shazwazza** [comment] 2020-10-14 04:07
@base33 perhaps all along you're encountering these issues: https://github.com/umbraco/Umbraco-CMS/pull/9137, https://github.com/umbraco/Umbraco-CMS/pull/9010

**Comment by JasonElkin** [comment] 2021-04-13 16:34
I was about to start a new issue, but I wonder if this is a manifestation of the problem I'm having [here](https://github.com/umbraco/UmbracoDocs/issues/3115).

**Comment by Shazwazza** [comment] 2021-04-14 01:53
There's a couple issues/questions here.

SupportProtectedContent for the external index is true by default. There's no customization needed to make this correct.

As mentioned the #9137, #9010 also has an effect on some reports above.

And yes possibly parts of the above are due to something resolving the underlying value types too early, as per https://github.com/umbraco/UmbracoDocs/issues/3115#issuecomment-819138962

For testing and reproduction - we need to know if there's any issue a a vanilla install of Umbraco (no packages). 

RE: 

> But on startup, the whole site reindexes itself which results in all of our code to add/update new fields and transform the values to not run.

Umbraco does not eagerly rebuild the indexes, it rebuilds on a background thread that is delayed and occurs after the boot process. So to me this sounds like something else (a package?) is eagerly rebuilding indexes during the boot phase which should not happen.

Example code that works with a vanilla Umbraco install. This works every time whether there is a cold boot occurring and index rebuilding occurs or if index rebuilding occurs because the indexes don't exist. 

```cs
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class CustomizeIndexComposer : ComponentComposer<CustomizeIndexComponent>, IUserComposer
    {
    }

    public class CustomizeIndexComponent : IComponent
    {
        private readonly IExamineManager examineManager;

        public CustomizeIndexComponent(IExamineManager examineManager)
        {
            this.examineManager = examineManager;
        }

        public void Initialize()
        {
            if (examineManager.TryGetIndex("ExternalIndex", out IIndex externalIndex))
            {
                externalIndex.FieldDefinitionCollection.AddOrUpdate(
                    new FieldDefinition("articleDate", FieldDefinitionTypes.DateTime));

                ((BaseIndexProvider)externalIndex).TransformingIndexValues +=
                    IndexerComponent_TransformingIndexValues;
            }
        }

        private void IndexerComponent_TransformingIndexValues(object sender, IndexingItemEventArgs e)
        {
            e.ValueSet.Set("hello", "world");
        }

        public void Terminate()
        {
        }
    }
```

**Comment by JasonElkin** [comment] 2021-04-14 11:57
@Shazwazza the plot thickens...

In my case it looks like it's due to race conditions with the `ContentTypeCacheRefresher`.

In my logs I can see that the refresher is getting fired in between the ExamineComponent and my custom component being composed. The refresher is [initialising the index](https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/Search/ExamineComponent.cs#L380) (and adding docs to it) before my component has a chance to initialize.

This is what I think is going on:

1. `ExamineComponent` is composed and subscribes to the `ContentTypeCacheRefresher.CacheUpdated`
2. Some other component/package/load balanced server etc. causes `ContentTypeCacheRefresher.CacheUpdated` to fire
3. `ExamineComponent.ContentTypeCacheRefresherUpdated` causes the index to init
4. My component adds to the `FieldDefinitionCollection` (too late)
5. When I come to run my search the field types are wrong.

If this is right then there isn't a sure-fire way to protect against this is there? Examine is already subscribed to an event that could get called at any time (and in my case is).

**Comment by Shazwazza** [comment] 2021-04-14 12:30
Thanks for more investigation. I'll have a look tomorrow if how that can happen. The problem isn't the approach documented, it's this odd behavior of premature index init that shouldn't happen. Sounds like you've found the culprit or at least part of it which is great! Gives me something to analyze. Will report back tomorrow. Cheers!

**Comment by Shazwazza** [comment] 2021-04-29 18:49
FYI, see PR https://github.com/umbraco/Umbraco-CMS/pull/10182

**Comment by Shazwazza** [comment] 2021-06-04 16:38
This should now be resolved in #10182

**Closed** 2021-06-04 16:37 UTC

**Comment by arknu** [comment] 2021-09-01 08:30
@Shazwazza I'm still seeing these issues on 8.16.0. I had applied the workaround to 8.14.0, upgraded to 8.16.0 and removed the workaround. I'm now back to custom fields not being added to the index on startup.

**Comment by Shazwazza** [comment] 2021-09-01 15:30
@arknu Can you please provide steps to replicate?

**Comment by Shazwazza** [comment] 2021-09-01 22:16
What 'work around' are you referring too?

A fail safe way to make sure there's no premature index initializations occurring (which could be forced by non-core code too) is to create your own `IUmbracoIndexesCreator` like this and modify the fields this way:

```cs
public class MyIndexFactory : UmbracoIndexesCreator
{
    public MyIndexFactory(IProfilingLogger profilingLogger, ILocalizationService languageService, IPublicAccessService publicAccessService, IMemberService memberService, IUmbracoIndexConfig umbracoIndexConfig) : base(profilingLogger, languageService, publicAccessService, memberService, umbracoIndexConfig)
    {
    }

    public override IEnumerable<IIndex> Create()
    {
        var indexes = base.Create();
        foreach(var index in indexes)
        {
            if (index.Name == Constants.UmbracoIndexes.InternalIndexName)
            {
                // ... modify fields here
            }
            // ... or process other indexes by name
        }
        return indexes;
    }
}
```

Then register this service 

```cs
composition.RegisterUnique<IUmbracoIndexesCreator, MyIndexFactory>();
```

Umbraco could make this easier by making something like `IUmbracoIndexFieldConfig` interface that can return `UmbracoFieldDefinitionCollection` and possibly custom value type factories, and having that injected into the `UmbracoIndexesCreator` and use results from that interface to pass these values to the index constructors.

In Examine 2 and Umbraco 9 this is all much simpler, everything is done during composition with IOptions.

**Comment by arknu** [comment] 2021-09-02 07:13
@Shazwazza I have the following ExamineUserComponent:

```csharp
public class ExamineComposer : ComponentComposer<ExamineComponent>
{
}

public class ExamineComponent : ExamineUserComponent
{
    private readonly IExamineManager examineManager;
    private readonly IContentTypeService contentTypeService;
    private readonly ILogger logger;
    private readonly string[] propertyEditorsToIndex = new string[] { PropertyEditors.Aliases.TextBox, PropertyEditors.Aliases.TextArea, PropertyEditors.Aliases.TinyMce };

    public ExamineComponent(IExamineManager examineManager, IContentTypeService contentTypeService, ILogger logger, IMainDom mainDom) : base(mainDom)
    {
        this.examineManager = examineManager;
        this.contentTypeService = contentTypeService;
        this.logger = logger;
    }

    protected override void InitializeComponent()
    {
        if(examineManager.TryGetIndex(UmbracoIndexes.ExternalIndexName, out var index))
        {
            if(index is BaseIndexProvider baseIndex)
            {
                baseIndex.TransformingIndexValues += BaseIndex_TransformingIndexValues;
            }
        }
    }

    private void BaseIndex_TransformingIndexValues(object sender, IndexingItemEventArgs e)
    {
        if(e.ValueSet.Category == "content")
        {
            var blocksJson = e.ValueSet.GetValue("blocks") as string;
            if(blocksJson != null)
            {
                try
                {
                    var json = JObject.Parse(blocksJson);

                    var strings = ParseBlockListJson(e.ValueSet.Id, json);

                    e.ValueSet.Add("searchText", string.Join(" ", strings));

                }
                catch(Exception ex)
                {
                    logger.Error<ExamineComponent>(ex, "Error processing blocklist index for item" + e.ValueSet.Id);
                }
            }
        }
    }

    private List<string> ParseBlockListJson(string contentId, JObject json)
    {
        
    }
}
```

When the AppPool starts, the index is created, but without the custom field I'm adding here. If I then go to the dashboard and rebuild the index, the custom field is added, so the code at least works. The weird thing is that it works on my local machine in IIS Express, but not on the production site...

The workaround was basically to inject an IndexRebuilder and then rebuild the index after registering my handler. This did of course result in the index being created twice on startup, which is why I removed it again, as that is not ideal.

**Comment by ontranet** [comment] 2024-06-12 12:21
Hi,
Need help.
on Umbraco version 8.9.1 our indexes are deleted.

Can anyone see problems in the code below?
Its runs fine for a month, sudenly all indexes are gone.

`using Examine;
using Examine.LuceneEngine.Providers;
using Examine.Providers;
using System;
using System.Collections.Generic;
using System.Linq;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Logging;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using UmbracoExamine.PDF;
using Website.Models.ModelsBuilder;
using Website.Extensions;
using static Umbraco.Core.Constants;
using Website.Services;
using Examine.LuceneEngine.Directories;
using Umbraco.Examine;

namespace Website.Composers
{
    [ComposeAfter(typeof(ExaminePdfComposer))] //this must execute after the ExaminePdfComposer composer
    public class RegisterIndexerComponentComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<IndexerComponent>();
            composition.Components().Append<MediaType>();
        }
    }
    public class IndexerComponent : IComponent
    {
        private readonly IExamineManager examineManager;
        private readonly IUmbracoContextFactory umbracoContextFactory;
        private readonly ILogger logger;

        public IndexerComponent(IExamineManager examineManager, IUmbracoContextFactory umbracoContextFactory, ILogger logger)
        {
            this.examineManager = examineManager ?? throw new ArgumentNullException(nameof(examineManager));
            this.umbracoContextFactory = umbracoContextFactory ?? throw new ArgumentNullException(nameof(umbracoContextFactory));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
        public void Initialize()
        {

            DirectoryFactory.DefaultLockFactory = d =>
            {
                var simpleFsLockFactory = new NoPrefixSimpleFsLockFactory(d);
                return simpleFsLockFactory;

            };
            //Get both the external and pdf index
            if (examineManager.TryGetIndex(UmbracoIndexes.ExternalIndexName, out var externalIndex) && examineManager.TryGetIndex(PdfIndexConstants.PdfIndexName, out var pdfIndex))
            {
                //register a multisearcher for both of them
                var multiSearcher = new MultiIndexSearcher("MultiSearcher", new IIndex[] { externalIndex, pdfIndex });
                examineManager.AddSearcher(multiSearcher);

                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("categoryNames", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("issueDate", FieldDefinitionTypes.Long));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("validDate", FieldDefinitionTypes.Long));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("Tags", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileNumber", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileName", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileNameAlt", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileNameAlt2", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLang", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangExtra", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangCode1", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangCode2", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangCode3", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangCode4", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangCode5", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangExtraCode1", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangExtraCode2", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangExtraCode3", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangExtraCode4", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("FileLangExtraCode5", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("EpdClassification2", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("EpdExtraClassification2", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("EpdType", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("mutual", FieldDefinitionTypes.Raw));
                externalIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("company", FieldDefinitionTypes.Raw));

                ((BaseIndexProvider)externalIndex).TransformingIndexValues += IndexerComponent_TransformingIndexValues;
            }
        }

        private void IndexerComponent_TransformingIndexValues(object sender, IndexingItemEventArgs e)
        {
            if (int.TryParse(e.ValueSet.Id, out var nodeId))
            {
                switch (e.ValueSet.ItemType)
                {
                    case "ePDPage":
                        using (var umbracoContext = umbracoContextFactory.EnsureUmbracoContext())
                        {
                            var contentNode = umbracoContext.UmbracoContext.Content.GetById(nodeId);

                            if (contentNode != null)
                            {
                                var ePDPage = contentNode as EPdpage;
                                var variants = ePDPage.Elements.Select(x => x.Content);

                                List<string> EpdClassificationNames = new List<string>();
                                List<string> FileLangNames = new List<string>();
                                List<string> FileLangCodeNames = new List<string>();
                                List<string> FileLangExtraNames = new List<string>();
                                List<string> FileLangExtraCodeNames = new List<string>();
                                List<string> MutualNames = new List<string>();
                                List<string> EpdExtraClassificationNames = new List<string>();
                                List<string> IssueDates = new List<string>();
                                List<string> ValidDates = new List<string>();
                                List<string> pageNameStrings = new List<string>();

                                if (variants != null)
                                {
                                    foreach (var variant in variants)
                                    {
                                        if (variant.HasValue("epdPDFIle") && !string.IsNullOrEmpty(variant.Value<IPublishedContent>("epdPDFIle").Name))
                                        {
                                            var fileName = variant.Value<IPublishedContent>("epdPDFIle").Name.ToLower();
                                            var number = new string(fileName.SkipWhile(c => !char.IsDigit(c)).TakeWhile(c => char.IsDigit(c)).ToArray());
                                            e.ValueSet.Set("FileNumber", number);
                                            e.ValueSet.Set("FileName", fileName);
                                            e.ValueSet.Set("FileNameAlt", fileName.Replace(" ", "-"));
                                            e.ValueSet.Set("FileNameAlt2", string.Concat("md", number));
                                        }

                                        if (variant.HasValue("epdFileClassification"))
                                        {
                                            if (!EpdClassificationNames.Contains(variant.Value<string>("epdFileClassification").ToLower().Replace("+", "")))
                                            {
                                                EpdClassificationNames.Add(variant.Value<string>("epdFileClassification").ToLower().Replace("+", ""));
                                            }
                                        }

                                        if (variant.HasValue("epdExtraFileClassification"))
                                        {
                                            if (!EpdExtraClassificationNames.Contains(variant.Value<string>("epdExtraFileClassification").ToLower().Replace("+", "")))
                                            {
                                                EpdExtraClassificationNames.Add(variant.Value<string>("epdExtraFileClassification").ToLower().Replace("+", ""));
                                            }
                                        }

                                        if (variant.HasValue("epdMutual") && variant.Value<bool>("epdMutual") && variant.HasValue("epdFileClassification"))
                                        {
                                            e.ValueSet.Set("mutual", "mutual");
                                        }

                                        if (variant.HasValue("issueDate"))
                                        {
                                            if (!IssueDates.Contains(variant.Value<string>("issueDate")))
                                                IssueDates.Add(variant.Value<string>("issueDate"));
                                        }

                                        if (variant.HasValue("validDate"))
                                        {
                                            if (!ValidDates.Contains(variant.Value<string>("validDate")))
                                                ValidDates.Add(variant.Value<string>("validDate"));
                                        }

                                        if (variant.HasValue("epdFileLanguage"))
                                        {
                                            var FileLang = variant.Value<EpdLanguage>("epdFileLanguage");
                                            e.ValueSet.Set("FileLang", FileLang.Name.ToLower());

                                            if (!FileLangCodeNames.Contains(variant.Value<IPublishedContent>("epdFileLanguage").Value("country").ToString().ToLower().Replace("-", "")))
                                            {
                                                FileLangCodeNames.Add(variant.Value<IPublishedContent>("epdFileLanguage").Value("country").ToString().ToLower().Replace("-", ""));
                                            }
                                        }

                                        if (variant.HasValue("epdTypes"))
                                        {
                                            e.ValueSet.Set("epdType", variant.Value<EpdTypePage>("epdTypes").Name.ToLower()); //variant.Value<EpdTypePage>("epdType").Name.ToLower()
                                        }

                                        if (variant.HasValue("epdExtraFileLangauge"))
                                        {
                                            var FileLang = variant.Value<EpdLanguage>("epdExtraFileLangauge");
                                            e.ValueSet.Set("epdExtraFileLangauge", FileLang.Name.ToLower());

                                            if (!FileLangExtraCodeNames.Contains(variant.Value<IPublishedContent>("epdExtraFileLangauge").Value("country").ToString().ToLower().Replace("-", "")))
                                            {
                                                FileLangExtraCodeNames.Add(variant.Value<IPublishedContent>("epdExtraFileLangauge").Value("country").ToString().ToLower().Replace("-", ""));
                                            }
                                        }
                                    }
                                }
                                e.ValueSet.Set("issueDate", string.Join(",", IssueDates.ToArray()));
                                e.ValueSet.Set("validDate", string.Join(",", ValidDates.ToArray()));
                                e.ValueSet.Set("EpdClassification2", string.Join(",", EpdClassificationNames.ToArray()));

                                var pageNames = ePDPage.Name.Split(' ');
                                foreach (var n in pageNames)
                                {
                                    if (n.Length > 1)
                                    {
                                        if (!pageNameStrings.Contains(n.ToLower().ReplaceDanishChars().Replace(";", "")))
                                        {
                                            pageNameStrings.Add(n.ToLower().ReplaceDanishChars().Replace(";", ""));
                                        }
                                    }
                                }

                                e.ValueSet.Set("Tags", string.Join(" ", pageNameStrings.ToArray()));


                                var f = 1;
                                foreach (var i in FileLangCodeNames)
                                {
                                    e.ValueSet.Set("FileLangCode" + f, i);
                                    f++;
                                }

                                var fe = 1;
                                foreach (var i in FileLangExtraCodeNames)
                                {
                                    e.ValueSet.Set("FileLangExtraCode" + fe, i);
                                    fe++;
                                }

                                if (EpdExtraClassificationNames.Count() > 0)
                                {
                                    e.ValueSet.Set("EpdExtraClassification2", string.Join(",", EpdExtraClassificationNames.ToArray()));
                                }

                                if (EpdExtraClassificationNames.Count() > 0)
                                {
                                    e.ValueSet.Set("EpdExtraClassification2", string.Join(",", EpdExtraClassificationNames.ToArray()));
                                }

                                //IF MNTP
                                List<string> categoryNames = new List<string>();

                                if (ePDPage.Kategori != null)
                                {
                                    foreach (var category in ePDPage.Kategori)
                                    {
                                        categoryNames.Add(category.Name.ReplaceDanishChars().ToLower());
                                    }

                                    e.ValueSet.Set("categoryNames", string.Join(",", categoryNames.ToArray()));
                                }

                                e.ValueSet.Set("company", ePDPage.Parent.Name.ReplaceDanishChars().ToLower());
                            }
                        }
                        break;
                }
            }
        }
        public void Terminate()
        {
        }
    }
}`
