### ISSUE TITLE
v8: Bug/Error. NuCache sometimes does not display images or files

### ISSUE THREAD

**Issue by OAOVLD** [umbraco/Umbraco-CMS#5016] opened 2019-03-19 06:54 UTC
Hello (Здравствуйте)

v8: Bug/Error. NuCache sometimes does not display images or files.

v8: Bug/Error. NuCache иногда не отображаются файлы или изображения.

We found a workaround, when the bug #4879 repeated -
https://github.com/umbraco/Umbraco-CMS/issues/4879.

Мы нашли временное решение, когда ошибка  #4879  повторяется - https://github.com/umbraco/Umbraco-CMS/issues/4879.

NoCache causes error #4879. You must go to Umbraco > Settings and do the following:
1. Published Status > Collect
2. Published Status > Refresh
3. Published Status > Rebuild
4. Published Status > Reload

Данная ошибка #4879 возникает из-за NuCache. Необходимо перейти в Umbraco > Settings и выполнить следующие действия:

1. Published Status > Собирать
2. Published Status > Обновление
3. Published Status > Перестраивать
4. Published Status > Перегружать

**Comment by OAOVLD** [comment] 2019-03-19 07:01
Most likely, after you restart IIS, you must run Published Status Reload automatically (4. Published Status > Reload)

**Comment by zpqrtbnk** [comment] 2019-03-19 07:24
A bit of infos: restarting IIS (or, more simply, restarting the app domain by touching `web.config`) does indeed cause a cache *reload*. Which simply reloads the cache from its pre-cache in database. If a reload can fix the problem, it would indicate that cache refreshing went wrong at some point.

The *rebuild* option in the dashboard, entirely rebuilds the pre-cache in database. If that action is required, it would indicate that something went wrong with maintaining that pre-cache, and that would be a nasty and yet unknown issue with NuCache.

Note that rebuilding from the dashboard, *also* triggers a reload. If you have to force a reload after a rebuild, it would indicate that something went wrong with our distributed cache notification, which would be again a nasty an unknown issue.

The *collect* option in the dashboard triggers a full .NET CLR garbage-collection, plus a NuCache internal collection of snapshots. It is intended for testing and debugging and should have no impact for you. If it *does* have impact, it would indicate a *very* nasty issue with either the CLR (!) or some deep NuCache internals.

Finally, the *refresh* option in the dashboard only refreshes what is displayed and has no action on the cache itself.

So...

We would need you to
* Narrow the list of actions in your list to those that are actually required. I suspect only one single reload is necessary. Otherwise, as indicated, you have discovered a very internal and very nasty issue.
* Provide us with a clear repro. As already discussed in #4879 we haven't been able to reproduce the problem and so we are powerless and cannot help.

Thanks for helping us!

**Comment by zpqrtbnk** [comment] 2019-03-19 07:26
More infos: if the problem lies in how the property value converters cache the conversion result, then a plain site restart (touching `web.config`) would fix the issue without having to do anything in NuCache's dashboard.

**Comment by OAOVLD** [comment] 2019-03-19 13:09
Yes, using operation # 4 (Published Status > Reload) the images appear. Thank

**Comment by OAOVLD** [comment] 2019-03-19 13:12
Reproduce the problem:
1. Stop site (or delete web.config)
2. F5 (Refresh Page)
3. Start site (or recovery web.config)
4. F5 (Refresh Page)
5. No images
6. Published Status > Reload
7. F5 (Refresh Page)
8. Images appeared

**Comment by OAOVLD** [comment] 2019-03-19 13:14
Which images/files are disappearing, where an image is displayed. The problem is partially spreading to some pages/files/images

**Comment by OAOVLD** [comment] 2019-03-19 13:17
How do I temporarily disable caching before this issue is resolved?

**Comment by zpqrtbnk** [comment] 2019-03-19 16:19
You cannot disable caching - it's more than caching, its the source of everything.

Glad to hear we can narrow it down to having to reload the cache.

Now, what you describe... we just cannot reproduce it. So, we cannot fix anything ;-(

I assume that images are somewhere in the media library... but then, we have zero details about... how are you rendering your page? Where are the images coming from, in the page? What's special about your site? Your content types? Your templates? You need to help us here ;-)

**Comment by OAOVLD** [comment] 2019-03-19 18:39
1. Question: I assume that images are somewhere in the media library
1. Answer: Yes

2. Question: but then, we have zero details about... how are you rendering your page?
2. Answer:

@* 1 полоса *@
@if (el_Content_Page_Main != null && el_Content_Page_Main.Count() > 0)
{
    IEnumerable<IPublishedContent> elem_list = el_Content_Page_Main.First().Children.Where(p => p.ContentType != null && p.ContentType.Alias == ContentType_Doc_News_Child).OrderByDescending(p => p.Properties.Where(x => x.PropertyType.Alias == "Content_Date").FirstOrDefault().GetValue()).Take(el_Content_Page_Main_Count);

    if (elem_list != null && elem_list.Count() > 0)
    {
        IEnumerable<IPublishedContent> Main_1_List = new List<IPublishedContent>();
        IEnumerable<IPublishedContent> Main_2_List = new List<IPublishedContent>();

        if (elem_list.Count() > 4)
        {
            Main_1_List = elem_list.Take(4);
            Main_2_List = elem_list.Skip(4);
        }
        else
        {
            Main_1_List = elem_list;
        }

        <div class="wis-block_1">
            <div class="wis-container no-padding">
                <div class="row">
                    
                    <div class="col-md-6">
                        
                        <div class="wis-slider">
                            <div class="wis-carousel-main owl-carousel owl-carousel__wiserv">
                                @if (Main_1_List.Count() > 0)
                                {
                                    int index = 0;
                                    foreach (var elem in Main_1_List)
                                    {
                                        string elem_Main_Title = elem.Value<string>("Main_Title");
                                        string elem_Content_Short_Title = elem.Value<string>("Content_Short_Title");
                                        string elem_Content_Short_Teaser = elem.Value<string>("Content_Short_Teaser");
                                        IPublishedContent elem_Content_Short_Image = elem.Value<IPublishedContent>("Content_Short_Image");

                                        DateTime elem_Content_Date = elem.Value<DateTime>("Content_Date");
                                        int elem_Content_ViewNum = elem.Value<int>("Content_ViewNum");

                                        index++;
                                        string elem_class = "";
                                        if (index > 1)
                                        {
                                            elem_class = "wis-carousel-main-elem__none";
                                        }

                                        <div class="wis-carousel-main-elem @elem_class">
                                            <a href="@elem.Url" class="wis-carousel-main-elem-link">
                                                <div class="wis-slider-main-elem-img">
                                                    <div class="wis-img_crop-width">
                                                        <div class="wis-img_crop-width-block">
                                                            @if (elem_Content_Short_Image != null)
                                                            {
                                                                <img src="@elem_Content_Short_Image.Url" alt="" />
                                                            }
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="wis-slider-main-elem-container">
                                                    <div class="wis-slider-main-elem-container-view">
                                                        <span class="wis-common-date_active wis-common-index">@Html.WIS_Date(Value: elem_Content_Date)</span>
                                                        @if (elem_Content_ViewNum > 0)
                                                        {
                                                            <span class="wis-common-view wis-common-index">@elem_Content_ViewNum просмотров</span>
                                                        }
                                                        <span class="wis-clear"></span>
                                                    </div>
                                                    <div class="wis-slider-main-elem-container-title">
                                                        @if (!string.IsNullOrWhiteSpace(elem_Content_Short_Title))
                                                        {
                                                            <text>@elem_Content_Short_Title</text>
                                                        }
                                                        else
                                                        {
                                                            <text>@elem_Main_Title</text>
                                                        }
                                                    </div>
                                                
                                                </div>
                                                <div class="wis-clear"></div>
                                            </a>
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
}

**Comment by OAOVLD** [comment] 2019-03-19 18:40
Question: I assume that images are somewhere in the media library?
Answer: Yes

**Comment by OAOVLD** [comment] 2019-03-19 18:42
Question: but then, we have zero details about... how are you rendering your page?
Answer: 
<div class="wis-test">
      @{ 
      
        string ContentType_Doc_News_Child = "Doc_News_Child";

        //Тип документа - Видео
        string ContentType_Doc_Video_Child = "Doc_Video_Child";

        //События недели
        IEnumerable<IPublishedContent> el_Content_Page_Main = Model.Value<IEnumerable<IPublishedContent>>("Content_Page_Main");
        int el_Content_Page_Main_Count = 8;
    }

    @* 1 полоса *@
    @if (el_Content_Page_Main != null && el_Content_Page_Main.Count() > 0)
    {
        IEnumerable<IPublishedContent> elem_list = el_Content_Page_Main.First().Children.Where(p => p.ContentType != null && p.ContentType.Alias == ContentType_Doc_News_Child).OrderByDescending(p => p.Properties.Where(x => x.PropertyType.Alias == "Content_Date").FirstOrDefault().GetValue()).Take(el_Content_Page_Main_Count);

        if (elem_list != null && elem_list.Count() > 0)
        {
            IEnumerable<IPublishedContent> Main_1_List = new List<IPublishedContent>();
            IEnumerable<IPublishedContent> Main_2_List = new List<IPublishedContent>();

            if (elem_list.Count() > 4)
            {
                Main_1_List = elem_list.Take(4);
                Main_2_List = elem_list.Skip(4);
            }
            else
            {
                Main_1_List = elem_list;
            }

            <div class="wis-block_1">
                <div class="wis-container no-padding">
                    <div class="row">
                        
                        <div class="col-md-6">
                            
                            <div class="wis-slider">
                                <div class="wis-carousel-main owl-carousel owl-carousel__wiserv">
                                    @if (Main_1_List.Count() > 0)
                                    {
                                        int index = 0;
                                        foreach (var elem in Main_1_List)
                                        {
                                            string elem_Main_Title = elem.Value<string>("Main_Title");
                                            string elem_Content_Short_Title = elem.Value<string>("Content_Short_Title");
                                            string elem_Content_Short_Teaser = elem.Value<string>("Content_Short_Teaser");
                                            IPublishedContent elem_Content_Short_Image = elem.Value<IPublishedContent>("Content_Short_Image");

                                            DateTime elem_Content_Date = elem.Value<DateTime>("Content_Date");
                                            int elem_Content_ViewNum = elem.Value<int>("Content_ViewNum");

                                            index++;
                                            string elem_class = "";
                                            if (index > 1)
                                            {
                                                elem_class = "wis-carousel-main-elem__none";
                                            }

                                            <div class="wis-carousel-main-elem @elem_class">
                                                <a href="@elem.Url" class="wis-carousel-main-elem-link">
                                                    <div class="wis-slider-main-elem-img">
                                                        <div class="wis-img_crop-width">
                                                            <div class="wis-img_crop-width-block">
                                                                @if (elem_Content_Short_Image != null)
                                                                {
                                                                    <img src="@elem_Content_Short_Image.Url" alt="" />
                                                                }
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="wis-slider-main-elem-container">
                                                        <div class="wis-slider-main-elem-container-view">
                                                            <span class="wis-common-date_active wis-common-index">@Html.WIS_Date(Value: elem_Content_Date)</span>
                                                            @if (elem_Content_ViewNum > 0)
                                                            {
                                                                <span class="wis-common-view wis-common-index">@elem_Content_ViewNum просмотров</span>
                                                            }
                                                            <span class="wis-clear"></span>
                                                        </div>
                                                        <div class="wis-slider-main-elem-container-title">
                                                            @if (!string.IsNullOrWhiteSpace(elem_Content_Short_Title))
                                                            {
                                                                <text>@elem_Content_Short_Title</text>
                                                            }
                                                            else
                                                            {
                                                                <text>@elem_Main_Title</text>
                                                            }
                                                        </div>

                                                    </div>
                                                    <div class="wis-clear"></div>
                                                </a>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        }
    }
</div>

**Comment by OAOVLD** [comment] 2019-03-19 18:44
Question: Where are the images coming from, in the page? 
Answer: From page (Image picker)

**Comment by OAOVLD** [comment] 2019-03-19 18:44
Question: What's special about your site? 
Answer: The usual news highload website

**Comment by OAOVLD** [comment] 2019-03-19 18:47
Question:Your content types?
Answer: The usual content type - Umbraco.MediaPicker and Umbaco.MultiUrlPicker (for select files and images)

**Comment by OAOVLD** [comment] 2019-03-19 18:47
Is there enough information now?

**Comment by OAOVLD** [comment] 2019-03-20 08:13
Importantly: this error occurs on about 3 out of 100 pages (1 out of 10) with the same template. 
Example:
1. News of the week - errors. Template : news, Data type: Doc_News
2. Topical news - no errors. Template : news, Data type: Doc_News
3. Important news - no errors. Template : news, Data type: Doc_News
4. Green news - no errors. Template : news, Data type: Doc_News
5. Red news - no errors. Template : news, Data type: Doc_News
6. Blue news - no errors. Template : news, Data type: Doc_News
......
99. Black news - errors
100. White news - no errors

**Comment by OAOVLD** [comment] 2019-03-21 08:38
Hello, 
EN: Now You have enough information to solve the problem?
RUS: Теперь у вас достаточно информации, чтобы решить проблему?

**Comment by OAOVLD** [comment] 2019-03-21 08:48
EN: Can be to call a method (Published Status > Reload) every 10-20 minutes? How to do this? (Temporary solution)
Rus: Может быть вызывать метод (Published Status > Reload) каждые 10-20 минут? Как это сделать? (Временное решение)

**Comment by OAOVLD** [comment] 2019-03-24 14:13
Hello
Have you made any progress?

**Comment by OAOVLD** [comment] 2019-03-25 10:22
EN: We found a temporary solution to the problem. Now we are waiting for your answer.
RU: Мы нашли временное решение проблемы. Теперь мы ждем ответа от вас.

**Comment by DanielToft** [comment] 2019-04-02 13:21
Hi @zpqrtbnk 

I think we are having the exact same problem. The media cache gets invalidated. It says it only have 3 entries. It helps to press Reload on the Published Status Page, but when the application restarts it's gets invalidated again. 

The database table "cmsContentNu" seems to have the right content. I have tried to investigate the nuCache content, with the NuCache explore, but it's giving me an error when trying to load the cache file.

We are working in a multi environment setup, which means we are sharing the same database (Two developers and a test environment). Maybe the problem is related to this?

If you have problems to reproduce, maybe you can get access to our source code and our shared database?

We are also having another problem with media items. I'm not sure it's related to the cache. With a Umbraco.MediaPicker set to only pick one item, the item is not resolved from the cache.

/ Daniel Toft

**Comment by zpqrtbnk** [comment] 2019-04-02 17:44
Have not been able to make any progress on this. The code of your view looks quite normal, and we have not been able to reproduce this situation, and we have other sites that do quite similar things and do not have this problem.

Which means... we cannot really investigate. As Sebastiaan wrote in his comments to #4879, maybe discussing the situation with the community on the https://our.umbraco.com forums may help.

Meanwhile, I am going to close the issue. Sorry about this, I do realize you have a problem with your site, but so far we cannot link it to an issue in Umbraco.

**Closed by zpqrtbnk** 2019-04-02 17:44 UTC

**Comment by OAOVLD** [comment] 2019-04-04 11:53
This problem occurs on all sites. (8.0.0 and 8.0.1).

**Comment by zpqrtbnk** [comment] 2019-04-04 16:03
Note: it may very well be that this issue is a duplicate of #5121 - more or less the same weird symptoms - and then, a fix is in PR at the moment!
