### ISSUE TITLE
Unreliable (content) tree behaviour when running tours

### ISSUE THREAD

**Issue by uniquelau** [umbraco/Umbraco-CMS#3864] opened 2018-12-12 15:46 UTC
Because content items are lazy loaded into the tree, you cannot rely on the referenced `eventElement` being present.

Reproduction
------------

### Bug summary

If the tour references something in the tree that has not yet been loaded, the tour is unreliable.

### Specifics

Umbraco 7.12.4
Chrome, Internet Explorer

### Steps to reproduce

Create a Tour that references nested nodes.

- Home
-- Level2
--- Level3

Step 1, select Home [data-element='tree-item-Home']
Step 2, select Level2 [data-element='tree-item-Level2']
Step 3, select Level3 [data-element='tree-item-Level3']

The tour will only work, if the user expands the tree to ensure those items are available. 
As a Umbraco developer, you could potentially resolve this, by adding expand tree steps, but it's additional work for the developer, and not a good experience for the editor.

### Expected result

Selector finds item/node required for tour.

### Actual result

If the tree is not expanded, the node is not found.

### Suggestion

Add the ability to execute JavaScript when the tour step event is triggered.
This could be used to open the children and resolve this.

**Comment by dawoe** [comment] 2018-12-12 17:07
Hi Laurence,

Thanks for raising this. 

Are you trying to create a tour for a specific node or doctype. Because I have a PR ready for doctype specific tours.

https://github.com/umbraco/Umbraco-CMS/pull/2635

Maybe that could solve your problem once it's merged in.

Dave

**Comment by uniquelau** [comment] 2018-12-12 17:44
Hi @dawoe,

Thank-you, I think it will resolve my issue, but if I go down that route, I'd need to create some kind of index of the tours, as otherwise the content editor might not find them.

In my current scenario, I have some tours, that take the content editor through a section, that include multiple doc types, such as a landing page, and child item. 

To resolve my immediate need, I have written a custom view and controller, that will take the eventElement, and try and open the children in the tree. That way I can add it into any tour steps and it then guarantee's, that the next element in the content tour can be selected.

**Comment by nul800sebastiaan** [comment] 2019-01-28 09:35
Sorry for the late reply on this one, we've discussed this at HQ and it would be really good to have the synctree method available in a tour step so it can be added to the tour manifest.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:37
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:37 UTC
Labels: community/up-for-grabs, help wanted, type/feature
