### ISSUE TITLE
umb-search-filter broken in "Select editor" window

### ISSUE THREAD

**Issue by glombek** [umbraco/Umbraco-CMS#9541] opened 2020-12-11 20:38 UTC
umb-search-filter is broken in the "Select editor" window when adding a new property to a document type.

## Umbraco version

I am seeing this issue on Umbraco version: v8/contrib (to be 8.11.0)

Cannot replicate in 8.9.1 (not tested in 8.10.*)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce

1. Open up a document type
2. Add a new property
3. Select editor type
4. Broken search box appears

### Expected result

Search icon is aligned with text box

Screenshot from 8.9.1:
![image](https://user-images.githubusercontent.com/3120611/101952686-f398cf80-3bf0-11eb-8aa6-59ba82efe257.png)

### Actual result

Search icon is misaligned
![image](https://user-images.githubusercontent.com/3120611/101948133-76b62780-3be9-11eb-8528-80e31f8284e8.png)

This likely relates to #9037.

**Comment by bjarnef** [comment] 2021-01-10 12:26
It seems this has been affected by the changed in this PR where `icon-search` was removed from the `<umb-icon>` in the search  filter. https://github.com/umbraco/Umbraco-CMS/pull/9255/files#diff-511f1dd6fea9b25e43b0cc0b3981515130d59c98c92cae29c8b26c90ecc338b7L4

The `icon-search` is not required for the icon itself, but it was used in the search filter styling.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less#L21-L28

Re-adding this make the search filter look nice again:
![image](https://user-images.githubusercontent.com/2919859/104122736-1f6db900-5347-11eb-9e2d-3625cca85345.png)

We can of course style specific on `.umb-icon` class instead, but I wonder if we can avoid breaking the styling if packages used the old markup.

**Comment by bjarnef** [comment] 2021-01-10 12:33
The old markup looked like this:

```
<div class="form-search">
         <umb-icon icon="icon-search" class="icon-search"></umb-icon>
         <input type="text"
                     style="width: 100%"
                     ng-model="searchTerm"
                     class="umb-search-field search-query input-block-level"
                     localize="placeholder"
                     placeholder="@placeholders_filter"
                     umb-auto-focus
                     no-dirty-check />
</div>
```

or:

```
<div class="form-search">
         <i class="icon-search" aria-hidden="true"></i>
         <input type="text"
                     style="width: 100%"
                     ng-model="searchTerm"
                     class="umb-search-field search-query input-block-level"
                     localize="placeholder"
                     placeholder="@placeholders_filter"
                     umb-auto-focus
                     no-dirty-check />
</div>
```

**Comment by bjarnef** [comment] 2021-01-10 12:38
It seems the old markup still works as long we keep the `icon-search` styling 👍 

![image](https://user-images.githubusercontent.com/2919859/104123058-24cc0300-5349-11eb-8b25-5c8e9a2d5fa6.png)

**Comment by bjarnef** [comment] 2021-01-10 13:19
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9631

**Comment by nul800sebastiaan** [comment] 2021-01-12 13:17
Thanks @glombek - we reverted a PR (https://github.com/umbraco/Umbraco-CMS/pull/9255) recently and I think that has fixed it. Right now I can't reproduce the problem in 8.11. I'll close this for now!

**Closed by nul800sebastiaan** 2021-01-12 13:17 UTC

**Comment by bjarnef** [comment] 2021-01-12 13:22
@nul800sebastiaan yes, the revert of https://github.com/umbraco/Umbraco-CMS/pull/9255 fixes the issue because `icon-search` class is back, where this styling target the element.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less#L21-L28

https://github.com/umbraco/Umbraco-CMS/pull/9631 wouldn't harm though if we later use don't need the `icon-search` here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html#L4

**Comment by nul800sebastiaan** [comment] 2021-01-12 13:23
Good stuff @bjarnef! I've left #9255 open on purpose for that indeed! 👍

**Comment by bjarnef** [comment] 2021-01-12 13:34
@nul800sebastiaan I guess you mean https://github.com/umbraco/Umbraco-CMS/pull/9631 but great to keep in mind for future changes 🦝

**Comment by nul800sebastiaan** [comment] 2021-01-12 13:40
Duh! Yes that is what I meant! 🤦‍♂️
