### ISSUE TITLE
Removing a media item doesn't prompt changes were made

### ISSUE THREAD

**Issue by matthewcare** [umbraco/Umbraco-CMS#13009] opened 2022-09-15 17:12 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0-preview.70

### Bug summary

Removing media from a media picker doesn't prompt that you have unsaved changes when navigating away.

### Steps to reproduce

Add a media item to a content node, and save.
Remove the media item from the picker, and navigate away, you will notice there is no prompt saying you have unsaved changes.
![image](https://user-images.githubusercontent.com/1469061/190467911-0aed6bcc-335f-4693-9e57-0a2a093f08dd.png)

### Expected result / actual result

Expected: A prompt warning you of unsaved changes.
Actual: No prompt, and you are allowed to navigate away.

**Comment by nul800sebastiaan** [comment] 2022-09-19 12:30
I can reproduce this one (with Media Picker 3, not the legacy one), can repro back to v9.4 as well, so it looks like something is not setting this property as dirty when removing a media item. Adding a new item after removing the existing one will trigger the dirty flag though, so a bit of logic is missing somewhere.

**Comment by Bakersbakebread** [comment] 2022-10-24 10:23
PR Submitted above ☝️

**Comment by nul800sebastiaan** [comment] 2022-11-28 14:53
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13085

**Closed by nul800sebastiaan** 2022-11-28 14:53 UTC
Labels: community/up-for-grabs, type/bug
