### ISSUE TITLE
NetCore: ContentModel.<ModelName>not working in Umbraco Beta 9

### ISSUE THREAD

**Issue by anantjaiswal339** [umbraco/Umbraco-CMS#10211] opened 2021-05-01 05:02 UTC
ℹ️ If this bug **also** appears on the current version 8 of Umbraco then please [report it as a regular bug](https://github.com/umbraco/Umbraco-CMS/issues/new?template=1_Bug.md), fixes in version 8 will be merged to the .NET Core version.

A brief description of the issue goes here.

Reproduction
------------
Add any document type and try to add the content of that document.
Lets assume I'm adding Home Page so you will find line `@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>`  where `ContentModels.Home` is not exists

### Bug summary
`ContentModels.Home` does not exists in the context, due to this I'm not able to display the property of the document in razor page.

### Specifics

Please take a look to the code snap: [Code snap](https://www.screencast.com/t/1e49UrgCcAh)

### Expected result

ContentModels.Home should work so that we can have all the property of the particular document type

### Actual result

[Result Error](https://www.screencast.com/t/hG9o9GVCF1f)

**Comment by bergmania** [comment] 2021-05-03 06:40
Not sure I understand this correct..

What you describe is expected behaviour when using ModelsBuilder in PureLive mode. But you should still be able to compile your codebase, as razor views are not compiled by default.

Your "Code snap" and "Result Error" seems to be from two different examples? From the little knowledge, I have currently my guess would be that the error in "Result Error" is because the `@item.quizPageImage` should have been `@item.QuizPageImage`.

Alternatively, try to see my answer to this question, which seems related:
https://our.umbraco.com/forum/umbraco-9/105870-umbraco-9-on-net-core

Let me know, if razor is happy, if you use another mode than the default `PureLive`. 🙂

**Comment by nul800sebastiaan** [comment] 2021-05-06 09:33
I'll close this for now until it's more clear if this is a bug or not.

**Closed by nul800sebastiaan** 2021-05-06 09:33 UTC
Labels: project/net-core
