### ISSUE TITLE
Unable to click on anything when closing newsletter or new user tutorial modals

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#16742] opened 2024-07-04 12:12 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.0

### Bug summary

On a login to a new account both the tutorial and newsletter modals continue to disable everything even after being closed.
(V13)
So you need to refresh the page after closing the modals to be able to click anything

### Steps to reproduce

Create a new bacoffice user
Login to the backoffice with a new user
Close either the newsletter or new user tutorial modals
Attempt to click on anything

### Expected result / actual result

To be able to click on items

Actual:

Need to reload the page before being able to click on anything

**Comment by callumbwhyte** [comment] 2024-07-05 13:35
Can confirm this is happening for us too!

**Comment by uniquelau** [comment] 2024-07-10 17:17
Observed in v13.4.0, and v14 and v14 rc1

**Comment by skttl** [comment] 2024-07-11 06:47
It's because this div containing everything inside the backoffice has the inert=true attribute
![image](https://github.com/umbraco/Umbraco-CMS/assets/3726467/fb944096-9974-46ad-83f0-475342d723e3)

**Comment by iOvergaard** [comment] 2024-07-11 09:46
Hi @AaronSadlerUK, thank you so much for noticing this. And thank you, @skttl, for figuring it out. We were able to pinpoint it back to a certain change. We are going to revert the change and figure out when to release a patch.

**Comment by iOvergaard** [comment] 2024-07-11 09:49
> Observed in v13.4.0, and v14 and v14 rc1

To the best of my abilities, I have been unable to reproduce this for any of the V14 versions. In fact, I don't think we have any code that references the `inert` attribute, which was the problem for V13. However, not saying it's not a problem, but can you provide some more information on your experiences with V14 such as:

- Browser version?
- When does it happen, e.g. when a popup is shown?
- Does it go away after reload?

**Comment by nul800sebastiaan** [comment] 2024-07-11 10:39
Fixed in #16775

**Closed by nul800sebastiaan** 2024-07-11 10:39 UTC
Labels: type/bug, area/frontend, affected/v13, release/13.4.1
