### ISSUE TITLE
[9.1.2] Variations add (2)... to the page names

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#11819] opened 2022-01-04 10:50 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

Since upgrading to Umbraco 9.1.2 when I edit a page with a variation, all the secondary languages (not default) end up with (2), (3) etc... added to the page name

### Steps to reproduce

Not 100% sure, other than editing a pre-existing page variation and then save and publishing it

### Expected result / actual result

The page name to remain as-is without the (2), (3)

**Comment by nul800sebastiaan** [comment] 2022-01-04 11:05
I can't reproduce this directly, but I can when there's a node on the same level in the tree with the same nodename, which is to be expected as we're trying to avoid routing conflicts. Could that be your problem?

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:07
This is happening across languages and didn't happen prior to 9.1.2

English (rootdomain.com): Page Name
Australian (au.rootdomain.com): Page Name (1)
United States (us.rootdomain.com): Page Name (2)

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:07
When changing the variation:
![image](https://user-images.githubusercontent.com/9937803/148050288-a4eacefc-5d98-4ed5-b185-38dc80ba9071.png)

**Comment by nul800sebastiaan** [comment] 2022-01-04 11:28
So you were on 9.1.1 before? Or else, what version does "prior" mean please?

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:28
Yes 9.1.1 previously

**Comment by nul800sebastiaan** [comment] 2022-01-04 11:41
Don't think it worked before either but it probably should work, not sure how v8 does this.


https://user-images.githubusercontent.com/304656/148053861-4d6d401e-00d6-48b6-99ca-a90ceb6bd39b.mp4

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:42
Ok so the main difference there:

(I can't edit the hostname out at this point, so apologies for that)

![image](https://user-images.githubusercontent.com/9937803/148054057-4f3e17eb-73ee-4455-875c-da7cc20dc8c4.png)

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:43
Australia for example:
![image](https://user-images.githubusercontent.com/9937803/148054110-c95f81f1-0a90-470a-a145-293c3d198fc1.png)

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:49
Ok I was able to replicate it:

Copy a page with multiple variations, then rename the new base page and variations (different to the original).

It will then cause the original page on saving to add the (1) / (2)
![Umbraco Bug](https://user-images.githubusercontent.com/9937803/148054750-7e92ceb2-0256-4902-950d-3e0b50649ab9.gif)

**Comment by AaronSadlerUK** [comment] 2022-01-04 11:55
It also does the same if you create a content template based on the original page

**Comment by nul800sebastiaan** [comment] 2022-01-04 12:13
It seems to be because pages with the same language on the same level in the node tree can not have the same name, which seems to be a bug, since the parent has a different. This is logic that came from v8 where I can reproduce the same behavior. I am not sure why this is since the domains are different. So the routing rules should probably be updated to take uniqueness from configured domains into account. We'd love a bit of help with that!

v9
https://user-images.githubusercontent.com/304656/148057349-61ded518-858b-4b41-8e88-f40349eb1921.mp4

v8
https://user-images.githubusercontent.com/304656/148057348-fe919319-259a-42e0-91a1-2de9496caaa7.mp4

**Comment by jveer** [comment] 2022-04-19 19:48
I've tried to reproduce with the steps above, however I'm no longer able to reproduce this specific issue.

I think it was solved with #11977 / #11996, but you might want to revalidate with 9.4.0 yourself first :).

**Comment by kjac** [comment] 2023-01-11 16:23
I think @jveer is correct 😄 this is no longer an issue in V10 either.

I'm going to close this now. If anyone manages to reproduce on V10+ we'd of course love to hear all about it 😆

**Closed by kjac** 2023-01-11 16:23 UTC
Labels: community/up-for-grabs, type/bug
