### ISSUE TITLE
Height of first element inside blocklist is off when using a large description on the blocklist

### ISSUE THREAD

**Issue by D-Inventor** [umbraco/Umbraco-CMS#14653] opened 2023-08-09 07:23 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

When choosing a blocklist for a property with inline editing enabled, the first property inside the first element of the blocklist scales its height the same as the description of the root property.

### Specifics

See this example with a long description and the effect that it has on the blocklist:
![image](https://github.com/umbraco/Umbraco-CMS/assets/25585418/0c7359aa-6c07-4f8d-955e-753cc09f4be8)

### Steps to reproduce

1. Create an element type with at least 2 properties, some textboxes suffice
2. Create a blocklist datatype using this element type.
3. Create a document type with a property with a long description.
4. Create new content using the document type of the previous step.
5. Add a block to the blocklist, open the inline harmonica and observe how the second property is pushed down to where the description of the root property ends.

### Expected result / actual result

I expected the second property inside the blocklist inline harmonica to be just below the first property. Instead, it is pushed downwards to where the description of the root property description ends.

**Comment by kjac** [comment] 2023-08-10 12:12
Hi @D-Inventor,

Thank you for reaching out. I can reproduce this on V10:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/af562cf8-a97a-49f3-a84f-b0a4a4257c62)

Weirdly, the same thing does not happen on V11:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/59b8ff1b-e3f6-4b57-a750-db2c48a93e50)

As a workaround you can disable inline editing on the Block List data type:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/45815c3c-c459-4814-b903-6c73953f3f21)

Workaround or not, we'd love some help getting this fixed. I've been digging a bit in the PR history for V11, and I haven't found any obvious PRs targeting this particular issue, so it might have been fixed by accident.

**Comment by D-Inventor** [comment] 2023-08-10 18:24
@kjac I've been able to pull the second property back up by disabling `clear: both` on `.form-horizontal .control-group:after` inside the devtools:
<img width="853" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/25585418/9f986b63-3f6f-45da-a0f6-7243fb6e03c5">

Perhaps that is a good place to continue the research. I am no css expert, but perhaps somebody else can confirm my hypothesis.

**Comment by nielslyngsoe** [comment] 2024-11-27 19:51
Based on KJACs comment this issue was only present in v.10 and solved in v.11. Since v.10 is now in support phase it wont receive any further fixes and therefor I will close this issue.

Thanks for the report and interesting in these matter, I appreciate it — as well this might be the issue that made someone fix it, it was just never referred which is why we cant find the PR that fixed this.

**Closed by nielslyngsoe** 2024-11-27 19:51 UTC
Labels: community/up-for-grabs, type/bug, state/reproduced, area/frontend, affected/v10
