### ISSUE TITLE
Document Type Collection Inheritance

### ISSUE THREAD

**Issue by bartmermans** [umbraco/Umbraco-CMS#9449] opened 2020-11-24 13:46 UTC
When creating a Document Type Collection under another Document Type, properties of the parent  Document Type are not inherited.

When I try to add a Document Type Collection under an existing Document Type, I get a console error like this:

![image](https://user-images.githubusercontent.com/72868418/100102012-49d0e900-2e63-11eb-950e-a5b5763b9882.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.8.0

**Comment by KevinJump** [comment] 2020-12-06 12:13
think this is the same issue as #4473 - which was originally for v7.13+ but it does look like its also v8

**Comment by nul800sebastiaan** [comment] 2020-12-14 21:51
Thanks! I'll close as duplicate of #4473 and we'd love to get some help getting that one resolved.

**Closed by nul800sebastiaan** 2020-12-14 21:51 UTC
