### ISSUE TITLE
Content section node context menu name "Culture and Hostnames" has changed to "Allow access to assign culture and hostnames"

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#12358] opened 2022-05-04 20:25 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc1

### Bug summary

Not sure this is a bug or made intentionally. 
"_Allow access to assign culture and hostnames_" sounds somehow misleading and for the left hand panel it is to long:
![image](https://user-images.githubusercontent.com/866917/166819529-9242c00a-873d-4be3-9207-08ef6d3c778f.png)

### Steps to reproduce

Just create one content node and open the right mouse click context menu / actions.

---
_This item has been added to our backlog [AB#19622](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/19622)_

**Comment by nathanwoulfe** [comment] 2022-05-04 20:42
Looks like a bug/regression to me... Probably a changed language key or value. 

Feel like investigating?

**Comment by nathanwoulfe** [comment] 2022-05-05 00:00
@idseefeld I had a bit of a dig into this, looks to be related to #11784 where the translation key changed from "assignDomain" to "assigndomain", which causes text localisation to check the no-area dictionary as "actions/assignDomain" doesn't exist, so instead returns "actionDescriptions/assignDomain"

This all happens in the below block - we fall into the else block since the area param has a value, then into the if because the "actions" dictionary exists, but we don't find a value for "assignDomain" in that dictionary, so we hit the block at 401, where we check for any item "assignDomain", which exists in "actionDescriptions" and returns "Allow access to assign culture and hostnames".

https://github.com/umbraco/Umbraco-CMS/blob/a676322fee8dc484e592cf2d051babbadc43a2ed/src/Umbraco.Core/Services/LocalizedTextService.cs#L387-L403

 I've verified that reverting the key change fixes this issue, but will obviously then reintroduce the issue fixed in #11784. Given this is a regression, and will be present in recent v9 releases, it's likely one for HQ to deal with.

**Comment by bjarnef** [comment] 2022-05-16 20:42
I noticed this as well when working on https://github.com/umbraco/Umbraco-CMS/pull/12403

So we currently get a quite long text in this menu action:

![image](https://user-images.githubusercontent.com/2919859/168678989-9dec58a6-0b62-4532-a2fe-6b320314696e.png)

**Comment by nikolajlauridsen** [comment] 2022-06-07 07:03
Fixed in #12448, thanks for reporting 👍

**Closed by nikolajlauridsen** 2022-06-07 07:03 UTC
Labels: state/sprint-candidate, type/bug

**Comment by nathanwoulfe** [comment] 2022-07-03 23:29
@nikolajlauridsen I think this one has resurfaced - #12611 was raised to handle long text in action items, but the particular long text was the string reported in this bug... Care to take a look at how/when/where this regressed?
