### ISSUE TITLE
Umbraco 9 Nested Content

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#11705] opened 2021-11-29 08:56 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.1

### Bug summary

After upgrading to Umbraco 9, some of the nested content the fields are not showing.

### Specifics

When unfolding some of the nested content I get this:

![image](https://user-images.githubusercontent.com/6445636/143836380-c939040b-d789-4ad4-ad41-128879d0442c.png)

But should look like this:

![image](https://user-images.githubusercontent.com/6445636/143836430-5d71eb2d-99fe-4137-babb-2f33fba207ac.png)

Getting these errors:

`System.NullReferenceException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.
`

And 

`at Umbraco.Cms.Core.PropertyEditors.NestedContentPropertyEditor.NestedContentValidator.GetElementTypeValidation(Object value)+MoveNext()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at Umbraco.Cms.Core.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass17_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Cms.Core.Services.Implement.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator3.ValidatePropertyValue(TModelSave model, TModelWithProperties modelWithProperties, IDataEditor editor, ContentPropertyDto property, Object postedValue, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator3.ValidatePropertiesData(TModelSave model, TModelWithProperties modelWithProperties, ContentPropertyCollectionDto dto, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutingAsync(ActionExecutingContext context)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

And this:

![image](https://user-images.githubusercontent.com/6445636/143836762-3c7fd565-109d-4fc6-9838-440fa48773fc.png)

I have looked a the nested content fields to find out if it's only nested content with specific fields, but it's not consistent

### Steps to reproduce

After opgrading an Umbraco 8.16.0 to a 9.0.1 we had the issue. Have now updated to 9.1.1 and still same issue.

### Expected result / actual result

Expected the Nested content fields to show the fields

**Comment by thomashdk** [comment] 2021-11-30 15:12
When I try to publish a node that has some Nested content elements that has that issue I get this:

![image](https://user-images.githubusercontent.com/6445636/144073501-b50dbae4-c66d-43fb-9821-82d8430ebcb6.png)

**Comment by thomashdk** [comment] 2021-12-01 08:13
Maybe it has something to do with this:

![image](https://user-images.githubusercontent.com/6445636/144196454-37579056-5626-49c3-b72e-6e88c9b7d72f.png)

**Comment by thomashdk** [comment] 2021-12-02 12:41
I'm pretty stuck here and can't get our clients sides out on then new version...

**Comment by thomashdk** [comment] 2021-12-02 14:03
Finally figured it out.

On my v8 tab I have translations on them like this.

![image](https://user-images.githubusercontent.com/6445636/144436980-ae9f0f26-502a-4fba-b2fa-8ce74665094f.png)

v9 don't like that in the nested content. When I remove # then it works...

**Comment by dutchbreeze** [comment] 2022-02-14 13:03
I'm getting the exact error on Umbraco 9.2. Just upgraded to 9.3 to see if there's any fix, but no luck. We don't use translation, so no # signs in any name or alias (hoewever we will be using it in the near future on this project).

In our situation we're using 9.3 and Perplex Content Blocks in combination with a nested content property.

Any ideas?

**Comment by kjac** [comment] 2023-01-12 15:21
Hi @thomashdk,

Sounds like you've been on quite the investigation task here. Thanks for reporting it - and sorry for the late response.

I can reproduce this on V10, we need to have a look at what's going on here.

This issue however is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/11705 ... I will close this one and cross reference them.

**Closed by kjac** 2023-01-12 15:21 UTC
Labels: type/bug
