### ISSUE TITLE
Serilog log viewer backoffice search returning no results

### ISSUE THREAD

**Issue by DanDiplo** [umbraco/Umbraco-CMS#13997] opened 2023-03-22 10:19 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.1

### Bug summary

Performing a keyword search in the back-office **Log Viewer** (under **Settings**) never returns any results.

### Specifics

The serilog keyword search never returns any results, even for a keyword that appears in the logs.

For instance, below you can see that "released" appears in the log entries:

![image](https://user-images.githubusercontent.com/6676168/226872229-af600ea9-9f8a-465b-a7ec-9434d7620f04.png)

But searching for "released" yields no results:

![image](https://user-images.githubusercontent.com/6676168/226872540-faeb269a-59da-4693-a413-1656610db192.png)

No keyword seems to work. I've confirmed this with other Umbraco users on Discord.

Most of the predefined filters do return results, but not a "plain" search.

### Steps to reproduce

Go to `Settings > Log Viewer`

Click `All Logs`

Enter a keyword that you know appears in the logs (eg. "document" or "application") and hit the "Search" button.

No results are returned.

### Expected result / actual result

Results that matched the keyword.

**Comment by nul800sebastiaan** [comment] 2023-03-22 12:16
Thanks, this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/13715 and it's fixed for the upcoming 10.5 / 11.2 versions.

**Closed by nul800sebastiaan** 2023-03-22 12:16 UTC
Labels: type/bug

**Comment by DanDiplo** [comment] 2023-03-22 13:02
@nul800sebastiaan Thanks. I always search for an existing open issue before filing an issue. Maybe you shouldn't close issues until they are released to avoid this?

**Comment by nul800sebastiaan** [comment] 2023-03-22 13:08
We already have a lot of admin work on our internal tracker and here on GitHub that is far easier to do at the time a PR is merged for the next release. At this time it's not feasible for us to keep things open until they are released.
