### ISSUE TITLE
Email incorrectly marked as Required when changing User's Group Access in Microsoft Edge

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#4020] opened 2019-01-09 13:56 UTC
Using the Microsoft Edge browser, edit an existing User's Access Groups, eg change or try to assign them to a different group, when you press Save after doing so, all is fine in Google Chrome, the user is updated as expected but in Microsoft Edge, the user isn't updated and the Email field is highlighted as being required, even though it clearly contains a valid email address!!

![image](https://user-images.githubusercontent.com/260802/50903319-600f6080-1415-11e9-85e4-e495621cdec0.png)

Actually just saving a User in Microsoft Edge with a valid Email Address in place will trigger the error. (but you can create them ok, no problems on the Create user screen, it's just something wrong with validation of Email Address field when you save a user on the user profile screen...

.. if you edit the email address, eg add a number to it, it saves fine, then revert back to the old email address (without leaving the screen) it saves fine. - but if you click away and then come back to the user, and press save, or change groups and press save, you get the Required error! Weird!

I'm terrible at explaining bugs, but hopefully you get the gist, Microsoft Edge, Save A user, see the error...

**Comment by kjac** [comment] 2019-01-09 14:34
Is this on 7.13? I recall having fixed something similar not too long ago.

**Comment by nul800sebastiaan** [comment] 2019-01-09 15:03
Yep, that should be fixed in 7.13 (can't reproduce it there at least). 

It was this PR: https://github.com/umbraco/Umbraco-CMS/pull/3456

**Closed by nul800sebastiaan** 2019-01-09 15:03 UTC

**Comment by marcemarc** [comment] 2019-01-09 15:21
Thanks, yes it was 7.12.4, I had a hunt for a fix, but didn't try it in 7.13! I knew I'd forget if I didn't raise it.

**Comment by nul800sebastiaan** [comment] 2019-01-09 15:50
Oh yes, better safe than sorry  👍
