### ISSUE TITLE
Download media folders etc.

### ISSUE THREAD

**Issue by simonbusborg** [umbraco/Umbraco-CMS#7843] opened 2020-03-25 09:58 UTC
As there is no possibility to restore media items in Umbraco Cloud, it would be a nice addition to the media library, if you could download single media items, media folders, multiple media folders or the full media library.

**TL;DR:** Make media folder downloadable, through actions menu or right-click menu 🙂

What are your thoughts on this one @nielslyngsoe?

**Comment by nul800sebastiaan** [comment] 2020-03-25 10:58
Thanks, this is not a thing for @nielslyngsoe though, we need to update Deploy.. ;-) I'll close this as a duplicate of https://github.com/umbraco/Umbraco.Cloud.Issues/issues/102 and we'll try to get this done in the next few weeks! 👍

**Closed by nul800sebastiaan** 2020-03-25 10:58 UTC

**Comment by nielslyngsoe** [comment] 2020-04-02 12:12
@simonbusborg I love the proposal and it sounds like it's coming soon to a version of Deploy near you! Thanks for reporting it.
