### ISSUE TITLE
Umbraco 13 Webhook - Empty 'General' window in create screen

### ISSUE THREAD

**Issue by royberris** [umbraco/Umbraco-CMS#15236] opened 2023-11-16 15:31 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-RC2

### Bug summary

The Create webhook screen contains an empty 'General' box with no information.

![image](https://github.com/umbraco/Umbraco-CMS/assets/25608596/84e86b6a-c30b-4545-b724-3f410c8fd00f)

### Steps to reproduce

Create a new webhook with 13.0.0-RC2

### Expected result / actual result

I would expect the box to not appear if it shows no information.

**Comment by bjarnef** [comment] 2023-11-17 09:26
This is not a bug, but a feature 😅
It is because the webhook hasn't been created yet and thus no id/key yet. It is the same for datatype, so it is expected behaviour.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/7f21b36b-7ca5-4310-b949-8eb54bc913ce)

**Comment by Zeegaan** [comment] 2023-11-17 10:03
Yea as @bjarnef it is expected behavior, so I will close this. 

Thanks for reporting it though, and please report anything else you find 🙏

**Closed by Zeegaan** 2023-11-17 10:03 UTC
Labels: type/bug
