### ISSUE TITLE
Save media type crashes

### ISSUE THREAD

**Issue by buttermilklemon** [umbraco/Umbraco-CMS#5899] opened 2019-07-15 11:21 UTC
We found an error when saving the media type. When we try to save a media type, we get an error message "System.NullReferenceException: Object reference not set to an instance of an object". 
This also happens with media types that have not been changed.

Reproduction
------------

- Get fresh umbraco installation 8.1
- Go to media types section
- Save file shows error

**Comment by kjac** [comment] 2019-07-15 11:26
Hi @buttermilklemon, thanks for reporting. This looks like a duplicate of #5894?

**Comment by esn303** [comment] 2019-07-15 17:19
Hey @kjac it looks like it is, but this also occures even if you don't change a thing. Just open the mediatype definition and click save. Does your PR account for this?

**Comment by kjac** [comment] 2019-07-15 17:20
I do believe it does 😀

**Comment by esn303** [comment] 2019-07-15 17:22
I was unable to build with your fix, so I couldn't test (not blaming you, but my inability!) 😬 Hence the stupid question. 😉

**Comment by Shazwazza** [comment] 2019-07-16 11:15
will close as a duplicate

**Closed by Shazwazza** 2019-07-16 11:15 UTC
