### ISSUE TITLE
Invalid non-ASCII or control character in header

### ISSUE THREAD

**Issue by warrenatatlas** [umbraco/Umbraco-CMS#12105] opened 2022-03-08 01:01 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Special characters for media elements is stopping the file from being loaded.
The files load correctly on the fron end of the site, and in the Media section too, however when trying to link them from the Content section they are not appearing.

### Steps to reproduce

Editing content and uploading an image with the media selection at
https://localhost:44354/umbraco/#/content/content/edit/1216

The image uploaded is named "jan-kopřiva-4502161.jpg" 
![image](https://user-images.githubusercontent.com/88474777/157144591-4f7e1408-799f-474e-93ff-810aae89fc68.png)
![image](https://user-images.githubusercontent.com/88474777/157144648-1d48c607-1a8c-4dae-8ee5-afad409cd579.png)

Browsing the image source at:
https://localhost:44354/umbraco/backoffice/umbracoapi/images/GetBigThumbnail?originalImagePath=%2Fmedia%2Fu4ahz3gd%2Fjan-kop%C5%99iva-4502161.jpg&rnd=0.3970329618491797

I see:
![image](https://user-images.githubusercontent.com/88474777/157144708-f95772b9-fdce-4af8-94cb-e1c354d80e89.png)

However in the Media seciont it loads correctly:
![image](https://user-images.githubusercontent.com/88474777/157144783-19ca2b08-5a43-440d-97c4-72284fbfe2af.png)

---
_This item has been added to our backlog [AB#17818](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17818)_

**Comment by nul800sebastiaan** [comment] 2022-03-08 11:54
Heya @warrenatatlas - thanks for the report, unfortunately I can't reproduce the problem. Am I correct in assuming you are using the Azure blob storage provider? We are indeed seeing similar problems with that. https://github.com/umbraco/Umbraco.StorageProviders/issues/32

**Comment by nul800sebastiaan** [comment] 2022-03-08 11:56
Ah but you're right, the `GetBigThumnail` method is doing something that doesn't seem to work: 

![image](https://user-images.githubusercontent.com/304656/157233495-ccf6e326-4772-4146-90c4-41d993909864.png)

We'll have to have a look! 👍

**Comment by kjac** [comment] 2023-01-09 05:50
This one has indeed been fixed 😄 closing it now.

**Closed by kjac** 2023-01-09 05:50 UTC
Labels: state/sprint-candidate, type/bug
