### ISSUE TITLE
Media picker should support a minimum and a maximum number of items.

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#4922] opened 2019-03-08 21:46 UTC
Today it is only possible to select whether a media picker is allowed to choose one item or multiple items. I would love to see the same settings as in the Multinode tree picker where you can specify the minimum and a maximum number of allowed items.

**Comment by kjac** [comment] 2019-03-09 19:22
There's a migration challenge here. Having "Minimum number of items" and "Maximum number of items" there's no longer any need for "Pick multiple items". Which means... how to migrate? 

A suggested approach could be: 

- If "Pick multiple items" is set to true, both "Minimum number of items" and "Maximum number of items" should be set to 0 (no limits).
- If "Pick multiple items" is set to false, "Minimum number of items" should be set to 0 and "Maximum number of items" should be set to 1.

**Comment by nul800sebastiaan** [comment] 2020-01-29 08:34
Oh no, never replied to this 🙈 Someone asked about it and this sounds sensible to me, taking @kjac's suggestions into account.

I think the only concern might be that we'd need to update Deploy to support these new options as well, I am not sure they will be picked up automatically.

And then there's a migration issue as well, not sure if Deploy will pick up on the migrated content. Anyway, we can figure that out later. For now it would be great to work on, sure!

**Comment by nul800sebastiaan** [comment] 2020-01-29 14:28
Feedback on the Deploy part: this is no problem, Deploy will pick up on the new config with no problem. So ignore my concerns! 👍

**Comment by bjarnef** [comment] 2021-01-13 23:17
I think this is similar to the condiguration changes I suggested in https://github.com/umbraco/Umbraco-CMS/issues/8471

Maybe "Disable folder select" would also be obsolete if we instead can configurate allowed media types 👍

**Comment by emma-hq** [comment] 2021-03-09 10:57
Hey folks,

I'm going to close this one as a duplicate of #8471, 

Emma

**Closed by emma-hq** 2021-03-09 10:57 UTC
Labels: community/up-for-grabs, type/feature
