### ISSUE TITLE
Empty recycle bin does not work with mysql server

### ISSUE THREAD

**Issue by maxemilian** [umbraco/Umbraco-CMS#3032] opened 2018-09-25 12:02 UTC
Umbraco reports an error when the recycle bin is purged. 

Reproduction
------------
Umbraco version 7.8.1
MySQL: mariadb.12.2.13

Create/Delete some items
Empty recycle bin

### Bug summary
Recycle bin does not empty, error is displayed

### Specifics

Trace log:
 2018-09-25 13:07:04,186 [P4208/D3/T59] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (2c323f90).
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'umbracoRedirectUrl' is specified twice, both as a target for 'DELETE' and as a separate source for data
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass2_0.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
 2018-09-25 13:07:04,186 [P4208/D3/T59] ERROR Umbraco.Core.Persistence.Repositories.RecycleBinRepository`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Umbraco.Core.Models.IContent, Umbraco.Core, Version=1.0.6614.16975, Culture=neutral, PublicKeyToken=null]] - An error occurred while emptying the Recycle Bin: Table 'umbracoRedirectUrl' is specified twice, both as a target for 'DELETE' and as a separate source for data
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'umbracoRedirectUrl' is specified twice, both as a target for 'DELETE' and as a separate source for data
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass2_0.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
   at Umbraco.Core.Persistence.Repositories.RecycleBinRepository`2.EmptyRecycleBin()
 2018-09-25 13:07:04,202 [P4208/D3/T59] ERROR Umbraco.Web.Editors.ContentController - Unhandled controller exception occurred
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'umbracoRedirectUrl' is specified twice, both as a target for 'DELETE' and as a separate source for data
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass2_0.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
   at Umbraco.Core.Persistence.Repositories.RecycleBinRepository`2.EmptyRecycleBin()
   at Umbraco.Core.Services.ContentService.EmptyRecycleBin()
   at Umbraco.Web.Editors.ContentController.EmptyRecycleBin()
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---

**Comment by maxemilian** [comment] 2018-09-25 12:04
... items can be removed manually using the delete function of the recycle bin. But not funny with 1000 items to delete, 10 at a time..

**Comment by dawoe** [comment] 2018-09-25 12:07
Hi @maxemilian 

I see you are using 7.8.1. Can you reproduce the issue on the latest version of Umbraco ?

If you can reproduce it on vLatest I would suggest you try it with MS SQL server or SQL CE to rule out if it is in the MySql implementation.

Dave

**Comment by maxemilian** [comment] 2018-09-25 12:14
Hi @dawoe 
thank you for the quick answer. Upgrade is not that easy, The website affected should go online in 2 hrs ;)
I have seen a similar problem with SQL Server and older versions of Umbraco. Using version 7.11.x with SQL Server works... but migration would be a problem...
Maybe it's just a cascade delete or something else which is missing, and I hoped you can help me out with a simple statement :)
Max

**Comment by nul800sebastiaan** [comment] 2018-09-25 12:44
Hey there @maxemilian - that's a slightly older version. I can't remember if this is actually fixed in a later version of Umbraco but I do know we've made some MySQL updates since then. Anyway, I'll close this issue for now until you or someone else can test if this is still an issue on the latest version. If it is, we can look into fixing it.

Thanks!

**Closed by nul800sebastiaan** 2018-09-25 12:44 UTC
