### ISSUE TITLE
'umbMigrationV14' property in 'Configuration' causes content transfer issues with Umbraco Deploy

### ISSUE THREAD

**Issue by RosenPetrovFFW** [umbraco/Umbraco-CMS#16587] opened 2024-06-11 13:50 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

'umbMigrationV14' Configuration field is generated multiple times locally and in the cloud with a different timestamp which causes problems with the content transfer.

### Steps to reproduce

We did an upgrade from Umbraco 13 to Umbraco 14. 

After we pushed the upgrade to Umbraco Cloud we immediately got auto-commit with changed data types. We talk about mainly custom data types based on default ones (like Content picker with some selected root and such) but also default ones. 

This is an example .uda file content:
```
{
  "Name": "Multiple Image Media Picker",
  "EditorAlias": "Umbraco.MediaPicker3",
  "EditorUiAlias": "Umb.PropertyEditorUi.MediaPicker",
  "Configuration": {
    "filter": "cc07b313-0843-4aa8-bbda-871c8da728c8",
    "multiple": true,
    "validationLimit": {},
    "enableLocalFocalPoint": false,
    "ignoreUserStartNodes": false,
    "umbMigrationV14": "2024-06-10T11:19:48.3239574\u002B03:00"
  },
  "Udi": "umb://data-type/0e63d883b62b479988c3157f82e83ecc",
  "Dependencies": [
    {
      "Udi": "umb://media-type/cc07b31308434aa8bbda871c8da728c8",
      "Mode": "Exist"
    }
  ],
  "__type": "Umbraco.Deploy.Infrastructure,Umbraco.Deploy.Infrastructure.Artifacts.DataTypeArtifact",
  "__version": "14.0.1"
}
```

When we check the auto-commit I can see that the only difference is in this 'umbMigrationV14' field. Locally, when we did the upgrade it was set to another time. 

Later on when we clone down the code from Umbraco Cloud and when I start it, we immediately get pending changes in the same Data Types that were changed in the Cloud, now with the new time. Content transfer fails because it complains that the Schema is different in the Configuration section. 

We found this code:
https://github.com/umbraco/Umbraco-CMS/blob/0bb46b9667182d57f4138f4f39f9fbebdd56cbac/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs#L118

In my opinion, there is a problem, and the if check should be changed to include a check if the 'umbMigrationV14' has been set. Something like (of course could be written in a cleaner way)

`if (updated && configurationData is not null && configurationData[""umbMigrationV14""] == null)`

### Expected result / actual result

'umbMigrationV14' Configuration field is not updated multiple times and content transfer works.

**Comment by ronaldbarendse** [comment] 2024-06-27 09:40
Thanks for reporting this @RosenPetrovFFW! The data type configuration migration in v14 already skips items that already have this key set, see:
https://github.com/umbraco/Umbraco-CMS/blob/0bb46b9667182d57f4138f4f39f9fbebdd56cbac/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs#L70-L74

If you upgrade your local environment from v13 to v14, the migration has run locally and written the updated UDA files (with `umbMigrationV14` already set). But if you push the upgrade/updates to another environment, the CMS will first run the migrations before Deploy processes the UDA files, so the `umbMigrationV14` value isn't set yet and the data type configuration migration will run again. The root of the problem is that before Deploy processes the UDA files that were pushed, they are already overwritten with the migrated versions, which will also overwrite any other changes 😬

Changing the `umbMigrationV14` date/time to a constant value will avoid the schema mismatches in most cases, but pushing any other changes (like a new/updated data type configuration value) will still be overwritten and still cause a schema mismatch between environments... We'll have to figure out why Deploy overwrites the UDA files after the migration: if that's because the CMS migration sets `RebuildCache = true`, uses services that fire notifications when it should only do database updates, etc. or if it's something within Deploy itself. If it's something that needs to be fixed in Deploy, I'll transfer this issue to the correct issue tracker.

**Comment by bergmania** [comment] 2024-07-04 05:38
Should be fixed by https://github.com/umbraco/Umbraco-CMS/pull/16732

**Closed by bergmania** 2024-07-04 05:38 UTC
Labels: type/bug, release/14.1.0

**Comment by ronaldbarendse** [comment] 2024-07-04 08:19
> We'll have to figure out why Deploy overwrites the UDA files after the migration: if that's because the CMS migration sets `RebuildCache = true`, uses services that fire notifications when it should only do database updates, etc. or if it's something within Deploy itself. If it's something that needs to be fixed in Deploy, I'll transfer this issue to the correct issue tracker.

I managed to figure out why this issue occurred: when Deploy processes the data type configuration (during a schema deployment/extraction), the CMS parsed the `umbMigrationV14` configuration value into a `DateTime`, losing the time zone information and subsequently writing a different value back to the UDA file (depending on whether your local environment uses a different time zone).

PR https://github.com/umbraco/Umbraco-CMS/pull/16732 fixes this by adding support for parsing into a `DateTimeOffset`, which keeps the time zone information and therefore doesn't write a different value after the data type is processed/saved.
