### ISSUE TITLE
Data for properties added through compositions lost after culture change

### ISSUE THREAD

**Issue by mszwi** [umbraco/Umbraco-CMS#8221] opened 2020-06-02 12:41 UTC
When inheriting properties though Compositions. The inherited properties don't get updated after changing the culture of the parent document type. 

In this example, the field type was the default Grid Layout editor type.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.2 using AppData models.

### Reproduction
------------

1. Create a parent DocType (Parent), with property "Grid Layout"
2. Create another DocType (Sibling) and inherit the property via the "Compositions" Button.
3. Create some Documents and add content to the field "Grid Layout"
4. Add a new language
5. Change the settings of Parent DocType to "Allow varying by culture" = true
6. Change the setting of "Grid Layout" property to on DocType "Parent" to "Allow varying by culture" = true
7. The property "Grid Layout" on the DocType "Sibling" has not changed and content is still there.
8. Change the setting on DocType "Sibling" to "Allow varying by culture" = true
9. Check the Sibling document created in step 3. the content is gone.

### Expected result

I expected that the data would be retained after changing the allow varying by culture setting of the DocType

**Comment by nul800sebastiaan** [comment] 2020-06-03 14:28
Hmm, I can indeed replicate this behavior, that's not nice! 

![8221](https://user-images.githubusercontent.com/304656/83649173-32e9c200-a5b7-11ea-9181-8e380a011fe6.gif)

**Comment by nul800sebastiaan** [comment] 2020-06-04 06:58
Ah, it actually looks like this has been reported already, I'll close this as a duplicate of #7471. Make sure to subscribe to that issue for progress.

**Closed by nul800sebastiaan** 2020-06-04 06:58 UTC
Labels: state/needs-investigation
