### ISSUE TITLE
'Save and publish' button changes to 'Save and schedule' when only unpublish date is selected

### ISSUE THREAD

**Issue by AlphaDelta** [umbraco/Umbraco-CMS#2936] opened 2018-09-06 20:49 UTC
### Bug summary

When a page is given an unpublish date, but not a publish date, the 'Save and publish' button will change to 'Save and schedule' and will change functionally from saving and publishing to only saving.

### Specifics

**Umbraco version:** 7.12.1
**Browser:** Chrome 68 (Have not checked other browsers)

**Screenshots**
![image](https://user-images.githubusercontent.com/2088238/45184252-8613d100-b27a-11e8-86a1-87b47d262002.png)

### Expected result

Page is published, but has expire date.
The expected outcome of clicking the save button in the bottom right of the backoffice is to always save and publish unless the page has a publish date and is currently unpublished (ie, scheduled for publishing).

### Actual result

Save button only saves and displays 'Save and schedule'

**Comment by AlphaDelta** [comment] 2018-09-07 02:54
I believe [this line in contenteditinghelper.service.js](https://github.com/umbraco/Umbraco-CMS/blob/46b0063921f1479881459c0296469b48c2afae83/src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js#L258) is causing this.

It is explained in the comment above it that the intention _is_ for the button to turn to 'Save and schedule' if there is either a publish or unpublish date, it does not state why though.

**Comment by nul800sebastiaan** [comment] 2018-09-07 08:37
I think this works as intended. As soon as you set either date you're scheduling the content for either publish or removal.
There is some wording we need to work on, as reported in https://github.com/umbraco/Umbraco-CMS/issues/2905 - I'll close this one in favor of the earlier reported issue!

**Closed by nul800sebastiaan** 2018-09-07 08:37 UTC
