### ISSUE TITLE
Datetime picker on media item

### ISSUE THREAD

**Issue by Lantzify** [umbraco/Umbraco-CMS#12272] opened 2022-04-20 09:05 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v8.18.3 & v9.4.1

### Bug summary

When you save a media item that has a datetime picker the  "You have unsaved changes" popup shows when you try to navigate away from the item. It seems only to be when with a datetime picker. I also tried a textstring. But that didn't cause the popup to show.

If i am not mistakes this happens because the form is dirty?

### Specifics

![Capture](https://user-images.githubusercontent.com/20320733/164191537-3ea6c231-3680-4faf-9146-083e9bf510ae.PNG)

### Steps to reproduce

1. Add a datetime picker to media type "Image".
2. Navigate to a image
3. Add a date
4. Save
5. Try to navigate away

### Expected result / actual result

The  "You have unsaved changes" popup should not show up

**Comment by nul800sebastiaan** [comment] 2022-07-18 06:42
Sorry for the late reply @Lantzify - Totally missed this one. This issue has been reported again at: https://github.com/umbraco/Umbraco-CMS/issues/12617

There's a bit more info on that one, so I'll close this one as a duplicate of the newer issue with the added information. Thanks for the report!

**Closed by nul800sebastiaan** 2022-07-18 06:42 UTC
Labels: type/bug
