### ISSUE TITLE
Reorder property to tab only switch tab first time

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#12144] opened 2022-03-17 12:39 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

When you want to reorder properties to another tab and drag the property to another tab, it switch to this tab, where you can drop the property.

However when you go back to first tab again and do the same with a second property nothing happens.

You will have to save the document type to reorder more properties to other tabs.

https://user-images.githubusercontent.com/2919859/158810847-d5769ad8-648e-41c6-8444-4a3fe8fc308e.mp4

### Steps to reproduce

Reorder a property from one tab to another on a content type.
Next do the same with a second property.

Notice the tab doesn't switch, so the property can be dropped on the new tab.

However I did notice it does work if you just drag to one of the other tabs first and back to the tab where you want to move the property to.

**Comment by mrgiao** [comment] 2022-07-14 12:46
I can confirm that this is still a bug in version 10.0.1

**Comment by kjac** [comment] 2023-01-09 07:55
Looks like this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/12810, fixed in 
https://github.com/umbraco/Umbraco-CMS/pull/13579

**Comment by kjac** [comment] 2023-01-09 07:57
Closed as a duplicate

**Closed by kjac** 2023-01-09 07:57 UTC
Labels: type/bug
