### ISSUE TITLE
List view issue with infinite editor option enable

### ISSUE THREAD

**Issue by dKumarmj** [umbraco/Umbraco-CMS#13652] opened 2023-01-10 12:30 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

The issue in [List View](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/listview?q=list+view)

If we are creating multiple parent-child doctypes as list view, and in one of the child doctype, we are selecting another parent content (child as a list view) using a node picker with the show open button enabled.

PFA for more info

https://user-images.githubusercontent.com/58820887/211546999-21434fd4-cb10-43cc-ab0c-af2f28526aff.mp4

### Steps to reproduce

- Create 2 docTypes, **Master** & **Parent**.
- Create another 2 doctypes **Variation** & **Child**, and allow **Variation** as **Master** child and **Child** doctype as **Parent** child respectively.
- Create a list view for **Master** & **Parent** doctypes and enable the **Infinite Editor option**.
- Open **Child**  doctype and create a _node picker_  and allow **Master**  as the doctype & also enable  **Show open button**.
- Start creating content.
- Create Master - Variation content & Parent-Child content.
- Open any of the created Parent Content, and go to list view, where we can see created child contents.
- Open any of the child content, click on the node picker and select any master content.
- Once selected, then try to open from the node picker, and then we can see the wrong button in the list view of the Master content.

The expected result is explained below.

I am attaching Usync Files of those four doctypes and a dataType for the node picker.

[uSyncFiles.zip](https://github.com/umbraco/Umbraco-CMS/files/10382662/ContentTypes.zip)

PFA
https://user-images.githubusercontent.com/58820887/211547310-cfb314e4-e70c-4bb2-98b0-3d059cca98c4.mp4

### Expected result / actual result

The expected result is **Master** -> **Variation** relation, but getting is **Master** -> **Child** relation, when opening from the node picker, and the interesting part is, even we can create wrong content from there, even if we do not allow **Child** doctypes under **Master**!

**Expected**

![Expected](https://user-images.githubusercontent.com/58820887/211551014-905aa1da-18b1-41bb-b8c7-d833abc0cf29.png)

Getting Wrong doctype option

![Wrong](https://user-images.githubusercontent.com/58820887/211551209-9a16b21b-c329-48cf-8e6d-fd3d26d293e9.png)

**Comment by kjac** [comment] 2023-01-11 06:13
Hi @dKumarmj,

Thank you for reaching out 😄 

This has already been reported as an issue - see https://github.com/umbraco/Umbraco-CMS/issues/13355. We'd love some help fixing it. 

I'm going to crosslink the two issues and close this one as a duplicate.

**Comment by kjac** [comment] 2023-01-11 06:14
Closed as duplicate of #13355

**Closed by kjac** 2023-01-11 06:13 UTC
Labels: type/bug
