### ISSUE TITLE
Content node creation - option alignment set incorrectly

### ISSUE THREAD

**Issue by blkpanther5** [umbraco/Umbraco-CMS#5945] opened 2019-07-19 00:01 UTC
**Summary**
When creating a new content node (by clicking the ellipsis or right click + create), the content option labels presented are not aligned correctly as of 8.1.0, and were aligned correctly in 8.0.2. 

**Repro**
Can be reproduced using a fresh install of 8.1.0, after creating a few document types/templates with differing lengths of title and description. Verified in current versions of Chrome, Edge and Firefox.

**Result**
Text alignment is weird, and undesired.
![image](https://user-images.githubusercontent.com/1998538/61499435-64987100-a984-11e9-83f1-3c62dd58c2ea.png)

**Expected**
Beautiful-ness, as it was in 8.0.2!

**Additional Info**
Text in the .menu-label class is inheriting a "text-align:center;" via the browser user agent stylesheet and probably should be explicitly set to align left.

**Comment by kjac** [comment] 2019-07-19 11:16
Duplicate of #5853, PR in #5752

**Comment by Shazwazza** [comment] 2019-07-22 00:39
thanks @kjac closing this one

**Closed by Shazwazza** 2019-07-22 00:39 UTC
