### ISSUE TITLE
v7.15.1 Property Editior - Media Picker - Upload - button is disabled

### ISSUE THREAD

**Issue by elliottjb7** [umbraco/Umbraco-CMS#6075] opened 2019-08-08 08:45 UTC
When creating/editing content the media picker's upload button is no longer active. If I have a need to upload a new media file, I can no longer do so from within the media picker, I now need to manually go into the media location and upload there. After that I can return to the media picker and choose the recently uploaded media. Not Ideal.

On inspection (Chrome/F12) I can see that the button is set to disabled. Please fix

---
_This item has been added to our backlog [AB#2213](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2213)_

**Comment by nul800sebastiaan** [comment] 2019-08-08 17:14
Thanks for reporting @elliottjb7 - this seems to be a little wonky indeed! We'll get it looked at, thanks for reporting!

**Comment by kjac** [comment] 2019-08-08 19:58
@elliottjb7 looks like there's a temporary workaround for you: If you browse the node structure in the picker (open a folder and go back to where you came from), the upload button starts working.

I'm digging into the root cause now.

**Comment by kjac** [comment] 2019-08-08 20:04
Upon further investigation... this only happens when Umbraco can remember your last opened media node (it's in localstorage). I found the culprit, PR incoming.

**Comment by kjac** [comment] 2019-08-08 20:13
PR in #6081

**Comment by kjac** [comment] 2019-08-08 20:25
Turns out this is an issue in V8 as well; PR for V8 in #6082

**Comment by nul800sebastiaan** [comment] 2019-08-09 14:37
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6082

**Closed** 2019-08-09 14:37 UTC
Labels: community/pr, release/7.15.2, type/bug

**Comment by nul800sebastiaan** [comment] 2019-08-09 14:43
Cherry picked to 7.15.2: 79c4d7797cc67ddc70f195e62961addd7613ef2b
And 8.1.3: c87a22f3475bc14f51a42690dc91afa0fabcb63b
