### ISSUE TITLE
v10: Unable to install on 10.0.0-rc4

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#12512] opened 2022-06-01 05:20 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc4

### Bug summary

On v10.0.0-rc4 it's not possible to install a new Umbraco instance via the UI when using a SQL server database.

**Note: This is encountered when running with the `Umbraco.Web.UI` setting in Visual Studio**

We've tried installing on:
* Azure database
* Docker running SQL server
* Local SQL server

### Specifics

It varies between two kinds of errors:

**Error during install:**
(Example from an SQLite install attempt)
```
[07:15:29 ERR] An error occurred during installation step DatabaseInstall
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Umbraco.Cms.Core.Install.InstallException: The database failed to install. ERROR: Database configuration is invalid. Please check that the entered database exists and that the provided username and password has write access to the database.
   at Umbraco.Cms.Infrastructure.Install.InstallSteps.DatabaseInstallStep.ExecuteAsync(Object model)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.ExecuteStepAsync(InstallSetupStep step, Object instruction)
   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.PostPerformInstall(InstallInstructions installModel)
```

**Error during connection**
(Example from a Docker SQL server attempt**)
```
[06:51:29 INF] Acquiring MainDom.
[06:51:29 INF] Acquired MainDom.
[06:51:30 INF] Now listening on: https://localhost:44352
[06:51:30 INF] Now listening on: http://localhost:35092
[06:51:30 INF] Application started. Press Ctrl+C to shut down.
[06:51:30 INF] Hosting environment: Development
[06:51:30 INF] Content root path: C:\Github\TEMP\UmbracoProject2
[06:51:30 WRN] Umbraco must install or upgrade.
[06:52:05 WRN] Configured database is reporting as not being available.
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:360e87a5-3e74-4133-a553-750e32d6780d
Error Number:18456,State:1,Class:14
```

### Steps to reproduce

**Note: This is encountered when running with the `Umbraco.Web.UI` setting in Visual Studio**

1. Create a new umbraco install using the CLI
2. Update the Umbraco version to 10.0.0-rc4 before boot.
3. Change the program.cs as described here: https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/version-specific#version-9-to-version-10
4. Boot & try to install to a database

### Expected result / actual result

Expected to being able to install Umbraco 😄

**Comment by p-m-j** [comment] 2022-06-01 06:48
> ERROR: Database configuration is invalid. Please check that the entered database exists and that the provided username and password has write access to the database.

> Login failed for user 'sa'.

It looks like your database credentials are incorrect.

**Comment by nikcio** [comment] 2022-06-01 07:24
@p-m-j Yeah it's a bit confusing because the credentials are valid and I've tried with multiple methods but I've encountered also encountered the error seen under: "Error during install" both when using a SQL Server and SQLite database. It's a bit 50/50.

**Note: This is when running the Umbraco instance with the `Umbraco.Web.UI` setting or with `dotnet run`**

See also: https://discord.com/channels/869656431308189746/882984410432012360/981222181608505394

**Comment by p-m-j** [comment] 2022-06-01 07:26
I can reproduce following the steps given.

Using the 10.0.0-rc4 template works fine, but following the docs for updating csproj and program.cs doesn't.

**Comment by nikcio** [comment] 2022-06-01 07:38
@p-m-j we only had the 9.5.0 template installed via the CLI. Running the command found here only teaches you to install the latest stable template: https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-templates

So we didn't take the time to figure out how to install a v10 template.

Have you any idea what changes when doing a `dotnet clean` that fixes this issue?

**Comment by p-m-j** [comment] 2022-06-01 07:44
> Have you any idea what changes when doing a dotnet clean that fixes this issue?

Working on establishing the exact reason for this.

If you `dotnet new umbraco` without a `--no-restore` then you get a file `obj/project.nuget.cache` which has lot's of paths to 9.5.0 things so it's probably something in there.

Workarounds

+ `dotnet clean` when it's not working
+ `dotnet new umbraco --no-restore` when wanting to create a new 9.5.0 site to upgrade
+ `dotnet new --install Umbraco.Templates::10.0.0-rc4` to get the updated templates.

**Comment by nikcio** [comment] 2022-06-01 07:45
Great! I guess we can close this again then? 😄

**Comment by p-m-j** [comment] 2022-06-01 07:48
If you're happy to close it sure :) 

Will try work out something that works consistently to put in the upgrade docs to ensure it's smooth sailing.

**Closed** 2022-06-01 07:48 UTC
Labels: type/bug
