### ISSUE TITLE
Umbraco 8.1.1 can't find existing datatypes

### ISSUE THREAD

**Issue by AndersBrohus-MySupport** [umbraco/Umbraco-CMS#6040] opened 2019-08-02 06:55 UTC
A brief description of the issue goes here.
Reproduction
------------

Simply try to add an new property to an document type.

### Bug summary

After upgraded my project to Umbraco 8.1.1 from Umbraco 8.0.2 i get an error each time i'm adding an new property to an document type, and then i can only create new data types i can't use the existing.

### Specifics

We are using Umbraco 8.1.1, and this happened after upgrading from 8.0.2 :)
And it's happening in all major browsers.

Complete error is here

```
An error occured
Sekvensen indeholder mere end ét tilsvarende element

Exception Details
System.InvalidOperationException: Sekvensen indeholder mere end ét tilsvarende element

ved System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   ved Umbraco.Web.Editors.DataTypeController.GetGroupedDataTypes() i d:\a\1\s\src\Umbraco.Web\Editors\DataTypeController.cs:linje 325
   ved lambda_method(Closure , Object , Object[] )
   ved System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   ved System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   ved System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Expected result

I expected to see my existing data types and not have to create new data types.

### Actual result

I can only choose to create new datatypes and can't use the existing onces.

**Comment by stevemegson** [comment] 2019-08-02 10:36
That exception suggests that you have two property editors trying to use the same alias. Trying to get the list of existing data types then fails because it can't work out which of the clashing property editors the existing data type should be using.

It's not immediately clear why any of that would have changed between 8.0.2 and 8.1.1, though.

Could you put this code in a macro or template on a test page somewhere and post the results? It'll list the property editors being detected on your site, which should tell us which property editors are the problem.

    <ul>
    @foreach(var p in global::Umbraco.Web.Composing.Current.PropertyEditors.OrderBy(p => p.Alias)){
    <li>@p.Alias @p.GetType().AssemblyQualifiedName</li>
    }
    </ul>

**Comment by AndersBrohus-MySupport** [comment] 2019-08-02 10:49
Oh .. 
I will try do that later! :)

**Comment by nul800sebastiaan** [comment] 2019-08-05 11:55
It seems like something went wrong somewhere in your setup @AndersBrohus-MySupport - I can't reproduce this problem in an upgrade from 8.0.2 to 8.1.1. I also haven't seen other people with this problem yet.

I wonder what might have caused this, maybe consider which packages you have installed etc? For now I'll close this, let us know if you find anything!

**Closed by nul800sebastiaan** 2019-08-05 11:55 UTC

**Comment by AndersBrohus-MySupport** [comment] 2019-08-07 13:31
It was a mistake i had a copy of a folder which had a datatype the same datatype as another folder .. 😬 

It works correctly now 👍

**Comment by stevemegson** [comment] 2019-08-07 16:13
Hopefully that's a pretty rare problem, though it wouldn't hurt to have PropertyEditorCollection's constructors check for duplicate aliases and log a warning. At least that would point you in the right direction.

**Comment by nul800sebastiaan** [comment] 2019-08-07 17:21
Sure thing. Let's see if anyone else ever reports this though, seems like a big edge case :-)

It seems impossible at the moment to actually create this situation from the interface, so I'm not exactly sure how this would have happened in the first place.
