### ISSUE TITLE
Umbraco 8.9 cannot delete invited user

### ISSUE THREAD

**Issue by HTDL-Andrew** [umbraco/Umbraco-CMS#9298] opened 2020-10-28 13:50 UTC
Cannot delete an invited user from the back office.

System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_umbracoUserLogin_umbracoUser_id". The conflict occurred in database "XXX", table "dbo.umbracoUserLogin", column 'userId'.
The statement has been terminated.

**Comment by nul800sebastiaan** [comment] 2020-11-10 14:18
Thanks @HTDL-Andrew - I don't have this problem in 8.9.1 so I assume it's been fixed by now. Let us know if you have other steps to reproduce.

![9298](https://user-images.githubusercontent.com/304656/98685601-d8277400-2367-11eb-8e87-06fc5066ec03.gif)

**Closed by nul800sebastiaan** 2020-11-10 14:18 UTC

**Comment by galaxylinq** [comment] 2021-02-24 19:06
Hi, I know this is a close case, I could open a new case, but i figured will try posting here first.
Apparently, this is an issue in Umbraco version 7.13.2 assembly: 1.0.6974.19955

Log error pointing to the cause:
System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_umbracoUserLogin_umbracoUser_id". The conflict occurred in database "HABCINTDB", table "dbo.umbracoUserLogin", column 'userId'.
The statement has been terminated.


I do see records here: 
SELECT        dbo.umbracoUserLogin.*
FROM            dbo.umbracoUserLogin
WHERE        (userId = 13)

and getting UI error:  Server error: Contact administrator, see log for full details. Failed to delete the user 13 


I am just thinking to alter the constraint and set on delete cascade, but I wonder if there are related tables that might start erroring out.

Any feedback is much appreciated,
Ivan S.

**Comment by DevonFraser** [comment] 2021-03-15 15:01
@HTDL-Andrew @galaxylinq The following steps will replicate the issue

- Send user an invite
- Click invite link (do not set password)

The status of the user will still be "invited" but clicking delete on the user will throw that exception. What we noticed is that once the link is clicked, an entry will be added to the umbracoUserLogin table.
