### ISSUE TITLE
Saving a member without the sensitive data role, wipes fields you can't see.

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#14723] opened 2023-08-25 16:28 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

If you have a user that doesn't have the sensitive data role, and that user saves a member, it will set all values the user can't see to a default value.

The reason I noticed: After saving IsApproved got set to False.

### Steps to reproduce

1. Create a member, set IsApproved to true.
2. Create a user without the Sensitive Data role
3. Login as user, go to member from step 1, save. 

### Expected result / actual result

IsApproved is now set to false, rather than keeping it set to true.

I expect it to leave values a user can't see alone.

**Comment by nikolajlauridsen** [comment] 2023-08-29 11:28
Duplicate of #14717

**Closed by nikolajlauridsen** 2023-08-29 11:28 UTC
Labels: type/bug

**Comment by LennardF1989** [comment] 2023-08-29 12:19
Heh, I think that typo in the title threw my search off, because I checked before reporting.

**Comment by nikolajlauridsen** [comment] 2023-08-29 12:33
It happens 😉 But yes this seems like something we indeed should have a look at 😄
