### ISSUE TITLE
Nested Content value of 0 won't show

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#8530] opened 2020-07-30 20:03 UTC
There is a bug in the Nested Content property editor where if a value is a decimal 0, then it won't show the value, causing validation to fail.

Offending line of code: https://github.com/umbraco/Umbraco-CMS/blob/61892882deaa7a979bcdbeacbfed3b9d09d157cd/src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js#L600

`fromNcEntry[prop.propertyAlias]` in this case will return false if the value is 0, leaving `prop.value` undefined. Instead, this should be something like `typeof(fromNcEntry[prop.propertyAlias]) !== "undefined")`.

**Comment by bjarnef** [comment] 2020-07-31 09:27
@LennardF1989 I guess you have a property in nested content using Decimal property editor `Umbraco.Decimal` (or Numeric `Umbraco.Integer`)?

With the latest changes in `v8/contrib` I can't reproduce this when using Decimal and saving value 0.

![image](https://user-images.githubusercontent.com/2919859/89021422-cf62e300-d320-11ea-8ebf-0c55d2042f35.png)

**Comment by nul800sebastiaan** [comment] 2020-08-03 11:52
I also can't reproduce in 8.5.5 nor in 8.6.2, can you add versions please @LennardF1989 and some steps to reproduce?

I'll close this for now, but we can re-open as soon as we can reproduce the problem!

**Closed by nul800sebastiaan** 2020-08-03 11:52 UTC
