### ISSUE TITLE
Node content should inherit chosen culture

### ISSUE THREAD

**Issue by KristianMedK** [umbraco/Umbraco-CMS#6355] opened 2019-09-17 08:57 UTC
this request is in response to my forum post here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/99054-node-content-always-shows-in-default-culture

When chosing a culture in the left pane, which isn't the default one, you have to change the node content culture everytime you chose a new node, because they alway chose default culture, and not the chosen one for content. 

I'm new to this community, so please let me know, if there's something missing for this feature request, or if it shouldn't be here at all.

**Comment by nul800sebastiaan** [comment] 2019-09-17 09:10
Hmm, strange, I don't see this behavior in 8.1.4 at all, which version are you using?

This is how it works for me: 
![6355](https://user-images.githubusercontent.com/304656/65027998-96559600-d93b-11e9-9620-a42c2867cf30.gif)

If you're running a version lower than 8.1.4 then make sure to upgrade and try again, I remember we updated some language selection issues in recent versions.

I'll close this for now unless you have some more specific steps to reproduce the problem.

**Closed by nul800sebastiaan** 2019-09-17 09:10 UTC

**Comment by KristianMedK** [comment] 2019-09-22 08:55
I've updated to version 8.1.4 and when i run umbraco locally it works, but when i deploy to azure, and try it in production, it still chooses the default language everytime i pick a new node. 

I tried pointing my local version to the prod DB, and it still works, so the only difference is the domain being localhost instead of mydomain.com

Any idea as to why that would break the varying culture default choice in the content pane ?

**Comment by nul800sebastiaan** [comment] 2019-09-22 12:38
Sounds like you might not have deployed all files in the Umbraco folder. Don't forget to update the version in Clientdependency.config on your azure site to make sure the newest versions of the client side files get used.

My tests were on local and on a Cloud site.

**Comment by KristianMedK** [comment] 2019-09-23 07:05
Ended up deploying using a nuget installation of umbraco instead of the visual code version where i had downloaded umbraco and build/run it witu visual code. 

The upgrade went through, and the language issue is fixed. Although i'm not sure why it didn't work using visual code. All files were replaced, and Clientdependency.config was identical to my local version where it worked.
