### ISSUE TITLE
Preview does not work property

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/Umbraco-CMS#11080] opened 2021-09-12 13:56 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v8.14.0, v8.16.0

### Bug summary

Preview does not work properly. It displays the latest published version instead of saved content.
I use 2 languages (EN-UK - default and Swedish)
Tried this with both and see the same result. 

### Steps to reproduce

1. Create a new page.
2. Add content
3. Click save.
4. Click save and preview

### Expected result / actual result

Expected result:
Display a saved content

Actual result:
Preview mode displays published content only.

**Comment by DaveYognaught** [comment] 2021-09-13 13:30
Can't recreate this personally on a v8.16.0 site I'm working on at the moment. EN-UK
Preview works as intended. Saved as draft and visible during preview. Published page remains unchanged. 

Bit limited to duration and what I can show with my gif but you should get the idea hopefully:
https://gyazo.com/545dd55b32619d22e301a14f556c4b8c

Can you go more in depth on how you're creating pages and content. Are you somehow publishing the content prior to preview?

**Comment by AndreyKarandashovUKAD** [comment] 2021-09-15 12:32
It's strange, can't reproduce it with the fresh Umbraco.
will investigate what is wrong with my solution

**Comment by nul800sebastiaan** [comment] 2021-09-21 14:16
I also couldn't repro! I'll close this for now but we can revisit if you have more details. 👍

**Closed by nul800sebastiaan** 2021-09-21 14:16 UTC
Labels: type/bug

**Comment by dvdvliet** [comment] 2021-10-05 13:06
In my case it was caused by overriding the OwinStartup because we needed to add Front-End Member authentication.

See https://github.com/Shazwazza/UmbracoIdentity/issues/144 for the fix that case.

The comment on this line tipped me off for this fix:
https://github.com/umbraco/Umbraco-CMS/blob/d13a555204ecb3e9c31ea57e400757538c87d5d6/src/Umbraco.Web/UmbracoDefaultOwinStartup.cs#L105

**Comment by GertyEngrie** [comment] 2022-03-31 10:33
@AndreyKarandashovUKAD using the blocklist editor in that install?

**Comment by AndreyKarandashovUKAD** [comment] 2022-03-31 10:37
@GertyEngrie Yes, we had blocklist editor. It was our internal issue that I found later.

**Comment by GertyEngrie** [comment] 2022-03-31 10:41
@AndreyKarandashovUKAD Care to share? Have the blocklist editor in 2 installs (v9), both fail to render the preview properly

**Comment by AndreyKarandashovUKAD** [comment] 2022-03-31 10:43
@GertyEngrie it was not related to blocklist editor at all and Umbraco v8/v9.
