### ISSUE TITLE
UmbracoContext.InPreviewMode returning false on Preview mode

### ISSUE THREAD

**Issue by vonbv** [umbraco/Umbraco-CMS#2961] opened 2018-09-11 10:36 UTC
This is related to [this](https://issues.umbraco.org/issue/U4-7908) and [this](https://issues.umbraco.org/issue/U4-7922). We encountered this on 7.11 and on 7.12.2.  The details are already in the linked pages. Basically, for us, when a new content is added and previewed the InPreviewMode  is always false.

**Comment by kjac** [comment] 2018-10-27 10:17
I can't reproduce this on the latest codebase. Maybe I'm doing it wrong.

With this template:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
  Layout = null;
}
<html>
  <body>
    <h1>My super awesome page</h1>
    <strong>Preview: @Umbraco.UmbracoContext.InPreviewMode</strong>
  </body>
</html>
```

This is the result:

![isinpreviewmode](https://user-images.githubusercontent.com/7405322/47602655-2caa6180-d9e2-11e8-9cef-a46b5579f7d1.gif)

**Comment by nul800sebastiaan** [comment] 2018-11-01 14:00
Thanks! I'll close this until we have steps to reproduce in a clean install of 7.12.3.

**Closed by nul800sebastiaan** 2018-11-01 14:00 UTC

**Comment by cleversolutions** [comment] 2019-04-11 20:31
I have a 7.12.3 site where @Umbraco.UmbracoContext.InPreviewMode is always returning false. That said, it's not a clean install, it's a site that has been upgraded numerous times. It's ugly, but I can use Request.Cookies["UMB_PREVIEW"] != null instead to detect preview mode.

**Comment by dhymik** [comment] 2021-07-17 11:18
I observe this error when using UmbracoIdentity, and it is reproduceable.

1. Install Umbraco (latest, 8.15) with default Starter Kit
 -> UmbracoContext.InPreviewMode works

2. Add Nuget package UmbracoIdentity (by Shannon Deminick)
 -> UmbracoContext.InPreviewMode always returns false

After I install UmbracoIdentity into a clean Umbraco 8 installation, `UmbracoContext.InPreviewMode` always returns `false`. The reason is that `Umbraco.Context.Security.CurrentUser` always returns `null` with UmbracoIdentity installed.
