### ISSUE TITLE
V9.0.0-rc003 doesn't install after upgrade

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco-CMS#11106] opened 2021-09-15 12:50 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco version 9.0.0-rc003

### Bug summary

I've tried both upgrading from rc001 -> rc003 and rc001-> rc002 ->rc003 through the package manager console and both upgrades seem to be going well until I try to run the solution. Then I receive a MissingMethodException:

MissingMethodException: Method not found: 'Void Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(Umbraco.Cms.Core.Migrations.IMigrationPlanExecutor, Umbraco.Cms.Core.Scoping.IScopeProvider, Umbraco.Cms.Core.Services.IKeyValueService)'

### Specifics

Umbraco 9.0.0-rc003

When trying to run the project after upgrade, Visual Studio enters break mode and then, when clicking "continue", the page displays a MissingMethodException message:

An error occurred while starting the application.
MissingMethodException: Method not found: 'Void Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(Umbraco.Cms.Core.Migrations.IMigrationPlanExecutor, Umbraco.Cms.Core.Scoping.IScopeProvider, Umbraco.Cms.Core.Services.IKeyValueService)'.

When running the application it first enters break mode:
![image](https://user-images.githubusercontent.com/19406378/133426140-3624e119-a0a5-4f47-b441-b8c68a43276d.png)

When continuing, it shows the error-message in the browser:
![image](https://user-images.githubusercontent.com/19406378/133426162-f12d6ec7-2155-4f79-90a8-386b235612d4.png)

I first tried go directly from rc001 to rc003 and when that didn't work I rolled back to rc001, upgraded to rc002 and then rc003 but it's the same issue. 

### Steps to reproduce

I made a Umbraco 9 version of an Umbraco 8 project and this is the steps I've taken:

- Make a copy of the SQL server database from the Umbraco 8 project and restore it to a new database
- Create a new Umbraco V9.0.0-rc001 project using the dotnet template: https://our.umbraco.com/documentation/UmbracoNetCoreUpdates#prerequisites
- Copied over views, media, classes etc. from the V8 project to the V9 and adjusted the code to work in V9
- Install Umbraco forms 9 beta: https://our.umbraco.com/documentation/UmbracoNetCoreUpdates#prerequisites
- After all the steps above the project is working properly
- Take a backup of the V9 project/database
- Use the "dotnet add <PROJECTNAME> package Umbraco.Cms --version 9.0.0-rc003" command to upgrade to V9.0.0-rc003: https://our.umbraco.com/Documentation/Fundamentals/Setup/Upgrading/general-v9
- Adjust some code for it to work properly (for instance in Startup.cs)
- Build and run the project

This is when the Visual Studio enters break mode and displays the error message

### Expected result / actual result

Expecting to see the installation wizard instead of the error message.

**Comment by nul800sebastiaan** [comment] 2021-09-15 13:42
I've been trying to reproduce and the error seems to be coming from Forms. Make sure to run `dotnet add package Umbraco.Forms -v 9.0.0-beta004` - should hopefully do the trick. 👍 

I'll close this for now but let us know if that still doesn't fix it.

**Closed by nul800sebastiaan** 2021-09-15 13:42 UTC
Labels: type/bug

**Comment by bjornnorlen** [comment] 2021-09-15 14:13
> I've been trying to reproduce and the error seems to be coming from Forms. Make sure to run `dotnet add package Umbraco.Forms -v 9.0.0-beta004` - should hopefully do the trick. 👍
> 
> I'll close this for now but let us know if that still doesn't fix it.

@nul800sebastiaan Awesome, that did the trick. Thanks for the help and keep up the good work 🎉
