### ISSUE TITLE
Failed to acquire write lock for id: -333

### ISSUE THREAD

**Issue by nilaydigiwhiz** [umbraco/Umbraco-CMS#14714] opened 2023-08-23 23:45 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco  11.3.1

### Bug summary

I have website hosted on Azure web app. This website has been migrated from Umbraco 8 to Umbraco 11

Getting the below error and it stops all activity to write to DB so Content Tree becomes blank etc..

```
Umbraco.Cms.Core.DistributedLocking.Exceptions.DistributedWriteLockTimeoutException: Failed to acquire write lock for id: -333.

Microsoft.Data.SqlClient.SqlException (0x80131904): Lock request time out period exceeded.
```

More people have raised it here

https://our.umbraco.com/forum/using-umbraco-and-getting-started/111951-failed-to-acquire-write-lock-for-id-333

### Steps to reproduce

Seems like issue can be replicable as soon as two users access umbraco at same time. 

Other issues are found that when i use  _contentService.SaveAndPublish from code , its getting stuck and looks like thats causing lock on DB

**Comment by Zeegaan** [comment] 2023-08-24 05:38
Hello there! 👋 Thanks for reporting this 🐛 

This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/14195, so I'm going to go ahead and close this 😁

**Closed by Zeegaan** 2023-08-24 05:38 UTC
Labels: type/bug
