### ISSUE TITLE
Public Access - Child Node Permissions 

### ISSUE THREAD

**Issue by parxal** [umbraco/Umbraco-CMS#17709] opened 2024-12-03 10:50 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

I have a parent node with several child nodes. The parent node has public access settings defined. Whenever I create a child node under this parent, it inherits the permissions from the parent.

Use case: I change the permissions of a single child node, and Umbraco applies this change to all the siblings and the parent node as well. Shouldn't the change affect only that specific child node?

### Steps to reproduce

1 - Create a Node (Parent)
2 - Assign public access roles (Parent)
3 - Create a child Node
4 - Change public access roles (Child node)
5 - Check Parent Node Permissions. Will notice that parent public access permissions were changed.

### Expected result / actual result

When I change the public access settings of a specific node, it should only apply to that node itself and not to its siblings or parent.

---
_This item has been added to our backlog AB#46945_

**Comment by NguyenThuyLan** [comment] 2024-12-04 07:33
Hi @parxal , thank you for reporting this issue.
I was able to reproduce it on v14.3.1 and v15.1.0-rc
Looks like the API **/umbraco/management/api/v1/document/{id}/public-access** returns wrong data

**Comment by parxal** [comment] 2024-12-06 10:07
@NguyenThuyLan Hi, do you know what's the priority to fix this issue?

**Comment by kjac** [comment] 2024-12-11 10:30
Hi @parxal,

Thanks for reporting this 👍 I'll have a look at the root cause this week, then I'll have more info.

**Comment by kjac** [comment] 2024-12-12 09:08
Fixed in #17797

**Comment by kjac** [comment] 2024-12-12 09:47
Will be released in V15.1.1 soon 👍

**Closed by kjac** 2024-12-12 09:47 UTC
Labels: status/regression, state/sprint-candidate, type/bug, state/reproduced, area/backend, affected/v14, affected/v15, release/15.1.1
