### ISSUE TITLE
Macro not rendered correct inserted into legacy grid layout editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14587] opened 2023-07-20 18:11 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.0-RC

### Bug summary

I noticed if inserting a macro in the richtext editor in the old/legacy grid editor, the macro isn't rendered correct, e.g. creating a macro "Login" from the partial snippet `<input asp-for="@loginModel.Username" class="form-control" />` doesn't render a text input.

Inserted directly in richtext editor property or render macro directly in template works though.

In home.cshtml of default starterkit:

```
<section class="section section">
    @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")

    <div>
        @Model.Text
    </div>

    @await Umbraco.RenderMacroAsync("Login")
</section>
```

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ff4de02d-4f29-4993-9e7c-997c4685d635)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/3557cb29-c081-46d2-b533-69bf2533361f)

### Steps to reproduce

Create a macro from partial snippet and allow it the be rendered in richtext editor.
Insert macro in old/legacy editor in default starterkit.

Notice no input fields are rendered.

First time publishing I was also able to get "Macro alias: [alias]" in frontend.
I guess this probably has sometime to do with the replacement of TinyMCE v4 to v6.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/eee1ce44-ab9d-4b1d-8a75-7d189fe57c9b)

**Comment by bjarnef** [comment] 2023-07-20 18:18
@iOvergaard although the grid layout editor is deprecated/legacy this still still work right? Can you reproduce this issue?

**Comment by Zeegaan** [comment] 2023-07-21 08:07
I cannot reproduce this 😢  
This is me on v12/dev: 
Inserted RichTextMacro in home content:
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/5098972a-893a-4a16-be32-3a2ed1eb8ea4)

Renders on the front-end 🤔 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/b8d4c226-4b3b-444d-9b8e-aaa5381a6bad)

**Comment by bjarnef** [comment] 2023-07-21 09:18
@Zeegaan but it is inserted into the Block Grid editor right?
Not into the legacy Grid Layout editor.

I know it is legacy, but should still be supported until removed in v13 or v14.

**Comment by bjarnef** [comment] 2023-07-23 21:25
If inserted via macro grid editor it does render though (the preview doesn't look correct though?), but not when inserted in richtext editor in the legacy grid layout editor.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ff9fed39-259e-41b6-8c3b-533f5bd7befa)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/25610bd6-7e67-414c-9ad9-4572808e06e1)

**Comment by elit0451** [comment] 2023-08-15 08:58
I will close this issue based on the comments in the referenced PR.

**Closed by elit0451** 2023-08-15 08:58 UTC
Labels: type/bug
