### ISSUE TITLE
When registering a default controller via DefaultRenderMvcControllerResolver allow it to run if the doctype has no template

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#3300] opened 2018-10-15 12:47 UTC
Sometimes you want to create a hijack controller for all page types that returns non HTML content. Because of this, it makes no sense to give a doctype a template. When using individual hijack controllers, this is fine and these are allowed to successfully run without needing the doctype to have a template. However, if you want to use a custom controller for all routes, and so register it via `DefaultRenderMvcControllerResolver.Current.SetDefaultControllerType` if the doc type doesn't have a template, the "No Template" screen is displayed.

Reproduction
------------

Create a doctype without a template, then create a default controller to handle all requests that returns some none HTML content. When navigating to a route, the default controller won't get hit and the "Non Template" screen will be displayed.

### Expected result

I expected that defining a custom default controller would give the controller full control over the rendering output and so the "No Template" screen should not have displayed and instead I should have been able to see the non HTML content I returned.

### Actual result

No Template content was displayed.

### Possible options
1. If a custom controller is defined as the default controller, don't show the "No Template" content and assume the controller will handled all output.
2. When registering a default controller, add an option to say whether this controller should run if the doctype has no template (defaulting to false for backwards compat) then this way you can have the best of both worlds.

**Comment by dawoe** [comment] 2018-10-15 13:08
Hi @mattbrailsford 

Good catch.  I think the problem is not your default controller. I think it happens earlier in the pipeline : https://github.com/umbraco/Umbraco-CMS/blob/9e564d70eff246b7a4570d2cfcc86231e130e058/src/Umbraco.Web/Routing/PublishedContentRequestEngine.cs#L637

I think if this method doesn't find a template it doesn't even get to your controller.

Will need to some diving in to this. And see how we can do this without breaking changes.

Dave

**Comment by pbres** [comment] 2018-10-15 13:46
Hi @mattbrailsford and @dawoe 

I've also found this one 

https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Mvc/RenderRouteHandler.cs#L400

According to this line if either `FeaturesResolver.Current.Features.Disabled.DisableTemplates` or `routeDef.HasHijackedRoute` would be set to true, it will skip the `publishedContentRequest.UpdateOnMissingTemplate(); // will go 404` part

Pawel

**Comment by dawoe** [comment] 2018-10-15 14:00
`FeaturesResolver.Current.Features.Disabled.DisableTemplates` is still internal. But at first glance this will disable templates entirely. eg...not even possible to set a template on doctype in the backoffice

**Comment by dawoe** [comment] 2018-10-15 14:05
My guess this was added for Umbraco Headless...because you don't have templates there

**Comment by dawoe** [comment] 2018-10-15 14:30
I think the issue happens here :  https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Mvc/RenderRouteHandler.cs#L281

There the default controller is retreived.

And then here there is a check if the assigned controller is different from the default one and then route hijacking is set 

https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Mvc/RenderRouteHandler.cs#L317

But that check should be extended that name also checks if the default controller is different from the built in one.

But maybe that is a breaking change...because than all items that don't have a template assigned will go through the default controller.

Dave

**Comment by pbres** [comment] 2018-10-15 19:32
Hi @dawoe 

maye=be we could add a `HandleByDefaultController` flag to the `RouteDefinition` object, similar to 'HasHijackedRoute`?

This way we could add a condition to this if statement I've pointed out above to skip it when the flag is set to false. It also won't introduce any breaking changes as the value of this flag will be `true` by default.

Pawel

**Comment by dawoe** [comment] 2018-10-16 05:56
Maybe @Shazwazza or @zpqrtbnk can give some input if there is a specific reason why a default controller is not seen as route hijacking.

Dave

**Comment by pbres** [comment] 2018-10-16 07:33
hi @Shazwazza 

the last option is looking promising and seems to be less problematic in implementation

It would be also pretty easy to explain in docs how it works. So if there are no additional reasons to modify `TemplateModel`, I would go for that.

What do you think @dawoe and @mattbrailsford?

Pawel

**Comment by nul800sebastiaan** [comment] 2018-11-14 17:24
I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-06-20 12:31
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-06-20 12:31 UTC
Labels: community/up-for-grabs, help wanted, type/feature
