### ISSUE TITLE
[14.1.1] (Collections) Custom collection does not display chosen icon & name for Workspace View

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#16855] opened 2024-08-02 11:08 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

When configuring a collection of child nodes from a document type and creating a new configuration for the collection of child nodes, where I specify different columns to filter on etc...

I can set the icon and text for the collection to be used for the workspace view however setting these values in the configuration of the collection are not displayed.

### Specifics

<img alt="image" src="https://github.com/user-attachments/assets/94c8bbfb-f6eb-4f49-88df-e9507abda268">

<img alt="image" src="https://github.com/user-attachments/assets/d022344f-2e8b-402f-a447-74c52a0bb5f2">

### Video (contains repro steps & other bugs related to collections)

https://github.com/user-attachments/assets/eddbecfe-ecd8-4c92-9d78-8eb53d531a9f

### Steps to reproduce

* Configure two document types, where one can be created as children
* Set the parent document type to use as a collection
* Create a custom collection configuration
* Set a custom icon and name for the content app (workspace view)
* Create content nodes in this structure
* See that the chosen icon & text is not displayed

### Expected result / actual result

* The chosen icon and text is displayed for the collection of items from the configuration of the collection

**Comment by elit0451** [comment] 2024-08-05 11:17
Hi @warrenbuckley 👋 

It's good to hear from you! Thanks for reaching out and for the video (_Note to anyone reading this in the future: the video has sound_ 🔈 😁 )

 I managed to reproduce this, we will have a look 🙂

**Comment by leekelleher** [comment] 2024-08-06 12:13
Duplicate of issue #16633.

We have a work-in-progress fix, https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2113, but it's not quite ready for release yet.

**Comment by elit0451** [comment] 2024-08-07 12:35
Thanks for pointing this out Lee, I'll close this one then 🙂

**Closed by elit0451** 2024-08-07 12:35 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v14
