### ISSUE TITLE
[15.0.0-rc2]: When using Custom Block List/Grid Views - allow clicking on the preview to open the content editor

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#17399] opened 2024-10-31 11:29 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

Currently I have to manually write my Block List/Grid views to have code that will wrap the markup in an anchor tag in order to open the modal to edit the content for the block.

For better DX I think people implementing custom views for blocks should not have to worry about this detail and keep repeating this logic for every custom block they implement.

### Steps to reproduce

I have to write the following code
```ts
import { html, customElement, LitElement, property, css, unsafeHTML, ifDefined } from '@umbraco-cms/backoffice/external/lit';
import { UmbElementMixin } from '@umbraco-cms/backoffice/element-api';
import { UMB_BLOCK_ENTRY_CONTEXT, UmbBlockDataType } from '@umbraco-cms/backoffice/block';
import { UmbBlockEditorCustomViewElement } from '@umbraco-cms/backoffice/block-custom-view';

@customElement('example-block-custom-view')
export class ExampleBlockCustomView extends UmbElementMixin(LitElement) implements UmbBlockEditorCustomViewElement {

    constructor() {
        super();

        // NOTE: I need this context to get the workspace edit content path in order to get the link for the <a> to wrap my custom block view with
        this.consumeContext(UMB_BLOCK_ENTRY_CONTEXT, (blockEntryCtx) => {
            this.observe(blockEntryCtx.workspaceEditContentPath, (workspaceEditContentPath) => {
                console.log('Workspace Edit Content Path:', workspaceEditContentPath);
                this.editBlockPath = workspaceEditContentPath;
            });
        });
    }

    editBlockPath?: string;

    @property({ attribute: false })
    content?: UmbBlockDataType;

    @property({ attribute: false })
    settings?: UmbBlockDataType;

    override render() {
        return html`
            <a href="${ifDefined(this.editBlockPath)}">
                ${unsafeHTML(this.content?.bodyText.markup)}
            </a>

            <umb-code-block language="Block Content" copy>${JSON.stringify(this.content, null, 2)}</umb-code-block>
        `;
    }

    static override styles = [
        css`
            :host {
                display: block;
                height: 100%;
                box-sizing: border-box;
                background-color: rgba(255,0,0, 0.1);
                border-radius: 9px;
                padding: 12px;
            }

            a {
                text-decoration: none;
                color: inherit;
            }
        `,
    ];
}

export default ExampleBlockCustomView;

declare global {
	interface HTMLElementTagNameMap {
		'example-block-custom-view': ExampleBlockCustomView;
	}
}
```

### Expected result / actual result

Remove the needs for developers implementing custom block views to not have to explicitly implement the code to open the modal when clicking on the preview.

**Comment by mjpraxis** [comment] 2024-11-01 08:47
If you need a copy of my v14 SQLite database, I can send it to you.

**Comment by warrenbuckley** [comment] 2024-11-01 11:52
@mjpraxis huh?! I am not sure this issue needs a SQLite DB?!
Did you mean to comment on another issue?

**Comment by mjpraxis** [comment] 2024-11-01 11:55
> If you need a copy of my v14 SQLite database, I can send it to you.

Ah, sorry. Wrong issue. Thanks for letting me know :-)

**Comment by warrenbuckley** [comment] 2024-11-05 19:28
Leaving this here, as may take a go at this at hackathon
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts

**Comment by nielslyngsoe** [comment] 2024-12-20 12:47
Hi @warrenbuckley 
This is the same as in v.13. It is fully intentional as you may want to write a Custom View that contains a Editorial Experience, in such case you do not want the whole thing to open 'Edit block'. also you maybe only want parts of it. So having to do this gives freedom to different types of implementations.

So as this is by design i will close this issue

**Closed by nielslyngsoe** 2024-12-20 12:47 UTC
Labels: type/bug
