### ISSUE TITLE
[14.1.1] (Collections) Child nodes are visible in the tree

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#16856] opened 2024-08-02 11:17 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

When using Collections, I was not expecting to see the created child nodes also in the tree

### Specifics

<img width="1931" alt="image" src="https://github.com/user-attachments/assets/343f603b-19a5-49b8-8a0b-7fd002fb7404">

## Video (contains repro steps & other bugs related to collections)
https://github.com/user-attachments/assets/88413455-4c3e-4855-9452-0cc240e28f0d

### Steps to reproduce

* Setup a collection for child nodes/documents
* Add sample content
* Expand the content tree and see child items

### Expected result / actual result

I was expecting the same behaviour we have today is that where the child nodes are not visible in the tree, especially as this was designed to avoid issues where these types of collections such as news articles etc, can have hundreds or thousands of nodes so display these in the content tree.

**Comment by elit0451** [comment] 2024-08-05 11:35
Hey @warrenbuckley 👋 

Thanks for reaching out! It seems like this is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16493, so I will close this as intended behaviour. You can see [Mads' comment](https://github.com/umbraco/Umbraco-CMS/issues/16493#issuecomment-2139247159) for reference.

**Closed by elit0451** 2024-08-05 11:35 UTC
Labels: type/bug

**Comment by warrenbuckley** [comment] 2024-08-05 16:41
OK thanks @elit0451 I didn't see that issue.
Curious to know how many child items are needed for a paginated tree to display. Just so I can see the UI and test this out myself

**Comment by nathanwoulfe** [comment] 2024-08-06 00:10
@warrenbuckley page size is 50, looks like you'll be creating some nodes...

**Comment by warrenbuckley** [comment] 2024-08-08 10:46
Cheers Nath - yep time to just hash out some quick & dirty code to create me some stuff
