### ISSUE TITLE
v8 - Request/Bug - Remove unnecessary AngularJs locale/i18n-files. (801 files)

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/Umbraco-CMS#5037] opened 2019-03-21 08:24 UTC
Backoffice uses the angular-i18n package, and that contains 801 language files and they are all included.
The default 20 languages should be fine =)

**Comment by nul800sebastiaan** [comment] 2019-03-21 09:18
What are the default 20 languages and why do you think it's enough?

Do you know if these languages are used anywhere in the backoffice anyway, I am asking out of ignorance, because I honestly have no idea :-)

**Comment by madsoulswe** [comment] 2019-03-21 11:48
The "default 20" that I think off are these:
https://github.com/umbraco/Umbraco-CMS/tree/dev-v8/src/Umbraco.Web.UI/Umbraco/config/lang

And I only think they are used for standard date/number-formating/filters all over Angular?

But there could be people using them with custom translations. =)

**Comment by nul800sebastiaan** [comment] 2019-03-25 13:43
Ah cool, I see what you mean now. The problem here is that more languages CAN be added so if I create `es_mx.xml` with the opening node of `<language alias="en_us" intName="Spanish (Mexico)" localName="Spanish (Mexico)" lcid="" culture="es-MX">` it will show up as an option in the backoffice.

It would, however, be great to ONLY load the languages that are available to backoffice users (so those default 20 and additional custom ones).

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment] 2019-08-29 19:16
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Closed by nul800sebastiaan** 2019-08-29 19:16 UTC
Labels: community/up-for-grabs, help wanted, type/feature
