### ISSUE TITLE
UmbracoUrlAlias is not fully working on multi language websites

### ISSUE THREAD

**Issue by Jalinco1** [umbraco/Umbraco-CMS#14681] opened 2023-08-14 16:20 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1 and 12.1.0

### Bug summary

I just testet some sites with "Alternative URL"
And it seems like its not working on a multilingual site (1-1)

I see and old issue here but it might has been re-introduced?
https://github.com/umbraco/Umbraco-CMS/issues/7383

### Steps to reproduce

On multilanguage site, seo "Alternative URL" only working for the main language.
As soon as I have /de /sv /en etc, the short url is not working as expected.

**Comment by elit0451** [comment] 2023-08-15 08:05
Hi @Jalinco1 👋 

It seems like this issue has never been fixed on multilingual sites. I managed to reproduce the issue on v10, v11 and v12

Based on [this comment](https://github.com/umbraco/Umbraco-CMS/issues/7383#issuecomment-1067834868) on the issue that you referenced:

>  "I think what we really need is a proper property editor that can help editors (!) make links that actually work...
Therefore, we will keep this issue closed as "works as intended". And yes, you all are very correct that it doesn't work as we would WANT.
..."

And there are also a few alternatives by the end of this comment ⬆️ that might help you. Therefore, I will have to close this one as it is also a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/14088

**Closed by elit0451** 2023-08-15 08:05 UTC
Labels: type/bug
