### ISSUE TITLE
Empty page after login to account with group without media start node selected

### ISSUE THREAD

**Issue by mPieczka** [umbraco/Umbraco-CMS#9346] opened 2020-11-04 15:12 UTC
Hi 

When I try to login to a user with a group without media start node selected view is empty, and a lot of error displays in console. 

## Umbraco version

I see this issue on Umbraco versions: 8.8, 8.8.1 and my colleague updated 8.8 to 8.9, and it still exists.

Reproduction
------------

### Bug summary

Empty page after login.

### Specifics

Umbraco log:

{"@t":"2020-11-04T14:53:10.5812652Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt failed for username test@account.co.uk from IP address 127.0.0.1, no content and/or media start nodes could be found for any of the user's groups","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":24636,"ProcessName":"iisexpress","ThreadId":140,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"WS-MARCINP","Log4NetLevel":"INFO ","HttpRequestNumber":18,"HttpRequestId":"faeb00d1-9b5f-4655-a280-ca64602225d9"}

Screenshoot:

![image](https://user-images.githubusercontent.com/26299040/98126448-e6801680-1eb5-11eb-987f-f11efc057f5c.png)

### Steps to reproduce

1. Create new empty visual studio c# web project, and install Umbraco via NuGet.
2. Run the project and got through installation process.
3. Remove media start node from, for example editors group, or create a new one without it.
4. Create a new user and attach him to the modified/created group.
5. Try to log as created user

### Expected result

Media start node is required, or you can log in without it. I recommend allowing to log without it, because one of my groups have access only to the content tab, so why should I assign media start node.

### Actual result

I can remove media start node, but I can't log without it.

**Comment by nul800sebastiaan** [comment] 2020-11-04 16:48
Thanks! This is a duplicate of #7682

**Closed by nul800sebastiaan** 2020-11-04 16:48 UTC
