### ISSUE TITLE
Non-required fields marked as required in nested content

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#10246] opened 2021-05-07 08:27 UTC
Non-required fields is marked as required if I have nested content in two levels.

## Umbraco version

I am seeing this issue on Umbraco version: 8.13.0

Bug summary
------------

I have a page with nested content in two levels, eg. a page with a nested content field, in that content field I can insert a module (level 1) and on the module I have a nested content field where I can insert another sub-module (level 2).

If I make the nested content field in level 1 required, then all fields on the module in level 2 will appear as required even though they are not make as required on the document type.

See examples:
![image](https://user-images.githubusercontent.com/2575817/117420244-aad61000-af1d-11eb-809a-4ade2a8150f0.png)

![image](https://user-images.githubusercontent.com/2575817/117420267-b0335a80-af1d-11eb-9c18-cbeb6de54d15.png)

### Expected result

Fields are only marked as required if they are marked as required in the document type not because the parent field is marked as required.

---
_This item has been added to our backlog [AB#12111](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12111)_

**Comment by jesperweber** [comment] 2021-05-07 08:31
Two others have reported simular issues: https://github.com/umbraco/Umbraco-CMS/issues/8963#issuecomment-765351836 and https://github.com/umbraco/Umbraco-CMS/issues/8963#issuecomment-783455859

**Comment by VargyasMoniLajos** [comment] 2021-05-12 07:05
We are also noticing this issue on 8.13.0 and 8.12.1. Exactly as described

**Comment by nul800sebastiaan** [comment] 2021-05-12 11:37
Hey there @jesperweber, we've done a bit of work on this nested validation, it was quite the challenge, but we think we got it all sorted now for the upcoming 8.14, I can not reproduce your scenario any more:

![image](https://user-images.githubusercontent.com/304656/117968906-01c95400-b327-11eb-88dc-f7bc532bda63.png)

I'll close this as a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8954 as this had the same cause as the issue fixed there. 8.14 release candidate is out next week, we'd love it if you could help test to make sure your exact configuration actually validates correctly now but I believe I have a similar setup as you pictured there!

**Comment by jesperweber** [comment] 2021-05-17 09:27
Hi @nul800sebastiaan, Sure I will give the release conditate a test and get back to you. Thanks.

**Comment by jesperweber** [comment] 2021-05-20 07:11
Hi @nul800sebastiaan I tried testing the 8.14.0-rc today, but I just get error after upgrading.

`An error occurred
The 'language' start tag on line 2 position 2 does not match the end tag of 'area'. Line 1911, position 5.

Exception Details:
System.Xml.XmlException: The 'language' start tag on line 2 position 2 does not match the end tag of 'area'. Line 1911, position 5.
Stacktrace:
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Umbraco.Core.Services.Implement.LocalizedTextServiceFileSources.<>c__DisplayClass6_0.<.ctor>b__2() in D:\a\1\s\src\Umbraco.Core\Services\Implement\LocalizedTextServiceFileSources.cs:line 112
   at Umbraco.Core.Cache.AppCacheExtensions.<>c__DisplayClass0_0`1.<GetCacheItem>b__0() in D:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 22
   at Umbraco.Core.Cache.FastDictionaryAppCacheBase.<>c__DisplayClass21_0.<GetSafeLazy>b__0() in D:\a\1\s\src\Umbraco.Core\Cache\FastDictionaryAppCacheBase.cs:line 285
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Core.Cache.WebCachingAppCache.GetInternal(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles) in D:\a\1\s\src\Umbraco.Core\Cache\WebCachingAppCache.cs:line 174
   at Umbraco.Core.Cache.WebCachingAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles) in D:\a\1\s\src\Umbraco.Core\Cache\WebCachingAppCache.cs:line 40
   at Umbraco.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles)
   at Umbraco.Core.Cache.AppCacheExtensions.GetCacheItem[T](IAppPolicyCache provider, String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles) in D:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 22
   at Umbraco.Core.Services.Implement.LocalizedTextServiceFileSources.<>c__DisplayClass6_0.<.ctor>b__1() in D:\a\1\s\src\Umbraco.Core\Services\Implement\LocalizedTextServiceFileSources.cs:line 106
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Umbraco.Core.Services.Implement.LocalizedTextService.FindTranslation(IDictionary`2 xmlSource, CultureInfo culture, String area, String key) in D:\a\1\s\src\Umbraco.Core\Services\Implement\LocalizedTextService.cs:line 271
   at Umbraco.Core.Services.Implement.LocalizedTextService.GetFromXmlSource(IDictionary`2 xmlSource, CultureInfo culture, String area, String key, IDictionary`2 tokens) in D:\a\1\s\src\Umbraco.Core\Services\Implement\LocalizedTextService.cs:line 254
   at Umbraco.Core.Services.Implement.LocalizedTextService.Localize(String key, CultureInfo culture, IDictionary`2 tokens) in D:\a\1\s\src\Umbraco.Core\Services\Implement\LocalizedTextService.cs:line 82
   at Umbraco.Web.Trees.ContentTreeControllerBase.GetTreeNodes(String id, FormDataCollection queryStrings) in D:\a\1\s\src\Umbraco.Web\Trees\ContentTreeControllerBase.cs:line 330
   at Umbraco.Web.Trees.TreeControllerBase.GetNodes(String id, FormDataCollection queryStrings) in D:\a\1\s\src\Umbraco.Web\Trees\TreeControllerBase.cs:line 134
   at Umbraco.Web.Trees.ApplicationTreeController.<GetChildren>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Trees.ApplicationTreeController.<GetTreeRootNode>d__5.MoveNext() in D:\a\1\s\src\Umbraco.Web\Trees\ApplicationTreeController.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Trees.ApplicationTreeController.<GetApplicationTrees>d__3.MoveNext() in D:\a\1\s\src\Umbraco.Web\Trees\ApplicationTreeController.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()`

**Comment by nul800sebastiaan** [comment] 2021-05-20 07:14
@jesperweber There's something wrong with one of your language files. Seems to happen sometimes when you have merge conflicts that are not resolved correctly. I would delete all files in `Umbraco\Config\Lang` and replace them with the files from the ZIP download of 8.14-RC on Our Umbraco! 👍 

If it still occurs it could be some other .xml file in `App_Plugins` or `Config/Lang` causing problems.

**Comment by jesperweber** [comment] 2021-05-20 07:24
@nul800sebastiaan It seem to be an error in the `umbraco\Config\Lang\da.xml` file in the Umbraco 8.14.0-rc code base.

![image](https://user-images.githubusercontent.com/2575817/118936709-10c68c80-b94d-11eb-8a5f-7d08567509fa.png)

After removing the duplicate `<\area>` Umbraco is working again.

**Comment by nul800sebastiaan** [comment] 2021-05-20 07:25
Bah.. sorry about that! 😞  We'll get it fixed, thanks!

**Comment by jesperweber** [comment] 2021-05-20 09:08
@nul800sebastiaan I'm still having the same issue with proeprties being marked as required on level two on 8.14.0-rc

![image](https://user-images.githubusercontent.com/2575817/118950468-838a3480-b95a-11eb-8c66-d7088a12c7f5.png)

Also I'm still not able to publish if I have fixed a validation error

![validation](https://user-images.githubusercontent.com/2575817/118951759-a6691880-b95b-11eb-891d-1134ad097965.gif)

**Comment by nul800sebastiaan** [comment] 2021-05-20 10:50
That's not what we'd want to hear @jesperweber! 😅 Is there any chance you can share this work in progress site + database with us so we can reproduce the issue, we have tried a lot of different scenarios but there must be something slightly different with your site. 

If at all possible then sj at umbraco . dk is where you can reach me with zip files (I like WeTransfer for this!).

**Comment by jesperweber** [comment] 2021-05-20 11:15
@nul800sebastiaan I will have to ask our client first. If it's okay with the client I would gladly share the codebase and the local database. 

I'll get back to you.

**Comment by nul800sebastiaan** [comment] 2021-05-20 11:17
Of course! Fingers crossed! 🤞

**Comment by jesperweber** [comment] 2021-05-21 06:52
Hi @nul800sebastiaan I have send you an email with the source code.

**Comment by nul800sebastiaan** [comment] 2021-05-26 07:17
Update: this might actually be a general issue with setting the RTE to mandatory: https://github.com/umbraco/Umbraco-CMS/issues/10246

**Comment by nul800sebastiaan** [comment] 2021-05-26 07:17
Update: this might actually be a general issue with setting the RTE to mandatory: https://github.com/umbraco/Umbraco-CMS/issues/10327

**Comment by nul800sebastiaan** [comment] 2021-05-26 11:45
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10328

**Closed by nul800sebastiaan** 2021-05-26 11:45 UTC
Labels: release/8.11.3, release/8.12.3, release/8.13.1, release/8.14.0, type/bug

**Comment by jesperweber** [comment] 2021-05-27 06:31
@nul800sebastiaan Has the 8.14.0-rc version been updated, so I can install it again and test?

**Comment by nul800sebastiaan** [comment] 2021-05-27 08:14
@jesperweber No but I can show you the result :) 


https://user-images.githubusercontent.com/304656/119790510-48e14880-bed4-11eb-9cda-296b1e16d0aa.mp4
