### ISSUE TITLE
Create menu option missing

### ISSUE THREAD

**Issue by mitraganesh** [umbraco/Umbraco-CMS#13855] opened 2023-02-20 04:51 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.14.1

### Bug summary

In production server, the create option missing for content node but my localhost showing perfectly. Same user with Administrators permission for both (localhost and production).

Localhost showing:

![a](https://user-images.githubusercontent.com/42875097/220011978-7e7c6ac6-2043-437b-b525-f51f6d0649a7.png)

Production showing:

![b](https://user-images.githubusercontent.com/42875097/220012123-d1d97f73-1461-4b13-807d-846e1fdb1dbc.png)

### Steps to reproduce

NA

**Comment by Zeegaan** [comment] 2023-02-20 09:32
Hello there! 👋 That does indeed seem like an issue, it seems like maybe the user permissions have been tangled up somewhere, weird that it is only created through 🤔 
Unfortunately, as we don't have much to go on here, I cannot reproduce this, so I'll have to close this issue for now 😕 
Feel free to re-open if you have more information or find some reproduction steps 🙏

**Closed by Zeegaan** 2023-02-20 09:32 UTC
Labels: type/bug
