### ISSUE TITLE
Issue with Dependency Handler and Nested Block List Editors: TypeError: Cannot set property 'udi' of undefined

### ISSUE THREAD

**Issue by garpunkal** [umbraco/Umbraco-CMS#10617] opened 2021-07-07 13:12 UTC
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

If you have a block list property with a nested blocklist, and render the frontend page, this can cause a JS error (TypeError: Cannot set property 'udi' of undefined) 

- Page 
--- Block list property
----- Child Block list property

Save and published, view the final website page, then return to the back office, this can cause a dependency handler error in the backoffice. 

![image](https://user-images.githubusercontent.com/13114807/124762958-5b1ac180-df2b-11eb-9244-b705df654306.png)
![image](https://user-images.githubusercontent.com/13114807/124763006-6837b080-df2b-11eb-9237-7e549384a52d.png)
![image](https://user-images.githubusercontent.com/13114807/124763024-6ff75500-df2b-11eb-9521-5598d454a4f4.png)

As you can see from the screenshots, once this JS error has occurred the back-office interface for the blocklist item just breaks.

### Specifics

JS error: TypeError: Cannot set property 'udi' of undefined

CTRL+R the back-office and things return to normal.

### Steps to reproduce

1. Include a Block List Property on a edit page
2. Include a (nested) Block List inside the previous block list property. 
3. Save & Publish
4. Open new tab and view updated webpage. 
5. Without refreshing URL the back-office, open the block list property again. 
6. The nested list fails to render and the following dependency handler error happens. 

### Expected result / actual result

The interface in the backoffice to continue to work

**Comment by nul800sebastiaan** [comment] 2021-07-07 13:32
I can't reproduce this with the steps listed @garpunkal - can you see what I'm doing wrong?


https://user-images.githubusercontent.com/304656/124767854-77712b00-df38-11eb-80e1-be7251c74efb.mp4

Here's the test site: https://drive.google.com/file/d/19IFLOIj-uNhhfNhTNfhtFyydfYKX5jor/view?usp=sharing

- Unzip the site, open it in VSCode and run it through IISExpress (install: https://marketplace.visualstudio.com/items?itemName=warren-buckley.iis-express) 
- User: test@test.com
- Pass: test123456

If you can make the error happen on this site then please let me know which changes you had to make (or just send me back a newly zipped version) and we can have another look.

For now I'll close this until we are able to reproduce.

**Closed by nul800sebastiaan** 2021-07-07 13:32 UTC
Labels: type/bug
