### ISSUE TITLE
Inserting Media Through Richtext Editor

### ISSUE THREAD

**Issue by Ryyyyannnn** [umbraco/Umbraco-CMS#7958] opened 2020-04-14 08:34 UTC
There seems to be a strange issue with inserting media through the richtext editor. The button to actually insert the image is disabled, although I can get round this by clicking enter.

The media type, image, has no required properties or any additional properties. I have tried this on a fresh install and have still got the same results.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.5 & 8.6

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I had this issue on 8.5.5 then when upgrading to 8.6 it still persisted. Same with a fresh install of 8.6.
The images I was trying to insert into the richtext editor were just jpg and png. Nothing special about them. But the issue still persists with svg also.

I have tried entering the alternative text, in case there was an issue with the conditional logic, however it made no difference to the disabled state of the button.

### Specifics

Anywhere a richtext editor is placed, nothing specific.
I've cross browser tested this with:
Latest Edge (chromium updated one)
Google Chrome (latest version)
Internet Explorer

### Steps to reproduce

- Create a richtext editor on any document type with the media picker
- Go to the richtext editor on the node
- Insert an image
- Where you get the option insert alternative text and see the preview of the media item you've selected (in my case I tried jpg, jpeg, png and svg) you will see the 'select' button is disabled, and you cannot click it.

### Expected result

After following the steps above, I expect to be able to select the image, with or without the alternative text as it's specified as optional.

### Actual result

The select button is disabled, and I'm unable to add the image to the richtext editor.

**Comment by nul800sebastiaan** [comment] 2020-04-14 12:09
That's strange.. We certainly would've had more reports of this if it was a problem for everyone. Have I done this thee way you did? Seems to be good for me?

![7958](https://user-images.githubusercontent.com/304656/79223395-89f5d500-7e59-11ea-9d7c-68e423620171.gif)

I'll close this for now, but let me know if there's some additional steps to reproduce! 👍

**Closed by nul800sebastiaan** 2020-04-14 12:09 UTC

**Comment by tomvanenckevort-hp** [comment] 2021-10-20 14:41
I came across this issue today on a v8.5.3 site and for us this was due to a bug in the Matryoshka plugin that changed the `z-index` of the `umb-editor-container` which caused it to hide the media details overlay with the active Submit button: https://github.com/skttl/umbraco-matryoshka/issues/9

Upgrading the Matryoshka plugin to a later version fixed the issue for us, so I thought it was worth sharing in case someone else comes across this same issue.
