### ISSUE TITLE
Int to String[] deserialization error after migration

### ISSUE THREAD

**Issue by TiagoPT** [umbraco/Umbraco-CMS#7072] opened 2019-11-06 14:07 UTC
A brief description of the issue goes here.

After following the steps described in the migration manual for a Umbraco Cloud site I have the content & document types available. But most of the pages don't properly load due to a deserialization error from Int64 to String[ ]. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.2.2

Reproduction
------------

Migration of a website from Umbraco 7.15.3 to Umbraco 8.2.2 that has Nested Content.

### Bug summary
Due to a type mismatch in one of the properties - int instead of string[] - the pages which have nested content can't be rendered.

### Steps to reproduce

Copy Umbraco.mdf file from Umbraco 7.15.3 project to Umbraco 8 project
Change the version in the Web.config to 7.15.3
Do the content migration
Open backoffice and load content
Error should be displayed on page with nested content.

### Expected result
Page to be displayed correctly after content Migration.

### Actual result

Deserialization exception.
![image](https://user-images.githubusercontent.com/1324397/68304807-d832cb00-00a6-11ea-8ea0-3ac5822a55cc.png)

See stack trace: https://gist.github.com/TiagoPT/6f06bd689f39ec153c8e4bd3830192f5

**Comment by TiagoPT** [comment] 2019-11-06 14:30
Possibly related to https://github.com/umbraco/Umbraco-CMS/issues/5889?

**Comment by nul800sebastiaan** [comment] 2019-11-07 07:51
Yep, that's a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/5889 - I'll comment there.

**Closed by nul800sebastiaan** 2019-11-07 07:51 UTC
