### ISSUE TITLE
postSave api call behave differently on different fields when there is mandatory field validation error 

### ISSUE THREAD

**Issue by harsheet** [umbraco/Umbraco-CMS#3872] opened 2018-12-14 00:14 UTC
This issue was closed in https://github.com/umbraco/Umbraco-CMS/issues/3858

But I want to open it again.

The postSave api call is behaving differently on different fields in umbraco. For eg. if title, description have missing values and throw a mandatory validation error, it shows "Property has errors". And if we try to hit Save and Publish it won't trigger a postSave api call, which is fine. It works okay when we add the missing value, it fires the postSave api call.

But if there are validation errors on tags or media, then the error message shows - "Value cannot be empty". And it trigger a postSave call with 400 bad request. This makes the content to be saved, but not published in Umbraco. And when we resolve the errors and attempt to publish again, it sends the 2nd postSave call and the content will be published.

We are using Umbraco 7.11.1

Here are the steps to reproduce this bug - 
1) Create a new content and leave the tags field empty.
![bug3](https://user-images.githubusercontent.com/5582747/49850537-c2088600-fdd5-11e8-8ec6-b53843d75b62.png)

2) Click Save and Publish and it will throw a 404 bad request with the validation errors.

3)  And if you look at the json posted with the postSave call, there is a parameter called action = 'publishNew', which means that the content is saved.
![postsave](https://user-images.githubusercontent.com/5582747/49850580-f714d880-fdd5-11e8-9502-c6c49ab9b331.png)

4)  Now, if you see the article list, this content has been saved but not published. And this should not happen as I have not yet fixed the validation error on tags.
![list](https://user-images.githubusercontent.com/5582747/49850896-34c63100-fdd7-11e8-8754-20b8d21908cc.png)

5) Now, if I fix the validation error on tags and click Save and Publish again, there is 2nd postSave api call. And if you look at the json posted with this call, it will have action = 'publish', instead of action = 'publishNew'. The content is published now.
![postsave2](https://user-images.githubusercontent.com/5582747/49851100-e5cccb80-fdd7-11e8-9d83-bd631d4eec43.png)

### Expected result

The postSave api call should behave same for all fields including title, description, tags, media.

### Actual result

The problem we are facing due to this is when we get the latest articles to display on our homepage, it does not show the one which was saved after fixing the validation errors.

**Comment by harsheet** [comment] 2018-12-14 01:33
Thanks for the explanation Shazwazza. But the thing is even if it is a server side validation, the content should never be saved. Even if this is the default behaviour, then why the action changes from publishNew to publish.

I tested this on one of our staging environments by hardcoding action to publishNew. And it was working fine, though it was creating a new content everytime, which should not happen. It should just fail because of validation error, even on server side validation as well. The content should never be saved or published when we still have validation errors.

**Comment by Shazwazza** [comment] 2018-12-14 01:36
If validation fails, saving can still happen because the content does not get published and go live. If your editor has spent an hour writing something and saves something and validation fails, they certainly don't want to lose their work in case they navigate away or don't have time to fix validation problems, so their changes are saved.

As i said there are different flags used "PublishedNew" and "SaveNew" will create new content "Publish" and "Save" update existing content. 

If you have a new content item, the flag will be sent as "PublishedNew" and  the item will be created. If you try to publish again, it will be "Publish" because it now exists.

The content is never published if there are validation errors but it can be saved.

**Comment by harsheet** [comment] 2018-12-14 01:39
Yes that is fine but it can also happen with the properties with client side validation. They just work fine. And in case of tags validation and in order to make it appear as the latest published content on site, I have to click save and publish twice or thrice. That is the actual problem.

**Comment by Shazwazza** [comment] 2018-12-14 01:43
In order for the item to be published, all validation needs to be fixed up. I don't think i understand what you mean by this

> They just work fine. And in case of tags validation and in order to make it appear as the latest published content on site, I have to click save and publish twice or thrice. That is the actual problem.

**Comment by nul800sebastiaan** [comment] 2018-12-14 08:18
As noted above, all of this is expected behavior, so I'll close this issue.

**Closed by nul800sebastiaan** 2018-12-14 08:18 UTC
