### ISSUE TITLE
Content Delivery API - Multinode Treepicker always returns the items in the default language

### ISSUE THREAD

**Issue by lauraneto** [umbraco/Umbraco-CMS#14758] opened 2023-09-01 09:51 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

When requesting an item by path and there is a multinode treepicker property, the items in that property are always returned in the default language, instead of matching the language of the main item.

You can see the issue in a sample demo I built (the requests are done client side, so you can see them by inspecting them in dev tools).
I have two variants of the content, one in `pt-PT` (https://lauraneto.github.io/Umbraco.Headless.Blazor/pt/blog/blog-1) and another one in `en-US` (https://lauraneto.github.io/Umbraco.Headless.Blazor/blog/blog-item-1) which are referencing another item (Blog Item 3), which also exists in both languages, but the `en-US` version is always returned (both the "main" properties like `name` and the actual `properties` (expanded)).

### Steps to reproduce

1. Create a node in multiple languages, where the document type contains a Multinode Treepicker property.
2. Create a second node in the same languages as the previous step.
3. Open the first node and add the second node to the Multinode Treepicker property.
4. Request the first node using the Content Delivery API path endpoint (expanding the multinode treepicker property) in the various languages and check that the items will always be retrieved in the default language, and not the language of the main item, even though it exists.

### Expected result / actual result

The content of the referenced item(s) would be returned in the language of the main item.

**Comment by kjac** [comment] 2023-09-05 06:58
Hi @lauraneto 👋 

Thank you for reporting. And thank you for the thorough description and samples. And not least for tinkering with the Delivery API, that's awesome 🚀 

I can reproduce this with a standard content picker - but "only" for invariant properties on variant content. Can you confirm that your `relatedBlogs` is indeed an invariant property?

I suspect you may have uncovered a general caching issue in Umbraco here 🙈

**Comment by lauraneto** [comment] 2023-09-05 08:56
Hi @kjac ,

Yes, you are correct, invariant property in variant content indeed!
Oh no! 🫠

**Comment by kjac** [comment] 2023-09-07 10:27
Hi there @lauraneto,

Just a quick follow-up. There truly seems to be a caching issue in the Umbraco core, which is barely noticeable when rendering with Razor templates. However, it becomes quite evident in the Delivery API output.

We're going to investigate a fix for this in the coming weeks.

**Comment by kjac** [comment] 2023-09-25 05:30
Hi again @lauraneto,

Just a quick follow-up here. The fix for this caching issue didn't make it to 12.2, but I'm definitively expecting it in 12.3 😄

**Comment by kjac** [comment] 2023-09-26 11:24
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14824

Thank you again for raising this, @lauraneto 👍

**Closed by kjac** 2023-09-26 11:24 UTC
Labels: state/in-sprint, type/bug, affected/v12
