### ISSUE TITLE
Image not updated after changing it in Media

### ISSUE THREAD

**Issue by PullensDennis** [umbraco/Umbraco-CMS#3869] opened 2018-12-13 09:16 UTC
When you use an image that is cropped (for instance in a RTE) and you re-upload it with changes in the image, it is not updated on the content pages. This is most likely due to the image processor that caches the cropped image. Because the source URL of the image is not changed after the update, the outdated image will still be returned from the Image Processor cache.

Reproduction
------------

In the base installation, add an image to a RTE. Then update the image in the Media folder. When you refresh the page you will still see the old image

### Specifics

* Umbraco version 7.12.4

### Steps to reproduce
Can be reproduced in the base installation

* Make sure you can add an image to a RTE
* Add an image to a content page within an RTE
* Update the image from the Media folder
* Reload the page

### Expected result

The image on the content page should be updated after the image was updated in the Media folder

### Actual result

The image remains the same, even though it is updated in the Media folder

**Comment by dawoe** [comment] 2018-12-13 09:19
Hi @PullensDennis 

Thanks for reporting the issue.

When you say "Update the image from the Media folder" do you mean directly on disk ? Or through the media section in umbraco and uploading a new image for the media item.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by dawoe** [comment] 2018-12-13 16:18
I can confirm this issue. I also the old image still being in use in the RTE.

I think it will be also the case with file links. But haven't tested that.

So the issue is that the RTE doesn't update the image path on disk when the file is changed in the media item.

In the rendering this could be fixed in the Property Value Converter. The image tags have a data-udi attribute (or data-id from pre 7.6) which can be used  to get the media item and update the image. But this would have a performance overhead when rendering.

But that still doesn't solve the issue with the old image still being visible in the RTE. No idea how this can be fixed easily. The umbraco core doesn't keep track of internal links.

You could solve it by installing my Nexu package. And when a media item is updated and the file is changed, you could use the data from nexu to find out in which items it is used in a RTE field. With that information you could update the RTE field of the content item. But that is hacky.

Dave






Dave


.

**Comment by kjac** [comment] 2019-01-08 11:09
I'll give this a go 👍

**Comment by dawoe** [comment] 2019-01-08 11:32
Hi @kjac ,

Keep in mind that sites upgraded from versions pre 7.6 don't have the data-udi attribute, but use the data-id attribute if the image hasn't been changed since the upgrade

Dave

**Comment by kjac** [comment] 2019-01-08 18:02
@dawoe yep. I've done some defensive coding that only works if the `<img />` tag has a `src` *and* a `data-udi` attribute.

PR in #4001

**Comment by nul800sebastiaan** [comment] 2019-03-20 21:47
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4001

**Closed by nul800sebastiaan** 2019-03-20 21:47 UTC
Labels: release/7.15.0, release/8.1.0, type/bug

**Comment by PullensDennis** [comment] 2019-03-21 07:51
Hi there @kjac and @nul800sebastiaan,

Thanks for your efforts! I'm looking forward to the update :)
