### ISSUE TITLE
v8.1 Avoid data loss when using culture variant elements in Nested Content

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#5817] opened 2019-07-09 12:57 UTC
I just updated to version **Umbraco 8.1** on cloud.

I have notest that Nested Content inside Nested Content are not saved. 

![image](https://user-images.githubusercontent.com/6445636/60889431-48e0ec80-a259-11e9-9356-331f30f88985.png)

![image](https://user-images.githubusercontent.com/6445636/60889458-54341800-a259-11e9-907f-d39fba0a79fb.png)

When publishing every thing looks fine, but if you reload page you can see that the content are not saved.
I have looked in the database, and it's not saved there.
![image](https://user-images.githubusercontent.com/6445636/60889482-61510700-a259-11e9-9b0d-da7d1d2f34ce.png)

Level 1. Nested are saved, but not level 2. Nested Content 
![image](https://user-images.githubusercontent.com/6445636/60889500-6d3cc900-a259-11e9-94de-e74614ffd74f.png)

**Comment by thomashdk** [comment] 2019-07-10 07:40
After deleting the datatype and create a new one it worked.

**Comment by thomashdk** [comment] 2019-07-10 10:48
I opened this again because i'm still getting a similar error. 

Sometimes the content are not saved to database... ex. here I have en content picker en selectes a local node and after I have save and published and reload the page, the contetn are gone.

![image](https://user-images.githubusercontent.com/6445636/60963310-b865e300-a310-11e9-88a5-fde9ba70991c.png)

The same happens with the form componenet I have. All the fields are empty after save/publish and relaod page. 
The DB don't have the content saved
![image](https://user-images.githubusercontent.com/6445636/60963408-f9f68e00-a310-11e9-9d64-101dc8651e81.png)

**Comment by thomashdk** [comment] 2019-07-10 11:03
After some debug I notes that some of my other components worked. 

If the fields did'nt had the "Allow varying by culture" active, it wouldn't save the content.
The doctype with the fields were set to allow carying by culture"
![image](https://user-images.githubusercontent.com/6445636/60964126-d3d1ed80-a312-11e9-8f6b-f88ff0834663.png)

**Comment by kjsguld** [comment] 2019-07-11 13:38
I've just seen the same behavior on 8.1 as reported. 
Triggered the same behavior and resolution on a node on a list view, that had nested content (where the content ie. images and drop-downs can't be saved). 
Thanks for spreading the word on this one @thomashdk 🐛

**Comment by kjac** [comment] 2019-07-12 19:39
For the life of me I can't reproduce this. I have a doctype with both variant and invariant properties; this is how it works when creating a new item of that doctype:

![variant-invariant-content](https://user-images.githubusercontent.com/7405322/61154062-67f7ac80-a4ed-11e9-8ede-ceeaa064540d.gif)

**Comment by kjac** [comment] 2019-07-15 11:21
So I've tried creating a variant doctype with an invariant Nested Content field. The Nested Content has Nested Content within it, and the nested Nested Content has a content picker. I still can't make it fail; here's another GIF:

![nc-variant-invariant](https://user-images.githubusercontent.com/7405322/61212656-36582e80-a703-11e9-8840-376086ac9cca.gif)

@thomashdk perhaps you could explain more in detail how you've set things up so we can reproduce and fix?

**Comment by miackers** [comment] 2019-07-16 13:08
@kjac what do you use to create the animated gifs?

I can confirm that my issue (#5909) seems to be a duplicate of this - happy for you to close that one down

I noticed that if I hover over the problematic fields, the title was weird/different:
![image](https://user-images.githubusercontent.com/2778432/61296832-daf57180-a7d2-11e9-82b8-cac8809ca47b.png)

That got me to this change (v8.0.2 vs 8.1)

![image](https://user-images.githubusercontent.com/2778432/61296894-f5c7e600-a7d2-11e9-909e-a41e733517e2.png)


Just thought I would give some of my investigation into the matter - as mentioned on my issue, just disabling "Allow varying by culture" is enough for me to "fix" this.

**Comment by miackers** [comment] 2019-07-16 13:09
Oh - just to mention about the title - i've got 4 languages, and stickySidebar repeats for each language variant. When I tested this on a clean instance with 2 languages, it repeated 2 times.

**Comment by miackers** [comment] 2019-07-17 13:02
thanks @kjac

**Comment by kjac** [comment] 2019-07-19 10:23
I've found the problem - will submit a fix shortly.

**Comment by kjac** [comment] 2019-07-19 11:02
PR in #5952

**Comment by Shazwazza** [comment] 2019-07-22 00:49
Hi @kjac can you please advise on what the title of this bug report should be ? (it shows up in the release notes)

**Comment by kjac** [comment] 2019-07-22 05:00
@Shazwazza I figure something along these lines: "Avoid data loss when using culture variant elements in Nested Content".

**Comment by RabeaM** [comment] 2019-07-23 06:58
Hi guys, i am still facing this issue after latest upgrade to v8.1, is there any update on this?

**Comment by kjac** [comment] 2019-07-23 07:12
Hi @RabeaM, the fix is not yet in any release. It might be included in 8.1.1 - for the time being you can work around the issue by making your element types non variant.

**Comment by CodeartIT** [comment] 2019-07-30 19:21
This is not fixed in v 8.1.1 and i cant see that its scheduled for next release

**Comment by YvoLinssen** [comment] 2019-08-12 14:54
Problem still occurs....

**Comment by kjac** [comment] 2019-08-12 15:04
@YvoLinssen yep, the PR hasn't been merged in yet.

**Comment by nul800sebastiaan** [comment] 2019-08-13 15:03
We're working on this soon!

In the mean time, if anyone wants to help test, you could try to apply the change manually on your current 8.1 install to see if you can test it then that would be awesome! 

In `~/Umbraco/Js/umbraco.controllers.js` around line 20042 replace this block:

                for (var v = 0; v < node.variants.length; v++) {
                    var variant = node.variants[v];
                    for (var t = 0; t < variant.tabs.length; t++) {
                        var tab = variant.tabs[t];
                        for (var p = 0; p < tab.properties.length; p++) {
                            var prop = tab.properties[p];
                            prop.propertyAlias = prop.alias;
                            prop.alias = $scope.model.alias + '___' + prop.alias;
                            // Force validation to occur server side as this is the
                            // only way we can have consistency between mandatory and
                            // regex validation messages. Not ideal, but it works.
                            prop.validation = {
                                mandatory: false,
                                pattern: ''
                            };
                            if (fromNcEntry && fromNcEntry[prop.propertyAlias]) {
                                prop.value = fromNcEntry[prop.propertyAlias];
                            }
                        }
                    }
                }


With this block:

                 var variant = node.variants[0];
                    
				for (var t = 0; t < variant.tabs.length; t++) {
					var tab = variant.tabs[t];
					for (var p = 0; p < tab.properties.length; p++) {
						var prop = tab.properties[p];
						prop.propertyAlias = prop.alias;
						prop.alias = $scope.model.alias + '___' + prop.alias;
						// Force validation to occur server side as this is the
						// only way we can have consistency between mandatory and
						// regex validation messages. Not ideal, but it works.
						prop.validation = {
							mandatory: false,
							pattern: ''
						};
						if (fromNcEntry && fromNcEntry[prop.propertyAlias]) {
							prop.value = fromNcEntry[prop.propertyAlias];
						}
					}
				}

That should do the trick. 

The best way to make sure your browser picks up the changes is to then update the version in ClientDependency.config (just make it 1 higher or lower).

Make sure to comment here with the results! 👍

**Comment by nul800sebastiaan** [comment] 2019-08-15 11:11
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5952

**Closed by nul800sebastiaan** 2019-08-15 11:11 UTC
Labels: community/pr, release/8.1.3, type/bug

**Comment by nul800sebastiaan** [comment] 2019-08-15 11:29
Cherry picked to 8.1.3 7e8364eae48be9bbd3a160c3f3aab03eb374ab1f
