### ISSUE TITLE
Delivery Api Query is not returing any results if Authorization Bearer header is added

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco-CMS#17560] opened 2024-11-17 09:18 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

When a Authorization Bearer header is added to a Delivery Api Query, no results are returned. The content is not protected with member access.

![image](https://github.com/user-attachments/assets/ca659ea6-b85a-479f-bfac-52d69c449c4b)
![image](https://github.com/user-attachments/assets/93d987a7-0cff-481f-970b-81e0e83773a9)

When the Autorization Bearer header is removed, all children are returned.

![image](https://github.com/user-attachments/assets/55b9d05d-ca7c-4a38-b680-f0f23742d4fd)
![image](https://github.com/user-attachments/assets/e87543ce-3f8e-4308-b5a7-a65be0b39695)

### Specifics

/umbraco/delivery/api/v2/content?fetch=children:{guid-of-parentnode}&take=10&skip=0&fields=properties[$all]

### Steps to reproduce

Create a Delivery Api fetch request and add a Authorization Bearer header with a access token to a node that has no member access protection.

/umbraco/delivery/api/v2/content?fetch=children:{guid-of-parentnode}&take=10&skip=0&fields=properties[$all]

### Expected result / actual result

The Delivery Api should return content if a Authorization Bearer header is added.

**Comment by NguyenThuyLan** [comment] 2024-11-27 06:47
Hi @mcl-sz , why do you add authorization bearer to query data?
In v13, Umbraco are using cookie authentication 🤔

**Comment by NguyenThuyLan** [comment] 2024-12-26 04:32
I was not able to reproduce it on v13.6.0-rc. Please take a look at the images below.
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/6311949f-c5a5-4617-ad63-6d8351193a93" />
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/688d744c-2d50-4c7c-a64f-29c2811d3438" />
So I will close this because I couldn't reproduce it. 
@mcl-sz let's upgrade to a newer version of Umbraco. Let me know if it still has errors

**Closed by NguyenThuyLan** 2024-12-26 04:32 UTC
Labels: type/bug
