### ISSUE TITLE
Rebuilding the member index causes time out exception

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#9439] opened 2020-11-23 20:12 UTC
Hi!

I am facing a lot of SQL time out exception when I try to rebuild the member index. There are 12-13k members in the index. 

Increasing the timeout doesn't really help since it seems to run into a hole for ever without completing the rebuild.

Exception ("f4fb6e62").
```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): Der Wartevorgang wurde abgebrochen
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   bei System.Data.SqlClient.SqlDataReader.get_MetaData()
   bei System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:Zeile 208.
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 222.
   bei Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:Zeile 172.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 219.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei System.Data.Common.DbCommand.ExecuteReader()
   bei NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   bei NPoco.Database.ExecuteDataReader(DbCommand cmd)
ClientConnectionId:3a19ad60-a809-4fb5-8a95-60d5fc8723d1
Fehlernummer (Error Number):-2,Status (State):0,Klasse (Class):11
```

An error occurred rebuilding index
```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): Der Wartevorgang wurde abgebrochen
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   bei System.Data.SqlClient.SqlDataReader.get_MetaData()
   bei System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:Zeile 208.
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 222.
   bei Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:Zeile 172.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 219.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei System.Data.Common.DbCommand.ExecuteReader()
   bei NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   bei NPoco.Database.ExecuteDataReader(DbCommand cmd)
   bei NPoco.Database.<QueryImp>d__164`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei NPoco.Database.<Page>b__170_0[T](Page`1 paged, Sql thesql)
   bei NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
   bei NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   bei NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)
   bei Umbraco.Core.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPage[TDto](IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, Func`2 mapDtos, Sql`1 filter, Ordering ordering) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\ContentRepositoryBase.cs:Zeile 611.
   bei Umbraco.Core.Persistence.Repositories.Implement.MemberRepository.GetPage(IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\MemberRepository.cs:Zeile 567.
   bei Umbraco.Core.Services.Implement.MemberService.GetAll(Int64 pageIndex, Int32 pageSize, Int64& totalRecords) in D:\a\1\s\src\Umbraco.Core\Services\Implement\MemberService.cs:Zeile 388.
   bei Umbraco.Examine.MemberIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes) in D:\a\1\s\src\Umbraco.Examine\MemberIndexPopulator.cs:Zeile 25.
   bei Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes) in D:\a\1\s\src\Umbraco.Examine\IndexPopulator.cs:Zeile 48.
   bei Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:Zeile 44.
   bei Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:Zeile 148.
ClientConnectionId:3a19ad60-a809-4fb5-8a95-60d5fc8723d1
Fehlernummer (Error Number):-2,Status (State):0,Klasse (Class):11
```

Any ideas?

Best
Dee

**Comment by Shazwazza** [comment] 2020-11-23 22:58
What version are you using? (Please always mention this :)

**Comment by deekoulos** [comment] 2020-11-23 23:00
sry forgot to mention. 8.9.1

**Comment by Shazwazza** [comment] 2020-11-23 23:09
The page size for querying members is only 1000 which is reasonably small. Are you able to run Sql Server Profiler to see the SQL queries being produced? You can then run these in SQL server manager with the execution plan enabled to see where the bottlenecks are. Is this database an upgrade from an old version or is it new?

**Comment by deekoulos** [comment] 2020-11-24 08:31
good point shannon. let me try that

**Comment by deekoulos** [comment] 2020-11-26 20:49
I think I found the issue. 

I was rebuilding the index on application start and unlocking the index if it was locked and in some cases, it led to those exceptions:

    ```
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    // register the component
    public class CustomizeIndexComposer : ComponentComposer<CustomizeIndexComponent> { }

    public class CustomizeIndexComponent : IComponent
    {
        private readonly IExamineManager _examineManager;
        private readonly IndexRebuilder _indexRebuilder;

        public CustomizeIndexComponent(IExamineManager examineManager, IndexRebuilder indexRebuilder)
        {
            _examineManager = examineManager;
            _indexRebuilder = indexRebuilder;
        }

        public void Initialize()
        {
            if (!_examineManager.TryGetIndex(Constants.UmbracoIndexes.MembersIndexName, out IIndex index))
                return;

            // modify an existing field type (not recommended)
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("minimumProjectSize", FieldDefinitionTypes.Integer));
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("memberGroups", FieldDefinitionTypes.FullTextSortable));

            var luceneIndex = index as LuceneIndex;
            var dir = luceneIndex.GetLuceneDirectory();
            if (IndexWriter.IsLocked(dir))
                IndexWriter.Unlock(dir);

            _indexRebuilder.RebuildIndex(index.Name);
        }

        public void Terminate() { }
    }
```

The reason why I had to do this was that by updating field definitions at this stage, without rebuilding the index, the index was kinda empty. no members in it. So I had to find a way to update the field definitions like above and rebuild the index to get all members back in it. Now I found a way to work around the above field updates. Without updating the field definitions, I do not need to rebuild the index here and since then I have no exceptions.

Which is not really a solution for this issue but at least a work around.

I think unlocking a locked index is not a good approach, but I wasn't able to find any other solution, to update field definitions and keeping the member index state ready with all data in it. 

Best
Dee

**Comment by Shazwazza** [comment] 2020-12-15 23:25
> I was rebuilding the index on application start

please please please don't ever rebuild indexes unless absolutely necessary and definitely not on startup, this is part of the common pitfalls document https://our.umbraco.com/Documentation/Reference/Common-Pitfalls/#rebuilding-indexes 

Please also don't unlock indexes on startup, Umbraco will do that all for you else you'll prob run into other problems. 

(maybe this is directly related to your other bot crawling issue)

Can you elaborate more on this

> The reason why I had to do this was that by updating field definitions at this stage, without rebuilding the index, the index was kinda empty. no members in it. So I had to find a way to update the field definitions like above and rebuild the index to get all members back in it

I don't really understand this problem. To change field definitions on startup you can just do this - just a reduction in your own code. That works fine. But yes, once you change field definitions, you will need to rebuild your index, or re-save all members but you don't need to rebuild it on each restart. 

```cs
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
public class CustomizeIndexComposer : ComponentComposer<CustomizeIndexComponent> { }

public class CustomizeIndexComponent : IComponent
{
    private readonly IExamineManager _examineManager;

    public CustomizeIndexComponent(IExamineManager examineManager)
    {
        _examineManager = examineManager;
    }

    public void Initialize()
    {
        if (!_examineManager.TryGetIndex(Core.Constants.UmbracoIndexes.MembersIndexName, out IIndex index))
            return;

        // modify an existing field type (not recommended)
        index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("minimumProjectSize", FieldDefinitionTypes.Integer));
        index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("memberGroups", FieldDefinitionTypes.FullTextSortable));
    }

    public void Terminate() { }
}
```

Maybe your are referring to the problem that you cannot rebuild indexes within a component on initialize? In which case, yes that is true because Umbraco will not have run it's final Examine initialization by then. This is by design... and also hopefully prevents people from trying to rebuild indexes on startup!

Umbraco itself doesn't even rebuild empty indexes during this startup phase, that rebuilding is delayed post startup and done async on a background thread which is how it should be done. All automated index rebuilding should be handled by Umbraco. 

If you want to force an index rebuild on startup because you changed field definitions and want to automate this rollout then you'll have to be more delicate/careful than just brute forcing a rebuild on each server startup. The way Umbraco performs rebuilds for empty indexes is here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Search/ExamineFinalComponent.cs#L35 

A problem with trying to automate index rebuilds on startup is if the index doesn't exist then you might be triggering 2x index rebuilds since one will already be in progress by Umbraco.  A work around might be to do this same type of thing in your component but ensure that only your member index is rebuilt and wait for a longer timeout period. The default registered `BackgroundIndexRebuilder` cannot target specific indexes. But you could achieve this by:

```cs
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
public class CustomizeIndexComposer : ComponentComposer<CustomizeIndexComponent> { }

public class CustomizeIndexComponent : IComponent
{
    private readonly IExamineManager _examineManager;
    private readonly BackgroundIndexRebuilder _rebuilder;

    public CustomizeIndexComponent(IExamineManager examineManager, IMainDom mainDom, IProfilingLogger logger, MemberIndexPopulator memberIndexPopulator)
    {
        _examineManager = examineManager;

        // create a standalone rebuilder targeting a specific index
        _rebuilder = new BackgroundIndexRebuilder(
            mainDom,
            logger,
            // only include the member index populator
            new IndexRebuilder(logger, examineManager, new[] { memberIndexPopulator }));
    }

    public void Initialize()
    {
        if (!_examineManager.TryGetIndex(Core.Constants.UmbracoIndexes.MembersIndexName, out IIndex index))
            return;

        // modify an existing field type (not recommended)
        index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("minimumProjectSize", FieldDefinitionTypes.Integer));
        index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("memberGroups", FieldDefinitionTypes.FullTextSortable));

        // TODO: Do a check to see if field definitions have changed
        // There's prob lots of ways to do this, maybe you use umbraco migrations to check if there's a new migration,
        // maybe you have a file marker that determines which iteration of field definitions exist and have a value in config
        // which you can compare to see if they are different, etc...

        // schedule a rebuild if field definitions have changed
        // wait 10 since the default rebuilder is 5 seconds

        _rebuilder.RebuildIndexes(false, 10000);
    }

    public void Terminate() { }
}
```

(I'll close this issue since this is just a question at this point)

**Closed by Shazwazza** 2020-12-15 23:25 UTC
