### ISSUE TITLE
Umbraco with Redis Distributed Cache is failing after restart

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#17649] opened 2024-11-27 09:20 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

When I configure umbraco with redis distributed cache, all properties in IPublishedContent become null after I restart the site.

The Redis Cache seems to have all documents cached correctly. If I clear the cache and restart the site, everything works as it should. After restarting again, it's the same problem.

### Steps to reproduce

- Install Umbraco v15
- Configure Redis Distributed cache
- Setup some content
- Restart applikation
- All properties from IPublishedContent is null

---
_This item has been added to our backlog AB#46625_

**Comment by Zeegaan** [comment] 2024-12-02 11:11
Hello there 👋 Sadly I cannot reproduce this, could you give me some steps to follow to reproduce from a clean install ? 😁 
I have a setup with redis running in a docker container, and when launching my site, the content appears just fine 🤔 
Here is a gif: 
![ContentNotNull](https://github.com/user-attachments/assets/e022af1e-1338-42a5-9262-5508163b42f7)

**Comment by DanielToft** [comment] 2024-12-02 13:14
@Zeegaan have you tried restarting the site after the cache is populated in the Redis container?

**Comment by Zeegaan** [comment] 2024-12-02 13:15
@DanielToft Yes this was me restarting after the cache was already populated 😁

**Comment by DanielToft** [comment] 2024-12-02 13:45
@Zeegaan I have just testet in my solution again (Not a clean install). It seems like it's not all the properties, but block grid and the Content Picker. I'm using both the Content Delivery API and directly from IPublishedContent. 

`/umbraco/delivery/api/v2/content/item/forside?fields=properties[$all]&expand=properties[$all[properties[$all]]]`

**Comment by Zeegaan** [comment] 2024-12-02 13:49
Ah okay, that makes alot more sense, I will test with a content picker and get back to you 😁

**Comment by DanielToft** [comment] 2024-12-02 14:07
The problem also happens on a Block Grid.

And it seems to work on an Umbraco.MultiNodeTreePicker.

**Comment by Zeegaan** [comment] 2024-12-03 15:02
Ah yes, that made the difference, seems like Redis serializes `object` properties different than MemoryCache does 😁 
I'm look into a fix, but seems like we have to write our own serializer to ensure it works properly 🕵️

**Comment by DanielToft** [comment] 2024-12-03 15:36
Seems strange, what's the difference? I thought the HybridCache would handle serialization.

**Comment by nikolajlauridsen** [comment] 2024-12-06 12:24
Fixed in #17727, thanks for reporting, this has been added to the upcoming 15.1 release 😄

**Closed by nikolajlauridsen** 2024-12-06 12:24 UTC
Labels: type/bug, area/backend, affected/v15
