### ISSUE TITLE
Url without domain shows invalid page

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#7930] opened 2020-04-10 14:32 UTC
We are having a certain problem with a multilanguage website we are making. We currently have the following structure:

- Homepage NL
      - Producten
      - Contact
- Homepage EN
      - Products
      - Contact

Both homepages have their own domain setup. Homepage NL has an nl-NL language and "/nl" as domain. Homepage EN has an "en-GB" language and "/en" as domain. 

All the normal urls work like they should. Producten has the url "/nl/producten" and Products has the url "/en/products". However, when going to the "/producten" url, the page will show the "/nl/producten" page (doesn't redirect). This should instead be a 404, because it's not a real url in our system. "/products" however doesn't have this problem. 

So, I took a look at the code and the problem lies in this file: https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Web/Routing/ContentFinderByUrl.cs
The problem is that when no domain is used, the culture will be set to the default culture. That's "nl-NL" in this case. Then the system will do a GetByRoute and then return the page if it's found. In our case, "/producten" will do a GetByRoute("/producten", culture: "nl-NL") call. (It actually has more parameters, but those aren't important for this problem). The call will actually return a page and the user will get the Producten page instead of a 404.

I don't know what the best way of fixing this is though. I could check if the domain is NULL, but what if there are actually urls on the root node that you want to navigate to? I could check for the .Url, but that kinda shows that there is a problem with the GetByRoute method and I am trying to work around it in the ContentFinder. 

Version that is tested is 8.6.0 & 8.5.5, but I suspect it also impacts older versions.

**Comment by nul800sebastiaan** [comment] 2020-04-14 07:08
I've tried to read this a few times now and before I really dig in I just have a question @patrickdemooij9 - why not add a domain? You can also add a domain that looks like `en/` and `nl/`.

**Comment by patrickdemooij9** [comment] 2020-04-14 07:17
Hey @nul800sebastiaan,
We already have the domains setup on the homepage nodes. And we see them working, but people are also able to go to the pages without a domain.

**Comment by patrickdemooij9** [comment] 2021-03-09 09:52
Hi @nul800sebastiaan,

It's been a while since I have created this ticket and it's something that has recently gotten some discussion in our team again. I've decided to create a video showcasing the bug:
![WrongDomainUrl](https://user-images.githubusercontent.com/11466511/110452243-4b968380-80c5-11eb-86f7-bb74be49212e.gif)

As you can see, even though I have 2 domains set for '/en' and '/nl'. The page '/blog' without any domain is still accessible. I hope the video helps with explaining the issue.

**Comment by nul800sebastiaan** [comment] 2021-03-09 10:38
This reminded [me of my old blog post around this](https://cultiv.nl/blog/tip-of-the-week-the-ultimate-site-structure-setup/), you'd need to redirect `/home` to an appropriate URL, or rename from `home` to `nl` or `en` or something like that.

**Comment by nul800sebastiaan** [comment] 2021-03-10 12:36
It does exactly what you wanted to do! 😅 

Easiest is to look at the site when you don't have domains, your link would then be:
`Umbraco.Core.HideTopLevelNodeFromPath = true` -  `/blog`
`Umbraco.Core.HideTopLevelNodeFromPath = false` -  `/home/blog`

It gets more complicated when you add a domain but basically you will notice (as you did) that you shouldn't be able to "escape" from the root node and the routes made. It's a bit difficult to explain and really it stems from the way we used to do things in.. I guess v3(?). 

So while not the easiest to understand I will close this one as "works as intended". And I will acknowledge that the intended way isn't super great, but that's the joy of ~legacy~ vintage code. 😉

Apologies for he long turnaround time on this one, it kinda fell between the cracks, good to have gotten back to this one though, I had forgotten about this setting as well for a while. 

Just for some background and something else you might run into when testing this, my original reply yesterday was going to be this:

> What you are seeing is the behavior of Alternative Templates, `blog` is the name of a template and the last URL `umbraco.com.dev.local/blog` is showing you the homepage/root page of the site with the `blog` template. You 
> You can disable that behavior in UmbracoSettings.config:
> 
> > @disableAlternativeTemplates
> > By default you can add a altTemplate querystring or append a template name to the current URL which
> > will make Umbraco render the content on the current page with the template you requested, for example:
> > http://mysite.com/about-us/?altTemplate=Home and http://mysite.com/about-us/Home would render the
> > "About Us" page with a template with the alias Home. Setting this setting to true stops that behavior

I realized that wasn't true when I tried to do a quick test to show it to you, then I remembered it had to be `HideTopLevelNodeFromPath` that we were looking for. You could

**Closed by nul800sebastiaan** 2021-03-10 12:36 UTC
Labels: state/needs-more-info
