### ISSUE TITLE
Block list editor heading feels a little intimidating?

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16463] opened 2024-05-29 11:33 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

When editing a block in a block list, the dialog header says "BLOCK EDITOR" in big, bold caps. A little intimidating, perhaps?

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/edd2b0c0-e5c8-4b4f-8033-e3c0b45c4096)

### Steps to reproduce

1. Setup a doctype with a block list.
2. Create a document based on this doctype.
3. Add a block and observe the "edit dialog" header 😄

**Comment by nielslyngsoe** [comment] 2024-08-16 13:03
Thanks, this is though a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16381
therefor I will close this one.

**Closed by nielslyngsoe** 2024-08-16 13:03 UTC
Labels: type/bug, state/reproduced, area/frontend, affected/v14
