### ISSUE TITLE
Umbraco version 7.5.7 - "Save and send for approval" only sends notification to one admin user

### ISSUE THREAD

**Issue by NurhakKaya** [umbraco/Umbraco-CMS#3204] opened 2018-10-08 16:10 UTC
I have created 2 admin users and they are both subscribed to "Send To Publish" notifications for a content page. When an editor updates the content of this page and hits "Save and send for approval" button, then only 1 admin(user with smaller userId) receives notification e-mail and the other doesn't. I have tried this with multiple smtp servers and the same result.

Umbraco version 7.5.7 assembly: 1.0.6219.11990

**Comment by kjac** [comment] 2018-10-28 20:17
Heads up! This is a symptom of a general bug in the notifications. This can happen to any notification in case someone only signs up for one specific notification and others have signed up for the same notification (not necessarily exclusively).

It's caused by the `i++` in [this line](https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Core/Services/NotificationService.cs#L101) should have been placed inside the body of `while` instead of as part of the clause. 

I'll submit a PR shortly.

**Comment by nul800sebastiaan** [comment] 2018-10-30 10:17
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3468

**Closed by nul800sebastiaan** 2018-10-30 10:17 UTC
