### ISSUE TITLE
Upload of image via media picker auto-select last media item

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9276] opened 2020-10-26 16:34 UTC
When uploading an image via media picker it seems to auto-select an image, which is fine. However it seems to select the last image/media item in the folder instead of the new uploaded image.

I am seing this in Umbraco v8.8.0

**Comment by nul800sebastiaan** [comment] 2020-11-03 09:43
Is the last item not the uploaded image?

**Comment by bjarnef** [comment] 2020-11-03 09:58
No, it isn't :)

The Umbraco Cloud project has beeing upgraded to v8.8.1
I have tried a few examples, but could reproduce it now, strange 🙈

**Comment by nul800sebastiaan** [comment] 2020-11-05 11:16
You mean you could NOT reproduce it any more, right? 😉

I'll close this for now, if we have a good repro for this then we should have a look at it but for now let's assume it was a fluke. 🙈

**Closed by nul800sebastiaan** 2020-11-05 11:16 UTC
Labels: state/needs-more-info
